[quote.epigraph, , Mark 14:8]
____
She hath done what she could.
____

== Preface

The preparation of the following selection from the
correspondence of our late dear friend,
Lydia Ann Barclay,
has been undertaken with an undoubting belief of
its being a duty to hand forth to the present generation,
and to posterity,
these records of the exercises and labours of our
departed friend and sister in the unchangeable truth.

The largest proportion of them has been supplied by her correspondents,
who were friends to whom she was closely united in Christian fellowship,
and who have willingly surrendered them for the benefit of others.

Whilst occupied in fulfilling the service devolving upon us,
we have been favoured with a precious feeling of peace,
and not unfrequently with the sweet incomes of our heavenly Father`'s love,
melting our hearts, and causing the tribute of gratitude and praise to ascend before Him.

We have felt concerned to be faithful in the fulfilment of our trust,
with a single eye to the glory of Him by whose grace our friend
was what she was--desiring neither to withhold more than is meet,
which tendeth to poverty, nor, by undue enlargement,
to exceed the bounds of a wise discretion;
and we earnestly hope that our readers may be prepared to
receive that which is written in the love of the truth,
to their own abiding instruction and deepening in Christ, the root of life.

We have, therefore, endeavoured, without compromise of the principles, doctrines,
and testimonies professed by us,
to select such of the letters of our departed friend as would render
the whole a true delineation of her religious views and experience;
and it is earnestly desired, that (in this day of conflict and of great perplexity,
and treading down within our borders,
because of the falling away of many from the ancient standard,
and the persevering efforts of an untiring enemy
to drive us back into the house of bondage,
out of which our forefathers were delivered by an Almighty Arm) the deep, practical,
heart-searching character of these letters,
may lead many amongst us to search and try their ways,
honestly inquiring of themselves what they know of such deep experience; and, also,
that it may tend to the confirming of the faith of those who,
seeing the ravages the enemy has made amongst us, may often be ready to query,
"`What is truth?`"

Our beloved friend left but few private memoranda of her religious experience;
but the little there is shows the purified state of her mind.
She left a few drafts of letters; and the following paper being found with them,
is felt by those into whose hands they have come to increase their responsibility:--

[.embedded-content-document.paper]
--

In preserving these rough drafts of letters, written under exercise of mind,
I desire to be preserved from boasting,
or seeking to make a fair show in the flesh (as it were),
knowing that in my flesh dwelleth no good thing;
"`But by the grace of God I am what I am,`" and that,
if His grace bestowed upon me has not been in vain,
it is all of His adorable love and mercy in Christ Jesus my Lord.
But my whole and sincere desire is, that,
if in the perusal of these papers by any when I am gone to rest,
the pure mind may be stirred up,
or that which is tender or of God in them strengthened--"`that
the abundant grace may through +++[+++their]
thanksgiving, redound to the glory of God,`" the fountain of all good,
and the centre of all true worship and praise.
Amen.

[.signed-section-context-close]
Cockermouth, 1862.

--
