== Chapter III

To +++_______+++.

Croydon, 24th of 2nd Month, 1834.

My Dear Friend,

Thy dear sister +++_______+++ having kindly and confidentially
read to me some part of thy last letter to her,
could not fail to introduce me into a degree of affectionate
sympathy with thee in thy present new (and,
may I not say, in some respects, trying?) allotment.
Ah! my dear friend,
there is much temptation to a warm and grateful disposition in the hospitality,
and kindness, and appearance of love of our friends,
especially to one lately come amongst them in a way to interest so many;
and such may be easily taken therewith, and led away from the quiet habitation,
where the mind is drawn off from all that is gratifying to our selfish nature,
and is prepared to hear the "`still, small voice`" of the Beloved,
teaching as never man taught, and leading into all that is excellent and pure; and,
may I not also say, where ability is mercifully given,
humbly to make a stand against all that is contrary to His precious leading and teaching,
however plausibly it may be decked out.

I was grieved to hear what thou describes as a weekly custom with certain Friends,
and yet it is no more than one quite expects in this backsliding day;
and no doubt thou hears much more that is trying discussed in your various circles.
But oh, my dear friend, let none of these things move thee,
or tempt thee out of the stillness where alone God is known and felt to be God,
and exalted over all that is of the creature!
I do not expect thou wilt find it thy place to sanction the thing by going to them.
I would not touch what I doubt of;
and no matter at all whether thou art able to answer their reasonings,
be content to be unable to do so, and to be thought a fool.
"`Study to be quiet, and to do thy own business.`"
It is enough for thee if thou feels the gentle,
withholding pressure of the Divine hand upon thee,
and in obedience to what is manifested, thy soul shall live;
for "`the Lord preserveth the simple`" and "`the faithful,`"
and in times of pinching trial and close besetment,
"`the name of the Lord`" will ever be "`a strong tower,`"
into which the righteous (or faithful) may run and be safe.
And, dear friend, I do also believe,
that in thy faithfulness the hands of others will be strengthened,
and who knows but a secret doubt may be thereby raised in others also on the subject?
and then they will bless the Lord on thy account.
I cannot but believe it is the enemy`'s work to hurry
into creaturely activity--he hates flesh to be quiet,
because then he cannot act.
Oh, how easy is it to mistake his imitations for the leadings
of God`'s Spirit! but (as dear Isaac Penington says),
in that which lies low in the pure fear is the preservation.
Surely the enemy cannot imitate the annihilation of true quiet; but there, in the light,
he is seen in all his approaches and successfully resisted.
It is indeed a precious thing to have unity with that blessed
Power that makes and keeps self of no reputation.
My soul most earnestly covets it for myself and for my dear friends.
I expect thou wilt find it best to keep much at home, and not to go from house to house;
and it is easier to begin cautiously, and not to open the door too wide at first,
for a torrent rushes on irresistibly, almost before we are aware,
and carries us off our feet.

It is nearly thirteen years ago since I was at +++_______+++,
so that there is almost a new generation risen.
No doubt it would be a comfort if there were one or two
whom thou couldst feel really united to in all respects;
but, alas! it is a day in which we can hardly trust a brother,
or put confidence in a friend whom we have looked on as a sound member.
But oh, "`it is better to trust in the Lord, than to put confidence in man,
even in the princes of the people.`"
Truly He "`is more excellent than the mountains of prey,`" and there is
none like unto Him or to His faithfulness round about Him;
therefore, let us lean upon Him, however much He humbles us, and love to hear His voice,
however much He reproves us, for it is the voice of love;
and verily His love is better than wine or any outward stimulant!
Whilst I write, I remember the dear Friends at +++_______+++,
whom I think thou wilt be pleased with.
I do not know them outwardly, but feel united to them in spirit--may I not say,
in the bond of Gospel love?
I hope you will occasionally go and see such as are in solitary situations
like them--there are many I believe in +++_______+++ (or +++_______+++) monthly meeting.
It will be refreshing to you and them,
and I think we often receive help ourselves in such little sacrifices,
comparable to the cup of cold water.
I have often thought the twenty-fifth chapter of Matthew (the latter part) very instructive,
taken in this point of view--I mean as to little
alms-deeds (spiritually) of various kinds.

Perhaps +++_______+++ has told thee we have had an acceptable
visit from dear +++_______+++ and +++_______+++ +++_______+++ to our families;
of course they were my guests, which was pleasant; but, I may own,
I was much taken up whilst they were here in beholding and fearing
the many snares to those who put their hand to the Gospel plough.
I assure thee, dear +++_______+++,
although I may try to do my little best to encourage another fellow-pilgrim,
I am often ready to halt and look back myself; yet, at times,
I desire to trust still in Him who has hitherto helped,
and to commit my all into His good hand, who will humble and correct in wisdom and love;
and oh! that nothing on my part may hinder His perfecting
that which He hath in mercy begun,
to His own praise and to the utter abasement of the creature forever.
Farewell affectionately.
I remain thy sincerely attached friend,

L+++.+++ A. Barclay.

To Hannah Marsh

23rd of 6th Month, 1834.

I can truly say,
it is my earnest desire that nothing may move forward but that living power,
freshly poured forth, which is the foundation and spring of true Gospel ministry.
And oh! that nothing may hinder or hold back,
but that all may be brought into humble subjection, the creature abased,
and the Creator alone exalted, and His blessed name magnified forever.

Farewell, dear friend.
Crave my preservation on every side,
and that such gracious condescension and long-suffering may be
answered by humble faithfulness and close watchfulness on my part.

L+++.+++ A. Barclay.

To +++_______+++.

+++_______+++, 1834.

My Dear +++_______+++,

I hardly feel easy to omit telling thee how very sorry I
was to hear of the step thou art about to take,
in resigning that which has cost thee some sacrifices to obtain,
and to make an open profession of, which I do believe was precious to thee,
inasmuch as solid peace and satisfaction was the result.
And now, dear +++_______+++, I would affectionately query, Who has beguiled thee,
or what has hindered that thou shouldst not obey the truth,
and follow on to know more and more of the precious leadings of the Lord,
who is "`the way, the truth,
and the life`"--even to know of the increase of His
holy "`government and peace`" in thy heart?
Hast thou not professed to believe in Christ,
in His inward and spiritual appearance in the soul,
according to what He declared by His servant John formerly--"`Behold,
I stand at the door, and knock; if any man hear my voice, and open the door,
I will come in to him, and will sup with him, and he with me?`"
And dost thou now seek to be made perfect by that which is outward,
and to subject thyself to ordinances which are but shadows
of the good things which Christ brings home to the heart,
in its faithful admission of, and subjection to His power inwardly manifested?
Oh! my dear friend, I can testify from my own (most unworthy) experience,
that there is indeed a rich supper prepared for those
who love Christ in His inward and spiritual appearance,
and are subject to Him.
They are, at seasons,
permitted to partake of that bread of God which comes down from heaven,
and gives life unto the world; yea, they feel that they live by Him,
and He giveth them of the new wine of His kingdom!

This is surely better than all the shadows of the thing!
And so, also, when the knockings of Christ`'s Spirit are attended to,
and the government of our hearts is placed, as it were, on His shoulders,
He doth baptise us with the "`one baptism`" of the Holy Ghost,
which is "`not the putting away of the filth of the flesh,
but the answer of a good conscience toward God,`" by the
cleansing of the thoughts and intents of the heart;
and thus we know a being "`baptised into Jesus Christ,`" a being "`buried
with Him by baptism into death,`" and a putting on of Him;
and experience abundant ability to "`walk in newness of life.`"
Hast thou, dear +++_______+++, read Barclay`'s Apology on this subject, and Elisha Bates?
But, above all, I would entreat thee to retire in spirit before the Lord,
and beg of Him to enlighten thy eyes to see that which belongs
to thy peace--that which will give thee solid comfort in pursuing.
I fear the unfaithfulness and deadness of many of
us have proved a stumbling block in thy way;
but oh! look not to the people, but to the unchangeable principle and power of truth,
which is abundantly able to direct and preserve, though we, from unfaithfulness,
may fall away from it.
I think I may say,
it is my full belief that none ever left the principles professed by our Society,
but such as either never really possessed them, or else,
through unfaithfulness or unwatchfulness, fell away from them.

And now, my dear friend, I would, in conclusion, say,
that it is my sincere and earnest desire that thou mayest so entirely
give up to be led and instructed by the Light and Spirit of Christ,
as that thou mayest be favoured to experience somewhat
of that precious fellowship mentioned in 1 John chap.
i.,
in which there is a holy communion partaken of that
far surpasses all outward signs and shadows!
I believe I need not ask thee to excuse my freedom; I think it is the freedom of love,
and that thou wilt as such accept it, and believe me to remain, thy sincere friend,

L+++.+++ A. Barclay.

P+++.+++ S.--I hope I write "`not as though I had already attained,
either were already perfect,`" but under a deep sense of
the unmerited and adorable mercy of my heavenly Father,
by whose free grace I am what I am; and, in the constrainings of His love,
I would not hide what He hath prepared for those who love Him, but would say, Come,
taste and see how good He is!

To +++_______+++.

Tunbridge Wells, 7th of 8th Month, 1834.

My Beloved Friend,

I fear thou hast thought me very neglectful of thy last kind and sisterly letter,
supposing that I have plenty of leisure for writing,
and perhaps I have appeared almost unfeeling,
or as if I did not share deeply with thy feelings of sorrow,
under the loss of such a dear friend and mother in Israel.
This has, I assure thee, not been the case;
for there have been times when it has been greatly felt,
as well as the reflection how very few of the old veterans (in the Lamb`'s army,
may I not say?) and experienced judges in Israel are left behind.
Shall I be thought judging if I say,
there are few comparatively that have not shaken hands more or less with the world,
that are men of truth, hating covetousness, clear in discerning,
and bold in testifying against what is not of the truth, discreet and tender,
yet faithful in reproving and warning?
In short, the fathers--where are they?
and the true prophets--do they live forever?
Ah! my dear friend, let their precepts and example live in our remembrance,
and may their good Master and great Pattern rule and reign in our hearts!
They directed us to Him, and they testified of His goodness and of His mighty power;
and now, if we have been favoured in any measure to taste thereof,
let us more and more desire and seek after that spiritual nourishment,
whereby we may be enabled to grow up into Him in all things, and to be built up in Him,
a spiritual house and holy priesthood,
to offer up the spiritual sacrifices which are acceptable through Him.
Is He not elect and precious to us, as the chief corner-stone,
though always despised and disallowed of the wise builders in every age?
and oh! that we may be preserved from grieving or going
away from Him by disobedience to His Spirit in our hearts.
He only hath the words of eternal life! and though the mountains should depart,
and the many helps, like hills, be removed, yet His kindness and peace,
and His instructions of life, shall not be taken away from His humble little ones,
who keep close to Him, and abide faithful in His fear.

It is a subject, as thou sayest,
that we should be careful not too much to dwell upon--the strippings in our poor Society,
and the inroads of the enemy--lest discouragement and dismay should overwhelm,
and our hearts should faint from rising up to do, with the little might and sight given,
that which belongs to our day`'s work; and by this means,
the general weakness is helped forward instead of hindered.
I often remember a passage in that sweet chapter, the second of Ecclesiasticus,
viz:--"`Woe unto him that is fainthearted, for he believeth not;
therefore shall he not be defended.`"
Is it not the case, that these fainthearted overlook, or do not yield to,
the Lord`'s mighty, strengthening power, and therefore are not likely to be helped?

The few particulars thou gave me of dear +++_______+++ and +++_______+++, and of the interment,
were very interesting to me, and I felt it kind of thee.
Ah! my dear,
I can fully sympathise with thee in the feelings of condemnation thou describes:
but how tenderly indeed are we dealt with, in that we should again be proved,
and our backsliding passed by.
Yet, do we not find that every act of disobedience dims the sight,
and weakens the ability to give up to the next apprehended requiring,
so that sometimes we have a dreary wilderness to
pass over before the effects are done away?
But let us endeavour to keep the word of the Lord`'s patience, till He say,
"`It is enough!`" let us bear His chastisement and the hidings of His power,
till He is pleased renewedly to wash,
and once again to re-anoint for what He shall appoint unto.
I noticed thy kind wish that we lived nearer each other; ah!
I fear I should stumble thee, and not strengthen thee.
I feel peculiarly united to thee, I will confess;
yet I hope that near attachment to thee, or any other,
would not lead me to fix in a place where the Divine
approbation did not rest on the movement.
I do not consider +++_______+++ as a very fixed place of residence,
although I should be sorry to let such an idea out, or to give too much way to it myself,
lest there should be a snare in so doing.
I often think, the more detached we are from earthly comforts and dependencies,
the more we are as sojourners, the better.
I miss dear +++_______+++ greatly, and have been tried in various ways the last two months,
so as latterly to be ready at times to give up hope,
yet have been mercifully preserved from utterly sinking,
and enabled to commit myself into His hand, who humbleth, and correcteth,
and instructeth according to His tender love and unerring wisdom.
The more we are melted, the more likely we are to be made up again tender,
so as to take the impression designed.

I am stopping here with +++_______+++ till next week,
and intend then going to Hastings for a fortnight, for a little sea bathing,
and hoping the change may be beneficial, not to health (for that is very good,
through favour), but to the mind,
as a season of renewed searching of heart and seeking
after fresh strength to walk more circumspectly,
faithfully, and humbly; may it be blessed to me is my earnest desire.
We have had nice accounts of dear +++_______+++, which are animating and comforting,
to see how those who feel their great weakness are mercifully
helped to be made strong in the Lord`'s might.

Farewell very affectionately,

L+++.+++ A. Barclay.

To Hannah Marsh

Hastings, 25th of 8th Month, 1834.

I would shrink gladly out of sight from fear of undoing
in conversation what is feebly attempted to be done in meeting.
I have been thinking, whilst writing,
of the sea of glass mingled with fire--is there not such a comparison?
how true it is!
Ah! there is no safety but in keeping close to Him
who is mighty to preserve as well as to strengthen.
How prone are some of us fainthearted ones to sink
down into despair at the sight of the slippery path,
instead of clinging more closely to Him!
Is not this something of unmortified self that would be strong in itself,
and does not like to see its own utter nothingness?
Ah, my dear friend, let us commit our way unto Him who is good and faithful,
in well-doing, that is,
in close watchfulness and humble faithfulness--and then He will bring it to pass,
that is, our safe stepping, to our own peace and to the praise of His great name,
who hath touched, and drawn, and made willing to follow.

I hope my dear friend, Hannah Marsh,
does not suffer the enemy by any discouraging feelings
to rob her of the good penny (as George Fox says);
but oh, for diligence when the good Master calls, and a humble watching thereunto;
otherwise I have thought (whether rightly or not I cannot
tell) we may not clearly see the pointing of His finger,
or may miss of His heavenly words.
How do I long for my dear friends of this description,
that they may more and more seek after and experience the
cleansing and qualifying efficacy of His living word,^
footnote:[John 15]
that they may be as clean and empty vessels,
ready for His use whenever He is mercifully pleased to bid! and
then I have thought that conduct and conversation would accord,
and be hardly less edifying or teaching.

It is now time for my afternoon`'s sit on the shore--the sea is grandly high,
most majestic waves!
Now, dear H., I must say farewell.
Do not think I am got stronger every way.
Oh, I am tremblingly weak, yet desiring to pursue, in the right fear,
the prize set before us.

L+++.+++ A. Barclay.

To+++_______+++.

Croydon, 15th of 9th Month, 1834.

My mind seemed much with you yesterday week,
and I hope you were favoured with the presence of
Him whose power and wisdom are the alone authority,
strength, and comfort, of all these our meetings for discipline.
I have from a child (almost) felt greatly interested in the transaction of the discipline,
and secretly exercised in these meetings; but now I am so deaf,
I can take almost no active part in them, were I able; so that I often think,
if I may but be enabled to breathe after the arising of the pure life,
both in myself and in others, this is all the part I can take;
and oh! to be helped to do so more and more.
After I returned home,
I had a bitter draught of inward discouragement and
outward depression to partake of for some days;
it seemed like the waves of the sea, one after another.
But, through adorable mercy, I have been helped out of it the last few days,
and have indeed cause to praise His good name, and to say,
It is good to lean upon His tender arm through all--yea,
it is He who giveth power to do so; He worketh in us to will as He wills,
and to do that which is well-pleasing in His sight.
I had a humbling testimony to bear yesterday in our preparative meeting,
on the subject of the second query, which I hope may be long remembered by me,
and I have been favoured to feel a peaceful retrospect; so I hope the anticipated (and,
in part, partaken of) storm is changed to a calm.
Oh! that nothing on my part may ruffle the waters!

We attended a meeting in town last fifth day, held at E. Bates`'s request,
for Friends of our quarterly meeting.
Dear Sarah Grubb was there, whom I could not but eagerly and affectionately salute,
not expecting to see much more of her in these parts--she is going to Hereford,
and Worcestershire, and Wales, with certificate.
I found that she and I coincided in our feelings
about the meetings--yet I hardly dare say how,
even to thee.
Dear R. H. is about to embark on the 24th, and is perhaps gone from London by this time.
The morning meeting would be likely to give him the usual certificate.

My dear brother John is returned to us with comfort, I trust, however poor,
and to our comfort too.^
footnote:[From a religious engagement in Cornwall, etc.]
He visited dear William Byrd, whom he found much brighter than he expected,
though entirely unable to move from the position in which he is placed,
either night or day.

My love, please, to all your little circle, and to thy brother,
to whom I did not bid farewell.
If it be not presumptuous in such a child to say so, may you be preserved faithful,
and watchful, and humble; and then you will, no doubt, be blessed of the Lord,
even of Him who made heaven and earth.
Many eyes are upon you, some for good, and, it may be, some for evil,
and they are quick-sighted; oh! that yours may be single to the recompense of the reward,
despising the shame, for His service is truly enriching, and it is perfect freedom.

Farewell, my dear friend and sister.
I hope thou wilt not shrink from yielding up thyself
even to be brought again under exercise.
I fear lest the good, and acceptable, and perfect will should not be accomplished.
But what great need have I to look at home.
May all within us be humbled and brought to nought (no matter how),
to entire resignation and submission!
May we be melted and made tender,
even just such as our heavenly Father would have us to be,
that He alone may be glorified forevermore!
Do write before long.
I am thy truly sympathising and nearly united friend,

L+++.+++ A. Barclay.

To I. E.

+++_______+++, 1834.

My Dear Friend,

I accept the kind intention of thy note; but oh!
I would rather thou took no notice of the poor instrument,
in whatever way she is enabled to hand any thing in season,
but rather may thy heart bow low before Him who is the great Giver.
He it is thou knowest who gives to feel sympathy,
and who puts words into our hearts for others,
and He it is who enables to hand outwardly also.
It is all of His goodness and free love; therefore,
let both of our hearts bow in gratitude and humble praise to Him alone,
who only is worthy of all our praise, and thanksgiving, and love; yea,
and He is worthy of the pure,
undivided service of our hearts--worthy forever to be trusted in, feared, and obeyed.
And, dear friend, let me add,
He is a never-failing help in the time of trouble
to those who fear Him and lean upon Him alone.
"`God is a refuge for us,`" therefore "`trust in Him at all times; ye people,
pour out your heart before Him.`"
Surely we may pour out to Him with safety, and cast all our care upon Him,
for He doth care for those who endeavour to walk uprightly before Him,
and when they may be ready to think that no eye seeth them, God pitieth them.
He doth not afflict willingly, but for a wise, and good, and gracious purpose,
even to draw us closer to Himself,
the fountain of good--to incite us more and more to love Him with a perfect heart,
to trust in Him alone and not lean to our own understandings,
and to serve Him more faithfully and willingly.
In all His dealings towards us (though we can hardly sometimes be persuaded
to think so) He doth prove Himself to be a wise and tender Father,
waiting long upon some of us to be gracious to us, and desiring we should come, taste,
and see how good He is!

Therefore, how desirable, my dear friend,
is it that we should seek after that wisdom by which
we may be enabled to hear the Lord`'s voice to us,
and to see His name or power manifested in His various dealings towards us!
Then shall we be strengthened to hear or mind the rod (if such should be administered),
and who hath appointed it, and what He is requiring at our hands.^
footnote:[See Micah 5]
And then, I have thought,
we shall be preserved from fainting or sinking too
low under the chastening of His hand on the one hand,
or from despising it on the other, remembering that whom the Lord loveth He chasteneth,
and proveth even with scourging the sons whom He receiveth.^
footnote:[Heb. 12]
And again, "`As many as I love I rebuke and chasten.`"
How striking too is what follows^
footnote:[Rev. 2:19-20]--the precious effects of hearing His voice,
and receiving Him in the way of His coming.
Ah, He doth sustain these from day to day,
through whatever He permits and whatever He requires.
They have bread fresh from the Master`'s table,
and His love is better than wine or outward stimulants and helps.

Give my love to thy wife; I feel much for her;
but how sweet to remember and feel that the Minister
of ministers is ever nigh by His blessed Spirit,
to minister spiritual instruction, and life, and nourishment,
to lead us in the way we should go, and to strengthen and comfort us therein,
if we will but wait for, seek after, and attend to Him.
The preciousness of our views on this subject is peculiarly felt
by those who are solitarily situated by sickness or otherwise.

L+++.+++ A. Barclay.

To R. R.

Croydon, 14th of 10th Month, 1834.

This morning, in our little retirement,
I felt instructed in remembering that unless we are
willing to go down as to the bottom of Jordan,
we shall not be enabled to bring up stones of memorial, and to say,
"`the Lord is my strength and song,
and He is become my salvation,`" delivering from
the proud waves that lifted up their heads on high.
I entirely united with thy remarks on our state as a Society.
Oh! for an increase of quietness and abasedness of the creature,
that He alone may rule and reign in us and amongst us, and work all in us,
and have the praise of all, whose right alone it is!
And then, I believe, when self is still, even in its fears and foreboding cogitations,
as well as its wise reasonings and hasty actings,
the Lord our God will be truly exalted in our earthly hearts,
and He will mercifully enable us to see and to perform our
individual work and service (whether actively or passively),
and thus to exalt His name before others.^
footnote:[See Ps. 46:10]

+++[+++There are]
comfortable accounts from dear Stephen Grellet from his own home; also of Daniel Wheeler,
who held several satisfactory meetings at Rio Janeiro, South America, and we heard,
that after he left,
prayers were put up by the congregation for his welfare and preservation;
they were much reached, and said that "`he spoke with authority,
and not as the scribes.`"

Thy desire for my encouragement felt cause for humbling gratitude;
I have but once broken through the host of discouraging reasonings here.
Oh! the compassionate forbearance of Him who has begun to show me of His great goodness,
and who knows the desire of my heart to be His only, His wholly.
Crave my preservation, dear R., when it is well with thee,
for I often feel weighed down under a sense of the many snares and dangers on every side.
Yet I know the Lord`'s arm is mighty; may He help me to cleave close to Him,
to lean upon Him, and never to leave Him,
and then He will not forsake me in the needful time.

Farewell.
With dear love, I remain thy nearly united friend,

L+++.+++ A. Barclay.

To +++_______+++.

My Dear Friend,

I have felt since quarterly meeting an inclination to pen thee a few lines,
which has been increased since hearing, the other day,
that thou hast been appointed to the station of overseer in your large meeting,
in which thou hast my tender sympathy; for it must, indeed,
be an awfully responsible station to fill,
although one of great use and blessing to the Church.
I feel greatly for such in the compass of our quarterly meeting, at the present day;
now that we have (many of us) so greatly degenerated from our original view of
being "`members one of another,`" and have got out into an independent view,
out of the true love and the unity of the Spirit.
These ideas have tended to deteriorate the station amongst us,
and to hinder the benefit of it; as well as to discourage,
and to render it trying to the sincere-hearted who
desire to come up in faithfulness to their duty.
But, dear +++_______+++, I would do my little best to encourage and animate thee,
however weak and unfit thou mayest believe and feel thyself to be,
not to look out at what others do or how they feel about it;
but do thou turn thy attention inward to the measure of
the light and grace of Christ mercifully given within.
He is head of the body, the Church,
and His light and grace are abundantly sufficient to direct, and lead,
and strengthen His poor feeble servants, in whatever way He requires their service.
Do thou meditate in the law and precepts of His blessed Spirit continually,
and thou wilt be given clearly to see what is the proper qualification,
as well as what is proper for thee to do and to leave undone.

Thou mayest be often ready to think that thou hast enough
to do to attend to the vineyard of thy own heart and family;
but let not the feeling of thy own weakness and shortcomings
hinder thee from yielding to that Power which can cleanse,
as well as strengthen, which can abilitate to follow, as well as enlighten and lead.
And if thou yieldest thereto (even art willing to be shown what is required of thee,
and the high standard thou must press up to),
He will lead thee to seek after great watchfulness before God,
that thou mayest not slip in thy duty,
or give offence to any of the little ones by thy example;
and He will lead thee into the humble fear and pure love of God,
which will keep thee from the fear of man,
as well as in the true love of thy dear fellow-members.
And in this love consists the proper discharge of the duty of an
overseer--to feel the value of the souls of our dear sisters,
to watch over them for their good and growth,
and therein to act in the meekness of the heavenly wisdom,
which Christ is ever willing to dispense to them that seek after it.
And in seeking after the help of others, thou wilt be helped thyself,
and kept humble and watchful.

I would also affectionately and tenderly say,
be careful that thy example in the bringing up of thy children is consistent with,
and adorns the Gospel--that is, that it is such as "`the power of God`" leads into;
and then, dear +++_______+++,
His power will assuredly bear thee up over all the thoughts of others,
and the reasonings and fears of thy own mind.
And the Lord will ever give strength to His people;
He will bless them with a peace which the world can neither give nor take away.
I hope thou wilt receive this free salutation in the sisterly love in which it is written.
I have often remembered the time we passed together at F., three or four years ago,
and the love and interest I felt then for thee are not abated by time and separation.
At the same time,
I desire renewedly to be made sensible of my own great weakness and shortcoming,
and the great and continual need I have of the preserving power, and strengthening grace,
and cleansing virtue of Him whom I do desire to serve in sincerity,
and to love as the only Beloved of my soul, the chief among ten thousand!

L+++.+++ A. Barclay.

To E. H.

10th Month, 1834.

My Dear +++_______+++,

I do not like to let the present opportunity slip without penning thee a line or two,
expressive of the sympathy I feel with thee,
as well as the rejoicing in that thou hast been enabled to yield
to the good Hand in tender condescension laid upon thee.
I did feel greatly for thee, dear, and thy example felt instructive and animating to me.
Ah! how long have some of us been waited upon,
and our great weakness and hesitation borne with,
and how tenderly have we been dealt with, and again and again visited.
So it may tend to thy comfort to know that a weak
sister feels animated afresh by thy example,
to look back on the great goodness and mercy extended, and upward,
with earnest desire to be enabled to come up in more faithful obedience
to Him who indeed proves Himself to be a tender Father,
a rich rewarder of those who endeavour, however feebly, to serve Him.
He makes willing, and He works the obedience; let us yield up to His power,
however humbling and crucifying to the creaturely wisdom and will,
and He will graciously lead about and instruct, correct and humble,
as His tender love and wisdom see best.
Let us lean upon Him, and cleave close to Him more and more; and then, I do believe,
He will not forsake us in the hour of trial and deep conflict.
He can still enable a little one to put to flight
a host of reasonings and opposing feelings,
and can cause those who feel themselves as the stones
of the street to celebrate His praise!

Farewell, my dear friend,

L+++.+++ A. Barclay.

P+++.+++ S.--I hope I have not improperly intruded myself on thee.
We have cause to remember the refreshing meeting we were favoured with on fourth day,
and may He have the praise and pure service of our hearts, who alone is worthy forever.

To +++_______+++.

Croydon, 19th of 11th Month, 1834.

My Dear Friend,

Thy short letter was felt kind and acceptable, and seemed to bring thee nearer to me.
It is very pleasant to have these tokens of the remembrance
and feeling of our dear absent friends,
to be thus brought nigh in sympathy,
and to be mutually refreshed in looking at and adoring the dealings of
an all-wise and gracious Providence towards His little dependent ones,
wherever scattered or however tried.
Yes!
He is indeed good to His Israel, His upright-hearted, clean-handed little ones.
His eye is for good upon them that fear Him,
in all His dealings towards them--He chooses them
in the furnace of affliction--He numbers their tears,
though scattered ever so secretly,
and their desires after Him and the honour of His name are had in remembrance before Him.
He will be their "`refuge and strength,
a very present help in trouble;`" and though the
earth (all that is earthly in them) may be shaken,
and the mountains (those whom they have looked to for strength and support,
as instruments) may be removed; though the sea roar,
and the proud waves may lift up their heads apparently
to overwhelm them--yet He is near to them,
and His voice is mightier than the noise of many waters; He is near to hear their cry,
and to save them; He is more than father or mother, and sticketh closer than a brother;
and He will hold them in the hollow of His hand,
and give them to see and partake of that river which maketh glad His whole heritage--yea,
He will cause them to shout for His mightiness and glory in the midst of them!
Then, oh! "`let Israel hope in the Lord from henceforth and forever.`"

We were privileged in having the company of dear +++_______+++ and +++_______+++
as my guests for a few nights about a fortnight ago.
It was truly a refreshing and strengthening time.
I had never seen so much of her before,
and her conversation was peculiarly helpful to us at the present time.
She had also never had any of +++_______+++`'s company,
and it seemed a comfort to her to find that both
his and my feelings were so similar to her own.
Surely there is a help sometimes in kindred minds thus speaking one to another,
although their communings may have much of the mournful in them,
and though they may be sad under a sense of the state of
things amongst us (a highly favoured yet backsliding people),
and of the insidious snares of our cruel enemy.
If such are but preserved in the Divine fear on such occasions,
and are engaged to think on His name--His mighty power--will
He not notice their tears and their sincere desires?
and He hath promised "`they shall be mine`" "`in that day when I make up my jewels,
and I will spare them,`" etc.
Oh, my dear friend (I have been thinking), that we may be of the number of these jewels,
of the number of those who are spared of the Lord, who, we read of in another part,
were those who sighed and mourned for the abominations committed in the land.
Let us be willing to be of these oppressed, suffering ones,
for assuredly those who suffer with their Lord shall reign with Him.

We hear agreeable accounts of +++_______+++. He is one
of those who hold up the ancient principles of truth,
which is a comfort to hear.
I fear +++_______+++ has got his view beclouded; many looked much towards him,
hoping he would set us all to rights, but I fear they have been sadly disappointed.
It will not do to look to or lean upon man; but oh! let us look to Christ,
our divine Master, who teaches us still by His Spirit as never man taught,
speaking with undoubted authority in our hearts,
and is a swift witness against all that is evil in ourselves and others,
if we will but give heed and believe His testimony.
But the thing is, we do not like His cross; we would have some easier way to the crown,
and so we say in our hearts, we will not have Him to reign over us;
and then slaying the witness, we become hard and blind,
and call light darkness and darkness light.

L+++.+++ A. Barclay.

To Lydia S.

Croydon, 10th of 12th Month, 1834.

I have been intending to write this day or two past,
and now that we have the affecting account of dear Edward Smith`'s decease,
it seems a fresh stimulus to take up my pen in the way of sympathy with thee, dear Lydia;
for I do not doubt it is a near stroke to thee (or you)
as well as to our little circle of intimates here,
with whom he has formed a precious link in the chain of endeared friendship and fellowship.
Ah, my beloved friend, it is indeed a keen stroke, as well as a solemn warning!
I felt him as a dear brother nearly united in the fellowship of the Gospel.
Well, his work is cut short in righteousness.
I do believe his prayers, and his alms,
and his secret tears and conflicts are had in remembrance
before Him whom he desired to serve above all,
and his memorial is blessed, and his works shall follow him.
How greatly will you miss him in your meeting!
It is very striking to me how faithful he has endeavoured
to be lately in the writing way;
as it were, making haste to do his day`'s work in the daytime.
We have been much pleased with the opportunity these
labours have afforded us of seeing him down here,
and dear C. and I have been looking back with much affecting interest
at the two last visits he paid us--I think also once when thou wast here,
and we took a sweet walk together.

Poor dear Eliza! how tenderly do we feel for her!
How sudden a stroke to her! yet it is inflicted by a most tender and wise Father;
and I believe the wind will be tempered to the shorn sheep--the soothing balm of His
consolation will be poured in--and His tender arm will be underneath to support.
And will she not have cause to rejoice that she had such a sacrifice to yield up to Him,
who will cause all things to work together for good to those who
love Him above all--who wounds only to heal--who strips only to
clothe with the pure garment of love and entire resignation?
Ah! in all His dealings towards us He doth show himself
to be very good--a wise and tender Father;
and all His provings are designed to draw us nearer to Himself,
the fountain of excellence and good; to mold us more and more after His Divine image,
that we may bear the inscription of holiness to Him.
May the language of her heart be, "`The Lord gave, and the Lord hath taken away;
blessed be the name of the Lord;`" and He will care for His stripped ones,
He will be tender over them, for they are precious to Him, and,
as their eye is ever unto Him, He will not fail or forsake them.

On hearing of this circumstance, the first impression was rejoicing with the departed,
and longing, if it might be, to follow; yet, dear Lydia,
I cannot help fearing this desire may, in some degree,
arise from an impure source--a shrinking from conflict and trial in this changing,
proving scene; and one is, as it were, reproved for the wish,
and brought back to the feeling--the will of the Lord be done,
let Him do what He will with His unworthy handmaid.
Should many days, and many trials, and exercises, and labours be appointed,
may the desire of my heart be, to be made resigned, and faithful, and humble.
It is affecting to lose a beloved brother and contemporary, but this is what thou, and I,
and others, must expect to do now;
and oh! that it may work the good designed by the trial, namely,
to stimulate and warn to diligence in the work of the day assigned us,
that we may be found ready, watching, and faithful.
If thou should be going to see dear Eliza,
do give C.`'s and my dear love and tender sympathy for her.
Perhaps it may be as well if thou read to her what I have written,
though it is not said to her, it is for her as much as thee,
for I feel you united together.

Well, dear Lydia, to turn from this absorbing subject to thy letter of 10th month, which,
on perusing a third time now, is felt to be more acceptable than I had felt it before,
although it was not unacceptable then by any means;
but there are (as thou sayest in it) times when we feel unable
to lay hold of the hand of help or encouragement held out to us.
This has been peculiarly my case since we parted--a time of stripping, of buffeting,
and of sore conflict, more than I have known for some time past;
but I suppose those who would be faithful soldiers of the Lamb must endure hardness;
and perhaps it is part of the many baptisms they must pass through, who are, at any time,
to be made use of in pulling down the strongholds of Satan in others.
The enemy attacks such much more inveterately,
as well as that they must be more often cleansed, more deeply plunged,
to be qualified for such an awful work.
Well, my dear friend,
though at times one seems ready to shrink from these necessary baptisms,
and rather to desire to be hid to be known only to One,
if so His will might be performed;
yet at others one seems melted under a sense of His
goodness and condescension to one so unworthy,
and the desire is raised that nothing may be spared,
that so His gracious designs may be accomplished;
that not a jot of suffering may be lost, but patience may have her perfect work,
that nothing may be wanting that may tend to the abasement and purification of the creature,
and to the glory of the Creator!

I notice thy allusion to taking the cup of salvation in any form;
this comes rather +++[+++home], having apprehended such an awful requiring lately; but oh,
the dread, and fear, and reasonings, and hesitation, and disobedience!
Yet I have trusted that He who knows the desire to be rightly directed, led,
and strengthened in so awful an exercise, has forgiven the offence; and,
in matchless mercy, He has condescended to put a little testimony in my mouth,
even since such a hesitation, after a long time of cessation.

It would be very pleasant to have thy company again here, dear Lydia.
I often remember the sweet walk we took, the morning thou left, up Primrose Hill.
It will not do to cling to earthly helps and enjoyments;
but yet it is a time when we have need to endeavour to strengthen one
another`'s hands in upholding the standard once delivered to our forefathers,
and which is still precious to many up and down, though others turn their backs,
and do not consider it to have been anointed of our Captain.

L+++.+++ A. Barclay.

To E. R.

Croydon, 29th of 12th Month, 1834.

It is good to be continually reminded that we must lean only upon
the One Good Friend who "`sticketh closer than a brother.`"
And how greatly do I desire that the present time may be blessed to us,
in our becoming increasingly acquainted with Him, His precious ways,
the mightiness of His power,
and the wisdom and love portrayed in all His works and dealings!
Well, my dear friend,
you must not look to escape what is come already upon others to try them; but oh,
that you may be enabled to set an example to them of the
benefit of faithful watchers and diligent labourers;
for surely one is ready to think if this had been the case in other parts,
things would not have come to their present painful state amongst us.

I have had lately a sweet letter from dear +++_______+++,
in which he desires his dear love to those dear Friends in the
West who are faithful in advocating our ancient principles.
He writes encouragingly as to brighter times,
that a remnant will be raised up and preserved of the humble, lowly ones,
who shall be made strong in the Lord`'s might; that He will gain a victory by these few,
and the wisdom and activity of man shall be abased
in the very dust and the Lord alone exalted.
Ah, we are sadly degenerated in our ideas on this subject as well as others,
which seem to me all as branches from one root,
namely the denying the precious universal gift of Divine light and grace.
It is true some appear to own it, but then they act and preach to the contrary,
and there is a sad endeavour to unite the two opinions,
and make things appear all the same, covering all over with love and harmony;
but it is like trying to unite the iron and clay in Nebuchadnezzar`'s image,
and it is better not to be in harmony with what militates against the
spiritual (and truly Gospel) view of things which we have always held.
True love will lead to judge what is contrary to Christ, the Light,
and to seek the recovery of the lost member even by severity, if need be.

I was much pleased to hear of your meeting being continued,
and hope it will tend to good,
though no doubt +++_______+++ and thou must feel the responsibility to be great.
But it will not do to shrink from burdens, if rightly come upon us,
and you will be strengthened for it.
We want more of a noble disinterestedness amongst us sadly in these parts,
that the cause of truth may be precious to us, and not a shrinking from exercise.
It is very sweet to hear of the dear blind man and
others being drawn near in spirit to us.
One can salute them in Gospel love, though outwardly unknown.
Many eyes are upon you, and you are as a city set on a hill that cannot be hid.
May your lamps be so continually replenished with heavenly
oil as that they may shine with unsullied brightness,
to the glory of the great Name and to the help of many a poor wandering soul.

I have been much interested and instructed during the past year
in making an Index to Isaac Penington`'s Works in Four Volumes,
and have just completed it after much labour on it.
Of course, I read the whole carefully, and condensed each paragraph.
I intend presenting a copy to my dear Cornish Friends who have the Works,
and shall not forget thy sister L., who I believe has them.
My dear love to them and tender sympathy in their trials.

L+++.+++ A. Barclay.

To L. S.

Croydon, 19th of 2nd Month, 1835.

My Beloved Friend,

I seem as if I could hardly let thee go into the
West without a few lines by F. J. (if he be at Wandsworth),
expressive of the rejoicing that I feel on thy account,
as well as the tender sympathy with thee,
since hearing for certain what passed at your last monthly meeting.
Ah! dear love, I do indeed feel for thee under the awful, and, may I not say,
humbling exaltation that is come upon thee, the increase of exercise and responsibility.
But thy good Master, the great Minister, will ever be with His poor, exercised, and,
peculiarly in this day, tribulated ministers;
He will be their strength in weakness--His good presence will be
with them in the many fiery trials that must be their portion,
to prove them and to purify them--His mighty arm shall be
underneath them when passing through the deep waters,
to bear them up from utterly sinking,
when the mighty waves may roll over their heads--and He will not
fail or forsake them when He leads them forth to the battle,
but will gird them with His own strength, and hold them as by the hand, saying,
"`Fear not; for I am with thee.`"

Well, my precious sister, I would fain do my little best to encourage thee.
Ah! it is no matter how poor, and weak, and foolish, we seem to ourselves or others.
We want some of the plough-boy preachers of old times in these degenerate days;
oh! for the baptising ministry of those times.
I sometimes think, if things are brought about amongst us,
that there will be again raised up mean and contemptible
instruments and a foolish way of preaching,
as in old times, that the Lord alone may be exalted.
And, blessed forever be His name, He is abundantly able to qualify these poor, mean,
foolish ones, as ever He was; to make them wise in His counsels and mighty in His power;
yea, to enable them to preach His everlasting Gospel with the Holy Ghost,
as it was in the beginning, that He alone may be glorified,
and His name exalted and spread among the nations.
May it be so, saith my very soul;
and may all flesh be silent and abased before Him forever!

Farewell.
With C.`'s and my united dear love, I remain thy poor, frail,
but affectionate and sympathising friend and sister,

L+++.+++ A. Barclay.

Croydon, 20th of 2nd Month, 1835.

The enclosed +++[+++the preceding letter]
was hastily written yesterday, whilst waiting for the fly to take us to monthly meeting,
and not finding F. J. there, I do not feel quite excused from sending it thee,
as perhaps there may be a time when even what is
hardly equal to a cup of cold water may be acceptable.
We had a few women Friends of the committee yesterday,
who stirred us up to take up the subject of overseers,
to the relief of some burdened minds, I do believe.
M+++.+++ P. has been paying us a little visit, very pleasantly,
and I think one might say helpfully,
for those who feel themselves but poor and weak may sometimes help the poor and weak!
I had long felt about going to Reigate monthly meeting,
and I was glad of the opportunity of (without selfishness) taking her and, on fourth day,
to it; and we were favoured with a sweet day altogether,
except a little burden I brought away from the second meeting, from fear, as usual.
The first meeting was very sweet; a precious covering in silence, much of the meeting.
Ah! this is what we want now-a-days, and what the true ministers covet,
and not to be heard--even the Lord`'s power reigning over all,
and being exalted over all in our earthly hearts, through an inward stillness,
whereby He may be livingly known to be God,
and an ability received to glorify His holy name before others.
^
footnote:[Ps. 46:10] Dear Joseph Sayers laid before
Friends the visiting of families in that monthly meeting.
We were glad to be there,
and I believe the company of my two dear companions was felt helpful.
We spent the afternoon with dear +++_______+++,
who seems more helpless than when I last saw her, a year ago,
but more resigned to wait her dismissal from this suffering state.

Do give my dear love to F. J.; I think I feel the same towards him, on this occasion,
as I do towards thee,
as I have expressed in the enclosed note.. Ah! we have few true elders
amongst us--those who have been baptised by the Holy Ghost for the service;
surely it is such only who are properly qualified to watch over the ministry,
to warn and to reprove, as well as to strengthen the weak!
And where there are those who have been thus anointed by Christ, our holy head,
for such (or any other) service, if they are not appointed thereto by their friends,
I believe it tends greatly to their own loss as individuals,
as well as to the loss and injury of the body.
I have often remembered, in looking at the subject of elders,
the description of those appointed in Moses`' time--"`able men, such as fear God,
men of truth, hating covetousness.`"
Ah! these are such as we want in the present day greatly; clean-handed, honest-hearted,
true to God, and the glory and spreading of His great name;
in nowise yielding to what will not tend to this excellent end, but rather hinder it,
however smooth and eloquent the words, and fair the doctrine (for thou knowest, dear L.,
how it may be so, as we were reading the other day, and as we have often felt).
And there is a covetousness which must indeed be hated by those
who desire above all to fear God--a covetousness of the esteem
and favour even of those whom we look upon as princes.
Is not this something like the Babylonish garment, and the wedge of gold, which,
being concealed, brought dimness of sight and led to faint-heartedness formerly,
so that the enemy prevailed to the discomfiture of Israel?
Ah!
I have thought that the Lord`'s gracious, tender hand is upon some in present day,
to allure them even into the wilderness, away from creaturely dependencies, and,
it may be, closely proved various ways;
and there He will speak comfortably unto such as
are willing to offer up these coveted things,
yea, will make the Valley of Achor a door of hope,
and give them to behold the vineyard they are to be engaged in,
and abundant ability to labour therein!

Well, I do believe dear F. has been so anointed, and is one of these honest-hearted;
and I greatly desire (if it be not impertinent in me to express it) that he may ever
be preserved so--that his sight may be kept clear for God (I desire to write with reverence),
and his hands strengthened in the power of His might to act for Him,
which will be greatly to the help of the body, to his own peace,
and to the praise of that excellent Name which we desire should be exalted over all.
And one is impressed, whilst writing,
with one great means of this being the case (and
this applies to both ministers and elders!) namely,
to be very frequent in inward retirement and waiting upon God,
in the silence of all flesh, or, at least, seeking after it!
Here we shall be more and more instructed in the knowledge of ourselves, and,
consequently, in that of others, as well as in the living knowledge of God;
here is the way for true discernment to increase amongst us as it was in the beginning,
as well as strength to act according to that discernment.
One longs for this, though, indeed, I have need to lay my mouth in the dust,
feeling very deficient in this, alas! as well as in other duties.

Well, dear L., farewell once more.
I did not by any means intend to enlarge thus when I began, but I knew not how to stop.
Perhaps it might not be wrong to show this to dear F., if not impertinent in such a child.
I hope he will deal faithfully with me, if it be so, tell him,
and at all other times also.
With the salutation of endeared love,
I remain thy and your nearly united friend--may I add, in the bonds of the Gospel.

L+++.+++ A. Barclay.
