== Chapter VIII

[.letter-heading]
To +++_______+++

[.signed-section-context-open]
2nd Month, 1840.

[.salutation]
My Dear Friend,

This morning when I awoke my mind seemed introduced into exercise on thy behalf,
in consequence, as I apprehend, of hearing yesterday that thou wast brushing-up at home,
in preparation for a new dear partner;
and a desire arose in me that thou might be careful
how thou in any wise yielded to do _aught_ which,
in seasons of tenderness and stillness,
thou wouldst feel the testimony of truth to witness secretly against.
Oh, how have I longed that thou might increasingly become a strong man for God,
valiant for the truth in the station and allotment in which thou stands;
and that this prospected union (though I do not know thy
dear friend) might be instrumental to this good work,
and not in any wise weaken or tie thy hands; and in order that it may be so, oh,
keep inward, and watchful,
and close to what thou feels of and from God in the secret of thy soul.
Here lies thy sure guidance in the way wherein thou shouldst go, to bring glory to Him;
here lies thy abundant strength to walk humbly therein,
in a clear and bright testimony for Him, and in a faithful working for Him,
both in taking heed to thyself and to the flock whom thou art given to oversee;
and here lies thy preservation, both _from_ that which would defile or draw aside,
and in the true feeling and tenderness, life and fruitfulness,
where His peace and blessing will rest upon thee and thine,
and praise resound to Him continually in thy heart and house.
So wisheth and prayeth thy very sincere friend,

[.signed-section-signature]
L+++.+++ A. Barclay.

[.postscript]
====

P+++.+++ S.--I saw no way of expressing this little word of tender caution today when we met,
yet felt afraid of withholding it in the faithfulness of true love; and hope I shall not,
in the least degree, be wounding, rather encouraging, that which is good,
though unworthily.

====

[.letter-heading]
To A. F.

[.signed-section-context-open]
Reigate, 1st of 4th Month, 1840.

[.salutation]
My Dear Friend,

I enclose thee a copy of a little tract I have felt it my duty to have printed,
whilst time is permitted me here, to revive the memory of primitive faithfulness,
and as a little testimony to that gracious Power who enables
unto faithfulness and crowns with overflowing peace.
She +++[+++Lydia Lancaster]
was a relation of ours, and after whom I was named,
and when I showed it to dear Thomas Shillito twelve years ago,
he much encouraged and urged me to print it then, and, indeed,
he procured for me the epistle to young Friends.
I hoped and believed that my dear brother John would have
put it into a volume of his [.book-title]#Series on Women Labourers,#
but he is now gone to his rest, so I thought I had better no longer bury it in oblivion,
and have had a small edition,
just to present to and circulate among my friends in this way.
Please lend it among your Friends as thou feels best.
I hope I am not intrusive, believing it will be encouraging to some of our dear Friends,
who are advancing down the hill of life, as well as instructive to the younger.

Our dear friend, John F. Marsh, has been lately engaged, accompanied by his wife Hannah,
in sitting in the families of a number of his neighbours at Croydon,
both rich and gay and the more straitened and serious minded.
Is not this an excellent concern?
I can truly say my heart went with him.
They have been kindly received by all, and some sweet visits they had.
Is not this encouraging?
Late in the autumn dear Hannah Marsh and I were united together
in a similar visit throughout the families of their monthly meeting,
in which we were mercifully helped to get a morsel of bread,
in endeavouring to do what we believed to be our good Master`'s will.
But oh! it is a trying time for the poor weak labourers;
it is no wonder that their bodily frames should be weighed down
under the sense of the state of things in our highly favoured,
but sadly backsliding Society.

And you have not been without your trials,
and truly grievous it is that the enemy should so far prevail
as to draw aside those who have been faithful standard-bearers,
so as even to render them obnoxious to that very discipline
which once they uprightly endeavoured to uphold.
Oh! he is the same crooked serpent that ever he was,
and where he cannot tempt to improper fear and shrinking,
he will to the haste and activity and brittleness of the creature,
which can never do the Lord`'s work, but mars it.
But oh, my dear friend,
I cannot but believe that those among you who occupy the place of fathers
and mothers in your church have cause to look well to _themselves,_
whether anything lies at their door in respect to these trying things,
whether there has been a faithful cleaving to the pure testimony of truth,
and a noble eschewing of all covetousness, of various kinds,
whereby a true feeling of the mind of Truth is attained,
a true discernment of the precious from the vile given,
and an ability received to act accordingly _for_ the truth and not _against_ it.
I trust I shall not be misunderstood in thus expressing
my feeling on what has greatly exercised my mind often,
in this quiet spot.

I have greatly enjoyed, with fresh instruction, Joseph Pike`'s life, this winter.
How strikingly adapted to present times are his two epistles!

[.signed-section-closing]
I remain, with love, thy sincere friend,

[.signed-section-signature]
L+++.+++ A. Barclay.

[.letter-heading]
To +++_______+++

[.signed-section-context-open]
4th Month, 1840.

[.salutation]
My Dear Friends,

I believe I must acknowledge to you that I came away burdened from you yesterday,
having much wished for a little quiet after dinner;
but the conversation was so kept up until I was obliged to leave,
and now I do not feel easy without taking up my pen,
desiring that in reading what may follow,
you will endeavour to gather your minds inward to the faithful
witness for God that so you may receive the good that is designed.
The language that ran through me at dinner-time,
and also at meeting--but it was not to be uttered there--was this passage of scripture,
"`The Lord`'s voice crieth to the city, and the man of wisdom will see thy name;
hear ye the rod and who hath appointed it.`"
My dear friends,
I have tenderly sympathised with you in the recent loss you have sustained,
although I was not with you on the day of publicly showing it,
believing that "`it is a grief`" and a keen stroke, especially to dear +++_______+++,
whose affectionate companion dear +++_______+++ had been principally the last two years.
Oh, may you hear the language of this afflictive rod or stroke,
and Him who hath appointed it in love unspeakable and tender mercy to your never-dying
souls--for surely all the Lord`'s strokes and pinching dealings towards us,
as well as His more conspicuous blessings,
have a voice of love and a speech of instruction in them,
and He intends good to us in them--for He doth not
willingly afflict or grieve the children of men.
It is of His tender compassion that we are not consumed,
that His hand was not laid upon _us,_
but He gives _us_ a little longer time to prove our love to
Him whilst He lays His hand upon a dear companion,
to touch us to the heart,
and to give us another tender yet powerful call that pierces us as to the quick!

Oh, then, that you may be so wise as to see His name, His power,
the putting forth of His hand of love, that so you may prove that you hear His rod,
His stroke, by obeying His call to seek His favour above all,
to give Him your whole heart!
David said, "`I entreated thy favour with my whole heart; I thought on my ways,
and turned my feet unto thy testimonies; I made haste,
and delayed not to keep thy commandments`"--so may the Lord`'s peace-giving,
life-giving favour be your most earnest and heartfelt search,
more than any worldly treasure or favour of man;
may you now make haste and search into all your ways, yea,
beg of the Lord to search you thoroughly by His pure light,
to try your heart by His faithful witness, the word nigh in the heart and mouth,
and to lead your feet and incline your heart unto the testimonies of His blessed
Spirit that calls and testifies to you there in the secret of your heart;
and then when you hear, oh delay not, shrink not, fear not to keep all His holy commands,
and to attend to all His restraints,
for durable riches and a crown of glory will He then give you!

And, my dear sisters,
I believe I must tell you faithfully how surprised and grieved I was to see you apparently
so soon forget your loss and the awful sight which you witnessed so recently!
I fear lest you should in any wise be endeavouring to drive
off reflection and to divert from serious feeling.
Oh, my dear sisters, and brothers too, rather than this should be the case,
how do I long that you may yield to that power that visits you,
that brings seriousness over your minds, yea,
that would check the vacant laugh or the light conversation that
has a tendency to draw you away from a sense of the Divine presence.
Oh, cherish the tendering impressions of your heavenly Father`'s love,
that so you may reap the benefit indeed which He intends in this afflictive stroke,
otherwise you may render it necessary for Him to stretch out His hand still!

[.signed-section-closing]
With true love, I remain, etc.,

[.signed-section-signature]
L+++.+++ A. Barclay.

[.letter-heading]
To R. R.

[.signed-section-context-open]
Reigate, 25th of 4th Month, 1840.

&hellip;Well, I _do_ trust that I love dearly the true-hearted, faithful brethren,
if this be a mark of having some degree of life;
and whether these have opportunity of outward intercourse or no,
they are as lively epistles written in one another`'s hearts;
tending to one another`'s comfort and strengthening,
and speaking forth the praises of Him whose grace hath made them what they are,
and daily upholds and preserves them,
though now (as formerly was the experience of the faithful), for the Lord`'s season,
if need be,
they may be in heaviness through manifold afflictions
and temptations for the trial of their faith,
chiefly from the sight and sense given them of what the
Lord requires of those who profess His blessed truth.
And how far--how _very_ far--behind the professors thereof are in
coming up faithfully according to the pure testimony of His Spirit!
And when I have looked at some of us who thus go mourning on our way,
having often sackcloth as on our loins, out of sight (except, perhaps,
disclosed to a few _who can understand_ our speech), I have felt an exercise on my mind,
and a desire that, in the midst of mourning,
we may "`remember the days of old,`" meditate on
all the Lord`'s wonderful and gracious works,
even on the mightiness of His power, and therefore stretch forth our hands unto Him,
thirsting for Him as a thirsty land, waiting for His counsel, for His humbling,
for His strengthening unto all patience and faithfulness to the very end.
Oh, may we increasingly lean on Him without anxiety, for it is His work,
and He will take care of His own dear Church,
and He will keep her true children as the apple of the eye.
Oh! the preciousness, the peaceful quietude, yea,
the powerfulness of that state of unity with the Divine will, when the true worship,
the true amen rules over all the trials and tribulations, so that nothing is a surprisal,
nothing too hard, yet the language of heavenly love is breathed,
"`Gather them if it please thee, O most Mighty.`"
May I be brought more and more into this state by _any_ means,
is the earnest desire of my soul.

I rejoice with thee in believing that the blessed truth shall prevail over all error,
light over darkness, life over death,
as there is a keeping close to Him who hath all power, yea,
who is of power to thoroughly purify the daughter of Zion,
even to purge away all her _reprobate silver,_ as well as her tin and her dross.
And in seasons of such solemn yet joyful contemplation, how do praises fill, yea,
resound from the temple of the heart unto Him that sitteth upon the throne,
and unto His dear Lamb that washeth and taketh away the sin of the faithful!

[.signed-section-signature]
L+++.+++ A. Barclay.

[.letter-heading]
To +++_______+++

[.signed-section-context-open]
5th Month, 1840.

[.salutation]
My Dear +++_______+++,

I believe I had best acknowledge that a feeling of earnest
and affectionate solicitude has attended my mind,
on your behalf, for several months past, which I have not known how to throw off,
and now last evening, as we sat up stairs after tea,
it seemed afresh to revive with strength,
so that it seemed to me best to endeavour to relieve my mind in this way.
I have looked upon these two affecting circumstances which
have occurred within a week`'s time in our little meeting,
as solemn warnings for you (as well as others),
whilst endeavouring to be diligent in business,
and to "`provide things honest in the sight of all men,`" to be also "`fervent in spirit,
serving the Lord,`" and thus to prepare to meet your God,
whether His summons be sent suddenly or not.

It is not from a desire to be forward in giving advice,
or to be intermeddling in other men`'s matters,
but from the view of the awful station in which I stand (most unworthily,
I know) as a steward, and the need to be faithful therein,
in order that I may be clear of the blood of all,
that I venture to acknowledge that I have long,
especially since your increase of business lately,
felt earnestly solicitous (as if it were my own self) that you might be
so _deeply_ sensible of the _responsibility_ of your present circumstances,
as that you might be scrupulously anxious that all your expenses and way of living,
the bringing up of your children,
and your whole ideas may be brought and kept in the closest manner,
that there might be an abstaining from even every appearance of evil,
that is from the desire of an appearance which you
cannot call consistent with a borrowed capital.
I would not wound, my dear friends, I assure you my heart would be tried to do so,
for I have deeply and very _tenderly_ sympathised with you under your many trials--but
I have a very _high_ sense of the importance and responsibility of borrowing,
and I do believe the danger is very great of the mind, by use,
losing this high sense and this tenderness of feeling on this subject,
unless the avenues thereto are closely guarded;
and thus persons are apt to get almost imperceptibly
into the use of many things which might be spared,
and out of that _scrupulous_ economy which would be desirable;
and thus difficulties may grow and impure methods be resorted to,
which may bring reproach on the blessed cause of truth which we profess,
and discomfort and pain to others around, as in poor +++_______+++`'s case.

But, my dear friends, if you mind and consult the Spirit of truth,
the faithful witness for God in the secret of every one of our hearts,
then you will not fail to be continually kept in
this high sense and tender feeling I have described;
you will be led into scrupulous economy and self-denial in all things,
in order that you may be just and honest towards all,
both "`in the _sight of the Lord_ and in the sight of men;`" and whilst engaged to be
diligent and "`not slothful in business,`" you will be preserved "`fervent in spirit,
serving the Lord`" with your whole heart and with your whole soul,
doing all things as to Him and not to men,
to gain their favour and to make a fair show in the flesh,
but eyeing the Lord at all times with _grateful, faithful_ hearts;
for _truly how_ has He brought you up as from a pit of distress!
and has He not promised that if you would mind His warning call,
and yield to His hand of power that has touched you again and again,
that then He would bless you again.
But oh, my dear friends, let Him bring you down in yourselves and break you to pieces,
and then you will be made up again tender, and faithful, and grateful, and just,
and humble; and, walking in His fear and in His counsel and might,
your example will shine as a light,
you will gather others to His blessed truth instead of scattering in _any_ wise,
and you will, through His mercy and love in Christ Jesus,
be prepared to obey His awful summons whenever served,
to give an account of your stewardship, to your own unspeakable and everlasting peace,
and the glory of God most high!

I hope you will read this in the fear of the Lord,
and then I know you will feel the love which constrains me to write it,
and I trust you will receive it in that love,
and then we shall be melted together in humble gratitude
before Him who causes us to love one another,
and to give and receive a word of faithful and affectionate warning.

[.signed-section-signature]
L+++.+++ A. Barclay.

[.letter-heading]
To Hannah Marsh

[.signed-section-context-open]
Leamington, 3rd of 6th Month, 1840.

I know +++_______+++ feels what the Dr says me, but thou knowest, dear Hannah,
this is nothing new to me,
and all my desire is to be mercifully preparing for the
summons to a much better home and heavenly country,
where I have often longed to be,
and latterly at some favoured seasons have been permitted,
in adorable goodness and condescension,
to feel an unspeakably precious union and fellowship with the just of many generations,
even, as it were, an union with their song.

[.signed-section-signature]
L+++.+++ A. Barclay.

[.letter-heading]
To +++_______+++

[.signed-section-context-open]
Reigate, 22nd of 6th Month, 1840.

[.salutation]
My Dear Friend,

I do not like to wait longer than a convenient opportunity
without at least beginning a letter to thee,
to show thee that it is not _out of sight, out of mind_ with me; nay,
I have often mentally visited thee in thy comparatively solitary situation,
and cannot but trust and believe that though trials
and depressing seasons may greatly abound,
yet that heavenly consolation and help is also mercifully extended, yea,
abounds sufficiently for thee, although thou mayest at seasons think hardly so,
or be hardly sensible thereof as thou couldst wish.
This reminds me of a sweet verse in J. Fisher`'s Diary:--

[verse]
____
Not to my wish, but to my want,
Do thou thy gifts supply;
Unasked, what good thou knowest, grant,
What ill, though asked, deny.
____

Oh! the sweet leaning of the childlike nature upon its Father,
which brings down the blessing of preservation--the
blessing of all things working together for good!
And this reminds me of a sweet instructive expression in
a letter which I saw lately of dear +++_______+++`'s to a Friend,
where, after alluding to the decease of my dear brother John,
and speaking of Him who is able to raise up others to supply the places of those
He removes from the militant Church to the Church triumphant in heaven,
he goes on somewhat in this way--"`and whether He sees good to suffer
His Church below to be driven again into the wilderness for a time,
or whether He will not altogether,
becomes not so much matter of importance to His servants, and to His handmaidens,
as to be found doing _no more nor less_ than He requires at their hands.`"
How excellent is this, how does it show the faithful, patient,
humble leaning of the true servant and handmaid, on Him who hath all power,
whose work it is and who will ever take care of His own dear Church.

In +++_______+++`'s letter,
he acknowledges a fear to withhold what has been
the fruit of deep bought and valuable experience;
at the same time _expatiates_ on the need of bearing with and yielding to one another,
where there is a difference of sentiment even in the highest matters.
Such is human weakness both spiritually and rationally, that we cannot see eye to eye, etc.
I told him in answer that I united with his remarks to a _certain extent;_
that we have need to get down deep away from creaturely reasoning,
and expediency and fear, as well as from creaturely zeal and activity,
and there to endeavour to feel what is consistent with the mind of truth,
what tends to advance the blessed truth,
and what would be likely to hinder or lessen the testimony thereof,
and that if this be the case with certain individuals
who are endeavouring to arrive at a true judgment,
I believe, though they may be of various growths and temperaments,
and not see exactly eye to eye in everything, yet that they will see _similarly,_
for they will all see as with the eye of truth,
and if there should be one of them that sees totally oppositely,
there will be a willingness to bear and yield, in so far as this;
a waiting and seeking still further to be clear as to the sense or mind
of truth--if _that_ sense be according to the view of the one,
then let all yield to that, but if it be according to the view of the many,
then let their view stand.

This sentiment of seemed to me to savour of modern
ideas that are so prevalent amongst us,
which under a plea of forbearance and charity,
lead to shrinking and winking at wrong things,
and would do away with simple faithfulness, and an honest, yet humble pleading for truth,
and I thought too it _trenched_ upon the _sufficiency_ of Divine
guidance under the plausible cover of a modest fear.

[.signed-section-closing]
With dear love, I remain thy friend sincerely,

[.signed-section-signature]
L+++.+++ A. Barclay.

[.letter-heading]
To +++_______+++

[.signed-section-context-open]
21st of 7th Month, 1840.

Thine to me was comforting.
We understand one another`'s speech,
and can enter into sisterly feeling one with another; and this is strengthening.
We enjoyed the beautiful ride to much; we could get no beds anywhere there,
the town being full of soldiers, and hardly any room to get our tea in.
However, we went to the select meeting.
It was a fearful time to thy poor weak friend,
but I was mercifully enabled to cast off my burden by reminding
Friends of +++_______+++`'s communication at the select yearly meeting,
and signifying how I had felt exercised under a belief that it was applicable to some,
and that in consequence harm had arisen to some of our beloved youth,
who had got thereby to desire and admire fine eloquent speeches,
that were mere sound without substance;
and even I feared to the going to hear such orators in their
chapels--that we must look and see what we were about,
for that if we opened the door but an inch, our young folks would push it wide open,
and then we should find a difficulty to bring it to again, etc.

The meeting next morning was exercising,
by reason of the waters being muddled by a mixture, but our dear friends,
+++_______+++ and +++_______+++, were instrumental to the clearance again.

Went on First day to +++_______+++ meeting, according to the pointing in my mind.
I felt it a sweet and strengthening time to me in much silence.
After a long time,
dear +++______+++ supplicated sweetly (and strikingly to my mind)
that what we might have communicated might be humbly received,
and sink deep, etc.
Afterwards +++______+++ had a few words, but my time was not fully come.
I trust I was preserved in patient,
humble waiting till after the epistle was read--and whilst it was reading,
the fire waxed hotter and hotter,
and it seemed shown me that I must stand up pretty
soon after it (lest they might break up the meeting),
and remain a little time in silence till my tongue was loosed;
and my good Master gave me faith and made me obedient,
and enabled me to relieve my mind fully to the young
people on going to other places of Worship,
and on the proper state of mind in worship, in which they should attend our own meetings, etc.

Oh, the great and gracious condescension to such a poor worm of the earth.
May I never refuse to obey so good a Master in the least thing again!
I should not have entered so into particulars, which may even savour of boasting,
but I thought it would encourage thee too, dear, to lean upon His good and mighty arm,
who can make way for His poor little ones where they can see none,
and out of weakness make them strong in His might.
Glory to His name forever, who only is worthy to be faithfully served,
humbly worshipped, entirely trusted in, and livingly praised!

[.signed-section-signature]
L+++.+++ A. Barclay.

[.letter-heading]
To +++_______+++

[.signed-section-context-open]
7th Month, 1840.

[.salutation]
My Dear Young Friend,

The sight of thy circulars has revived a feeling of concern on thy account,
which attended my mind last second day,
in hearing that thou intended adding jewellery to thy stock;
and I can hardly do otherwise than,
in the sincerity of true love and affectionate solicitude for thy best welfare,
express my earnest desire that thou mayest now, on thy first setting out in business,
_ponder_ the path of thy feet,
even seeking after Divine counsel to direct thy movements and bound thy inclinations;
thus shall all thy ways be ordered aright in the Divine fear,
and thy goings be established in the Divine peace and blessing.

I know thou hast been engaged in a business where the Friend had jewellery,
and the mind often by habit loses its susceptibility of the pure testimony of truth,
and becomes accustomed gradually to what the Spirit of truth would really testify against;
and then it is very natural, on beginning a business,
to fear that unless we accommodate our stock to others`' views,
we shall be in danger of losing some profit--and thus by giving way in little things,
dimness of sight and weakness of hands creeps almost imperceptibly over us,
so that we may be ready to answer that we do not see any objection to this or that,
or do not feel this or that required of us.
But, my dear brother,
this is a temptation of the enemy to rob us of that purity of sight and feeling,
and strength of action and example, which would contribute to our own great peace,
the help of others around, and the glory of God;
and this enemy will bring many plausible reasons to effect his purpose,
but he was a liar from the beginning, and abode not in the truth,
don`'t thou hearken to him nor be his servant,
but follow the testimony of the Spirit of Christ in the secret of thy heart;
and if thou art but simple and resigned enough,
He will give thee to see where thou shouldst draw the line between what is useful and
what is merely ornamental for the decking out these poor bodies to please the vain mind.
It is best to begin well,
for it is harder work afterwards to alter--and I feel it a serious thing for
a member of our highly professing Society to open a fresh business in our town,
and it behooves such to look well to the example or
testimony they are setting before their neighbours,
for we are very narrowly looked at by others,
who know what we ought to be (even lights in the world),
and believe that a consistent faithful walk is the way to
get respect and credit amongst all around us,
and will be a means of gathering others to Christ the truth,
instead of scattering from Him and serving the enemy, which a contrary conduct will do.

And so, my dear friend, as a faithful elder sister,
I would beg of thee not to be hasty in anything,
but to covet and seek after the inward pointings of truth,
and not shrink from them in this matter,
and then let nothing hinder thee from going simply and _nobly_ forward, fearing nothing,
and heeding not what others say or how they do,
and then I believe thou wilt reap the hundred-fold
for any little sacrifice thou mayest make,
even in this life, and be blessed of Him who can (thou well knowest) bless the little,
where there is a humble trust in a faithful walk before Him,
and who can also blast the much, where there is a yielding to our own understanding,
fear, or inclinations.
Oh, mayest thou indeed, by a faithful humble walk,
come up to the help of the Lord`'s cause in our little town and meeting;
so wilt thou be a strength, and comfort, and joy, to the exercised minds amongst us,
instead of any grief, and, dear +++_______+++, verily thou shalt be fed,
be abundantly blessed here, and have an enduring treasure hereafter in heaven.

[.signed-section-signature]
L+++.+++ A. Barclay.

[.letter-heading]
To John G. Sargent

[.signed-section-context-open]
3rd of 9th Month, 1840.

[.salutation]
My Dear Young Friend,

Thy aunt kindly let me see a part of a letter of thine,
describing thy appearing before an _earthly_ judge, which interested me much, and,
I may say,
melted my heart under a sense of the Lord`'s goodness to one of His dear visited children,
in taking away the fear of man,
and enabling to stand firm to the pure testimony of the unchangeable truth.
Oh! may we increasingly, in the feeling of His love and tender goodness,
yield up our hearts wholly unto Him, that He may lead us about, and instruct us,
and subject us under whatever He may be pleased to
require at our hands or to restrain us from.
Oh! how precious are these dealings and workings of His;
His "`works`" of grace as well as of creation truly "`are great,`"^
footnote:[Ps. 111]
past finding out or comprehending by the natural, unregenerate man;
but wonderful and precious, and as such "`sought out,`" continually observed,
and yielded unto by the humble, meek ones, who, indeed, "`have pleasure therein.`"
To these He will show the power thereof,
and overcome all their enemies--these experience that He is "`gracious
and full of compassion,`" that He is near to support,
to "`give meat unto them that fear Him,`" and that He will ever be "`mindful
of His covenant,`" that "`His commandments are sure`" and safe,
and "`stand fast forever,`" yea, that the work of His grace is honourable and glorious,
bringing redemption unto His people that yield unto Him,
making them truly honourable and crowning them with glory.
Oh! then, let us cast ourselves as into the hand of His power or grace,
that He may break us to pieces continually in ourselves,
and bring us to nothing as to our own willings, runnings,
or devices--that He may mold us as He will,
and raise up His own pure life into dominion over all,
and thereby prepare our hearts as an habitation for His holiness.

God setteth the solitary in families, and He biddeth such to remember Abraham,
the father of the faithful--"`for I called Him _alone,_
and blessed and increased him;`" so, my dear brother,
if thou art careful to walk in the footsteps of faithful Abraham,
thou mayest be instrumental to gather families unto the Lord,
even in that apparently desolate and benighted spot--for faithfulness leads to fruitfulness.
Oh! it doth spread a sweet savour and a substantial life all around,
whereby many may be helped and the Lord glorified,
even though it be in the midst of fiery trials.^
footnote:[Isa. 24:15]
Therefore faint not, neither let in discouragement, because thou hast no outward helper;
for the Lord thus proves thee in tender love,
that thou mayest look to none or lean on none but Him alone,
who is all-sufficient to make the weak strong, and a little one as a strong nation,
and a feeble one as David valiant for the truth,
even to run through a troop of fears and to leap over a wall of difficulties,
and to stand firm upon the Rock of Ages,
and to know the goings established in the unchangeable truth,
and the new song of praise put into the mouth, unto Him the strength and Redeemer.

The present is not a time to look out to any for help or example;
for all are not Jews that say they are or appear to be--all are
not so united by subjection to Christ the blessed truth (even knowing
Him in their inward parts) as to have the mind of truth,
and so to be preserved from doing anything against the truth.^
footnote:[2 Cor. 13:8]
These not being faithful to the true light which shineth in the secret of the heart,
however plausible they may appear, are but in the twilight,
and cannot stand up for nor uphold the pure dispensation of the Gospel,
which is that of the Son in Spirit, therefore they are not trusty waymarks.
Oh, then, the need for us to dwell deep,
to be frequent and fervent in an inward exercise,
and waiting before the Lord in the silence of all flesh!
It is here that the faithful of all ages have had
their strength renewed and vision cleared;
it is here that a true knowledge of ourselves is
given--and we can never too well know our own weakness,
and nothingness, and natural vileness,
and the more we know of ourselves the better we shall be able to feel and discern others;
and here it is, in this lowly, humble, patient state,
that the Lord delights to reveal of the mysteries of His kingdom,
to ordain strength and to perfect His praise,
even out of the mouths of His babes and sucklings.
Therefore may we, my dear friend,
increasingly gather into this quiet habitation and place of true prayer,
keeping out of all our own willings, and runnings, and haste,
and then the blessed Spirit of Christ will arise and give
a clear testimony and a certain evidence of its own self,
and as we join in with the lowly appearance thereof, in the obedience of the true faith,
it will give not only strength but seal peace to the obedient.

Farewell.
With sincere desires for thy, as for my own, preservation in faithfulness, watchfulness,
and deep humility, I remain, etc.,

[.signed-section-signature]
L+++.+++ A. Barclay.

[.letter-heading]
To Hannah Marsh

[.signed-section-context-open]
Margate, 19th of 9th Month, 1840.

[.salutation]
My Dear Hannah,

Having an hour`'s leisure at C. W.`'s where I lodge, I thought I would begin,
if not able to finish a letter to thee.
I hope, my dear friends, you have thought of me hereaway,
and breathed for my help and preservation,
for no one I think has greater need of the prayers of the faithful,
and no one could have come out more poor, and empty, and blind, and stripped,
on such an errand!
Thou wouldst hear we stopped a few hours at Croydon,
and were refreshed by thy husband`'s kindness and company.
We proceeded to London in the afternoon,
and called on J. and M. Peirson for an hour before tea, which we took at J. Burtt`'s,
and lodged there.
It was affecting to see poor +++_______+++ come in,
and it brought humbling instruction to my mind.
J+++.+++ B. saw me into the Folkestone coach.
I had a painful ride to Ashford, as relates to the poor body, but, through favour,
was helped in mind, which having been stripped and brought low, was now clothed,
as it were, with exercise towards the dear Kentish Friends,
as I drew near them outwardly.

Dear Hannah, it was the "`cottage of peace and content`" I went to,
and felt it a comfortable resting place; dear Letitia Hagger, like a dear sister,
so kind and tender.
The two meetings at Ashford were times of exercise and relief to me;
I could truly say I had been or "`was brought low, and the Lord helped me.`"
The time between meetings I passed quietly with L. H., and went to tea at E. J.`'s;
had a little time with her,
and also with her little boy and with the young man in the shop next morning,
as well as opportunities with dear L. H. and her little maid,
so my time was closely filled up there.
On second day I went on with other Friends to Folkstone.
The select meeting was truly an exercising time to me,
as well as the meeting next morning, but, through merciful help,
I was enabled to relieve my mind,
though in a humbling way to the creature--the latter
was much more relieving than the select meeting.
I do hope I did no harm, although it was hard work to utter close things,
especially to elders--but it is the Master`'s favour we must seek for,
in just handing what we believe He gives us--no more and no less.
I think I generally come shortly off rather than go beyond, but it is more safe.

It was a large quarterly meeting and many visitors.
Elizabeth Beck (who was acceptable in the second meeting) and her son
Thomas Beck (who was engaged in testimony and supplication) were there;
the line of the ministry was very much in accordance with my exercise,
which was an encouragement to me,
and cause of humble gratitude to Him who gives power
to those who feel they have no might of their own.
On fourth day morning I had sittings with several Friends,
and after dinner went on to Canterbury; next morning was at their meeting,
where there were several attenders, and had sittings with +++_______+++ and +++_______+++;
and after dinner came on here with S. D. as my kind guide.
Meeting here yesterday was very exercising, several strangers,
but endeavoured to do as well as I knew how.
I am to go to Dover this afternoon,
and I suppose to Maidstone on third or fifth day next,
and I rather expect to attend that meeting on First day week, in the morning,
and Rochester in the afternoon, which would I suppose finish what I have before me.
It seems desirable to attend both those meetings on First day,
otherwise I should not prefer doing so.
And now, dear, I have given thee a very particular account, if not a selfish one,
but I knew thou wouldst like to hear all.
I have had a long and interesting letter from dear A. Cruickshank,
giving account of many acceptable public meetings held by and in Scotland,
which rejoices my very heart.
I do trust there will be a gathering to the true Shiloh thereaway,
though we may not live to see it, and a great people come forth to praise the Lord!

Farewell, my beloved friend.
I have been quite favoured as to health ever since being actually on service;
what a kind good Master! may I hold nothing back!
Continue to breathe for my preservation, and believe me thy very affectionate friend,

[.signed-section-signature]
L+++.+++ A. Barclay.

[.letter-heading]
To A. and E. R.

[.signed-section-context-open]
10th Month, 1840.

The remembrance of you is very fresh to me.
I do indeed feel much for you in what must be a solitary situation,
now that your dear earthly parent is removed from you,
who was such a stay and sweet savour in the meeting.
But oh, my dear friends, let us hold on our way, however solitary,
and not cast away our confidence,
which hath great recompense of reward--the power of the Lord is over all,
is able to overcome all weaknesses and disease, fears and foes.
Oh! how many, and lively, and strong are the foes of our own houses or hearts;
they are like the goods of the strong man armed,
of various kinds in strength and beauty apparently;
but the Lord`'s power is able to turn them all out,
and to cleanse and sanctify the heart, to anoint it,
to fill it with beautiful offerings and a cloud of incense!
So don`'t let us faint, nor yet fear, but increasingly yield up unto His power,
who is able to do this both in ourselves and others,
individually as well as in our little gatherings or churches.
I think He has said, after promising every mercy, that He will be sought unto,
as to His people formerly;
that He would yet for all this be inquired of by them to do it--so let
us be very frequent and deep in an inward exercise of mind before Him,
craving that He would be with us in the way that we go, baptise, strengthen,
and anoint us from day to day, that we may be confirmed in our faith,
and strengthened in faithfulness to bear a living
testimony for Him in our little day and generation.
Thus shall we know our lamps to be brightly burning, and our loins to be girded afresh,
even from day to day, with the truth,
and then shall we be ready at what hour our good Lord may come.
And blessed shall that servant be whom the Lord, when He cometh,
shall find doing as He bids him.

Oh, we shall have nothing to spare, so we have need to lose no time,
even in the approaching evening of life, as it were, to bring in all the tithes,
even the small tithes, into the treasury.
Oh, we must not, how can we, withhold anything from so good a Master,
who is so willing to pass over and condescend to our great weakness,
is so very tender towards us,
and ready to hold out a hand of gracious help at all times of need--yea, He still saith,
I, even I, am He that comforteth you,
who art thou that thou shouldst be afraid of a man that shall die,
and forgettest the Lord thy maker, who divided the sea (oh, has He not done it often?),
whose waves roared, that made the depths a way for the ransomed to pass over.
And He is mighty on the behalf of those who fear Him,
and yield to His redeeming arm of power,
and He will bring them even with singing unto Zion, and everlasting joy upon their heads,
and they shall obtain joy and gladness, and sorrow and sighing shall flee away.
Then let us lift up our heads in hope, and humble trust in His divine guidance;
let us lift up our hearts in simplicity of resignation,
and holy subjection to His blessed will, and then will He not preserve us,
establish the work of our hands upon us, even in His peace and blessing,
that it shall not be in vain in the Lord, but tend to His glory.
I feel much for you; I believe He will not fail or forsake you,
who is a friend that sticketh closer than a brother.

[.signed-section-signature]
L+++.+++ A. Barclay.

[.letter-heading]
To John F. Marsh

[.signed-section-context-open]
Reigate, 6th of 10th Month, 1840.

As our monthly meeting draws on, it brings _renewed exercise_ with it.
I hope to be shown what to do and what to leave undone,
to be strengthened with faith though my outward man be weak.
You will feel for me.
There is nothing too hard for the good Master,
and surely I can hold nothing back from Him who has
hitherto helped and dealt very tenderly with me.
I desire to trust all to Ilim, body and spirit, and to be wholly given up,
for it is very uncertain if I see another year.

[.signed-section-signature]
L+++.+++ A. Barclay.

[.letter-heading]
To the Same

[.signed-section-context-open]
Reigate, 22nd of 10th Month, 1840.

Thy kind letter was very welcome--the brotherly encouragement
it contained was truly acceptable and cheering,
for thou knowest at such times we have many low seasons and deep plunges.
We were favoured greatly at our monthly meeting by a precious covering of heavenly good;
and at the conference I returned my minute for Kent, and asked for another to visit,
in Gospel love, our dear young friends of Brighton meeting,
and such other service within that monthly meeting as I might feel required.
There were several sweet expressions of sympathy and unity (as I was told after),
and I was liberated for the work.
Nature shrinks from turning out again at this season and
in such weakly health--my cough still hangs on me;--yet,
blessed be the Lord, I have a little grain of faith,
that as my day is so will be His strength all-sufficient,
if I do but yield to His good and tender hand.
Crave for me that I may be so helped and preserved from doing any harm.
I remember this is your monthly meeting at C+++_______+++; hope you have had a good meeting.

[.signed-section-signature]
L+++.+++ A. Barclay.

[.letter-heading]
To Hannah Marsh

[.signed-section-context-open]
Reigate, 30th of 11th Month, 1840.

I have indeed great cause to look back with humble gratitude to Him who graciously
condescended to be near me in my many low seasons and times of extremity,
and sent me help from His sanctuary, and strengthened me out of Zion,
in His unspeakable goodness and tender pity.
Ah, it is indeed of His tender compassion and mercy that
we yet live and have hope towards Him,
and that we are any moment and every moment kept
not only from slipping but from downright evil.
And I desire now, in returning to my peaceful home,
to be ever kept in this lowly and dependent state,
and that I may from day to day seek after His humbling, His renewing,
His quickening power upon my spirit, that so all may be kept fresh and savoury,
and that there may be a growth known from one degree of grace to another--a being continually
renewed in the heavenly knowledge (which is life) as well as preserved in it.

I had near forty sittings at Brighton, beginning with young men at shops;
then went to the monthly meeting at Chichester, and stayed First day there,
sitting with all their (few) members; afterwards to Lewes,
and had a few sittings there--the _Brighton_ children at the school,--attended their meeting,
and then to Brighton meeting last fifth day to finish.

[.signed-section-signature]
L+++.+++ A. Barclay.

[.letter-heading]
To +++_______+++

[.signed-section-context-open]
Reigate, 5th of 11th Month, 1840.

[.salutation]
My Dear Friend,

I think it is good for fellow-feelers and fellow-sufferers
to commune as it were by the way often together;
and though such communications may often be of a sad or mournful cast,
if they be but in the Divine fear, and in remembrance of His mighty power,
which is over all weaknesses, and all trials, and all the powers of darkness,
I believe there will be a little gathering of strength by the way,
a little lifting up of the heart in renewal of humble trust and confiding hope,
of fervent love and fruitful dedication, yea, and of heartfelt,
grateful praise unto Him whose tender mercies and tender care are over all His works,
but especially over His sincere, upright-hearted ones, however poor and needy,
despised and tried!

Ah, my dear friend, in thinking of thy letter,
and of thy communications in affectionate freedom to me,
I am struck with the feeling that the Lord knoweth best what is good for us,
and all His dealings and permissions towards us, however pinching and proving to nature,
are intended for our good, in tender love, and not to grieve us.
Oh, then, may we increasingly yield up ourselves into His tender good hand,
suffer Him to lead us about and instruct us in all things,
and never grow weary or repine,
then will that nature in us be gradually starved
and worn out which He would have to die in us,
and His own pure life will be raised up in dominion over all,
in which we shall be enabled to hope all things and endure all things even to the end.
It is often very instructive to me to watch His different
dealings with different individuals and instruments;
and I have great pleasure as well as instruction in thus
seeking out and marking His great works of grace.
He knows best how and when the fruit-bearing branches require pruning,
and He varies the turnings of His tender hand to each of their temperaments,
according to what they require for a vigorous and healthy and fruitful growth.
Oh, then, that we may not start aside, nor yet sink under these various operations,
but endeavour, as it were, to drink in all the good designed,
that we may increasingly bring forth sound, well-seasoned, and well-flavoured fruit,
to the praise and glory of the great and good Husbandman.

[.signed-section-signature]
L+++.+++ A. Barclay.

[.letter-heading]
To +++_______+++

[.signed-section-context-open]
Reigate, 6th of 12th Month, 1840.

Ah! my dear friend, I have seen, as I have thought,
a great snare to our ministers and to our dear young people in the free, familiar,
and even light manner and conversation which has of late years sprang up amongst us,
with the view of being attractive and pleasant to our young people,
"`and as such are not fully given up.`"
Instead of ministers and elders being a reproof to what is of an evil tendency (that is,
what _springs from_ the vain mind or the worldly spirit,
and pleases it in others) by their weightiness of spirit and inwardness,
they are too generally shaking hands, as it were, with these things,
or with the dear youth in their unfaithfulness or
shortcoming up to what truth would ever lead into,
instead of helping them up to a higher state.
For I do believe there is a faithful witness in the hearts even of dear children,
which causes them to admire a faithful consistent walk,
and that they will feel the evil kept down, and the good strengthened,
in being with such weighty characters, although nature may kick against the restraint.
Nevertheless, do not mistake me; I believe this weightiness will never bring gloominess,
but will give an innocent cheerfulness.
If thou looks at pages 71, 72, and 73 of [.book-title]#Mary Peisley`'s Life,#
thou wilt see how she felt,
and this is what I have earnestly coveted after these twenty-one years, but,
alas! how far behind am I. I assure thee,
I much more often feel that my freeness and openness is cause for mourning,
than the opposite condition of silence and reserve; nay,
how _many_ times have I longed for the silence and reserve
that characterised me when _I first saw_ thee in 1821,
lest I might draw any, like Absalom, from their true King!
Let me be vile and weak that He may be exalted and loved above all!
Crave for me that I may be increasingly made and kept faithful, watchful,
and humble in the Divine sight, abiding in the true Vine,
receiving daily fresh sap or life from Him,
that so there may be a continual freshness and fruit
found to the praise of the great Husbandman,
as well as a true oneness (in the true unity) with all the living branches in Him.

Farewell. With much love, I remain thy friend sincerely,

[.signed-section-signature]
L+++.+++ A. Barclay.

[.letter-heading]
To Lydia C.

[.signed-section-context-open]
Reigate, 29th of 12th Month, 1840.

[.salutation]
My Dear Friend,

I do not like thy kind letter of the 10th should go long unanswered.
I am pleased by thine to find thy health is favoured to hold up,
and that thou art in the salutary practice of a regular
walk daily as a means to retain so great a blessing.
No doubt the constitution is braced by the frost,
although we do hear of divers dear elderly and delicate ones being removed by death,
as is generally the case in the extreme seasons of heat or cold,
but no doubt it is all ordered in wisdom and love,
the righteous (or upright) are taken away from the evil to come,
and we that are allowed to remain a little longer,
are afresh warned and exhorted thereby to be diligent and watchful,
and to arise and trim our lamps afresh--even that
we may again and again yield to the Lord`'s trimming,
and emptying, and cleansing hand of power,
and seek to be renewed and filled with His heavenly oil,
that the light that He bestows upon us may shine clearly and brightly to all around us,
to His glory and the gathering of others under the precious influence thereof.

Thou kindly asks me about my visit at Brighton.
Through condescending goodness I was helped to relieve my
mind of the burden I had felt in going from house to house,
and in some cases visiting our dear younger Friends individually in their families.
I need not to thee say it was truly a weighty and
exercising service and deeply humbling to the creature,
often being led in a close way and foolish looking; no doubt, feeling after every word.
If the good in any has been a little helped up,
I am sure the glory belongs only to Him from whom the ability came,
and if I might but be preserved from bringing the least reproach on the precious cause,
what a favour it will be! for oh, how great is the encompassing weakness;
it is a wondrous mercy that we are kept any moment, and every moment,
from slipping and from evil!
Grace! grace! we may and must say continually.
I felt much exercised on the subject of the essay meetings and
also the fancy work that has crept in so much amongst us,
and had to press upon them to search and try all
their ways by the unerring light of Christ,
all that they put their hands unto or employ their time in;
for that the enemy of their souls`' true peace might lead them,
with apparently very good and plausible motives, into things whereby the wisdom,
and activity, the vanity and pride of the creature would be greatly fostered, yea,
excited, which ought to be crucified and brought to nothing! Alas! dear Lydia,
how is the man`'s part nourished and strengthened by the sort of education
and bringing up of children that is now in vogue amongst Friends;
we are sadly apostatised!
I was at Chichester sitting in their families, also in a few at Lewes.
My health was wonderfully preserved, and, through favour,
I came home stronger than I went.
May the Lord help and keep His poor worm living, and unto the very end!

[.signed-section-closing]
Thy sincere and affectionate friend,

[.signed-section-signature]
L+++.+++ A. Barclay.

[.letter-heading]
To A. R.

[.signed-section-context-open]
2th Month, 1840.

Whilst at B+++_______+++ I felt constrained to press upon the dear young people
to search and try _all their ways_ by the unerring light of Christ,
all that they put their hands unto or employed their time in,
lest they should in any degree be led, with an apparently good and plausible motive,
into such things as might excite the creaturely activity or wisdom,
or please the vain mind, or promote the worldly spirit either in themselves or others;
all of which ought to be mortified or subdued and brought to nothing.
I spoke on the subject of the essay meetings.
I was sorry to find these essays are encouraged in our schools, whether public or private.
Alas! how is self (or the man`'s part, as Isaac Penington says) fostered by these things;
but few see it to be so, nor the consequences.
Ah, the Spirit of Christ must regulate all our affections, and desires,
and good feelings, as well as curb the bad.
I fear with some dear friends there is too much of an entwining about one another,
and living like parasitical plants upon the life of others,
instead of having a good root and bottom themselves,
and something of a living upon the love and sympathy and tender feeling of others;
but anything that draws us away from an inward dwelling and feeling, yea,
and an inward dying, is dangerous,
however _much_ it may look as if it would strengthen and nourish
the right thing--it may only foster a sickly growth that
does not promote full-flavoured and rightly-seasoned fruit,
nor yet such firmness in the Root as may bear the stormy, proving wind.

I felt thy kind expressions very grateful;
surely I above all others need the prayers of the faithful.
If I might but have been preserved from bringing
the least reproach on the cause of truth,
what a favour it would be! but many and deep are
often my plungings in returning home on these occasions.
I know that constant sunshine is not good,
and baptisms even unto death are necessary to cleanse
and to prepare for what further may be required.
Oh! saith my soul, that patience may have her thorough work,
that nothing may be lacking that may tend to the glory of the Creator,
or to the utter abasement and entire purification of the creature.

[.signed-section-signature]
L+++.+++ A. Barclay.

[.letter-heading]
To A. R.

[.signed-section-context-open]
1st Month, 1841.

The account of the dear soldier really seemed to do me good in the midst of a low season.
It was indeed cheering to hear of good springing up in the heart of the dear youth,
and a willingness to take up the cross,
and despise the shame that attends a confession of the truth.
I could not but think how it would have gladdened the heart of my dear brother,
who rejoiced in the spreading of truth, through suffering, even through tribulation and,
as it were, the blood of the martyrs or witnesses.
I have thought that similar would have been your
dear father`'s feelings (whose memory is blessed).
But these dear departed spirits do join with us below
when permitted thus to praise the Lord in our hearts,
only after a more heavenly and purified sort, even in the angelic chorus.

Our thoughts and desires are often directed towards the dear youth,
craving that he may be preserved firm and steadfast
in the faith and patience of the saints,
and then I have no doubt that whatever he has suffered, and however trying to nature,
that it will tend to the glory of the Lord and the spreading of His excellent truth.
There is danger of taking such, as it were,
out of the Lord`'s good hand that would lead them gently on,
and be their all-sufficient support and comfort.
Much notice has drawn them out of that deep exercise and lowly abiding,
which would have worked to their greater deepening and more true and safe growth.
I feel tenderly for such,
and know that the word of encouragement and counsel may
often be very helpful to them and necessary at times.
How surely, and wisely, and excellently will truth guide us, even to an hair`'s breadth,
as to our steppings towards them,
or the puttings forth of our hands to the support of the testimonies thereof,
if our eye is but single enough, and our heart simple enough,
in looking for and minding the sweet gentle pointings thereof in the secret of our hearts,
even leading to the denial and humiliation of self in all its twinings.
I am fearful lest anything of nature creep up in me.
Oh, how necessary then to watch both sides,
lest it should prompt or lest it should hinder and dismay!
I am often ready to conclude I can no more put my hand to such awful work,
yet I know the Lord`'s power is sufficient to preserve as well as to strengthen.
May we increasingly yield to it, and then all will be well to the end.

[.signed-section-signature]
L+++.+++ A. Barclay.

[.letter-heading]
To R. B.

[.signed-section-context-open]
4th Month, 1841

[.salutation]
My Dear Friend,

In looking back to thy late visit to us,
my mind seems to be arrested at our conversation
on the death scenes of some of our younger Friends,
whose lives had to us appeared more to be marked for following their own
inclinations than for subjection to the crucifying power of truth.
I have sometimes thought that, on these occasions,
expressions indicative of sweetness or comfort are much spoken of and come abroad,
while the previous deep sense and humbling view of many former shortcomings or backslidings,
and the passing through the judgments of the Lord therefore, whereby redeeming is known,
and the purifying of the blood of Christ is rightly felt,
is often kept hid in the bosom of the dear invalid, or not made known by the relations,
lest it should have a gloomy or discouraging effect.
On the other hand,
we know how easy it is for some to be buoyed up and
buoying themselves up in a false hope and ease,
and this may be carried on to a very late period!
At the same time, we also know the tender goodness of the Lord,
who can at a very late hour so touch, and melt, and subject the soul,
can so shine in the heart and enlighten to see His glory,
as to change by His Spirit even as in a moment.
But I believe it is best for us not to dive into these things that are too high for us;
we have full enough around us to warn us to "`use diligence to
make our calling and election sure,`" by a faithful cooperation
with that Divine grace which appears to and visits us for our salvation,
and _abundantly_ will work in us to will and to do according to the Lord`'s good pleasure,
if we yield thereunto.
There is also plenty of encouragement for the humbled and returning penitent
not to despair or doubt the Lord`'s unutterable goodness and almighty power,
whose mercy is as His majesty infinite!
Oh, then, may we be both warned against in any wise drawing back,
lest we should come short of His promised rest,
and be encouraged to press forward in the way of known duty,
in the belief that we shall not fail to reap if we faint not.

And, dear R., while I have the pen in hand,
I would express the sincere desires that I feel for
thy best welfare and growth in the truth.
Do not be looking too much out at others,
lest thou shouldst be either stumbled or led by them improperly.
"`Every tub must stand on its own bottom,`" is a true saying.
It will not do for us to be leaning on the opinions
of others any more than on their help and encouragement.
This is not a good foundation;
it is but a sort of parasitical life that looks fair and elegant,
while the growth and strength of the substantial
tree of God`'s right hand planting is thereby hindered,
and eventually the life thereof decay.
Let thy attention then be more and more turned inward to mind the piercing,
quickening word of life that is nigh in the heart and mouth.
Wait for and feel after the gentle secret influences
thereof upon thy spirit day by day to humble,
cleanse, quicken, and strengthen thee;
thus shalt thou know thy spiritual senses by reason of use to wax stronger and stronger--the
ear of thy soul to become more and more quick in understanding the dear Master`'s voice--thy
spiritual vision more and more clear to perceive the guidings of His heavenly eye^
footnote:[Ps. 32:8]--thou wilt the more readily
be able to smell what savours of God or not--yea,
wilt be increasingly permitted to taste the sweetness of His great goodness,
and acutely to feel the gentlest touches of His power within to constrain or to restrain.

Thus nourished by fresh virtue continually from Him, thy life and beloved,
thou wilt be led on gradually and safely from one
degree of growth and fruitfulness to another;
and waiting thus on the Lord in the way of His inward judgments,
even until judgment dwell in the wilderness and righteousness
remain in the fruitful field,
thou shalt truly know "`the work of righteousness shall be peace,
and the effect of righteousness quietness and assurance
forever,`" and that God`'s true-hearted,
faithful people do "`dwell in a peaceable habitation and in sure dwellings
and in quiet resting places,`" although many are their afflictions,
and they have to pass through much tribulation,
and the shoutings of their soul are "`all of His grace,
all of His unutterable grace in Christ Jesus.
Glory to Him forever!`"

[.signed-section-signature]
L+++.+++ A. Barclay.

[.letter-heading]
To A. R.

[.signed-section-context-open]
6th Month, 1841.

I hear is +++_______+++ gone to Millbank.
I hope he will have much time for waiting on Him who has
revealed Himself to him in the secret of his heart,
and gives him strength to testify against their wicked doings.
Ah, here lies his strength,
even in waiting for and yielding unto the Lord`'s power inwardly revealed,
and then a prison may be a growing place, a deepening place,
and as a palace for the enjoyment of the Lord`'s presence, the King of kings!
May this work for the tendering of many hearts.

[.signed-section-signature]
L+++.+++ A. Barclay.

[.letter-heading]
To J. B.

[.signed-section-context-open]
Reigate, 6th of 8th Month, 1841.

[.salutation]
My Dear Friend,

Thy kind letter during the yearly meeting I felt truly acceptable, nay,
may I not say strengthening too, however poor thou mayest feel thyself,
and unworthy to hand even a cup of cold water to a fellow-pilgrim.
Ah, my dear friend,
we know not sometimes how helpful an acknowledgment of love and unity,
or even a mere tender squeeze by the hand showing as much may be; therefore,
it is well indeed to yield to little pointings,
for the true fellowship is very strengthening, and,
alas! there is but too little of it now-a-days,
so that the poor exercised ones go bowed down as it were all the day,
besides having to bear many wounds to their best life from without,
and many deaths to pass through within,
in order for their purification and the slaying (and
the keeping slain) of the wrong nature!

Oh! it is comforting, and it seems to give one a little lift on one`'s way,
to receive a salutation from a neighbour as we pass along,
that is going towards the same city of abiding habitation and of peace!
But how very many imitations are there of all the good things in Zion,
even by the enemy of our soul`'s peace, so that it is hard to trust any,
and the fear is great of being mistaken ourselves!
But in the pure fear is the true preservation,
and in the silence of all that is of the flesh is the true voice heard clearly,
and the true feeling is given of what is right and what is wrong,
so that I often remember with instruction what one of our ancient worthies said,
that when there was more of the true silence and retirement amongst us as a people,
there was more of the true knowledge of ourselves, of others, and of God,
the true discerning of all things;
and it is for want of this inwardness that we have so many young
people intruding into things that are too high for them,
speaking as if they were grown men in the truth all at once,
not knowing themselves or the power of God sufficiently--as well as so many older
Friends that have not attained the strength that was designed them,
nor that degree of union with the truth,
whereby they should be able both to discern others,
and to "`know what Israel ought to do.`"
Ah, I can well say with thee, "`The fathers, the mothers, where are they?`"
But, dear friend,
let us not sink too low in discouragement at the state of things amongst us,
a poor backsliding and rebellious people,
nor cast away our confidence in that Divine arm that
will ever be sufficient for His truehearted,
clean-handed Israel, however small and scattered a remnant they be!
I believe these, as they keep close to His Divine gift in the secret of their hearts,
will be hid as in the hollow of His holy hand during
the shakings and siftings that must come upon us,
and will daily seek after and receive His heavenly strengthening to walk faithfully,
watchfully, and humbly before Him in their different lots to the end of their day.
And oh, saith my soul, that thou and I may be of this happy number.
Wherefore, let us take unto us "`the whole armour of God,
that we may be able to withstand in the evil day;`" let us "`take heed unto ourselves,
watch and pray always that we may be accounted worthy
to escape all these things that shall come to pass,
and to stand before the Son of man.`"
And, my dear friend, in order that we may become "`strong in the Lord`" and for the Lord,
even "`in the power of His might,`" I long that we may be more and more
faithful in the little that we do already know and feel of and from Him,
and then I believe He will gradually increase our knowledge of Him, our feeling for Him,
and our ability to work for and with Him,
to our own great peace and the help of the body;
for as one member grows all the members partake of
and feel that growth and increase of strength.

We had a more quiet and agreeable yearly meeting than usual,
and there seems a tender visitation to the youth,
and more of a yielding thereto than has been perceptible for some years,
which is truly comforting to some of us poor mourners.
Still there is much evil underneath that has to be
worked out both _to_ sight and _out_ of sight.
Man`'s wisdom and activity have crept up too much in our meetings,
and would be up and doing.
While the Divine power is oppressed, there is no _room_ for it to humble and move us,
and our discipline becomes in consequence much in the form without the power,
and fails to do what it was designed to do, to keep the camp clean.
But let us have, or seek after, faith and patience,
and we shall see that that which is only superficial will be swept away by the torrent,
whilst that which is solid and deep beneath the surface, founded on the Rock,
will stand the commotion, the tempest!
Oh, then, let us labour to get deep in our spirits, feeling all our springs,
our strength, and our standing to be in Him, the Rock of Ages,
the foundation that remains sure, having this seal,
"`The Lord knoweth them that are His.`"

My health has, through mercy,
been greatly strengthened during the last winter and spring--a great favour,
and surely deserves returns of unreserved dedication and
humble gratitude to the author of all our blessings.
But, alas!
I fear the health of the better part is dwindling instead of increasing,
through letting in the enemy`'s discouragings,
and a want of feeling after the daily sap of life,
whereby strength would be received to overcome all obstacles and all weaknesses,
and to bring forth the fruit designed and looked for.

[.signed-section-closing]
Thy sincerely affectionate friend,

[.signed-section-signature]
L+++.+++ A. Barclay.
