== Chapter IX

To L. H.

Reigate, 29th of 9th Month, 1841.

My Dear Friend,

Thou needst not feel ashamed of thyself, I am sure,
for I have not thought thee at all negligent.
I had heard of thy being in London,
and supposed thou hadst come up about the little book.^
footnote:[Memoir of Mary Hagger]
I am so pleased to find by thy letter that thou hast been strengthened to go
simply forward in it without attending unduly to +++_______+++`'s reasonings.
I say strengthened, for I know it is not in man either to direct his own steps aright,
or to give himself courage or faith to take those steps.
I hope and believe thou wilt have no cause to repent.

Thou dost not say whether +++_______+++ sent to you at
Ashford the letter addressed by me to you all three.
I feared you would think me very bold, perhaps impertinent;
but indeed I felt much about it,
and thought it my duty to do my "`very best`" (as dear old
Thomas Shillitoe used to say) in forwarding so good a work.
I long to see it, and should like to take twenty-five copies for myself,
and twenty-five for two Friends who are in a little way of shopkeeping.
I trust it will give general satisfaction,
and I shall endeavour to promote its spreading in
my correspondence with my distant Friends.
It was truly pleasant to hear a little of your Friends from thy pen.
Dear M. Baker! how solitary is her path, as well as that of many others,
and thine included,
dear L. It is a peculiarly trying time to the exercised on this account,
that they are so solitary.
But I believe it is in wisdom thus ordered,
that they may be driven the more closely and constantly to Him,
who is never failing and changeth not!
Ah, what a precious consideration is this,
that He does not change (as man does so very frequently and tryingly to
us!) nor yet does He see as man sees who judges by outward appearance,
but looks at the heart!
To whom then can we go for such true, and constant, and omnipotent help,
as to so unshaken and good a Friend, the Almighty and all-gracious One,
who knows what is best for us, as well as all that is in us; will tell us the truth,
and most tenderly counsel us; yea,
and His tender words of counsel are with power also to follow it,
and His sweet peace flows on our yielding to it!

How do I long for us who are so solitary, and who do, I humbly trust,
feel exercised for the precious cause sake, that we may be more and more diligent,
and earnest in waiting on the Lord for His counsel, and strength,
and heavenly direction day by day, and more and more firm in keeping to it,
and occupying with it, in His holy fear, and the true humility before Him who touches,
and draws, and calls us!
Never let us mind if we have many seasons of dreary
drought and times of proving and suffering;
may we be enabled to keep the word of His patience through all trials, and reproaches,
and persecutions, for He is faithful who hath promised, "`I will never leave thee,
nor forsake thee.`"
"`Fear thou not, for I am with thee!`"
Let us endeavour to do all our little best for the truth,
and watch and pray that we may be preserved from doing any thing against the truth; thus,
by keeping to the truth, the truth will keep us to the end that crowns all.

I am pleased to hear of +++_______+++. I earnestly desire that he may,
through humbling repentance and condemnation of his error, find acceptance at last.
My love to +++_______+++. Oh, that she might seek to elicit this,
to fan the little spark of true humbling feeling into a flame,
for Zion shall be redeemed through the spirit of judgment and of burning!

Dear John F. Marsh is gone to York quarterly meeting.
His prospect is to visit that county, Lancashire, Derby, and Notts quarterly meetings,
with liberty for families, etc.
Poor dear M. A. S.! I fear she is sinking in decline.
On her account we can but rejoice in her prospect,
but for that little church we must mourn, for the exercised labourers are few.
She wrote very sweetly.
Dear S. Grubb, I suppose you know,
is liberated for visiting the quarterly meetings (only) all over the kingdom,
and has made a beginning with those of Reading, Gloucester, and Bristol.
What an excellent concern!
I fear it will be her last, like the winding up of her testimony.
I remain thy affectionate and sincere friend,

L+++.+++ A. Barclay.

To +++_______+++.

Reigate, 6th of 10th Month, 1841.

&hellip;My dear love to +++_______+++, and I hope she tries to be very good and helpful to mother,
by endeavouring to overcome self and selfish inclinations on all occasions.
In proportion as the selfish spirit is driven out of us,
so God`'s good Spirit will come in and dwell with us,
and shed such sweetness and meekness and peace all around us,
it will be like taking us up to heaven or bringing heaven down to us.
How happy shall we be then, and so will all who love us and are near to us!

L+++.+++ A. Barclay.

To Hannah Marsh

Reigate, 1st of 11th Month, 1841.

My Dear Friend,

Thy kind sisterly epistle I do not like to neglect.
It does cheer one up to hear from those who are like-minded
in the present hot day of trial and of sore treading down,
and, alas! dear Hannah, how few there are who are like-minded in most important respects.
I am more and more dismayed to fancy one`'s self so solitary;
one gets continually baulked, or rather knocked down,
by finding out differences of feeling in those whom
one has hitherto imagined were on the ancient side,
and which I believe to be no sectarian view or mere opinions,
but the only sure foundation, viz., a building on the inward revelation of Jesus Christ.
Ah! this does not in the least lessen our value for,
and enjoyment of the benefit of His outward manifestation and sacrifice--no,
it enhances it, and, if I may so say, sanctifies it unto us, appropriates it to us,
for if He wash us not by the washing of regeneration, and renew us by His Holy Spirit,
we shall have no part in Him,
nor in that salvation He laid down His precious life to purchase for us.
Oh, this ancient and precious foundation of the life and Spirit of Christ,
it shall stand all the tempests of the windy doctrines of men,
and shall outlast them all, for the Spirit of Christ must and shall prevail over all,
and His dominion be forever and ever!

L+++.+++ A. Barclay.

To John F. Marsh^
footnote:[When visiting Hannah Marsh, in his absence.]

Croydon, 23rd of 11th Month, 1841.

Such opportunities we really should avail of, when thrown in our way,
of mingling a little with those whom we feel to be fellow-feelers and fellow-sufferers,
of endeavouring to take sweet counsel together as in the presence of the Lord,
who would indeed keep our conversation innocent, weighty, and serious.
Oh, this is what I long for, that though our communications may be of the mournful cast,
yet that they may be seasoned by the Divine fear,
which would keep us in the remembrance of His mighty power,
whereby He is able even to subdue all things unto Himself,
and to work mightily in and for us.

It has been very pleasant, my dear friend, and cause of renewed thankfulness on my part,
to hear from time to time such nice accounts of thee from thy dear wife.
Thou hast hitherto been strengthened and helped in every needful time,
and preserved in health throughout so long and exercising an engagement,
and I have no doubt it will be so to the end.
Oh! what a good and tender Master is He to all who look and cleave to Him alone,
so bountiful in His condescension to us poor, weak, unworthy creatures,
and so very tender if at any time we slip,
and it is of His wonderful grace that we yet live and have hope towards Him.
Oh, that we may never turn away from His gentle drawings,
or grieve Him either by withholding or overacting.

I am pleased thou hadst +++_______+++ with thee.
He is a young man I feel much interested about,
and desire his deepening and growth in the root of Divine life.
Ah! this is what is wanted among us, and it is attained more in the shade, I often think,
than in the sunshine of favour and encouragement from without.
If this hidden life were more promoted amongst our dear youth,
and earnestly travailed for,
there would be less of the superficial work that
is so very prevalent and plausible with us,
and then there would be more full seasoned, full flavoured, and sound fruit to be found.
Ah, this true life would give the true sight of the things of the kingdom,
and the true feeling of the mind,
and for the cause of truth a true zeal for the promotion thereof,
even in the meekness of the true wisdom, and in the humility of the true and pure fear.
My very soul craves it as the best of all treasures.

L+++.+++ A. Barclay.

To L. C.

Reigate, 27th of 11th Month, 1841.

My Dear Friend,

Did I tell thee I had heard of the decease of dear of +++_______+++, of rapid consumption?
What a sweet Friend she was!
Ah, I remember receiving a precious letter from her eighteen months ago,
when I was under deep trial and reproach from a quarter
I could hardly have expected on account of my peculiar walk.
She said that for nearly a year she had been longing to acknowledge
(but feared it would be a liberty) her near sympathy and unity
with me in the narrow walk I had believed it required to walk in;
and that although she might be esteemed a plain, consistent Friend by most,
yet that she believed a much narrower walk must be hers if she yielded to inward conviction.
Oh, it seemed to help me up a bit, and were it not for such little providential lifts, I,
for one, should, I fear, soon sink and faint, being one of the weakest of the weak.
Yet I do bless the Lord that He permits me to be
thus frequently proved and plunged and sifted,
that the foundation may be thoroughly shaken,
and that that which cannot be shaken and that which
can stand the fire may remain to His praise;
for oh, how easy it is for self to be creeping up even when and where we least expect it,
yea, to gather life to itself from that which looks most likely to slay it!
It is the Lord`'s power that can alone cut off its many heads as they rise up; and oh,
saith my soul, let us patiently and submissively yield to His good hand of power,
however it operate, that it may be so by little and little,
and that we may witness His own pure life thereby
to rise more and more into dominion over all,
and that will make and keep us lively and low, sound and savoury, faithful and fruitful,
and then His own works will praise Him indeed!

I felt much at parting with dear +++_______+++. It was a pleasant visit to me,
and an opportunity of seeing most of my old friends;
but towards the end we were rather hurried.
Oh, how do I long that we were more deep and inward in
our spirits in these times of social intercourse,
breathing after heavenly help, and not shrinking from it,
and that we were less in the chattiness and outwardness!
I believe we should thereby gain abundantly more and lose abundantly less.
It is, I need hardly tell thee, so comfortable to get home again,
and perhaps it does one good to leave it for a time,
and go and see and feel for others`' trials and sufferings,
and then it makes us the less poignantly feel our own.
Oh, what a dense atmosphere spiritually do some live in around!
But truly the Lord is sufficient, if alone looked to and cleaved to,
and the faithful may be as a little salt in the midst thereof.

Farewell in haste and with dear love.
I should quite like, if permitted, to come and see you.
In the meantime, I remain, as ever, thy very sincere and affectionate friend,

L+++.+++ A. Barclay.

To R. R.

Reigate, 30th of 11th Month, 1841.

It was much in my heart to have gone to the interment of dear E. Pryor.
I only heard accidentally of her death at breakfast-time that morning,
and was much affected, though I had long expected it,
and felt constrained at meeting to allude to the
blessedness of being gathered into the heavenly garner,
and how we might experience it.
I had great love and respect for her.
This is a season when we are continually reminded of the uncertainty of time,
and the great need for a continual consideration of, and preparation for our latter end.

The day that is coming will prove every man`'s work of what sort it is;
and oh that mine may be proved even by fire, and made what it ought to be,
for all is not gold that glitters.
Oh, how few there are comparatively who bear an entirely clear testimony,
not only in ministry, but also in practice!
I have felt deeply humbled and instructed in the consideration thereof lately,
in the seeing and hearing and feeling of what is wounding to the best life.
Let us lay it to heart, dear R., and crave to be thoroughly searched, humbled, purified,
and quickened afresh from time to time by the blessed power of truth,
that ever remains to be all-sufficient to overcome all weaknesses and snares,
and to strengthen to a faithful testimony-bearing to the end.

L+++.+++ A. Barclay.

To A. R.

11th Month, 1841.

There is sometimes more of a deepening in the root in the shade, as it were, unobserved,
and these are indeed times when such a progress is especially wanted,
and less branchification.
Ah! the more one sees, hears, and feels about things,
the more one is clothed in mourning;
there seems so few comparatively who come up entirely in a clear testimony,
both in ministry and practice.
I have of late been deeply humbled and instructed in the consideration hereof.
How does one long to be thoroughly searched and purified,
humbled and quickened by the power of truth,
which ever continues to be all-sufficient to overcome all weaknesses and snares,
and to strengthen unto a faithful, humble testimony-bearing, even unto the end!
I must be content to be a solitary one.
The day that is hastening will try every man`'s work of what sort it is.
Oh! that mine may be tried though even by fire, and made what it ought to be,
that I may be preserved in the ancient testimony to the blessed and unchangeable truth.

L+++.+++ A. Barclay.

To the Same.

21st of 12th Month, 1841.

I have been thinking of your quarterly meeting drawing on, and I might say breathing,
I trust, in our little retirement, that the Lord`'s power and presence might be with you,
in which alone is wisdom, strength, and comfort;
that it might so humble and bow you down before Him,
as that you might witness a little ability to arise in His name or might,
and experience the comfort of His love and the fellowship of His Spirit,
being made conformable to His death.
And now that you have had a living member added to the select meeting,
I do trust Friends will be quickened and anointed
to see and to feel where the true anointing is,
and where the true baptism has been and is submitted to,
and will be enabled to be firm in the true discovery and judgment
thereof in the consideration of an addition to the elders.
It would be truly sad if the true qualification were passed by,
and a weak nomination made, to bring weakness over you for time to come.
Ah! this has been one great cause of our degeneracy as a people,
man`'s judgment has been looked to on appointments,
instead of the life and power of truth,
and so the wrong thing has had sway and crushed the tender life,
even though a most plausible appearance has shown itself.

Oh, the great need of the baptising, crucifying power of truth,
and the thorough work which this will do in us.
Nothing short of this will do anything for us,
either as members or officers in the church.
My soul craves this earnestly for myself and those I love, yea,
a constant renewal thereof, a constant baptising into Christ`'s death,
that so we may know Him to be our resurrection and life,
and may witness that newness of life in and by which we
may serve God acceptably with reverence and godly fear.
Thus I seemed led on to meditate on the Lord`'s wonderful goodness towards His upright-hearted,
faithful,
travailing children who are often bowed down in sorrowful
mourning for the desolations of Zion,
and in deep painful travail for the arising of Him who is
her light and life into more full dominion over all,
strewing their tears in solitary places;
and I saw how He would make a way for their deliverance, even where they,
with all their looking or contrivance in their own willing and wisdom, can see none; yea,
though they may have long been as among the pots, yet He can, in His own time and way,
give them to arise up aloft, as with the wings of a dove covered with silver,
and her feathers with yellow gold; for blessed be His mighty good name,
He hath prepared and still does prepare of His goodness for His poor.

Thus, I thought,
He made (in condescending goodness) the outgoings of my
morning this day to rejoice in the remembrance of His name.
Oh, were it not for such help, what would become of such a poor, weak,
fainting one as I am; for truly, bonds and afflictions continually await and abound.
Many are the fears within and fightings without.
It is hard work to be faithful,
especially to those most dear to us--truly like laying down our lives for our friends.
I believe that many of our dear friends, elder and younger,
have been hurt by having their minds gradually drawn away from a deep inward exercise,
to know the arising of the well-spring of life in themselves,
to the hindrance of their service,
and the weakening their testimony-bearing for the truth.
I hope +++_______+++ does not confine revelation to what is written in the scriptures,
though we know it accords therewith.

L+++.+++ A. Barclay.

To +++_______+++

12th Month, 1841.

My Dear E.,

I was in degree prepared for thy open ingenuous letter,
and could in a moment enter into all thy feelings,
although I must own it could not fail of trying me in one respect; but,
in endeavouring to look back at what had come before me to express to thee,
and in which one was under a degree of disadvantage by interruption,
I have felt quiet in the belief that it was my desire and
endeavour to do what I apprehended was required of me.
I have often found, dear E., in my own experience,
that when what has been delivered to me by an instrument has not seemed to me to apply,
if I have endeavoured to abide in the patience and cleaving to the power (which,
as I apprehended, moved him or her),
the thing has gradually been opened unto my mind afterwards,
and been brought home by the Witness in the secret of my heart, to my comfort,
or instruction, or warning,
and so I cannot but believe it will be thy case in this respect,
as thou endeavours to turn and keep thy attention
inward to the power of Divine grace and truth,
which I believe is preciously visiting thee to draw
thee nearer and nearer to the fountain thereof.

Ah, we must not be looking outward, either at what one may say or at how another may do,
however plausible or excellent it may appear,
or however it may coincide with our own creaturely apprehensions--but
rather let us sink down into the stillness of true resignation
of the creature to whatever may be manifested,
desiring to hear the voice of the good Shepherd and Master within,
who indeed is our truest friend and the faithful witness for God;
and let us not fear the searching of His holy light,
or the fiery and crucifying operation of His word, if He break up our false rest,
and rend off our beautiful covering, and spoil all our pleasant pictures,
and give us closely to feel and clearly to see what is our real situation and condition,
and what His Spirit is not in, how plausible soever it may appear.
I say let us not start aside at such a disclosure, what though it touch us, as it were,
in the tenderest spot,--neither let us suffer the enemy to dim the little
light and sight thus mercifully given by a fair looking cloud,
persuading us that we are mistaken or must not take so narrow a view! thus should we
endanger our Guide and Shepherd`'s retiring further from us--but rather let us,
by closely attending to the motions and discoveries
of His light and life in the secret of our hearts,
as Isaac Penington says, "`Draw His yoke close about our necks, take the cross,
the contrariety of Jesus, upon our spirits daily,
that that may be worn out which hinders the true unity with Him,
and so we may feel our King and Saviour exalted upon
His throne in our hearts--this will be our rest,
peace, life, kingdom, and crown forever!`"

And I believe, dear E., if this be thy endeavour and earnest concern,
that thou wilt increasingly find thy path to be a solitary one.
Ah, we have but few helpers in this deep and inward path,
else there would not be so much of a beautiful-looking superficial work amongst us, as,
alas! is sorrowfully the case;
for it is a path which the vulturous eye of man`'s
carnal reasoning and comprehension cannot perceive,
neither can that which is comparable to the lion`'s whelp,
the strong unsubjected will of man, that is in the ravenous nature against the life,
ever tread thereon! but, blessed be the name of the Lord,
those who are yielding to His redeeming power, even the spirit of judgment and burning,
and abiding under the yoke of His life,
do and ever shall find it a path of pleasantness and peace, yea, though fools,
they shall not err therein,
but be brought safely thereby through all that stands in their way, even unto Zion,
with songs and everlasting joy upon their heads,
and sorrow and sighing shall flee away from them,
for they shall experience the work of Christ`'s righteousness to be peace,
and the effect thereof quietness and assurance forever!

L+++.+++ A. Barclay.

To J. W.

Reigate, 29th of 12th Month, 1841.

My Dear Friend,

Thy last was truly acceptable and strengthening--and I trust my eye in reading it,
was unto Him from whom all help and good comes,
who does remember His poor afflicted ones in seasons of His wise and good pleasure,
and strengthens them with a little fresh might, from time to time,
by His Spirit in the inner man, whether with or without instruments,
and sometimes such little lifts are like the prophet`'s cake,
that supported him during a long wilderness journey.
So it is good indeed to trust in Him, however low,
for He will not suffer us to be tried beyond what will tend to His glory and our purification,
nor above what He will strengthen us to bear, as we cleave close unto Him through all.

Ah, my dearly beloved friend, thou knowest in what sense I am anxious.
To have the living in Israel taken away from us at such a time of trial,
and of treading down, and of sore dismay, makes one sad at heart to think of;
but on their account one cannot be anxious--rather
rejoice that their dear Master calls them up higher,
where sorrow and sighing flee away,
where the wicked cease from troubling and the weary soul is forever at rest.
It is no matter what are the means used for the breaking down of these
poor tabernacles of clay that must crumble into dust again soon.
But, oh! that the Spirit may be prepared and wound up for heaven!
I am sometimes ready to long it may be soon, yet desire not to be hasty,
but to be preserved in the true faith and resignation to the end,
"`if so be that being clothed, I may, through Divine goodness, not be found naked.`"

But, oh! my dear friend,
we do want true and tender elders sadly amongst us--such as can tenderly and
wisely point out any little weakness or temptation we may be liable to,
and help us out of it into greater strength,
instead of either letting us abide alone and get deeper and deeper into weakness,
or else doing their work in a rough, injudicious way, and so discouraging.

But, oh! how many,
many snares are there all around for us poor weak children in the awful work!
We may well fear and tremble for ourselves, rather than look out at others.
And oh, that we may breathe one for another,
that we may more and more know that thorough purifying work, that thou, my dear friend,
speakest of.
How did my heart go with every word of that part of thy letter.
It was so peculiarly in coincidence with the secret meditations
and exercise of my own mind for these two or three months past.
I cannot but believe that if there were more submission to this fiery baptism
and thorough purging from all that pertains to the creature known amongst us,
there would be a more pure and clear testimony (consistent
throughout) borne for the blessed truth,
both by precept and example, both by ministers and others;
and I have greatly lamented of late to see and hear
of inconsistency of practice in ministers;
it seems to me like pulling down with one hand what
is endeavoured to be built up with the other,
and surely it must be from a want of this thorough purification.
I fear lest seeking minds should be stumbled,
and I know that many of our dear youth observe it;
and oh! there are too many amongst us who are watching and make a handle of everything
that will lower our ancient testimony to the sufficiency of Divine grace!
These things often make me mournful, and, as I said before,
trembling and fearful for myself, lest I should come short of the pure standard of truth;
and, oh! saith my soul,
that I may more and more entirely yield up to be
melted and moulded by the power of truth,
which I know is all-sufficient to overcome all weakness, and evil,
and temptations either of the enemy, or the worldly spirit, his servant.

There have been, during the past year, many running to and fro amongst us,
and very many have been the public meetings in different parts; but oh, my dear friend,
I hope it is not uncharitable to acknowledge that
if they were such as dear +++_______+++ and a few others,
one could then more rejoice.
I often remember the expression in Jeremiah 22:22,
and greatly lament that many such expressions, both in his book and that of Ezekiel,
are but too plainly applicable to us now-a-days.
Many people of other persuasions see and feel the difference, the weakness,
and deficiency, alas! in our ministry.
Some of them like it all the better, and think we are coming round to them;
and we continually hear of their saying, on public occasions,
"`that they could find nothing to object to;`" while others, tender, seeking minds,
are grieved with these things, and go away sorrowful, saying,
"`We did not think to hear such preaching in your meetings:
we looked for something higher: we could hear such in our own chapels!`"
Ah, my dear friend, many are the such like wounds that pierce our very life,
so that it is truly like being killed all the day long!

Well, my dear friend, I seem as if I were sitting conversing with thee by thy fireside.
The remembrance of thy labour, and exercise, and afflictions,
and of the savour of thy spirit, is very fresh and precious to some of us;
and though far separated outwardly, yet art thou near in the bonds, I humbly trust,
of that blessed fellowship in which we shall not
be separated even by death from one another,
if indeed we are mercifully preserved in faith and patience to the end.
And oh, my dear friend,
crave that it may be so in the experience of thy unworthy
friend--that I may be delivered from every snare,
and kept humble and faithful to the last of my little day here;
and may the Lord be with thy spirit from day to day,
comfort and strengthen thee amidst thy manifold afflictions
with the rich consolations of His love in Christ Jesus,
and preserve and receive thee unto His heavenly kingdom at last.

With the salutation of dear love, I bid thee farewell,
and remain thy nearly united and sympathising friend,

L+++.+++ A. Barclay.

To +++_______+++.

+++_______+++, 1842.

My Beloved Nephew,

I have long had it on my heart to write to thee,
at least since we last met on a solemn occasion,
from a feeling of tender sympathy with thee under the loss of thy dear cousin R.,
which I can conceive is no slight one to thee,
inasmuch as his affectionate solicitude and counsel,
and his example of humble conscientiousness had become increasingly valuable to thee;
yet I have no doubt that both as regards thyself and the
others of his family (even the dearest object!),
this trial was permitted in wisdom and tender mercy
by Him who sees the end from the beginning,
and knows better than we what is most for our good.
As it regards dear R., great as the trial is to me to lose him, I am resigned,
in the full belief that it was well for him that he was taken from the evil to come,
for many would in all probability have been the snares and
the difficulties that would have attended his path,
and I often feared he might suffer from the injudicious notice and thrusting forward,
as it were, of kind Friends.
Ah, he showed his belief in and love to his Saviour by a simple
obedience to what was revealed to him by His blessed Spirit,
and being faithful to what he had received, is, I doubt not, accepted in the Beloved,
and entered into His joy in the heavenly inheritance.
And oh, how have I longed, my dear J., that thou might mark his footsteps,
which (as I have ever apprehended concerning him) were those of humble,
sincere inquiry after what was good and right in the best sense,
seeking to feel after the true judgment in the light of Christ,
even in its smallest appearances, and then an honest, noble, fearless following thereof,
however he might be laughed at by any who thought they had reason
or the common opinion of the worldly wise on their side!
And as humility attended his sincere inquiry or feeling after good,
so also humility attended (softening, seasoning,
and preserving) his firm and faithful acting thereon, so that he was kept in a lowly,
teachable state, which is the proper state for the true growing to be experienced.
And though the steps he had as yet taken were but few, yet they were fundamental ones,
considering his very many disadvantages; and I believe, as he once hinted to me,
that more would undoubtedly have followed as he was able to bear them.

And now thou art bereft of this dear relative, and more, this faithful friend,
at a critical time,
and I often think that though we may have a few dear
intimate friends with whom we are nearly united,
yet a faithful relative is still more valuable,
as he knows more fully from fellow experience all our besetments and liabilities,
our weak sides, and is more likely to tell us the truth.
This was the case with thy dear father and me, and oh,
how great is my loss of him! so that I can sympathise with thee, my dear nephew,
and the comforting language seems to arise whilst I write,
"`There is a friend that sticketh closer than a brother.`"
O seek to have this friend for thy friend, by showing thyself to be His friend,
by doing "`whatsoever He commands thee.`"
Confess Him faithfully before all that thou desires to be His only, His wholly,
to wear his livery truly (even a meek and lowly and watchful spirit),
to enlist under His banner of the cross to all that is of self,
to fight and suffer in His power and might for His precious cause,
for the faith once and still delivered to the saints,
whereof He is the author and finisher, not man.
Oh, be not ashamed of His words whether of command or of restraint,
"`tie them about thy neck and bind them upon thy fingers,`" that His lowly
and pure government in thee may be conspicuous in all thy conduct,
conversation, and demeanour,
so wilt thou season and gather others unto Him thy heavenly King,
and He will confess thee as His liege and faithful subject, redeemed by a mighty price,
and purified and prepared by His precious Spirit.

Oh I do comfortingly believe that thou hast been
so preciously visited and touched by Divine love,
that this is in favoured moments thy most earnest desire.
Oh, that nothing may in any wise hurt or hinder thy pressing towards this mark,
though it be a high one, even for the rich prize of our calling.
Let not the roughness, the narrowness, the solitariness,
or the many difficulties and trials of thy path,
deter thee or induce thee to turn aside into the many more easy looking by-paths,
or to sit down at ease short of the true rest,
which is the result of the true perseverance.
"`My son, if thou come to serve the Lord, prepare thy soul for temptation, set thy heart,
aright, and constantly endure, and make not haste in time of trouble.`"

Oh, how much there is in us that is opposed to His pure and searching government--even
the government of His holy light and word and Spirit,
that pierces to the quick, to the very root and ground of all things!
Oh, what a many-headed monster is self! and yet it hides itself,
looks and appears as a true lamb,
so that it may well be described in scripture as "`the old man which is corrupt
according to the deceitful lusts`"--for deceitful indeed are these lusts or inclinations!
so that we may often be dismayed at the sight and feeling of what the precious
light and Spirit of Christ opens to us of what is within us,
especially in our youth when the man`'s part (as dear Isaac Penington says),
that is the selfish nature, is so strong in us;
and then it is that the enemy would fain persuade us (as if taking the side of the good),
that it is all in vain to strive to overcome the evil,
for it is such a mass and so continually rising up
in us! but he is a liar as ever he was,
for help is laid upon One that is mighty, yea,
mightier in us than he that is in the world,
if we will but cast ourselves into the arms of His power,
by yielding to the smallest touches thereof in the secret of our hearts,
then His strength or grace shall be sufficient for us,
and in this true faith shall we be enabled to subdue kingdoms, work righteousness,
obtain promises, quench the violence of fire, stop the mouths of lions (spiritually),
yea, "`out of weakness shall be made strong.`"
So it is good for us to yield ourselves up to that
which shows us our condition without fear or flinching,
doubt or dismay, and this will beget in us a watchful, retired, and humble frame of mind,
yet clothed with an artless, cheerful simplicity.
Oh, this is the setting the heart aright, which enables constantly to endure,
and preserves from "`making haste`" either out of the necessary furnace or into
any step before our heavenly guide clearly points and tenderly leads.

This is what I have earnestly desired may be thy experience, my dear +++_______+++,
now that thou hast completed thy apprenticeship, and art in some sort thy own master,
though I trust not without law and subjection unto Christ.
Oh, that thy conduct, conversation,
and demeanour may be regulated by the Spirit of Christ,
and in the Divine fear at all times and under all circumstances,
then hast thou ground for humble confidence and trust
that all things shall work together for thy good,
and that the Lord will be thy never failing friend and helper in every time of need;
for He hath respect unto the lowly, but the proud He knoweth afar of.

L+++.+++ A. Barclay.

To +++_______+++.

1st or 2nd Month, 1842.

My Dear Friend,

I have felt much exercised in mind towards my dear friends
in the station of overseer for above a year past,
and have seen no way of relief until our late appointment,
when it came forcibly before me to write to nearly each one of them,
which I have been mercifully enabled to do in the cross, to my own feelings,
but I trust in a degree of heavenly might,
and greatly to the relief and peace of my own mind; and now, in looking towards thee,
my dear friend,
I thought I could hardly close this little labour of love without
endeavouring to do my little best to strengthen thy hands,
by acknowledging that I earnestly desire thy encouragement in a faithful,
unflinching coming up to the help of the Lord`'s cause,
which truly is worth pleading for and worth suffering for.
Oh, it will not do to be sitting down, as it were, in our ceiled houses,
content with merely wishing well to the cause of truth,
and merely mourning over the desolations of Zion;
but it is time for some amongst us to be fathers and mothers, to take a prominent part,
to come forward nobly, and plead and act for the truth, to feel and judge for the truth,
and not wait to see how others feel.
Oh, then, the need for such as these to be deep and inward in their spirits,
to mind the Master`'s voice, and to wait for the daily quickenings of His life,
whereby the true sight and feeling is given of what
is for Him (the blessed truth) and what against Him;
for it is not our appointment to any station that is the qualification or anointing,
but the Lord`'s humbling, quickening power and life,
which must be waited for and yielded to, and not shrunk from.
Oh! let us watch and see if He does not draw, listen if He does not call,
feel if He does not quicken--and if He gives us thereby senses for Him,
enabling us to see, hear, savour, and feel the things of His heavenly kingdom,
He will require us to use them in His holy fear,
and as His life moves that they may be strengthened,
and His praise may be perfected in us, howsoever weak, and poor,
and simple we may feel ourselves to be.
Oh! let us seek to be of perfect heart for Him, not partly so,
and verily He will stand by us and hold up our hands in His counsel and might,
and establish the work of our hands upon us in His peace and heavenly blessing.

I long for thy encouragement and strengthening thus to come forward,
for truly thou should be the one most looked to in
all our monthly meetings as a mother in Israel,
and the qualification is not man`'s arts and parts--no, nothing less;
but it is the true life and feeling which I believe thou desires to wait for and act in.
Oh! then, mayest thou cleave to the Lord`'s power, acknowledge it, and yield to it,
and not in any way shrink from it or forsake it.
So shall thy light break forth out of obscurity, and many shall say,
"`She hath been a succourer of many, and of me also.`"

I hope I write with a degree of true fear and humility,
feeling my own comparative childhood and weakness,
but a love to the precious cause of truth seems to
knock down all distinction of age or station,
and I trust thou wilt receive these few lines in the dear love in which they are sent,
in which I remain thy very sincere and affectionate friend,

L+++.+++ A. Barclay.

To +++_______+++.

1st of 2nd Month, 1842.

My Dear Friends,

My mind has been for many months past much exercised towards my dear friends,
who occupy the station of overseer amongst us,
and recently still more so since the subject of a
revision and addition to them has been before us,
so as to bring me under the feeling that I shall
not be clear in the sight of my great Master,
without taking up the pen to each or most of them at this time, whether new or old.
Great indeed is the responsibility of the station you fill, dear Friends,
inasmuch as to you is peculiarly committed the testimonies of the Spirit of truth,
to uphold and promote them before and among the whole flock,
both by example as well as by a tender and faithful
watching over and labouring with the flock,
for this purpose, whether it be in informing the ignorant, strengthening the weak,
encouraging the tender, seeking out the scattered, cautioning the unwary,
or warning the unruly--and where further steps are necessary,
that they be taken in true love and meekness, yet with holy firmness,
that the cause of truth may not be lowered by any remissness
on your parts who are appointed as watchers upon the walls.
These are important duties indeed,
and they had need to be clean-handed and of garments unspotted who are called unto them--and
none can rightly perform them but such as have the precious cause of truth at heart,
love it above all, yea, are united to it by subjection to the Spirit of truth.
Such as these are constrained first "`to take heed unto themselves,`" to see
that their own conduct is consistent in all respects with the testimony of truth,
and that they rule their own families well;
for if there be inconsistency in their families their own hands will be weakened,
yea tied, and their mouths stopped from speaking for their Master.
Moreover they (the true overseers) must be grave and sober,
not light or encouraging lightness--their wives must "`not be slanderers`"--they
must not be "`double-tongued`" (not appearing one thing to one,
and another thing to another), for a double tongue proceeds from a double mind,
from a heart that is not perfectly for the truth, but only partly so,
and "`a double-minded man is unstable in all his ways,`" he has no sound bottom,
as it were, no true judgment,
but is shifting about according to circumstances--neither
must they be "`greedy of filthy lucre,`" that is,
of the favour, or good esteem, or honour of man,
for that would hinder them from purely seeking and acting for the honour of God,
and the promotion of His cause of truth.

Oh! how faithfully will these then "`take heed to the flock of God over
whom they are made overseers,`" for being quickened by His life,
humbled by His power, and strengthened by His grace day by day,
how tender and susceptible will they be to the things of Christ,
so that they cannot but seek them more than their
own things! how jealous will they be of His honour,
and if anything grieves His Spirit either in themselves or others,
they will feel as if the apple of the eye were hurt! they
will have a true sense of what is against the truth,
and what for the truth, whether in themselves or others,
for the true life will give them a true sight and feeling.
Oh! this is the precious oneness with the truth,
by subjection to the Spirit of truth that we want more and more amongst us, dear Friends,
and how do I long that you who are in the above important
station may in an especial manner seek after it,
for your own sakes and for the good of the flock.
Oh, I beseech you to feel after and earnestly crave for the humbling
influences of the Lord`'s power upon your spirits from day to day,
and He will not fail to bring you down first in yourselves and then to
quicken you with fresh life and feeling towards Himself and His pure cause,
and then you will be constrained by love to Him,
to look round and see what there is for you to do for Him towards the
flock over whom you are appointed--where the weak may be strengthened,
where those who are tender may be encouraged even
to still greater tenderness to Divine convictions,
how the scattered may be sought out and gathered
to a closer attention to the dear Shepherd`'s voice,
as well as the unwary cautioned against unseen dangers, etc., etc.
Oh! it must be a humbling station,
it ought to be a humbling station to be rightly filled,
for the mere appointment is not the qualification nor the authority--but
the Lord`'s humbling power must daily be waited for,
His fresh anointing day by days ought after to keep you alive unto His cause,
as also to enable you to keep your own hands clean and garments unspotted,
that your hands be not in any wise weakened,
and to enable you to watch over yourselves first,
and then to watch over others in His fear.
Oh, let us humble ourselves under the Lord`'s mighty
and good hand that shows us any and all our weaknesses,
and He will help us with a little help from season to season;
enabling us to withstand the enemy`'s besetments and temptations,
and to overcome even our bodily weaknesses,
or show us what we should do that we hurt not His precious cause in any wise!

I trust you will receive this in the love in which it is sent,
for nothing but a sincere love to the cause or kingdom of Christ the Truth,
both in your hearts, my dear Friends, and in our meeting generally,
could induce or enable me thus faithfully to write,
and I trust also with tenderness considering my own
great weakness and liability to be tempted,
and to fall any and every moment,
were it not for heavenly goodness and mercy still following and upholding!
Oh, look not at the poor instrument in any way, but look to the Lord,
who can and will touch and quicken the heart, humble the spirit, and strengthen the soul;
and, oh! let it be so, let it be so, saith all that is alive in me,
who remains your sincere and affectionate friend,

L+++.+++ A. Barclay.

To +++_______+++.

Reigate, 1st or 2nd Month, 1842.

My Dear Friend,

My mind has often turned towards thee since we parted in much tender sympathy,
and I thought I must tell thee so in dear love.
Oh, my dear friend, let not thy heart sink within thee when thou comes to consider,
in thy solitary and exercised moments, what is come upon thee (as, I trust,
from the Lord),
when the weight of the service and the importance of the duties come over thee.
Fear not with man`'s fear, nor be afraid with any amazement;
cast not away the shield of faith, as though it had never been anointed; but, oh,
sanctify the Lord of hosts Himself, and let Him be thy fear, and let Him be thy dread.
Look off from all discouraging thoughts and vain reasonings--look up unto the Lord alone,
whose power is above every power, whose law is the truth.
Greater is He that is in you than He that is in the world,
so let thy eye be single unto Him,
unto His honour and the upholding of His cause and kingdom,
and thy heart simple in acting for Him, and He will never fail thee nor forsake thee.
His truth shall be thy shield and buckler, His grace all-sufficient for thee to direct,
strengthen, and preserve--yea, the Lord,
as thou cleaves close unto His power revealed in the secret of thy heart,
shall be thy confidence, thy sure and precious sanctuary, and His peace thy rich portion.

Mayest thou seek, then, to be exercised before the Lord day by day,
to know what He would have thee to do for Him and His cause,
and He will not fail to quicken in thee a just sense of things and how thou shouldst act;
and as thou yieldest thyself more and more to the humbling touches of His power,
that tenders thee and makes thee susceptible of His will and impression,
thou wilt find a gentle putting on by Him in the
true faith and in the simplicity of a little child;
and then see that thou refuse not Him that speaketh even in a little matter,
but give up to the motion of truth, and thou shalt wax stronger and stronger, able,
through thy God, to leap over a wall of difficulty, and to run through a troop of fears,
even as a valiant for the truth; but remember it must be by little and little,
if thou stops short in the beginning thou canst not come to the good end.
Oh, then, go on and be faithful, be simple in a forgetfulness of self,
no one fearing and nothing doubting,
and surely thy peace shall flow as a river with increasing force, and thy righteousness,
thy alms-deeds of true love to thy neighbours,
and thy acts of dedication to thy Master shall ever be as the waves of the sea,
one wave succeeding another in a succession of praises
to Him the great Giver of all good,
and the mighty Strengthener unto all good, unto whom be all dominion, and honour,
and praise forevermore, for He is worthy, worthy!

L+++.+++ A. Barclay.

To J. D.

Reigate, 1st or 2nd Month, 1842.

My Dear Friend,

My mind has felt much exercised on thy account for many months past,
both in tender sympathy with thee and in earnest solicitude for thee,
desiring the strengthening of thy hands and the deepening
of thy spirit and the increasing of thy weight;
and oh, if this be the case,
there must be a correspondent exercise and travail on thy part that nothing may in the
least weaken thy hands or shallow thy spirit by bringing it to the surface as it were,
or lessen thy weight by adding any degree of lightness thereto,
but mayest thou seek more and more after a deep dwelling and an inward feeling,
even a feeling of that and a dwelling and waiting
in that which gives dominion over all wrong spirits,
even the power of truth and life revealed within.
Feel after it, dear friend, day by day, yea, crave after the humbling, quickening,
strengthening influences thereof upon thy spirit morning by morning,
and endeavour to guard against what would scatter
thee in any wise from it through the day.
Ah, there are many things that have a scattering effect,
especially social and free intercourse with those who are
not in subjection to the humbling power of truth,
and thus we may be thrown off our guard for our Master,
and possibly lower ourselves and the cause before them, and join, as it were,
in their unguardedness,
rather than have a gathering effect in drawing them
nearer to the testimony of truth in themselves.

But oh! the weightiness of spirit which the life of truth will give us,
the true oneness with the cause of truth,
the true savouring and seeking the things that are of Christ above all things else,
the "`conducting ourselves as those that believe and feel God present,
which (as W. P. says) will keep our conversation innocent, weighty, and serious.`"
I long that thou mayest seek to be preserved therein more and more,
in which lies the true authority and the fresh anointing for every service,
and not in the mere appointment by man.
And oh, what an honest, fearless,
noble authority and dominion does this life of truth give us!
It makes us bold as a lion, upright pillars in God`'s house,
and therefore able to sustain much weight of burdens
and afflictions for Him and His precious cause.
Oh! it doth give a true trust in the Lord, a true stayedness of mind upon Him, and,
consequently,
preserves us in such a quiet confidence and a perfect
peace as tends to our unspeakable strength,
so that we are not fretted because of evil doers, nor yet yield to evil spirits,
but "`rest in the Lord and wait patiently for`" His arising,
still faithful in keeping His way, His charge committed to us,
so will "`He bring forth our righteousness as the light,
and our judgment as the noonday,`" and make all our way before us,
and cause our enemies even to be at peace with us!
Oh, then,
let us seek after this fresh humbling and anointing
by the life and power of truth day by day,
so shall our hearts be preserved perfect for our God and "`sound in His statutes that
we be not ashamed,`" able by Him "`to leap over a wall`" of opposing difficulties,
and to "`run through a troop`" of wicked spirits without and weakening fears within,
His truth shall be our mighty shield and impenetrable buckler,
and He will cover our heads in the day of battle,
and enable us to overcome all things through Christ, His dear Lamb,
who shall have the victory through and over all.

My mind has been drawn to address most of my dear friends in the station of overseer,
both young and old, appointed at this time,
and I think I may say I have felt an earnest desire for
their encouragement in a faithful labour for our dear Master,
believing that as there is a feeling and savouring of the things of the blessed truth,
so there will not fail to be a putting on in the
wisdom and power thereof to promote them,
there will be a continual inquiry of our Lord,
"`What more can I do for thee and thy precious cause?`"
There will not be a shrinking from exercise of mind in any wise,
nor a flinching from seeing too clearly what we should do for Him,
but there will be an honest and faithful looking round,
and a bending of the mind to see and feel where the weak may be strengthened,
where the tender may be encouraged even to still greater tenderness to Divine convictions,
how the scattered may be gathered into a closer attention to the dear Shepherd`'s voice,
as well as the unwary cautioned against the many surrounding and unseen dangers, etc.;
and where such duties and drawings are, there will be a yielding to the Lord`'s power,
enabling to follow them up, for it remains a truth,
that with sight and feeling comes strength, as yielded to,
even to act in the Lord`'s fear and for His honour and cause, and without fear, favour,
or affection of man.
Oh, how is the true overseership, even in the strengthening and gathering,
as well as in the tender dealing with those who manifestly err!
Therefore, my dear brother, be thou stedfast, unmovable,
always abounding in the work of the Lord, through yielding to His tendering,
strengthening power,
forasmuch as thou mayest verily be assured that thy labour shall by no means be in vain,
as it is in Him,
for He will establish the work of thy hands upon thee in His heavenly peace and blessing,
yea, the work of thy hands for His precious cause sake He will establish it forever,
and every little act in love thereto towards the
least of His brethren He will take as done unto Himself,
and it shall in no wise lose its reward.

Farewell.
In the pure love of the Gospel, I remain thy faithful and affectionate friend,

L+++.+++ A. Barclay.

To +++_______+++.

1st or 2nd Month, 1842.

My Dear Friend,

My mind seems drawn in Gospel love to salute all or most of my dear Friends,
whether old or fresh in the station of overseer,
believing that as you truly feel the weight of the
important duties thus devolving upon you,
so you will be humbled under a sense of the insufficiency
of your own natural powers for these things,
and will in proportion be earnestly concerned and deeply exercised before the Lord,
that He may establish you with His heavenly power and grace even from day to day!
Oh, it is by the humbling touches of the Lord`'s power, and the renewings of His grace,
that we are at any time quickened with fresh life from Him,
whereby alone we can rightly see and feel what is
against the pure cause and testimony of truth,
or what is for it either in ourselves or others,
and I believe we shall be accountable for every such degree of feeling mercifully vouchsafed,
and this true sight and feeling with the truth will lead
to a faithful and humble acting for it in the Divine fear,
and out of the fear of man, seeking only the Divine favour,
and not fearing to lose man`'s--it will not suffer us to
rest contented with merely admonishing those who err,
with merely attending to such things as if neglected would
bring us under the censure of men as deficient--but,
oh! the precious oneness with Christ the truth,
which is (through adorable mercy) attained by yielding
to the humbling touches of the Spirit of truth;
how tender and susceptible does it make us to the things of Christ,
so that we cannot but seek them more than our own things,
and we cannot but be jealous of His honour,
and if anything grieves His Spirit either in ourselves or others,
we feel as if the apple of the eye were hurt!
This feeling will lead us continually to query of our good Master,
"`What more can I do for thee and thy cause?`"
and we shall be constrained by love to Him to look
round and see where the weak may be strengthened,
where those who are tender may be encouraged even
to still greater tenderness to Divine convictions,
how the scattered may be sought out and gathered
to a closer attention to the Shepherd`'s voice,
as well as the unwary cautioned of unseen dangers, etc., etc.

And as it is not by our own natural powers that we can attain to this true overseership,
not a mere personal plainness or natural gravity of manner,
or a consistent education that will qualify us--so how earnestly
do I desire for my dear Friends thus appointed,
and thee among them,
that they and thou may be deeply concerned before the Lord day by day,
seeking after His tendering power to humble, quicken,
and strengthen thee for His work and service to which thou art appointed--His
fresh anointing day by day--for the mere appointment is not the true anointing,
or the true authority--but the Lord`'s power must be daily waited for fresh and fresh,
to keep thee alive unto His cause,
as also to enable thee to keep thy own hands clean and garments unspotted,
that thy hands be not in any wise weakened--so shall thy service for the Lord be clean,
and thy heart be kept perfectly for Him thy Master,
fixed in His pure fear and in His honour,
so that thou shalt not be moved in the day of trial,
and then He will honour thee and make thee honourable in His house,
and many shall have cause to bless the Lord on thy account, saying,
He "`hath been a succourer of many and of me also.`"
That thus it may be with thee,
and that thou mayest grow to be a father in the truth amongst us,
is my earnest and affectionate desire.
But, oh! remember it must be,
it can only be through the arising of the life and power of truth in thee,
by a yielding on thy part thereunto in true self-denial
and humble seeking before the Lord,
for thus will He "`be inquired of by`" thee to do these gracious things for thee.

L+++.+++ A. Barclay.

To +++_______+++.

Without date.

My Dear Friend,

My mind seems drawn, I trust in a measure of Gospel love, to salute thee in this way,
on the occasion of thy recent promotion in our little church to the station of
overseer--a station truly of important charge (and I believe thou feels it so),
inasmuch as the testimonies of the Spirit of truth are peculiarly
committed to your trust (who are thus appointed),
to endeavour to uphold and promote them,
both by example as well as by a tender and faithful watching
over and labouring with the flock to this effect,
whether it be in informing the ignorant, strengthening the weak, encouraging the tender,
seeking out the scattered, cautioning the unwary, or warning the unruly,
and when further steps are necessary, that they be taken in true love and meekness,
yet with holy firmness,
that the cause of truth may not be lowered by any remissness on your parts,
who are appointed as watchmen on the walls.
These are important duties indeed, and they had need to be clean-handed,
and of garments unspotted who are called unto them,
and none can rightly perform them but such as have the precious cause of truth at heart,
love it above all, yea, are united to it by subjection to the Spirit of truth.

Oh, dear friend, let not thy heart sink within thee because thereof;
say not within thy heart, "`Wherewith shall I serve the Lord?`"
neither let such reasonings overtake thee as that
the necessary qualifications are beyond thy reach,
or that it is not necessary to set the standard up so high.
Let others do as they may,
let us not lower the standard to suit our weakness and unfaithfulness
and unwillingness to bend under the Lord`'s qualifying power,
but rather let us with one consent resolve to serve the
Lord in what we know He requires with a willing mind,
doing service as unto the Lord and not unto men,
having our eye single and steadily unto Him, unto His honour,
and His recompense of reward, and not looking out at what others may do,
Oh! it is a humbling service; let others set it off as highly as they may,
it is a humbling service; and the more we bend our minds under it,
the more we shall be humbled under a sense of our
continued need of Divine guidance and wisdom,
strength and preservation in it; yea,
it is in the humbling that we shall know the true strengthening for it--feel
the Lord`'s power to arise up even under our own great weakness,
and making us to be strong in and for Him!

Therefore, dear friend, shrink not from a humbling view of the subject,
but seek daily after the Lord`'s humbling power,
that so thou mayest be brought to nothing in all thine own powers,
and mayest witness His life and strength to arise
in thee over all that stands in thy way,
and He will then never fail thee or forsake thee,
but will prosper thee as He did Joshua of old,
and establish the work of thy hands even in His peace and blessing--"`only be thou strong
and courageous,`" observing to do faithfully according to the law written in thy heart,
yea "`meditating therein day and night,`" and turning
not from it either to the right or to the left,
for then thou shalt make thy way prosperous,
and then thou shalt have good success--and lest thou should faint at any time,
how encouraging is the succeeding language, "`Have not I commanded thee?`"
Oh! it is the Lord`'s touches of life that quicken us and give us (as we seek
after and yield unto them) a true sight and sense of what is for His pure cause
of truth (either in ourselves or others) and what against it,
and we are accountable for every such favour!
And this "`sight of and feeling`" with the cause of truth will lead to a faithful
and humble acting for it in the Divine fear and out of the fear of man,
seeking the Divine favour, and not man`'s. Such shall not be moved,
for their heart is fixed in the pure love and service
of God--leaning not to their own understanding,
nor trusting in their own strength, but in the Lord`'s power and wisdom,
which alone can do His work, and is all-sufficient;
and oh! what a blessing are such to the flock,
and their labour shall not be in vain in the Lord;
but when the chief Shepherd shall appear they shall
receive a crown of glory that fadeth not away!

I earnestly desire that this may be thy blessed experience, my dear friend,
for surely thou hast been called to be a bright star in our little constellation hereaway,
even in the firmament of God`'s power, through yielding thereunto in all respects;
and oh! let it be so, let it be so, saith my soul,
that we may have increasingly thy faithful travail and help,
and He the glory due unto His name forever! for oh,
how great is His goodness and how great is His beauty!

With the salutation of Gospel love, I remain very sincerely thy friend,

L+++.+++ A. Barclay.

To +++_______+++.

Without date.

My Dear Friend,

My mind has felt much drawn towards thee for some months past,
both in tender sympathy under the loss of thy dear sister,
and in affectionate solicitude that the good end for which any
of us are thus tried may be thoroughly answered in thy experience.
I have several times been on the point of acknowledging
thus my feelings to thee since last 9th month,
but fears and discouragements have seemed as often to flow in and hinder; but now,
since our meeting together in the committee,
affectionate solicitude and tender sympathy have waxed stronger still,
indeed a feeling that perhaps thou mayest have been a little
discouraged that thy name was not brought forward,
seeing that thou wast under that appointment in +++_______+++. I may
truly say thou hast my tender sympathy under such a feeling;
but, oh, my dear friend, suffer me to say, I beg of thee,
not to let such a feeling be laid hold of by the enemy, to thy hurt and hindering,
either by inducing thee, on the one hand,
to give up the striving for and the following after that
for which I cannot but believe thou hast in time past known,
an "`apprehending of Christ Jesus`"--or, on the other,
by filling thy mind with reasonings or any idea of
prejudice or of hardness on the part of any,
which would indeed be greatly to thy hurt in best things.

But, oh, my dear sister, for whom I have deeply travailed,
according to my small capacity, ever since being one of you, may there be,
on this occasion, a thorough inward searching of heart, a humble inquiry of the Lord,
even in the tendering which His power will not fail
to bring over thee as thou yields to it,
"`What lack I yet?`"
Oh! what a need continually to return, as it were,
unto Bethel--to look back to the times of precious
visitation in days that are over and gone,
when the Lord sought to espouse us unto Himself--to
remember how He has proved us with many a blessing,
followed us with His goodness and mercy, as well as tried us with His bereaving hand!
Oh! what more could He have done for any of us,
and "`what iniquity (what lacking) can we find in Him`" that we should
in any wise "`go away from`" His tendering convictions and leadings,
"`and walk after vanity and become vain.`"
"`Yet lackest thou one thing`" was the answer of Christ to the rich young man formerly,
and it may yet be His answer of peace to thee by His blessed Spirit,
or that in attending to which thou shalt know thy peace to flow even as a river.

Ah, He alone can indubitably show us if there has been, and in what,
a coming short or going back instead of forward in any wise,
and let us mind His faithful discoveries.
"`Go sell all that thou hast`"--thou hast much of thy own that
may hinder thy becoming Christ`'s meek and lowly disciple,
and some of these things (even mental endowments) may look
very likely to be valuable in thy heavenward journey,
and it may be very hard to nature to part with them as into thy Lord`'s hand--but, oh,
be courageous, be faithful, give up all that thou hast, or that thou canst call thy own,
thy own will and wisdom, understanding and judgment,
desires and fears and hopes--let all go to the fire that is for the fire,
and to the sword and the hammer that is for them, that all may be broken to pieces,
and slain, and consumed that should be,
remembering that the pure and precious part will never lose by these proving operations,
but wax stronger and stronger,
more and more pure and precious to the Lord and for His service.
And be content to be little and lowly, weak and empty,
and to appear so before others--this is the Lord`'s
way to prepare us to be filled with His goodness,
and it is indeed His tender love to us to turn His
hand of power upon us inwardly or outwardly,
that we may be thus humbled.
Oh, let us not shrink from this His great goodness,
nor go away sorrowful when he gives us a glimpse of what He would do in
us and for us--but rather let us embrace the offers of His love,
and bend ourselves under His good hand--let us "`come,
take up the cross`" to our own willings and refusings, "`follow Him`" faithfully,
and "`verily we shall have treasure in heaven that faileth not,
and a crown of life that fadeth not.`"
And I do believe that it is as we thus know and bend under the Lord`'s forming hand,
that we become qualified for usefulness in the Church, His family and house,
in filling up such offices or doing such services as are
appointed us--for it is not man`'s natural judgment,
nor his natural or acquired gravity, nor yet his talents,
that are of avail in the things of God, for none knoweth His things but His Spirit; yea,
"`the natural man receiveth not the things of the Spirit of God,
for they are foolishness unto him, neither can he know them,
because they are spiritually discerned,`" but, blessed be God,
they are revealed unto us by His Spirit as we are humbly attentive
to His teachings and bend obediently under His government,
even in the faith that is of His own begetting.
Thus we come to partake of a blessed union and fellowship with God and Christ,
are engrafted into the true Vine, consequently partake of the true life,
which gives the true sight and the true feeling of
what is for the cause of Christ the Truth,
and what is against it--and the true sight and feeling will lead to the faithful,
humble acting in the fear of the Lord for His honour, and to His glory,
and the true edification of His Church.

This is what I long may increase amongst us more than pen can describe,
that so the true love and the true peace and unity may abound more and more; and oh,
my dear friend, come and yield thyself more and more to this blessed work,
first within thee and then without thee,
and great will be thy travail with us and help of us poor unworthy burden-bearers,
and thy heart shall fear more and more even in the true humility,
and yet be enlarged to receive further of the Lord`'s blessings.

L+++.+++ A. Barclay.

To John G. Sargent

Reigate, 1st of 2nd Month, 1842.

My Dear Friend,

As thy aunt informs me there is an opportunity of sending to thee,
I avail myself of it to ask thy acceptance of the Selections from my beloved
brother`'s Letters and Papers which is recently come out.
The one in allusion to his removal to Poole will I trust be as
a watchword of encouragement to thee under thy present state of
anxiety and of deep exercise (as I trust) before the Lord,
to know and be enabled to do His will and not thine own.
I do feel very tenderly for thee,
yet cannot doubt that thou wilt be directed even to an hair`'s
breadth in the way in which thou shouldst go,
in proportion as thou endeavours to keep low before
the Lord and close to His heavenly gift,
the word nigh in the heart and mouth, the light within, which will never deceive thee,
but ever lead and guide thee aright,
as the fiery and cloudy pillar (the type thereof) did formerly for Israel of old.
Therefore, mayest thou, as a true and spiritual Israelite,
keep thy mind inward to the light, grace, and good Spirit of Christ revealed within,
and then with life and light will come a true sight
and sense of whether and how thou art to stand still,
or whether and how thou art to move forward and act; yea,
and with the word of our heavenly King and Captain and blessed Saviour,
there will not fail to be power and faith, wisdom and patience,
abundantly given for what He calls unto or permits; so let Him be thy all,
and He will overcome all, and make a way where thou canst see none possible,
and cause all things to work together for good!

I have felt anxious to hear of thee since we parted at Croydon, but have not,
until this morning`'s post brought thy aunt`'s letter.
Perhaps it is well for thee to be thus in comparative retirement
and seclusion from Friends whilst thou art unsettled,
though no doubt pinching to nature.
To be alone with the Master is better than to have many outward counsellors,
lest we should lean on man.

Farewell.
I shall be pleased to hear further of or from thee
when thou art free to let me know how thou feels;
at the same time desire not to be intermeddling,
nor yet to draw to a poor weak instrument.
I remain thy sincere and affectionate friend,

L+++.+++ A. Barclay.

To +++_______+++.

Leytonstone, 8th of 3rd Month, 1842.

Dear +++_______+++,

Trials are sent for our good, to humble and instruct us,
and are varied according to our needs and our different dispositions,
so tender and so wise is our heavenly Father towards us!
I hope thou art not dull without us,
but finds various little jobs to do to keep things in nice order,
and enjoys some time in reading.
There is a nice book in the book-case that I know would interest thee,
the Life of Thomas Shillitoe, who was a poor shoemaker,
but a faithful minister of the Gospel,
who out of much weakness (naturally) was made strong in his Lord,
to go through many dangers and labours, and out of a very timid,
fearful disposition was made bold as a lion,
to stand before kings and princes and the fiercest looking of men.
So mighty is the Divine power,
as we yield to its smallest secret leadings and restraints revealed in our hearts.
So this is what I long for thee (and for us all) to give
up more and more to what is made known to us within;
for this is better than all outward teachings, whether by books or men;
indeed this is the object and design of all good reading, writing, and preaching,
to bring all to Christ in our hearts by His Holy Spirit, the hope of the saint`'s glory,
the best beloved of all the redeemed and redeeming people of all ages!

Here we shall know our strength, life, and peace to be continually renewed,
and ability received to worship and serve God acceptably with reverence and godly fear.
And when He speaks peace to us, who can bring trouble or make afraid?
Oh! the sweet flowing of His peace and the preciousness
of His talking with us in our hearts,
as we sit in the house, and as we are about our work, and as we walk by the way,
and when we lie down on our bed at night! it is more sweet than tongue can utter
or pen describe! and this is what we are all called to and may enjoy,
if we will but give up to the heavenly visitation of God`'s love,
whilst time is allotted us here.
So, dear +++_______+++, mayest thou be faithful to the Lord,
not looking out at others or minding what they may say; follow the good Master,
then shalt thou be made faithful in His Divine love,
and joyful in His holy peace! which is the earnest
desire of thy sincere friend and affectionate mistress,

L+++.+++ A. Barclay.
