== Chapter X

[.letter-heading]
To H. Grubb, on the Death of Her Mother, Sarah Grubb

[.signed-section-context-open]
Reigate, 18th of 3rd Month, 1842.

[.salutation]
My Dear Friend,

Deeply affecting, though sorrowfully looked for,
was the account transmitted to me yesterday by dear H. Impey.
Ah!
I do indeed tenderly feel for you, and thee especially, my dear friend,
who hast been so closely thy dear mother`'s affectionate and careful attendant.
It must indeed be a keen stroke,
although in the course of nature expected latterly from year to year.
Yet how great must be thy comfort in the consideration
that thy great loss is her exceeding gain,
in the assurance that _it is_ well with her,
that she is gathered to the generations of the just who are gone before her,
and is forever at rest,
where the wicked cease from troubling and the weary are at rest in the Lord!

Ah, it was for this blessed end she lived and breathed, strove and toiled,
even in and by the life and power of truth.
Yes, to this she testified abundantly in and by the same--the consummation and realisation
of those views which can be only seen while here by the eye of faith,
and as through a glass darkly in comparison of the full fruition and everlasting enjoyment!
How does the contemplation of the bliss and exaltation of such as are thus translated
seem to fill one with humble adoration and grateful praise to God their Redeemer,
who truly is "`rich in mercy`" and great in love,
and delights to "`show forth the exceeding riches of His
grace in His kindness towards us through Christ Jesus!`"
And though the tear of natural affection must be allowed to flow abundantly,
yet let us not sorrow as those that have no hope,
but rather seek after heavenly ability to stay ourselves
upon Him who smites us in a tender part,
and thus to bless His holy name even for that which seems almost
severe to our nature! so will He bring good out of seeming evil,
and give us the grateful, humble language,
"`It is good for me that I have been afflicted,`" and "`I
know that thou in very faithfulness hast afflicted me;
who is like unto thee, or to thy faithfulness round about thee!`"

Ah, the loss of the Church is great--one is ready to say not likely to be repaired!
Yet surely the Judge of the whole earth will do right;
He doth ever care tenderly for His poor afflicted people, and He can raise up,
even of those comparable to the stones of the street,
to be His children in the faith of Abraham,
and give them to testify for His name and truth, and to celebrate abundantly His praise;
and there is nothing too hard for His mighty power,
or too great for His tender goodness to do for all those who love
and faithfully serve Him even through many tribulations.
Oh, then, my dear H., whether we look at our own or at the Church`'s loss,
may we increasingly and over all look upward, yes, look upward, and breathe upward,
and all will be well and work together for our abundant good and blessing.

Farewell.
With dear love to you all, I remain thy sincerely affectionate and sympathising friend,

[.signed-section-signature]
L+++.+++ A. Barclay.

[.postscript]
====

P+++.+++ S.--I do hope to pay my last tribute of love and unity
with my dearly beloved and honoured departed friend.

====

[.letter-heading]
To J. B.

[.signed-section-context-open]
Reigate, 10th of 6th Month, 1842.

[.salutation]
My Dear Friend,

How greatly do I feel for you all in the approaching loss of dear +++_______+++,
an elder worthy of double honour, I truly think, in these degenerate days,
when but few are the truly baptised!
How greatly we missed her this yearly meeting with us!
She had been, I think, four years with us,
and we loved her more almost _every day_ of her stay--the savour of her spirit,
through the daily exercise, was so sweet and strengthening to us,
and her example of faithfulness to individuals was very instructive.
Ah, there is more of this wanting amongst us, especially among elders,
or things would never have got to the state they are in.
But, then,
there must be a true anointing with the right eye
salve that they may see aright--that is,
for the truth and with the truth (or the mind of truth);
otherwise there may be an acting _against_ the truth instead of _for_ it,
as I fear has lamentably been the case of late in some instances,
even by some of our elders speaking to and finding fault with those who really
are on the ancient foundation and upholding the pure testimony of truth,
to their great discouragement and grief, whereas they forbear to touch,
and rather smooth over with love and peace,
those who _really are_ the true troublers of Israel
and the sowers of discord and disunity amongst us,
whatever they may profess of and talk about love and unity and peace.

I had a dear faithful friend and minister with me this year, one of the _old-fashioned,_
upright, downright sort,
that was excellently concerned in our last sitting of the select meeting,
to address both classes, and especially the elders,
bringing forward the instructive instance of John Crook,
whose ministry latterly had become wordy and lifeless,
but when spoken to by the judicious and deeply feeling elders of old times,
received it in the meekness of the true Gospel minister,
and it was blessed to his recovery; for he was silent some years,
and then came forth again in a little humble, trembling way as at first, pure and living,
and thus was preserved to the end.
Oh! how excellent is this, it is as things ought to be with us.

Our yearly meeting was deeply exercising and sorely trying to many of us,
although there is much said about the solemnity and favoured times, the harmony,
and unanimity; but, alas, my dear friend, _all is not gold that glitters!_
Never was there so much cause for mourning and girding
with sackcloth on behalf of the _leaders of the people,_
as well as the people;
for the pure testimony of truth is sadly reproached by the inconsistency amongst us,
and the world sees and points the finger at it.
And our meetings for discipline, both select and general are painful times,
for man`'s will and wisdom, arts and parts, and contrivance are uppermost;
and there is no room for the Lord`'s power to humble, and move, and act,
which should be over all and have the praise of all.

The mouths of the mourners were closed in silence pretty much,
except a few broke through, as it were, in a weakly, trembling way; nevertheless,
others seem to have nothing but peace and brightness to prophesy of,
and in large measure!
Well, the day that is coming shall try every man`'s foundation and building,
and then the hail of the overflowing scourge shall sweep away the refuge of lies,
and destroy the various hiding-places men have got
to get away from the piercing light of God`'s Spirit;
and the wall that the prophets have been building up very fair and high,
and daubing over to look so beautiful and exact, shall come tumbling down!
Ah, I may never live to see it,
but I do live in the faith (as _dear_ Sarah Grubb lived and died in) that,
after this sifting and purging, a brighter day shall dawn yet upon us,
and the true Church shall look forth clear as the sun, fair as the moon,
and terrible as an army with banners,
for the blessed and _unchangeable_ truth shall yet prevail and reign over all.
So be it, saith my soul; and oh! that we,
who are left a little longer on this beautiful (but, alas, defiled) earth,
may be so strengthened and helped from season to season as to possess our souls in patience;
even to keep the word of the Lord`'s patience, that so we may be,
through His adorable love and grace and mercy in Christ Jesus,
kept in the hour and day of trial and temptation
that shall come to try them that dwell upon the earth,
and be favoured to stand in our lot and to rest in Him at the end of the days.
It is a comfort to remember that, however sifted,
not one grain of _weighty wheat_ shall be lost;
also that a mark shall be put on the foreheads of those who sigh
and mourn for all the abominations and transgressions in the land,
and that they shall be spared in the day of slaughter,
and those that fear the Lord and think of His name (or power) shall be
written in His book of remembrance and spared as His precious jewels.

We had a precious visit from a dear Irish farmer, Jacob Green, into our meeting;
it seemed to bind up our wounds and revive as with a cordial!
Another time at one of the meetings for worship,
a dear farmer from Lancashire spoke excellently to +++[+++the great comfort of some of us]. Oh,
it is through these dear simple,
unpolished ones that the golden oil seems to flow
so purely and unmixed to the refreshing of the heritage;
or rather, I might better say, to the causing the lamps to burn up with fresh vigour,
and thus the Lord`'s power is over all as it should be.
He spoke of the precious times he had had at the _plough stilts,_
calling on the dear youth to yield up to that which visited and tendered their minds!
Oh! it is a favour there are still such instruments preserved and raising up amongst us;
and I do believe there is a precious visitation extended to the dear youth,
and many are embracing it.
So, dear friend, let us, in the midst of our tears, cheer up and be faithful,
and cleave to the Lord`'s power, which is all-sufficient and over all,
and that will _make_ and _keep_ us _humble_ and _in unity with His_ will,
and then nothing will surprise us or greatly move us,
neither will anything harm us or separate us from His precious love in Christ Jesus.
Ah, what a tender thing is the work of Divine grace in any way,
how easily snibbed and hindered!

Do you ever go over and feel with and for them +++[+++at +++_______+++ meeting]? Ah,
we must stir up the gift in both of our stations, dear J.; I mean,
yield to little pointings, and way will be made for us where we may see none,
to hand a cup of cold water to a fellow-pilgrim;
and as we thus use the little strength given or held out to us,
we shall gain more strength.

I have been very ill this spring, but, through favour,
I came back from yearly meeting _better_ than I went.
The cough is now at last gone, and I am in comfortable health,
for which blessing and _many_ others I can never be too grateful or render enough.

Farewell, dear friend, with love to thyself and husband.
Thy sincere and affectionate friend,

[.signed-section-signature]
L+++.+++ A. Barclay.

[.letter-heading]
To Marianne F.

[.signed-section-context-open]
Reigate, 23rd of 7th Month, 1842.

[.salutation]
My Dear Friend,

It seems a very long time since we met, and much has transpired since then to us both.
It would be very pleasant to be able to meet again,
to mingle our feelings both of grief and mourning, as well as of hope and longing for,
I cannot say much of _rejoicing,_ for that is scarce now-a-days,
except when by the eye of faith we seem permitted
(in mercy to cheer and animate us on a little),
to have a glimpse of a brighter day,
when truth shall more eminently and evidently prevail and reign over all!
Ah, _this_ seems to give wings, as it were to the soul,
to mount upward from the tribulations of this transitory scene,
and causes the temple of the heart to resound with praise to Him whose power is over all,
and whose kingdom is an everlasting kingdom!

If we are not faithful we may be laid aside as the Israelites were! and oh,
how applicable are many passages in the prophets respecting them to our condition now!
Well, dear Marianne, I expect thou feelest it to be so,
and hast much to mourn over in that large meeting (besides
looking into thy own house or heart!) and oh,
how do I desire for us who feel these things that we may not get too much into discouragement,
whether in the looking outward or looking within, and so give the enemy place,
as it were; but oh, let us increasingly look _upward_ over and in all,
and breathe upward too for continual grace to help in time of need!
Oh, let us breathe after and feel after the daily quickenings of life upon our spirits,
that we may be helped out of the many hindering, clogging, and defiling things around us,
and kept in the _living sense_ and _sight_ of the things of God and of Christ,
the blessed and _unchangeable_ truth;
for the true life gives a true sight and sense (otherwise we are but blind and dead,
profess what we will), and this must not only be thankfully and humbly received,
and faithfully occupied with, but a renewal thereof diligently waited for,
in order to be kept living and tender in the true seeing and feeling,
and tasting of the things of the dear Master!
Oh, that it may be so with us,
and then we shall without fail be found fresh and fruitful,
sound and savoury to the praise of the great Giver and mighty Strengthener!

I find from dear Hannah Marsh that you are going to move.
I cannot tell where it is, nor what is the little meeting thou wilt belong to;
is it in Cheshire?
It will be a great _shift_ to thee! and I shall much feel
for thee in the leaving the few with whom thou feelest united.
Sometimes a transplanting does us good like the plants; but I am a witness,
and so I should think thy dear sister is,
that _apparently_ snug corners and little meetings
are by no means devoid of trials in various ways.
I often think of a saying of dear old Thomas Shillitoe,
that the old enemy creeps up into snug corners as well as other more open places.
I feel that our little meetings are replete with trials and burdens.
Sometimes, alas! (the view seems thereof), to almost cast one down too low;
but how animating is the language of the apostle! "`Whom resist, steadfast in the faith,
knowing that the same afflictions are accomplished in your
brethren that are in the world;`" also the reflection that
though chastisements and trials are grievous for the present,
yet if we are patiently exercised thereby,
they afterwards yield the peaceable and peaceful fruits of righteousness.

I was in a very weakly state at yearly meeting time,
having had a long influenza cold and cough for nearly two months,
and was very strongly advised and _warned_ not to go there; but, wonderful to say,
and I hope I look upon it gratefully,
I was favoured to gather strength every day (after the first day or two of seasoning),
even during such a _great trial_ of it,
both by meetings and by much excitement in seeing dear friends at my lodgings,
so that I returned home nearly well, except my cough,
but which I told dear Ann Conning _she helped to knock off_ in a short time,
by an acceptable and strengthening visit of three weeks afterwards.

I often remember his +++[+++Alexander Dirkin]
laying _thee_ upon me to endeavour to do what I could
to help and cheer thee along the rugged path.
I am intending to remove into another house here this autumn,
occasioned by a new and rather untoward landlord.
This has rather an unsettling effect, for I enjoy quiet, and thought I should die here;
but I strive to view it all as an inn to a better home.
We must not mind being shifted about, nor be too particular about our fare,
so we are but journeying on aright to the good end.

I hear dear +++_______+++ is expected at Uxbridge next week.
How we do miss her dear husband and dear Sarah Grubb! and I thought at yearly meeting
(and before it too) that it seemed as if the enemy took advantage of our depression,
and lifted up his heel and horn the higher!
But they are taken from the evil to come, for surely a day of shaking must come,
when the root of all things will be searched,
and the idols and painted images will be cast down;
and then it will be clearly made manifest who are on the Lord`'s side,
and who are really on the enemy`'s side and doing his work,
however plausible their language and appearance may be.
Oh, that we may seek after the quiet habitation,
that we may possess our souls in patience, that we may be able to stand in this evil day,
and having done all and suffered all,
according to the Divine will and through Divine grace may
be permitted to stand with acceptance through the Beloved.

[.signed-section-closing]
I remain thy affectionate friend,

[.signed-section-signature]
L+++.+++ A. Barclay.

[.letter-heading]
To M. S.

[.signed-section-context-open]
Reigate, 23rd of 8th Month, 1842.

[.salutation]
My Dear Friend,

Thy kind note was gratefully received and proved acceptable,
and I do believe it is well to attend to little pointings in this way,
to hand what may be comparable to but a cup of cold water,
for it will not lose its reward,
and we know who declared "`Inasmuch as ye did it unto one of the least
of these my brethren (oh! what condescension!) ye did it unto me!`"
But alas! how often are we (or am I) apt to reason away these little feelings of attraction,
doubting how their fruits may be received,
or fearing we feel not sufficient to warrant our giving up to them; although I must own,
with respect to myself, I ever desire to try the fleece both ways,
lest I should move in anything like the willing and running and haste of the creature,
and so thereby self might get strengthened even by that which looks likely to slay it!
Ah! my dear friend,
the present is indeed a time when we peculiarly need all the little
cups of help that we can have through any of our dear fellow-pilgrims;
for how many are the burdens, how grievous are the continual wounds,
how deep is the mourning,
how great is the discouragement of the present day in our poor backsliding Society!
so that those to whom it is given to feel a degree ever so small of sympathy
with the poor burden-bearers (who weep as between the porch and the altar crying,
"`spare thy people O Lord,
and give not thy heritage to reproach!`") had need to be
faithful in pouring in their little mite of balm.

Ah!
My dear friend, some seem able to prophesy smooth things and to cry peace, peace!
Some seem able to think that all things are well with us and improving;
but as for poor me, the roll to me is written within and without with mourning,
and lamentation, and woe! for alas! how is the gold become dim,
and the fine gold changed! how are we become as "`an assembly of adulterers
and adulteresses,`" for we are adulterated from Christ the life,
whose life is the light of men, consequently death and darkness is crept over us,
while we hardly know it! and surely we are going from bad to worse,
and unless our downward course be arrested, we shall come, as the Jews were,
cast off as a people, and mingled with the common mass of professors,
yet be distinguished among them by deserved reproach and just despising!
Yet I have a humble hope that there will be a little remnant, a worthy few,
who through watchfulness and holy fear will be enabled to keep their garments undefiled,
and be permitted to stand in the evil day, yea,
will be further and further purified by these deep trials and made white!
And I am at times comforted in remembering what my dear brother
John says at the end of the letter (at page 274 of the [.book-title]#Selections#),
viz.:--"`__However we__ may be permitted to be trampled upon and to be broken to pieces,
__yet the blessed truth shall outlive it all, and emerge out of the very ruins,__
if it must come to that.`"
This shows his sense how that the truth is not dependent on us as a people,
but that the holy standard thereof was mercifully given to us to uphold before the nations,
and if we forsake our own mercies,
we may be permitted to be trampled upon and broken to pieces,
but the holy truth would still arise transcendent
above all and at last stand and prevail over all!

This is an universal view indeed,
and is truly cheering in the midst of much around to cast down.
The Lamb and His followers shall have the victory!
Oh, that we may all seek to be found _in Him,_
to be clothed with His Spirit and truly subjected thereby under
His government! then shall we truly reign with Him over all,
although now for a season, if need be, we are in heaviness through manifold temptations,
and partaking with Him in His deep sufferings for the body`'s sake which is His church.
Oh! then, that we may be enabled, like those of old, to endure unto the end,
as seeing Him who is invisible!
Oh! that we may be enabled with single eye to His light and firm
confidence in His power to look unto Him who endured the cross,
despising the shame,
lest we be wearied and faint in our minds in the heavenly race
towards the mark for the rich prize of our high and holy calling;
that so running with diligence and fighting the good fight of faith,
we may be permitted to obtain, and to lay hold on eternal life,
whereunto we are graciously called!

Farewell, my dear friend.
I remain with dear love from us both, thy affectionate and sincere friend,

[.signed-section-signature]
L+++.+++ A. Barclay.

[.letter-heading]
To +++_______+++

[.signed-section-context-open]
27th of 8th Month, 1842.

[.salutation]
My Dear Young Friend,

Although the cause for my writing to thee as I promised is now at an end,
yet I do not think I shall be clear without, in some degree,
testifying to thee how I feel in regard to the trying
subject thou alluded to the other evening,
believing that the pure witness for God within, even the Spirit of Christ,
who is called the faithful and true Witness, will unite therewith,
to which I ever desire to appeal, and _not_ to the judgment and spirit of the creature,
which thou knows have both need of _restraining_ and of _regulation._
There is an old saying,
"`A man is known by the company he keeps,`" and as I think this is very true,
so I also think that the society we have and seek has a great effect upon us;
our ideas and tone of mind are too apt to get moulded
or leavened by it very imperceptibly to us,
and that if we are in the continual or very frequent habit of associating with
those whose principles and profession are in many respects contrary to ours,
we shall be throwing ourselves in the way of being
weakened from our principles and profession,
if not of being tempted to cast them aside with such--at
least I have found this to be the case with me;
and even at this time of my life I dare not mingle much with others,
feeling their society tends to revive the old nature in me,
which was flattered and pleased with their maxims and spirit;
and to leaven me in a way that upon solid and serious feeling does not bring
true comfort and peaceful quiet to my mind--and if so with one declining in life,
and desiring above all things to press towards a heavenly inheritance,
how much greater must be the effect upon those who are just entering, as it were,
into this perilous world;
with less experience and less accustomedness to seek for best strength,
and in whom the natural propensities are stronger!

I do trust I can fully enter into the feelings of the young,
having in former days had I think, I may say,
_intense_ enjoyment in the sweets of friendship;
neither am I so narrow-minded as to say abstain from _all_ association out
of our Society--but let such as thou associates with be _picked men,_
that is, selected with an eye to the advice of the truest Friend,
the best Guide and Counsellor, even thy Saviour,
and let thy hand be tender and susceptible to the gentle
pressure of His restraints or drawings away from any,
for thou knowest He loves thee too truly and dearly to wish thy hurt or thy misery,
but seeks thy most substantial and enduring comfort; and surely, dear +++_______+++,
they cannot be thy true friends whose company would in the least degree
draw thee away from or lessen thy attraction to the Beloved of souls,
thy attention to His inward voice that is "`still and small,`" or thy
inclination to take up the cross openly and confess Him before men.

I trust the young men thou mentioned to +++_______+++ are serious characters.
A man may be moral,
but if he be not serious (religiously disposed) his society still
may be very weakening and even pernicious to good principles,
especially those of our _high_ and _holy_ profession.
Of course thou wilt want society;
as I said before I am not hard to the feelings of youth, but mayest thou use _sparingly,_
with _fear and caution,_ that which is likely to have a weakening tendency,
if thou canst not avoid it.
Thy dear father`'s company will always be agreeable to thee,
I trust (while he is yet spared to us).
I regret that our young men Friends here are not as suitable as they should be.
But I believe I must go further and say, my dear friend,
that it is my feeling that late hours for associating with any is very dangerous;
as well as the habit of smoking,
for young people to get into it leads to temptations that may be of serious consequences.
I believe thou would find far more solid satisfaction
on resting thy head on thy pillow at night,
if thou wert to devote the _short_ time that _should_ (for _health`'s_
sake) elapse between closing the shop and going to bed,
to suitable reading and meditation or retirement of mind,
seeking after heavenly searching into the actions and feelings of the day,
heavenly humbling and heavenly strengthening.
By suitable reading I mean such works as will innocently instruct and edify,
leading the mind still upward to the source of all good and the centre of all
true worship and praise--of which the present day is indeed privileged with many;
many that are truly interesting, both in biography, natural and experimental philosophy,
besides those of a more serious cast.

But, oh, my dear friend, as ever thou values the welfare of thy immortal soul, shun,
I entreat thee,
those poisonous books of Byron as thou wouldst the venom of an asp--they are so insidious,
so defiling, thou canst hardly read them without being hurt.
Watch the tenor of thy mind in reading them,
and thou wilt find it drawn farther and farther from the little and lowly,
the pure and purifying witness for God in the secret of thy heart,
but that the man`'s part, the creaturely nature, will, wisdom, _imagination,_
and _reasoning_ is set up and strengthened thereby, which it is the work of true religion,
or the power of God, to bring down and subject;
and if thou dost not feel this tendency to be the case,
verily it is because thou art blinded by the delusion of the enemy by
having quenched the little glimmerings of the light of Christ in thy heart,
for there is not one, as I believe, who has been really touched by the Divine power,
but what has had this feeling concerning these publications.

And now again,
in reference to the words "`fear and caution`" used
above--what I mean is with _fear for thyself,_
and with caution or watchfulness for Divine help,
for "`Happy is the man that feareth alway;
but he that hardeneth his heart shall fall into mischief.`"
It is those who are mistrustful of themselves,
who feel how weak and unable they are of themselves to resist temptation,
or to do and keep in that which is good and right,
that are likely to receive the Lord`'s precious strength, and guidance, and preservation;
but those who are self-confident, and think they can stand,
He is likely to turn from and leave to themselves,
and then they do fall into mischief indeed.

Be assured, my dear young friend,
that humility and meekness are the truest ornaments both to man and woman,
they are the offspring of the true wisdom of which it was said,
"`She shall give to thine head an ornament of grace,
a crown of glory shall she deliver thee,`" and again, "`Riches and honour are with me,
yea, durable riches and righteousness.`"
Ah, then, that thou mayest seek after that wisdom,
the beginning whereof is the fear of the Lord,
and the fruit thereof true humility and meekness,
so shalt thou witness it to be a fountain of life,
continually preserving from the snares of death;
delivering thee both from the way of the evil man,
who leaves the paths of uprightness to walk in the ways of darkness,
whose ways are crooked, and they froward in their paths,
as well as from the strange woman who flattereth
with her words and forsaketh the guide of her youth.

Oh, seek after this wisdom as for silver, and cry after the true knowledge,
the knowledge of God`'s holy will and ways, as for daily food;
for the Lord giveth wisdom, out of His mouth cometh knowledge and understanding;
and He waits to be gracious unto us, to make known His words unto us,
and to pour out His Spirit upon us,
if we will but turn at His reproofs and receive His instruction; and if we do so,
then shall we walk in the right way safely, and our foot shall not stumble;
when we lie down, we shall not be afraid; yea,
we shall lie down and our sleep shall be sweet.
Humility and meekness, also, are most in accordance with our blessed Saviour`'s example,
who was meek and lowly in heart, and exhorted to the denial of self,
and declared that except we become as little children,
we cannot inherit the kingdom of heaven, that is, become His disciples.
Now it struck me the other day, that that disposition which seemed to set up self,
and wished to have justice done to self, was contrary to this true humility,
neither is it so likely to see clearly what is right.
It is the humble that are shown the right way,
and the meek who are led in the paths of _true_ judgment;
they are teachable and easily taught, being mistrustful of self,
and their path is more likely to be safe.

And now, my dear friend, I will bid thee affectionately farewell,
having relieved my mind;
and will conclude by directing and commending thee
to the great and ancient principle of our profession,
the Spirit of Christ in the secret of the heart, which will unfailingly show thee,
if thou art attentive and obedient enough to its lowest whispers and discoveries,
with whom thou mayest associate with comfort or impunity; will strengthen, restrain,
and preserve thee aright when there, even in humility, watchfulness, and the Divine fear,
and it will also assuredly show thee where thou mayest _not_ go but at thy peril.
Oh, then, cleave unto Him, and depart not away,
and mayest thou increasingly seek after His precious company and delightful converse,
of which thou canst never have too much; for He is the truest Friend, the surest Guide,
the wisest Counsellor, and the most blessed Comforter.
Blessed be His name over all forever!

[.signed-section-signature]
L+++.+++ A. Barclay.

[.letter-heading]
To a Child

[.signed-section-context-open]
Reigate, 17th of 10th Month, 1842.

[.salutation]
My Dear +++_______+++,

I hope thou will not feel tried with dear +++_______+++,
but she read me some of thy letter to her,
knowing I should feel tenderly interested about thee,
and so it has led me into very affectionate sympathy with thee, my dear girl,
respecting evil thoughts,
and I thought I could not do otherwise than take
up my pen and write what I feel come into my mind.
Ah, I do and _can_ feel for thee, dear +++_______+++, for it is no new thing to be thus tried.
Thou hast many neighbours and fellow-sharers in such trials,
and I am not one of the least.
But I rejoice in that thou _feelest_ thus _tried_ by them;
this is the tender love of thy heavenly Father to
make thee thus sensible of their evil tendency,
and so be tried by them.
Oh, cherish this sensibility,
and do not crush and quench it by turning away from
and seeking to divert thyself from such feelings.
Oh, no;
this would indeed be grieving thy heavenly Father and the good Spirit of thy dear Saviour.

But perhaps thou wilt say, what am I to do to get rid of such troublesome intruders?
I would affectionately answer thee, dear,
if thou cherish that which makes thee sensible of them,
it will by degrees purge them all away and deliver thee from them--not in thy own time,
for _this_ would be directly instead of gradually, and then this would be easy work,
and self would be in danger of getting up and vaunting of its victory;
remember the Israelites did not all at once destroy their Canaanite enemies.
But He who gives thee this sensibility of their evil tendency,
knows best _when_ and _how_ to deliver thee from all
the evil enemies of thine own house or heart,
and which I doubt not thou often feels to be both many, and lively, and strong,
and perhaps art sometimes ready to conclude thou _never shalt_ be able to conquer them.
But oh, never fear, but yield thyself up to this power that visits and shows thee them,
and He will _not fail_ to conquer them for thee and in thee;
for stronger is He that is in thee,
though He appear in thee only as in a very small and foolish looking way,
as a little seed of life and light,
a little leaven that would leaven thee into His meek and lowly nature; yea,
as a secret power or word behind thee that seems
to rise up against all that is evil in thought,
word, or deed, and testifies against it.
I say stronger is He that is thus appearing in thee
than all the powers of the worldly spirit,
the fleshly mind, or the stratagems of the cruel enemy.
So be not afraid, only believe, that is _receive_ and _yield_ to His power,
and thou shalt be made more than a conqueror through Him that loved thee.

But, my dear girl, in reference to those evil thoughts that are so constantly rising up,
I have always found and still find--for I am still tried and tempted,
if this will be any encouragement to thee to know of,
and it is no sin to be tempted thou knowest,
but the sin is in yielding to the tempter--I have always found that the best way is
to endeavour to gather the mind inward to the power of truth that shows the evil thought;
do not be _fretted_ because of the evil,
but try to turn as _quietly_ as possible from the evil to that which shows it,
and which stands ready to overcome it with good, even the power of truth,
the light of truth, the Spirit of Christ in the secret of thy soul.

In thus ceasing from thy own frettings and disquietude because of the evil,
and from thy own strivings to reason thyself out of the evil as it were,
and in thus simply and quietly turning inward and looking upward,
as a dear little child looks up to its mother to lift it up out of any danger,
thou wilt find that _He_ who is mighty and very tender is _ever_ near to succour thee,
to stay thy mind in quiet and in abhorrence of the evil,
and to season and sanctify it unto Himself.
And as thou art practised in this inward work and watchfulness unto prayer, that is,
unto breathing unto the Lord,
so thou wilt become more and more practised in knowing and understanding
thy dear Saviour`'s voice and heavenly inward speech.
And oh,
that nobody and nothing may ever turn or divert thee
away from it in any wise! for thou knowest,
my dear, that no man or woman upon earth can ever give thee His precious peace;
so never think to obtain it any other way than by hearing and obeying His voice,
thus wilt thou _prove_ thy love to Him,
and thus wilt thou truly enjoy His love and manifestation of Himself to thy soul;
and oh that thou mayest experience the blessed promise to such lovers
of the Lord Jesus abundantly fulfilled--"`My Father will love him,
and we will come unto him and make our abode with him.`"
And, my dear +++_______+++,
be sure thou always turns away from whatever does _not_ give
thee a feeling of peaceful quiet to thy mind;
and though thou canst not understand _why,_
yet be content to be faithful to inward feeling, and patient before the Lord,
and He will gradually open all to thee that is necessary for thee to know.

So farewell, my dear, for tonight.
I shall often think of thee and +++_______+++ together,
and long that you may go hand in hand together along the good old way to the kingdom,
the _strait_ and _narrow way to self._
With dear love, I remain thy truly affectionate friend,

[.signed-section-signature]
L+++.+++ A. Barclay.

[.letter-heading]
To B. Bishop

[.signed-section-context-open]
+++_______+++, 1842.

Such a token of true sympathy and unity of spirit was truly grateful.
I trust I received it as from the good hand of Him
who hath pity on the workmanship of His hands,
and who, when He sees meet to prove, most graciously sends a precious cordial to sustain.
I desire to remain under such close exercise and
deep baptism the whole time that is appointed,
that so the good end therein may be answered and not frustrated.

[.signed-section-signature]
L+++.+++ A. Barclay.

[.letter-heading]
To A. R.

[.signed-section-context-open]
10th Month, 1842.

I am one for gathering up the fragments that nothing may be lost,
of such as testify to the sufficiency of the Divine power,
which is likely to prove strengthening and helpful to the Zionward traveller,
or promotive of the glory of the Divine being.
The main desideratum in these publications is the
faithful upholding of the ancient standard of truth,
so that the pure truth, the pure dispensation of the Gospel be really and rightly upheld,
exalted, and spread.

[.signed-section-signature]
L+++.+++ A. Barclay.

[.letter-heading]
To +++_______+++

[.signed-section-context-open]
Reigate, 23rd of 11th Month, 1842.

[.salutation]
My Dear Friend,

The date of thy letter yesterday did not surprise me,
but it did please me to find where thou wast.
Thou mayest at all times freely write to me,
for I feel tenderly interested in thy welfare every way,
but fear I am but a poor broken reed to lean upon in any way for counsel and help!
How remarkable was thy meeting with dear Thomas Bayes, at Tottenham!
Ah, his dear brother! my mind has been so with his spirit, as it were,
these several days,
as if just landing on the blissful shores of the heavenly country! yet,
nothing is impossible with Omnipotence!
What an unspeakable favour that he has been so sensible of his situation,
so calm and stayed!

My tender love and sympathy flows copiously towards
all the dear families both in Norfolk and Tottenham.
Now, my dear friend and younger brother,
I must turn to thy letter and first let me say to thee, whatever thou doest,
whatever thou mayest suffer, _mind_ those tender impressions and secret stops in thy mind,
for all lies in them, however plausible may be the advice or cogent the reasoning of any.
Oh, let nothing draw thy attention away therefrom,
for thy safety depends on a simple obedience thereto.
Mind what the savour of life (even the inward life
quickened by the Divine Word) draws thee to,
and mind what it draws thee from,
and let nothing deter thee from forsaking the one and cleaving to the other.
And what though faith may at times seem very low, yea, altogether gone (as thou sayest),
for it is the life of the word that quickens and gives faith,
(and thence called the word of faith, or the faith-giving word),
and if the influence thereof be withdrawn for a little moment,
faith may well be said to flee from us; yet oh, be thou patient awhile,
and dare not to move out of the faith,
and hope will come in to succour the faith and stay thy mind in that,
and thou wilt see that though for a little moment He who is thy life was pleased,
for thy proving and purifying, to hide His face as it were,
yet in tender lovingkindness will He have mercy on thee,
and in due time lift up His royal banner again in thee and gather thee thereto! yea,
and open thy way gradually more and more as thou art willing to be led
as the blind by a way that the natural man can never comprehend,
and exceedingly in the cross to all that thou canst call
thy own! and He who hath called and touched thee,
and drawn thee by His love to run after His tender counsel in His pure fear,
can make a way both through the sea and through the cloud for thee,
when thou hast borne the baptism in them that He sees fit;
and as thou cleaves close to His mighty but secret power,
He will enable thee to run as through a troop of enemies within and without,
and to leap as over a wall of opposition and difficulty,
bring thee out through fire and water as into a large place,
and oh then remember to pay thy vows and to offer the sacrifices of thanksgiving!

I do feel much interested in thy letter, and though I have but little idea of business,
yet I have felt lately more and more convinced that a truly upright and
faithful friend will find it increasingly a difficult thing to get a livelihood
with clean hands and a clear conscience in most branches of trade,
all the channels seem so sadly polluted in one way or another.
It was but the other day that I was talking to a Friend on the very subject,
and he was saying what a sad custom there is now of feeing servants, so much per cent,
and of charging more than really was had of any article to meet that expense! so much so,
that he knew of one or two Friends who could not get on
in business because they conscientiously refused to do so.
But farming has often appeared to me the least objectionable and the most quiet,
and reflective business,
in which our _utter_ dependence on Divine goodness is the most brought to view,
if it be but really entertained,
and one in which our testimonies may be so fully and convincingly upheld.
Thou asks me about going into the North and the names of such as I know.

There is also that dear Friend,
R+++.+++ J. of +++_______+++. He is a faithful and powerful minister
beyond all man`'s arts and parts,
and was at yearly meeting this year,
and bore a clear and weighty testimony to the sufficiency of the
Divine power that visited him when _between the plough stilts._
I do not know him outwardly, but feel a precious unity with him.

Well, my dear friend, this is all I know of to say to thee.
If it prove of any use I should be glad, and now I must say farewell,
committing and commending thee to thy good and all-sufficient Guide,
who never has failed thee yet,
though thou hast seemed to wait long for Him and sought Him with many tears.
He will direct thee to a hair`'s breadth,
and give thee faith and strength to follow as thou keeps
close to Him all the day and waits for Him all the night.
I remain thy sincere and affectionate friend,

[.signed-section-signature]
L+++.+++ A. Barclay.

[.letter-heading]
To L. C.

[.signed-section-context-open]
Reigate, 28th of 11th Month, 1842.

[.salutation]
My Dear Friend,

I received thy kind note yesterday, and am obliged for the contents.
I was not aware of the illness of +++_______+++;
she was one that I used to know before her marriage,
being often with her relations the other side of London.
I believe she had a value for what was good,
and for those who were sincerely desirous of pursuing it.
But, alas! how many there are of this class, who know what is right,
and admire and love those who are faithful, yet are unwilling to bend themselves,
so as to acknowledge what they often feel in the secret of their hearts,
and thus remain dwarfs all their lives.

I do not think I feel sufficient of a draft to attend the interment.
Oh, for the pure testimony to the truth,
to the all-sufficiency of the blessed power thereof, to enable us to overcome the world,
the flesh, and the wiles of the wicked one;
may it be unflinchingly held forth and exalted on high,
though through the weak and little ones.
I notice what thou sayest about coming to see us,
and it is very pleasant to us to think it is in your hearts, dear friends,
and we shall look for you sometime on sixth day.
I hope you will stay over First day with us.
It is pleasant to think of having the help of your spirits.
Perhaps you may be instrumental to arouse some to
cleanse their hands from that which obstructs,
that the heavyhearted may again lift up their heads in hope of that which quickens,
nourishes, and strengthens the immortal soul.

I am much pleased that +++_______+++ has at heart such a good work, but, oh,
I do hope it will be purely brought forth,
that man`'s tool of wisdom and expediency may not be lifted upon it to mar it.
I am rejoiced that Job Scott`'s journal is to be reprinted.
The sad attempts to cry it down and destroy it seem
only to have awakened the desire to have it the more.
I believe his pure testimony will not slumber in the dust,
but even revive as out of the stones of persecution.

Farewell, dear L. I remain thy and your affectionate friend,

[.signed-section-signature]
L+++.+++ A. Barclay.

[.letter-heading]
To +++_______+++

[.signed-section-context-open]
11th of 12th Month, 1842.

[.salutation]
My Dear Friend,

I was much pleased to hear by thy kind letter that thou got home with comfort,
and found all pretty well.
Thou hast indeed been wonderfully cared for and helped on in thy late journey,
so I do hope, my dear +++_______+++, it will animate thy faith a little,
and renew thy trust in Him who never yet has failed thee in the hour of need.
And oh, how true it is that,
with even but a grain of faith and but a little mite of heavenly power,
we are enabled to leap over a wall of opposition and difficulty,
and to run through a troop of fears and foes! and how do the mountains
flow down at the presence or prevalency in our hearts of the Lord`'s power,
and our earthly feelings and natures are made to smoke as at His mighty touch!
Oh, then, that we may increasingly, my dear friend,
yield up ourselves to His mighty and tendering power to do with us as seemeth Him good!
Let our hearts cleave unto Him in uprightness and true fear
that keeps us clean and keeps out all other fears;
and let our eye be singly unto Him, looking and waiting for His all-searching,
all-quickening, and all-strengthening word more than they that watch for the morning;
and surely He will revive His work as in the midst of the years,
animate and strengthen us to let the time past suffice
wherein we have indeed been very hesitating and doubting,
disobedient and backsliding from His tender hand that touched us many a time.
And oh,
that we may each of us know more and more a putting on strength in the name of the Lord,
by whose good and tender power alone we shall know our ability to overcome all things,
the worldly spirit, the flesh, and the wicked one,
remembering the many precious promises "`to him that overcometh.`"

After ten days`' absence we were favoured to reach home the evening before last,
and though weak in body most of the time, and very low and tried in mind,
yet my gracious Master was pleased to introduce me into
much exercise on behalf of others where my lot was cast,
both in and out of meetings,
and I was enabled to relieve my mind to my great comfort and humbling
admiration at His goodness to such a poor unworthy worm of the earth!
But so it sometimes is.
He is pleased to put His words into the heart and mouth of the weak and foolish,
and mean and reproached,
and causes the stammering ones to speak forth close things that reach the witness,
that no flesh may glory in His sight!
Oh, that we may be favoured to get to the watch tower,
and abide there in humility and meekness, that we may watch and keep our garments,
and be enabled to stand faithful to the pure testimony
of truth even to the very end of our time of suffering,
though we suffer the loss of life and all things else outward for it.

[.signed-section-signature]
L+++.+++ A. Barclay

[.letter-heading]
To Letitia Hagger

[.signed-section-context-open]
Reigate, 11th of 12th Month, 1842.

[.salutation]
My Dear Friend,

I trust I shall not forget thy great and sisterly kindness when with thee,
and I do desire thy reward at a better and higher hand,
for He takes the least kindness (for His name`'s sake),
even only comparable to a cup of cold water, as done unto Himself!
And oh, my dear friend,
mayest thou be animated and strengthened by His mighty and good power,
and thy faith from time to time revived when ready
to faint by Him who alone can increase it;
and I remember His gracious promise of old, "`I will be as the dew unto Israel,
he shall revive as the corn, and grow as the vine,
and the scent thereof shall be as the wine of Lebanon; from me is thy fruit found.`"
Ah, it is His heavenly dew, administered from day to day,
that can revive our drooping faith,
and give us to lay hold of His strength thereby so as to witness
a growing in grace and in the heavenly wisdom and stature;
and here we know (as we are diligent in exercise
and faithful in keeping close to the Divine power,
however small its appearance in the revelation thereof within us) a going "`from strength
to strength,`" and how that "`every one of them in Zion appeareth before God.`"
How sweetly descriptive is this of our passing under the Lord`'s good hand of power,
under the "`judgments of His mouth`" or operation of His inward and living word,
under the various baptisms of His Spirit of judgment and burning,
whereby He redeems all Zion`'s converts, and purifies them unto Himself,
and sanctifies unto His holy use;
for we read "`His fire is in Zion and His furnace in Jerusalem!`"
Oh, then,
that we may be willing and patient to endure all the turnings
and overturnings of His good and tender hand.
Let us not shrink from appearing before Him that He may thoroughly search and sift us,
and surely nothing that is really weighty and living and tender,
nothing that is really of His own begetting in us, shall ever suffer,
but rather wax stronger and stronger in His heavenly might and holy life,
and be more and more prepared for fruitfulness to His praise; yea,
the fruit that is of and from Himself shall unfailingly
come forth in His own _pushing yet_ mellowing life,
so as to yield a precious and refreshing savour and flavour.

And now, my dear friend,
I desire thy increase and deepening in this living experience and exercise,
and thy faithfulness in the Lord`'s puttings forth,
in the little grain of faith and of might that He vouchsafes to
what thou feelest required in the secret of thy soul at any time,
without fear of man or looking at consequences,
or leaning to thy own understanding or reasonings,
nor yet yielding to the mists and clouds of doubt and dismay that the enemy may raise;
for before the least grain of the true faith, the least mite of the true power,
they shall all vanish and melt away, and the mountains shall flow down,
and the earthly nature in us shall smoke, and nothing shall be too hard!

I know not how I am led thus to write, and did not so intend when I sat down,
but as it flows in my heart my pen is that of a ready writer.
And, my dear friend, my tender sympathy is with thee in thy very solitary allotment;
but oh, mayest thou not be dismayed thereat,
so as to be hindered from the Lord`'s service.
What though thou hast few or none to help thee outwardly, for the fathers, where are they?
and the prophets do not live forever!
Yet let this drive thee the more deep and inward to the revelation of the Lord`'s power,
who is ever sufficient for poor worm Jacob; and oh,
stay thy mind in deep inward attention upon Him, trusting thy all unto Him,
and He will direct thy path, what to do and how to step and where to step,
and He will open thy way before thee,
even to cleave unto and serve Him in uprightness
(whatever others may do) in what He bids thee,
and none shall be able to gainsay or resist,
and the arms of thy hands shall be made strong by the mighty God
of Jacob as thou thus preferest His honour and favour to all beside!
So look not out, but keep the eye single and inward, and mind the Master`'s pointings;
thus, though the standard-bearers should faint and shrink,
yet the blessed standard of the truth will be taken up, even by the little ones,
and even _one_ of these, through faithfulness to the Lord`'s power,
may become as a thousand, and he that seems very feeble as a strong nation, yea,
as David, valiant for the truth!

I believe this is all I feel at present, and it is in dear love,
in which I remain thy much obliged and truly affectionate friend,

[.signed-section-signature]
L+++.+++ A. Barclay.

[.letter-heading]
To Hannah Marsh

[.signed-section-context-open]
17th of 12th Month, 1842.

&hellip;So, my dear friends, do feel for me and crave my preservation every way and every day.
And _how_ do I feel for you!
There is nothing so preciously uniting as suffering;
to be fellow-sufferers together for the dear Master`'s cause, as we humbly hope.
But this we cannot be without being fellow-__feelers;__
and how can we be fellow-feelers without being similarly
baptised into one and the same Divine life,
whence springs the true seeing and feeling, and the fruitful bearing!
So, oh, let us each travail for it more and more,
even to know the precious life of Christ,
fresh and fresh to bubble up in us from day to day;
and then we shall be increasingly one in Him and feel Him one in us, our all in all,
and shall know the heavenly increase, and the fruitful praise,
and the humble rejoicing before Him forever,
even though in the midst of persecutions and reproaches, and tribulations and perils.

I am so pleased thou wast helped in that meeting +++_______+++ was at.
Do be faithful, my dear friends (if it be not impertinent in me to say so to you),
and go on right forward for our dear Master, nothing doubting and no one fearing,
and He will make your way in the hearts of all, plead your cause in them,
either sooner or later, in mercy or in judgment;
and I do hope thy dear husband will simply yield to any
little pointing to go now and then to this or that meeting.

[.signed-section-signature]
L+++.+++ A. Barclay.

[.letter-heading]
To A. R.

[.signed-section-context-open]
1st Month, 1843.

When I look at the children of the exercised ones amongst us,
I am often tried at the consideration of _how little_ are they brought under that all-regulating,
subjecting power of which we believe their dear parents
are constrained to testify and direct unto;
but what is the plainest outside,
if the humbling and restraining power of truth is unsubjected to and unheeded;
and in feeling these remarks to arise continually, how does the mind revert to poor self,
and desire to take the warning and instruction home therein contained, fearing lest,
while constrained by Divine grace and enabled to testify unto others thereof,
I myself should become a castaway or bring the least reproach on the blessed cause.
Dear M. S. is a deep feeler and mourner, for we cannot deeply feel or rightly see,
without being clothed also in mourning;
and it is sometimes hard to hinder the sackcloth from peeping out.

I accept thy kind encouragement, my dear friend.
These are times when we often get rather the reverse,
even in the midst of our painful suffering for the precious cause sake.
Oh! the woe, the loss that will and must be to us,
if we appoint as elders such as are unsuitable and unbaptised for the work,
through our following natural judgment, and affectionate feelings,
and the sight of the eye outwardly.
I have had cause to deplore such appointments, made in the hope of qualification,
or with the desire to strengthen the hands of such.
Unless they are Divinely prepared and anointed (as it were hewn
and cut out in the mountain of the Lord) by deep baptisms,
similar to those of the poor ministers, how _can_ they feel for and with them,
or have any clear discerning of the work in each under their fostering care;
they may on the contrary be hindering and hurting
the very work they should strengthen and help.
Ah, the continued baptisms unto death of all that is of the creature,
how many have fallen from the want of it! being settled down at ease by their appointment,
and forget their first speaking tremblingly,
or being humbled under the Lord`'s good power;
but we must trust in Him who can overrule all things for good,
and who can give the poor little oppressed ones patience under all permitted trials.

[.signed-section-signature]
L+++.+++ A. Barclay

[.letter-heading]
To the Same

[.signed-section-context-open]
Without date.

Alas! there is much to discourage and dismay,
so much that seems to strike at our life and pierce as to the quick,
in what we see and hear; it is like being "`killed all the day.`"
Nevertheless it is comfortable to hear of the faithful ones scattered up and down;
they seem like the savoury salt, though often mournful and solitary,
whether inwardly or literally so,
as it were prophesying and bearing their testimony in sackcloth,
and in a wilderness state!
Ah! surely these faithful, upright-hearted ones are the true Church,
and will they not all be gathered unto Zion with everlasting joy and gladness,
and sorrow and sighing shall forever flee away from them.

[.signed-section-signature]
L+++.+++ A. Barclay.

[.letter-heading]
To the Same

[.signed-section-context-open]
Without date.

I have been much occupied in mind on the subject of overseers,
having had a fresh appointment in our monthly meeting,
in which much deep exercise has fallen to my portion, as I apprehend, for the cause sake,
which is more precious to me than life or reputation amongst men.
I was mercifully strengthened to be faithful, though most pinching to nature,
during the consideration and afterwards.
I laboured with each individual of them to my great relief and peace of mind,
so that I am now quiet and full of praise to the
Giver and Strengthener of all His poor unworthy servants,
even the meanest of them.

Towards the close of this labour of love,
I was tried with the sad accounts of my dearly beloved nephew, R. Barclay,
a most sweet young man, whom I had fondly watched from childhood,
and comfortingly beheld his promising steps in changing
his dress and yielding to what he felt to be right.
I was hoping he might succeed his dear uncle John; but how shortsighted we are!
He suddenly went off when his family were hoping he might
recover from hemorrhage he had recently had.
It was exactly six months from his wedding-day to the day of his burial,
and it is remarkable how many of his young friends attended both.

[.signed-section-signature]
L+++.+++ A. Barclay.

[.letter-heading]
To the Same

[.signed-section-context-open]
Without date.

P.`'s visit was a uniting time--one of entering into feeling with the burden-bearers,
and this truly is desirable.
Alas! the affairs of truth of the dear Master are in a very
low state in almost every part of our poor Society,
and mourning must cover the true feelers.
Still there are some encouraging features which convince
us that we are not a forsaken people,
and that the good hand is yet stretched out to gather and to redeem from bondage.
May those who feel with and for Him endeavour to strengthen each other`'s hands,
cleaving close to Him in subjection and watchfulness and fear,
and then may we not hope that good may arise even out of apparent evil,
and that there may be a revival even in the midst of the
years as from the desolations of many generations.

[.signed-section-signature]
L+++.+++ A. Barclay.

[.letter-heading]
To a Very Young Friend

[.signed-section-context-open]
Reigate, 21st of 1st Month, 1843.

[.salutation]
My Dear +++_______+++,

I must _tuck in_ a little note to thee in that I have written to thy dear mother,
to show thee that I have not forgotten thee now that thou art left,
although I have been of late variously diverted.
No, my dear girl, thou still lives in affectionate remembrance,
and so I believe thou ever would, however thou might be wandering afar off,
whether in a natural and outward sense or in a spiritual and inward sense;
for the true love extends over sea and land, and is not dependent on outward intercourse,
nor yet _entirely_ on outward conduct,
because it is of the same _nature_ (a branch or _fruit_) of that precious Divine
love which beholds even the poor prodigal who has wandered afar off and wasted
all his substance in wrong things--that precious Divine love,
I say, which, beholding, pities and touches him even to the quick,
as with the remembrance of his dear Father`'s house where there is bread enough and
to spare--and all to bring him back again with renewed and increased rejoicing!
Although I must own that where we see and feel the
gracious good work yielded unto and going on,
our love will and must be in proportion increased
for the work`'s sake and for the faith that is begotten.

I am much pleased that dear +++_______+++ has kindly offered for thee to read French with her;
it is truly kind, and I hope thou wilt value the privilege,
and perhaps too thou might gain from her some useful hints as to books that are improving,
and perhaps she may lend thee one now and then, which would be an advantage to thee.
But I hope, dear, thou wilt keep up the reading of some Friends`' book daily,
either aloud or to thyself;
for I am sure thou must have felt the precious seasoning
effect it had on thy mind when thou wast here,
and it helps to undo the leavening effect which there is both in
association and conversation that we are subject to daily,
as well as that there is too often in the pursuits that
we take up for our improvement in a natural sense.
Oh, we want the spiritual life to be kept up and cherished _by all_ possible means,
even the _side channels_ as it were of reading and of intercourse with the spiritually minded,
as well as by waiting for and seeking after it at the Fountain-head.

+++_______+++ told me thou hadst expressed a fear lest we had disapproved
of a certain tract from prejudice against the writer of it.
That, my dear,
we would never willingly be guilty of I am sure--it would not be just and sincere;
and I have spread some dozens of another tract by the same writer, on Teetotalism,
as highly approving of it.
It is the substance and the feeling that we must judge by in such things,
and I do believe in these and other things too,
that the lower we get and the more inward we dwell with the little principle
or seed of light and life within (which though in us _is not of us_),
the more we shall be preserved in the true savour of all things,
and free from prejudice--for these are days of much superficialness in many respects,
but all is not gold that glitters!
I had rather have a little sound and substantial iron, however rough and ugly looking,
than much mock gold with all its shining lustre.
I want thee to be more inward, dear and not upon the surface,
then will thy building stand all the storms and tempests
that may and _must_ prove its foundation.
It is no matter what the many may say, nor what our _own nature_ may _hope_ to be correct,
but it is a _great matter_ what the Lord whispers to us in secret,
and the sense and savour which His life gives of things and persons and of all within us.
But I did not intend thus to write; thou wilt say I am always sermonizing.

We had a sweet visit from dear +++_______+++,
and it was very hard to part--she and I feel like _mother and daughter as I fancy._
We were very busy at mathematics daily, and had our two kinds of reading besides,
Paxton ([.book-title]#Illustrations of Scripture#) and Richard Shackleton`'s sweet letters.
I hope to get a few more shillings for Germany.

Farewell, dear,
in true affection and earnest desire for thy present and everlasting blessing and welfare,
says thy sincere friend,

[.signed-section-signature]
L+++.+++ A. Barclay.
