== Chapter XI

To John F. Marsh

Reigate, 2nd of 2nd Month, 1843.

My Dear Friend,

A little one may sometimes help a great one! and this encourages me to think
that a few lines even from such an one as I may not be unacceptable when on the
eve of departure for thy awful journey--believing that it does indeed feel truly
awful to thee thus to be going forth as with thy life in thy hand,
to visit the seed which is in much oppression! yea, pressed down,
as a cart is pressed that is full of sheaves,
under much that opposes and treads down! in which awful labour and prospect I think
I can truly sympathise with thee according to my very small measure of experience;
and oh, who is sufficient for these things! who,
but the omnipotent One is indeed sufficient to bear up the
poor bowed down mind under the prospect of the conflicts,
and deep baptisms, and low plunges, and long wadings, and proving, fastings,
and pinching strippings,
the watchings and the perils that must be the portion of
the Lord`'s painful labourers in these days of backsliding,
and of sore trial! who but He is sufficient to gird with strength unto the battle,
to clothe with the armour of light on the right hand and on the left,
and to preserve even on the watch tower of humble fear! who but
He is sufficient to pour forth of His Spirit upon them,
and to put His words into their mouths,
that they may boldly plead His cause and faithfully uphold His pure testimony,
making them able ministers, not of the letter which killeth,
but of the Spirit that giveth life,
and of the new covenant and testament which God hath
bequeathed to and made with His poor fallen creatures,
in and through His beloved Son!

Oh, then, in wishing thee, my beloved friend and brother, the best,
even God`'s holy speed,
how does all that is quick and lively in my burdened soul earnestly
crave that His all-sufficient good hand may be with thee,
and that thy eye may be ever and only unto Him--and I do
comfortingly believe that He who has been thy tender Alpha,
who condescended thus to touch and to draw, and to make willing to run after Him,
will strengthen and carry thee through from day to day,
to the accomplishing of what He has for thee to do,
and will be thy blessing and peace-giving, yet humbling Omega,
to His glory and to His praise, which is all thou desires I know!
And oh, when it is well with thee, remember thy poor weak sister,
and crave that I may be preserved from taking any step before the
Lord calls thereunto--yet enabled in simplicity and true fear to
move as He may be pleased clearly to point out the way and time.
I may acknowledge that the matter has much cleared before me in
the last week--yet as the time of showing unto Israel draws nigh,
many fears rise up to dismay,
both as to the poor weak body as well as the disqualification
and unworthiness of the mind,
and the many dangers and snares likely to surround!
But oh, dear friend, crave my preservation,
that I may be kept ever so weak and low in myself, fearing for and distrusting myself,
yet wholly hanging upon the Lord and keeping closely
to His blessed secret power and heavenly gift,
wherein alone is the true preservation!

Suffer me to say,
that I hope thou wilt in simplicity yield thy mind to any
pointings towards public meetings in Lincolnshire,
especially the northern part;
I think it is beyond Brigg where dear J. C. found a tender people,
and much openness about Waltham and Caistor.
Oh, spread abroad the sound or testimony of the word of the Lord,
even that blessed word which is quick and powerful,
yet very nigh in every heart to discern good and evil!
Oh, I would fain bear the company in this good labour and glorious work,
as a silent breather for success to the Gospel (the power) the world over!
I have herewith sent thee as a little mite towards the work,
one hundred of each of my tracts.
I trust thou wilt find some tender ones also scattered up and down poor Norfolk,
and I do hope thou wilt not hurry through,
and do not put by any little feeling towards a solitary individual even,
for we know not how an arrow shot at a venture, as it were,
may even pierce through the very joints of the harness, or coat of mail,
wherewith such an one is enveloped.

Farewell, my endeared friend.
I remain, may I say, in the love and bonds of the Gospel, thy nearly united,
and affectionate, and sympathising friend,

L+++.+++ A. Barclay.

To a Young Friend on Going Out Into a Situation as Governess.

2nd Month, 1843.

My Dear +++_______+++,

I omitted to hand thee the little account of J. D.,
so I herein enclose it for thy acceptance, and I trust reading to profit,
as we began to do, the third time, the evening of the day thou left us.
I hope thou wilt observe how that when he was, after long pleading with and disobedience,
at last convinced of the blessed truth (that is,
of the inward power of the Lord Jesus Christ),
partly by means of the awful judgments and afflicting dealings of the Almighty,
and partly by the instrumentality of a consistent walking Friend--I say,
I hope thou wilt observe how that then he was shown and convinced
that all those reproofs and teachings in the secret of his heart,
which he had been favoured with even from early childhood,
were the operations of the Spirit of Christ,
visiting him and vouchsafed to him by the tender love of God to his never-dying soul,
although at the time he was ignorant thereof, or turned a deaf ear to them,
and therefore could not know them.
Now, seeing that we as a people are not thus ignorant, but are instructed,
both by our parents and by many instruments raised up to testify thereto,
to mind these secret reproofs and teachings as the way to life eternal,
how exceedingly responsible are we,
and how great will be our condemnation if we despise
the love of God thus visiting our souls,
and neglect so great salvation by grieving the blessed Spirit of Christ our Saviour!
Surely this will be no less than crucifying Him afresh,
and denying the Lord that bought us.

Now, my dear +++_______+++;
suffer me to say that this is the very object and end of all true education,
to testify of and direct our dear pupils to this inward power or Spirit,
whereby the spiritual kingdom of our Lord may be set up and spread in their hearts;
and this will sanctify and season all the knowledge
of things civil or temporal that we may give them,
and enable them to direct and appropriate it in the right way.
Oh, this is the true way of leading them to the dear Saviour,
to sit at His feet and hear His gracious words, as Mary did,
which I believe symbolical of a lowly posture or frame of mind,
attentive to the lowest appearance--the smallest communications of His Spirit within us.
And surely it is as we thus come under His word or law in our hearts,
that we become His subjects, and know Him to be really and truly our King and our Lord.
Oh, here is the true coming unto Jesus, believing in Him,
and knowing Him to be our Shepherd to lead us in the pastures of life;
our wonderful Counsellor and Teacher that cannot be removed into a corner,
and our blessed Saviour from both the power and dominion of sin,
as well as the guilt and punishment thereof--for His word inwardly,
as well as formerly it was outwardly, is with power.
"`Greater is He that is in us than he that is in the world`"--that is,
the enemy who rules in the hearts of the worldly-minded and disobedient.
His law is a law of power, of life, of liberty, of peace, and joy unspeakable,
able to deliver us from the law of sin and death!

And this is what I earnestly desire for thee, dear +++_______+++,
that it may be thy fervent concern and careful endeavour to do all thou canst
to lead and direct thy dear pupils to this inward power or Spirit of Christ,
this pure witness for God in their conscience,
and swift and unflattering witness against all that is against Him.
And I do believe the reproofs and whisperings thereof
are to be heard even by very young children;
and also the precious and sweetly melting feelings experienced,
which are thereby brought over the mind, as attention and obedience are yielded;
and oh! mayest thou be very careful that nothing in thee, whether by word or conduct,
may in any wise either discourage these tendering feelings
or give them a slight esteem thereof! for if thou dost,
and they suffer loss thereby, it will lie at thy door!

And oh, my dear girl, be careful, oh,
be craving that thou mayest at all times be brought and
kept under this nurture and admonition of the Lord thyself,
otherwise thou canst not lead them to the same.
Oh, let the fear of God be always before thy eyes,
and be earnestly concerned to seek His face, His favour,
the guiding light of His countenance, and His heavenly strength,
that thou mayest be so enabled to walk consistently
and watchfully as that they may see it,
and be led to follow thy example because it is a peaceful one.
There is great danger of our having too great an idea of our own abilities and strength,
and of what we will do and what not.
Such are not the meek and humble whom the Lord delighteth to teach of His precious ways,
and to lead in the paths of true judgment.
"`The Lord hath respect unto the lowly,
but the proud He knoweth afar off,`" and doth not draw dear unto them,
but leaves them to themselves, and then they are likely to step amiss, yea,
cannot fail of erring.
It is not a mean thing or a base thing to distrust ourselves--to feel our own weakness,
and to apply unto the Lord for help continually; no, it is a great thing,
and a noble thing, and a very precious thing in His sight,
and that is worth far more than all that men think of us for our abilities.
None are so truly great as those who think little of their own attainments and capabilities,
and are fearful of themselves and of trusting themselves,
and therefore look wholly to and lean only on the Lord, in whom is everlasting strength,
and with whom are hid all the treasures of the true wisdom and knowledge.

And I hope, my dear, thou wilt not think that I do not love thee in thus writing;
those are our truest friends who tell us the truth,
and point out dangers and even weaknesses;
and the reproofs of a true friend are better than the kisses of an enemy.
If I did not love thee dearly,
I should not feel so tenderly concerned for thy best welfare.
Ah!
I long that thou mayest be brought more really and fully to the possession
of that which thou hast been brought up in the profession of.
For, as I said to thee here, our parents cannot give us possession of the truth,
or the inward kingdom of Christ; they may testify of it, and direct unto it, where it is,
and how to be attained; they may pray for our being brought to the knowledge thereof;
but it is our own fault if we will not follow their directions and testimony,
nor seek to answer their prayers.
But how much greater is our responsibility and will be our condemnation; yes,
and how much more harm may we be instrumental of spreading,
for the children of such exercised parents are looked at peculiarly for examples,
and their parents are often bitterly reproached if they are not what they should be.

But oh, my dear, I long--yea,
words fail me to describe the earnest and affectionate desire that fills my heart,
that thou mayest grow up as before the Lord in His holy nurture and government; and,
going forth, mayest lead and persuade all around thee to come, taste,
and see how good the Lord is;
and that they verily are blessed that wholly give up to love Him above all,
and to be led humbly by His good hand.
And I believe, as this is thy care and desire,
thou wilt unfailingly experience Him to be a God nigh at hand,
to do thee good at all times and under all circumstances--a
never-failing Friend and sure Adviser--a safe Guide--a mighty
Strengthener--a powerful Preserver--and a blessed Comforter.

L+++.+++ A. Barclay.

To +++_______+++.

Reigate, 21st of 2nd Month, 1843.

&hellip;Alas, my dear friend,
how many there are in our highly favoured and highly professing Society,
and even some in station, who have not this tender, honest feeling, I am sorry to say,
but who seem as if they made use of a borrowed capital to make a fair show in the flesh,
and then run the risk of losing all,
and thus bring reproach on the pure testimony of the truth.
That which is not my own I should feel as sacred,
and would even stint myself of butter in order to pay off by degrees!
But there are many, many things to grieve us continually, coming to our ears now-a-days,
in our poor backslidden Society; yet truth is truth though all forsake it,
and the foundation of God standeth sure, having this seal,
the Lord knoweth them that are His,
and let him that nameth the name of Christ depart from iniquity.`"
I mark thy low estate, as depicted in thy kind letter; but it is no marvel.
Those who are of the living in Israel that is, touched by the Lord`'s life-giving power,
and thereby enabled to see and feel how things ought to be, both in and out of them, yea,
and clothed thereby with an earnest desire to walk according thereto,
in all faithfulness, and uprightness,
and humble fear before Him--these cannot fail of
being often clothed with mourning and lamentation,
sometimes over their own weakness and unanswerable walking,
and at other times over the desolations of Zion and the
abominations of those who profess to be her daughters!
But I have often desired that as it regards the former cause for mourning,
it may not lead to unprofitable discouragement,
neither may self get up even in our mourning over ourselves.
Let us be content to see ourselves as weak, and foolish, and vile, and nothing,
that we ought to be, and let us abide under the humbling sense thereof,
till patience have her perfect work therein.

But oh, let us look, yea,
let us be animated still to look over all up unto Him in whom is everlasting strength,
and in whom are hid all the treasures of wisdom and knowledge,
that we may lay hold on His tender arm of Divine strength
which is renewedly stretched out for our help,
and then surely we shall know the healing through
the chastisement or judgment of His blessed Spirit,
and the strengthening through the humbling,
and the Lord`'s power will be over all the enemy`'s plunges and doubts and discouragements!

And as it regards a deep mourning over others,
whether in secret or whether in our communings together as by the way,
of what is come and coming to pass at Jerusalem, which truly make us sad,
may we not be slow of heart to believe what is declared again and again,
both within and without us,
that Christ must suffer from the generation of the unbelievers who are wise in
their own eyes--may we not be greatly moved nor dismayed at what we see,
hear, and feel--let us not fear with man`'s fear, but oh,
let the holy fear of the Lord God be ever before our eyes,
let Him be sanctified in our hearts,
and let us ever think upon His name which is His power; remember that He is over all,
and wholly yield up ourselves into His holy hand
that He may require or permit what He pleaseth,
and mold us how He sees meet.
Oh, this is what I believe to be Jacob`'s tent in which he is safe,
and no enchantment shall ever prevail against him,
even whilst he is gathered to and abiding in the Lord`'s holy life
and power which compasseth him and encloseth him as with walls,
and but works and clothes him with a quiet, peaceful, watchful, and humble spirit!
Oh, let us seek more and more to be baptised into this
blessed spirit by this holy life and power,
then shall we be all united together in one mind and judgment as one bread,
partaking of the one blessed nourishment and comfort, and rejoicing,
even though scattered up and down in solitary places and in much tribulation;
and in all these things (permitted to come upon us for our
proving and refinement) our souls should live,
wax stronger and stronger in that life which is hid with Christ in God,
and the Lord`'s name would be exalted and glorified over all, who is worthy forever!

I may now inform thee,
I trust under a humbling sense of the Lord`'s condescending
goodness to such a poor unworthy one,
that I was liberated last fourth day by my Friends
to visit Friends once again in the land of my forefathers,
Scotland, and am looking to start the middle of next month.
I cannot describe the waves that have been permitted
to come over me on this account during the last year,
and even still I seem hardly out of their reach! for oh, how awful does the work seem,
and how formidable does the journey seem at this most trying season to the delicate,
and to such a cold climate!
But there is one who is all-sufficient for the weak and foolish,
and He also can temper the winds even to the shorn lamb.
And oh,
that He may preserve me from bringing the least reproach or hurt to His precious cause,
and strengthen me to uphold the pure and ancient testimony
of truth in faithfulness and simplicity and deep humility,
to the end of my little day of testimony-bearing and of suffering for Him here,
is the earnest desire of my travailing soul!
And, dear friend, do thou crave it for me I beg,
for I have great need of the prayers of the faithful.
Oh, crave for me the daily quickening, the daily humbling by the Divine power,
that I may be preserved and enabled to praise His great name fer ever.

Farewell.
With dear love, I remain thy truly sympathising and affectionate friend,

L+++.+++ A. Barclay.

To Mary +++_______+++

Reigate, 3rd of 3rd Month, 1843.

My Dear Mary,

I feel as if I should be best satisfied to send thee a few lines by way of parting salutation.
I do want thee, dear, to grow in best things, in the truth, in the Divine life,
and come up in that faithfulness and fruitfulness which thou art called unto,
and which it is graciously designed thou shouldst enjoy the reward of!
I have often felt much about your allotment in your little meeting,
and how the blessed end so mercifully designed therein may be answered;
and it appears to me there is no other way than daily to wait for the Divine
life and counsel to quicken and to direct you in all your conduct and steppings.
It is thus that life and love towards God and the
things of His heavenly kingdom is quickened in us,
and we know that unless these be daily renewed in us,
there is so much around us that is calculated to deaden and clog our spirits
heavenward and so hinder us of the precious good so mercifully designed.
And when this life and love towards God is quickened in us,
though in ever so little a way,
it must bring with it a true feeling towards His precious cause of truth,
which is the inward kingdom of Christ`'s Spirit,
both in our own hearts and the hearts of others--a true zeal for it; and as we,
in simplicity and godly sincerity, seek to be humbly faithful to this feeling,
which truly is not of us, though it be begotten in us,
desiring to have a conscience void of offence towards God and men,
which we cannot have without faithfulness, so we shall know a growing in heavenly grace,
in the heavenly increase,
become more quick of understanding in the Divine
fear in the things that concern the heavenly kingdom,
and consequently our present and eternal peace,
and shall become more and more helpful as living members in the body, the Church,
and in which body none are to be idle and useless,
but every joint and every member is to supply strength and beauty
according to the effectual working of the Divine power in each!

So I want thee, dear,
to look to it--see that thou refuse not Him who calleth from heaven--see
that thou in being faithful magnify His name!
Do not think this is too high an attainment, but remember it is a gradual work,
for all good as well as all evil comes on gradually.
We must be willing to take one little step before
we can expect to see how and where to take another;
but if we shrink and draw back,
the heavenly light and strength will also draw back from us,
and we shall even lose what we once had,
and become mere dwarfs instead of fruitful trees of comely stature!

In looking at your preparative meeting, I have much desired that thou might,
through a humble and simple walk and acting,
be a means of helping dear +++_______+++ on a little.
We may often be helped when diffident,
by seeing the simplicity and faithfulness of another, even one younger than ourselves;
and she has been so bred up in the discouraging and crushing atmosphere of +++_______+++,
that I know she feels as if she could not stir out of the pit of it.
I am aware there is much +++[+++that]
lies at her door in the matter by a want of simple faithfulness,
and self may creep up in many ways that don`'t seem likely, and so hinder us,
and I have told her so,
and tried to stir her up to mind the little gift
of light and life whilst mercifully permitted;
still example may do much, and whether she follows or not,
thou wilt be clear and wilt thereby wax stronger and stronger!

Oh, there is something overcomingly strong in the truth
as it is suffered to prevail in our hearts,
as we yield thereunto in all things,
and know all things in us thereby brought low in subjection thereto;
it will overcome all evil, both without and within us,
it goes on conquering and to conquer, makes even our enemies to be at peace with us,
and raises a testimony even in their hearts for us, so that they cannot gainsay;
and we shall, as the scripture says,
"`possess the gates of our enemies!`" and as we are faithful,
though in ever so little and humbling a way,
how does it seem to lift us up above the evil in ourselves or in others,
and it gives us to feel a precious union and communion with Christ the truth;
we seem as it were lifted up to the mount where we say it
is good for us to be here and desire to abide there always!
Nevertheless our clothing is deep humility,
and we are made willing to go with Him also to Calvary, and to know self crucified in us!
Oh, my dear Mary, let us seek after this precious experience more and more,
which is to be known by little and little in the daily quickenings,
in the daily humbling, by the Divine power in our souls!
Ah, do you crave it for me in this awful journey, for unless I know it day by day,
my faith and resignation will soon fail!

Farewell very dearly, saith thy and your affectionate and very sincere friend,

L+++.+++ A. Barclay.

To +++_______+++ and +++_______+++

14th of 3rd Month, 1843.

My Dear Friends,

As I am not likely to meet you at our next quarterly meeting,
I thought it seemed in my heart to send you a little salutation of love,
that I might be clear before leaving home.
I have thought much and often of you since your appointment
by your monthly meeting to the station of elder,
with earnest desire that you may be enabled to come up faithfully
in the duties thereof as before the Lord and unto Him,
and not before or unto man--as well as that you may
daily seek after the renewal of qualification therefor,
the quickening and the humbling that is of the Lord.
For I trust you are sensible that man`'s appointment is not the true qualification,
neither is his favour and approbation the peaceful sanction,
nor the mere office the true living authority.
For man, in his own wisdom and prudence and judgment,
may look only at the outward or superficial appearance,
and judge such fit as are "`old enough, and rich enough,
and dry enough,`" as dear S. Emlen once said on such an
occasion--may look at the outward profession and consistency,
or be taken by mental endowments or pleasing manners,
that may seem very encouraging to that which is good.
But when the Church does not lean to their own understanding
and judgment or affection as men,
but look to the Divine Spirit to open their eye mentally
and to guide their judgment aright,
then they look deeper,
even to inward qualification--for it is the Lord`'s blessed Spirit that alone can quicken,
humble, and sanctify all classes and ages, as yielded unto for this awful service--yes,
this can quicken, humble, and sanctify both old and young,
render the former green and fruitful even in old age, rectify, strengthen,
and preserve the latter from all that is likely to corrode
or impede the savoury life--this can humble the rich,
whether in outward circumstances or in mental endowments,
and sanctify all they have and are unto the Master`'s pure and holy use--this can quicken
and raise up the true feeling and judgment in such as are poor in either sense,
and enable them to bring it forth in humility and unflinching faithfulness for the upholding
of His pure and blessed cause this can preserve any from becoming dry and formal,
even by the daily quickening and melting that is of and from the Lord.

Oh, then,
how needful is it that those who are called to this
station should daily seek after this truest qualification,
even to bow low before the Lord and feel after His living, piercing power,
whereby they may know a daily dying unto all that is of the creature,
whether outwardly or inwardly, and then that tender,
lowly life of Christ will arise in them which gives the true vision and the true feeling,
the very mind and judgment of truth!
Oh, then will they be qualified to feel whence words proceed,
and will not be dazzled by outward appearance,
or overcome by outward sounds--they will be able to feel the various
stages or degrees of growth in the work of the ministry,
as well as to appreciate the various gifts to minister to the various needs and
against the varied snares thereof--not merely warning or discouraging,
but showing forth unto those thus under their care and nurture what they
may be at any time deficient in and how they may attain it;
endeavouring thus to help both out of and away from the enemy`'s snares,
to clothe the naked, to feed the hungry, to visit the sick and in prison,
and to strengthen the stranger or inexperienced into a better way.

It is these truly fellow-feelers who will mourn with the right-minded who mourn,
and they will be helpers of their joy and rejoicers with them when they rejoice,
uphold and strengthen their hands before all gainsayers,
comfort and confirm their feeble minds in the testimony required
of them in this day of treading down and of deep trial.
Oh, it is those who will "`feed the flock of God,
taking the oversight thereof not by (mere) constraint`"
of appointment "`but willingly,`" as from the heart,
from the heavenly melting touch of the Lord`'s powerful hand,
and beyond all outward considerations--not from a desire of man`'s respect and esteem,
nor to be bowed and sought unto as fathers and mothers,
for this is but "`filthy lucre,`" inasmuch as it draws the
hearts both of givers and receivers away from the Lord,
the true Shepherd and King; but oh,
the true eldership must be from the pure constrainings or drawings of
the Lord`'s Spirit that gives to feel truly with His blessed cause,
and then makes us "`of a ready mind`" in a living, holy,
but humble zeal to act in the meekness of His wisdom for the pure
testimony thereof--such will not shrink in the day of battle,
nor yet seek to smother and gloss the truth in the day of judgment,
but will acknowledge it in all their ways,
and thus be upright and sure as a dart in the Lord`'s cause;
and under His humbling power there will be no lording over the heritage,
nor seeking to rule or leaning on the authority of office,
but that He the Lord of life and glory may alone rule in every heart,
and be subjected to and glorified in a holy, humble, faithful example! and verily,
such shall be crowned with a crown of glory that fadeth not away!

And now, my dear friends, though this may seem a very high standard,
yet it is not too high for any of us to seek after and press towards,
for our calling is a high and holy one who are thus called to be leaders of the people,
fathers and mothers in the congregation.
Great is the responsibility of the charge of the ministry,
and we must not lower the standard to meet the weakness that there is amongst us,
lest we be instrumental to further the erring that there is,
to weaken and discourage that which is pure,
and the answering thereof be required at our hands--but
rather seek and cry unto the strong for strength,
and to the wise for wisdom,
to press towards the mark for the prize of our high calling in Christ Jesus.
Oh, then,
let us be engaged to "`take heed to ourselves,`" to the daily humbling
and quickening of ourselves by the Lord`'s power,
and then we shall be renewedly enabled to take faithful and diligent
heed "`to all the flock`" over which we are appointed overseers,
that we may feed them or nourish up in them the true life,
and promote in them the nurture and admonition that is of the Lord.
This is my earnest desire on behalf of all my dear friends in the station of elders,
that they may be a blessing and not a hindrance, and may be blessed of the Lord,
the chief Shepherd.

L+++.+++ A. Barclay.

To +++_______+++.

4th Month, 1843.

My Dear Friend,

I feel best satisfied to take up the pen to finish that which is lacking towards thee.
It has often appeared to me that there is a snare both for elders and overseers,
in a tendency to sit down as it were at ease in the appointment,
and consider all they have to do is to attend to what is
brought to their knowledge that requires care,
and thus they may become mere formalists as it were,
eye-servants as men pleasers--that is,
only doing that without attention to which they would be found fault with by their friends.
Now, it has often appeared to me that a truly exercised Friend in these stations will,
as he daily waits for the heavenly humblings and quickenings,
whereby alone he receives a true feeling for and with Christ the truth,
feel a holy zeal and a tender fostering care raised in him for
his Master`'s cause or kingdom in the hearts of all the flock,
and which is compared to a little seed;
He will feel an engagement of soul in the true love and holy fear,
that casts out all wrong fears,
to labour various ways for the health and vigorous growth thereof,
and that all that is likely to hinder it may be guarded against
or removed out of the way--that the wanderers may be sought out,
the scattered gathered, the unwary warned, the unruly rebuked, the weak strengthened,
the tender encouraged to greater tenderness,
and the faithful confirmed and comforted amidst their many tribulations;
so that indeed his is no sinecure station,
if faithfully fulfilled and our pure testimony therein uprightly upheld.

And though under a sense of our own great weakness we may say,
"`and who is sufficient for these things?`"
yet let us remember the Lord`'s power is over all weakness, and difficulties,
and trials all-sufficient,
and it is most preciously and as it were precisely manifested in proportion
as we are reduced to feel our own weakness and unfitness the most;
and in His power a little one may become as a thousand,
and a feeble one as a strong nation, and he that is weak as David,
valiant for the truth! so that there is no need for the sincere to be discouraged,
but rather stirred greater diligence in seeking after the
daily baptism unto the death of all that is of the creature,
all that thinks itself sufficient, or would move in the wisdom and prudence,
will or might of the creature! and the daily quickening
of life and strength in and for the Master.
Yes, and there is need for such; and oh, dear friend,
look to it to be stirred up to look closely at home
and consult the unflattering witness for truth within,
whether we are clean-banded in all respects,
whether there is aught that hinders our uprightness
for our Master and our faithful pleading for Him,
whether His cause is uppermost in our hearts both in prevalency and in preciousness,
or whether other lovers in various ways and under
very specious excuses are running away with our strength,
warping us from the true uprightness,
and bringing up to coolness of zeal and dimness of
sight over us as to the things of our Master.
Oh, this is like grey hairs creeping over us when we know it not;
and though the outward shell or form of sobriety and gravity,
and a consistent appearance as it regards our own selves may remain,
and we may appear nothing different to our Friends perhaps, yet the kernel,
the life is wanting that gives the true taste and savour,
and leads into the true exercise of spirit, whereby the feeding of the Church is known!

Oh, there is much in that exhortation, "`take heed to yourselves first,
and then to all the flock over which ye are appointed
overseers to feed the Church of God.`"
As we are concerned to take heed to ourselves first,
to see that the lets and hindrances are removed whereby
our hands are weakened or made unclean,
and to seek after the daily qualifying as above said,
so the exercise and the heed for the flock necessarily follow,
even in that precious life which nourishes that which is
of its own nature in the hearts of the flock or Church.
Oh, how tenderly then do we move for our Master, yet how surely,
for He tenders us in ourselves and moves us in His own life and wisdom that must
gather unto Him--His cause is tender to us as the apple of the eye,
we are hurt when He is grieved, yet think not of our own suffering!

Oh, what harm a self-serving, self-seeking, self-saving spirit hath done us!
I desire not to multiply words, my dear friend,--but oh! "`consider what I say,
and the Lord give thee understanding,`" and make thee willing
to bow to the judgment and call of His Spirit within,
that thou mayest indeed be a true father in His Church,
for truly the Lord hath need of thee, and His love saith,
come and plead my cause and uphold my banner of truth; and the bride, the Church,
hath need of thee, and saith,
come and help to build up the waste places and restore the desolations of latter generations;
and those who hear the call and are themselves endeavouring faithfully to obey it,
they also have need of thee, and do say, come and help us,
bear our burdens and share our afflictions, and strengthen our hands in an unflinching,
uncompromising testimony for the truth,
and verily thou shalt never repent of any sacrifice therefor,
neither shall any glory or honour,
favour or advantage whatsoever in a worldly point of view,
be to be compared to the honour which cometh from God alone, His favour in which is life,
His treasure in the heavens that corrupteth not,
His peace and joy unspeakable and full of glory, yea,
which is a crown of glory that fadeth not away!

L+++.+++ A. Barclay.

To P. D.

7th Month, 1843.

My Dear Young Friend,

As I had no opportunity of having thy company alone before thou left home,
I feel inclined to avail of this medium of conveying to thee the
affectionate interest that glows in my heart towards thee,
as I believe from the source of true love, and the desire I feel for thy best welfare,
and thy growth in that which is truly good,
and enjoyment of that which is truly substantial and enduring.

Thou art now, my dear P., as it were, launching into the world,
entering upon the most important epoch of thy life,
in which thou art not only to be engaged in perfecting
and confirming what thou hast already attained,
in order for its being put to a good purpose afterwards for thy benefit,
if life be spared;
but in which also the character and complexion of mind is likely to be formed and moulded,
and consequently on which the true welfare and enjoyment
of thy after life will very much depend--for it is not our
condition in life that will render us either happy or miserable,
but our conduct and state of mind under our condition!
Oh! then,
that thou mayest seek above all things to have thy
whole conduct and mind moulded and formed aright,
even according to the Divine will which is our sanctification and true happiness!
For, what will it avail us when we come to lie on a deathbed to have gained the whole
world if we have by losing the favour of God lost our own soul and become a castaway!
And however we may be permitted to possess the many good things of this life,
yet if we have not the good favour of our heavenly Father,
what real substantial happiness can we have?
Shall we not feel a sense that all things are not right with us,
even pursuing us everywhere and hindering our real and peaceful enjoyment of all things;
and is not this comparable to "`the worm that never dies,`" mentioned in scripture?

Oh, then, that thou mayest above all things seek the one thing most needful,
the better part, (like Mary of old) that shall not be taken away,
even the precious favour of God in the knowing His
kingdom come and coming more and more in thy heart,
His holy will being done there as in heaven.
Oh, this will bring as it were heaven into thy heart;
it will make the temple of thy heart to be a pure house of prayer,
and a holy temple of praise to thy God forever; yes, my dear,
even in the midst of whatever of outward losses and crosses
and tribulations may be permitted thee in this life!
Oh, then, wisely count the cost and look at the exceeding rich prize,
and be willing to sacrifice even the right eye or the right
hand to obtain the prize and to avoid the worm.

But how may thou know the Divine will and kingdom to come and be established in thy heart?
Certainly not by doing thy own will and following thy own ways and inclinations,
for these are the enemies of thy own house that withstand God`'s
heavenly kingdom and will not have Christ to rule over them.
Neither is it by what thou canst learn outwardly and gather together in thy head,
for this will be but superficial knowledge and a mere imitation.
But "`the kingdom of God is within`" us,
and "`that which may be known of Him`" and His holy will and precious
ways "`is manifested`" or revealed "`within us,`" even by His Spirit
or word that is nigh in the heart and mouth,
so that we need not say "`who shall ascend up into heaven.`"

Oh, then,
that thou mayest diligently take heed to this precious word
(or measure of the Spirit of Christ) within thee,
which will abundantly reveal to thee what is pleasing or displeasing in the Divine sight,
in all thy conduct and conversation.
This is the rule of the new covenant by which thy heart and mind may be
moulded aright--it is the law of the Spirit of life in Christ Jesus,
which as obeyed so the kingdom of God comes to be known and established in the heart,
and the heart thus comes to be changed from a state of nature to a state of grace,
and the mind from being carnal comes to be so changed and moulded as to become spiritual,
and thou knowest it is said in scripture, that "`to be carnally minded is death,
but to be spiritually minded is life and peace.`"
"`The carnal mind (the flesh-pleasing, self-pleasing mind) is enmity against God,
for it is not subject to the law of God,
neither indeed can be;`"--but the spiritual mind
sees and feels God everywhere and in all things;
and being subject to and in unison with His Divine will,
enjoys happiness and a continual feast in all things,
and really reigns with Christ and in Him possesses all things.

Oh, then, this is what I most earnestly long for thee, my dear girl,
even now in entering upon a new sphere of life, as it were,
that thou mayest wholly and unreservedly yield up thyself,
thy whole conduct and conversation, to be formed and moulded,
governed and restrained by this precious word nigh in the heart and mouth,
this Spirit of Christ that visits and calls to thee within;
fear not its reproofs or close searchings, though it be quick and powerful and piercing,
even like dividing as between soul and spirit, joints and marrow.
Oh, it will discern the very thoughts and intents of the heart,
and make a clean separation between the precious and the vile;
but let the judgments and reproofs thereof be more precious to thee than gold,
and sweeter than the honey-comb to thy taste; for,
remember it is the Spirit of Christ that thus whispers in thee and makes manifest,
and He is thy best friend.
His reproofs are better than the kisses of many enemies,
and if thou quench His Spirit in ever so small a degree, He will be grieved,
and if thou despise the prophesyings thereof in the
secret of thy heart about ever so small a matter,
it is the way to lose His favour and to cause Him
to be ashamed of thee at the last great day,
instead of confessing thee to be one of His own dear sheep and faithful disciples.

Oh, then, think nothing too dear or near to part with for His sake;
draw His yoke close about thy neck,
and let the restraints of His Spirit be as golden chains about thy neck,
conspicuously showing unto others whose livery thou hast,
whose servant thou art--so shall His grace be a crown of glory upon thy head,
and the meekness of His heavenly wisdom an excellent ornament,
comely and of great price in the Divine sight.
And I would advise thee, dear, as a means of strengthening thy love for,
and attention to the Spirit of Christ our dear Saviour,
to seek after opportunities of inward retirement in which thou mayest feel after Him.
We cannot pass the day well without such seasons of uplifting of the heart,
of heavenward breathing--and there can be no day in which we may not catch
a few minutes even for this purpose if we will avail of them.
Our spiritual life, our love to God and Christ cannot be supported without it,
but will wax cooler and cooler, wither and die;
and if we thus are not living in Him and He in us,
we shall have no power over sin and self;
but our enemies of our own houses will prevail over us,
and whither Christ has gone we cannot go, for we shall have no part in Him.

Therefore, dear P.,
cleave unto the lowly appearance of Christ by His
blessed Spirit in the secret of thy heart,
and wait more and more to feel Him there, subduing all things to Himself,
to feel His inward power humbling, quickening,
and strengthening thee and as thou yields thereto in simple obedience and humble watchfulness,
thou shalt know Him to be to thee,
however separated from home and situated amongst strangers comparatively,
a most sure Guide, a wonderful Counsellor, thy best and truest Friend,
a mighty Preserver and Helper in all times of need and danger.
Thus mayest thou know Him to be thine indeed, and thou wilt be His,
joined to Him by sacrifice in a precious and perpetual covenant--and oh,
what an excellent experience is this in the season of trial, in the time of sickness,
and in the hour of death!

L+++.+++ A. Barclay.

To a Child Staying at the Seaside

Reigate, 24th of 7th Month, 1843.

I expect these stormy winds we have had these two
last days have thrown up a deal of sea-weed,
and I hope thou art very busy in searching out for
pretty kinds of it and spreading them out on paper.
It so much adds to the interest of the walk, whether by the sea-side or inland,
to have the eyes open to,
and to seek after all the various beauties of creation in the vegetable or animal world,
and then it helps a rainy morning, or an hour of rest to prepare them at home,
at least the vegetable kinds,
so as in the best manner to show forth and preserve their beauty.
And in doing this, my dear girl, we must not, when out in the search,
be so downward with our eyes as not to be able at times to lift them up to behold
the fine sea or the beautiful fields and woods whence these beauties come;
and when indoors preparing them,
we must endeavour not to be too intent outwardly
to behold in them the wonderful wisdom and skill,
power and goodness of Him who has created and given
them for our use and enjoyment and admiration,
that our hearts may be continually lifted up in praise
and humble gratitude to their and our Maker;
yea, that every blade of grass, and tender leaf, and pretty flower, and sea-weed,
may have a language in them,
and raise a corresponding language in our hearts of "`praise Him all His works;
in all places of His dominion, bless the Lord, oh my soul!`"

Oh, what a blessing it is, my dear +++_______+++, to have a tender mind,
one susceptible of the touches of the Divine hand of power and love;
and what great and unspeakable need have we to watch that we may be preserved
in the same--for how many things there are all around us,
yea, and many feelings within us too,
that would lessen this tenderness and harden this susceptibility of God`'s love,
and draw us into carelessness about it and even forgetfulness of Him;
and some of these things and feelings seem so plausible,
so interwoven in our nature and apparently good and sweet,
that it is very hard to part with them when we see them
in the true light by the help of Christ`'s Spirit,
or even to think them amiss.
So that my great desire for thee, dear,
is that thou mayest seek to be preserved in this tenderness,
and to cultivate it more and more--this susceptibility
to the Lord`'s touches of His Spirit,
which during the day of thy visitation thou wilt feel constantly
drawing thee upward and upward still! even towards Him the
source of all good that thou seest all around thee,
and of all the good and tender,
and sweet peaceful feelings that thou mayest at any
time feel spreading over thy young heart within.

And I do believe one great mode of cultivating these precious
feelings is inward retirement and waiting on the Lord,
even in moments of leisure when few may be aware how thy mind is engaged and lifted up.
I can look back to many such precious seasons when I could hardly suppress my tears,
whilst sitting at my father`'s dinner-table with eight others around,
and two servants waiting.
Then did I endeavour to lift up my heart instead of listening
to conversation that would not profit me;
and these were moments often of renewal of desire
and of covenant towards Him whom I felt to be good,
and spreading sweetness over my mind: also when walking out, when dressing,
and often when my hand was upon the door-latch to leave my bedroom for the parlour.
I have since then had to believe that the more such
opportunities are yielded unto and sought after,
the more we shall know them to increase upon us in freshness, and strength,
and blessing,--and, alas!
I have known also that the more I have quenched the drawings thereunto,
and put by such feelings as if out of due or suitable time (where it was only
to save self alive from that tendering power that would silence and slay it),
the more the ability for, and susceptibility of them has decreased and faded away,
and by degrees a leanness and dryness has crept over me,
so that I could hardly look upward at all.

So, my dear +++_______+++,
I would have thee shun all and everything that tends
to lessen thy desire after true tenderness,
true hunger and thirst after righteousness,
and avoid all that tends to increase thy desire to
be like others rather than to please God.
Oh, count the cost, the consequence of such a desire, before thou yields to it,
for what canst thou give in exchange for the soul-satisfying
peace of the Lord`'s countenance lifted up upon thee?
Oh, let Him and His heavenly peace be thy chosen portion,
the inheritance thou longest for, and seek it and pursue it evermore,
even by following after those things that will ever make for true, and substantial,
and enduring peace,
which all the allurements of the world and of false
friends can never give nor yet take away.

And in this thy tender, humble, yet heartfelt and earnest pursuit,
fear not "`the world`'s dread laugh`"--fear not what others may say or think of thee--follow
thou thy dear Saviour`'s voice who speaks in the secret of thy soul,
"`What is that to thee what others may do?
follow thou me,`" as He said to Peter, and remember what the wise man says, "`My son,
if thou come to serve the Lord, prepare thy soul for temptation`"--that is,
expect to meet with trials and temptations,
for so the faithful ever have done--but "`set thy heart aright
and constantly endure,`" believe in Him and He will help thee,
walk in His light and cleave to His power,
and depart not away from what He shows thee to be right--so shall
His blessing be upon thee and His grace all-sufficient for thee,
and His joy in thy soul no stranger thereto shall ever intermeddle with.
For "`look at the generations of old, did ever any trust in the Lord and was confounded?
or did any abide in His fear and was forsaken?
or whom did He ever despise that called upon Him?`"
And "`oh,
how great is His goodness which He hath prepared for them that fear and love Him,
which He hath wrought for those that trust in Him before the sons of men!`"
And I do long thou and dear +++_______+++ too,
may become rich partakers of this abundant goodness
which is placed so mercifully within our reach.
Give my love to +++_______+++. I hope this time of your being together may be
a season of gathering fresh strength and help heavenward:--tell her,
please.

I remain thy very sincere and affectionate friend.

L+++.+++ A. Barclay.

To +++_______+++.

Reigate, 19th of 9th Month, 1843.

My Dear Friend,

I sincerely desire thy help and that of thy dear husband spiritually,
that as your day is so may be the strength and wisdom from above administered--that
you may be kept very close to the Divine gift of light and grace revealed within,
that so you may be safely led along and kept in humility and fear,
in which is the true preservation.
And as those who visit the oppressed seed in the hearts of the professors of the blessed
truth at the present day must expect to go down into deep baptisms and suffering therewith,
oh, that your eye and your cry may be unto the Lord that He may support you through all,
and make you willing to suffer, willing to die often, yea, daily, and to go, as it were,
through a host of enemies, to bring a draught of the water of life,
as from the well of Bethlehem, to revive the spirits of the humble and afflicted.
And, oh, may you not be taken by the gifts or kindness of any,
but endeavour to be deep and inward in mind, to feel whence all comes,
and of what root it springs; and be ye faithful in testifying against evil,
and pleading for the Master, and this will be the true gathering love of the Gospel,
which is the power of God bringing salvation;
and be not discouraged if you be at times closely proved and stripped, as it were,
quite naked--you must be baptised for the spiritually
naked as well as the spiritually dead,
so will you be enabled rightly and preciously to minister unto such,
as well as be preserved in humility and dependence yourselves, that all may be of,
and from, and to the Lord, who alone is exalted and glorified over all, in, and by,
and through His poor servants.

Believe me, with dear love and desire for your help, preservation, and return in peace,
thy friend sincerely,

L+++.+++ A. Barclay.

To J. S.

Reigate, 11th of 11th Month, 1843.

Thou hast my tender sympathy, my dear friend, under thy trying circumstances of suspense,
which must indeed be humiliating, especially to that part in us which would be active,
and is pricked at any slur being cast upon us by our friends, as indolent, or proud,
or careless about a necessary livelihood,
and we may and ought to have many fears ourselves lest we should
bring the least reproach upon the precious cause of truth,
under whose banner we have enlisted.
Oh, there will be much need of close watchfulness to
the precious light of Christ shining within,
in order that the enemy`'s snares may be clearly seen and avoided,
the reasonings and fears of our own minds guarded against,
and the doubts and suggestions of our kind friends supported under,
as well as to show us what is right, and enable to do it.
And I have quite thought with thee that the sojourn at +++_______+++, in the quiet,
may rather favour than otherwise this desire of mind to
watch unto prayer for best direction and heavenly counsel.

Ah, there is, as thou remarks, very much to hinder the Divine work in this day,
even amongst the professors of the blessed truth! and why so,
but because they are gone from the inward,
close attention to and waiting on the living word nigh in the heart and mouth,
but are gone out into outwardness, into the world and its spirit,
where there are many voices to draw aside!
But the Divine work and kingdom is only to be known, carried on, and established within,
and this in the quiet and humility of the creature, sitting as it were alone,
having no outward dependence, and keeping silence, bearing the heavenly yoke of Christ,
and laying the mouth, all creaturely pleadings, and willings, and runnings, and wisdom,
in the dust! and verily to such humbled souls "`there shall be hope`" in the
precious and true knowledge of "`Christ and the power of His resurrection,
and the fellowship of His sufferings, being found in Him,
and made conformable to His death.`"
But, alas! this being a crucifying work, many,
many of the professors of the truth are pleased and taken with
the enemy`'s suggestion of an easier and very plausible way,
by a mere profession, though of the very truth itself!
And thus it is there is so much death and darkness, yea,
blindness amongst us as a people, and the blessed truth,
or Christ in His inward or spiritual appearance, is despised and persecuted,
and trampled under foot by those who should be testimony-bearers for Him!

And consequently it happens that the remnant of those who keep to first principles,
and are desirous of not bowing the knee to Baal or kissing his image, is but small,
even a poor and afflicted people, hidden and scattered by ones and twos,
despised and often reproached by their fellow-professors, and mourning over wrong things.
Yet am I comforted in beholding them, in the vision of light, as a goodly remnant,
comparable to the seven thousand in Israel formerly; their sighs are numbered,
and their tears are bottled, and their foreheads are marked,
and their God knoweth who they are that trust in Him; for they are His own,
and saving +++[+++He]
will save them, and glorifying will glorify them,
as they continue in faith and patience to the end!
And I am gladdened of late by the belief that many
of the dear youth are added and adding to this honoured,
though poor in themselves, remnant.

And oh,
that such dear young warriors in the Lamb`'s army
may not shrink or flinch in the day of battle,
nor faint and grow weary in the time of trial and pinching famine,
but keep their eye to their Captain,
and their ear to His voice who speaks and shows Himself
within a Saviour nigh at hand and not afar off!
And oh, my dear friend, as I comfortingly trust thou art one of these,
mayest thou hold on thy way in His might,
combating all the enemies within that He turns thee against,
and bearing all the privations and trials that He appoints in thy wilderness travel,
and He will not fail to bring thee to the heavenly Canaan!
Oh! it will not do for us to be choosing and contriving for ourselves.
Perhaps what we might think desirable and helpful in spiritual things
might but be like the quails formerly--bring leanness to our souls!
The life, the hidden life of Christ, is more than meat; and the body,
the inward communion and fellowship with His mystical body or Church,
is more than raiment, the bright clothing of spiritual fervours and gifts!
So mayest thou seek after an inward union with this afflicted,
yet truly noble and highly honoured remnant of faithful ones,
whether thy lot be in the city or in the wilderness;
for they walking in the light of Christ,
do truly enjoy a precious fellowship with the Father and with His beloved Son,
and know His precious blood to cleanse them truly from all sin.
It has been of late a great comfort to me to meet
with and to hear of several visited minds,
who have felt tender scruples in regard to business.
This may encourage thee to be faithful to conviction,
inasmuch as the Spirit`'s leadings are similar with all who wholly yield thereto.

And now, farewell, in much love and sympathy and earnest desire for thy growth,
and strengthening, and establishment in the blessed and unchangeable truth,
the Rock of Ages,
on which all the upright have ever built--the Foundation
of prophets and apostles of all ages!
I shall always be pleased to hear from thee when thou art inclined.

I remain thy poor weak fellow traveller, but affectionate and sincere friend,

L+++.+++ A. Barclay.

To Priscilla R.

Reigate, 21st of 11th Month, 1843.

My Dear Priscilla,

I cannot tell thee what a great comfort and blessing I feel
it to have been thus restored to comparative health,
though I do not expect I shall regain the strength and health wholly which I have lost,
and have often many thoughtful anticipations of the future spring,
being still very weak and easily overdone both by exertion and excitement.
But I desire to live a day at a time (if I might but rightly live it),
and to be resigned to whatever may be in store for
me--oh! that I could say with the apostle,
"`To me to live is Christ, and to die is gain.`"
It was indeed an unspeakable favour and blessing that when at the worst those two days,
when I seemed gasping for life, as it were, my mind was preserved so quiet,
and in the intervals of pain such sweet and precious
renewals of confidence in the ancient and sure Foundation,
the Rock of Ages, the Word that was in the beginning,
the quickening Spirit from everlasting to everlasting,
the Lamb slain from the foundation of the world, the Light and Life of the world.
And now, oh,
that I may walk worthy of such great condescension of Him
who thus renewedly revealed His dear Son in me,
that I may "`serve Him without fear,`" in renewed devotion
and humble gratitude all the residue of my days.
It is a great comfort to return again to our winter habits and settled evenings.

With very dear love to you all from thy affectionate friend,

L+++.+++ A. Barclay.

To J. W.

Reigate, 25th of 11th Month, 1843.

My Dear and Honoured Friend,

I am grieved that I should have appeared negligent of thee,
and still more so if thereby I had given rise in any way to a supposition,
at low seasons,
that there should be any shaking or diminishing in the near unity
and tender sympathy which I have felt and do feel with thee;
yes, and in the firm and humble confidence which clothes my mind, that the Lord,
whom thou servest,
and for whom thou art willing to testify and to suffer to thy latest breath,
and in whose might and wisdom, love and mercy thou trustest,
will still condescend to guide and strengthen, support and comfort,
to preserve thee in humility and patience,
and in unflinching faithfulness and boldness in His pure
testimony unto the end--that nought of the flesh may glory,
but that "`His glory may dwell in (and fill) thy land,`" and His
salvation be near and round about thee (who fearest Him only),
even as "`walls and bulwarks.`"
And oh, what a favour it is,
and a great comfort to me to hear (which indeed I did not doubt),
that thou hast been thus Divinely supported and comforted amidst all thy bitter trials!
so that one may truly say that righteousness and peace have kissed each other,
and praise has from season to season been as the gates of thy dwelling.
And I do hope and trust it will be so to the end, and that thy life and strength,
both outwardly and spiritually,
will be preserved and strengthened for the time of trial permitted.

And seeing the weakness of human nature,
and how difficult it is for those who are persecuted and afflicted
to maintain the watch and the true meekness of the Lamb,
how do I crave that we may be helped with a little help from the holy sanctuary,
from season to season,
to "`be sober and watch unto prayer,`" to stand fast in the true faith,
upholding and contending and suffering for it,
in the true meekness of wisdom and humble patience,
and with holy zeal and fervour of soul, keeping our own garments with all fear,
lest we become naked at unawares,
and breathing for the gathering of the erred and deluded--that thus being
enabled to stand in our lot of suffering and to abide in our tent or holy
enclosure of subjection to the Spirit of truth to the end of the days,
we may be permitted "`to stand`" at last with acceptance "`before
the Son of man,`" and to rest forever in the joy of our Lord!

Our discipline is but a dead letter.
Wrong appointments by means of riches and influence,
and consequently Friends in stations wholly unqualified for them,
and whose hands are not clean,
so that we seem completely gone back as one of the daughters of Babylon,
and the true Church is only known among the hidden ones as it were in the wilderness.
But, oh, that we may patiently wait,
and seek to possess our souls in patience--though it be a day of Jacob`'s trouble,
the Lord will in due time deliver him out of it.
My dear friend,
I had thought I should have been released from this scene of trial and affliction,
and I was favoured to feel very peaceful and quiet under such a view--yea,
to feel a most precious degree of union and communion with the spirits of the faithful;
and the feeling spread over sea and land, even to the land of America,
and the faithful tribulated ones there.
I have had a serious illness, which has confined me ten weeks,
or thou wouldst have heard from me ere now.
But, through mercy adorable, I am again raised up,
and got out to meeting the first time this week.

In the course of my journey last spring into Scotland, I was very ill,
yet was graciously enabled to accomplish all that came before me, though in weakness,
and fear, and much trembling for myself, and was permitted to return with peace,
though afterwards proved with many plungings, buffetings,
and discouragements--no doubt for my humbling and good.
There was much to afflict and grieve,
both in Scotland and in going through the north (of England); my eye affected my heart,
and I think I may say also, my spirit affected my eye, for feeling is beyond sight.
There are divers appearances in the ministry of late that I fear are raw--many
among the youth who are not giving proof of coming under the sanctifying power.
The world also and its many snares seem to have overcome both old and young.
Yet are there a few grains of the savoury salt left here and there,
as it were "`two or three berries on the top of the outmost branches`"--chiefly
among the poor and hidden with whom I was comforted,
and with some of whom we mourned together over our waste places and the glory departed.

And now, my dear and valued friend, I must reluctantly bid thee farewell.
It is pleasant to converse in this way together; but still more precious to drink,
as it were, into one and the same blessed Spirit.
This union and communion remains the same in silence or in words,
in strength or in weakness, in joy or in tribulation, in life or in death.
In a measure of this do I tenderly salute thee,
and remain thy affectionate and sympathising friend,

L+++.+++ A. Barclay.

To J. S.

Reigate, 6th of 12th Month, 1843.

I am pleased that thy dear mother continues tolerable for her,
her age and infirmities considered; do give my dear love to her.
It is sweet to think of her, and I trust,
though she is unable now to mingle personally with her friends at meeting,
and to share thus in the sufferings and wadings of the faithful,
yet that she is favoured to experience in her own chamber
the teachings and replenishings of the Minister of the sanctuary,
the blessed Messenger of the covenant, who sometimes breaks in suddenly into His temple,
the temple of our hearts, as the Sun of righteousness with healing in His wings;
and truly He is precious to a tried remnant, whose souls delight in Him.
I have often remembered a farewell desire expressed on behalf of a dear aged Friend,
Christiana Whiting, by the dear pious Indian, Peter Jones,
who is mentioned in Thomas Shillitoe`'s journal, when he was over here, viz.,
"`May the great good Spirit talk with thee in thy heart every day.`"
This, I trust, is thy dear mother`'s experience in moments of solitude,
and I hope will continue so to the end; and if Jesus be thus with her spirit,
she need not fear, but rejoice in the Lord alway.

With dear love to you both, I remain thy affectionate friend,

L+++.+++ A. Barclay.

To +++_______+++.

Reigate, 12th of 12th Month, 1843.

My Dear Friend,

I wondered much at Friends allowing you to miss those solitary few at
+++_______+++. I should have thought as you began your service at +++_______+++,
that +++_______+++ would have known of them,
and it was their duty to have laid them before your minds,
in order that in laying out the meetings for you,
they might have been embraced at the most suitable time.
But, alas! we do find that too few have the cause of truth really at heart,
they will only do what they must to save their credit
and without which they should be censured.
There is too much a "`loving the praise of men more than
the praise of God!`" and what is the cause thereof?
a want of seeking after a constant exercise of mind to know a baptism into Christ,
whereby they would know a death unto self and a living unto Him,
and consequently a feeling for and with Him,
a seeking and loving His things more than a seeking and loving their own things; but,
alas! for want of this they get buried in the earth and the lawful things,
and so can neither see, feel, or act for Him as they should!
I have felt nearly united to +++_______+++ in time past, and long to know how she is now.
Thou dost not mention +++_______+++, but I suppose that was not left out,
and no doubt it was a trying visit: what a beautiful spot it is outwardly,
or rather the county round! and oh, that those gathered to the truth had continued in it,
then it might have flourished spiritually also, even as Eden,
and sent forth a fragrant savour as the blossom of the rose.

Well, dear +++_______+++, you seem to have gone along.
I hope you were faithful in delivering close things where required,
and setting the truth over gainsayers, and pleading with the refusers,
and arousing the careless; for the present is a day when,
if we plead faithfully for our Master, we cannot fail of having close things to preach,
not pleasing to those who have itching ears, that like smooth doctrine,
and to be encouraged as they are;
and then consequently we must expect not only to pass through deep baptism, plunging,
and wading inwardly, but also to meet with much trial and despising,
and evil report outwardly, although perhaps to our faces we are spoken smoothly too;
for the world (among Friends) whilst it loves its own and what
will foster it (or at least not hew at it but save its life),
is also very insincere--it being the fashion to appear kind and amiable.

But oh, how precious to have unity with the dear Master in His sufferings;
to feel where He is not,
but rather mocked and scourged and crucified--and to labour with Him in His forgiving,
gathering Spirit, with "`Turn ye, turn ye, for why will ye die!`"
Ah! there are many snares and temptations for poor travellers!
It is easy to be taken with the outside of things,
easy to be bribed by or pleased and gratified by the kindness of those
we go amongst--easy to appear pleased with or to wink at wrong things,
from a desire of gathering and of not appearing gloomy;
but it is hard to get down very deep beneath the workings
of self or the world both in ourselves and others,
in order truly and availingly to minister to the true and living birth,
and to reach the pure unflattering witness within.
But, alas!
I often fear there is too much of a superficial ministry amongst us,
a dwelling as upon the surface, and consequently a pleasing and being pleased,
and self being nursed up in us,
and thus come light-weighted concerns to increase amongst us,
and though there is much preaching and running to and fro, there are but few fruits,
solid fruits in a true convincement and conversion!

With dear love to you all, thy very affectionate friend,

L+++.+++ A. Barclay

To +++_______+++.

Reigate, 16th of 12th Month, 1843.

&hellip;I should be obliged by thy giving my dear love to dear +++_______+++,
and tell her I feel a sincere and earnest desire for her
best welfare (though I did not write on her birthday),
even that she may "`buy the truth and sell it not,`" that is,
by obedience to what is made manifest in the secret of her heart,
even at the sacrifice of her own will and inclinations,
to seek to have the kingdom of Christ set up in her heart, which kingdom is not in word,
not in an outside profession, but in power;
even that power that enables to overcome all evil inclinations and worldly lusts,
and to do the will of God.
Her dear parents cannot give her this experience, though they can direct to it,
but she must seek it for herself,
and she is come now to an age when she must show forth the
fruits of their faithful labour and good example,
proving to others that she is as desirous herself
to come under the nurture and admonition of the Lord,
as ever they are and have been for her;
thus will she become increasingly a blessing and comfort to them,
as well as know that peace within which the world and all its allurements can never give.
Oh, then, may the example or reasonings of no one, nor yet self-love in any shape,
hinder her from, above all things, pursuing after this peace,
and seeking this rich treasure which never shall decay, nor ever fail.

L+++.+++ A. Barclay.

To S. B.

28th of 12th Month, 1843.

Though so distantly separated, dear +++_______+++,
thou art very dear to us in that bond of true love and fellowship
which stands not in word or outward communication,
but in the life and power of Jesus Christ prevailing,
and made manifest in our mortal flesh through the daily dying to the old nature!
Ah, how precious is this,
and how greatly do I desire its continual renewal or nourishment,
lest it should decay or wax dim,
but rather may it wax brighter and brighter unto the perfect day of redemption!
And how may this be but by the daily quickenings of life
and a yielding to the crucifying operations thereof.
Then let us endeavour to stir one another up,
and breathe for one another`'s help hereto again and again,
though in person we be absent one from the other;
and our friendship being founded on the true love shall not be dissolved by death,
any more than it is fed by outward intercourse, by gifts, or kindness, or feastings,
or commonly called civilities,
nor designated by the shaking of hands or saluting the body.

I hear +++_______+++ was strikingly engaged on third day last,
at the quarterly meeting at +++_______+++, at which I rejoice,
and earnestly desire his preservation in the low valley of humiliation,
whence are fetched up the few smooth stones for the bringing
down the mighty Goliaths of the present day,
as slung in the holy name of the Lord God of Israel,
who is mighty as ever to save His tribulated people,
and to perfect His praise out of the mouth of babes and sucklings!

And now, my dear friend, farewell.
May the Lord whom thou desires to serve faithfully be with thee,
and as it were hold thy hand in the hour of trial,
and mayest thou still trust in Him to the end, and He will do thee good.

L+++.+++ A. Barclay.
