== Chapter XII

To J. B.

Reigate, 29th of 2nd Month, 1844.

My Dear Friend,

I desire to feel thankful that my love to the cause of truth is as warm as ever;
and if there be less of an ability to work for it actively,
I trust there is more of a capacity and willingness
raised in me to suffer for it night and day.
Ah, there are too few now-a-days who are grieved for the afflictions of Joseph,
and too many who are adding thereto.
When the Lord calls to weeping and to mourning, as He still does like in old times,
there is too much of a disposition to salve things over with a wrong love and unity,
and to cry Peace, peace, and to call to feasting and rejoicing and encouragement,
as in Isaiah`'s time, as if all were well with us!
But this was an iniquity that was not to be purged away,
the prophet declared in the word of the Lord.
But I believe the blessing will be to the mourners, and the poor in spirit,
and the persecuted and reproached, as all the Lord`'s people have ever been--that is,
those who are true to His cause--and which is the highway to His kingdom,
inasmuch as it is of His own work and begetting in them,
for they cannot give to themselves the true sight and feeling for and with Him.

Oh, then, saith my soul,
that He who has thus quickened in us a little of the true feeling,
even by the life or Spirit of His dear Son in us,
would be mercifully pleased to give us a heart to wait daily upon Him for more life,
more feeling, more strength,
more humbling from Him the heavenly Fountain of all good--that we may
be continually thus renewed in knowledge and life and holiness,
after the image of Him who hath created us,
and then shall our knowledge be preserved and continued
in the will and life of the Father,
fresh and savoury, and nothing of our own or at our own command;
and thus preserved it will not be barren or unfruitful, but will lead to a holy,
humble zeal and a faithful acting for our Divine Master,
whose kingdom is most dear unto us of all things here!

With dear love, I remain thy affectionate friend,

L+++.+++ A. Barclay.

To +++_______+++.

7th of 3rd Month, 1844.

These are trying times and shaking times,
but none of the weighty wheat or of the pure metal shall be lost or hurt.
That which is too light to bear the turning and overturning
in the heavenly sieve will be driven off by the wind,
and that which is combustible and cannot stand the fire,
or dwell with the everlasting burnings of the Divine word is to be done away,
that that which is pure and cannot be shaken or hurt may remain.
And blessed are they who, yielding to it, keep the word of patience to the end,
suffering the Divine power to work in them the Divine will;
for it is not by might or power or wisdom of man now in
the erecting of the building of life in the soul,
any more than formerly in the erecting of desolate Jerusalem and her temple,
but by the Spirit of the Lord,
and such as yield thereto shall rejoice in beholding the plummet
of righteous judgment in the hand of Christ our spiritual Zerubbabel,
and that the headstone of that which seemed as a great mountain shall be brought down,
and brought forth with shoutings of "`Grace, grace, unto it.`"
Ah, yes,
I believe that in due time all the many horns and the many mountains
of lofty profession up and down will be brought to nought before
and by the little stone cut out without hands,
and which shall indeed become a great mountain,
and fill the whole earth with the knowledge of the glory of God!

The main thing for each one of us is to seek to know this great
and glorious work carried on in our own individual hearts,
and then what does it matter how hidden, how solitary, and how afflicted our lot may be,
if we know this blessed Foundation, even the life and peace of Christ the word,
the quickening Spirit, the Lamb slain from the beginning to be raised up in us,
and we to be builded upon and in Him; do we not know that it remaineth sure,
having this seal, the Lord knoweth them that are His,
and let Him that nameth the name of Christ depart from iniquity?

L+++.+++ A. Barclay.

To J. S., on the Death of her Mother.

Reigate, 15th of 3rd Month, 1844.

My Dear Friend,

Be assured thou hast our affectionate and tender sympathy under the great loss which,
in the dealings of an all-wise Providence, is permitted to come upon thee,
but one in which thy and our mourning can only be for ourselves that are
left behind in the separation from one dearly loved by us;
for on her own account we can do no otherwise than rejoice,
and as it were join our acclamations of praise and thanksgiving with hers,
now liberated from the shackles of mortality,
and translated to the realms of unmixed peace, joy, and rest,
where the wicked cease from troubling!

Ah, my dear J., how much, very much of mercy is mingled in this cup,
which is and must be bitter to nature!
What a favour that she was not taken ill while thou wast here! and what
a mercy that she should have been spared a long and trying illness,
that thou wast thus so gently and tenderly dealt with,
and that she seemed as it were rapidly (without time for thee to
be preyed upon by affecting anticipations) to fall asleep in Jesus!
Ah, we cannot doubt it is well with her in Him,
and may we seek for ourselves such a humble hope,
by endeavouring like her to dwell near to Him, close to His Spirit in our hearts;
for what a good example was she of a conscientious uprightness to what she felt
was consistent with His inward kingdom or truth in the inward parts,
and walked in humility and childlike trust as long as ever I knew her,
and truly sweet it was to sit beside her,
whether in meeting or in her own little parlour!
Surely this sweetness arises from the love of God shed abroad in the heart--He
first loving us and causing us to love Him and one another in Him.
Oh, then,
that we may yield to the same precious love when we feel
it as it were spread over our minds like a holy,
quiet canopy, and He will cause all things, however trying,
to work together for our good, be our strength and comforter,
our guide and preserver through our solitary pilgrimage,
give us good hope through His grace in Christ Jesus, and receive us unto Himself at last!

It would have been in my heart to have testified the dear love and respect I had,
by being present with you on fourth day afternoon,
but do not think I could possibly manage it, but shall be with you in mind no doubt,
and +++[+++may]
the dear Master`'s power and presence be with you,
solemnizing the mind and gathering the spirit into union with the Divine will.
It will be inward powerful preaching and reaching to all around;
and this is what she desired, dear creature,
that the Lord`'s name over all might be praised, exalted, and glorified forever,
who is worthy to be served, loved, honoured, and obeyed!

Farewell, dear J. With our united dear love,
I remain thy truly affectionate and sympathising friend,

L+++.+++ A. Barclay.

To +++_______+++.

Reigate, 8th of 6th Month, 1844.

My Dear Friend,

Thou knowest sometimes we may have a pointing to service, which perhaps,
after being under ground as it were for some months or even years,
may be again elicited and called up into avowal and action,
by a pointing towards joining another in similar view; and if this should be thy case,
I do not think thou shouldst say thy feeling merely arises from sympathy.
I thought I would just leave this sentiment with thee to feel about,
and be assured thy company would be truly helpful to me,
who am indeed a very very weak one.
What I meant to convey to thee the other day,
and which I fear I did abruptly and awkwardly,
was the feeling which thou knowest I ever have had,
that where the attraction arises entirely from sympathy,
and not from any previous feeling in the mind towards the service in days past,
there it seems to me doubtful about proceeding.
Ah! we want our conversation to be regulated and restrained as well as other things,
and our words to become few and savoury.

Farewell very dearly, and when it is well with you,
remember your truly affectionate friend,

L+++.+++ A. Barclay.

To L+++_______+++ +++_______+++.

21st of 6th Month, 1844.

My Dear Friend,

From a little that transpired last evening,
I am inclined to turn thy attention to these two valuable tracts,
which have been often a comfort to me and a strength,
and please accept of them if thou likes them,
and they may be useful to lend to other dear fellow travellers,
who are seeking the way to Zion with their faces and hearts thitherward set.
And I am also reminded of a letter of James Parnell`'s to Stephen Crisp:--

In that stand, and unto it keep thy mind,
which lets thee see thy foes to be of thy own house: thine imagination is an enemy;
thy wisdom is an enemy; that which hath been thy darling is now thy greatest enemy;
therefore now sacrifice up thy darling and give up unto the death,
that the just may be raised to life,
and the righteous seed may be brought forth to reign and be thy Head,
and so will the head of the serpent be bruised.
And this, in thy measure, thou comest to read as in the light thou dwellest low,
which manifests unto thee thy condition; for whatsoever makes manifest is light:
and that is the eye which must be kept open,
which the god of the world blinds in the children of the world.
By this the children of the light see the god of the world, and so the tempter is known,
resisted, and denied.
So with this eye, set thy watch constant, and let not the fool`'s eye wander abroad,
which draws out the wandering mind after the visible objects; but stand in the warfare,
not giving place to the enemy nor his delusions; and be content to become a fool,
that all selfish thoughts may be judged,
and thou wilt receive wisdom from Him (who giveth liberally and upbraideth not),
to discern and know the enemy`'s wiles.
For in the cross to the hasty mind the gift of God is received; therefore it is said,
he that believeth maketh not haste.
Be not therefore weary of the yoke, for in faith it is made easy,
and the impatient nature crucified, and patience hath its perfect work.
Therefore be still in the measure of light which exerciseth thy mind unto God,
and will nothing; but let thoughts be judged, and let the power of God work,
that He may be seen to be all:
and by this alone principle thou mayest be led and acted in the cross to the carnal,
and the denial of self in particular and in general.
And weigh not what is displeased when God is pleased,
for then thou givest no just occasion, but the enmity is in the world;
but that which leads to walk towards God in faithfulness,
that also leads thee to walk towards men with a conscience void of offence.
So to that keep thy mind, and be not hasty to know anything beyond thy measure,
for there Eve lost her paradise; but lie down in the will of God,
and wait upon His teaching that He may be thy head;
and so thou wilt find the way of peace, and dwell in unity with the faithful,
though of the world thou be hated, for in God is peace and well-being.

I did not intend to copy the whole of this valuable letter,
but when begun I knew not where to stop!
Oh, my dear friend,
yield to the Lord`'s power that yokes down all the powers of the creature,
the strong will, the wise comprehending mind, the flighty soaring imagination,
with all the bright sparks of the intellectual faculties,
and brings all into the pure stillness,
where alone the Lord`'s voice is distinctly heard and understood,
and the guidings of His heavenly eye or light within
are clearly seen--and there be content with,
be wholly resigned to what He gives thee, look not for more certainty,
otherwise how can there be an acting in faith?
The gentle whisper, the secret hesitation, the assurance of peaceful quiet,
attending the doing or the forbearing, the saying or the forbearing is enough!
Be thou faithful in the little already revealed,
although it be unto the death of that which seems as dear as life,
and He will give thee more and more light and life, strength and peace here,
and a crown of life hereafter!

And, dear sister, does not this testimony live in our poor feeble hearts,
even as far as we have been helped along.
"`The Lord is good,
a stronghold in the day of trouble;`" and so I believe
He waits to show us yet more of His goodness,
and to make us large to receive it still; and if it be by emptying us,
or proving us various ways, what does it matter!
And what if He give thee yet to know more of trouble
and affliction that may be very pinching;
if thy heart be upright unto Him in His fear and
holy trust (in the true subjection and resignation),
He will abundantly show thee that "`He knoweth them that trust
in Him,`" that He is near to care abundantly for them and to comfort
them on every side! and His blessing makes truly rich,
and when He speaks peace who then can bring trouble or make afraid!

So farewell, dear L.,
and may you breathe for the help and preservation of your poor weak friend,
who feels very trembling and foolish for so awful a mission,
but knows that the Lord is very good and very strong!

L+++.+++ A. Barclay.

To +++_______+++.

Gloucester, 13th of 7th Month, 1844.

My Dear +++_______+++.

I have not been able to write thee before,
I find it so difficult to get scraps of time for writing,
or even for that quiet of mind which is indispensable,
at least for so weak a body as I. My only time for
quiet has been at night and early in the morning,
and so I have got into the way of being wakeful, in order to obtain such opportunities,
usually waking about four o`'clock, and sometimes not asleep till eleven or twelve.

I thought much of thee yesterday,
hoping thou hadst been helped with some little refreshment at quarterly meeting,
although I know such times are not rejoicing times, but, on the contrary,
times that often bring burdens; but it is a favour to be made sensible of burdens,
and be willing to bear them.
We cannot give ourselves the true feeling that grieves for the afflictions of Joseph,
neither can we keep it alive in us,
nor yet give ourselves the ability rightly (patiently, faithfully,
and humbly) to bear burdens for our Master, our spiritual Joseph,
who has the keys of the heavenly treasury;
so we have great need to wait for His blessed quickening and anointing and humbling,
that we may daily be kept upright unto and for Him;
and our patient suffering and our faithful, humble labour, shall not be in vain in Him,
but it shall prosper in that for which He designs it,
even our continual redemption and purification, if not the help of the body.
Therefore don`'t get too low below the gift of heavenly faith and Divine grace,
but cheer up and cleave to that wherein is the strength
and the hope that shall be as an anchor in all storms,
and let the eye and the cry be unto Him that endureth forever, and so does His goodness,
and whose power is all-sufficient; the heart lifted up,
and yet the spirit lying low before Him, and He will not fail or forsake,
who has been with us in six troubles (can we not say?),
and will not leave in the seventh.

I had a sweet letter from dear brother Abram, and intend, if I can,
to write to him by the middle of next week to meet him at home;
it was very timely and acceptable when much weighed down.
I had also the same day a kind letter from dear D. P. Hack.
I went to Cheltenham on third day evening, and back fourth day evening,
a very exercising time next day at monthly meeting.
I left there and came to Tewkesbury,
an appointed and trying meeting at six in the evening, lodged,
and am just come on here by railroad.
I hope I go to Hay on second day, to attend the monthly meeting there next day,
which is brought forward from the 30th, and then on to Brecon select and general meeting.
I don`'t know how I shall get on tomorrow, I greatly dread it; but, oh,
that I may keep close to the great and good Master,
and then no matter how poor or weak the instrument appears.

Dear S. D.`'s message came remarkably to my help at Cirencester; do tell her so, please.
I shall not forget the time.
Was deeply exercised in meeting,
and had strength at last to speak on the subject of tenderness and brokenness,
and a forgiving spirit,
and a healing gathering love as a mark of being baptised into Christ Jesus,
and therefore a Christian, etc.
I marvelled at it, but was helped in a hobbling way to relieve my mind,
and then addressed the youth.
Now I am entering a new field; it feels formidable,
but what a favour to have been helped hitherto!

Farewell.
I remain, with dear love, thy affectionate friend,

L+++.+++ A. Barclay.

To the Same.

Leominster, Third Day Afternoon.

My Dear +++_______+++,

Thy letter was very acceptable, and interesting, and affecting to me,
though thou thinks it bare.
Tell +++_______+++ how closely I am engaged, and that I could not write,
but felt her expressions encouraging and kind,
and even her dismal tale did me good in leading me into
tender sympathy and oneness with the suffering members,
and I thought as seeming to partake of their afflictions
or the sufferings of their Master.
I was also graciously favoured with a little drop of that
precious consolation which is in and from Him,
giving one to rejoice even in tribulation,
and to long to be kept patient and faithful under it to the very end.

I must be brief, but just tell thee I had a very fatiguing journey to Hay,
twenty miles before the monthly meeting.
I was helped in a little humbling way, and after a hasty dinner,
and an opportunity with our host`'s family, who had just lost a daughter,
went on fifteen miles to Brecon, where we were at a large hotel two nights.
A party of fifty to our meals each day, in a long room formed by opening folding doors,
a motley group,
but very interesting and sweet to me to meet many
that I knew and felt much about in times past,
viz., dear +++_______+++`'s relatives from Wales,
and the descendants of the good and truly honourable, some friendly and others not;
but over all the Lord`'s good power and tender wing of everlasting
love seemed to hover and spread at each of our meals,
to gather the children and sanctify the elders, and to heal all,
so that we had much sweet silence.
It reminded me much of the Cornish quarterly meetings at Austell,
where we used to be at an inn in the same way.

I had after long silence a long time of relief,
and after the epistle to bow the knee in much fear, awe, and trembling.
Perhaps they never had such a weak one with them before.
The meeting for discipline was agreeably conducted.
There was a committee on elders sat that evening, and Friends wished me to be with them,
as also to join a committee to visit a little meeting that is very weak in Wales,
but I felt best not, as not in my tether, nor drawn to it;
so I sat at the window meanwhile writing to dear Abram,
and had a most beautiful view of the fine Welsh mountains
glowing with the rays of the setting sun,
which carried me back in mind to the bonny, canny mountains of Scotland.
Oh, the country round Brecon is exactly like Hawick and Jedburgh.
We left next morning,
and after dining at a Friend`'s at Hay (or near it) came on here to tea late.
I have had an exercising meeting here this morning,
but was comforted with dear Ann Burlingham`'s company.

I am getting to feel a little relief now, which is a great comfort.
Although I felt very low on coming here, so I do at every place,
like fresh mountains rising up to be got over.
If it were not for a little help from above from day to day what would become of me!
It must be watering every moment truly, as the prophet says.

Farewell, dear +++_______+++. With dear love, thy affectionate friend,

L+++.+++ A. Barclay.

To +++_______+++.

Reigate, 16th of 9th Month, 1844.

My Dear Friend,

Opportunities are not always at our command of communicating our feelings one to another;
and this being the case with me when we last met at J. M.`'s,
I thought it seemed with me the first scrap of time I could get to put pen to paper,
and tell thee how much I desire thy encouragement to persevere in the
way that seems to have been cast up for thee these many years,
"`not slothful in business,`" yet withal "`fervent in spirit, serving the Lord.`"
I would not have thee to be over-anxious,
in a distrustful spirit--this would not be "`casting all thy care upon
Him`" whom thou canst truly say hath hitherto abundantly cared for thee;
but mayest thou be stimulated to do thy very best,
and then leave the rest in His good hands.
It is an old saying and a good one, "`God helps those that help themselves.`"
I wish it was more the practice of those who can afford it,
to deal with their neighbours in preference to their relations or their own customers,
who perhaps do not want it so much.
There is an old saying,
"`Keep thy shop and thy shop will keep thee,`" so I long thou mayest give thy
mind to thy business in promoting its increase by all means in thy power,
and then trust that which is right will be given thee.
Mind I don`'t mean by so saying that worldly things should be uppermost;
but I think where heavenly things are uppermost,
it will not by any means exclude or hinder a proper
activity and diligence in our outward calling,
but on the contrary will be a true stimulus, and safe guide,
a right balance to outward things.
It will urge us to set about them in the right and savoury way,
and is very likely to draw down the Divine blessing;
and our minds will be kept from unprofitable harass and mistrustful anxiety or murmuring,
and will be stayed in perfect peace on Him who can bless the little and blast the much!
And this will be serving the Lord;
for we may be serving our business with an eye unto Him,
and He may be glorified therein as His fear is abode in and His Spirit followed.

I hope I have not hurt thy feelings in writing thus freely.
Thou knowest I feel tenderly interested about thee.
My only desire in so doing is to encourage and stir thee up,
as also to give a few hints as I felt well in the true love.
I shall be much interested in hearing how thou finds things when thou takes stock, etc.,
if thou art free to tell me.
I think thou wilt find the barrel of meal will not waste,
nor the cruise of oil fail till there be a heavenly supply; so cheer up, and do thy best,
and trust thy Master, and don`'t look at the favour of man; I mean don`'t bow to man,
but go on thy even course in uprightness and faithfulness, and neither fear nor doubt.
Commit all unto Him who is a faithful Creator, even in well-doing--that is,
in the faithful acting, the watchful walking, the humble abiding, and all things,
however trying and humiliating, shall work together for good.
How various are the Lord`'s ways and tender dealings to humble us,
and to bring us to a full and entire dependence upon Himself!
The more we bend under His good hand and learn His good lessons,
the less we shall need of that which tries us.
From thy truly sympathising and affectionate friend,

L+++.+++ A. Barclay.

To +++_______+++.

Reigate, 19th of 11th Month, 1844.

My Dear +++_______+++,

I hope the time may come when thou mayest be able to come and spend a little time with us.
I want to have thee much, and I hope to be able to read French together,
and to go on in a quiet and regular way, and above all,
I want us to be a little favoured together with the
flowings of the spring of life and love Divine.
Oh, my dear,
I fear thou hast somewhat lost ground of late through
a want of daily waiting for best help and humbling!
Thou knowest it is easy to lose a relish or desire for this daily exercise; nay,
that man`'s nature is opposed to it radically,
and so much around him is calculated to deaden this desire and relish,
and to draw him into lukewarmness and indifference;
and when we yield to this disinclination,
we insensibly lose our relish for heavenly things,
and our own natural and wayward inclinations become stronger,
and we become like Samson shorn of our strength, and if we look back a few months,
or a year or two,
we shall be sensible that we have lost that tenderness which once we had.

So that, my dear +++_______+++,
I want thee again to be aroused to fresh diligence in seeking after
a true exercise of mind--a breathing towards God every day.
There is much in that sentence of scripture, "`their strength is to sit still.`"
It is in stillness that the powers of nature are brought down by
the tendering power of the Lord and our hearts are made soft;
we are melted under a sense of heavenly goodness to us in various and many ways,
and under a sense of our many deficiencies and unworthiness;
and a true feeling of our weakness is given us,
and earnest breathings unto God for help and cleansing and
pardoning and renewing of a right spirit within us,
and this humble, soft state is very acceptable in the Divine sight;
it is described as the sacrifices that God will ever accept and never despise;
and in this state of softness we are the better prepared
to receive the celestial showers of goodness,
and to drink them in and be strengthened and profited thereby.
And even should we be proved at such seasons with drought and famine from what we desire,
yet even here may our strength be renewed in faith and patience to wait the Lord`'s time,
and still to look as it were towards His holy temple and hope in His mercy.

So, my dear, be diligent, that thou may be found of Him in peace,
for I do believe this practice will bring thee true peace with God.
And thus I believe also thou wilt be the better enabled to keep
a holy and constant watch on thy demeanour and conduct at all times,
to keep in thy proper place,
which as a young person is ever in retirement and much silence,
waiting to receive instruction,
and not intermeddling in what does not concern thee or what is not necessary.
Thou knowest I love thee dearly,
and therefore gave thee a hint about this when I was at +++_______+++;
but I thought I would again stir up the pure mind in thee,
hoping that in thy solitary evening thou mayest be inclined to
and enabled to turn in thy mind to the unflattering witness,
which will show thee how thou art deficient, and point out a remedy,
and also enable thee afresh to renew covenant with the Lord,
in desire to be His dear child and a lamb of His heavenly fold.
And what a comfort it will be to thy parents thus to see
thee growing up in the nurture and admonition of the Lord,
and thou wilt then be taught more and more in the things of His heavenly kingdom,
which are foolishness to the natural part in man,
neither can he discern them by all his strivings in his own wisdom and strength,
nor yet can parents or teachers bring us into the feeling of them,
though they may testify of them--it is the Spirit of God alone that can reveal
them unto us as we are willing to be taught of Him in stillness and submission.

And so thou remembers that dear young woman, whose letter I read to you,
learnt of the Lord in stillness and obedience, and was thus prepared,
though young in years, to testify to others that the Lord is good,
and that His yoke is light,
and His consolations most excellent--and this she testified
from experience and not mere hearsay and superficial knowledge.
So I want thee to come to the same blessed experience, and to be a real Quaker,
not by birthright and education merely, but from waiting for, yielding to,
and trembling at the word of the Lord in the secret of the heart;
for "`to this man will I look, saith the Lord,
even to Him that is poor and of a contrite heart, and that trembleth at my word.`"
Don`'t be ashamed then of that state of mind which
God will graciously look unto with acceptance,
but seek after it evermore, and cherish it, and hold it fast,
and then none shall take away thy crown of life--peace and pure rejoicing in the Lord.

Farewell very dearly, very dearly, saith thy affectionate and truly sincere friend,

L+++.+++ A. Barclay

To Mary +++_______+++,
in Allusion to the Practice of Informing Friends of the Receipt of Their Certificates.

Reigate, 7th of 12th Month, 1844.

My Dear Friend,

My view of these appointments is that they are not to be done in an off-hand,
business-like way, like outward business, and without feeling,
but that we should allow plenty of time for some social intercourse as well as
religious feeling--we know not how such times may prove a blessing in after life!
But I often feel a solitary bird; few see and feel with me,
and many think the sooner they get rid of such jobs the better,
so a few minutes is sufficient!
But surely this does not show the true feeling one for another,
neither does it further the dear Master`'s heavenly cause.
I often long for my dear friends that they may not
be looking one on another and doing as others do,
but be more inward in their minds to feel what the sense
and savour of the life and truth within would lead into,
how it would conduct them in what they do for the Church,
and then I believe we should be led simply, faithfully,
and humbly along without the fear of man and in the fear of God; and then,
however little might be the work required at our hands,
it would all tend to His glory and to our increase
and strengthening in ability to serve Him with peace.

I hope thou wilt not take discouragement from these my remarks,
for I am not alluding herein to thee, dear Mary,
but to the common (too common!) views and feelings of such things.
No, I long for thy encouragement in every good word and work,
and would do all in my little power to promote it;
for thou art one among the several or many in our
monthly meeting that I feel ought to buckle to,
by yielding to the Divine power,
so that you may be clothed with the whole armour of light,
and thus become strong in the Lord and for Him too,
and in the power of His might to uphold His ancient testimonies, that they may be,
as they were to faithful, humble David, your delight, your counsellors,
and your heritage and rejoicing forever!

Farewell, dear Mary.
This is but a hurried scrawl in the dusk,
and only a faint transcript of what glows in my heart toward thee,
but accept it with dear love from thy sincere and affectionate friend,

L+++.+++ A. Barclay.

To J. S.

Reigate, 13th of 12th Month, 1844.

My Dear Friend,

I must put in a little note into M. A. B.`'s, to assure thee that I do not forget thee,
and that I felt thy letter in 10th Month acceptable,
and I am rejoiced that thou feelest so comfortable in thy new allotment and trade,
and I am greatly hoping that it may be a time of growing with thee,
that is of strengthening in the root, in the being with these dear friends,
whom we feel so united to, beholding their good example and feeling the strengthening,
seasoning influence of their spirit!
But, my dear Friend, in looking back at the past pages of my experience,
how often has it been the case with me,
that when I have been apparently the most advantageously
situated for the spiritual help and growth,
then have I had to pass through the most close times of stripping and dreary drought;
and on the contrary, when under the most trying circumstances outwardly,
then have I been favoured with seasons of the greatest refreshing inwardly,
and enlargement in the Divine love!

So exceeding wise and tender is our heavenly Father
in all His dealings with and towards us,
feeding us with the food most convenient for us,
although perhaps at the time not the most palatable or desired by us;
for He knoweth our frame, He remembereth that we are but dust!
So that I thought, dear J.,
I would tell thee how it was with me in case it might
be an acceptable way-mark unto thee,
if so proved,
showing that thou art not out of the way to the kingdom in experiencing such provings,
but in the footsteps of the flock, if I may dare to number my poor self with them!
For I know that the enemy of our soul`'s peace often tries to cast down and to perplex,
and discomfort under the idea that we are all wrong and know not what good is!
But it is the Lord that can bring quietness over the mind in an unexpected moment,
and bring into resignation to all His blessed dealings, as it were,
saying to the boisterous elements, "`Peace, be still,`" and there was a great calm!

On looking over again thy letter, I find a little hint of thy being thus proved,
which I knew not when writing the above,
not having read thy letter again before writing it.
Oh, my dear friend, mayest thou follow on from day to day,
to know more and more of the Lord, of His precious ways and will,
and delight to wait upon Him in the way of His judgments,
as thou intimates thou desires to do, which truly are more valuable than much fine gold,
and sweeter to the resigned and devoted mind than honey is to the taste!
To follow on means with close attention and tender yielding to all His leadings,
the touches of His power within; this is the only way to know Him more and more,
the mightiness of His power, the greatness of His goodness, the excellency of His will,
yea, the purity and purifying of His word, the preciousness of His law,
the righteousness of His testimonies,
which is everlasting! and thou wilt be prepared to take them as an heritage forever,
for that they are the rejoicing of thy heart!
Thus will the goings forth of His power in and to thy soul
"`be prepared as the morning with increasing light and warmth,
and the returning incomes of His love will be as the latter and
the former rain in its season,`" bringing refreshing from His presence,
life and nourishment, and abundant fructification unto His praise!

Thy account of your meeting is very interesting; such a number of attenders not members,
but under different degrees of convincement.
My heart seems to salute them and wish them, in the love of the Gospel,
the heavenly speed towards the city that hath foundations!
There is the more need of care to walk wisely and watchfully
before them on the part of those who are members,
and which I have no doubt thou feelest.

We have been much enjoying John Pemberton`'s life, which came out last yearly meeting;
do read it, it is so sweet and instructive!

I remain thy well wishing and sincere friend,

L+++.+++ A. Barclay.

To +++_______+++.

Reigate, 10th of 2nd Month, 1845.

I highly approve and advise to all the keeping a correct system of accounts,
by which they may see what they spend in each branch, what should be retrenched,
and what may be properly devoted to the help of others.
I was taught it first by my dear sister-in-law, Elizabeth B.,
then followed the practice when living with my dear
brothers and sisters together in Russell Square,
and afterwards when keeping my dear brother Abram`'s
house at Forest Place (at his special desire),
and have continued it since being my own housekeeper.
At the same time,
I believe it right to leave behind me this testimony in my family account-book, viz.,
that whereas some may have thought, from my own dress and simple way of living,
that I have been stingy, penurious,
or narrow-minded--my principle has ever been that there should
be no lack in my house of what is necessary and suitable,
plenty, consistent with Christian simplicity;
but that there should be no waste or misuse of any of the good things committed to me,
either for my own use or the use of others--desiring to follow the apostle`'s advice,
"`Let your moderation be known unto all men,
(for) the Lord is at hand,`" and that I might be enabled in humility,
and without uncharitably judging others,
to bear a true and faithful testimony to that simplicity and self-denial which
the Gospel (the power of God) or Spirit of Christ ever hath and ever will lead
into and require--believing that there is a witness for God in every conscience
which will approve and bear testimony to this by whomsoever it is borne,
and that the same blessed Divine light shining within will also judge, reprove,
and condemn the contrary wherever it appears.

L+++.+++ A. Barclay.

To +++_______+++.

Reigate, 18th of 5th Month, 1845.

Dear +++_______+++,

I thought I could not go to London without penning thee a few lines,
to assure thee with my dear love that thou art not without
my thoughts and sympathy in this temporary widowhood,
believing that there may be times when it may feel a close
pinch thus to give up thy dear +++_______+++`'s tender company
and kind solicitude and sharing with thee in thy daily cares;
but I hope that He who has enabled thee to give up thus thy own inclinations
and desires for the sake of what you feel to be thy husband`'s duty,
will be near thee, from day to day to strengthen, counsel,
and preserve thee who stays behind, as well as with +++_______+++,
who thus endeavours to fulfill his duty,
leaving all to the care of the Shepherd of Israel meanwhile.
I hope thy dear mother will be preserved in tolerable health in his absence,
and that thou and she may both be favoured with a sense of those
precious refreshings which come from the Lord`'s holy presence,
and if this be the case,
it will bear up amidst all privations or trials of faith and patience,
and give a peaceful quiet hope that maketh not ashamed.
So, my dear friend, be encouraged to seek after and feel after this, even with tears,
day by day, like craving earthly bread, and thou wilt not be sent empty away;
and this precious life inwardly will be more than meat,
and this precious union and communion with Him who is the
Head of His body the Church will be far better than raiment;
for if we have Him as our all in all,
what can we want more--heaven is begun then here on earth!
Oh, then, let us yield to His holy power that presses us gently onward and upward,
even in the secret of the heart, saying, "`This is the way,
walk thou in it,`" and He will not fail to make us His own dear ones,
and He will be our almighty all.

We are "`ready to depart on the morrow`" for our annual solemnity.
I think I never felt poorer and more stripped of
that capacity I seek after for such an occasion,
almost fearing from my poverty and unpreparedness that I shall bring harm to the meetings.
May He who is of tender mercy in pity look down upon
my weakness and strengthen me out of Zion,
and enable me to bear that portion of suffering or
of silent labour that may be assigned me,
that so I may be favoured to return with a little penny.
If thou hears of +++_______+++ do let us know.

Farewell, dear with our united dear love.
From thy affectionate friend,

L+++.+++ A. Barclay.

To a Young Friend

Reigate, 5th of 8th Month, 1845.

My Dear +++_______+++,

How very rapidly do the months pass on!
We are come to another month,
and have nearly seen two-thirds of the year--so rapidly
are our opportunities passing of labouring for,
receiving and laying up a treasure which is soul-enriching and will be everlasting!
Oh, then, that we may in a spiritual sense follow the good old proverb,
"`Take care of the pence and the pounds will take care of
themselves;`" make the most of the moments allotted us,
of the little opportunities of receiving and getting heavenly good,
and be faithful in the day of small things,
that we may not have cause to repent of the retrospect and lament our irretrievable loss.

I am so pleased to find that thy dear parents had
not left Cornwall without a public meeting.
It really made me quite sad at heart to suppose that they would,
for my heart yearns over the dear people there,
and gladly would I be in their pockets at such a time; but, dear +++_______+++, we may,
though afar off,
yet breathe for the arising and prevailing of the
Divine life and power in the hearts of others;
and oh,
may we "`so run`" and conduct ourselves as that we
"`may obtain`" the same blessing in our own hearts,
and thus have a leavening influence on those around us.
I want to know when they are likely to get home.
I know thou hast been following them in mind as well as I,
and I trust the time has (though perhaps seeming long) been
made profitable to thee by a proper exercise of mind and
painstaking on thy part for thy own improvement every way,
and that thus thy meeting them will be without an alloy from consciousness of neglect,
and that thou wilt share in their sheaves of peace.

Farewell, dear +++_______+++. Cleave to that which is good, and then thou wilt be made good,
and filled with good, and enjoy good forever.
With dear love, I remain thy affectionate friend,

L+++.+++ A. Barclay.

To +++_______+++.

14th of 8th Month, 1845.

My Dear Friend,

The idea of meeting thee once again looks very sweet,
and I long we may be mutually strengthened together in every sense of the word.
The being at +++_______+++ will recall many past interesting
and affecting events to my recollection,
and there it was that I first saw thee sitting opposite to me in meeting,
and I felt knit in spirit unto thee.
Oh, may the coming time, if permitted to be realised,
be one of recurring as it were to Bethel,
and of renewing our covenants with Him who hath hitherto helped us in our lowest estates,
and wonderfully and tenderly and very graciously dealt with us all our lives long--to
whom may the remaining few years of our lives be unreservedly and submissively dedicated,
with all that we have and are, for He is worthy,
worthy of all the pure service and the humble praise of our hearts forever,
saith my soul!

L+++.+++ A. Barclay.

To +++_______+++.

2nd of 9th Month, 1845.

My Dear Friend,

Thy kind letter was forwarded to me at Swanage,
and did not fail to interest me much as well as introduce
us into a degree of affectionate solicitude on your account,
desiring that you may not be spared from plentiful baptism,
that so you may know a death unto all that is of the creature in every respect,
and be enabled to enter deeply into feeling with the precious seed
which is very low and oppressed in most hearts you will visit,
and thus be permitted to minister to the due arising thereof;
so shall your feet be shod with the preparation of the Gospel of peace,
which implies that living power that leads and brings to true peace,
not to the wrong nature that should be crucified, but to that which only should live,
being tender and willing to be operated upon.

Ah, my beloved friend,
there is much of a spurious and light-weighted sort of ministry amongst us,
which I tenderly desire you may be preserved from, which is more in sound than substance,
in wisdom of words and activity of the creaturely part than
in demonstration of the Spirit and power of truth;
and such light-weighted ones are what I call lightly running to and fro,
scouring the country,
and apparently doing great things in visiting families and holding public meetings,
seemingly with ease and self-complacency and not much depth
of baptism and sore exercise or self-humiliation.
These are for pleasing all,
and I fear the self-abasing kingdom of the dear Redeemer is not
thereby truly exalted and spread either by example or precept.

Oh, it is the Lord only who can bring us into and preserve us
in the true virgin spirit pure and chaste unto Him,
and may He do so is my earnest desire for myself and all that are dear unto me.
There are many running to and fro amongst us that I greatly doubt of,
and I believe the time is coming and come when the
true servants will be put into prison as it were,
and my soul says amen to it,
till it shall please Him to open the right door of deliverance and enlargement.

And now, dear +++_______+++, as it regards myself,
although I have frequently had pointings for years to various services or parts,
and those where you are going amongst them, yet all seems to be gone away at present,
and I dare not move from old openings.
We are pleased with this simple, natural, and humble place;
the only difficulty being the distance from Poole meeting.
We sat down together twice.

Farewell, dear +++_______+++, with love.
I shall be pleased to hear further when thou art inclined to write.
From thy affectionate and sincere friend,

L+++.+++ A. Barclay.

To +++_______+++.

Swanage, Dorsetshire, 3rd of 9th Month, 1845.

My Dear Friend,

I can quite believe it to be a critical and important time with thee,
and that thou wouldst greatly feel the leaving so sweet a home as Kimberley,
where thou hast been as in a quiet nook for awhile
to gather a little fresh strength with genial spirits.
And I can also quite believe that under such circumstances of enjoyment,
the wise Master builder may have seen it best to prove thee
with seasons of desertion and of permitted buffeting.
Ah, He knows best how to cut and to square and to polish the stones of His heavenly building,
preparing them in His tender mercy and condescending
goodness for what part He requires them to occupy.
And the doubts and fears of the causes of our trials,
and whether we are mistaken or whether forsaken,
are among the provings of our faith and patience.
If we could see all the ins and outs as it were of the heavenly leadings,
there would be no walking by faith,
no exercise of the childlike confidence and humble patience.
Oh, the overcoming might that is the result of cleaving to the inward and lowly word of life,
which is called the Word of Faith, because it is not only the object,
but gives or quickens the true faith--the Word of Patience, giving true patience,
His patience, the Lamb`'s patience, which all the saints are to keep,
and then they shall be kept in the hour of temptation--the Word of Wisdom,
giving true wisdom, and causing it to dwell richly in us, etc.;
and as we cleave thereunto in all tribulations,
they will be so sanctified as to work patience and experience and hope; and then,
O my beloved younger brother, a little grain of this blessed true-born,
life-springing hope will come in in the needful moment to succour our fainting faith,
even in seasons of greatest barrenness causing as it were a green and fruitful
tree to spring up even out of the wilderness and from the dry looking stock;
for it is said,
"`And all the trees of the forest shall know that I the
Lord do bring down the high tree and exalt the low tree,
do dry up the green tree and cause the dry tree to flourish.`"

Oh, the wonderful workings of the Lord`'s mighty and
tendering power in and for His poor weak children,
the workmanship of His hand, as they yield up thereunto to be led about,
and instructed and humbled and proved as He sees best in full reliance--the
cup which my Father hands shall I not drink it!
And thus being more and more emptied and cleansed of the dregs of nature,
they become prepared to be filled with the riches of His grace and treasure of His kingdom,
which is righteousness and peace and joy in the Holy Ghost!
And being filled they cannot but run over to His praise and the
refreshment of others and spreading of His kingdom and glory.
Therefore, dear +++_______+++, cleave to the lowly seed,
or word of life and power in the secret of thy heart.
Here lieth the power that the enemy cannot overcome, but it still overcometh Him.
Here lieth the light which the enemy cannot approach,
whatever roaring he may make about thee.
Here lieth the hope that shall be an anchor to thy soul in all storms and buffetings,
and which entereth into that within the veil, and thy soul shall be safe,
and know all things to work together for good,
to thy exceeding humbling and exceeding rejoicing!
The fear of losing all is a sign that all is not lost,
and stimulates so to run as to obtain all we desire.

Farewell.
With dear love from thy very sincere friend,

L+++.+++ A. Barclay.

To J. B.

Reigate, 19th of 9th Month, 1845.

My Dear Friend,

I have indeed had a great loss in the removal of my dear brother,
so that I only am left now of the three who gave up in early life
to leave the gaieties of the world and walk in the narrow path.
I am often ready to long to depart and be with Him whom my soul doth love,
through His first loving me, to be taken also from the evil to come.
But I expect I am not ready yet for such an awful change,
more purifying and refining and crucifying is needed, and oh,
that I may be able to bear what is yet lacking, and to wait the appointed time,
and to yield wholly to that good hand that can perfect
that which concerneth me also in His good time,
and bring me to the good end that crowns all, the end that is peace.
I had not heard of thy sister`'s removal till thy letter.
Such losses are to shake us from earth and draw us nearer to heaven,
upward and still upward.
We may truly say,
"`Blessed are they who die in the Lord;`" they are taken from trial and provings
to where the wicked cease from troubling and the weary are at rest.

Oh, the low and desolate places amongst us! the ways of Zion do truly mourn,
for few come to her solemn feasts.
Ah, they know not the truth, though they make profession thereof; they--that is,
the multitude among us, are like Pilate asking, "`What is truth?`"
but don`'t care to know it.
No, they are like Gallio of old, "`Care for none of these things`"--that is,
the things or teachings of the Spirit of truth.
Ah, what will such do at the last great day of account,
for God requireth truth in the inward parts, even the rule of His dear and precious Son,
and no other covering but His Spirit will He accept or allow to enter the wedding-chamber!
Ah, the various plausible coverings which now so much take and are fashionable,
owing to the enemy`'s deceit and guile to catch the unwary, these will be stripped off,
and the nakedness or bareness of profession will really appear,
in a day that is hastening, wherein the foundations of all will be proved.

Oh, then, that we, my dear friend,
who are favoured to see these things and to lament them,
may be concerned to gather more and more inward to the Lord`'s name or power,
which is a strong tower in the day of trouble--to abide in subjection
to His power is to abide in the safe tent of His people in all ages,
where none can make afraid--here His Spirit is the precious covering,
and His life is the soul-satisfying food,
and His presence is the crown of glory and diadem of beauty,
and He will enable to overcome all, and give to reign with Him forever and ever,
notwithstanding the many tribulations such must pass through.

Farewell, dear friend.
May we crave one another`'s help and preservation to the end, and do our best,
and leave the rest.
With dear love, I remain thy affectionate friend,

L+++.+++ A. Barclay.

To +++_______+++.

22nd of 12th Month, 1845.

My Dear Friend,

I feel best satisfied to take up my pen and say that I have for
sometime past felt a fear lest thou and +++_______+++ should in any wise
be wound about by the kindness of certain Friends,
neighbours of yours,
and thus be any how warped from the true uprightness for the cause of truth.
I know it is very hard when Friends are very kind
and neighbourly with us in an outward sense,
and especially if they have dealings with us in the way of trade,
to stand firm against what we believe to be of evil root or tendency,
and to tell them the whole truth, and be faithful and sincere to them.
This goes very hard.
But, oh, my dear friends,
I want you to be preserved single-eyed to the Lord and His honour,
and the promotion of His cause of truth, and not only single-eyed, but simple-hearted,
going right forward in the way of truth--that is,
minding the discoveries and pointings of the Spirit of truth in your hearts,
however in the cross to self and nature, or apparently foolish to others.

Oh, then, mind the savour of life in you, mind what it leads and draws you from,
and what it leads and draws you to, for we all have a seed or principle of light, life,
and truth in our hearts, placed or sown there by God,
and which doth and ever will savour what is of God,
and what goes against Him in all that we say or think or do,
and also will savour what is of or against Him in others around us;
and let us mind what this draws us to or from, in what it manifests to us,
and that is the way to be preserved in the truth--that is, in Christ`'s Spirit,
firm and upright for Him, endeavouring to feel and to act for Him like faithful servants,
not with eye-service--that is, with merely a show,
or doing only those things which are manifest to others,
or without which we may be blamed by others, as men-pleasers,
but with good will and our whole hearts doing service as unto the Lord and not to men,
out of true love to His cause, that we may have His heavenly peace and favour.

I do not write from any outward thing, but from inward feeling,
fearing lest a more frequent intercourse may familiarise
you to what hitherto has been trying to you,
and thus your eyes should become dimmed as to the truth, and your hands weakened,
which indeed I should be sorry for,
so thought I must pen a few lines to stir up the pure mind in you;
for I greatly long that you may go right forward,
and come up nobly to the help of the Lord against the mighty, yea,
that you may increase and abound in a faithful labour
for the truth in whatever way your duty may be revealed,
that thus your hands may be strengthened and your path may be (like the just
man`'s) as the shining light that shines more and more unto the perfect day.
For surely our poor monthly meeting wants all the help of every member that can be!
And, my dear friends,
I believe one great means of gathering strength will be by waiting
on the Lord daily for His renewings of life and strength,
and as you are now so retired from business there is or may be more opportunity of such
times of uplifting of the heart and downcasting of the spirit before Him,
so do be encouraged to be faithful in this respect, for I think you will,
if you listen attentively, hear the call to it in secret.
Do not think me an intermeddler, for I love you both dearly,
and long for you to be a father and mother in Israel,
and how this would bring joy to my heart, if spared to witness it!

I remain thy truly affectionate and sincere friend,

L+++.+++ A. Barclay.

To +++_______+++

Reigate, 30th of 12th Month, 1845.

My Dear Friend,

I have thought of and felt much for thee for some weeks past,
and was hoping to have had some of thy company when I went to +++_______+++,
but found to my disappointment that thou hadst left that very morning for +++_______+++,
and was sorry for the cause, but hope, if so permitted,
that thy dear mother is favoured to recover,
though of course she will greatly feel at her age the effects of such an illness.
We have seen very little of you, dear +++_______+++, since you left Reigate.
You have had many claims and engagements to hinder your coming over,
as you once gave us reason to expect.

The hearing of thy dear +++_______+++`'s sufferings even at +++_______+++,
convince me that it is not any particular spot that is favourable,
but that a continual change is the best.
This is very trying, and I who am such a lover of settlement and of home,
can sympathise tenderly with you in it.
I have been thinking that to live as it were in a tent, is better for such as you,
instead of being cumbered with a house and household.
This is indeed trying to nature;
yet it is emblematical of our pilgrim life here to have no continuing city,
and may be beneficial in the more loosening us from
this beautiful earth and lovely things thereof,
and in the more earnestly drawing us to heavenly things,
that the affections may be fixed thereon,
and the heavenly mold more entirely fallen in with and yielded unto!
Oh, what a blessed state is this! let us daily covet after it, dear +++_______+++,
for when we are thus moulded, according to the Divine will, and fitted for heaven,
we shall be translated there, to the good heavenly resting place that changes not,
and the everlasting city where none of the inhabitants shall ever say they are sick,
knowing their sins to be forgiven and washed away by the blood of the dear Lamb!
How many are the warnings that we have had lately,
and the instances of the uncertainty of all things here!

I have recently lost a dear niece at Torquay, sister of dear Robert,
who died a few years ago.
She was a sweet creature, seemed to have no will of her own, and I trust is,
as a tender plant,
transplanted from the storms and clouds of time to the everlasting sunshine of heaven!
Her death had such an effect upon +++_______+++! She also sunk in less than a week;
thus a double trial in my brother`'s family!
I passed two days at +++_______+++ with dear +++_______+++,
and two at Croydon with dear John and Hannah Marsh in my way home.
The former it was truly sweet to feel,
had benefited and deepened during her late illness, and it was a strengthening time,
wherein we were favoured as it were to go up to the
Lord`'s house together in our seasons of retirement!
Ah! this is what I long for in our times of social meeting with those whom we love;
not to be all taken up with chitchat and many spending words,
but to feel after His precious presence and power that is
beyond words and is the true life of our souls.

How needful it is for parents to guard against the affectionate part being too uppermost!
for the affections are to be mortified or crucified as well as the lusts,
lest they should be blinded from seeing the tendencies
and snares that beset their dear children,^
footnote:[See Colossians.]
and they should, whilst desiring to cherish the good,
be in any wise cherishing imperceptibly the ill weed of self which chokes the good!

Whilst there,
I heard of the proposition that had been made to thee and
+++_______+++ to fill the station of overseer in that meeting,
and was much pleased to hear that you had declined accepting it!
Ah, my dear friend, this is an important station,
and in these times of weakness and degeneracy amongst us,
it is important it should be well filled,
by such as are "`grown in the truth`" (to use an ancient expression) such
as through the Lord`'s humbling baptism unto obedience to His Spirit,
are brought into a degree of oneness and of feeling with Him,
and therefore feel and "`know what Israel ought to do,`" and are faithfully
concerned for the lifting up and upholding of this pure standard,
even the standard of the Spirit of truth, both in themselves and in others.
These will be indeed "`men and women`" of truth, and of and for truth also,
fearing God and hating covetousness, neither fearing man or his frowns,
not coveting his favour or honour, but solely seeking the fear of God,
the honour that comes from Him, and the honour and promotion of His blessed cause, name,
and kingdom! these will keep close to the Spirit of Christ the truth,
to the humbling and regulating influences thereof, wherein alone is their qualification,
which will make them tender, will break them to pieces in themselves,
will make and keep them clean-handed, simple-hearted, and single-eyed for their Master,
and thus prepare them to work for Him in His meek and lowly Spirit,
to labour in His vineyard; and truly their labour shall not be in vain in Him,
but tend to His glory, the help of others, and the peace of their own minds!

Now, my dear friend, although I believe you are mercifully called unto,
and are preparing for this good work in proportion as obedience keeps pace with knowledge,
yet I cannot say, that I think you are quite ready for such a burden yet,
and if it were imposed upon you in too tender a state,
it might be to your cramping or growing crooked, in a spiritual sense,
and be to your lasting hurt, and what hurts individuals hurts meetings!
Now don`'t think I am setting up the standard of truth too high.
Can it be higher than it really is?
and that things must be conformed to the weak state of our society!
Is this the way to make things better?
is it not to keep things weak and even make them worse, for like begets its like!
And oh, I trust I shall not discourage you,
for I desire your encouragement in obeying the Spirit of truth,
which will deepen you and qualify you, and make you truly noble and honourable.
So I do indeed desire and covet for you the best things--first deepening in the root,
then a growing up in the vine,
and then unfailingly will follow fruitfulness and stability!
Therefore, dear +++_______+++, don`'t be discouraged by the greatness of the work,
and so draw back from the heavenly Workman or Qualifier,
but suffer Him to work what He will in and with thee when He pleaseth!
A great mountain of opposition or difficulty is to be brought down by little and little,
even to become as a plain, and the headstone thereof brought forth! but not by thy might,
or power, or wisdom, but by the Lord`'s power or Spirit,
and then the shoutings will be of Grace, grace unto it! for all is of God`'s grace,
in and by Christ Jesus,
which is bestowed upon us all according to our different measures and needs; and oh,
that it may not be in vain,
but be cooperated or occupied with in living faith and
obedience to the salvation and redemption of the soul!

Now, I do want to encourage thee not to be looking out at the reasonings of others,
nor leaning to thy own understanding or the drawings
of the affectionate part which may plead many excuses,
but cleave closely to the Lord, mind His inspeaking voice,
the shinings and discoveries of His light in thy heart,
the touches and savour of His life there;
come out of what the savour of life would draw thee from,
and take up and follow what the savour of life draws thee to.
This is the only path of safety and way of growth and peace;
and remember no man on earth can give thee true peace and a growth in the truth,
neither can any one take it away when mercifully permitted,
except by drawing away from the Spirit of truth!
Therefore,
keep to truth and truth will keep thee and make thee prosperous and victorious over all;
and may the God of truth bless thee and make thee a blessing,
is the earnest desire of thy very sincere and affectionate friend,

L+++.+++ A. Barclay.

P+++.+++ S.--In looking over the above on overseers, it is suggested,
that it almost seems uncalled for, nevertheless, I let it go,
as it arose in my mind in writing.
It may stir up the pure mind in you or strengthen you in that which is good,
though you do know these things and feel them to be so!
Farewell, with dear love.

To B. B.

+++_______+++, 1846.

We must not fear,
but put forth what is given us of our Master to testify
for Him in the savour and leadings of life and light,
and leave all consequences, cast our lot, as it were, into the lap,
and the Lord will prosper it, as it pleaseth Him, if done in faith and faithfulness,
in His fear and deep humility.
Who can harm us, if we be thus followers of that which is good, even His good Spirit?
We must show on whose side we are.
I believe these storms and siftings are designed for our purification,
painful as they are to witness.
Oh, that we who feel these things may be preserved in the hollow of the Divine hand,
in a quiet habitation, even abiding in humble fear and subjection to the Divine power,
leaning not to our own understanding, nor trusting to our might, lest we fall.

L+++.+++ A. Barclay.

To a Young Friend.

Reigate, 1846 or 1847.

I feel as if I could rejoice in the departure of all who go rightly.
It is because we are not rightly prepared that tender
mercy yet spares us and calls us not hence.
Therefore, oh, to avail of the precious moments as they fly,
that we may be growing more and more ready.
For surely this is not, and ought not to be, our rest; neither can the things of time,
however good-looking, really feed or satisfy an immortal soul.
But Christ is the true Sabbath and rest, the life and food of the soul,
and He is all-sufficient, unchangeable, and eternal.
Oh, then, that we may seek to be of Paul`'s noble spirit,
who counted all things but as loss and as dross if
so be he might win Christ and be found in Him,
that he might know Him and the power of His resurrection and the fellowship of His sufferings,
being made conformable to His death.
Oh, then,
let us seek to be in Christ and to really win or
have Christ by being in subjection to His Spirit,
clothed by His Spirit,
in unison with His Spirit--this will make us conformable
to His death by crucifying the evil nature in us;
it will quicken us in the resurrection of His life,
so that we shall become new creatures, and shall really know Him,
not by hearsay or education, but by true feeling of Him in us--yea,
this will then bring us into the precious fellowship of His suffering--and
we know that unless we suffer with Him we shall not reign with Him,
and unless we die with Him we shall not live with Him,
and unless He wash us with the washing of regeneration we shall have no part in Him.

I was much pleased to see S.`'s sobriety and quietude of mind and guarded behaviour.
I longed much that thou might be induced to seek
after best help to follow her example in this respect;
for surely it is a great ornament to a woman to be of a meek and quiet spirit--and
it is of great help to the watchfulness of the mind and the guardedness or propriety
of the behaviour when we are preserved in a meek and quiet spirit;
we can then much more easily watch the avenues to evil or the risings of evil,
as well as hear the still small voice of the good Shepherd within us;
and it is here in quietness that our strength is
renewed to follow the good and avoid the evil.
The true love of the good is more shown by a meek appreciation of it and an inward
subjection to it in ourselves than in the warmth of affection for it outwardly:
this is like the rattling thunder--that like the quickening, melting lightning.

My love to dear S. May she keep close to what she knows and feels to be right and peaceful,
and may you go hand in hand together up the good but narrow
path that leads to heavenly blessings without number.
I have sent the sweet memoir of William Boen, the poor slave, to be printed,
I hope to send you some soon.

Farewell, my dear girl.
Mayest thou grow in grace and in every good thing,
by following only those things that will make for thy real and true peace of mind.
With dear love, I am thy very affectionate and heartfelt friend.

L+++.+++ A. Barclay.
