== Chapter XIII

[.letter-heading]
To +++_______+++

[.signed-section-context-open]
Reigate, 17th of 3rd Month, 1846.

Oh! saith my soul, that all the shakings and plungings that have been,
and that yet may be my allotted portion,
may settle me more firm upon the only sure and immutable Foundation,
and drive me yet more closely to that precious Friend that sticketh closer than a brother,
and who will ever be all-sufficient for his faithful, humble followers,
though He see meet at times to prove their faith deeply,
and may seem to require hard things!
Let His holy will be done in me and by me wherever
my lot may be cast and however I may be led,
required, or tried, is the earnest breathing of my soul.

[.signed-section-signature]
L+++.+++ A. Barclay.

[.letter-heading]
To +++_______+++

[.signed-section-context-open]
Reigate, 20th of 3rd Month, 1846.

Ah, dear friend, the present is a time of multiplying modern productions,
but few of them come near to the life and substance, the savour of the blessed truth,
which characterised or seasoned the writings of our ancient faithful worthies,
and whereby they _so clearly_ testified for and gathered unto, yea,
and exalted and glorified the blessed truth! but our very tracts are by
degrees planing and smoothing down the pure principles of the truth,
so as to insinuate gradually a lower standard or testimony,
and which it is to be feared will at last land us in a lower dispensation,
even among the many "`horns`" of formal profession which have been
pushing and thrusting at one another--and yet under a show of much
love and condescension!--ever since the apostasy came in;
and,
alas! our modern Quakers are finding fault with our
ancient worthies who stood the fire of hot persecution,
yea, who overcame all by the word of their testimony and the blood of the Lamb,
and are pluming themselves upon having more Gospel light in these days,
whereas not being so entirely and unflinchingly devoted and subjected
to the little pointings and restrainings of the blessed light of
Christ in the secret of the heart as _those_ were,
they have by no means attained to _their_ standard and measure or growth of experience,
and consequently have no business to, neither can, properly judge concerning them;
but there is reason to fear, when tried in the unerring balance of the sanctuary,
even the pure light or Spirit of Christ,
will be found sorrowfully wanting in that life and
power in which the kingdom of God stands,
and not in word or mere outward profession.

[.signed-section-signature]
L+++.+++ A. Barclay.

[.letter-heading]
To J. B.

[.signed-section-context-open]
Reigate, 10th of 4th Month, 1846.

&hellip;But, dear friend,
do thou stand fast and firm in the power of truth and for the precious cause thereof,
yield to the power first, and let it work in thee and then stand fast in it,
in the sight and feeling it gives thee, nothing doubting and no one fearing;
love the truth more than all, and keep to the Spirit of it,
and thou shalt be kept and strengthened over and unto and through all to the end.
Remember Caleb which signifies a heart,
and Joshua a saviour overcame all and inherited the good land!

Dearly farewell.
With dear love, thy truly affectionate friend,

[.signed-section-signature]
L+++.+++ A. Barclay.

[.letter-heading]
To Ann Conning

[.signed-section-context-open]
Reigate, 23rd of 4th Month, 1846.

[.salutation]
My Dear Friend,

Hearing from John F. Marsh that they had informed thee of the decease of dear Ann Jones,
I feel inclined to put pen to paper,
as it were to share with thee in thy mournings on behalf of the Church,
and also I trust in thy rejoicings on her behalf
that she is liberated from the shackles of mortality,
and translated to the realms of unmixed and unchangeable bliss.
Ah, how can our spirits as it were unite with her spirit in the angelic shout
of praise "`to Him who has loved us and washed us,`" etc.! I felt in duty
bound to go and show my near and dear love and unity with and for her
by attending the interment--dear John F. Marsh as my escort.
We went on second day and returned yesterday.
It was indeed a long journey for me, 220 miles each day,
and the interment a day of much exercise and deep feeling between; but, through mercy,
I have been helped through to my wonder and grateful praise!

I lodged at John Harrison`'s, and went with them to Stockport;
the interment was before meeting;
there was a large gathering of Friends from different parts,
and indeed the crowd was so great that I could not
see the coffin till I looked in upon it;
the people also all out of their houses and standing in the streets.
I was told four Friends spoke at the grave side.
In the meeting dear John F. Marsh had a little time, and I think L. Neild;
also a few words from H. Marriage, the sister of dear Ann Jones.
I should have named J. Milner spoke the first in
the meeting in a very sweet and lively way,
which rejoiced my heart,
especially as I found he was expecting to start next morning to visit Warwick, Leicester,
and Rutland shires, also Berk and Oxford shires, in his way to the yearly meeting,
the first certificate he has had.
But oh! how greatly will he miss this dear mother in Israel, also dear John Harrison,
for _they_ appear to have shared so _very largely_ in her company and counsel!

I saw some sweet expressions of hers during the last ten days,
penned from memory by J. Milner,
uttered in various opportunities with Friends who came to see her,
all indicative of deep humility,
and that she had nothing to trust in but the free love and mercy of God in Christ Jesus,
and that she was an unprofitable servant,
and had come short of what she should have been--at the same time avowing her
unshaken belief and holding of our ancient and Gospel principles and testimonies,
and that if she had ever done anything that was right
it was in endeavouring faithfully to uphold them,
and to testify against all that would mar them--also
looking forward to a brighter day amongst us.
The last words (only twenty minutes before the close) were,
"`Bring the chalcedony and the precious stones.`"

Do not give up the yearly meeting.
Why dost thou shrink from it?
No matter how weak and crushed we may appear, our suffering countenances may help some,
and the exercise of our spirits may do good, and if we suffer aright there is joy in it.

[.signed-section-closing]
Farewell, with dear love.

[.signed-section-signature]
L+++.+++ A. Barclay.

[.letter-heading]
To +++_______+++

[.signed-section-context-open]
Reigate, 1st of 5th Month, 1846.

[.salutation]
My Dear Friend,

I was much pleased that the good overcame what was _doubtful_ in thee on fourth day,
and that thou wast thereby made willing to accept the call of the Church
to come up to her help in a simple yielding to the Lord`'s tendering power,
whereby He will more and more quicken in thee a true sense and sensibility
of what is for Him and what against Him and His precious cause of truth;
yea, and with a degree, however small, of true sight and sense,
will not fail to come also in His _wonderful_ goodness and compassion,
a degree of heavenly wisdom and strength to do what
thy hands find to do for Him and His cause,
so that thou wilt be enabled to rise up, in the true zeal and in humble faithfulness,
to act for Him, not daring to keep silence for Jerusalem`'s sake, trusting thy all,
the keeping of thy spirit too to Him,
who knows what thou hast need of and is able to do exceeding
abundantly above all that we can ask or think,
and to bless with the hundredfold His dependent little ones who have none in
heaven or earth that they desire in comparison of Him and His peace-giving favour!
Then mayest thou cleave to the Lord`'s tendering, humbling power,
and seek after it day by day in thy private retirements--let the
lifting up of thy soul and the desire of thy heart be continually,
even at any spare moments, unto Him, to the remembrance of His name,
and the feeling after His seasoning, strengthening influences;
thus wilt thou increasingly be made _strong for Him,_
though weak and humble in thyself! and verily His
own works will praise Him _in thee_ and _through_ thee.
So I hope thou wilt not faint in thy heart at what is come upon thee.
Look not _out_ in any wise so as to be discouraged by any of the enemy`'s lying vanities,
his vain reasonings, lest thou should be thereby forsaking and hindering thy own mercies;
but look _up_ unto the Lord over all, and trust in Him forever,
for in Him is everlasting strength and wisdom,
and He will ever preserve the simple and the faithful!

Farewell very affectionately and in tender sympathy.
I remain, with dear love to thy wife, thy friend very sincerely,

[.signed-section-signature]
L+++.+++ A. Barclay.

[.letter-heading]
To +++_______+++

[.signed-section-context-open]
Forest Place, 23rd of 6th Month, 1846.

[.offset]
+++[+++Alluding to the prospect of attending the general meeting at Aberdeen--]

&hellip;Nature,
I need hardly say, shrinks often, but yet I seem carried above all,
and am kept in quiet as to the future in a way that has been marvellous to me,
so that my soul has often been as it were melted within me into resignation and praise.

[.signed-section-signature]
L+++.+++ A. Barclay.

[.letter-heading]
To Priscilla R.

[.signed-section-context-open]
Forest Place, 24th of 6th Month, 1846.

[.salutation]
My Dear Friend,

I fear you will have thought me very negligently silent towards you, dear R. especially,
after her last kind sympathetic letter before yearly meeting.
Yet thou, dear Priscilla, knowing what is and has been on my mind,
will be prepared to make all allowances.
I have now in the enclosed letter ventured to inform dear R. and M.
of my prospect of going to _sit_ in the general meeting at Aberdeen,
and the other two meetings thereabouts.
Thus am I now prepared as it were to cast my bread as upon the waters,
trusting that all will be wisely and goodly ordered for
me and that I shall as heretofore be abundantly cared for.
I do hope and trust that my dear +++_______+++ and myself will
be guided in all these things relative to our future settlement,
if we endeavour to follow the pointings in our own minds in simplicity,
and not to lean to our own understandings or the reasonings of others.

Speaking so, reminds me of yearly meeting.
I do and have felt great regret in having leaned to other people`'s fears or discouragements,
and not borne my simple testimony against the sending an
epistle to New England--not that any good would have resulted,
but I should have felt clear on the subject.
Ah, we should not be looking at consequences,
whether at trying rejoinders or at the no apparent good likely to result,
but simply to do what seems required, leaving all else.
This is a blank to me, in looking back at yearly meeting,
believing that had I yielded in this instance it would have opened my way for a further
testimony in a doctrinal way which pressed for several days upon my mind.
May I learn experience from the suffering, slow as I am to do so.
What a favour it was, in the midst of so much suffering,
to be preserved in such calm resignation,
whilst the proud vaunting waves were rolling over
our heads with overwhelming impetuosity! nay,
it seemed as if the precious promise was graciously fulfilled,
that as the sufferings of Christ abound in us, so should also His consolations,
and there seemed joy in suffering, as one of old said.
Surely these things ought not so to be with us,
and they will only tend or chiefly tend to open the eyes of even the dear youth,
for they know full well that by "`their fruits ye shall know them.`"
On the other hand, in my _silent watchings_ at my lodgings,
I saw the necessity on the part of the suffering
ones to guard against their own spirits getting up,
and so anything _savouring_ of a party spirit or a feeling
of bitterness towards those who are the cause of their suffering,
creeping in; perhaps it was more the _danger_ of the thing striking one than the _reality._
Oh, that I may be helped to let the day`'s work keep pace with the day;
this is all I long for, and to be preserved to the end.

We had a trying monthly meeting, but I was enabled to leave my burden, and oh,
that I may go clear of the blood of all.
In looking forward, nature shrinks many, many times, and many fears rise up, but,
through mercy, I have been marvellously preserved in quiet, and carried above all,
to rest my all on Him whom I desire sincerely to serve.
And I hope dear will be thus helped.
Ah! "`he that forsaketh not father and mother,`" etc., "`for my sake,
is not worthy of me.`"

Farewell very affectionately.
How sweet was our intercourse and union of spirit!
Oh, that it may be increased rather than die away.
I remain, with dear love, thy truly affectionate friend,

[.signed-section-signature]
L+++.+++ A. Barclay.

[.letter-heading]
To Hannah Marsh

[.signed-section-context-open]
Aberdeen, 6th of 8th Month, 1846.

[.salutation]
My Dear Friend,

I may now inform thee, I trust under some grateful feelings,
that we were favoured to arrive here in safety last second day week,
about half-past three o`'clock in the afternoon,
after a very quick passage of only forty hours--the captain
said he had only once had a quicker passage in his life!
We had a fine calm day all First day, so that we passed it mostly on deck,
except at our meals,
and we found a snug corner at the end of it where we had our little quiet meeting together,
without any interruption, in the forenoon to our comfort.
On second day, however, the sea was covered with white breakers,
and there was a heaving swell that made us feel very poorly,
and we were obliged to go down below and lie on the sofa a few hours,
till the joyful news of "`land in sight!`" hailed us,
brightening the countenances of our still more sickly comrades
who had never once left their berths all the voyage,
and rousing us up on deck again to see the approach to this port.
We had lost land for twenty-four hours which to me occasioned not a few solemn reflections.

We had 120 passengers, and 59 crew and servants,
and we were distressed to see the latter so hard worked all the First day,
with serving our different meals,
amongst which was a grand dinner with all sorts of luxuries and varieties,
even to pine apples and other fruit for dessert!
We spoke to the captain about it and also the chess playing; he agreed to all we said,
but said he was only servant to the company and could not do as he would!
He seemed an agreeable man,
and acknowledged his belief that all mankind are at one time or other
visited with a sense of what is right or wrong in the Divine sight;
and +++_______+++ rejoined to him the responsibility and awfulness of resisting such convictions!
We had the Bishop of Aberdeen and wife with us;
he seemed a jolly fat man that troubled not himself with the care of others,
though we thought he should have overseen the flock
better than to have allowed chess playing!
G+++.+++ B. met us here and took us to his hospitable home.

I had intended and _arranged_ to go out to Kinmuck meeting on fourth day,
to stop over their preparative meeting next First day,
but I was taken so ill on third day that I was obliged to give it up;
and perhaps it was all for the best,
for I was helped and enabled not only to totter along to this meeting yesterday,
but also to stand some little time to the relief of my mind!
so it is all good to be restrained as well as constrained.
I hope to be able to go to Kinmuck on First day if I am well enough.

It was quite a cordial to my mind, on coming to our little lodging last week,
in a very low drooping state of mind, to find a kind encouraging letter from dear D. D.,
and, amongst other things,
saying how he rejoiced to _hope_ that I should go to K. on a First day,
for that they had not had a stranger on that day for more than twenty years!
It was like balm to me, and my drooping was turned into melted praise!
I was mercifully helped to have a very close and relieving time here on First day last,
and am hoping to have got through my business before the _great folks_ come,
though I think too I am resigned to be humbled anyhow among them!
The Lord, the good Master, help His poor weak worm,
and give me to glorify His great name as He sees best!
And now, dear Hannah, I may say that the sweet and peaceful, the quiet and confiding,
covering of my mind ever since entering this lodging,
in looking at a still more close and bitter sacrifice, has been very remarkable to me,
and what I cannot describe--"`it is the Lord`'s doing and marvellous in my eyes`" truly!

[.signed-section-signature]
L+++.+++ A. Barclay.

[.letter-heading]
To M. R.

[.signed-section-context-open]
Reigate, 18th of 9th Month, 1846.

[.salutation]
My Dear Friends,

I want to hear from you, feeling love to flow very strongly towards you,
and that strengthening union which is not dependent on personal intercourse,
nor yet is broken by distant separation.
Ah, I know I have had your tender sympathy when far off,
and shall do still when the tent is removed there.
I cannot describe the solemnizing and tendering and calming
feelings I was favoured with when on the water,
both in going to and coming from Aberdeen,
and the language was consolingly revived each time within me, "`Fear not,
for I am with thee; be not dismayed, for I am thy God: I will strengthen thee, yea,
I will help thee,`" etc.; and the awful answer seemed begotten, "`Here am I, send me.`"
Nothing short of the Divine power could have enabled me to bear the deep exercises,
plungings, and conflicts that awaited me there,
and nothing less than Divine and unutterable goodness could have clothed me with
such peaceful quiet and humble confidence as was mercifully permitted at seasons.
And since leaving Aberdeen, although wave after wave has seemed at times to overwhelm,
yet has there also seemed a secret standard, lifted up by the Lord`'s Spirit,
which has stayed and supported.

[.signed-section-signature]
L+++.+++ A. Barclay.

[.letter-heading]
To +++_______+++

[.signed-section-context-open]
Reigate, 14th of 11th Month, 1846.

My _dear_ love to +++_______+++, and tell her I want her to love the truth _above all,_
even to love to feel it in her _inward parts,
that is_ where God requires it to be in us all, even that the Spirit of Christ,
who is the truth, should be uppermost there,
should be _loved_ and _honoured_ and _obeyed_ and _trusted in above all, then_
Christ becomes _truly_ our King, our Lord, and our Saviour, and _no otherwise,_
and we become really and truly His.
I have had three proofs of Patrick Livingstone, and it is _so very_ sweet and savoury,
I long to share it with you; but I _may_ be taken from it,
as my dear brothers were both from their good works of Thomas Shillitoe and Samuel Neale.
It is as the Lord wills, and His will is ever good.

[.signed-section-signature]
L+++.+++ A. Barclay.

[.letter-heading]
To Priscilla R.

[.signed-section-context-open]
Reigate, 30th of 11th Month, 1846.

[.salutation]
My Dear Priscilla,

Ah! how sweet it is when we feel the bond of affectionate union more and more strengthening!
When this is the case,
no matter even if we have the prospect of further separation to a vast distance,
_that_ remains that is stronger than death itself!
I say strengthening--I mean after an _inward_ manner,
from a deepening and strengthening in the best life,
not a mere addition of _outward warmth_ as it were.
And I think I may say it has seemed so to me in reading thy kind notes of late,
I have felt that which has knit my heart to thine;
and I do long that I may be more and more rooted and grounded in the one true love,
which I apprehend must be by Christ dwelling in the heart by the true faith,
through the quickening,
strengthening efficacy of the Divine Spirit--then shall
we not only be enabled to comprehend the love of Christ,
which passeth knowledge, and be filled with all the fulness of God,
but also shall love one another with a pure heart fervently.

Thy last kind note touched my heart, as did the one before,
especially thy allusion to Daniel.
Ah, that chapter is a peculiar favourite of mine;
and I think thou quoted it in allusion to myself in a way in which
it has often been secretly opened to me by the good Remembrancer!
How strikingly sweet and instructive and strengthening is almost every verse,
or one in connection with one another!
So, dear Priscilla, it was reviving to have it revived.
And now, in allusion to what thou so diffidently hints at in thy last,
I would have thee rest under the Divine power that can clear and make way for,
as well as melt into acquiescence with all,
and do not let in reasoning or doubting so as to nip any tender buddings,
but yield to the heavenly touch which gives faith and makes willing,
and then power will spring all-sufficient!

[.signed-section-signature]
L+++.+++ A. Barclay.

[.letter-heading]
To the Same

[.signed-section-context-open]
11th Month, 1846.

I wanted to tell thee that I have just seen a nice letter from T. B. Gould,
clerk to the sound yearly meeting in New England, a very valuable friend, who,
speaking of their yearly meeting last 6th month,
says how very strikingly dear John Wilbur was engaged
in the different meetings at that time;
he had never heard him more clear and lively and powerful--so much so,
that he could not help fearing that the close of his valuable life was drawing near,
it seemed so like a taking leave or evening offering.
I was struck with one passage in dear +++_______+++`'s letter.
I cannot repeat the words now;
but it seemed to me almost to convey that _only since_ our
blessed Saviour`'s outward sacrifice had He been a Saviour!
Now, this I _can`'t_ believe was dear +++_______+++`'s view--it is too modern a one for him.
But I have supposed either that it was an oversight of expression,
or else that he alluded to His first being given for a Saviour
when the promise was made to our first parents;
for we may imagine that as He was in the beginning with God, and was God,
so the language was applicable to Him then, "`Lo, I come to do thy will,`" etc.,
when the gracious promise of His bruising the serpent`'s head was made to Eve,
and we may say He was the Lamb slain from the foundation of the world,
both in allusion to His precious sacrifice on the cross and also His being
slain in His spiritual appearance in the hearts of the disobedient!

Our visit from dear +++_______+++ and +++_______+++ was very sweet; but oh,
it is not like where we see eye to eye in the things
most dear to us--the things of the precious truth.
Some think that text about seeing "`eye to eye when the
Lord shall bring again Zion`" means another state of being,
and so content themselves with a want of unity;
whereas I felt it to refer to the right state of citizenship of Zion even in this life.

[.signed-section-closing]
Dearly farewell.

[.signed-section-signature]
L+++.+++ A. Barclay.

[.letter-heading]
To +++_______+++

[.signed-section-context-open]
11th Month, 1846.

&hellip;Perhaps some might argue from A.`'s remark, that I sought to cast all into _my mold,_
which is _far from my_ thoughts I assure thee;
for my aim is solely to direct and bring all to the dear Master,
that they may in no wise be looking outward, whether to fear anything or person,
or to follow or imitate any one,
but simply to follow the Master in all that He commands or forbids.

[.signed-section-signature]
L+++.+++ A. Barclay.

[.letter-heading]
To Hannah Marsh

[.signed-section-context-open]
Reigate, 23rd of 11th Month, 1846.

[.salutation]
My Dear Friend,

I received thy kind note on seventh day,
and hasten to inform you of the decease of our dear friend, Susanna Dann,
who peacefully and quietly breathed her last on sixth day morning!--had
the privilege of sitting up with her on the night of yesterday week,
and which was a sweet time to her, from the flow of heavenly expressions,
and the feeling of peaceful praise that attended during that season.
Once, after one of her _very distressing_ attacks of retching,
she sank back in the bed quite exhausted, but,
with heavenly brightness beaming in her countenance, ejaculated,
"`for all I praise thee--most for the severe!`"
At another time she broke forth,
"`O how I love thy law! you know that I have always loved
the heavenly law!`" appealing to those with her.
Another time, called on them to join her in praising and glorifying the Lord.
From fourth day she wandered much, and was unconscious of all around her,
except her son whom she knew to the last.
He was very assiduous in coming.
It was so very sweet to go into the house as we came home from meeting;
it seemed as if on entering the parlour there was a sweet and precious odour met us!
It was very sweet to be with her (_my_ last time) yesterday week;
she sent messages of love to all her friends.
Our loss is great, but it is her everlasting gain!
She was as a mother to dear +++_______+++, who deeply feels it, as does also dear J. Dann.

Oh, how I long that this second trial may but arouse +++_______+++ and +++_______+++,
and not prove as the early dew, soon vanishing away!
If I might but see a prospect of any bending the right way
and likely to uphold the testimonies of truth,
oh how it would gladden my poor heart, and I should depart in peace!^
footnote:[Alluding to her prospective removal to Aberdeen.]
Not that if it be not so, it would rob me of my peace,
for I have endeavoured to do my best and must leave all!
And though I am sensible of many, many shortcomings, and very great weakness on my part,
so as to suffer discouragements to prevail and hinder,
yet I have at times a humble hope that the gracious testimony,
"`she hath done what she could,`" will in tender mercy be pleaded for me,
by Him who is our precious Mediator and blessed Intercessor
with compassionate goodness itself!

And now farewell.
With dear love to you both, I remain thy friend,

[.signed-section-signature]
L+++.+++ A. Barclay.

[.letter-heading]
To +++_______+++

[.signed-section-context-open]
Reigate, 5th of 12th Month, 1846.

[.salutation]
My Dear Friend,

Thy kind open letter felt very cordial to me,
though I assure thee I had not been looking for any acknowledgment
from thee as to the part I had taken in thy help,
and it is a pleasure in any small measure to help those
who are earnestly endeavouring to help themselves,
which, by thy account, appears to be thy case.
I was very much pleased to hear of thy attending to the pointings of the Divine
power--the "`truth in the inward parts`"--in regard to those matters in thy business;
I may say it rejoiced my heart.
And I do hope, my dear friend,
that thou wilt let nothing and nobody dissuade or hinder thee from
such an exercise of mind and faithful conforming of conduct,
no matter in how small a matter;
for I believe that our individual safety and preservation,
as well as growth and strengthening in the _life_ of true religion,
which is far beyond the mere form or profession of it,
depends on our simple obedience in what is secretly revealed to us,
and for which we shall each be accountable.

I am so pleased thou wast enabled to make such a stand at the _onset;_
for it is harder work to retrace our steps afterwards, if we have made a wrong beginning.
Don`'t be afraid;
He who takes care for the poor little solitary sparrows will never forsake nor
fail those who are sincerely endeavouring to acknowledge Him in all their ways,
even to show forth, without being ashamed,
that they desire to love and seek His favour above all,
and that they are under His government.
He stands bound by His blessed promise to help them in every time of need,
and He is not a man that He should lie or change His word.
David says, "`Great peace have they who love thy law,
and nothing shall offend them;`" and this remains to be a precious truth,
confirmed in the experience of all who have tried it;
for nothing shall hurt or harm those who love the
law of the Spirit of life in Christ Jesus,
which is revealed in the secret of the heart--even
their very "`enemies shall be at peace`" with them,
and all things, however trying, shall be made to work together for their good.
And _more than this,_
for the Lord`'s presence and power will be near and round about and in them,
to support through all trials that may be permitted
for their proving and strengthening in the true faith,
so as to make hard things to become comparatively easy and bitter sweet;
and when the Lord speaks peace in us, who then can bring real trouble or make afraid!

Therefore, don`'t be too much looking outward for advice,
but cleave to the Lord`'s power within, mind the dear Master`'s voice there,
don`'t be afraid of trusting what He says to thee, but _believe Him,_
and __thy reward shall be sure__--He will guide thee in safety to an hair`'s breadth,
and His commands will ever come with a clearness and authority (not like the scribes),
and attended not only with a sweet assurance of peace,
but also with a sufficient measure of _power;_ for His word is still with power inwardly,
as ever it was outwardly formerly.
Then I believe, my dear friend, as this is thy humble and sincere endeavour,
outward things will be all __necessarily ordered aright__--there will be a consistent conduct,
industry, diligence, order, and uprightness in business,
and strict economy and justice in all that is used--and there will be
the Divine blessing experienced upon the "`little meal in the barrel and
the little oil in the cruse`"--a blessing on the basket and store.`"

I am quite of thy mind in regard to those who have abundance of this world`'s good things,
and think if these were less devoted to self there would be more to help the needy.
I often feel tenderly for those in business,
for these are times when it is hard for conscientious persons to get along; but,
alas! too many of our Friends are following _the multitude to do evil,_
instead of standing in the testimony of truth against it, even in the true nobility.
But the Lord`'s power is as able as ever it was to direct, to strengthen,
and to preserve, as well as to bless those who cleave to it;
and it is far better to stand _solitarily for the Lord_ than to enjoy the treasures of sin,
even for a season, with the multitude.

Farewell, with much true love.
I had not intended writing so much, but seemed led on,
and must now remain thy sincerely well-wishing friend,
desiring thy encouragement in that which is good,

[.signed-section-signature]
L+++.+++ A. Barclay.

[.letter-heading]
To B. B.

[.signed-section-context-open]
1st Month, 1847.

I count it a privilege and favour to be permitted to feel a degree
of that precious fellowship with the living in Israel,
whatever may be their condition in this life,
which not only unites them one unto another,
but unto Him who is the God and Father of all the human race,
and whose tender mercies are over all His works in every corner of the habitable earth.
Ah, how sweet and strengthening is this precious fellowship,
like a cordial in our many bitter trials and sore conflicts with our spiritual enemies--to
feel a gentle flowing up as it were at times of that precious life of Christ,
wherein is the fellowship and cement that unites
us to the faithful and just of all generations,
whether in the body or removed out of it!
I thought I was sensible of it in reading thy letter,
and I have felt a near sympathy with thee and others in the loss you have recently
had--and perhaps in looking at home you may be often ready to say,
Oh! my leanness! my leanness!
But, dear friends, the Lord is near to sustain under every stripping He permits,
to comfort under every cause for mourning,
and to strengthen and animate under every sense of
our own weakness that He proves or favours us with.
Then it is we cling all the closer to Him, the source of all good and all effectual help;
so that at times we are enabled to say with the poet, "`for all my soul shall bless Thee,
most for the severe.`"

I trust dear +++_______+++ and +++_______+++ are rightly united,
and desire to travel together in the way everlasting, which is the way of the cross.
I have had it on my mind for years to move my tent to a far distant spot,
but nature has sadly flinched.
I must give up to it.
Thou knowest there is a power of Divine grace that is superior to nature,
and able to overcome all difficulties, and lay low the mountains,
and make the hard things easy, and the bitter comparatively sweet.
And I am trusting this blessed power will sustain
amidst all the trials which I know await me largely.

[.signed-section-signature]
L+++.+++ A. Barclay.

[.letter-heading]
To J. B.

[.signed-section-context-open]
Reigate, 8th of 3rd Month, 1847.

&hellip;And oh, dear friend and sister,
may we who are already in such awful stations be fervent in spirit, serving the Lord,
daily waiting for and yielding unto His blessed power, and suffering it to humble, lead,
and restrain us as it pleaseth Him, that we may truly be His faithful servants,
labouring for the advancement and spreading of His blessed cause of truth.
I do feel more and more the necessity and blessing of a season or seasons
of retirement and waiting on the Lord for His feeding or humbling,
His emptying or filling, His magnifying or quickening;
for without His life daily manifesting in our mortal flesh,
what part shall we have in His glorious and dearly bought salvation!
And in looking fearfully forward to the great trial and
sacrifice which is before me in the going into another land,
the words to Baruch, who was in great fear and grief,
have been often made comforting to me--"`Seekest thou great things for thyself?
seek them not, for I will bring evil upon _all_ flesh,
but thy life will I give thee for a prey!`"
Ah, whatever He may be pleased to pluck up and to break down in us of the fleshly mind,
and however He may prove and tryingly lead us,
if His precious life be but given us in ever so small
a measure in the places whither we come,
it will be all-sufficient and an unspeakable favour.
It is coming nearer and nearer to me,
and I feel greatly desirous to be enabled to leave
these South parts clear of the blood of all,
and hope to be shown how before long, and to be enabled to do the Divine will,
however in the cross to nature,
believing that He is all-sufficient to strengthen the poor
weak ones to plead His cause and testify for Him,
that He and His poor servants may be clear.

Farewell, my dear friend; and when it is well with thee,
remember for good thy poor but affectionate friend,

[.signed-section-signature]
L+++.+++ A. Barclay.

[.letter-heading]
To George H.

[.signed-section-context-open]
11th of 3rd Month, 1847.

[.salutation]
Dear George,

I cannot tell thee how very kind I take it of thee
to offer to help and superintend my packing,
and still more to go with me and see me in my new house at Aberdeen.
I feel it as the offer of a _kind brother,_ and if thou art able to do so,
I shall gladly accept thy kind services,
hoping that nothing will occur to prevent thy doing so for me,
and that all will go on well during the week of thy absence.
I feel much obliged to dear S. for giving thee up so kindly and freely.

Dear George, I know thou wilt feel for me in coming to this meeting today;
it was like going into the lion`'s mouth almost,
and so it was yesterday at +++_______+++. But there is a power that can
shut the mouths of the lions and take away all fear but the one
good fear of disobeying the dear Master--and He did help me,
blessed and praised be His holy name, for He hath done for me great things, lifting me,
a poor beggar, as out of the dunghill, and setting me among the princes of His people,
and making me to sound forth His testimony without fear of them,
and gave me peaceful quiet after, though some have shunned me and stood aloof of me.
Do thou crave my preservation in deep humility and watchfulness,
and that I may be made faithful and bold for my Master,
and then I shall flee away to Aberdeen with sweet peace.

Farewell.
With dear love to you both and your dear mother, from your affectionate friend,

[.signed-section-signature]
L+++.+++ A. Barclay.

[.letter-heading]
To K. +++_______+++

[.signed-section-context-open]
Aberdeen, 3rd of 5th Month, 1847.

[.salutation]
My Beloved K.,

I again sit down to inform thee,
I trust under a grateful sense of Divine goodness and mercy,
and which I was constrained on the bended knee to acknowledge hereafter breakfast,
in thus having brought us poor unworthy servants in peace
and safety to the desired haven here on earth,
and to crave His continued renewals of might in the inner man,
that we might be enabled to war a good warfare, to bear a faithful testimony for Him,
and to suffer with patience such trials as He might see best to prove us with,
whilst sojourning here; that thus His good work might be carried on in us,
and that good perfected which concerneth us, whilst time is allotted us here,
and that when time to us here shall be no more, He might be pleased,
in the riches of His grace in Christ Jesus, to bring us to the desired haven above,
the port of everlasting life, rest, peace,
and joy forever! when His high praises might be fully consummated in us,
which now are but feebly begun!

Oh, my dear K., all seems melted in me in thankfulness,
when I tell thee we arrived here at half-past four this morning,
forty-two hours from port to port.
We felt the fresh breezes on the river quite reviving
to us after our great fatigue and poor nights,
and kept up well till half-past eight, when we went down to bed; and early next morning,
on getting out to sea, the heaving began,
though it was said by the sailors to be very calm,
and then we became very sick and tried to get better on deck, but it rained very hard,
and after becoming damp and cold in bearing it from seven till nine o`'clock,
we then went down finally to bed, which we have kept till five this morning,
not raising our heads an inch, lying all three of us like logs; and,
as the last meal we took was tea and toast on seventh day evening at six,
thou mayest judge of our weak and ill state this morning.

How sad it was to part,
and I felt as if I had not half thanked thee enough
for thy great pains and labour for me and mine,
but there is One who can reward thee openly and will do so!

[.signed-section-closing]
Thy very affectionate and truly obliged friend,

[.signed-section-signature]
L+++.+++ A. Barclay.

[.letter-heading]
To Ann Conning

[.signed-section-context-open]
Aberdeen, 8th of 5th Month, 1847.

[.salutation]
My Dear Friend,

I fear thou wilt be impatient to hear, in thy kind affectionate anxiety;
I could quite fancy how thou wouldst feel that windy day,
as thou sayest in thine yesterday.
I may now tell thee,
I hope with grateful feelings to that Divine power who has hitherto helped,
that we left the docks at half-past ten this day week, in the morning.
It was a sorrowful parting with dear John and Hannah Marsh and C. S.,
who came to see us on board, and who watched us till we were out of sight;
and landed here on second day morning in safety.
We were kindly taken in by dear G. and E. Brantingham till fourth day,
when I was anxious to get to my own house, though far from comfortable yet.
I cannot tell thee how great was the comfort of having George H. with us,
and it was a favour that he was not at all sick,
so that he was able directly to get to work for me,
and very active and skilful he has been both at R.
in taking down and packing up the things,
as well as here in putting together.
He desires his dear love to thee.
I have just parted with him reluctantly as the last relic of the South,
and he is to leave by the packet this evening, at six, for home.

Oh, let us seek after the streams of that river of God`'s love
and life that shall never fail but ever make glad,
though the earth be removed and the mountains be carried as into the sea,
and the waves thereof roar and be troubled.
General meeting begins today at Edinburgh, and our yearly meeting the week after next.
It will be very strange to be away; my mind will, I trust, be with them,
and so will thine.
Let us breathe for the arising of the pure life to support the poor little remnant,
even under an unusual depth of suffering; they will need the prayers of their friends.
With dear love, I will remain thy very affectionate friend,

[.signed-section-signature]
L+++.+++ A. Barclay.

[.letter-heading]
To +++_______+++, +++_______+++ and +++_______+++

[.signed-section-context-open]
Aberdeen, 10th of 5th Month, 1847.

[.salutation]
My Beloved Friends,

I enjoy looking at the waves breaking on the shore;
it reminds me much of my room at Marazion.
But the house is very small and inconvenient, no accommodations like the South--in short,
there is _great self-denial_ in the daily comforts
and even almost necessaries of life required;
but our nice North-country Friend servant seems disposed to make the best of everything,
and we must all bring ourselves down to our circumstances,
and learn more self-denial still.
Last night was my best night for several weeks;
it is indeed wonderful how I have been helped through!
This sea air is quite reviving, but we have a great deal of mist often.
The language is so different, we need an interpreter to help us at the shops.
Dear G. and E. Brantingham are like a kind brother
and sister in helping us every way and every day.

And now, dear friends, you will want to _hear_ how I feel.
I was favoured with a season of solemn worship and praise and renewal of desire
to be given up to do and suffer the Divine will entirely yesterday morning,
in my silent sitting in this meeting, and was blessed with a sweet covering,
like the fulfilling of the gracious promise made me at Reigate,
one time when I was greatly tried with the prospect, viz.,
My presence shall go with thee, and I will give thee peace!
So now, what wait I for?
my only hope is in the Lord, even in His mighty and all-sufficient power,
and in the tenderness of His mercy and the excellency of His goodness,
that it may still be extended; for without it I shall fall any and every moment,
but with it I shall be able to do and suffer all things permitted or required.
With dear love to you all, from your very affectionate friend,

[.signed-section-signature]
L+++.+++ A. Barclay.

[.letter-heading]
To +++_______+++

[.signed-section-context-open]
13 Spital, Aberdeen, 17th of 5th Month, 1847.

[.salutation]
My Dear Friend,

My mind has been much with you today at general meeting, and breathing, I humbly trust,
as I have sat at my needle, for the arising of the pure life whereby at least the tried,
oppressed remnant might be enabled to still struggle on after patience and faith,
to wrestle for them as it were in the night season of dismal darkness that may be felt,
wherein is perplexity, if not somewhat of death.
Oh, to be enabled by the Divine life and power to keep the word of patience,
the word of faith, so as to endure all things by the former,
and to move in the right time and way in faithful simplicity by the latter;
for faith overcomes all and shuts the mouths of the lions,
and out of weakness makes strong, strong in and for the Lord.

My beloved sister, my heart seems poured out for the faithful remnant,
but must not linger, having another note to write;
yet feel inclined to allude to thy touching remark as to the encumbering
lawful things hindering the true exercise of this awful annual assembly.^
footnote:[The Yearly Meeting.]
Ah, there is indeed a need of constant watchfulness and endeavouring to dwell deep,
out of the many words and talking about things; feeling is better than talking;
and above all, breathing upward will bring down all-sufficient strength,
as well as all-important humbling of the creature,
and the fear that is clean and keepeth clean; therefore, oh,
let us not get out of a breathing state of mind, whether in or out of meetings!
Alas!
I fear my own mind has been buried in outward things these last two weeks;
but now I am resting on my oars a little,
and tomorrow we start to our monthly meeting at K.

It is sweet to have dear S. H. with us tomorrow, and next day our meeting here,
though I only heard a few words here and there on First day,
and was most deplorably dry and stripped myself of all good.
I thought it was good to sit beside her,
and feel the testimony of truth go forth with life,
though I feared I must almost be a clog in the way myself;
but such a stripping was good for me, if it were not merely caused by my bodily weakness.
Do tell dear +++_______+++ what a comfort her letter was this evening,
and how glad I am she and +++_______+++ were so helped, and dear +++_______+++ also!
Oh, they must increasingly come forward, and eventually, through faithfulness,
possess the gates of all their enemies,
and know a bow of steel to be broken by their arms! oh,
it is humbling to me that way was so made for my exercise at +++_______+++!
It is the Lord`'s doing and marvellous in my eyes.

[.signed-section-closing]
Farewell, dear love.

[.signed-section-signature]
L+++.+++ A. Barclay.

[.letter-heading]
To a Young Friend

[.signed-section-context-open]
13 Spital, Aberdeen, 23rd of 5th Month, 1847.

[.salutation]
My Dear +++_______+++,

I desire, my dear,
that thou mayest carefully treasure up the little fragments of
good that thou mayest have been favoured with during yearly meeting,
not merely under what thou hears, dear +++_______+++,
but also under that precious soul-melting feeling often
permitted graciously in solemn few minutes of quiet.
Ah, this used to be so peculiarly sweet and precious to me, I remember, when thy age,
and still it continues so, with the greater ability to wrestle for it, I trust, and oh,
may it continue to be so choice and sought after to the end of my time here.
And now, my dear, thou must excuse a short note;
but my desire is as strong as ever that thou mayest come down to the power that is super-excellent,
and is within thee, though not of thee,
and will be as a refiner`'s fire and a fuller`'s soap to purify thee and
enable thee to offer an offering in righteousness to the Lord,
and as thou fears and bows to this blessed name or
power revealed within (in the cross to nature),
the Sun of righteousness will arise to thee and in thee more and more,
and enable thee to grow up as a tender and well-favoured calf of the stall,
ready to be offered as a whole burnt-offering to the Lord, thy mighty and good one.
May this be the case is the earnest desire of thy truly affectionate friend,

[.signed-section-signature]
L+++.+++ A. Barclay.

[.letter-heading]
To Friends of Reigate Monthly Meeting

[.signed-section-context-open]
5th Month, 1847.

[.salutation]
Dear Friends,

Being now favoured to arrive here in safety, and a degree of peaceful quiet,
I feel it best to request a certificate removing me to this monthly meeting; and,
in doing so,
it seems with me to acknowledge that during the last eight
months since this removal has been settled on,
my mind has been greatly led at times to dwell on the state of our monthly meeting;
the weak, low state thereof has been spread before me in the light of truth,
and whilst we know that all weakness is owing to a departure from a close
attention to the power of truth on the part of individuals in a meeting,
and that therefore there can be no other way to wax stronger than for each one
in uprightness to cleave to the secret leadings and restraints thereof,
revealed in their own minds--yet have there been two or three little steps opened to me,
as, I trust, in that light and wisdom of truth which is profitable to direct,
whereby you may, as a meeting, be in some degree helped,
and which I feel constrained thus to lay before your weighty consideration.

One of these is the further junction of P. meetings; for,
in looking at the state of these so as to judge aright how far the testimony
of truth can suitably be exalted in the holding of a meeting for discipline,
we should not so much look at the number of members in such meetings,
but should rather look at the standing or condition of the members of them _in the truth,_
how far they will be competent faithfully to uphold the standard thereof.
It has frequently appeared to me that there might
be a service in joining Reigate with Dorking,
and Ifield with Horsham and Capel.
And it is very desirable, in a weak monthly meeting like ours,
that P. meetings should not be held all on the same day,
that there may be opportunity for them to be occasionally visited,
whether by the rightly exercised members of our own monthly meeting,
or by strangers who may feel drawn to travel amongst us.
Where we have a disrelish for the kind visits of others,
it is a sure sign that our weakness wants to be searched into and helped out of,
for none are so weak as those who do not know their weakness.

Another little step that has appeared to me might
be helpful to the state of the monthly meeting,
inasmuch as it would be helpful to the burden-bearers in it,
is that there be once (or more,
if thought well) in the year a committee of overseers held,
to which also such might be invited as are concerned for the right exercise of the discipline,
who should read over the list of members,
and confer together relative to such cases as may require care and tender
counsel--this would be more truly answering the end for which the rule
was made enjoining the reading the list of members (which was that overseers
should be stirred up to diligence and zeal in their several duties,
and especially in the tender care over the dear youth) than the mere formal
reading that list over as is at present done before the meeting at large,
which entirely precludes that interchange of feeling so desirable;
for though the rule of discipline may _allow_ monthly meetings to follow the latter plan,
yet it is evident the former is _enjoined_ at first and the reason or end is given,
see [.book-title]#Book of Discipline,#
page 187. Our overseers lie scattered in our different little meetings,
and thus would there be opportunity for their hands to be a little strengthened
by unanimity and a development of exercise for the good of the body.

And now, dear friends,
having laid upon your shoulders what I have long felt as a little burden, I am relieved,
and believe the gracious testimony will go forth, "`She hath done what she could.`"
Yet still there is a parting testimony required of me,
even for the wisdom and power of Christ,
that it may arise and prevail in your meetings for discipline--for oh, Friends,
especially my brothers,
count me not as an enemy (though ye may receive me
as a fool) because I tell you the truth.
There is a spirit gone forth in our camp, in our meetings for discipline,
which is opposed to the pure and humbling government of Christ,
and hath long had sway and oppressed the true burden-bearers,
and hath thought itself strong and able to speak and act
in those things which concern the dear Master`'s kingdom,
and so hath been busy, up and doing upon all occasions;
whereas it knows not His heavenly control nor humbling qualification even at home,
in its own house or heart, and therefore can never act aright for Him,
how busy soever in its own will and wisdom, striving to have things its own way.
Now this spirit must be brought down into silence
and subjection to the humbling power of Christ,
or else blasting and withering cannot fail of coming
upon whatever meeting it prevails in.

Oh, therefore, dear friends,
let us be willing to come under this baptising power
of Christ revealed in each one of our hearts,
which will bring the silence of death upon every spirit
and feeling in us which is opposed to His righteous government,
and then will His pure life arise more and more in us,
and give us a true feeling and a true sight with
and for Him and His blessed cause or kingdom.
And then in our meetings for discipline we shall each one be concerned
to wait for the renewal of this precious sight and feeling,
which is not at our command,
but is a gift to be continually sought after and faithfully occupied with or exercised.
We should not then be always ready to speak or act,
neither should we be desirous of talking about and reasoning
about subjects out of meeting one with another,
but we should each be as servants in waiting on the good Master in the meeting,
and yielding in simplicity to His humbling and strengthening power,
should be enabled to step or to refrain from stepping according to His bidding, and,
in either case,
should be doing our little best to promote the cause by keeping to His Spirit;
then whatsoever we did in word or deed, being done in His name or power,
would be to the glory of God,
and the reward would be sure both to the doers and to the forbearers,
even the peace of His approving favour.

And now, dear friends,
I salute you in the love of the everlasting Gospel
which seeks the gathering and strengthening of all,
and in which you are at this time individually brought very near to me in spirit,
though outwardly far separated--and, desiring that "`grace, mercy,
and peace may be multiplied unto you,`" through an individual faithfulness
to what you know and feel to be of and from God,
that thus ye may escape the corruptions that are in the world through lust,
become inheritors of God`'s exceeding great and precious promises in Christ Jesus,
and be made partakers of the Divine nature and of
the happiness of heaven forever and ever!
I remain, etc.,

[.signed-section-signature]
L+++.+++ A. Barclay.

[.postscript]
====

P+++.+++ S.--Let this be read in the fear of God in your men`'s and women`'s meetings.

====

[.letter-heading]
To R. R.

[.signed-section-context-open]
13 Spital, Aberdeen, 31st of 5th Month, 1847.

[.salutation]
My Beloved Friend,

We know _who_ can make a way of escape even where we
poor finite creatures can`'t possibly see any,
and then indeed it will be seen that man`'s extremity is God`'s glorious
opportunity for the display of His power and the magnifying of His name,
when the creature is utterly laid low!
Oh! how renewedly the call is reiterated as with fresh force to cease from man,
from looking to him, or leaning on him, as thou says, whose breath is in his nostrils,
and to draw nigh unto God, who will draw nigh unto such to help them freely!
I hear there are very glowing accounts from various quarters
of the love and harmony and condescension at yearly meeting,
but I can`'t but fancy they spring from mere superficial feelers;
that the love and condescension is but a mere imitation of the true thing,
an image which they can`'t give life to! and the harmony
is the reign of oppression caused by man`'s will and wisdom,
and bringing forth a kind of self-complacency,
which is far from the prevalency and humbling of the Divine power!
I have seemed much mentally with them at yearly meeting, and breathing at secret moments,
even while my hands have been much occupied, for the little arisings of the pure life,
whereby the faithful and oppressed remnant might
be preserved in patience and faith a little longer,
even that patience whereby their souls will be possessed in peace,
and that faith which will overcome all things,
and enable to endure the fiery furnace and the lions`' mouths!

I have felt well content with my allotment away, believing I am in my right place,
which is a comfort.
I could indeed believe thy recollection of thy feelings at Hastings from thy letter;
and how true it is, that when the most tried then the most helped! for yesterday week,
after a trying night,
I thought I should have a very unsettled meeting and could not get quiet;
but even then was mercy again lifted up on me in my distress,
in the solemn and sweet season of the silent meeting here,
for heavenly help needs not outward words!
There is a sweet covering over this meeting which is so very precious!
There are four or five not members who come and sit solidly with us,
and two of them even on a fourth day.
There is much openness for tracts here,
and we spread Patrick Livingstone`'s among work people and shopkeepers generally.
We are much stared at,
and I often think of the service there was in dear
Thomas Shillitoe`'s walking along the public walks,
and trust we are desirous to be consistent spectacles in appearance and conduct.

My dear love to M. and P. How sweet was your trebly
dear joint packet before we left Reigate!
How preciously strengthening and cordial is the true fellowship, and,
in the sweets of this, I affectionately salute you three dear sisters,
and remain thy and your truly affectionate friend,

[.signed-section-signature]
L+++.+++ A. Barclay.

[.letter-heading]
To +++_______+++

[.signed-section-context-open]
Spital, Aberdeen, 1st of 9th Month, 1847.

[.salutation]
My Dear Friend,

It seems pleasant to take up the pen to thee,
though I believe our friendship and love for one
another does not stand in mere outward communication,
but in the mutual feeling that we are each endeavouring to yield to the
blessed Spirit of Christ in what is inwardly revealed to us thereby,
and thus in our little measures are in Him in degree,
and longing to be yet more and more so,
and to partake increasingly of that most excellent
communion and union set forth by Him in these words,
"`I in them, and thou in me.`"
The occasion for my now writing is, that I have two days ago heard of the death of W. H.,
and feeling tenderly for his dear widow,
I thought I might ask thee what she is thinking of doing under her present circumstances.
I know not when the event took place; perhaps nothing has been thought of yet;
but I thought no doubt some of your feeling Friends would feel
her case of affliction one to claim your care as well as sympathy.
How will she and her dear children be supported?
as if any thing is raised for her, I would willingly help.

I may I trust gratefully acknowledge that I am now comfortably settled,
and feel peacefully quiet respecting my removal,
though I still _greatly_ feel the trial of the change,
both as regards the climate and the accommodations I am used to,
and nature is very often pinched in it;
but I remember the milch kine of old lowed after their calves left behind,
when bearing the ark of the testimony into another country.
This is a low spot as to truth, as many others are, and trials abound everywhere;
but I desire the seclusion may lead me the more to seek unto Himself,
the alone source of light, life, strength, peace, and comfort!
I can say, "`My soul follows hard after Him,
and His right hand has hitherto upheld me`" in mercy from sinking as into the mire!

[.signed-section-closing]
Thy affectionate friend,

[.signed-section-signature]
L+++.+++ A. Barclay,

[.letter-heading]
To S. B.

[.signed-section-context-open]
Aberdeen, 17th of 9th Month, 1847.

[.salutation]
My Dear Friend,

I fear thou hast thought me very long in taking notice of thy kind letter.
I now enclose a post-office order for five pounds,
which thou wilt ask dear +++_______+++ to accept of.
Please give my kind and tender feeling to +++_______+++,
and I greatly commend and admire her strong and laudable
desire of doing all her best to get a living _unshackled._
I know she is a very executive one,
and I have felt greatly interested about her and her husband.
I hope she continues to be faithful when anything is required of her in meetings.
There is no good advancing either temporally or spiritually without faithfulness;
and I hope she will neither fear nor seek the favour of man,
nor let a gift or kindness blind the eyes, but speak the word faithfully for her Master;
for those who honour Him in serving Him faithfully,
He will honour and cause nothing to harm them!
I expect it is doubtful if the dear child is spared to her,
but children often struggle through much; but if not, it is in mercy,
though a touching stroke;
and if taken away in its innocency she will have cause to bless the good hand!

It must be a comfort to thee to have dear S. H.`'s
and J. Allen`'s company at monthly meeting.
Ah, when we are really baptised into Jesus Christ,
we shall infallibly all speak the same language, the pure language of His Spirit,
and what a precious oneness is there then! the Lord being one, and His name or power one,
His children and people must be one too in spirit!
There is a great talk about keeping "`the unity of the Spirit
in the bond of peace,`" and that text in 2 Cor. 13, v. 11,
is often quoted, but it is too much lost sight of,
that it is subjection to the lowly appearance of the Spirit
of Christ within us that is the key of all these good things;
and if we have this it will make us perfect and upright towards God,
of one mind and speech and testimony in all we do, it will speak the true peace to us,
yea, cause it to rule in our hearts, filling us with good comfort,
not a false encouragement, and the God of love and peace would be felt to be with us.
Ah! the spurious love and unity that is among us! may the
Lord break down the beautiful image in His own good time,
for the worship thereof has truly drawn from the
true worship of and uprightness towards Him!

Farewell.
I fear I have wearied thee, and did not expect to write so much.
I remain, with love to Thomas, thy affectionate friend,

[.signed-section-signature]
L+++.+++ A. Barclay.
