== Chapter XV

[.letter-heading]
To +++_______+++

[.signed-section-context-open]
Aberdeen, 13th of 2nd Month, 1850.

I was much interested in thy account of that meeting at Westminster.
Dear +++_______+++ I know well; he has long appeared,
and again and again been silenced while in +++_______+++ quarterly meeting.
I expect there was a cause there, but how it has been in +++_______+++ I know not.
Oh, how sad it is that there seems often more desire to silence
than to help a dear creature into a better way,
and thus, by this neglect or rather hardness,
many have been as it were driven into the enemy`'s snare and lost to the Church,
who might otherwise have been bright instruments in her!
Dear +++_______+++ is another;
but I fully believe his ancient views are the sole hindrance to him.
The faithful are too often rejected, and the weak or forward are approved of.

Ah, my dear friend, it is a privilege to be of the tribulated ones,
and the little lifts we receive from merciful goodness, from time to time,
surely are enough to make us thank God and take courage!
How sweet is the feeling of union and communion with the faithful,
whether in meeting together as thou didst the other day, and often may with dear +++_______+++,
etc., or whether inwardly in spirit with those who are absent,
even when we each draw near to the Fountain of good, and of all true unity and love,
at the place where prayer is wont to be made,
an inward retirement and subjection of spirit before God!
How close and strengthening is the union!
Then we seem to breathe the same air and drink of the same cup together,
being quickened by and drinking into the same Holy Spirit,
and feel animated thereby to press onward and not to faint.
Yes, are we not _then_ as it were ashamed of our doubting and distrust,
our weariness and fainting under the exercises and trials of our day?
we feel it is ungrateful to Him who deals so tenderly with us.

I think thou art of a very sensitive make;
the enemy tries to move such from their own stedfastness all the more;
but thanks be unto God who hath laid help upon One that is mighty,
and His power is able to quench all the fiery darts
of the enemy as it is yielded to in the true faith;
and it can in a moment calm the troubled waters and quiet the boisterous winds,
speaking peace in the soul.
And the more this power is yielded to, and suffered to spread its mantle over us,
the more will our sensitive natures be properly regulated and quieted,
and made subservient to a good purpose of heavenly praise.
I trust we shall each think of one another for good,
for I have great need indeed to be remembered and breathed for.
But the Lord will not forsake His poor weak worms, but help them still,
and be their guide even unto death.
Farewell very dearly says thy affectionately interested friend,

[.signed-section-signature]
L+++.+++ A. Barclay.

[.letter-heading]
To S. +++_______+++

[.signed-section-context-open]
Aberdeen, 22nd of 2nd Month, 1850.

[.salutation]
My Dear Friend,

I am pleased to hear dear John and Hannah Marsh were at your monthly meeting this week.
You have often such cheering little visits,
and I hope it helps you on your way in struggling after holiness,
without which we are told in Scripture none shall see God.
Well, dear friends, go on in this struggle, in this journey heavenward, cost what it may,
and bring with it what it may of trials and reproaches;
yield to the power of Christ which touches and calls you,
and will strengthen and preserve you as you cleave
close to it in the secret of the heart,
and nothing shall harm you or pluck you out of His tender and good hand.
How wonderfully those dear friends were preserved when attacked by those wicked thieves;
surely they felt a secret power in the house which chained them.
It is a comfort that none of them were not the worse for so fearful an attack.
I feel much for them, but they are so sweet and so helped.

[.signed-section-closing]
I remain, dear S., thy affectionate friend,

[.signed-section-signature]
L+++.+++ A. Barclay.

[.letter-heading]
To Hannah Marsh

[.signed-section-context-open]
Aberdeen, 26th of 2nd Month, 1850.

[.salutation]
My Dear Friend,

I sit down to scribble thee a few lines in haste, and in much poverty and weakness,
and yet with a degree of calmness and awfulness which
is not at my own command as I believe.
It was our monthly meeting today,
and at it I was liberated to visit the meetings and families, where required,
within the compass of Dorset and Hants general meeting.
This is what I alluded to in my last, but I felt afraid of letting it out further then,
as I have never before felt such a sense of the uncertainty of all things,
and whether it might be taken from me or I from it.
I know I shall have your feeling, and I trust also your breathings as you are enabled,
for never poor creature needed them more.
I suppose these humiliating baptisms are necessary
to baptise me for visiting the "`poor and needy.`"
Do you hear of any one going that way?
I have for many years seen it would be required of me, but it often happens with me,
as with the poor impotent man formerly (and I am very impotent I think),
that while he was making ready another stepped in first.
I expect to leave home this day fortnight.

And now, my dear friend, farewell.
I am very weak in mind and body.
But it`'s no matter where the poor body is laid, if it be but in the way of duty.
Blessed is that servant who shall be found ready and distributing
the due portion of meat to the household as required.
In dear love to you both, I remain thy affectionate friend,

[.signed-section-signature]
L+++.+++ A. Barclay.

[.letter-heading]
To +++_______+++

[.signed-section-context-open]
Aberdeen, 2nd of 3rd Month, 1850.

I am now on the eve of departure southward,
an exercising journey to visit Dorset and Hants.
I am much pressed in body and mind,
yet a humble hope clothes me with calm that the Divine
power will be near to strengthen for the duties,
and to support and comfort under the trials allotted,
and that _mercy will compass me about._
And so I desire to be given up to be led about, humbled, and instructed anyhow,
and to bear the little foolish-looking testimony that may be given me to bear,
whether in silent exercise, secret suffering, or vocal utterance; only,
oh to be preserved in the pure life, that _life may be over all,_ as dear P. L. says,
and keep me to the end.
I cannot add more, being pressed out of measure, but yet,
would add thy kind expressions concerning such a poor weak creature, make me to tremble,
but it is well that I should be given to feel my own vileness as a counteractor.
Oh, let us cleave to that power which can work in us
that which is well-pleasing in the Divine sight,
perfecting in us the work of faith to His glory and our everlasting gain.
With dear love, I am thy friend truly,

[.signed-section-signature]
L+++.+++ A. Barclay.

[.letter-heading]
To +++_______+++

[.signed-section-context-open]
Southampton, 5th of 4th Month, 1850.

We know the Divine power is all-sufficient as ever
to quicken and clothe the very dry bones,
and to raise up unto Himself children in the faith, of faithful Abraham,
even as from the stones of the street, and nothing is too great for His goodness,
nor too hard for His power to do, in and for those who wholly yield up unto Him.
I may inform thee I have gone through the chief part of the exercising service,
if such I dare to call it, which I had on my mind,
and in it have been most mercifully helped in a way I never experienced before,
to my marvelling and humbling at times as in the dust,
so that I am sure I ought never more to flinch or to distrust,
or to fear to be wholly given up to what appears to be required; but, oh,
what poor weak creatures we are,
and what would become of us were it not for daily
and _momentary_ mercy which is so tenderly extended.
I found dear W. Binns was thought to be sinking the day I got there, but he revived.
He said his only hope is in the mercy of God in Christ Jesus,
and he greatly desired to be preserved in resignation to the Divine will,
and from bringing the least hurt to the precious cause.

[.signed-section-signature]
L+++.+++ A. Barclay.

[.letter-heading]
To Priscilla R.

[.signed-section-context-open]
Bregsell, 23rd of 4th Month, 1850.

[.salutation]
My Dear Friend,

Once again do I salute thee from this interesting spot, where I arrived,
last fourth day evening, from Godalming monthly meeting.
And though feeling very poor and empty, and as a dry stick,
so that I doubted before meeting if I should take my certificate in my pocket, yet,
through adorable and condescending goodness,
I was made unexpectedly strong in a pleading testimony to my dear old Surrey Friends,
and was helped also to supplicate for the few burden-bearers,
and that others from the rising generation might come up to their help.
I was also brought under unexpected exercise in both meetings for discipline,
having to go into the men`'s meeting:
so it was well I had my certificate and had not yielded to doubts.
A+++.+++ M. went with me and J. Dann, so that, my dear Priscilla,
thou wilt unite with me in humble praise to Him who helps the poor and weak,
and enables to magnify His name and exalt His pure truth when least expected.
I was melted afterwards,
in hearing that the visit to the men`'s meeting was remarkably opportune; so that,
my dear friend,
we poor weak ones have indeed cause more than ever to lie low and cleave close
to inward and pure guidance that will lead us safely and wisely along!

I think in this journey I have been renewedly confirmed
and strengthened in my desire to do so through mercy!
I was very _sweetly_ at S. and M. Lamley`'s,
and the former kindly went with me to the Isle of Wight.
I was much comforted in being at +++_______+++`'s at Newport,
things were so much improved there,
a sweet savour in the house! and there I had to inform
Friends that I felt somewhat of the woe,
if I omitted a little meeting with the serious professors at Ventnor,
and that the word within was, "`go and I will go with thee; be mouth and wisdom, tongue,
and utterance to thee!`" and so,
having previously obtained the sanction of the select Friends at Southampton,
we went forward and got the British school next to the Independents`' chapel,
and their minister gave up his usual prayer meeting that evening--and
gave notice to all his auditors of the meeting in the next room,
and attended it himself.
We had about one hundred, the room being quite full of "`Plymouth brethren,`" Brianites,
Methodists, and Independents--and, through merciful goodness,
it was a solemn and favoured time, and a sweet covering seemed to be over us I thought,
in time of silence, which was long.
Next day I paid two visits at Ventnor, and two on the road to Ryde,
at Bonchurch and Brading, with serious people--one a female Brianite preacher,
whom I had felt much drawn to eight years ago,
and it was worth going through much in body and mind for a time of mutual praise I thought.

We sat with dear +++_______+++, wife, and daughter, next morning,
and got into Basingstoke that afternoon,
so as to attend the monthly meeting there next day, and,
after some sittings with and calls on a few,
to proceed to Alton--a very interesting spot to me.
Oh, how, as we rode along there,
I was reminded of some sweet seasons of favour when riding on my pony alone,
along that road twenty-one years before,
wherein I would stop the pony and sit still to enjoy the heavenly goodness!

My dear friends, I more and more feel the uncertainty of time and all things here,
and that I am decaying fast, feeling unable to bear what I did,
and do not expect to sit more than one sitting of the yearly meeting a day,
except the select ones!
But oh, how do all things here seem to sink in estimation,
in comparison of the one precious fellowship with the Father, and the Son,
and with the faithful, whether in the body or removed out of it;
and which blessed fellowship is only attained or graciously
permitted as we walk in the pure light Divine,
and suffer the Divine will to be wrought in us by
the Divine power! and this will is our sanctification,
whatever trials it may lead into.
But I have not time to enlarge further as is in my heart to do;
you can feel me in that which is beyond words, and needs not words to depict it.
Oh, what a favour and mercy to have been helped over
what I felt as a duty in this journey! and oh,
to be continued to be helped a little from day to day all
my remaining journey through this vale of tears,
and to be preserved to the end in humility and nothingness of self.
Crave it for me, my beloved sisters,
and that I may never bring the least reproach on the holy cause!
Yea, let us crave it for each other, or seek ability to do so!

[.signed-section-closing]
Farewell dearly. Thy affectionate friend,

[.signed-section-signature]
L+++.+++ A. Barclay.

[.letter-heading]
To +++_______+++

[.signed-section-context-open]
Dorking, 29th of 4th Month, 1850.

My dear friend,
I am melted when I look at the goodness and mercy
that have been extended to me in this journey throughout,
and how, out of so much weakness and poverty and strippedness of all good,
I have been enabled and filled with a testimony for my good Master as I humbly trust,
which has proved that it was His doing and marvellous in my eyes,
so that indeed I have cause never more to shrink or to doubt or to distrust,
but increasingly to yield myself to the touches and
drawings of His blessed and blessing power,
for His mercy endureth truly forever;
and what great mercy to make use of such a poor weak worm of the dust!
My heart is at times filled with praises and with the gentle flowings of peace,
and my whole desire is to be kept humble and prostrate,
cleansed by any refining means Eternal Wisdom sees best, that flesh may be abased,
and He alone be glorified and magnified in and by me.
This is more about _self_ than I at all intended, but somehow my pen has run on,
and perhaps it may encourage thee too, dear +++_______+++, to stretch forth thy arms,
and let the Lord gird thee and lead or carry thee as and where He will,
even into the simplicity and quieting of the weaned child,
for of such His heavenly kingdom is composed.

Farewell, very dearly. I am thy very affectionate friend,

[.signed-section-signature]
L+++.+++ A. Barclay.

[.letter-heading]
To +++_______+++

[.signed-section-context-open]
5th Month, 1850.

[.salutation]
My Dear Friend,

I hardly feel easy to leave these parts without dropping thee a
few lines to make up for the deficiency which I have often felt,
by acknowledging that I have, at different times,
felt much tender sympathy with thee under thy solitary circumstances hereaway,
and especially last autumn,
in hearing of the decease of two of thy dearest and oldest friends;
and I have no doubt thou often hast very low times in looking
round and seeing that thy contemporaries are nearly all,
if not quite so, dropped off from beside thee,
and thou mayest feel like a solitary beacon upon the top of a hill!
And in such low seasons thou mayest not see any good
that thou art of in being thus long detained here,
and mayest often be ready to fear,
lest thou shouldst be anything of a stumbling-block or hurt
to that cause which I do believe is precious to thee!
But, dear friend, it may be well for us to be thus proved and tossed in mind,
and the Lord has a good design in thus permitting
it and in stripping us as on every hand,
even to refine us more thoroughly, and to poise our spirits more entirely heavenward,
and to lead us to cling the more closely unto Him
in whom are all our fresh springs both of life,
of support, and of consolation!

Ah, I can indeed feel for the solitary and the tried, being thus situated myself;
and I have said in my heart, during this late little labour of love,
when meeting with such stripped ones,
surely it has not been in vain that I have been when
at home baptised into their state and for them!
And I earnestly desire, that we may be more and more drawn inward and upward,
even to an inward daily waiting for the quickenings of life from Christ,
whereby we may be kept alive unto God and upright for Him,
faithful and fruitful unto Christ, and savouring of Him--and then I believe,
our breathings will continually ascend heavenward for fresh and fresh guidance, counsel,
support, and preservation,
under the remaining temptations and trials of our day--and being preserved hereby
from casting away our confidence in the sufficiency of the Divine power and light,
shall, from season to season, be rewarded,
even amidst the many tribulations of the present day,
with those precious consolations which are in Christ Jesus,
and are graciously permitted to the soul that is brought
into union with Him through the one true baptism.

So, dear friend,
I long that thou mayest not yield to the buffetings or temptations of the enemy;
however brought low,
but mayest hold fast this blessed and holy "`confidence which hath great recompense
of reward,`" cleaving close to that which thou hast known and felt,
and heard in the secret of thy heart, and then,
though solitary or surrounded by such as may have a weakening tendency,
thou wilt be preserved in the true integrity to the end,
and be a helper of the upright and a gatherer under the sacred influence of Christ,
and His holy life springing up in the soul will make up for all trials.

In dear love, farewell,
and desiring to be ever kept in remembrance that the good seed
is only to be obtained by persevering in cleaving to the good power.

[.signed-section-signature]
L+++.+++ A. Barclay.

[.letter-heading]
To +++_______+++

[.signed-section-context-open]
14th of 6th Month, 1850.

[.salutation]
My Dear Friend,

I did not feel those few minutes before meeting relieving
to my mind on the subject of thy business,
viz., the selling of wines and spirits,
however thou mayest plead that thou only sells for refreshment and in moderate quantities,
yet surely much will lie at thy door, for thus encouraging the use of such beverages,
and thereby begetting the taste and habit,
which in after life may lead to serious consequences to body and mind.

How important it is that Friends who are called to
be promoters of all that is good and pure,
and discouragers of and testifiers against all that is of evil tendency,
should look well to what they put their hands to or encourage by example!
And, my dear friend, thou mayest fancy thou art easy with the practice,
and seest no harm in it or no requiring to leave it off,
but I believe thou hast been stifling the voice of Christ in thy conscience,
and would none of His counsel,
under the plausible plea of providing for thy family by this means,
forgetting that the Lord can bring a blast upon all thy endeavours in a moment,
and though thou may gather a heap, if He blow upon it in displeasure it will vanish away,
and should He permit it unto thee,
there may be as it were a worm that never dies at the bottom of all thy enjoyment of it!

Ah, how apt are we poor erring mortals to say we don`'t
feel this or that required as a sacrifice,
when all the while we are shrinking from the pure light of Christ`'s Spirit,
or hiding our eyes from seeing with it what is our duty to do,
for fear of the consequences! and when we become hardened by long resistance,
we may fancy we feel easy,
but is it not the ease of the enemy which ends in spiritual death?
Now, my dear friend, I would,
in sisterly tenderness as well as earnest concern for thy best welfare,
entreat thee to look well at the subject; yes, to lay it as before the Lord,
to be weighed in the righteous balances of the sanctuary,
and examined in His pure sight--be willing to come
and sit as a little child before the Lord,
waiting for His holy counsel and heavenly guidance,
and then I undoubtingly believe thou wilt be given to see
that He hath a controversy with thy continuing the practice,
and calls thee to wash thy hands in innocency of it,
now that the time is come that thou art unshackled by others;
and He requires thee to set a noble and humble example in this respect--and if thou
art willing to come down in thy mind to let the Lord gird thee with His strength,
and guide thee with His counsel,
and carry thee where thou wouldst not (into the denial of self),
herein thou knowest not how thy example might be
followed by divers serious persons of other persuasions;
for I have known many such instances of faithful Friends thus leading
others by their example out of undesirable practices similar;
on the other hand, if thou neglect this opportunity by persisting in thy old course,
when thou _might_ step properly out of it in true faith and faithfulness,
I fear the loss and consequences will be sad and great to thyself and to others,
and sorrowful indeed would it be if thou train thy sons up to such a practice; oh,
_do_ take care how thou lays snares before these dear
tender young plants committed to thy charge,
but train them in the _pure_ way of the Lord, and set them a good example,
for thou wilt be answerable before Him in a day that is hastening on us all.
I hope thou wilt not think this close pleading unkind,
for I have nothing but dear love in my heart to thee,
and must be faithful as a mark of it.

Oh, I cannot tell thee how much my heart has yearned over thee ever since I knew thee,
believing that thou wast brought in mercy to the knowledge of the
truth for a good and blessed purpose to thyself and others;
and I have feared there has been that which has let and hindered it,
there has not been that humbling submission to the Lord`'s holy power,
whereby thou might have been made a holy vessel for Him; but oh,
that the stumbling-block may be removed out of the way, and the meek and lowly,
and lamb-like spirit of Christ may be put on,
that the light of thy good example may shine more and more clearly and brightly,
so shall thy last days be thy best days,
and the poor little church in +++_______+++ yet have strength through thee,
by the prevalency of the pure testimony of truth in thee,
and thy peace would flow as a river!

[.signed-section-signature]
L+++.+++ A. Barclay.

[.letter-heading]
To Ann Conning

[.signed-section-context-open]
Aberdeen, 17th of 6th Month, 1850.

Now, my dear friend, to turn to thy kind letter,
I may also say I felt more than ever in parting with thee this time.
It felt probably the last time we shall meet together in this world.
I could not suppress my tears even after we were seated in the railway carriage.
I comfortingly believe thou art near to the haven of rest,
whereas I may have many more painful steps along the rugged and "`tribulated
path from death to life,`" as thou sayest Sarah Grubb says.
May my eye be kept singly to the sure Guide,
and my leaning be simply on the gracious Strengthener,
and then I have a little humble hope He will bring
me in due time out of all the troubles and afflictions,
in wisdom permitted for the trial of my faith and patience,
and give me an inheritance with the sanctified in Christ Jesus.

Ah, I have much sympathy with thee in thy close provings
and many downsittings and great strippings`';
but all is known to Him who will not suffer us to be tempted
or tried above what we are able through His grace to bear,
so let us cast ourselves at His feet as it were, but not cast away our confidence,
but girding up the mind,
hope to the end for that precious grace that shall
be brought unto us at the revelation of Jesus Christ.
I think it is often the case that such as have been much made use of and
favoured with heavenly gifts are deeply plunged at the end of their pilgrimage,
as dear +++_______+++ was, and others too;
but this is a merciful and last baptism to prepare for the realms of bliss,
and the girdle of the power of truth will keep the garments,
even the clothing of the Spirit of Jesus, close around, that no nakedness may appear,
and strengthen the limbs to press onward to the good end that crowns all and is peace.
I unite with thy remark as to our meetings being similar in want of light and life,
and the wading times this brings me are many, and I do feel solitary,
inasmuch as there is too much of a disposition to
let things go on as they are and have long been,
instead of arising and labouring for an improvement,
either inwardly in spiritual exercise, or vocally in testifying for the pure cause.
I felt grateful for thy kind attentions and care over me,
and it was sweet to be in thy house; I often felt so during the day,
especially while walking up and down in the garden.
I remain thy nearly united and affectionate friend,

[.signed-section-signature]
L+++.+++ A. Barclay.

[.letter-heading]
To +++_______+++

[.signed-section-context-open]
Aberdeen, 1st of 7th Month, 1850.

[.salutation]
My Dear Friend,

I was glad to have that little time with thee at my lodgings +++[+++in London],
and should have liked more if I could have had it.
I could well enter into thy trials as I thought,
and can enter into thy feelings as expressed in thy letter.
Is it not well for us thus to be proved and pinched
with fears and a sense of weakness and dangers around?
Does not such a dispensation or permission tend to keep us more humble and watchful,
distrustful of ourselves, and continually craving after best help every moment?
whereas if we thought ourselves going on right and well we might get exalted,
and so less careful and craving; certainty would not prove our faith then.
I can so well sympathise with thee in these feelings just now, having, as it were,
to sink down into trials, and had to return as to the sitting at the King`'s gate,
divested of all the royal robes and best ability, and to be clothed instead,
as with the abhorring one`'s self, and mourning over my many weaknesses and shortcomings.
But this I can say, I do _look towards_ His holy temple often in the day,
and breathe for help and quickening; but this is not my own either,
for He gives the eye that can and chooses to look thitherward.

I am rejoiced to hear of your late quarterly meeting.
I suppose the friend thou alluded to was dear +++_______+++. Yes, my dear friend,
I never was so struck with the low state of things
amongst us as when in and around London.
Well, however we may as a people get worse and worse,
more and more leavened into the worldly spirit, outward and superficial,
yet there is and will be a little remnant preserved who have not bowed the knee to Baal,
and such must submit to be trodden down and put into prison as it were,
and lay their mouths in the dust till the time of their deliverance comes.
But though things are getting so bad, and as I may so say rotten at heart,
yet still some seem to think all things are well and like to make a boast.
Ah, the enemy will not care what good works we set about,
if He may but rule and govern within us,
and so crush the tender buddings of the seed immortal which leads to inwardness,
quietness, and humility, wherein will be our preservation,
even in subjection to the Lord alone.

Dear Priscilla R. I had a very sweet little time with,
one morning after reading (she breakfasted with us);
first in a _sweet_ and _uniting_ and _solemn silence,_
and then she addressed me peculiarly to my comfort and help when outwardly much tried.
Oh, these secret and deep and hidden times are better than all the outward _chat,_
strengthening and refreshing,
and to be dwelt upon afterwards with peace and with grateful praise.

With dear love, and loving to think upon thee as one of my dear Lord`'s little ones,
remain, craving thy preservation and help as of myself, thy affectionate friend,

[.signed-section-signature]
L+++.+++ A. Barclay.

[.letter-heading]
To +++_______+++

[.signed-section-context-open]
7th or 8th Month, 1850.

[.salutation]
My Dear Friend,

I know not where this may reach thee, but thought I would send thee a few lines,
which I have long wished to do, expressive of dear love,
and the breathings which have continually ascended within me for thy strengthening and
preservation in thy deeply exercising labours of love in this part of the world,
that thy eye may be kept closely inward to the pure and Divine gift of light and life,
that so thou mayest be enabled to see all the various snares set by the grand adversary,
especially in the way of such as are devoted to do their little best to pull
down his kingdom in the hearts of their fellow creatures--and seeing them,
thou mayest be led to cry mightily to the Strong for strength,
to the Wise for wisdom to avoid them, even to thy deeper humbling,
and further strengthening,
and greater filling with praise to Him who is sufficient
and all in all to His devoted and dependent children.

I have earnestly craved that,
whilst supported under the sore exercises and deep baptisms which must be thy
portion in thus visiting the seed that is in oppression in the hearts of the
professors of the truth (who are too often crucifying the dear Son of God afresh,
in His inward and spiritual appearance),
thou mayest equally be guarded against anything savouring of seeking
or delighting in the favour or approbation or applause of men,
and which I apprehend may so very imperceptibly to ourselves creep over us when
thus largely and continuously engaged in our Divine Master`'s service,
as well as so insidiously be made use of by the enemy,
thereby to draw us aside from that littleness and lowliness,
that holy watch in the Divine fear,
that pure inward dwelling whereby our eye may be
kept clear from creaturely bias or affection,
our hearts upright to and for our Master,
our hands clean and strong to labour for His holy cause,
and our feet preserved from every snare.
However wily and strong the enemy may be to lay hold
of our various weaknesses of flesh and spirit,
for his own bad purpose, the Lord is nigh and stronger than all to guide, guard,
strengthen, and preserve, as there is a low lying and a close keeping to and before Him;
and therefore unto Him and the word of His grace nigh in the heart would
I affectionately commit and commend thee and all my dear friends,
with my own soul, who is able to build us all up, to preserve us to the end,
and to give us an inheritance with the sanctified of all generations,
to praise His excellent name forever and ever!

[.signed-section-signature]
L+++.+++ A. Barclay.

[.offset]
+++[+++The following was addressed to one not in profession with Friends.]

[.signed-section-context-open]
9th Month, 1850.

[.salutation]
Dear Friend,

Writing to +++_______+++ I feel inclined to salute thee with a few lines,
to express the earnest solicitude I feel for thy best and everlasting welfare,
and which I believe proceeds from that love which spreads over sea and land,
and to all sects and names,
and seeks not the gaining of proselytes to any mere set of opinions or compact of practices,
but seeks after and rejoices in the spreading of the holy and pure truth,
even the inward and spiritual kingdom of our blessed Redeemer,
whose kingdom is an everlasting kingdom, and His dominion shall endure forever and ever,
and of the increase whereof, even the riches, the glory and the peace thereof,
there never shall be an end.

I felt indescribably for the short time we were together,
believing that thou hast been visited by the dayspring
from on high after an excellent manner,
in tender mercy to thy soul; that God who commanded the light to shine out of darkness,
hath shined in thy heart to give the light of the knowledge
of His glory in the face or appearing of Jesus Christ;
but it appears to me that thou art overrunning this pure and holy light--thou
art as it were overlaying the Babe immortal that hath been quickened and
brought forth in thee--thou art not little enough and low enough,
silent enough, and enough willing to be a fool and to be nothing, do nothing,
and appear nothing, that so that living birth might grow and spread in thee,
that holy light and seed might increase in thee,
so as to come over thee and overcome thee,
and to bring and leaven thee into its own nature.
But going forth after the enemy who raises up a dust
of reasonings and plausible conclusions in thee,
thou art leading away from that lowly nature, that little Child that should lead thee,
even the Saviour in His lowly appearance within thee,
and art entering into and sucking down reasonings against this, that, and the other,
without thee, whereas thou hadst better dwell more inward and mind what is passing there,
and what the Master says and bids thee either do or forsake,
and not be so much looking outward and reasoning.

The Lord seeks not a reasoning mind in us, but a feeling, submissive heart;
and it is the meek and the humble (who _must_ be silent to
be so) whom He teaches His way and guides in true judgment,
because in their humbling their own judgment is taken away,
and they become wholly passive and nothing in His holy hand.
Therefore,
the enemy will strive ever so to draw us away from
this inwardness and littleness and stillness;
and it is one of His surest devices to lead us from
yielding to the drawings of the light of Christ,
by inducing us to look at this or that person or people
who have made or are making a profession thereof,
to behold and reason upon what is inconsistent or wrong in them,
and to lay it upon such a profession instead of upon
the weakness or unfaithfulness of individuals.
Thus many a tenderly visited one has stopped short instead of following
on in the simplicity and humility of a little child,
to know more and more of the Lord`'s holy will and
precious leadings--and as they thus stop short,
so the heavenly light is lessened,
and dimness of sight and weakness of hands creep over them,
they wander further and further in the mazes of the enemy,
and get to call light darkness and darkness light.

It is these who are going back again to Babylon,
though they think they are come to Mount Zion,
and they have need to remember our blessed Lord`'s language, "`If ye were blind,
ye should have no sin; but now ye say, We see, therefore your sin remaineth.`"
Whereas, those who, without reasoning or looking outward,
mind the Master`'s voice within,
yielding to His blessed power that makes willing to be little and low,
and to receive little and low instructions from Him,
and to walk in the path of brokenness and humility--these thus following on to know
Him shall know the goings forth of His power to and in them to be prepared as the morning,
with increasing light, life, and strength;
and the returning incomes of His love to and in their souls
shall be as the latter and the former rain in its season,
bringing renewed refreshment, nourishment,
and fruitfulness with them to His praise and glory.

Oh, therefore, dear friend,
receive this little word of exhortation in the love in which
it is written--cleave close to the seed or measure of light,
life, and truth revealed in the secret of thy heart,
let that judge in thee and judge thee down, move in thee and lead and act in thee,
and then thou wilt unfailingly be humbled and consequently strengthened,
be brought to nothing in thyself and consequently
made what the Lord would have thee to be;
be emptied of all thou canst call thy own, and consequently filled with the substance,
riches, and everlasting peace of the heavenly kingdom, yea,
and be made an instrument for the gathering of others to the same.

I remain thy poor, weak, tribulated friend, and hearty well-wisher,

[.signed-section-signature]
L+++.+++ A. Barclay.

[.letter-heading]
To a Young Friend

[.signed-section-context-open]
Aberdeen, 14th of 9th Month, 1850.

[.salutation]
My Dear +++_______+++,

How thou wouldst have enjoyed being at Ballater with us!
It is a simple village situated in a rich valley by the river Dee,
and is surrounded with hills and mountains rising
like waves one behind the other,--some wild and craggy,
and others feathered up to the top and amongst the crags with beautiful weeping birches,
Scotch and spruce firs, and larches, oaks, and mountain ash,
covered with red berries--and in the far south and west, highest of all,
were the Cairn Gorum mountains, Benavon and Lochnagar,
about 4000 feet above the level of the sea;
the hollows of these were still white with snow when we first went--the
latter is a very fine mountain with several peaks,
and was always visible, the others we could only see by climbing the nearer crags.
One of these, Craigendarach, was a favourite resort of ours,
having so much variety,--steep perpendicular precipices,
rocks jumbled about in all directions and shapes,
with the clusters of weeping birches romantically growing out from these debris,
with the other variety of trees I have mentioned,
and the purple heath in luxuriance and brilliancy of colour that I cannot describe:
the sheep scattered about, nibbling on the patches of grass interspersed,
and a flock of pretty goats climbing the frightful rocks for the foliage among them;
a beautiful landscape of hills and mountains,
with the Dee winding like a blue ribbon through the valley rich with corn;
and an intense quiet all around,
save when a breeze rippled among the woods below or above us;--a
lovely scene where I much enjoyed to pitch my camp stool,
and +++_______+++ occupied a rock on the heather.
We never got tired of its variety--the height is 1340 feet and I only once got to the top.

The weather was very fine, but the last week it became misty and frosty,
and we had blazing wood-fires to warm us.
It was a beautiful sight to see the mist rolling up the mountains,
like drawing up _curtains_ in _festoons_ about eleven o`'clock, when the sun got up,
and it left as it were "`hoary locks`" upon all the
heather and brushwood and smaller firs,
caused by the gossamer being covered with strong dew or
frost--and at mid-day it glistened beautifully in the sunshine.
These mists considerably changed the colour of the foliage and ferns,
and dimmed the dazzling brightness of the heath the last week.
We found the people were pleased with tracts, some of them.

Well, dear +++_______+++,
the same good and mighty Arm that raised up our forefathers
and predecessors to be a people,
to bear His pure and holy testimony to the nations formerly,
is still able and willing to raise up counsellors
as at the beginning and judges as at the first,
humble valiants, and faithful testimony-bearers in various ways at the present day,
if there be but a yielding to His humbling, crucifying, quickening,
and strengthening power,
which is nigh in every one of our hearts to visit and do us good,
and all-sufficient for all.
Oh, then,
that thou and I may be of this happy number who are thus yielding and abiding in subjection
and in waiting thereupon--so shall we be built up in the most holy faith,
and receive an inheritance with the sanctified which shall endure forever.

With dear love, I remain thy truly affectionate friend,

[.signed-section-signature]
L+++.+++ A. Barclay.

[.letter-heading]
To +++_______+++

[.signed-section-context-open]
Aberdeen, 20th of 9th Month, 1850.

[.salutation]
My Dear Friend,

I quite agree with thee thou canst not do better than remain as thou art,
trusting in that Almighty power who has hitherto
stayed the waves when they looked ready to overwhelm,
and has kept up thy little bark still struggling on.
Thy remarks are very just,
and I only wish that many others of our young men followed thy example,
but while they are turning away their ear from the alone
sure Guide and leaning only to their own understanding,
trusting in an arm of flesh, where is their consistency as Friends?
where is there being testimony-bearers against the worldly spirit in their trade?
where is their right direction, and consequently the blessing of heavenly peace?
They may seem to get on well for a time, but their minds are buried in the earth,
they are slaves to outward things, instead of being the Lord`'s free-men,
are in anxiety and harass,
instead of enjoying the true peaceful quiet of trusting in Him, and having His favour.
I much commend thy endeavours about prices.
I think many Friends err by seeking such great profits and really lose business by it.
It is quite proverbial in some places.
We can`'t have too much of the dear Master`'s company,
nor can we lean too much or pour out too much to Him,
a never-failing and unfaltering Friend, that sticketh closer than a brother.

[.signed-section-closing]
I remain thy affectionate and sincere friend,

[.signed-section-signature]
L+++.+++ A. Barclay.

[.letter-heading]
To +++_______+++

[.signed-section-context-open]
Aberdeen, 3rd of 10th Month, 1850.

[.salutation]
My Dear Friend,

Surely the messenger of sickness and death is going about awfully at this season,
and the warning is a solemn one to us all!
I expect you have known dear +++_______+++ revive more than once as from the gates of death;
still this seems a more near approach than any,
and I tenderly feel for thee in the prospect of having to yield up this
dear brother and object of thy very affectionate watching to Him who gave
him and has spared him so long and unexpectedly to you all.
Perhaps even before this note reaches thee, the severing stroke may have been given;
but I trust that ere that takes place,
you may have had the comfort of your dear invalid`'s
more clear evidence of acceptance in the Beloved,
_his_ beloved!
It is often in matchless wisdom seen meet to be withheld till a very late season;
yet surely no true-hearted follower of the dear Lamb is forsaken at last,
or deprived of that humbling and calming assurance
which fills the departing spirit as with praise,
though there may be a fear of much expression thereof.
If he is still in the poor body, give my dear love to him, and tell him I trust,
that whatever may be his provings of faith and patience,
he is at times made sensible that the everlasting
Arm is underneath for his support and help,
or at least that, when faith is fainting, heavenly hope comes in to its succour,
giving again and again to lean upon Him who is of
power and tender goodness to His poor weak creatures.
I remain thy truly sympathising and affectionate friend,

[.signed-section-signature]
L+++.+++ A. Barclay.

[.letter-heading]
To +++_______+++

[.signed-section-context-open]
Same date.

+++_______+++and +++_______+++ have just finished our families,
and very acceptable and sweet has been their visit, as a brook by the way;
so I feel I have had my little cake,
and must prepare for a forty days`' travel in the wilderness;
but great is the mercy that helps us poor travellers along.

With dear love,
and hoping you have had the like refreshment in +++_______+++ and +++_______+++`'s late visit,
I remain thy and your affectionate friend,

[.signed-section-signature]
L+++.+++ A. Barclay.

[.letter-heading]
To +++_______+++

[.signed-section-context-open]
Perth, 22nd of 10th Month, 1850.

[.salutation]
My Dear Friend,

Thy thoughts are like my thoughts of myself.
But in looking at these things, I have thought,
that as we are drawing nearer to the end of our race, it is well, yea,
a marvellous mercy, that we should be deeply humbled, and increasingly so as we advance,
that we may more and more feel that "`in our flesh dwelleth no good thing,`" and all
that is good or right is only a loan for the purpose of the glory of the Giver,
and to spread His blessed kingdom and the enjoyment thereof;
and I think we see it to be so with all the faithful--they are deeply abased and behold
their own vileness again towards the end of their day as when they were first visited.
But there is this blessed exception, a quietness and assurance,
a heavenly peace in and through the holy Redeemer,
which is mercifully permitted in His free grace to
be the work and the effect of the true righteousness,
even that righteousness which is by faith in and of the operation of God

Do not think of me above what I am, a very weak sister.
How sweet are those words, "`therefore I _take pleasure_`"--that is,
more than resignation in infirmities, in reproaches, in necessities, in persecutions,
in distresses for Christ`'s sake, for when I am weak then am I strong!
These deep baptisms, as in the cloud and in the sea,
often are preparatory for either service or suffering.
I long my little sojourn here may be sanctified to me, if no other good come of it.

Farewell, dear friend.
Let us seek to be preserved on the sure Foundation that our work may stand the fire;
let us seek that the Spirit of God may dwell in us, sanctify us,
and clothe us as little children, and then it is said, all shall be yours, whether Paul,
Apollos, or Cephas, or life, or death, or things present or to come, all are yours,
and ye are Christ`'s, and Christ is God`'s.

[.signed-section-signature]
L+++.+++ A. Barclay.

[.letter-heading]
To +++_______+++

[.signed-section-context-open]
25th of 10th Month, 1850.

I have had the great privilege of dear +++_______+++ and
companion`'s company nine days under my roof,
and a most strengthening visit it was, and comforting,
although she had _comparatively_ little to say in either
of the three meetings we sat together,
nor had we _any_ private sitting at all; yet there was such a weightiness and silence,
and _ingatheredness_ in her social intercourse,
and such a sweet savour attending her converse, as was better than words,
however encouraging; it felt something solid and not superficial,
reminding me of good old days thirty years ago,
when our meal-times used to feel like meeting-times,
in mingling with our faithful ministers.
_But now_ chattiness and fascinating manners have taken
the place of this gathering to the one blessed Master,
and a _formal_ gravity has taken the place of the true and lively weightiness of spirit.
I assure thee it was hard to us to part with them,
and I do trust it was a comfortable and peaceful resting place for her.
Dear +++_______+++ is exactly the one to suit her as companion, so feeling and exercised,
weighty in spirit, just what _our elders ought to be._

[.signed-section-signature]
L+++.+++ A. Barclay.

[.letter-heading]
To +++_______+++

[.signed-section-context-open]
2nd of 11th Month, 1850.

[.salutation]
My Dear Friend,

I hope I am not too late in saying I rejoice in thy prospect, my beloved sister,
and wish thee God`'s heavenly speed on thy way _most heartily!_
In one sense, I do not see thou art so much to be pitied,
for thou hast such a valuable helper in thy dear husband; but I know what thou means.
Alas! those who go forth now-a-days at their Divine Master`'s bidding,
have need in a _deeper_ sense to be both pitied and prayed for,
for they must be where their Master is in deep suffering, and, as it were, buffeted,
and derided, and beaten,
and crucified! but it is enough for them that they be as their Master; yea,
it is their honour, and let them count it all joy thus to suffer with Him,
notwithstanding that mourning and grief is their clothing on behalf of those they visit,
that they should thus be crucifying afresh, as it were, the Lord of life and glory!

But, my dear friend, never fear the sufferings, the despising, the reproaches,
and evil reports, rather fear the favour and the flattery, or warm expressions of any,
even when well meant.
The Lord whom thou desires to serve in faithfulness and truth, will strengthen, guide,
and preserve thee as thou cleaves close to His pure gift and only leans on Him,
and He will help thee over all the close places,
and hard pinches thou must bear and go through, if thou speaks faithfully for Him.
And mayest thou not be dismayed, if low places and deep baptisms be thy portion;
it must be so, if ever thou art enabled to minister aright to the true seed,
or to bring up stones of memorial unto the Lord`'s power and goodness.
Oh, mayest thou never shrink from inwardness and silence
in the social intercourse connected with this service,
nor be ashamed of having nothing to say in little opportunities--but mayest thou,
by example as well as precept,
draw the professors of the pure truth into more inwardness, and silence,
and watching unto the word within, which is sadly wanted amongst us.
I was greatly instructed in seeing this godly example in dear +++_______+++ and +++_______+++.

May I, in sisterly freedom, suggest thy reading my little tract from Job Scott,
addressed to select Friends; it may have a strengthening effect--I feel it has on me,
and like to read it every year,
tending to strengthen me in keeping close to the Divine gift,
not to launch forth into the mixture by many words which deaden the gift,
as so many do now-a-days.
I hope, though thou may not visit families in other meetings, yet that,
if thou feels anything on thy mind to any individuals or single families,
thou wilt be faithful and let nothing slip by being left undone wherever thou art.
I should like to have a little idea of thy route.
I suppose beginning with home duties first; and I shall tenderly sympathise with thee,
and, as enabled, breathe for thy help and preservation!

Thou wilt say perhaps I have reason to be encouraged in
meeting with such tender-minded ones as the three here,
whom I mentioned in my last,
and especially so in their so rejoicing in my coming here _just now_ with
the object of encouraging them to sit down together for worship weekly,
saying it was what they so desired, and it was _providential._
But what wilt thou say when I tell thee that one of these told us,
that +++_______+++ had advised their beginning their little meetings with the Scriptures?
This dear young man told us _this_ would not do,
for reading the Bible was no _part of true worship!_
But we perceive an inclination to it in the other two;
I must do my best to counteract it,
and try to leave them on second day week in as good a way as I can,
recommending them to their Divine Teacher, who speaks as no man spake!

And now farewell, in much dear love to you both.
May the Lord help and preserve is the desire of thy affectionate friend,

[.signed-section-signature]
L+++.+++ A. Barclay.

[.letter-heading]
To +++_______+++

[.signed-section-context-open]
Aberdeen, 20th of 11th Month, 1850.

[.salutation]
My Dear Friend,

When you have decided on your future abode I shall be pleased to hear of it,
and feel much for you in the unsettlement that you have so long felt,
it must be so trying.
If trials of this sort are not brought on by a want
of close attention to the good and sure Guide,
speaking and showing in the secret of the heart,
then we may have a humble confidence that they are among the "`all
things that shall work together for good,`" and shall feel the
supporting Arm near to sustain and comfort us;
and if, upon a close scrutiny,
we find that they are the result of this want of close care on our parts, then,
although we may and must feel a degree of self-condemnation,
let it lead us not to despair or discouragement on the one hand,
nor to a doubting about or slighting of inward guidance on the other,
but to a humble sense of our own deficiency, and a desire after a closer watchfulness,
a simpler faithfulness for the future, with a seeking after best help therefor.
And thus our very slips and the trials incident thereto may be made helpful,
or rather overruled for good to us, in making us more watchful and humble.
I don`'t know that these remarks apply to you,
but as they came into my mind I simply pen them, and am myself instructed in doing so.

The present is a time when, if persons can possibly do on a little out of business,
it is better, rather than to run the risk of losing all by seeking more.
The present is such a time of running to and fro by some,
and there seems such a vast deal of good afloat,
that one longs to see more of good fruit and conversion result therefrom.
It is a time wherein I am not (and shall not be) surprised, if the little ones,
the true-hearted and deeply-baptised servants,
should either be restrained from travelling, or else, if led out,
may be required to be much in silence, as a sign to the empty professors of truth,
who are too much clothing themselves with a fair looking covering,
but not of the Divine Spirit.
There is more of drawing folks, especially the young,
to the creature instead of to their Creator and heavenly King,
and the superficiality begets superficiality, so there is (comparatively,
with all the many words and much labour) but little
turning of the wicked from their evil way,
or strengthening the hands of the faithful.
See Jeremiah and Ezekiel.

[.signed-section-closing]
With dear love, I will remain thy very sincere friend,

[.signed-section-signature]
L+++.+++ A. Barclay.

[.letter-heading]
To W. H., Jun.

[.signed-section-context-open]
Aberdeen, 26th of 12th Month, 1850.

[.salutation]
My Dear Friend,

Oh! how excellent is the true unity--surely as precious
ointment that is healing and strengthening and reviving.
And such I seem to feel renewedly poured forth,
in the reading of thy acceptable letter of 10th month last,
to the melting of my heart in grateful praise to the great Giver of,
and Strengthener unto all that is good.
The feelings and the exercises,
and even the trials of such seem to be like face answering to face in a glass,
and seem by the sight or hearing thereof to animate
one afresh to travel on and press forward,
and look upward in and over all.

Thou speakest of the difficulty thou sometimes feelest in writing.
I sometimes, when thus fearing my letters are poor and worth nothing,
feel _the more_ bound to send them, and appear as a fool and weak;
and sometimes I have for answers an account of their
applicability and helpfulness at that very time,
which is an encouragement just to pen as matter opens on the mind,
and without any reasoning or garnishing.

My dear friend, how well can I enter into and respond to thy expressions as to thyself!
Surely it is a time to cry and breathe day and night
to the alone Preserver and Strengthener of His people,
to keep us from falling into one or other of the wily enemy`'s specious snares,
and to strengthen us to be faithful unto Him,
doing neither more nor less than He requires of us.
And surely, seeing we feel ourselves such poor weak children,
will He not condescend to take us as by the hand, and keep us close to Himself, yea,
and answer the breathings that He puts into us?
And, oh, saith my soul, on my own account, may He take me away,
rather than that I should live to bring the least hurt or reproach
to that cause which He has made so precious to me.
My mind has been of late much pondering and exercised, I think I may say,
on the state of things in the world at large, both on your continent and in this land,
and also amongst us--a highly favoured yet backsliding people.

The Papists are _exulting_ in their rapid increase everywhere,
and in the hope of an entire subjugation of this nation to papal government.
At one of the late meetings on the subject,
the Dean of Bristol seemed to speak strikingly,
showing the degeneracy that had crept over all denominations,
and that there was wanting a purging from Papacy--not Roman Papacy, he said,
but Anglo-Papacy,
which had crept up amongst all sorts (alas! how true is this as it regards our Friends),
and especially the clergy, and that this purging would come from the laity.
And he quoted from one of the early Christians (Ambrose),
that "`there never was a heresy in the Church but it came by way of the clergy,`" etc.
I was much struck with these views, and from such an one,
and it coincides with that text,
"`The leaders of this people cause them to err;`" and I
was reminded herein of Archbishop Usher`'s remarkable prophecy,
mentioned in the preface of [.book-title]#Sewell`'s History;# also of another,
supposed to have been delivered by Lawford Godfrey, a Friend,
and minister of Exeter early in the last century.
The last peculiarly shows the purification of the ministry, and is awful to think of.
And yet there is much comfort in the assurance that the
pure gold and the weighty wheat shall not be hurt,
and that Zion shall arise and shine forth more brightly,
and that "`truth is stronger than all,
and shall prevail,`" as dear old William Rickman said to me on his deathbed.
So let us cheer up through all our tears and sighing,
and hope for the glory of God through all and over all--and He will preserve the simple,
the faithful, and the humble we know.
And, oh, let us seek to be of such, by cleaving to His power, which can make us so.

And now, my dear friend, I have written thee many words,
but I fear a poor letter as to substance--it`'s the
best my poor treasury can furnish at present,
being in a very low and stripped spot;
but sometimes am deriving a little comfort or hope from the full belief
that I do love the brethren who love the Lord Jesus Christ in sincerity,
and manifest it by their faithfulness and humility.
Thy writing to me as thou feelest a little gentle putting forth in love and life,
not looking for great things, will be truly acceptable,
and no doubt helpful and cheering to thy poor tribulated but affectionate friend,

[.signed-section-signature]
L+++.+++ A. Barclay.

[.letter-heading]
To +++_______+++

[.signed-section-context-open]
Aberdeen, 16th of 1st Month, 1851.

[.salutation]
My Dear Friend,

The re-perusal of thy kind letter a month`'s date ago,
fills me with wonder that thou shouldst write of riches
to one so miserably poor as I feel myself to be;
it is like speaking about summer to one in the depth of winter,
or about dainty morsels to one in a starving condition.
It has been with me a long season of mental starvation, or rather, I should say,
of apparent darkness and desertion;
and what so afflicting as the loss of the precious company
and converse of Him who is the beloved of redeeming souls,
of those whom He has touched with His love, and given to feel that "`sweet is His voice,
and His countenance is comely!`"
I desire to be resigned to this winter season,
remembering that man shall not live by bread alone
(by that which looks likely to nourish him),
but by every word of God, even by the judgment of His mouth, the commands of His Spirit,
the permissions of His will, however stripping, however crucifying,
however close and hewing; even afflictions, and overcomings of the enemy,
may tend in some degree to the strengthening the best life,
by drawing us more inward--"`by these things men live,
and in all these things is the life of my spirit,`" said Hezekiah, when pushed sore.

We have been favoured to have continued comfortable
accounts of the little meeting at +++_______+++ and +++_______+++;
one simple man writes, they had had "`a blessed meeting,`" on first day week in silence.
I long for their help and holding on, and we write to one or another of them occasionally.
// lint-disable invalid-characters ""
I am having four tracts (two of Patrick Livingstone`'s) printed in the Glic language,
for spreading in the Highlands, either by myself, if spared to go there,
or by any who come after me, perhaps at public meetings; but oh,
the self-sufficiency and lukewarmness here! when will the truth arise and shine over all?

I fear this is a poor dull scrawl, dear +++_______+++,
but thou takes me for better and for worse.
With dear love, I remain thy true friend,

[.signed-section-signature]
L+++.+++ A. Barclay.

[.letter-heading]
To Sarah +++_______+++

[.signed-section-context-open]
Aberdeen, 21st of 1st Month, 1851.

[.salutation]
My Dear Friend,

I was pleased to hear from thee and of your quarterly meeting,
at which time my mind seemed much with you.
Thy former one of 10th month, informed me of the decease of thy dear uncle.
It was sweet to me to hear of his apparent preparation and readiness to depart,
like one going a journey.
I thought it showed the work of the Divine power, that thus gave quiet and a humble trust.
He was one of the hidden worthies who I believe endeavoured
to do what he knew to be right,
and I felt his loss for +++_______+++,
for there are but few comparatively of the true Friends in it.
Still I believe amongst those not of this fold there
are of the upright-hearted or righteous in it,
and we read that for ten righteous persons Sodom would not have been destroyed.

I have been very low, truly of the poor and needy ones,
and ready to think no one so tried and bad as I. But, dear Sarah,
to feel a panting after the water brooks is a sign of a little life, is it not?
and to be sensible of the darkness and distress of desertion is a sign of a little light,
for it is the light that manifests the darkness, is it not?
So I travel on in fear, and hope for better days, and the language of my heart is

[verse]
____
"`If I am right, thy grace impart
Still in the right to stay;
If I am wrong, oh teach my heart
To find that better way.`"
____

If such seasons are designed for proving and refining,
may patience have her perfect work,
that nothing may be wanting that tends to the glory
of the Creator and the utter abasement of the creature.
We are variously afflicted, and the good hand is laid upon us,
but all for our spiritual help; and, oh, that we may so receive the chastening,
and abide under it as to obtain the help designed towards heaven.

Thy description of the enjoyment of your country was very touching to me,
reminding me of past days in a south land.
Still I desire to be resigned to the trials of my northern home as long as required.

Farewell.
With dear love to you both, from thy affectionate friend,

[.signed-section-signature]
L+++.+++ A. Barclay.

[.letter-heading]
To Hannah Marsh

[.signed-section-context-open]
Aberdeen, 29th of 1st Month, 1851.

[.salutation]
My Beloved Friend,

When we feel drawn nearer and nearer to our friends by reason of losing others,
and thus being reminded afresh how precious they are,
we seem as if our minds continually were as on the wing to them,
and communicating in a hidden way with them, and we want to tell them so.

Ah, thine was a touching allusion to happy hours in W.,
and I may also add P. and C. with you;
but He who mercifully gave such good and precious times together,
is as near now as ever to bless us and do us good, yea,
to support us still under the troubles and tribulations of time,
and to guide and strengthen us still in what He requires,
and to comfort us in all our losses and afflictions and sufferings for His sake.
Therefore let us still pour out our souls unto Him,
and He will be a sure refuge and peaceful little sanctuary
unto us in the places where our lots may be cast,
and under whatever provings He appoints--let us trust in the Lord Jehovah forever,
for in Him is everlasting strength,
and none of them that trust in Him shall be desolate--let Him strip us, as it were,
quite naked, only not take His Holy Spirit from us,
nor suffer the enemy to draw us aside.

I think I gave thee a hint in my last,
how my mind had been attracted towards those who attend our meetings not members.
I was constrained last monthly meeting to avow it,
and was liberated to visit them individually, which,
through Divine goodness humbling and helping,
I have been enabled to do in about sixteen sittings,
to the great relief and comfort of my mind.
My bodily health was much stressed upon with the exercise, especially in anticipation,
for it was a trial to me to avow it.

[.signed-section-signature]
L+++.+++ A. Barclay.

[.letter-heading]
To +++_______+++

[.signed-section-context-open]
Aberdeen, 12th of 2nd Month, 1851.

[.salutation]
My Dear Friend,

I am much obliged for and interested in thy account of your German journey;
it must have been very pleasant going together,
and what a _great favour_ you were helped through so well,
and were preserved from all accidents and illness,
for I had many fears about your being either of you taken ill!
Surely it will be a time to be often remembered with sweetness, gratitude, and praise;
and I trust desires will renewedly arise after greater degrees of love, trust,
and dedication to Him who has thus been mindful of you to bless us.
I was so pleased that +++_______+++`'s two brothers were alive and glad to see him--also
that you went to Oberkirchen to see that nice little company of whom I had heard,
and towards whom I often felt much love!
I hope you had a good supply of German tracts to spread.
Ah, I wish G. would translate some real old-fashioned ones into German,
to spread the ancient and unchangeable truth!
I trust the visit may be as the prophet`'s cake of old,
that helped him over a long wilderness travel.

Farewell, dear +++_______+++. With dear love to you both and dear +++_______+++ also,
I remain thy affectionate friend,

[.signed-section-signature]
L+++.+++ A. Barclay.

[.letter-heading]
To R. R.

[.signed-section-context-open]
Castleton of Bremar, 1st of 7th Month, 1851.

I thought of thee and others too, last sixth day, at Dorking quarterly meeting,
as I was rapidly travelling away from England.
Home is home, however solitary and trying; the mind rests there in the place allotted us,
if it be in right ordering.
How super-excellent then would be the heavenly home,
and to be made a pillar in the Lord`'s house that shall go no more out.

Yesterday we had a most wild mountainous ride here, in an open barouche,
along the Queen`'s Road,
winding up the mountain and in and out the many romantic
gullies or dells--a _majestic_ scene,
and a _vast change_ from the richer and softer beauties of Surrey; a narrow road,
and nothing to prevent our rolling down the precipice, had our _ponies_ slipped,
or turned aside too much in their windings;
and in the far distance there _really_ is snow in the recesses of the mountains, and,
as I sit, I can see them twenty miles off,
and of a glistening or silvery whiteness by the sun shining on them.
It is strange to see snow when we are oppressed with heat.
But, whilst we were at dinner a little while ago,
soon after admiring this silvery appearance, it changed to blackness,
and a severe storm of thunder and lightning came on; it was a treat to me,
though awful to behold, for we never hardly have thunder at Aberdeen.
This is a simple place of thatched cottages chiefly,
including the shops and lodging-houses.

I much felt seeing so little of you, and oh,
that we may seek daily after that life which is hid with Christ in God.

[.signed-section-signature]
L+++.+++ A. Barclay.
