== Chapter XVII

To S. H.

Aberdeen, 6th of 1st Month, 1853.

Dear S.,

I feel for the poor +++_______+++s, and must write to them when my mind is more relieved.
At present it is much weighed down,
and I feel in a very exercised and stripped state
in the prospect of holding a public meeting here,
on third day evening, for some of the factory girls in this large city,
those who have lived more in our late neighbourhood, and I feel but a poor weak child,
and truly have no might of my own.
But I desire to look to and lean on Him alone,
in whom is everlasting strength and wisdom; and if He will but be with me,
keep me from wrong fear, and close unto His pure gift of light and life,
that I may not bring the least hurt to His blessed cause,
but may be enabled to exalt and spread His holy name,
and testify and direct unto His heavenly power revealed in their hearts,
it will be indeed a great favour, and what I earnestly desire.
It has been a time of deep feeling lately for the state of these high professing people,
for they are wholly given up to revellings, drinking,
and pleasures at this time for a week or more,
not only men but women also and even children, lads and lasses drinking spirits sadly,
even to intoxication;
and I fear that many hundreds have the seeds sown
annually of disease of body and misery of soul,
which is shocking to think of.

Farewell, in dear love to you both.

L+++.+++ A. Barclay.

To +++_______+++

Aberdeen, 6th of 1st Month, 1853.

My Dear Friend,

I am pleased to tell thee we were encouraged to hear
that the intoxication and noise in our streets,
the first three days of this year were far less than usual this time,
so we must be faithful in scattering seed, as it were, and not withhold our hand,
must we not?
I admire dear +++_______+++`'s courage following after the market
carts along the four entrance roads to this city,
to give the temperance tract,
called "`New-Year`'s Day in Scotland,`" of which we had 600 by post for the purpose;
and this led to numbers of foot passengers in the streets running after her for more,
and crowds of children for "`bookies;`" but she was well received everywhere,
and feared no one!
// lint-disable invalid-characters "æ"
She is perseveringly teaching herself Gælic, and is already able to revise my tracts,
so that I am soon going to press with three more narrative tracts,
which I have long wished for.

Now, I must say farewell, with dear love, desiring that we may be afresh stimulated,
by the favours and mercies of the past year,
in humble watchfulness and grateful faithfulness to the measure
of the Divine gift of light and life in the secret of our hearts,
that so we may be preserved from all evil,
and strengthened unto that which is good and well-pleasing in the Divine sight,
through Jesus Christ our Lord.
I remain thy affectionate friend,

L+++.+++ A. Barclay.

To +++_______+++

Victoria Street, Aberdeen, 14th of 1st Month, 1853.

Dear Friend,

I quite united with thy remarks on the state of things amongst us,
and it was a comfort to me that thou wast given to feel so,
and I desire thy encouragement in yielding to inward feeling;
for in our solitary moments, when we have none congenial around us,
then is it often the case that Divine goodness favours
us with heavenly refreshings from His presence,
as well as reveals many things to us respecting His Church and people and our own states;
for His secrets are with those who fear Him, for our instruction, humbling,
strengthening,
and comfort--and may we seek to dwell low with the revealing power and follow His counsel.
I think thou art favoured in being so retired from the sight,
and perhaps hearing of many trying things in our poor society,
and I can`'t but feel and see that the real true Friends are becoming
more and more solitary and tried by being stripped of helps,
whether as thou sayest by death or desertion;
but good is the hand of the Lord that is thus laid upon us,
and all His dealings are for our good, and His holy "`foundation stands sure,
having this seal the Lord knoweth them that are His`"--and knowing them,
will sustain and strengthen them to the end,
as they cling close unto Him and turn not aside from
a steadfast faith in His secret power!

With love, thy friend sincerely,

L+++.+++ A. Barclay.

To +++_______+++

Aberdeen, 5th of 2nd Month, 1853.

My Dear Friend,

I was much pleased to receive thy circumstantial account in thy last letter;
it was so clear to my unbusiness-like comprehension,
and as I had laid out in my heart the enclosed sum,
I send it for thy acceptance--it will be a little forward help.
Thou knowest we must not withhold good when it is in the power of our hand to do it,
not knowing what the future may bring forth.
And I hope, my dear friend,
thou wilt not have any uncomfortable feelings in receiving through me,
for it is no more than my duty to the Giver of all good,
as it is also a pleasure towards thee,
believing thee to be one desiring to be of the number
of the Lord`'s humble and faithful ones,
serving Him in uprightness of heart; and oh, saith my soul, that thou, as well as myself,
may be preserved to the end to and in that blessed principle of light, life,
and truth revealed within,
whereby and whereinto the Lord in His tender mercy and mighty power hath gathered us,
that so we may be His forever.

I quite admire thy preference of keeping in a safe little way, as thou describes;
far better to do so than to run risks of hurting thyself either temporally or spiritually,
or both, by seeking to increase business imprudently.
I believe Friends should be a little people,
and not so vastly rich and grasping as they too often are now.
Alas! notwithstanding all our high pretensions,
we are no way hardly different from the world in our business dealings;
but there are a few faithful ones left,
and I long these may be increased and encouraged to persevere,
that they may draw others to the same restraining and guiding,
strengthening and blessing Power.

I remain thy affectionate friend,

L+++.+++ A. Barclay.

To A. C.

Aberdeen, 9th of 2nd Month, 1853.

My Dear Friend,

I return thee the Peace paper herewith;
it is not a society that I have ever felt comfortable to subscribe to,
although I greatly desire the promotion of universal peace.
I think, with Robert Barclay,
that until people are brought under the government of the Spirit of Christ,
that they cannot see rightly into the matter,
nor be enabled to stand and act faithfully and consistently with it.
Nevertheless,
I think it well that the subject should be spread by tracts as much as possible.

I am made sad this morning at receiving an account
of the death of dear +++_______+++ of +++_______+++,
faithful elder and father in the truth,
lively and savoury in his communications and exercise therefor,
and who will be greatly missed.
His poor wife was strengthened to express something at the interment.
"`The fathers where are they, and the prophets do they live forever?`"
But the Lord is the never-failing refuge and strength of His true-hearted little ones;
though the mountains be removed and the waves roar and be troubled,
there is still as ever a river whose streams make
glad at seasons the tabernacles of the Most High,
however solitary they may be, and the subjects of deep suffering.
These citizens of Zion shall know that God is in the midst of her,
and will in His due time help her,
as they are concerned to seek after that stillness of the creature,
wherein He alone may be exalted over all in them.
Still it makes me sad at heart to think of the right
sort being taken away from us at such a time.

My dear friend,
thy sweet lines of encouragement and exhortation felt truly helpful to my tried mind,
which is very low just now,
and I long that I may have not only thy sympathy but thy prayers, as enabled from above,
for my preservation and help to be faithful.

Our monthly meeting occurred here on fourth day,
at which I was liberated to visit meetings and families as way opens for it in Cornwall,
and to attend Dublin yearly meeting, with a few meetings in the way.

In near and dear love, and hoping to hear again soon, I remain thy affectionate friend,

L+++.+++ A. Barclay.

To W. H.

Aberdeen, 24th of 2nd Month, 1853.

My Dear Friend,

Thy kind letter of 17th of 12th month was thrice welcome,
and has many a time both cheered and encouraged me
in my many and mournful downsittings this winter.
I felt it truly brotherly, both in its freedom and confidence,
as well as in a more spiritual sense;
showing forth a being baptised together into one spirit--and I
do trust and humbly hope that is by and into the Spirit of Christ;
at least, it is the utmost of my earnest desire for my poor self.
And oh, my dear friend,
words fail me to set forth the fervent breathings that have been raised in me,
this wintry season, for myself,
and for the remnant that is left amongst us true-hearted to the ancient cause,
wherever scattered, that the Lord may be pleased to be near,
and to comfort us in all our afflictions,
to strengthen us unto all He requires at our hands,
to humble and preserve us amidst all the snares of
the wicked one that may attend our path;
yea, that He would be pleased ever to keep us to and in that blessed principle of light,
life, and truth,
whereby and whereinto His tender mercy and His mighty power hath gathered us;
that so we may be kept His, and for Him to the end here,
and may be graciously permitted to be His hereafter, to a never ending eternity.

I say wintry season; for never, I think,
have I had to pass through such a winter as this, both in an outward and inward sense;
and the fear has been great of making shipwreck of faith and a good conscience,
and bringing any reproach on that blessed cause, which, if I know my poor heart,
is truly precious to me--more than the natural life.
Mind and body are sympathetic, and when the Beloved of the soul seems also to be removed,
as into a far country, the enemy`'s buffetings and temptations are increased.
Surely, then, we are in a pitiable and afflicted condition--a wintry season indeed.
But why should I set forth such a low state to thee?
except perhaps it may convince thee, at a similar time of trial,
that thou hast only "`neighbour`'s fare,`" and so thou mayest lay hold of a little hope,
and cast not away thy confidence in His mercy, who,
though He prove and pinch very sorely, and strip as it were entirely,
yet will not forsake His redeeming ones in their lowest seasons,
whom He is refining because He loves them; but His arm of support will be underneath,
though in a hidden manner;
and in His own good time He will say to the overwhelming waves, "`Peace,
be still,`" and to the furious fire, "`It is enough.`"
During this time of trial, I greatly felt the loneliness, the fewness of fellow-feelers,
and the wound of dear John Harrison`'s death seemed again opened,
and it was then that thy brotherly letter seemed so helpful and strengthening,
through Divine favour.
Still,
I can with thee bless the Hand that took him away from the evil and temptation to come.
Oh, far better for the work to be cut short in righteousness,
than to live to dishonour the great Name which we have taken into our mouths!

Again was I afflicted in sympathy lately for dear
John Wilbur`'s great loss +++[+++of his wife];
but had such a feeling, such a noble letter from him in allusion to it,
and informing me also of the exercise of his mind towards the scattered
ones in New York State and some parts of your yearly meeting,
that my tears are turned into secret songs of praise
to Him who supports His little ones so wonderfully,
and strengthens in the midst of affliction to offer a meat-offering
and a drink-offering unto the Lord their God!
I hope thou wilt write me of his movements and reception while within your limits.
My tender feeling is towards him and breathing for him, that he may be guided,
strengthened, humbled, and preserved from day to day,
and helped over the deep exercises and proving duties
that must await him in such an engagement,
and favoured to return with relief and peace of mind, giving God the glory.

My dear love to thy wife;
and I can feelingly unite in your grateful feelings to the Giver of health, life,
and every blessing.
And oh, dear friends, let us not be slow to offer the sacrifices of thanksgiving,
and pay our vows unto Him who is so tender and good
unto us! what shall we not render unto Him?
But what am I thus to open my mouth to a dear fellow traveller?
for, alas!
I am but a poor lag-behind, and have a great need to be stirred up.

Last month I held a public meeting here for the factory
girls of three of our large factories.
It was, through mercy, a time of a little relief to my burdened mind,
but I was much plunged afterwards.
No matter how much we are humbled and stripped, if we are but saved from ourselves,
as dear John used to say.
We have been reading, with fresh enjoyment and instruction, his manuscript letters,
which I have of my own.
Ah, he had to pass through the fiery furnace continually;
but the work was cut short in righteousness, and he was taken from the evil to come;
for how has his testimony been trampled under foot,
and how has our poor society hereaway greatly declined since then!
His remarks on our state, and what we might expect, are very good and wholly verified.

And now, my dear friend, I must close this long epistle,
which I fear has wearied thy eyes to read; and, with the salutation of endeared love,
I remain thy sincere and affectionate friend,
desiring that the Lord may have us in His holy keeping,
support through the remaining tribulations and sufferings of our day,
enable us to be faithful to Him to the end, and preserve us in deep humility forever!

L+++.+++ A. Barclay.

To +++_______+++

3rd Month, 1853.

+++[+++Alluding to the decease of J. H., Lydia A. Barclay writes]

I know the Lord can raise up others in His life and Spirit, if He see meet,
to lift up the standard of truth; and even if we, as a society,
should be broken to pieces and trampled under feet,
yet the blessed truth shall outlive all.
It is my belief that, as the testimonies delivered to us to be upheld,
are no cunningly devised fables, but the real testimonies of Christ,
who speaks the same language in all ages,
so should we go from them by unfaithfulness and let them fall,
yet God will raise up others to uphold them in life, and power, and purity,
to the glory of His great name!
In this I rejoice and rest in hope,
and reach forth in spirit to that brighter day coming,
trusting in the Lord`'s tender arm for support, during the time of sifting and shaking,
believing He will yet bring His little faithful ones through all their tribulations,
and give them to sing His high praises on the banks of deliverance.

L+++.+++ A. Barclay.

To S. H.

Aberdeen, 17th of 3rd Month, 1853.

My Dear Friend,

I have greatly felt dear J. Dann`'s decease, though it is what I have long expected,
and when I last parted with him I did not think I should see him again.
It has been a great favour to him that he had so long a time to ripen for heaven;
we do not know that we may have such an one.
It is truly awful, and ought to be closely warning,
the many deaths of late among such as we know, and some who filled conspicuous places.
Last First day week there were four women Friends, ministers, lying corpses, viz.,
Ann Lucas, M. Sterry, Susanna Haworth, and Ann Priestman,
and we know not whose turn may come the next.
I wish that the loss of J. Dann may stir up some in your
monthly meeting closely to see whose side they are on,
whether the side of the truth, or the side of the world and the enemy,
and to look well whether the call be not again going
forth to them to loosen from the latter,
and to devote themselves more fully to the former,
and not to shrink from showing themselves, desiring to be on the Lord`'s side,
by wearing His livery and serving Him faithfully,
for it is high time for them to awake out of sleep, even the sleep of death,
to gird themselves or suffer themselves to be girded by the Lord`'s strength and power,
and to follow Him, otherwise He will cast them off forever.

And I earnestly desire also, that you, my endeared friends,
may stir up the gift that is mercifully permitted, and be faithful for your Lord,
and bold and valiant for His holy cause,
in the simplicity and humility of a little child, fearing and looking at no one,
but only your Divine Master, whom may it be your delight, your meat and drink to obey,
and do not doubt about the little pointings of truth in your minds,
nor yet reason them away, but believe in them and yield to them,
trusting your all with and unto Him who never yet failed
or forsook His little dependent and obedient ones,
but His hand is full of blessings for them.

With dear love to you both, as ever thy friend sincerely,

L+++.+++ A. Barclay.

To a Young Friend.

Aberdeen, 22nd of 3rd Month, 1853.

My Dear +++_______+++,

Feeling my head a little better this morning,
I incline to give thee a little affectionate greeting in thy mother`'s envelope,
after thy kind letter last month, which contained much to interest us.
It is a most wintry morning, the snow falling and driving fast,
and I feel the blessing of having nothing to go out
of a snug and comfortable house for on such a day,
as also that we have coals now,
for we were a fortnight lately very anxious about our fires,
our coals were very nearly out and none to be had in the town.
It was then we felt humblingly our entire dependence
on a gracious Providence for all our blessings,
and oh, how good is it to be kept as well as made so continually.
The wind changed just as we were out,
and twenty ships came in with coals which were eagerly seized upon the moment they came.
One of our attenders of meeting, a nice diffident widow,
was actually without a morsel of coal during two whole days
of the piercing snow storm--she and her three children,
one of the little ones just recovered from the scarlet fever and very delicate;
it was accidentally found out,
and a subscription got to send her a boll of coal directly.
The poor here will never hardly make known their want, for fear of troubling.

Last fourth day we set out with our dear old widow
friends to go to our monthly meeting at Kinmuck,
for the snow was but slight that had then fallen here and soon
melted--but when we got to a mile and a half from Kinmuck,
we stuck fast in a snow drift, and could not go further, to our great disappointment!
It happened providentially to be not far from a farm-house,
so the farmer and his sister came and helped the old friends
to wade through the snow knee-deep to the house,
and the driver took the horses to the stable, as much as he could manage to hold them,
and A. G. and I sat still in the fly; then, with the help of the farmer, his spade,
and his cart horse, they took off the pole,
and turned the fly round with us two in it and when
our friends and the horses were brought back,
we again travelled home, minus our dinner, but thankful that we had had no accident.

L+++.+++ A. Barclay.

To Hannah Marsh

Aberdeen, 22nd of 3rd Month, 1853.

+++_______+++ is a great comfort to me spiritually in feeling with me.
I rejoice in her tract giving,
and having often nice opportunities of pleading for truth in giving them,
striking times often; and she feels so tenderly interested about the seamen, as I do,
and we are hoping to be able to get them a life-boat,
with apparatus for casting ropes over wrecks.
I have had it at heart all winter,
and now hope it will be accomplished in a few weeks`' time.
I have got seventy pounds for it from divers, and it is to be at my disposal.
I trust it will be a blessing to this port,
and the dear sailors are so rejoiced in hopes of it.

I am more inclined to take a journey into the Highlands this summer,
// lint-disable invalid-characters "æ"
and strew seed there by the Gælic tracts I am having printed,
than to go to yearly meeting when my health is weaker, my ears more deaf;
whereas I have long had the former at heart and been hitherto hindered;
and now dear +++_______+++ seems given to help me to get rid of the burden,
and her heart is in it also, and I know not that I shall have another opportunity.

L+++.+++ A. Barclay.

To +++_______+++

Aberfeldie, 17th of 5th Month, 1853.

My Dear Friend,

Thy kind sisterly epistle came very acceptably just before we left Edinburgh,
and as thou expressed a wish that I would write thee while thou art at yearly meeting,
I take pen this afternoon,
as +++_______+++ is gone out to distribute tracts from house to house in this nice little town,
thirty miles north of Perth, and in the Highlands.
Oh, how I seemed with you in mind this morning,
between half-past nine and eleven o`'clock,
as I sat by the side of the very beautiful Loch Tay (six miles from here),
embosomed in trees,
and looking many miles up the lake at a beautiful
mountain between three and four thousand feet high,
and whose top is covered with snow,
called Ben Lawers! my mind seemed to wander from these outward
beauties to the site of Devonshire house in the heart of London,
where so many are now collected of our highly professing people--many with the appearance,
and many I trust also with the desire of attending to the affairs of the blessed truth,
the inward and spiritual kingdom of our holy Saviour--but may I not add few comparatively,
whose eyes have been anointed to see, like poor Jeremiah,
the abominations and deeds of darkness that are doing by the elders of Israel.
But I do hope, as these sad things become more manifested,
that the eyes of many will be opened to see, and their hearts touched to lament them,
and their spirits stirred up to do their utmost in faithfulness and in deep humility,
and in the meekness of heavenly wisdom to counteract these things, to stem the torrent,
and to plead for Christ their Master before an evil and adulterous generation.
May the Lord help you of the little faithful ones to do
your part and preserve you from the fear of man,
"`fear thou none of their faces, neither be afraid of their words,
though they be a rebellious house, and though briers and thorns be with thee,
and thou dwell among scorpions.`"

Oh, what responsibility rests upon us, if a sight and sense of evil is given us,
and a call to sound an alarm or to reprove in the gate!
Oh, may we be enabled to go simply forward, according to the Lord`'s pointings,
and heed not the reasoning of the enemy,
for there surely shall come a time when the terrible ones
shall be brought to nought and the scorner consumed,
and all that watch for iniquity shall be cut off, that make man an offender for a word,
and lay a snare for him that reproveth in the gate,
and turn aside the just for a thing of nought.
"`And in that day shall the deaf hear the words of the book,
and the eyes of the blind shall see out of obscurity;
the meek also shall increase their joy in the Lord,
and the poor among men shall rejoice in the Holy One of Israel.`"

+++_______+++ took up what I said in our general meeting against the exclusion of servants
in the third answer (which some of our members said only refers to such as are Friends),
and so it was put in,
and we both bore our testimony that the query refers to our promotion of religion,
by example and precept, both among those who are Friends and not Friends under our care.
I had a very exercising time,
having to go into the men`'s meeting with a very close little testimony,
and it was also to be borne in our women`'s; but I was mercifully favoured with peace,
which was all I coveted, and more than gold or silver or praise of man.

L+++.+++ A. Barclay.

To P. M.

Aberdeen, 10th of 6th Month, 1853.

Dear Friend,

I write to let thee and your other two friends know
that J. L. is intending to visit our meetings.
We expect him and his companion here on second day in next week,
and they hope to be with you on fourth day, the 15th instant, at about six o`'clock,
and they wish to have a meeting with you in your parlour that evening;
and if you are inclined to invite a few more, they have no objection.
Of course you will name to M. L.,
and I was thinking that solid-looking Methodist and
her husband would perhaps like to come;
and, dear friend, don`'t withhold from asking any thy mind inclines to ask, that is,
as far as you can accommodate with seats,
for if we feel the preciousness of the principles of truth,
we should be glad to invite others to come, and either feel or hear testify of them too.
Could you not put a few chairs in the opposite room or the forms,
in case of more being wanted?
or even seats in the passage would do.

J+++.+++ L. is a plain, simple country farmer, drives his own team.
A true friend, whose company you will enjoy.
He is very deaf, worse than I am, and uses a large trumpet; he is weighty in spirit,
and very inward in mind.
They are to be my guests,
and thou may judge of my grateful feelings that we poor corner-folks
should be thus remembered and visited in our low and solitary condition,
and I feel it a great privilege to entertain the Lord`'s faithful servants.
I have not heard any outward ministry since last 9th month, when I was in London; and,
if the Lord will, I shall hope to hear this dear friend,
if he has anything given him to say, because he has a loud voice and English accent.
But, dear P., to feel united in spirit,
and to partake in his inward exercise in our meeting,
how sweet this will be and strengthening, though no word be spoken.
Oh, the unspeakably precious baptism together by and into the one Holy Spirit,
drinking into it,
as it were! what a favour to be permitted unto us poor fallen creatures by God
in His infinite compassion and mercy to us through His dear Son our Saviour!

L+++.+++ A. Barclay.

To +++_______+++

Aberdeen, 16th of 6th Month, 1853.

I may say +++_______+++ is a truly hard-working man and minister, being wholly devoted to,
and fitted by his Master for His work, which he does in great simplicity and diligence;
and, as a minister ought to be, is just like a tube,
he gives his message or testimony and then departs immediately,
without seeking for any social intercourse, which often weakens things,
and without fawning or flattering of any,
which too many do now-a-days to get esteem and agreeable favour of folks.
I could not hear a word that he said in meeting,
but was highly favoured to have three private times in which
I heard to my indescribable comfort and strengthening;
and what he said was strikingly adapted to my circumstances both present and future,
which is indeed cause for grateful praise and prostration of spirit.
I believe, my dear friends,
that the time is hastening on when we must each be willing to count the cost,
and to show ourselves on whose side we are; and oh, that we may be enabled,
in humility and patience, to go both to prison and to death with and for our dear Lord,
as all the faithful in old times were made willing to do.
I believe things are waxing worse and worse amongst us,
and we need not marvel at anything, however bad, neither be greatly moved.
Oh, no;
may we never be moved from that humble confidence which hath great recompense of reward,
and which has been given unto us through Divine mercy, for it`'s nothing of our own.
I am much obliged for thy continued and particular account of yearly meeting;
it is better than scraps.

Ah!
I think there is as much harm done by the neglecting
even to utter a few words of unity and concurrence,
with what a poor exercised one has had courage and strength to utter,
as there often is by an opposing speech.
The showing unity afterwards privately will not do;
it should be done publicly when it may vastly help
the cause and perhaps hinder a wrong step.
The accounts of thy faithfulness, my dear sister,
have been truly heart-cheering and comforting;
so we have need to think when nature shrinks from duty,
how we shall cause the hearts of the faithful to rejoice and praise the Lord,
if we endeavour to move in simplicity at the Lord`'s holy call, have we not?

L+++.+++ A. Barclay.

To R. R.

Aberdeen, 4th of 8th Month, 1853.

My Beloved Friend,

My heart is with thee in a unity and sympathy which is beyond words,
precious and strengthening,
and bowing in the humble praise of Him who can "`open and none can shut,
and shut and none can open;`" whose works only can praise Him, and they shall and must;
and in the remembrance of His goodness and mercy, surely we may cry out,
"`While I live will I praise the Lord,
I will sing praises to my God while I have my being.`"
Yes, thou wilt have to go down to the bottom of Jordan.

But the Lord will be thy strength and song and become thy salvation,
and He will enable thee to bring up stones of memorial to His praise
as thy eye and thy cry is solely and closely unto Him.
He is able to preserve still in the hollow of His hand, to guide and guard continually,
and to water every moment; and I crave that He may do so, and bring thee home in peace,
with the acknowledgment that thou hast lacked nothing.

I have been tried at times, yet have felt the good hand near to sustain, strengthen,
and comfort, and a degreed of inward peace.
How sweet it is, it makes heaven on earth and fills us with praise!

L+++.+++ A. Barclay.

To +++_______+++

Aberdeen, 27th of 10th Month, 1853.

My Dear Friend,

I was pleased to receive thy letter last night, having been anxious for it.
Ah, my dear friend,
I told thee you would find many inconsistencies if
you settled where thou wast looking at;
and thou knowest well enough there are many amongst
us who say and think they are Jews but are not,
but do lie; and these, many of them, take part in the government of the Church,
whereas they ought not to touch the ark with their unsanctified hands.
It will be so with us whilst birthright membership,
or rather birthright meddling with the discipline,
remains with us contrary to the good old way,
and the spirit of the world is suffered to prevail over us.
More is the need, therefore,
that visited minds who have been favoured with the knowledge of the blessed truth,
or the pure inward kingdom and power of the Lord Jesus Christ,
should the more cleave close to His inward revealing, guiding power,
and the less to look outward at others how or what they do.

Oh, then, my earnest desire and prayer is,
that thou and dear J. may strive to keep your eye single unto the Lord and His guiding,
strengthening power, yes, very single,
in the true uprightness to Him and His blessed and glorious cause;
thus will you be preserved from being stumbled at the failings of others, yea,
their faults will the more lead you to cling to the alone and never-failing
and all-sufficient Source of availing help--you will then not only come
up faithfully "`to the help of the Lord against the mighty,`" but also,
to the help of the little remnant of faithful Jews amongst us;
for you must perceive that there are such still in mercy left us,
even the seven thousand in Israel who are not bowing
the knee to Baal nor kissing his image;
and you must believe from all you see and hear,
that these are greatly grieved and afflicted, and, as it were,
sigh all the day long "`because of the abominations committed`" amongst us,
a so highly professing yet a backsliding people.
May you then, in unity and sympathy with them,
be constrained to join yourselves unto them,
that you may help to bear their many burdens,
thus sharing with them and their Master in the sufferings incident to the narrow way,
that you may also partake of the glory that shall
be revealed in them by their dear Master,
who is not forgetful of His faithful and suffering servants,
but has promised to set His mark on them, and to spare them as a man spareth his own son,
in the day that He maketh up His precious jewels.^
footnote:[See Ezekiel 9, Zephaniah 3:18, Malachi 3:17.]

I think thou will be able to understand my original advice to thee, viz.,
that it would be better for thee to be content with a moderate income
in the place where thou hast been called to receive the truth,
and where thou art respected, and where thy faithful, watchful,
and humble walk will be likely to do much good,
and be to the strengthening of thy own hands and that of others,
however solitary you may feel, rather than be seeking elsewhere for more getting,
and where there may be a weakening influence or a stumbling
one exercised over you by professors of the truth.
There are trials everywhere, go where we will,
and the old enemy sets his temptations and snares
even in quiet comfortable looking corners.
Farewell,

L+++.+++ A. Barclay.

To P. +++_______+++

Aberdeen, 23rd of 11th Month, 1853.

My Dear Friend,

I feel melted, I trust I may say,
under a sense of abounding goodness and unmerited mercy,
extended towards such a poor weak creature,
and only desire that I may be more and more given up to
anything that may be pointed out to me as a duty,
however humiliating!
I have at times a little faith, that He, the mighty One, will enable me, the weak one,
to do whatever He requires--and was a little encouraged
this morning in our reading in Luke 1.,
about how two poor handmaids were condescended to and honoured,
Elizabeth and Mary! and were filled with the Holy Ghost,
enabling to praise and magnify the Divine name.

Oh, how well it is, dear P., to be faithful to little pointings, however humiliating,
although we may be thought ill of for it!
I have been led to look much at the low state of things lately amongst us as a people,
and it seems as if we are more and more mingling with the sects of the world,
and becoming a sect like them,
and as the many horns that are pushing against and
opposing the kingdom of the dear Lamb of God!
I am reminded of the outer court being measured and given to the Gentiles,
and the true Church being called still more inward and deep as it were;
and how the Jews were idolizing their temple and the testimonies given them to bear,
crying "`The temple of the Lord,`" etc., extolling them in the letter or by word,
while they departed therefrom and lowered it and them in spirit!
But so the Lord departed from them!
But after refining and bringing His little remnant ("`the third part`") through the fire,
He will deliver and redeem them, and gather them home to Himself,
and He will show that He is their God and that they are His people truly.

There are two sentiments which I find are greatly gaining ground amongst us, viz.,
the discarding of birthright membership,
and the discarding of our testimony as to a peculiar appearance.
With the former I can quite unite; but I am not prepared to unite with the latter,
although I allow there is a great formality and want
of life crept up amongst us as to our plain dress,
and too much of a judging by outward appearance.
But truth will ever lead to a simplicity, and consequently to a peculiarity; for,
as the leaven of the kingdom works inwardly, it must by degrees come outward,
and thus manifest forth its working.
I was much tried to see the girls`' dress at +++_______+++ school so
altered--from the Friends`' bonnets and simple tippets or shawls,
to straw bonnets and the fashionable jackets, as I call them;
and when pouring out my sense of its being an inlet to further encroachments and inconsistencies,
to an elder, she told me that at +++_______+++ and +++_______+++ a similar change had been made!
So I was doubly tried; but came home willing to be singular from all,
and to feel and suffer in solitude.

Farewell, with dear love to you all.
The last few days of bright frost have helped me much, and, through mercy, I am well;
and hoping you are the same, I remain thy affectionate friend,

L+++.+++ A. Barclay.

To +++_______+++

Aberdeen, 17th of 11th Month, 1853.

Dear Friend,

Thy sweet note in 3rd month last was very acceptable to me,
as life answering to life through the goodness of God,
and therefore strengthening and comforting in these
days of grief for the precious truth`'s sake,
because of the treading down of the testimonies and doctrines
thereof by many of the professors among Friends.
Ah, how did I breathe to my God on your behalf while you were in our land,
and especially near London, for your preservation from being stumbled by what you saw,
heard, and felt amongst Friends,
and for the opening of your eyes to see that all are not Jews who call
themselves of the spiritual Israel--none but such as have been inwardly
baptised and circumcised by the blessed Spirit of Christ!
Ah, some of you dear simple-hearted ones may have felt the degeneracy there is amongst us,
a highly favoured, preciously visited, but a backsliding people,
not only in our practice and discipline,
but also in our ministry--for "`all is not gold that
glitters,`" as an old proverb in England says truly.
But the single eye and the simple heart of the true
babes can taste and try whence words spring from,
and they can perceive where there is a mixture of creaturely
wisdom and eloquence with the words that are spoken,
and their souls loath it in comparison of the pure streams
from the Fountain of life untainted by the creature.
Ah, my dear friend, it is only that which comes from Christ that can truly gather to Him,
or be food for the soul,
and then this will be sure to lead to His praise and the
abasement and humbling of all flesh before Him.

I am glad you went to see my dear friends, John and Hannah Marsh;
your visit was very refreshing to their tribulated spirits,
being such as are grieved for the afflictions of Joseph,
our blessed Saviour in His spiritual appearance in the heart.

L+++.+++ A. Barclay.

To +++_______+++

Aberdeen, 30th of 11th Month, 1853.

My Dear Friend,

I expect these dear friends will be returning home soon,
which no doubt will be to thy great comfort--nevertheless,
put not thy trust in the sons of men, nor in the princes even,
but lift up thy eyes unto the hills from whence cometh all sure and availing help,
even from the Lord who made heaven and earth.

I have felt a letter to thee often in my heart since receiving thy last,
but have been so much occupied, I may say pressed upon, and so poorly part of the time,
that I was constrained only to be still and to breathe for your
encouragement and help and preservation in the path of tribulation,
which you both know very well is, and ever was the path to the heavenly kingdom,
the path of the ransomed and redeemed of all generations;
for they that will live godly in Christ Jesus shall suffer persecution, it is said,
and we have no reason to expect an alteration in this permission, for if there were,
the faithful would not be manifest.

Sanctify the Lord of hosts himself, and let Him be your fear and your dread;
dread nothing so much as to lose His favour and approving smile;
fear nothing like the omission to follow as He leads you step by step.
Keep close to what the savour of the pure life in you dictates,
not looking at consequences,
and then will the Lord be unto you a precious little sanctuary indeed in all trials,
safe and sweet, quiet and peaceful.
The time is coming when we must each show ourselves on whose side we are, and, oh,
may it be on the Lord`'s side and His holy truth,
for truly it is no party that we seek to make,
but we have a secret taste and feeling of what is for the truth,
and what goes against it, and may we stand firm to truth, however hot the furnace may be.
By the faithfulness of one individual, and he or she feeling but a poor little one,
many weak ones may be strengthened and wavering ones confirmed;
and what if I say that it is possible that even some,
who ought to be as fathers and mothers,
may be helped and strengthened by their comparative children,
so it will not do to look out at others, or too much in at ourselves,
but to look upward to Him in whom is everlasting strength and wisdom, the Lord Jehovah.

L+++.+++ A. Barclay.

To +++_______+++

Aberdeen, 20th of 12th Month, 1853.

My Dear Friend,

I don`'t like to encourage idleness.
I have often feared that the poor among Friends or
attenders are not as industrious to maintain themselves,
as they might be, and as truth would lead all to be; and I think I have seen,
either in George Fox`'s epistles or in others of the early Friends,
some very strong expressions against any being encouraged
in idleness and living upon others.

I will see in a fortnight`'s time how my cash stands, and, if suitable,
I hope to send thee five pounds to lay out in cases of distress,
provided thou wilt keep it to thyself, and don`'t speak of the donor,
but direct to the Lord on high,
whose voice is mightier than the noise of many waters of affliction,
and He takes care of the poor little sparrows; let them praise His holy name,
for none is like unto Him.

L+++.+++ A. Barclay.

To +++_______+++

Aberdeen, 22nd of 12th Month, 1853.

I hope neither of you will suffer the enemy of all righteousness
to make use of these dispensations amongst us to draw you out of
the close watchfulness unto prayer for your individual preservation,
and the close waiting for and abiding with and under the precious Divine gift of light,
life, and grace in the secret of the heart, for we, none of us,
are safe out of this close keeping and low lying.
I think one of the apostles says there must needs be heresies,
that they which are approved may be made manifest.
So now is there a little remnant who hold to first principles,
the seven thousand in Israel who have not bowed unto Baal nor kissed his image;
they mourn over our departure and backslidings, their tears fall in secret places,
but their Lord sees them, and will bottle them up,
and in due time will bring them out of all their afflictions.
Oh, that you may come and join yourselves to these faithful
few by obedience to the Spirit of Christ,
and help them, bear their many burdens and afflictions,
without fear of man or of the troubles consequent
on faithfulness--let the Lord alone be your fear,
and His holy cause more precious to you than all beside.

I am pleased with thy decision about staying at +++_______+++;
thou hast now seen the backsliding of Friends and the trials attendant on the faithful,
and mayest well believe it is better to dwell as it were alone,
and keep silence (as Jeremiah says),
bearing the yoke of the Lord and His pure testimony in humility and patience,
and content to eat thy morsel in quietude, and to dwell among thine own people.
Oh, let your light so shine before all around you as to glorify the holy name of the Lord,
and to bring peace to your souls.
I could but praise the Lord on hearing from +++_______+++ that you had
in some increased measure yielded to take up the cross;
yes, I may almost say, rejoiced as for the bringing forth of a first-born;
believing that, as the good Hand is continued to be submitted to,
your strength and comfort will be further increased,
and sweet peace and humble praise reign in your hearts.

But need I tell you there must be a daily watch kept, a cleaving close to the cross,
the power of God, that so there may be a going on unto perfection,
unto the crucifying with Christ,
and the arising with Him in the resurrection of His life;
that no one may take your crown.
And, oh, how will His blessed power judge between word and word, thing and thing,
and keep us watchful in all our ways, both with others of the world,
and when amongst ourselves, seeking only to please the Lord, and dwell in His holy fear.
May He stablish, strengthen, and settle you in His holy truth and power,
perfect that which concerneth you,
and forsake not the work of His own hand in the time of trial, but sustain, comfort,
and preserve through all unto His heavenly kingdom.
Amen.

I unite with thee in admiring Thomas Shillitoe,
or rather the grace by which he was what he was.
Let us follow it and cleave to it, as that by which we may stand.

I remain thy true friend,

L+++.+++ A. Barclay.

To +++_______+++

Aberdeen, 12th of 1st Month, 1854.

My Dear Friend,

It is a comfort to believe with thee that all this opposition
and these trials may work for the good of the cause of truth;
may lead many, both older and younger, to look more into the points of difference,
and not shut themselves up in darkness and confusion,
under the plausible idea that controversy hurts religion;
by which shrinking from a sincere search after truth,
many have become blinded and led amiss, even against the truth,
when once they sincerely sought to do right.

Thy truly affectionate and sympathising friend,

L+++.+++ A. Barclay.

To +++_______+++

Aberdeen, 14th of 2nd Month, 1854.

My Dear Friend,

Everything was finished up yesterday about the life-boat for Stonehaven,
and it was taken home there last sixth day.
I went to the top of the light-house cliff to see
it come round the point (as quick as a dart almost!),
and waved my hand to bid them farewell,
desiring that it might be blessed to the rescue of many lives from a watery grave.
It is named the Rescue.

L+++.+++ A. Barclay.

+++[+++The following lines accompanied this valuable gift for the poor sailors of Stonehaven]--

Lydia A. Barclay has much pleasure in presenting the Port of Stonehaven with a life-boat,
built on a principle which there is every reason to believe, under the Divine blessing,
will secure greater stability to its motion the more rough and heavy the sea.
It has been tried under very dangerous circumstances in a late storm here,
and kept its position admirably,
which she trusts will be an encouragement to those who are likely to make use of it.
In conclusion, she desires that a blessing may attend it,
and that all thanksgiving and praise may be rendered unto
Him from whom all good comes and help in every time of need.

To Louisa E. Gilkes

Stonehaven, 4th of 8th Month, 1854.

My Dear Friend,

It is thy turn to hear from me now, and thou wilt, I dare say,
share this with dear Hannah Marsh.
Do not smile at this expression.
I find that writing two letters, though short, and to friends of the same place,
is as exciting as two visits; and as I am desirous of curtailing my writing what I can,
I hope thou and dear Hannah Marsh will excuse it.
My health is very weakly, and my sleep is very easily disturbed,
and which loss is not repaired under several days.
A late call, or reading an interesting or trying letter or book late in the evening,
will often deprive me of sleep all night,
and then my head is so weak and hearing so bad the next day or two.

My dear friend, I fear I should have felt with thee had +++_______+++`'s lot been mine;
but I believe it arises from a want of true humility and simplicity of heart,
which I long the baptising operations of the Lord`'s
Holy Spirit may purge away from each of us,
that our usefulness in the Church and testimony for our dear Master
may not be lessened to our hurt and the robbing Him of His glory.
My discouragement about the sailors`' meeting has not yet been overcome,
nor do I know that it will ere I leave this place;
yet we know who it is who can remove mountains by His mighty power,
and make hard things easy to us by His all-efficacious gift of faith.

Since I last wrote, I was obliged to give up my Highland tour, being too weakly,
and I went to Cockermouth for ten days, being wanted to look at two houses,
and to feel my way about removing there.
I was very poorly there most of the time,
from the fatigue of the journey and a very bad attack of hay colds,
and was glad to come home,
and in a week`'s time came here to brace me up with sea breezes.
I had a trying time at C., like going into the furnace truly, proving my step,
so as almost to discourage me; but I became resigned to the anticipated trials at last,
and the last evening light seemed to arise out of obscurity,
and I then went forward and engaged the best house I could find,
though without a garden or yard, and no sunshine--a north aspect.
Thus I was favoured to come away in relief, quiet, and peace,
and have felt no regret since.
I expect to move into the above temporary house in the 10th month.
I feel greatly the thought of leaving poor Scotia, I am so much attached to it.

My dear love to John and Hannah Marsh.
Tell the latter I was obliged for her kind letter,
and could well sympathise with her under the many trials of the present day,
never so deep and many as now in proportion to the depth of the disease.
I try to live a day at a time, and oh that I may be so enabled and quickened!
I am much worn now, and must go down to the sea; so, with dear love to you both,
I remain thy affectionate friend,

L+++.+++ A. Barclay.

To +++_______+++

Ambleside, 5th of 9th Month, 1854.

+++[+++In reference to her own select monthly meeting, she writes]--

I was helped to relieve my mind of a burden or testimony, viz.,
against Friends keeping their seats in meetings or committees
where their qualifications were to be discussed,
whether as ministers, elders, overseers, or clerks; saying, it is both improper,
indecorous, and unsavoury, and may do much hurt to the cause of truth,
and the welfare of the Church as well as individuals,
by preventing a free disclosure of feeling,
few liking to speak against a Friend when he or she is present;
and that this hurt would not be counteracted by any supposed
instruction the individual might derive by being present,
as some might think.

I have not thoroughly recovered from the attack I had in the 7th month.
I am anxious to get to Cockermouth about the 1st or 4th of 10th month,
to save the usual change to foul weather the middle of that month.
My health is very weak, and I am hastening to do my little day`'s work.
How sweet it is to see dear F.; but he too is so altered and aged,
and like my dear father--we may never meet again!
My beloved +++_______+++, I feel my time is so uncertain; oh, that we may be ready!

L+++.+++ A. Barclay.

To W. H.

Cockermouth, 19th of 10th Month, 1854.

My Dear Friend,

Alas, we cannot, in this day of trouble and dismay, confess that joys abound in our cup,
except, my dear friend, that Divine goodness, at some few precious seasons,
permits us to rejoice, in hope of the glory of God, with the feeling also, and assurance,
that His power, and the power of His Christ,
shall eventually reign over all forever and ever;
which blessed hope and assurance we are enabled, as it were, to reach forth unto,
though now there is a "`need be`" to pass through much heaviness,
through manifold temptations and afflictions.
But, oh, how sweet is that text, 2 Cor. 4:17, +++[+++"`For our light affliction,
which is but for a moment,
worketh for us a far more exceeding and eternal weight of glory`"];
and may the God of all grace, who hath called us unto His eternal glory by Christ Jesus,
after that we have suffered as long as He sees meet, make us perfect, stablish,
strengthen, settle us; to whom be glory and dominion forever and ever.
I am come from one furnace of affliction to another,
and there is much to dismay and afflict me.
Mayest thou be helped to crave that the Lord may in mercy guide and direct me unto discretion,
strengthen me unto faithfulness, and preserve me in His holy fear,
and in deep humility before Him,
unto the end of my little time of suffering and of testimony-bearing,
to His praise and glory, and to the peace and blessing of my never-dying soul.

I am much grieved to hear and see the almost universal dropping
off of the plain dress and language amongst us,
even among the members of the select meetings, etc.
And if the leaders of the people cause them to err,
what can we expect the flock will become?

Thy sincere friend,

L+++.+++ A. Barclay.

To +++_______+++

Cockermouth, 27th of 10th Month, 1854.

My Beloved Friend,

It was two weeks last third day that I entered upon my new home here,
after having been five days at the temperance hotel,
while the furniture was being brought, unpacked, and housed.
J+++.+++ S. kindly came to Aberdeen to help me in the removal.

My dear friend, though many trials have attended me all this while, I do feel,
I trust in a measure of thankfulness, that mercy has indeed compassed me about.
When I consider how many journeys all this year that
my poor weak body has undergone (five,
besides other little outs),
I am astonished with the mercy that has thus helped me over this time,
and not surprised at the weak and declining state I am now in.
I have had two weeks also here of much harass and fatigue, to get settled and comfortable.
My nervous system or mental powers are greatly weakened, to my humiliation and trial,
but no doubt it is good for me.
I came under great discouragement and depression,
from knowing that I was coming into another furnace here.

It has been a very low time with me, and the heavens also have seemed to be as brass.
The Lord only can help me, and make way for me,
and help me over the various snares of the enemy;
and at times I feel a little hidden hope that He will in mercy do so,
to His praise and my own enlargement in His own due time.
The state of Truth`'s things is indeed very low, and where are they not?
I am grieved to see the evidence everywhere abounding,
that the primitive and Gospel testimony given this people to uphold
among the nations of plainness and simplicity in dress and address,
is completely lowered and trampled upon, even by the families of our leaders;
and if the heads do so themselves, what can we expect from the +++[+++body]? But,
alas! the heads wink at these things,
and even go so far as to appoint such as are inconsistent as Friends, as clerks,
as important committees, and even to visit delinquents,
thus lowering the standard of truth,
and causing the discipline (I may say our holy discipline,
which was given forth and exercised at first in the wisdom
and power of God) to be handled by unclean hands.

This degeneracy has been growing amongst us rapidly in the last ten years,
increased by or evinced by the various papers issued
in the periodical way amongst us on this subject,
and I see no other prospect than ere long,
what poor +++_______+++ said thirty years ago will come to pass,
we shall sink back to a similarity with the world; this he said desiringly,
but many of us view it deploringly and with grief;
but this may pave the way for a revival and purification of us,
as dear +++_______+++ used to say,
"`We must be very much worse before we can be better,`" and I believe
dear Sarah Grubb has also spoken to the same import.
I hear that vocal and instrumental music is increasing,
and some even who have been thought of as overseers have yielded to it in their families.

I could sympathise with thee about +++_______+++ meeting; there are many such desolate places.
When will they be rebuilt?
But there is One who is called the Restorer of paths to dwell in.
I was sorry +++_______+++ took up a piece in the 8th month,
B+++.+++ F. advising the reading of the yearly meeting epistle in the last hour of a meeting,
and I was so grieved at it,
it seemed like opening the door to reading the Scriptures or anything else in a meeting;
and I wrote a letter, to be inserted in last month, against such a practice,
saying that the epistle is no part of our worship,
and it may be a hindrance to the true worship as well the
true ministry (as I had witnessed once to my trial),
by being read in the time of worship, instead of, as is most usually done,
at the close of the worship time by the top two Friends shaking hands first,
and immediately the epistle being read.
I have made years ago much inquiry about it in various meetings,
and have found the most sound and true Friends feel with me upon it.

Please tell me your feeling on the epistle reading.
And now I must conclude at this time.
With dear love to you all, I am thy united friend,

L+++.+++ A. Barclay.

+++[+++The following, it is believed, was nearly the last letter our beloved friend wrote.
It accompanied a copy of extracts from the letters of Lydia Lancaster,
a little work she had edited some years before,
and to which her mind seemed much turned in her last illness.]

Cockermouth, 28th of 12th Month, 1854.

Catharine Sargent, from her very affectionate friend, Lydia Ann Barclay,
for lending as the service of truth shall call for--chiefly designed for the
confirming and strengthening of Friends in the all-sufficiency of Divine grace;
or, in other words, that little and lowly principle or measure of the light, grace,
and good Spirit of our Lord Jesus Christ,
which God in mercy has bestowed on every man coming into the world,
as his heavenly talent, to be occupied with, increased,
and awfully accounted for at the last great and awful day! whereby,
as yielded unto and suffered to work in us that which is the good
and acceptable will of God during His day of visitation,
that glorious salvation which our blessed Saviour
so preciously purchased and ratified for us,
when He laid down His precious life without the gates of Jerusalem,
a sacrifice and propitiation for the sins of all mankind,
is brought home to the door of each of our hearts, and offered for our acceptance;
and a blessed yet humble hope is held out and vouchsafed
of salvation and eternal life from God,
through our Saviour Jesus Christ.
Oh! the unspeakable gift, the rich, the astonishing mercy of God!
Surely the language of our hearts must be in the depths of abasement,
"`Blessing and honour, and glory and power, be unto Him who sitteth upon the throne,
and to His dear Lamb, who taketh away the sins of the world, forever and evermore.`"
Amen!
Hallelujah!

[.asterism]
'''

The depth of expression in this letter does, we think,
clearly show that the anointing which she had received, did abide in her,
and although at that period the powers of nature were fast failing, yet even then,
like the well instructed scribe,
was she enabled to bring forth from the good treasury things new and old.

Some particulars of the last illness of our beloved friend being
described in the testimony given forth by Aberdeen monthly meeting,
much further detail may not be called for here;
yet it seems well for those who were eye-witnesses of the heavenly
frame of mind in which this devoted follower of the Lamb was kept,
to bear testimony thereto.
Many were the refreshing, contriting seasons partaken of beside her couch,
when she believed her life was drawing near its close,
and did not wish to have her mind turned from the solemn subject.
The love of her heavenly Father was her chief theme, and "`eternity,`" she said,
"`would be too short to celebrate His praise.`"
It was her earnest desire to the last,
to encourage all in the diligent practice of private retirement,
and the frequent reading of the holy Scriptures; and she remarked,
when passages of Scripture were brought to our remembrance,
it was well to take the Bible and find them,
even though we might be busily engaged in our outward concerns,
and so let the good Spirit work more and more upon us.

She died as she had lived,
a firm and faithful believer in and supporter of the doctrines
and testimonies committed to our honoured forefathers.
In sending a message of love to a friend,
a short time before she was deprived of the power of speech, she said,
"`tell her my views are not altered.`"
It was her desire that the testimony to simplicity and self-denial required
in her life should be faithfully carried out in all respects to the end,
as the following memoranda will show:

For My Dear Brothers or Others Concerned in the Ordering of my Funeral,
Being Directions for the Same, Consistent With the Simplicity of Truth.

It is my especial desire that the interment of my body should
be in that simplicity which the Spirit of Christ leads into,
and that is consistent with the testimony I have felt required at my hands whilst living,
viz., That the coffin should be of plain English wood, elm, without any colouring,
polish, or oil; no panels or mouldings, nor yet with brass nails or screws or plates.
I should wish the handles to be iron; that, if suitable,
the coffin should be carried into the meetinghouse;
that the bearers should not be dressed in black clothes, neither should they have gloves;
also, that a plain cold meat dinner should be provided (with plenty, but with simplicity,
as I have ever wished in my lifetime) for such as may attend,
and that the fragments be given to the poor.
I also wish to be buried in the graveyard belonging
to the meetinghouse at which I generally attend,
and of which I am a member; and in case of dying when absent from home,
then in the nearest burial place belonging to Friends.

Signed,

Lydia Ann Barclay.

Reigate, 9th of 4th Month, 1842.

Memorandum.--Since writing the foregoing directions for the burial of my body,
finding it is the practice of Friends in Scotland not to hold a meeting at interments,
I feel it right to testify against such a practice,
by requesting that there may be a meeting held on the occasion of my interment;
and that Friends may not be ashamed of sitting down in silence to feel
after the solemnising power of the Lord to impress their minds with the
awfulness of putting off the body and entering into eternity,
that they may seek after a preparation therefor,
through faithfulness to the grace of our Lord Jesus Christ,
a measure whereof is given to all.

Signed, this 9th of 12th month, 1850, at Aberdeen,

Lydia A. Barclay.

And now, having accomplished what has appeared to be called for at our hands,
and due to the memory of one who, we believe,
may be numbered amongst those who "`shall be had in everlasting remembrance,`"
earnest are our desires that a blessing may rest upon the work;
believing, as we do,
that she was entrusted with the ministry of the pen as well as of the tongue,
and that the Gospel which she preached was "`not of man, neither received she it of man,
neither was she taught it but by the revelation of Jesus Christ.`"

THE END.
