== Testimonies

[.blurb]
=== Testimony Of Aberdeen Monthly Meeting, Concerning Lydia Ann Barclay, who died on the 31st of 1st month, 1855, aged 55 years, and whose remains were interred at Cockermouth, on the 7th of 2nd month following: a Minister about 20 years.

Although our dear friend was not a member of this
Monthly Meeting at the time of her decease,
yet, her removal having taken place so shortly before her illness,
we feel it our duty to issue the following testimony.

Lydia Ann Barclay, daughter of Robert and Ann Barclay, members of our religious Society,
was born at Clapham, in Surrey, on the 25th of 10th month, 1799,
and when very young was deprived by death of her mother.
In the season of youth she appears to have been tendered
and contrited by the visitations of heavenly love,
and, under the quickening power of the Spirit of Truth,
was given to see the necessity of obedience to all its manifestations
and pure leadings in the secret of her soul.
To Him who was thus knocking at the door of her heart she was enabled to open; and,
through cooperation with His grace,
she was strengthened to take up her daily cross and walk
in the narrow path of self-denial and regeneration,
esteeming all things but loss that she might "`win Christ, and be found in him.`"
The following extract, from a letter to a friend,
shows the work of the Lord`'s Spirit on her mind in her younger days:--

[.embedded-content-document.letter]
--

My dear friend: you queried of me yesterday,
how the work of religion was begun in my heart?
to which I believe I gave you no satisfactory answer.
I feel afraid of expressing much on such subjects,
or of "`judging my own self;`" but now, fearing lest my silence should have done harm,
I feel at liberty to tell you,
I trust under a humbling sense of the tender mercy of my heavenly Father.
Ah!
His compassionate regard was to me, when but a child, visiting me by His love,
making me sensible of the depravity of my evil heart, of the exceeding sinfulness of sin,
of my great need of a Saviour, and of His cleansing, sanctifying power: and this,
my dear friend, was not through the instrumentality of any outward means,
but mostly during the time of my being confined on a couch,
and in my secret retirings to wait upon Him.
We were brought up to the use of prayers morning and evening,
and very often went with our governess (who was of
the Established Church) to her place of worship;
this I became uneasy with, when about fifteen, and, showing a dislike to it,
she never pressed it again;
places of public amusement and dancing were also given up about the same time,
and music soon after.
Oh! how tenderly have I been dealt with!
I can never sufficiently remember it.
He has led me gently along, showing me by degrees, first,
what He would have me avoid and forsake, and then what He would have me to do and pursue:
but how many times have I revolted and turned away from His offers,
disobeyed His commands and grieved His Holy Spirit!
I desire to be continually humbled under a sense of these things,
and animated to renewed dedication of heart to Him
who has loved me and given Himself for me;
waiting for the fresh discoveries of His blessed will.

--

As she continued faithfully to follow Him who had
called her out of darkness into His marvellous light,
passing through those deep baptisms of spirit which
are necessary for the reduction of self,
and are preparatory to service in the Church,
she saw clearly that it would be required of her to engage in the work of the ministry;
in allusion to which she writes, on the 15th of 1st month, 1827:--"`Oh Lord, my God! if,
in the riches of your mercy and condescending goodness to a poor worm,
you see fit to require of me to '`speak of you to others,
to speak of the glorious honour of your majesty,
and tell of your wondrous works,`'--your will be done.
Behold the handmaid of my Lord; do what you will with me, only make me your dear child,
your faithful servant.
Be my strength; let it be in your power and authority,
and to the utter abasement and deep humiliation of the creature,
that so all power and glory may be ascribed unto you, to whom it is ever due!
Amen.`"
Again, in reference to this awful engagement, the breathings of her soul are penned,
on the 1st of 10th month, 1830:--"`Let the mountains flow down at your presence,
and cause the hills of opposition to melt like wax before you;
bring all within me into pure resignation, into holy obedience--then open my lips,
and my mouth shall show forth your praise--then speak the word,
and I will publish it in your might; and, oh Lord!
I beseech you, bring me into deep humility and nothingness of self,
and keep me there forever.`"

She appears to have first come forth in the ministry at Friends`' Meeting at Epping,
in allusion to which she writes, on the 17th of 2nd month, 1831:--

"`And now it seems well for me to acknowledge (I trust under a
deep sense of the condescending goodness of my dear Lord and Master,
and of my own utter unworthiness),
that having often felt uneasiness in not having yielded to a secret
desire that has seemed to attend me these several years,
to go and sit with Epping Friends in their Meeting,
I ventured to go there yesterday fortnight, in fear for the body,
it being a deep snow and severely cold; and in mental fear also,
lest it should be presumptuous and wrong.
But, oh, what a favour! it pleased Divine Goodness again, as it were,
to overshadow me with His love,
and to require obedience in the expression of a few words; after fearing and hesitating,
and at last trembling, till near the close of the meeting,
I ventured and was enabled to stand up.
How unworthy am I to make mention of His name!
What great condescension and mercy, thus to make a way where I can see no way,
to take away fear, to remove doubt, and to give strength! and not only so,
but afterwards to favour with a peaceful quiet!
And now, what can I render for all His mercies?
The answer seems, '`All you require, my whole heart, oh Lord!`' But, oh,
may He enable me and undertake for me, for I am indeed weak and feeble;
and may He purify and prepare me for Himself to dwell in!
And now, whenever and wherever such another sacrifice may again be required of me,
no matter--may He make me more and more His simple, His obedient child!
And seeing I am such a poor, weak, ignorant child,
may He take me by the hand and show me how to go,
and all the snares and dangers that surround, enabling me to take right steps;
and when I slip or miss my way, may He tell me and reprove and chasten me,
humbling me as His tender love and wisdom see fitting.
And, oh! says my soul, may He keep me low in His pure fear,
that all praise and glory may ever be ascribed to
Him to whom alone it is eternally due!`"

She was recorded a minister on the 24th of 12th month, 1835, while resident at Croydon,
and in this capacity visited many of the counties of England,
once the Yearly Meeting of Friends at Dublin, and twice the Meetings of Scotland.
In 1847, under an apprehension of duty, she removed from Reigate, in Surrey,
where she had resided nearly eight years, and settled in Aberdeen.
While living here she was liberated, in the 2nd month, 1849,
for religious service in the Quarterly Meeting of Cornwall;
in the following year she visited the Meetings and
part of the families of Friends in Dorset and Hants,
and attended the Yearly Meeting at Dublin; in the 1st month, 1852,
she held a meeting with a portion of the young women employed in the factories at Aberdeen;
and, in 1854, was engaged to visit, in Gospel love,
the Meetings composing the Quarterly Meeting of Cumberland and Northumberland;
besides other services at different times within the compass of this General Meeting.

It was her conscientious endeavour to occupy faithfully, as a good steward,
with the outward means with which she was abundantly blessed,
being concerned to do good and to communicate, and being herself in deportment, dress,
and the furniture of her house, an example of plainness and simplicity,
which she believed the Spirit of Christ led into.
She removed to Cockermouth early in the 10th month, 1854,
and had been there little more than four weeks,
when a paralytic seizure deprived her of the use of her left side,
and affected her mind with frequent and protracted wanderings.
About this time a relative bidding her farewell, and adding,
"`The Lord be with you,`" she said, "`He has been with me;
I have had many favoured times; they have been very sweet:`" and at another interval,
"`I have been brought very low, but Divine aid has supported me.`"
She had been under much exercise for the young females engaged in the factories at Cockermouth;
and on one occasion, expressing this,
and her desire that +++_______+++ should visit them frequently,
and assist in teaching them to read, etc.,
she added:--she wanted young friends to be encouraged to use their talents,
though it might be in a little way:
the little would be accepted that was done in love to the Lord,
for even a cup of cold water, if given in His name, would have its reward;
none should shrink from these services because they could do but little;
little ability--little means--little talent--ought not to hinder; all could do something;
and if we omitted to do what was called for at our hands for our poor suffering fellow creatures,
how could we expect to have the blessing of those
who were ready to perish to rest upon us.

She thought we ought to be faithful in speaking our minds to others,
not deterred by the fear of offending them, lest, by unfaithfulness,
we should endanger the soul of our brother, and his blood should be required at our hand:
also how sad it would be, if, owing to us, he should go to the place of perdition,
"`where their worm dies not, and the fire is not quenched.`"
It pleased Him who had afflicted her gradually to restore her mental faculties,
when under a deep sense of the humiliating condition of her earthly tabernacle,
and of the abounding mercy of her dear Lord and Master, she wrote the following:--

"`My mind has been so filled with these words that I believe
I must try and write them down to the glory of God.
And now, O Lord!
I desire to praise, and thank, and adore your holy name,
for all your great goodness and mercy to your poor, weak, unworthy servant,
who is truly unworthy of the least of all your tender mercies to her:
especially making known and revealing your grace, in favouring her,
with others of her family, with your blessed day-spring from on high,
whereby you have brought me forth out of darkness and the shadow of death,
and have in measure translated me into the kingdom of your dear Son,
who has abolished death, and brought life and immortality to light through the Gospel,
giving us a lively hope through your dear Son,
and favouring with a humble hope of acceptance, according to your precious grace,
through Him in whom we have redemption through His blood,
and forgiveness for the sins that are repented of.
And now, Lord, may it please you so to work in and upon your poor, unworthy child,
as to bring me into a humble resignation,
a true resignation and real subjection to your mighty power and holy will in all things,
that I may, by your goodness, be purified and prepared,
through this humbling dispensation, for my awful time of translation.
Oh! so work in and upon me, as that your life may reign and come into dominion over all,
and thus I may be permitted graciously to obtain a glorious victory over death, hell,
and the grave, through your dear Son, my Lord and Saviour.
For when your life comes to reign over all,
then your peace and praise shall fill my soul! peace with you through Jesus Christ,
and your peace and love to all mankind the world over (but not to their sins).
Oh! be pleased thus to fill me with your peace and praise, who are worthy,
worthy of all praise and thanksgiving, honour, adoration, and renown, and living,
living praises, not only now, but now, henceforth, and forevermore, Amen.`"

After this, in a letter to a friend, she remarks,
"`I always had a feeling that my moving to this place would be like the end of my career,
but what a mercy to have been spared and so favoured during this painful time; yes,
favoured with songs of praise in the night season,
and heartfelt praise and thanksgiving by day,
so as to be quite resigned to wait the Lord`'s time!`"
Thus, with a heart overflowing with gratitude for all her mercies--the
sweet savour of her spirit evidencing that her dwelling was in
the secret place of the Most High--a second seizure,
on the 25th of the 1st month, 1855, deprived her of the use of the other side,
also of speech and the power of swallowing.
In this prostrated state, apparently with little or no pain,
she lay until the 31st of the same, when she quietly and peacefully breathed her last.

[.blurb]
=== Testimony of Lydia Ann Barclay by John and Hannah Marsh

A little tribute to the memory of our beloved departed friend, Lydia Ann Barclay,
seems due from us,
who for a long course of years were privileged to
enjoy a close intimacy and friendship with her,
being sweetly united together in the love and fellowship of the Gospel,
and which continued unabated until the close of her life.

Our acquaintance commenced in the days of early dedication,
at a time when her mind was sweetly visited with the contriting,
humbling influences of heavenly love, engaging her heart to seek and to serve the Lord;
and by yielding obedience to the teachings of Divine grace, as inwardly manifested,
she was favoured to experience a growth therein,
and in the saving knowledge of the truth as it is in Jesus,
evidencing by her undeviating walk in the way of the cross and path of self-denial,
that she was indeed concerned to follow Him in the regeneration and in newness of life.

Very humble were the views she took of herself, feeling that she had nothing to glory in,
save in the cross of our Lord Jesus Christ, by whom the world was crucified unto her,
and she unto the world.
Her memory is precious, her example was instructive and edifying,
the one bent of her mind being to journey Zionward;
and in her endeavour to serve her Divine Master,
she was earnestly concerned to press upon others the need of a daily feeling
after fresh supplies of heavenly grace to keep the soul alive.
This being much her own experience caused the dew of heaven to rest upon her spirit,
preserving her leaf from fading,
and thereby causing much fruit to be brought forth for the refreshment of many,
to the praise and glory of the great and good Husbandman.

And not only was she livingly concerned to be found
a faithful steward of the manifold grace of God,
but was also sensible of her accountability to Him
for the right use of her outward substance,
of which she was a liberal distributor,
seeking out objects of a more hidden character to
whom pecuniary aid was peculiarly acceptable.

She was also in no common degree a remarkable economist of time, which,
with her other gifts and talents,
she was zealously concerned to occupy to the honour of the great Giver,
and at different times was industriously engaged in spreading among others,
by the distribution of sound religious books and tracts,
an acquaintance with the principles of truth, as always professed by Friends.

More might be said of this devoted handmaid of the Lord,
yet our object is not to eulogise the creature,
but briefly and simply to delineate her character
and untiring zeal for the prosperity of Zion,
and the enlargement of her borders,
for unto her was given in the behalf of Christ not only to believe on Him,
but also to suffer for His sake; therefore, she could say from experience,
that "`the sufferings of this present time are not worthy to be compared with
the glory which shall be revealed in us,`" for she counted nothing too near or
too dear to part with that she might win Christ and be found in Him.

In the remembrance of the many favoured opportunities we were permitted
to partake of together in seasons of inward retirement before the Lord,
for the refreshings of His presence and renewal of our spiritual strength,
as likewise the privilege of frequent social interaction,
we are afresh made sensible of our great loss,
as well as that which we feel the Church has sustained by
the removal of this beloved friend and sister in the truth,
who having been concerned to work while it was called day, was, as we reverently believe,
through redeeming love and mercy, prepared to receive the joyful summons of "`Well done,
good and faithful servant,
enter into the joy of your Lord,`" and into your Master`'s rest.

[.signed-section-signature]
John Finch Marsh.

[.signed-section-signature]
Hannah Marsh.

[.signed-section-context-close]
Croydon, Surrey, 12th Month, 1861.

[.blurb]
=== Testimony of Lydia Ann Barclay by Louisa E. Gilkes

Precious is the memory of the Lord`'s faithful servants,
of which blessed number may justly be reckoned our late beloved Lydia A. Barclay.
It may be said of her that she walked through the world but was not of it;
and was an example of humility, self-renunciation,
and dedication of heart unto the will of Him whom she chose for her blessed portion,
and whose holy cause she preferred above her chief joy,
being given up to the promotion thereof in her own soul, and in the souls of others,
but especially among her own people,
that they might be redeemed from the corruptions of the world, and live soberly,
righteously, and godly in this present life, according to their high and holy profession.

She bought the truth at the price of all she held dear, and having done so,
she dared not sell it again,
but bound it about her so closely that the enemy`'s attempts to
rob her of her treasure proved but vain and fruitless before the
preserving power of Him who is stronger than the strong man armed.

Thus she was not content to run well for a time only, but continued stedfast to the end,
in the fulfilment of the commandments of the Divine Lawgiver;
and so conspicuously did her light shine before men,
that many seeing her good works were led to glorify their Father who is in heaven.
Hers was as the path of the just, that shines more and more unto the perfect day.
The remembrance of her is animating to those who were made partakers of her labours,
and were strengthened by her example and counsel to take up the cross, deny themselves,
and follow Him whom she followed.

Though unworthy thus to claim a place among the numerous objects of her Gospel labours,
yet gratitude demands of me an open acknowledgment
of their value in this short tribute to her memory.
Her day`'s work was early completed, and she was permitted to lay down her head in peace,
reposing in the love of that Saviour who redeemed her and qualified her for His service,
and who is now, we reverently believe, her everlasting reward and crown of rejoicing.

[.signed-section-signature]
Louisa E. Gilkes.

[.signed-section-context-close]
London, 1862.
