== Chapter 1

+++[+++Journal Entry]
_1st Month 15th, 1827._--Oh Lord, my God! if,
in the riches of your mercy and condescending goodness to a poor worm,
you see fit to require me to speak of you to others,
to "`speak of the glorious honour of your majesty,`" and
tell "`of your wondrous works`"--your will be done.
Behold the handmaid of my Lord; do what you will with me, only make me your dear child,
your faithful servant.
Be my strength; let it be in your power and authority,
and to the utter abasement and deep humiliation of the creature,
that so all power and glory may be ascribed unto you, to whom it is forever due.
Amen.

It seemed well to write down the above--if it meet
the eye of a brother or sister after my dissolution,
it may be of use.
Let all praise be rendered unto Him from whom all good desires spring,
and who answers them.

[.small-break]
'''

_3rd Month 20th, 1827._--Should my great and good Master see fitting that
the foregoing feelings should be a preparation for eternity,
may His holy will be done!
My heart has desired to unite in the language--

[verse]
____
My life, if thou preserve my life,
Thy sacrifice shall be;
And death, if death must be my doom,
Oh may it join my soul to thee.
____

Oh! may His hand not spare, nor His eye pity,
till He has thoroughly purged away all the dross, and the tin, and the reprobate silver,
and made me what He would have me to be.
Truly He is worthy to be served, loved, and obeyed forever.

[.letter-heading]
To Hannah Marsh

What I have gone through for these several years you can
better imagine from experience than I can describe;
but I will not attempt to enlarge on such an awful subject, except it be to say,
that I believe it is my earnest desire to be emptied and stripped,
to be washed and purified,
to be rendered soft and pliable as clay in the hands of the potter,
to be anything or nothing.
Do, dear Hannah,
crave for me that I may be preserved from slipping on the right hand or on the left,
and that when the acceptable time may come, strength may be given to bring forth,
no matter how much to the abasement and humiliation of the creature,
so it be to the praise of His great and ever excellent name, who alone is worthy.

Farewell, in haste, with the dear love of your affectionate friend,

[.signed-section-signature]
L+++.+++ A. Barclay.

+++[+++The following letter is in reply to one written to her by a Friend,
relative to that plainness of dress which she believed she was required to adopt:]

[.letter-heading]
To +++_______+++

[.signed-section-context-open]
+++_______+++, 1828, or 1829.

[.salutation]
Dear Friend,

Your letter I duly received; it needed no apology I assure you.
I desire to be always open to the advice or reproof of my friends,
and take it as a mark of that love which ought to
subsist between the members of the same body.
With respect to the subject of your letter, I wish to take your hint,
and that the subject may again obtain my serious consideration--this
has been the case from time to time during the last nine years.
I believe I may venture to say, I desire to have no will in it,
but to be enabled clearly to see and simply to follow the requisitions of truth.
I may own, it has been exceedingly trying to be thus peculiar,
being naturally inclined to be rather nice and particular in dress,
as well as to shrink from observation.

Whether this trial has been required for the subjection of my natural pride,
or whether as a testimony against the over-nicety and elegance of many of my dear friends,
I must leave.
I think I may truly say, the cause of truth is very precious to me;
and while I should be exceedingly sorry that any manner or outward
appearance of mine should have any repelling effect,
I feel a fear (and desire it may increase) of encouraging or slipping
into that which will not bring peace in the retrospect.

I feel my own weakness is very great,
and that the snares of the enemy are laid subtilely on every side.
It seems a very serious matter to take upon one to
say this or that is required at my hands!
How earnestly do I desire to be enabled to distinguish the voice
of the great and good Shepherd from the voice of the stranger,
believing that He will give strength to follow Him,
and preserve from the enemy`'s snares.

Farewell.
I hope you will be able to understand my meaning, and,
whenever you may see a hint necessary, that you will deal faithfully with me.
With love to your wife, I remain your friend sincerely,

[.signed-section-signature]
L+++.+++ A. Barclay.

[.letter-heading]
To the Same

[.signed-section-context-open]
Forest Place, 6th Day, +++_______+++

To be thought well of by others, what a golden wedge that is!
But oh! to be approved by Him who is the Beloved of my soul, this is all I crave.
He has truly betrothed me unto Himself in righteousness, and in judgment,
and in lovingkindness, and in very _long-suffering_ mercy, yes, in faithfulness too;
and oh! that I may never depart from Him,
nor cease from serving Him with the strength He gives.
Amen.

[.signed-section-signature]
L+++.+++ A. Barclay.

[.letter-heading]
To Hannah Marsh

[.signed-section-context-open]
1st of Seventh Month, 1829.

How do I long that the fire may thoroughly accomplish its work,
be it kindled ever so fierce, that every crook and corner may be searched,
into which self can creep, that so it may be made of no reputation.
Oh! if we are but enabled to lisp (as it were) the ABC after our heavenly Father,
and at his bidding, what a favour!
I have much admired the conduct of Lazarus`' sister Mary,
how she sat still in the house until she received the call, "`The Master is come,
and calls for you,`" when she rose up quickly.
I have much desire to follow her example, and to wait the full time, when,
I have at times believed, there would be no lack and no doubt.

[.signed-section-signature]
L+++.+++ A. Barclay.

[.letter-heading]
To M. M., On Her Being Admitted Into Membership

[.signed-section-context-open]
+++_______+++, 1830.

It is my earnest desire that you may not settle down at
ease now that you have obtained your membership with Friends,
stopping short and looking at others; but that you may still press forward,
seeking after a further growth and establishment
in the blessed truth--looking up to our great Pattern,
and desiring the sincere milk of the word, that you may grow more and more in grace.
And now, in attending all our meetings, I desire that you may not be tempted to judge,
on the one hand,
or to be discouraged or stumbled on the other by what you see amiss in any.
You must remember,
that the shortness and deficiency in any of us does not arise from the
insufficiency of the blessed principle we profess to be led by,
but from our own unfaithfulness and lack of subjection to it--and,
alas! your poor mistress often laments over her shortcomings.
Do learn from the failings of others,
and seek daily for ability to walk worthy of the high profession you have taken up.

[.signed-section-signature]
L+++.+++ A. Barclay

+++[+++Journal Entry]
_3rd Month 7th, 1830._--Oh Lord, my God! seeing I am but a child,
be graciously pleased to take me by the hand and lead me,
teach me more and more of your precious ways,
cause me more and more to know your language.
Put your fear in my heart, that I may never depart from you more;
increase my faith and trust in you, give me to love and obey you more and more!
And whether you see fit to permit me many days and many trials,
or whether to cut short the thread of my life in righteousness,
your holy and blessed will be done!
Only make me yours--yours _only,_ yours _wholly,_ in time and in eternity.

And now, Oh Lord! what wait I for?
my hope is in you, and in your tender condescension to your poor, unworthy,
disobedient creature, that you will yet revive your work as in the midst of the years,
and in the midst of the years make known your power and the calls of your love.
And oh! when it shall be, let the mountains flow down at your presence,
and cause the hills of opposition to melt like wax before you;
bring all within me into pure resignation, into holy obedience--then "`open my lips,
and my mouth shall show forth your praise`"--then speak the word,
and I will publish it in your might; and, oh Lord!
I beseech you, bring me into deep humility and nothingness of soul,
and keep me there forever!

These were the breathings of my soul as I was returning from Leighton Quarterly Meeting,
the 1st of 10th month, 1830, and it seems with me to pen them down.
It may be a stimulus to me in after times (if preserved) to see
the tender dealings of my heavenly Father to His backsliding,
revolting creature.
May He turn His hand again and again upon me,
and perfect that which concerns me in His own time and way, and to His own praise;
for what am I, His poor weak handmaid,
that He should condescend to put His words into my mouth,
and honour me with His commands!

[.letter-heading]
To S. B.

[.signed-section-context-open]
Forest Place, 1831 or 1832.

[.salutation]
My Dear Friend,

For no other reason than lest you should feel fearful of
having done amiss by the few words that passed between us,
I thought I would venture to tell you that you are not mistaken,
nor is your exhortation unnecessary.
Your observations were close on obedience; but, dear S+++_______+++,
we are so apt to attribute our hesitation and lack of compliance to better
motives than disobedience--for how can we grieve so tender a Father?
The fear of mistaking His voice, or of stepping too soon in so awful a matter,
before the weeks of preparation are _wholly_ accomplished,
and the fiery baptisms _thoroughly_ partaken of--this appears to keep us back!
Ah! He has indeed waited long on some of us,
and again and again visited with the calls of His love, laying His hand tenderly upon us!
But, alas! we have refused in the day of trial, and have turned back from His requiring.
Surely it is of His tender compassion that we are not utterly
consumed--that the talent is not taken away,
and given to others more faithful.
The forwardness of some has a restraining effect--the snares seem greatest on that side.
How _great_ the danger of getting into a lifeless way, ministering death instead of life!
My dear friend, have I run on too freely to you?
I know the danger there is in disclosing to others that which had better be kept secret,
and dwelt under.
I know the advantage of sitting alone (as dear Sarah
Grubb said at Quarterly Meeting) and keeping silence;
but it must not always be; there will be a time of making known, as upon the house-top,
what is revealed in the ear.
Amen! says all that is within me.
Let it only be in His time and way, and according to His most blessed will to His praise,
and the utter abasement and humiliation of the creature!

I need hardly say that, of course, I write in confidence,
and I shall attend to your injunction.
I often think such matters are made too public,
though indeed it is animating and encouraging to hear of the faithfulness of any we know.
I do hope, dear S+++_______+++, that you will deal faithfully with me at all times,
more _especially_ when you see need to _reprove_ or _discourage,_
for I desire to take it as a mark of true love.
May such a child be allowed to say, that I hope,
if it should be some time before such a sacrifice is again called for from your husband,
that he will not be discouraged or dismayed;
it is the Master`'s touch or bidding that should only move us,
and no matter when it is or what others think.

[.signed-section-closing]
Dear love, from your affectionate friend,

[.signed-section-signature]
L+++.+++ A. Barclay.

[.letter-heading]
To E. J. FRY

[.signed-section-context-open]
1st Month, 1831.

[.salutation]
My Dear Cousin,

I fear I appeared ungrateful for your kindness this morning.
I was too overcome to speak to you.
I can more easily write than converse.
You do not know the misery, I might say anguish,
that I have brought upon myself again--though often before,
yet never so great as within these few weeks.
I have been fearful I should sink below hope.
Miserable myself, and, as I thought, making everyone miserable around me,
I longed to shut myself up in some corner out of sight;
yet everywhere would distress follow me!
I believe I am naturally liable to depression and discouragement,
and the enemy attacks the weak side always;
he laid me waste sadly in this way in Cornwall.
Distress is _justly_ my portion for disobeying and rebelling against so tender a Father;
yet surely true compunction ought to lead to trust in His plenteous forgiveness,
and in His willingness to enable to do better!
I expect what you were sensible of last First day
was the effects of my disobedience that day two weeks,
for I felt as if I obstructed the arising of life; indeed,
I would gladly have stayed away from meeting if I dared.
There are times (times of great favour to such an unworthy one!)
when all reasonings seem hushed into silence and resignation;
and _then_ it seems alike indifferent whether there be one thousand or but one present,
and whether two or more words be given to be uttered,
so the Divine will be but accomplished.
But I am ashamed to own there are many other times when the fear of man--the
idea of this or that person being present--seems an insurmountable mountain.
I long for my bonds to be broken.
Ah!
He is able to do so--to say to the prisoners,
"`Go forth,`" and to those who have sat long in darkness, "`Show yourselves!`"

Dear +++_______+++ has much pressed me to go and see them, but I am fearful of it at present;
I am afraid of going so among those whose tender sympathy for me I know to be great,
and I am afraid, too, of running away from suffering.
Perhaps my stubborn,
proud nature must first be humbled as in the dust before my own family; however,
this I must leave, though I long to flee away from home and the cares of the body.
Quarterly Meeting was indeed an awful time to me; you all seemed to address me,
and I felt contrited and melted, as it were, into resignation.
The sudden death of one so beloved in our circle seemed, indeed,
like loud preaching in my ears.
How awful the thought of being thus snatched away before
peace is made with a calling and long-suffering God!
What great condescension to visit again with His constraining power two weeks back,
and not only so,
but to confirm my doubting mind--yet did I hesitate and hesitate till the meeting closed!
Alas!
I have great need of the prayers of the faithful; when favoured with ability,
my beloved cousin, remember me for good.
I fear I have made you sorrowful with my bewailings over myself.

[.signed-section-signature]
L+++.+++ A. Barclay.

+++[+++Journal Entry]
_1st Month 5th,
1831._--Considering the tender mercy of my heavenly Father to me these many years,
and even from childhood, and feeling the great uncertainty of time,
it seems with me to leave some record of His tender dealings to such an unworthy creature.
It may prove to the animating and stirring me up
in after times (if time be prolonged to me);
or, if these lines should meet the eye of a surviving dear brother or sister,
may they afresh excite to praise, love, and adore so compassionate, so merciful a God!
Ah! He has followed me all my life long; He raised me from death when an infant;
He visited me with His love when quite a child,
though I did not then understand His voice;
in after years manifesting Himself more conspicuously by His reproofs and instructions,
as well as the shedding abroad of His love in my heart in seasons of His good pleasure.
But, alas! how slow to believe,
how slow to obey was I (and am I still)! It is indeed
of His tender mercy that I am not utterly consumed,
because His compassions fail not.
How many times have I turned back, and limited the Holy One of Israel,
and refused to yield the sacrifices He has commanded!
But, oh! how great then was His love, how unmerited His mercy,
that He should condescend to reveal His will,
His gracious will--that He would cause me to speak of the glorious majesty of His kingdom,
and to tell of His wondrous works to my dear fellow creatures!

It is near ten years since the _merciful_ opening of this
view by the immediate operation of His power and love,
though afterwards permitted to be confirmed instrumentally.
All within seemed bowed down in resignation, and the language of my heart was,
"`Here am I; do what you will with your poor, unworthy handmaid,
only make me your dear child, your faithful servant, O Lord!`"
Great, indeed, have been the conflicts, the doubts and fears,
and various the exercises since that time to this, known only to my God; and,
alas! since this great and most awful matter has appeared to be
ripened of later years--shall I venture to say so?--how often have
condemnation and distress been the consequence of disobedience!
What shall I say?
It is indeed of His tender mercy that the one talent
is not taken away and given to another more faithful.
The fear has been great of stepping before the right time,
before the weeks of preparation are accomplished, and the necessary baptisms partaken of.
The danger of mistaking any of the preparatory exercises for the thing
itself--of putting forth a hand unbidden to the ark of the testimony,
or of offering strange fire,
as it were--of getting into words without life--the many snares on every side,
within and without all these things, together with the feeling of weakness,
and unfitness, and utter unworthiness to make mention of so sacred a name,
have been overpowering at times.
It has been often in my heart, "`Oh Lord! you know my foolishness,
and my sins are not hid from you.`"

Yet, shall the clay say to the potter, "`What are you doing?`"
Is not the Lord pleased to make choice of the weak and foolish things, sometimes,
for the purposes of His wisdom and mercy?
Can He not purify and make fit?
Yes, all is of and from Him--the emptying, the purification, the qualification,
the power, the fitting,
the obedience--and He said He would pour of His Spirit even upon the daughters and handmaids,
the weaker vessels, the first in transgression.
Wonderful condescension!
Should we resist His love, and quench His Spirit?
When He puts His words into our mouths, should we keep silence?

When I look at myself, shame covers me;
mourning and distress are justly my due--my bonds yet unbroken--what
I have apprehended to be His gracious and clear commands disobeyed.

And now,
oh Lord God! may it please you yet to revive your work as in the midst of the years,
and in the midst of the years to make known your mighty power.
Yet again,
may the commands of your love go forth--the clear discovery of your blessed will;
and oh! may it please you to make willing, to make obedient;
so strengthen and give to believe,
as that all the doubts and the fear of man may vanish before your power!

[.small-break]
'''

_2nd Month 17th,
1831._--And now it seems well for me to acknowledge (I trust under a deep
sense of the condescending goodness of my dear Lord and Master,
and of my own utter unworthiness),
that having often felt uneasiness in not having yielded to a secret
desire that has seemed to attend me these several years,
to go and sit with Epping Friends in their meeting,
I ventured to go there yesterday fortnight, in fear for the body,
it being a deep snow and severely cold; and in mental fear also,
lest it should be presumptuous and wrong.
But oh, what a favour! it pleased Divine goodness again, as it were,
to overshadow me with His love,
and to require obedience in the expression of a few words; after fearing and hesitating,
and at last trembling, till near the close of the meeting,
I ventured and was enabled to stand up.
How unworthy am I to make mention of His name!
What great condescension and mercy, thus to make a way where I could see no way,
to take away fear, to remove doubt, and to give strength! and not only so,
but afterwards to favour with a peaceful quiet!
And now, what can I render for all His mercies?
The answer seems, "`All you require, my whole heart, oh Lord!`"
But oh, may He enable me and undertake for me, for I am indeed weak and feeble;
and may He purify and prepare me for Himself to dwell in!
And now, whenever and wherever such another sacrifice may again be required of me,
no matter--may He make me more and more His simple, His obedient child!
And seeing I am such a poor, weak, ignorant child,
may He take me by the hand and show me how to go,
and all the snares and dangers that surround, enabling me to take right steps;
and when I slip or miss my way, may He tell me, and reprove, and chasten me,
humbling me as His tender love and wisdom see fitting.
And oh! says my soul, may He ever keep me low in His pure fear,
that all praise and glory may be ascribed to Him to whom alone it is eternally due!

[.letter-heading]
To Hannah Marsh

[.signed-section-context-open]
4th of 3rd Month, 1831.

I have been quite confined since I saw you, and am now under the doctor`'s care.
I have had much solitary time, yet fear it has not been improved as it should have been,
in seeking after the teachings of my heavenly Master, but the body is weak.
Ah! it has indeed been a changed time the last month (as I hinted to you),
since having been graciously enabled to take up the cross on one occasion.
Oh! _how_ unworthy to taste of such peaceful quiet,
and _how_ unworthy to make mention of His name--__how__
unfit in any way to celebrate His praise!
May such _great_ mercy incite to fresh diligence and faithfulness when recovered!
And, dear +++_______+++, crave that I may be preserved _simple_ and obedient, and, above all,
__humble__--be brought low and kept low.
I feel it a great favour to have been so ill and confined.
He is indeed a tender Father!
He knows our weakness and what is best for us; and I have a little faith to believe,
in looking forward to any future steps, if any should be required,
that He will strengthen to do and suffer His will,
and graciously show the snares and dangers on either side;
and when one slips or steps amiss, that He will correct, and chasten, and humble,
as His tender love and wisdom see fit.
This feeling has been quieting to some reasonings which you, dear +++_______+++, can,
I dare say, enter into.

I have just been out in Robert`'s carriage with dear Elizabeth,
who has been similarly affected with myself, and enjoyed it much.
The sight of the budding trees and opening flowers--what
a rejoicing feeling there is in everything in the spring!
From the letters from America,
dear J. & H. Backhouse have not yet received the afflicting accounts of their loss.
Poor things!
I feel for them; they have completed the families at New York,
and are going to Philadelphia.
So hard at work have they been,
that the going in a steam vessel to an interment _fifty_ miles off was a great _rest._

[.signed-section-signature]
L+++.+++ A. Barclay.

[.letter-heading]
To E. R.

[.signed-section-context-open]
Folkstone, Kent, 15th of 7th Month, 1831.

[.salutation]
My Dear Friend,

It was very pleasant to hear of you as well as other
dear Cornish Friends from +++_______+++ and +++_______+++,
who took up their quarters at my brother John`'s, while I was at Croydon,
in the 4th month.
They were visiting the families,
and it was very sweet and instructive to have their company at that time;
more particularly so, as I am so solitarily situated at home,
being at a distance from meeting and the Friends of it,
and I had also been absent when they visited there.
This Yearly Meeting struck me as unusually small,
though mercifully favoured during the different sittings of it,
especially in seasons of silence, with the overshadowing wing of ancient goodness,
to the contriting our hearts, and raising the thankful acknowledgment, that,
unworthy and backsliding as we are, the Lord has not forgotten to be gracious,
nor in anger shut up His tender mercies!

We missed a number of our dear ancients, as A. Price, Rebecca Byrd, Mary Alexander,
S+++.+++ Fox, Sarah Abbot,
and Mary Capper--indeed few are left in the gallery
that were there ten or twelve years ago.
This is _indeed_ affecting! yet we can expect no other,
and it is in the wise ordering of Him who can work by few or many,
and even qualify the very stones to sing His praise!
We had indeed a very awful instance of the uncertainty
of time and the talents mercifully lent,
in the seizure by paralysis of dear Mary Marriage,
which happened in our meeting at Plaistow, the First day in Yearly Meeting.
She had been strikingly engaged, both in the morning and afternoon meeting,
especially in the latter (a few minutes only before she became speechless!),
addressing our (many) young people in a very affectionate, persuasive manner,
and bearing a sweet testimony to that goodness and
mercy which had followed her all her life.
The meeting speedily broke up, though Joseph John Gurney was upon his knees,
and she was carried to a Friend`'s house near, where she lay three weeks,
and then was removed home to Chelmsford.
I saw her last week; her voice is returned,
but no articulation--it was sweet to be with her.
It was very pleasant, as well as helpful,
to have the company of three dear Friends who had
been absent from Yearly Meeting some years,
Daniel Wheeler of Russia, Jacob Green of Ireland, and Ann Jones;
the two former paid our meeting very acceptable visits--the latter,
after sitting in silent exercise nearly all the sittings, at the last but one,
stood up with a few very striking sentences which occur in John Woolman`'s journal,
to this effect:--"`The trumpet is sounded; the call goes forth to the Church,
that she gather to the place of pure inward prayer, and her habitation is safe.`"
I should enjoy to be sitting by you, my dear friend.
I could tell you much more of what passed during Yearly Meeting,
which I must own was rather a mournful, what if I say discouraging,
time to me and some others, who, perhaps, look too much on the gloomy side of things.
I remain your affectionate friend,

[.signed-section-signature]
L+++.+++ A. Barclay.

[.letter-heading]
To Hannah Cruickshank

[.signed-section-context-open]
Leytonstone, Essex, 26th of 9th Month, 1831.

It is sweet, my beloved friend, to feel that we are united together,
whether there is any outward communication with one another or not--that we do
desire above all things to love and serve the same dear and good Master,
to wait upon and listen to Him more and more, whose words are indeed sweet to us,
and His countenance is comely!
Oh! may nothing hinder us from following on to know Him,
to know more and more of His precious ways and teachings;
for to whom else can we go?--we have found that He alone has the words of eternal life:
He is indeed the living bread of the soul!

But to return to your letter, dear Hannah; it was truly acceptable,
for I had sometimes felt a fear that I had done amiss in obtruding myself upon you.
Ah!
I can fully unite with you, that were there but a passive submission to the purifying,
forming hand of Omnipotence, we should become beautiful as a city set on a hill,
and as lights in the world,
reflecting the light and glory shed on us abundantly by our heavenly Father.
When shall these good things be?
Surely it must be by individual faithfulness.
Ah! my dear friend, your remarks do apply to me,
though you think __not__--you do not know how obstinate and self-willed I am,
and what a deal of pride and other sad things there is to be brought down in me; so that,
at times, I shudder (as it were) at the sight of what is within,
and often say in my heart, "`I am`" one "`of unclean lips,`" and, "`behold, I am vile!`"
But I believe we have need to be wary,
lest the enemy should lay hold of such a humbling view,
in order wholly to discourage and dissuade us from yielding
to that Power which would cleanse and sanctify us.
How very instructive it is to remember that the ten lepers were cleansed as __they went!__

Your account of the dear Friends in your neighbourhood was truly interesting to me,
and I could feel united to the living among you,
if such a poor halting child may be allowed to say so.
The expression of the Apostle is sometimes cheering in seasons of doubt
and dismay,--"`We know that we have passed from death unto life,
because we love the brethren.`"
I felt much with you, mentally, at your General Meeting last month;
hope you had a good time, or, as dear old Thomas Gwin says in his journal,
that it was _much good_ to you!
Ah! what can we desire, at these times,
but His presence and power bringing all within us into holy subjection,
into humble resignation to His blessed will.
I long to be outwardly acquainted with your dear grandfather and mother;
will they accept of the dear love of a stranger?
You have, of course, heard a full account of this Yearly Meeting.
We were mercifully favoured to feel the overshadowing wing
of ancient goodness in the seasons of solemn silence,
as well as when vocal service was offered; nevertheless, I think I may say,
it was a time of trial, shall I say mourning to me.
But I am a poor child, and have great need to look _at home,_
and above all (oh may I be enabled!) to look __upward__--from
off the discouragements from without,
and the fears and feebleness within--to Him in whom
is "`everlasting strength`" and wisdom!

It was pleasant to hear that you were favoured to return home with comfort last year,
but I hear you have been very ill since.
Do mention your health particularly in your next, which I hope may be before long.
I also had an illness in the spring (on the chest), and was brought very low,
and have felt its effects ever since; but, through favour,
am very much in usual health now.
I passed a month or two again at Folkstone this summer,
but it has been a time of great stress on the body for some time past;
the body and the mind sympathise with each other.
I fear I have been too much _poring_ at (as dear Isaac
Penington says) the high mountains of difficulty,
and the many surrounding precipices and snares of the unwearied enemy,
under the feeling of _great_ encompassing weakness.
Yet I think I may acknowledge that, at seasons,
when these appalling things have seemed to come in like an overwhelming flood,
a standard has, in adorable mercy, appeared lifted up against them,
even the love and power of the heavenly Captain,
whose grace He has declared will be found sufficient.
Oh, then, may my eye be ever unto Him, for He is able to pluck my feet out of the net,
yes, to preserve from falling, and to strengthen to run the way of His commandments.
And oh! says my soul, whatever may be the commands of His love,
and the pure requirings of His will,
let all tend to His glory and to the deep humbling and utter abasement of the creature.

I expect you have heard of dear John and M+++_______+++,
as he told me yesterday he had written to a Friend of Aberdeen.
He has been in Essex on the Yearly Meeting Committee.
We met yesterday at our Quarterly Meeting.
After a long time of solemn silence (which is rather unusual in our Quarterly Meeting),
dear Sarah Grubb addressed us in her awfully striking manner,
as to our revoltings and backslidings, the accumulation of riches, etc.,
quoting Haggai 1:9, also Amos 9:9; then, after long pleading with us,
she called on the "`beloved youth`" to come away
from "`Babylon`'s streams,`" and went on in an affectionate,
persuasive way.
Stephen Grellet, also, and Thomas Shillitoe spoke entirely in unison with Sarah Grubb,
particularly the latter,
exhorting against accumulation and a following of
the world in respectability and elegance of living,
saying, "`Taste not of their dainties, for you will find there is death in the pot.`"
Stephen Grellet addressed the mourners in Zion,
those that sigh and cry for the abominations, etc.,
for that there is still left "`an afflicted and poor people`" among us,
exhorting and encouraging such to trust in the Lord.^
footnote:[Zeph. 2:12]

I hope I have not been writing too freely, but I feel knit to you,
though I believe you are farther advanced in the spiritual journey than I: well,
that is no matter; we have all, from the greatest to the least,
need to press forward towards the mark;
and oh that the day`'s work may keep pace with the day!

With dear love to you and your cousin L+++_______+++, I remain your truly affectionate friend,

[.signed-section-signature]
L+++.+++ A. Barclay.

+++[+++The exact date of the following communication is unknown,
but it is supposed to belong to this period.]

[.letter-heading]
To +++_______+++

[.salutation]
My Dear Friend,

You queried of me yesterday how the work of religion was begun in my heart,
to which I believe I gave you no satisfactory answer.
I feel afraid of expressing much on such subjects,
or of "`judging my own self;`" but now, fearing that my silence should have done harm,
I feel at liberty to tell you, I trust,
under a humbling sense of the tender mercy of my heavenly Father.
Ah!
His compassionate regard was to me, when but a child, visiting me by His love,
making me sensible of the depravity of my evil heart, of the exceeding sinfulness of sin,
of my great need of a Saviour, and of His cleansing, sanctifying power; and this,
my dear friend, was not through the instrumentality of any outward means,
but mostly during the time of my being confined on a couch,^
footnote:[On account of spinal weakness.]
and in my secret retirings to wait upon Him.
We were brought up to the use of prayers morning and evening,
and _very_ often went with our governess (who was of
the Established Church) to her place of worship;
this I became uneasy with, when about fifteen, and, showing a dislike to it,
she never pressed it again;
places of public amusement and dancing were also given up about the same time,
and music soon after.
Oh! how tenderly have I been dealt with!
I can never sufficiently remember it.
He has led me gently along, showing me by degrees, first,
what He would have me avoid and forsake, and then what He would have me to do and pursue:
but how many times have I revolted and turned away from His offers,
disobeyed His commands and grieved His Holy Spirit!
I desire to be continually humbled under a sense of these things,
and animated to renewed dedication of heart to Him
who has loved me and given Himself for me;
waiting for the fresh discoveries of His blessed will.

And now, my dear friend,
I know not whether I have answered your question more satisfactorily; tell me,
if I have not--I feel much sympathy for you,
and desire to be your companion in seeking daily
for fresh virtue and nourishment from Christ,
the true vine and word of God,
that we may "`grow up into Him in all things,`" and be enabled
to bring forth fruit in due season to His praise.

I hope you will accept of Isaac Penington`'s letters as a small token of my love.
Perhaps some day next week you can spend with me.

[.signed-section-signature]
L+++.+++ A. Barclay.

[.letter-heading]
To Hannah Marsh

[.signed-section-context-open]
Without date, 7th Day Morning.

&hellip;Well, my dear friend, in saying farewell, I would add,
May the Lord of the harvest more and more raise up living ministers among us,
even from among the poor, the illiterate, and the contemptible in man`'s estimation,
that He alone may have all the glory.
Ah! that which is of and from Christ the life is living and baptising;
it baptises into His nature and spirit;
it ministers His spirit and life to that which is born of God in the hearts of the hearers;
and truly it _has_ a testimony from that in their hearts from which it proceeds; for,
as our Saviour and His beloved apostle declared, it is only those who are of God,
and who know Him that _can_ hear His words or receive the testimony of His faithful servants.
And oh! let me be one of these poor, weak, yet baptising ones,
if ever entrusted with so precious a gift.

[.small-break]
'''

+++[+++Journal Entry]
_12th Month 6th,
1831._--I think I may venture to acknowledge that the good
hand has again been laid upon me--ah! more than once,
but through fear of stepping amiss, and also, alas! the fear of man,
I have only once yielded obedience to what has appeared to be required at my hands publicly.
And oh! what _great,_ what _merciful_ condescension to dispense to such a poor, weak,
hesitating creature a portion of sweet peace and humble quiet afterwards.
Is it presumptuous to regard it as a token for good, that it was even He? And now,
though disobedience has occurred since, and darkness, and deep conflict,
and sore buffetings have seemed to beset on every side, I think I may say,
that it is my most earnest desire that He who has in unmerited mercy begun
to show me of His wonderful dealings and the workings of His love,
would be pleased to anoint my eyes to behold the pointings of His finger,
to open my ears and my heart to hear and receive His precious
teachings and the communications of His will.
And oh! says my soul, that He would bring all within me into pure subjection thereto,
and chase away all the darkening reasonings and fear of man,
that so He may rule and reign over all within me,
and self may forever be abased as in the dust before Him,
who is indeed everlastingly worthy to be praised, loved, and obeyed,
and that by the whole house of Israel!

[.letter-heading]
To the Daughters of S. T. and J. C.

[.salutation]
My Dear Young Friends,

I thought as I shook hands with you yesterday in the cloakroom,
that I felt a salutation of dear love to you,
and perhaps I shall be most easy in acknowledging it,
and telling you that I long to be your companion
in seeking earnestly after a growth in grace,
and in the knowledge of our dear Saviour, desiring to sit as at His feet,
that we may hear the gracious words that proceed out of His mouth,
and learn more and more of His precious ways and teachings.
He said, "`He that loves me shall be loved of my Father, and I will love him,
and will manifest myself to him.`"
May He cause us to love Him more and more!
And let us not be ashamed to show that we love Him by keeping His commandments,
and following as He leads.
I feel earnestly solicitous for your welfare and preservation, now you are as it were,
entering on the world;
and would affectionately entreat you not to be as slack and slow as I have been, but now,
in the morning of your day, to yield your hearts up wholly to our dear Saviour.
Let Him come in and take the government of them upon His shoulders,
and you will find He is worthy to be called "`Wonderful, Counsellor, the mighty God,
the everlasting Father,
the Prince of Peace,`" counselling and preserving you on every occasion,
dispensing of His heavenly treasures to you, and delighting to do you good, yes,
enriching you with His everlasting peace.

That this may be your happy experience is the earnest desire of your affectionate friend,

[.signed-section-signature]
L+++.+++ A. Barclay.

[.letter-heading]
To +++_______+++

[.signed-section-context-open]
Forest Place, Leytonstone, 13th of 4th Month, 1832.

[.salutation]
My Dear Friend,

Your letter seemed in unison with my feelings.
Ah! how tenderly can I sympathise with the depressed, the tossed,
the dismayed--shall I say, from _sad_ experience?
The enemy does indeed know where to attack a weak side, and lays his baits accordingly.
The depths of discouragement I have, at times, been plunged into, I cannot describe.
Surely it is the enemy`'s work, if he cannot puff up, to try and dismay.
Surely our merciful and tender Father would not have
the least babe to be thus discouraged--how tender,
how healing are His wounds!--and when He makes us sensible of our vileness, our weakness,
our foolishness, it is not to discourage us,
but to lead us to apply more earnestly for His cleansing power, His strengthening grace,
His enlightening Spirit.
Oh! dear friend, let us not fear to be thus stripped by such a good hand,
for He empties _that_ he may fill us, and when we are weak then are we strong.
I believe I have greatly suffered from giving way to and drinking in, as it were,
discouragements of the enemy, instead of endeavouring to look upward,
and to breathe after a patient, quiet,
trusting frame--thus vilely casting away the shield of the Mighty.
How does a glimpse of His love and of His almighty power seem, in a moment,
to dispel the clouds of the enemy, and quiet the swelling of the floods!
I hope, my dear friend, I have not been launching out into words,
by writing thus much as it arose, or going, as it were, beyond my measure,
as John Crook says.
I have been indeed tenderly dealt with,
and mercifully upheld from sinking into the very pit of despair.
May I be enabled to love Him much, yes,
more and more to trust and hope in His love and tender care forever!

And now I would turn, dear +++_______+++, to a part in your letter which did _prick_ me,
because I know it is not true, and it ought to be so,
alas!--I mean as to advancement in the path of obedience.
Did you know my proud, rebellious heart, you would be astonished,
and admire that condescending Goodness which has waited very long upon me,
and not cut off in just displeasure.
What amazing condescension is it that He should require of poor, weak,
feeble women (the first in transgression),
to "`speak of the glorious honour of His majesty, and of His wondrous works.`"
But oh! how most awful, and what great need of the "`live coal!`"
My dear friend,
to hear of your faithfulness in this respect has been instructive and animating to me;
the fear of man, and, I would hope, the greater fear of stepping amiss or hastily,
still keeps me back;
but I desire humbly to acknowledge that the few times
when these have been mercifully overcome,
have been followed, very unworthily, by a feeling of peaceful quiet.
How earnestly do I desire that He would ever preserve me in _deep_
humility and abasement of soul before Him--that all may be of Him,
and for Him, and to Him!
The seasons of dismay at the sight of the many dangers and snares around,
and weakness within, one has been at times enabled to look up to Him, in humble trust,
that He is willing and able to preserve and to give wisdom--yes,
that when we step amiss He will humble, and chasten, and reprove,
as His wisdom and tender love see fit.
Writing to you has been cheering to me;
our situation is very solitary (I mean from _genial_ society),
and I feel so very depressed from body or mind.
There is much _indeed_ to depress in looking round on our highly favoured Society.
Ah! we are a backsliding people.
May He melt us, and try us, and not leave us uncorrected.^
footnote:[Jeremiah 4:7]

Have you seen [.book-title]#An Affectionate Address to the Members of the Society of Friends?#
It is written by one who is not a member,
but has long attended Gracechurch Street meeting;
it appears to me to be the burden of his mind for some time past,
and is a close appeal to us indeed.
Ah!
I fear we have stumbled many such honest inquirers, and how sad to think of!
The present is indeed a remarkable time, as it respects the religious world; there is,
no doubt, much good stirring, yet Friends have need to take care,
lest they should be led away off from their foundation.
I much admire a comparison in Isaac Penington`'s works,
where he compares the several sorts of believers to scholars in the school of Christ,
each learning their own lessons and performing their peculiar services,
owning and loving one another in their several places.
But I have been thinking that it will not do for us who have been so highly favoured,
and, as it were, drawn up higher and nearer the great Master,
in our loving and owning of the good in others,
to descend down to their classes and measures--but rather let us keep close to the Master,
and endeavour to draw others up to Him and His _spiritual_ and _blessed_ teaching and government.

I fear you can hardly make this out, so I will say farewell, desiring that,
if you feel anything savoury in it, you will look upwards to Him who only is good,
and gives all good, and not to the poor worm.

[.signed-section-signature]
L+++.+++ A. Barclay.

[.letter-heading]
To Abram R. Barclay

[.centered]
+++[+++In reference to a desire which she had long felt to change her residence.]

[.signed-section-context-open]
Knott`'s Green, 14th of 4th Month, 1832.

I do think it is well to ponder some plan of improvement.
I would rather be farther off, and come and visit at times for a week,
and I felt the same in our last monthly meeting, although it was a sweet one to me.
But I know the many snares laid on all sides,
and desire to be preserved from taking any step hastily,
or hastily giving in to any impression.
There are trials in every place, and in every meeting;
I think that of encouragement and much notice is a great one.
Though I certainly would not choose for myself a residence in +++_______+++ quarter,
I would readily be within a walk of most or many of the members of a meeting,
where we could have a simple, and cheering, and helpful fellowship with one another,
as "`members one of another,`" whether rich or poor.
And I should also like to devote some time in attention
to the _education_ and relief of the poor neighbours,
as objects for bodily exercise,
and recreation and employment of mind--also to be able to invite
my friends farther off to give me their company at times,
for I think where _we_ are _always_ the visitors it has a bad effect in setting up self.
This, dear Rawlinson, is my idea of an old maid`'s life, as mine is likely to be;
and I would also add the belief which has always accompanied my mind,
that a peculiar testimony to plainness and simplicity, both in dress, and furniture,
and manner of living, would be required of me.
This belief has never left me, although I have been inclined myself,
as well as put upon by others, to look at it and reweigh it from time to time;
and I think I have felt willing to give up at any
time that which I desired to take up in sincerity,
only wishing that self may have nothing to do in it,
but to be found walking faithfully to that degree of light I may be favoured with.

With such views,
it is not likely that much interaction with those who live in luxury would be desirable,
though I desire to sympathise with and encourage the good in all;
there is danger of slipping into their spirit,
and tacitly encouraging what ought to be testified against.

[.signed-section-signature]
L+++.+++ A. Barclay.

[.letter-heading]
To S. B.

[.signed-section-context-open]
+++_______+++, 1832.

[.salutation]
My Dear Friend,

_Not_ by way of _return_ do I take up my pen to you; I was, as it were,
_dictating_ a few lines to you yesterday,
when sitting solitarily in the cloak-room eating my sandwich dinner,
and ruminating on the very pleasant time that I had enjoyed with you,
and your many instructive and helpful remarks.
I hope I may treasure them up,
and they may come out again with fresh vigour (as it were) in aftertimes, and,
I should say, with fresh gratitude to Him from whom all good comes.

Dear S+++_______+++, I do hope you will continue to watch over me, a poor, weak, little one,
if one of the flock at all!
And do not hesitate a moment to discourage or caution, as appears right;
for of what vast importance is it to be faithful in this watchful
care towards the poor "`conduits`" (as John Griffiths says),
though indeed I would not arrogate such a title to poor me.
Ah! what a great favour it is to be enabled at times
to trust and hope in His tender care,
and wisdom, and love--that He will lead about, instruct, and humble, and chasten.
May He waken me morning by morning to hear as the learned,
giving me to understand His "`speech`" more and more;
and oh! that He may bring all within me into pure
resignation and deep humility before Him.

How very kind of you to write to me!
I think I may acknowledge the same poverty; but, you know, after a feast a fast is good.
I do trust I was enabled to look only to the source of all good,
before and after you left--we must love Him in our dear friends, and them in Him.
Is it not His love shed abroad in our hearts that causes us to love Him, and,
consequently, those who are doing so also?
It was to me a sweet half-hour in quiet the other evening--it is sweet to seek the strengthening,
contriting influences of His love with our beloved friends.
You will be interested I know,
to hear that Jacob Green has laid before his friends a concern
to visit America--poor man! we must feel for him,
yet also rejoice in the good intended our dear friends there away,
and that the good Hand is laying on another such an honoured embassage.
How instructive is the account of William Caton in John`'s [.book-title]#Select Anecdotes;#
I read it yesterday between meetings.

I must hastily conclude, hardly knowing what I have written,
except that it is very different from what I thought of yesterday.

[.signed-section-signature]
L+++.+++ A. Barclay.

[.postscript]
====

How many crannies has self to creep up into!
I do wish they may be all searched thoroughly.

====

[.letter-heading]
To the Same

[.signed-section-context-open]
+++_______+++, 1832.

It was so sweet to salute +++_______+++ in the cloak-room a week ago;
she spent a few hours with me also on fourth day--how
favoured I have been this long solitude with helps!
We can sympathise one with another (though she is
so much further advanced than poor halting me),
being similarly situated in some respects; well,
it is animating to meet with such fellow travellers.
I do hope our (such) meetings are not _entirely_ to sigh and to mourn over the desolations,
but that we are sometimes enabled "`to think upon
His name,`" whom we do desire to love above all.

[.signed-section-signature]
L+++.+++ A. Barclay.

[.letter-heading]
To S. A. D.

[.salutation]
Dear Friend,

I think I shall hardly feel easy longer to refrain from expressing to you,
how much I feel for you and several other dear young
women in the station of servants in our meeting.
I think I can, in some degree,
sympathise with you in the trials and difficulties that are often your lot,
as well as in the temptations that surround you on every hand;
and I think I may say I earnestly desire your preservation from that which is evil,
and your encouragement in that which is good.
"`Abhor that which is evil,`" my dear friends,
"`cleave to that which is good,`" even in little matters that may seem but trifles.
Nothing is trifling or little that has a tendency (in ever so small
a degree) to separate us from the love of our heavenly Father.
He is of purer eyes than to behold iniquity;
He is following after us with His gentle reproofs;
He is drawing us with the cords of His love; let us, then, run after Him,
let us listen to His "`reproofs of instruction`"--they are
indeed the "`way of life,`" and the way of peace also.

You are much exposed to temptations, both among your fellow servants and otherwise;
oh! may it be the earnest engagement of your minds
_daily_ to seek after ability to withstand them,
and to be faithful.
I believe a few minutes spared from our sleep for this purpose will be no mean sacrifice;
but even we may lift up our hearts, or breathe after Divine help,
while our hands are engaged in our various avocations.
Such feeble aspirations have often been wonderfully answered, and we may,
again and again, be enabled to say, "`Hitherto has the Lord helped us!`"
To be a faithful servant is a very honourable thing;
and I do believe if Friends kept their places,
they would be a blessing to the family where they live,
a check to everything that is wrong, and, like the good salt,
seasoning those around them.

That thus it may be with you, my dear friend, and other of your friends and neighbours,
is the earnest desire of your sincere friend.

[.signed-section-signature]
L+++.+++ A. Barclay.

[.letter-heading]
To S. B.

[.signed-section-context-open]
Forest Place, 6th Month, 1832.

[.salutation]
My Dear Friend,

I have been very fearful since yesterday,
lest I should have hurt you by any manner of mine
when touching on the subject of trial to us both,
which I know you will believe I should be very sorry to do.
I know I am often apt to use strong expressions to convey my meaning, and sometimes,
on such occasions, when nervous about it,
omit to put in those palliatives or explicatives
which I afterwards see might have been desirable.
It would _indeed_ grieve me to know that I had wounded you, for I love you dearly,
and believe you only acted for the best, and that the blame lies at my door.
I do hope it will be a useful lesson to me to dwell alone and keep silence,
as in days that are past.
Alas!
I fear I am going _downhill_ sadly!
I desire the Divine correcting and humbling hand may not be stayed in the least;
and oh! that I might be enabled to wait continually on Him
for a renewal of strength and preservation from fainting.
I know that it is the enemy`'s work to discourage and dismay;
and he is particularly active and stirring where it is the weak side of the vessel.
How well can I enter into the psalmist`'s words,
"`Let not the pit shut her mouth upon me!`"
Ah! if it had not been that a hand of help was held out (many of us can say),
then our enemies had swallowed us up quickly, and the proud waves had gone over our soul.
I do hope the same merciful hand may be underneath still to support,
although it may be appointed to "`correct in measure.`"
Dear S+++_______+++, do crave for me that the work of sanctification may not be marred,
by any means,
and that reproach may not be brought by me on that cause which is indeed precious to me,
nor any of its humble followers stumbled or hurt.

Farewell, my dear friend; when we may meet again I know not.
If I might, I would like to stay down in the western counties out of sight, and,
one is ready to think, out of danger; yet there the enemy could follow, could he not?
and I am reminded, while writing,
of a remark of Edward Smith`'s to dear John on this subject when in Cornwall twelve
years ago--he reminded John of Lot fleeing to the little city and how he acted.
Do write me a few lines, and tell me whether I wounded you, dear, will you?
it will be a relief.
From your affectionate friend,

[.signed-section-signature]
L+++.+++ A. Barclay.

[.postscript]
====

P+++.+++ S.--If you see dear Sarah Grubb, give my dear love to her;
I longed to shake hands with her to intimate near feeling and unity,
if such a child might say so.

====

[.letter-heading]
To the Same

[.centered]
+++[+++In reference to a manuscript which had been lent her to read.]

[.signed-section-context-open]
Forest Place, 19th of 6th Month, 1832.

[.salutation]
My Dear Friend,

I do not think it is a thing that should be much out; there strikes me a danger,
if read by one of an ardent, grateful heart,
lest such a one should be improperly excited.
Do you remember a letter rather on this subject (overwarmth) in [.book-title]#John Kendall`'s Selection,#
second volume, near the end,
signed by (as far as I recollect) R. G.? it is instructive to me, and has often been.
I remember I felt a great fear, from eleven to eight years ago,
when such a most awful subject was first thrown before me,
of reading accounts of the exercises of Friends relative to it.
Ah! how did I, and do I, desire that all may be genuine,
no mixture--that _nothing_ may move forward but the
Master`'s voice and power--that all may be of Him,
and for Him, and to Him, no matter how much to the humiliation of the creature!
What an instructive letter it is!
How striking is the allusion to "`various washings,`" etc.
May patience have her perfect work in all these probations!
Like a picture drawn to the life, how cutting is the allusion to Moses and Aaron!
The part I told you of, as to fear of man, is in the postscript.
Your kind note was very relieving to me, dear S+++_______+++,
but indeed I am not worthy to be a "`burden-bearer;`" nevertheless,
I do wish to be willing to be anything or nothing.
If permitted to mingle together in deep exercise with the living in Israel,
what a great favour it will be!
I thought today, in our monthly meeting at Ratcliff,
if I might but be enabled to breathe after the arising of Him who is our life,
it is all I desire.

Yesterday, I had the great _treat_ of a visit from +++_______+++; I had not had her company,
except in meeting, for nine months before.
She was encouraging, so I feel a little brightening;
for I assure you I have been often ready to give up going into Cornwall,
and to sink into _naughty feelings._
Ah! surely I should fall by the hands of the enemy, did not mercy hold me up; may I ever,
then, trust and hope in such great love, and believe in such a powerful Friend!
I intend setting out on fifth day next, to sleep at Staines,
and take the Exeter coach next day.
How formidable it does look to go and visit my friends so
far and many temptations in going from meeting to meeting.
Do, dear, crave my preservation every way.
I must not forget dear +++_______+++`'s burden.
"`Keep silence before me, O islands, and let the people renew their strength,`" etc.

[.signed-section-closing]
Farewell, very affectionately your friend,

[.signed-section-signature]
L+++.+++ A. Barclay.

[.letter-heading]
To +++_______+++

[.salutation]
My Dear Friend,

I hope I am not improperly intruding myself upon you,
but having felt in times past much love and sympathy for you,
I fear to omit expressing at this time (I trust under the influence of the same love),
how grieved I was to hear, the other day,
that you had in outward appearance shown a diminution of attachment
to those principles which I know to be precious to your dear mother,
and which I hoped were becoming increasingly so to you--the more so,
as the profession of these, I believed, cost you much trial and sacrifice.
Ah! my beloved friend,
I hope you have not been discouraged from the _noble_ and faithful avowal of them,
by the haltings, and slips, and falls of any around you.
Truth is the same though all men forsake it--it is unchangeably good and valuable,
worthy (can my soul say) to be bought with the sacrifice
of all that is near and dear in the world`'s account;
and it is exceedingly powerful too, mighty to subdue hosts of inward enemies,
and to sustain in outward fights of affliction,^
footnote:[Heb. 10:32]
yes, able to preserve on every hand, and to crown at last with life and glory!
Oh, then,
if we have been favoured with the knowledge of the blessed truth as it is in Jesus,
and have received of His grace, and hearing the voice of His wisdom,
have felt the preciousness of it,
and been enabled to give much for it--oh! let us not sell it under any consideration,
or even show to others that it is less estimable in our eyes.
Let not the smallness of the outsteppings,
nor the apparent lack of reasons for withstanding them,
lead us to yield to the temptations of the vain mind.
The rise of evil is but small at first, and easily withstood;
so also the reproofs and leadings of instruction are small
and easily despised by the reasoning mind--nevertheless,
they are full of strength and peace to the obedient,
and remain to be the "`way of life!`"

Farewell, dear +++_______+++, I hope I need not apologise for this;
I believe it has been written in true love,
and under a deep sense of my own weakness and need,
"`every moment,`" of the preserving power of Him who first visited me in tender love,
and mercifully enabled me to follow Him.
May He humble, and purify, and lead us as He pleases,
only to make us what He would have us to be--His dear children, His faithful servants,
to the praise of His great name!

[.signed-section-signature]
L+++.+++ A. Barclay.

[.letter-heading]
To Hannah Cruickshank

[.signed-section-context-open]
Forest Place, Leytonstone, 1st of 10th Month, 1832.

How could I feel one with you and partake with you, dear love,
under the chastising hand of our merciful heavenly Father!
It was with me as I fancied it was with you--I had
hesitated throughout the meeting that morning,
and it broke up without the utterance of a few words
that seemed laid upon poor halting me:
and now also,
I may say the same to my shame!--last fifth day being a similar day of trial to me,
and though the sign I had requested was mercifully given,
yet the _many_ fears were permitted to out-balance the belief of duty.
And what has been the consequence?
Woe indescribable! for how sad is the consideration of having
grieved Him who has dealt so very tenderly with me,
who has borne long with my hesitation for years,
has graciously revived His work as in the midst of the years,
has condescended to my great weakness,
leading me gently along--and now lately has helped and preserved
me every way in my long journey into the West,
and in condescending goodness has followed the little offerings
required with a feeling of peaceful quiet wholly unmerited!
What can I say more to set forth His goodness?

But oh! my dear friend, let us not give way to the enemy`'s discouragements;
he will try to make it appear there is no hope,
that we shall never be visited alike again,
taking advantage of the sense given us of our shortcomings--and
perhaps even to excite to a dread of ever being so tried again.
But our heavenly Father deals not so with us;
He would only teach us _obedience_ by the things which we suffer,
that we may be humbled under a sense of our utter unworthiness and the
_condescending_ goodness which thus lays His tender hand upon us.
Ah! what were we, and what our Father`'s house, that He should thus look on us,
and even cause His word to burn within us?
Alas! that we should so requite Him!
I have found, in my short experience,
every act of disobedience has given the enemy advantage over me,
so that He has brought floods of discouragement over me,
and everything around me has appeared to go wrong; and not only so,
but the power to distinguish the voice of the true Shepherd,
to discover the approaches of good, seems lessened.
On the other hand, every act of simple, humble obedience has tended to strengthen good,
to strengthen the hands against the enemy--yes, even to unite to the best Friend!
I often remember the expression of a dear Friend,
in a meeting where I was--"`in your obedience your
soul shall live;`" she also supplicated for such.
I believed it was for me, but alas!
I did not give up, and I have ever since regretted the omission, now five years ago.
But you will say to me, If you know these things, why do you not do them?
Alas! my leanness, my backslidings!
May I be enabled to yield up to His power, that He may undertake for me,
working in me both the faith and the obedience, that all may be of Him, and for Him,
and to Him, to whom only belongs praise, but to the creature utter abasement.
I feel now ill with conflict of mind and the dread of meeting-days;
but oh! that all may be brought into holy resignation, into pure subjection,
even if it cost me life--it seems truly like laying down our lives for the brethren,
I have often thought.
Our meeting is a trying one to my _proud_ nature;
to appear like a fool among my own family, and other gay, rich, wise folks,
is very crucifying--but oh! may I be brought to submission.
Surely the vows entered into must be performed.

[.signed-section-signature]
L+++.+++ A. Barclay.

[.letter-heading]
To E. R.

[.signed-section-context-open]
Forest Place, Leytonstone, 29th of 10th Month, 1832.

[.salutation]
My Dear Friend,

I have often been reminded of you the last week,
my brother being confined to the sofa with a sprained knee;
but do not think I _needed_ such a stimulus to bring
you to my affectionate remembrance--far from it,
I assure you.
In my many solitary hours, since my return home,
you have _often_ seemed my mental and instructive companion.
Yes, dear friend, it is instructive to remember the sincere-hearted, the faithful,
the living ones, however solitary and hidden their lot may be.
It does excite at times an earnest desire to be made one with them,
even in that precious fellowship in which a cleansing is witnessed from all impurity,
and this stands not in words but in power;
and does not this sweet remembrance seem to shed over us a glow
of praise to Him who is the glorious giver of their brightness,
and we are stimulated thereby to love Him above all,
and encouraged to trust in and follow so good a Master, nothing doubting!

Did I tell you I had much conversation with +++_______+++,
on the evangelical opinions (so called) creeping in among us?
Her faithfulness in contending for the faith,
in the different opportunities in which the conversation turned on the subject,
was very instructive to me.
She could speak from real experience,
and that seemed to have a convincing effect in one or two instances--but
it was affecting to hear how prevalent they were!
They have a very plausible effect, exciting the affectionate feelings, and, I fear,
tending to stir up or to strengthen that which should be weakened and laid low.
I have been much enjoying [.book-title]#Isaac Penington`'s Works,# at some leisure times;
how sad that these, as well as Barclay`'s [.book-title]#Apology,#
should be not united with by many in these modern times.
Surely, are we not backsliding from what our worthy predecessors were called out of,
and to testify against?
J+++_______+++ W+++_______+++ has been visiting our different meetings.
How greatly do we need true, faithful,
baptised elders--what a great blessing such are to the Church and the ministry!

I have had much time, at my needle,
in ruminating on the many mercies conferred on a
very unworthy one (during) the past summer,
as well as the many lessons set before me to learn in that time--lessons of caution
as well as of stimulus--but alas! how slow to learn to believe and trust.
Since my return it has been a season of deep conflict and besetment,
known only to Him who searches the heart; and were it not that His arm was underneath,
I should have sunk indeed.
May He bring all within me into acquiescence with His holy will,
whether in doing or suffering;
for how unworthy am I of the least of all the goodness and truth shown me!

Dear Daniel Wheeler, I suppose you have heard,
has obtained a certificate for religious service in South Africa, New South Wales,
and the Society Islands.
How fully can we unite with _such_ missions,
and rejoice that the good Hand is laying upon another dear servant,
attracting even to "`the ends of the earth!`"
Well, my dear friend, I fear I shall try your eyes.
I often recur with pleasure, and, I hope, with gratitude, to time spent at Marazion,
both beside your couch and down on the rocks.
It was sweet to sit beside you,
and at times "`take sweet counsel together,`" and may I not say,
to feel at times the tendering, strengthening influences of our heavenly Father`'s love.
When it is well with you,
do crave the preservation of a poor child from snares on every side, and above all,
in faithfulness and humility.

With the salutation of dear love to you both, I remain your nearly united friend,

[.signed-section-signature]
L+++.+++ A. Barclay.

[.postscript]
====

P+++.+++ S.--My love to R+++_______+++ and M+++_______+++,
also your brother and sister L+++_______+++,
and dear +++_______+++, to whom I could not but feel much attracted in love;
may her eye be more and more attentive and fixed on the great and good Master,
humbly waiting for His precious teachings and the discoveries of His will,
that so she may be moulded according thereto,
and thus become of the number of His dear handmaids and children.

====

[.small-break]
'''

+++[+++Journal Entry]
_12th Month 1st, 1832._--Perhaps for some surviving dear brother or sister,
a testimony lives in my heart to the gracious dealings of the Lord my God to me,
a poor unworthy creature, unworthy of the least of all His tender mercies,
and of His great goodness and truth shown unto me.
In my late journey into Cornwall, to see my dear friends there,
He preserved me from disease and death (when not far off) and brought me safely home.
He led me gently along, and made hard and bitter things easy and sweet,
when He had subjected my will into pure resignation--for
oh! let all the praise be given unto Him.
He _gives_ to believe, He _makes_ willing and obedient, He strengthens, He preserves; yes,
there is forgiveness too with Him, and plenteous redemption!
He, of His own free grace in Christ Jesus, pardons iniquity,
and blots out the transgressions of those in whom He has wrought repentance.
And now, oh my Lord God,
what can I render unto you for all your great goodness and mercy?--the
pure service of my heart--the holy subjection of my soul!
But oh!
I am weak, very weak; be pleased to undertake for me;
work in me that which is well-pleasing in your sight.
May your will be done in me and by me,
to the utter abasement of the creature and to the entire
subjection of the creaturely will--but if it may be,
to your glory and the praise of your great name forever!
