== Chapter II

To S. B.

Forest Place, Leytonstone, 14th of 1st Month, 1833.

My Dear Friend,

Hearing of an opportunity of sending you a few lines, I willingly avail of it,
and indeed think I have cause to apologise for not doing so sooner;
but I know you will bear with me, and not think I love you the less from keeping silence.
I have often thought of you, dear +++_______+++, in your little simple retreat,
and have longed to follow your example; perhaps some of these days I may, if so best.
But I have been thinking that, no doubt, in even ever so quiet a retreat,
our unwearied enemy contrives to creep in,
and vary his temptations according to our circumstances; and then again, outwardly,
every place has its trials.
The main thing seems to be to endeavour to seek after best direction,
and to act accordingly,
trusting that He whom we desire to serve will cause things to work together for good,
and support us under them.

Dear +++_______+++, I can sympathise with you more than I can readily express by writing.
We must not look too much at what others say or think of us; but,
if we have weighed things well, go simply forward.
What a favour it is to feel quiet in reference to any step! ah!
I have need of your sympathy and prayers in this respect.

I had a very pleasant and satisfactory journey into the West, and had comfort and,
I hope, profit in being with my dear old friends there.
I found them not cooled by a seven years`' absence,
and though there were many alterations, by death and otherwise, in that time,
it was sweet to mark the spiritual progress of many,
and to be favoured to feel when together the cementing,
strengthening influence of Divine love.
It was a great trial on my strength visiting so from
house to house (almost) in every meeting,
among my dear old friends, and I stopped over their autumn quarterly meeting,
as well as that in the summer; but strength was mercifully granted,
and preservation also from the sad disease^
footnote:[The Cholera.]
that sometimes was not far off, which was indeed cause for humble thankfulness.
I took tea with dear William and R+++_______+++ Byrd in my way back,
and found them better than they had been, though William is much altered.
I also made a point of going to see dear S. Tuckett at Looe
(besides seeing her at quarterly meeting in 6th month),
and much enjoyed an hour and a half on the rocks by the sea with her,
listening to her animating yet cautionary conversation.
She is as lively as ever, both in meeting and out of meeting,
and seemed as it were raised up afresh, having kept at home two years before.
Speaking of the enemy`'s transformings, she said, "`He can imitate the best things,
but he can never bring into quietness, any more than the Egyptian magicians could,
with all their skill, make one of the least things with life;
and he can raise many mountains, but not remove one.`"
I hope to remember her words; I do not expect to see her again.

Since returning home, it has been a time of much conflict with me,
as well as that I have had much solitary time for
looking back at the many favours of the summer,
and the many lessons set before me to learn,
also the deficiencies and weaknesses on my part.
May all tend to humble as well as excite to love, trust in,
and obey Him better who has dealt thus tenderly and bountifully with me;
and oh! if it be His merciful way with me continually to abase and to strip,
to plunge and to wash, let it be so,
if there may but be a preparation thereby witnessed to receive
and to give from His good hand more purely His praise.

L+++.+++ A. Barclay.

To +++_______+++ and +++_______+++.

My Beloved Cousins,

Is it not sweet, when socially meeting with our dear friends,
or partaking of a bounteous meal,
to be favoured to feel something of our dear Saviour`'s strengthening
company among us?--as when He came and stood among His disciples formerly,
when the doors were shut from outward intruders,
and He saluted them with the language of "`Peace be unto you!`"
I thought I was a little sensible of this, this evening,
and longed that we might open the door to such a precious visitant.
I would also acknowledge, that I was ready to query of you,
my dear young friends:--Have you not felt His gentle knockings at the door of your hearts,
accompanied by the language, "`Open to me, my sister, my spouse,
for my head is filled with dew,
and my locks with the drops of the night`"? Have you not heard His clear,
though whispering voice, "`This is the way,
walk in it,`" when you have been inclined to turn
out of the path of self-denial and peace?
Have you not felt the gentle, persuasive pressure of His hand upon you,
with the encouraging assurance, "`'`Fear not; for I am with you; I will help you:`' come,
follow me, I will lead you to enduring substance, and my peace will I give unto you,
not as the world pretends to give!`"

Dear friends, when Jesus calls you, haste after Him;
leave all to run after Him in the way of His secret requirings,
and heed not what others say or think;
for they will not be able to intermeddle with the peace which your
dear Saviour will give to all those who love Him,
and keep His commandments.
His love, His manifesting himself to you, His abode with you,
are well worth all you can part with or sacrifice for His sake.
Therefore, love to wait upon Him, to hear His words, His commands,
and the restraints of His love, and do not shrink from them;
His words are with power to the willing, but they will judge the disobedient hereafter;
and truly His reward is with Him, even a peace the world can never give nor take away!

L+++.+++ A. Barclay.

+++[+++Journal Entry]
Leytonstone, 1st Month 26th,
1833.--Oh! you who have condescended to be my refuge and my deliverer from my childhood,
ever near to guide, to strengthen, and to preserve,
be pleased to look down upon me with compassion in this season of extremity and proving.
I beseech you to counsel and direct me, to show me what you would have me to do,
and oh! bring my mind into quiet resignation and humble submission thereto,
however trying it may be to the creaturely part.
You have loved me, and given me to desire to serve and love you more and more:
do with me what you will,
only let me not depart from you or bring reproach on your precious cause, but rather,
if it may be, contribute towards the exaltation and spreading thereof,
both by example and precept, if so your will ordains.
Yours, O Lord! is the kingdom,
and yours also is the power--may all praise and glory be
ascribed to you forever by my poor soul and all others.
Amen!

To +++_______+++.

Dear Friend,

It was pleasant to me to have that call from you.
In considering our conversation afterwards, I was fearful lest I should be thought,
while lamenting the state of things among us,
and the ill effects that riches too often bring with them, to have encouraged,
in any degree,
an improper judging of those who are favoured with
many talents in a temporal point of view-believing,
as I do,
that such a disposition would much hinder our progress and growth in that
humility which leads to preservation and to strengthening grace.
We know that a birthright in the Society will not give possession of the truth,
and we have great reason to magnify that grace by which we have
been brought to this precious knowledge and possession,
and to seek after that fear of the Lord which will preserve
from the many snares of death surrounding us.

With respect to the awful subject we a little adverted to,
towards the end of our conversation,
and in which it struck me you were a little discouraged--though
I feel myself but a child and a partaker with you of this
burden (unworthy as I am)--it seems with me to tell you,
that while sympathising with you under these feelings,
and pondering our similar situation,
the words addressed to one of the churches formerly revived in my remembrance,
as conveying instruction to us both,
"`Fear none of those things which you shall suffer,`" "`be faithful unto death,
and I will give you a crown of life.`"
Provings and trials may be permitted us for our good;
it is good for us that self should be thus battered and brought to nothing,
yes crucified in us, that so Christ may live in us, and act in us,
and have the praise of all in us.
It is no sin to be tempted, if we do not yield to the temptation.
Sometimes the enemy, if he cannot exalt, will cast a flood of discouragement upon us;
but oh! let us not look at him or listen to him, for he was a liar from the beginning;
let us look up to Him who is mightier than the enemy,
who can lift up a standard against him, yes, in a word,
restore a calm confidence to our troubled minds.
In the course of my short experience,
I have thought that the seasons of sore conflict and discouragement
that I have passed through between the times of public exercise,
had been permitted for my further purification and humbling;
and oh! if they should be the means of a capacity being attained
to receive and to give more purely from His good hand,
my very soul craves it may not be spared, but that I may not come forth of the furnace,
until the trial of my faith may be found unto His praise, and honour, and glory!

Well, dear friend, I have desired for you that nothing may hinder you in any way,
or the work to which you have believed yourself called to put a hand, but that,
patiently enduring the baptisms and provings that may be necessary,
you may become more and more skillful in discerning the will of the good Master,
and faithful in doing it.
I have often remembered, with instruction,
a remark of John Churchman`'s--"`Ministry must be of necessity, and not of choice;
there is no living by silence or by preaching merely.`"
Ah! surely our living must be in subjection to the Divine will.
If silence is commanded us, either for the benefit of others or for our own proving,
let us resignedly acquiesce-if it is ordered for our own correction
or humbling (we having fallen short or gone beyond our duty),
may we be instructed thereby and not discouraged improperly.
It is a comfort to believe that our heavenly Father knows all our hearts and their sincerity,
that we desire to be His only, His wholly;
let us lean upon His good hand that we believe has been laid upon us (in great condescension!);
if we do wrong, He will correct us; if we slip or hold back from fear, or, if,
on the other hand, run on too fast,
He will humble and instruct us in His wisdom and tender love.
Let us trust in Him, and crave of Him that He will lead us by the hand safely along,
being children; and no matter how He humbles us, or in what way,
so that His great name be not reproached through us,
but rather let it be glorified and exalted forevermore!

L+++.+++ A. Barclay.

TO E. R.

Leytonstone, 22nd of 2nd Month, 1833.

My Dear Friend,

Your kind and very interesting letter surely deserved an earlier answer,
and I fear I must almost have appeared ungrateful for it;
but did you know how it has been with me the last three months,
you would willingly excuse me.
I have been glad to avoid letter-writing all I well could,
and I knew you would kindly bear with me,
and not attribute my silence to a diminution of that near and dear love which I have
always felt for you ever since we first were together twelve and a half years ago,
and which has gone on increasingly ever since we have been separated these seven years.
I hope I am not writing disrespectfully to one so much further
advanced in the spiritual journey--the less may love the greater,
and true love seems to cast down all difference of age.
I have wondered at this effect in me latterly,
for I am naturally so much afraid of those who are older than myself.
Before I enter upon your letter, I feel at liberty to inform you, my dear friend,
as I know you take an interest in what concerns me,
what has been the absorbing subject with me this winter.

I believed I did hint to you (and no other), when in Cornwall, how I was situated here,
and how I have felt burdened for some years past.
I found, on my return home, that my dear brother`'s mind was turning to Croydon,
which was very agreeable to me; but, after pondering the matter for some weeks secretly,
I did not feel easy about it.
It seemed taking him from here, where his duties, and interests, and pursuits lie,
and where his services are increasingly valuable
and needed in our meeting--merely for my sake,
when, after all, my mind would not be relieved as to furniture and way of living;
and there, we should be among a body of friends--here, we are out of sight,
as it were-which appeared to me to render it more important that one should be faithful.
Just at that time, my eldest sister`'s plans were changed, and she left Birmingham;
so that it then seemed to me as an opening of the right time, and that,
if I stepped the first, perhaps she might be induced to unite with dear R.,
and though not a Friend,
yet would suit him in many respects better than I.
It will take too much paper to say much more,
except that it has been, as you may suppose, a season of great sifting and trial,
of extremity, I might say, fully known only to the Searcher of Hearts.
I have desired it might be one of His gracious opportunities
for the carrying on of His work in me,
even the bringing down of the creature and the exaltation of His name or power!

Since the time I allude to, I have looked at it in various ways--as it were,
tried the fleece both ways--and have, amidst reasonings and trials without and within,
concluded (and this conclusion has been attended by confirming and peaceful quiet) on
removing to Croydon (if nothing prevent) in the summer to take a simple cottage there,
and have a young woman Friend as my companion and fellow-helper.
This I do not consider to have been fully decided on till this week;
for I have felt fearful of stepping all along,
and indeed have borne what I have felt as a burden these six years nearly,
so I do hope I am not hasty.
You would judge it must be painful to think of leaving my dear brother.

On now reading your kind letter again,
I note your observations on depressing feelings as to your removal,
and it comes rather pat to me now; not that I feel so at this time,
but I fully expect to be so tried, as the time draws nearer to the 6th month.
It is a comfort, as you say, to believe that it is not in displeasure that we are thus,
for a season, deprived of the sensible evidence of Divine approbation,
but in Fatherly love, to try our faith.
Ah!
He knows the sincerity of our hearts,
and our earnest desire that we may be preserved from bringing
reproach on that cause which is indeed precious to us,
and which He alone has made so to us.
I have had cast before me (both outwardly and inwardly) the many
and specious snares which our subtle enemy spreads in every place,
and suited to every circumstance and situation in life.
It is so indeed! but is there not One mightier than He? Should this sight,
and that of our own great weakness,
hinder us from stepping forward in humility and faithfulness,
when the way is plainly cast up before us?
I have thought that a proper sense of our own weakness and of the enemy`'s snares,
will lead us to seek more earnestly and depend more simply on His help and strength,
who will preserve the simple and the faithful.
I suppose I must prepare for evil report, and, of the two,
I would rather have it than good.

Last quarterly meeting we drank tea at P. B.`'s, and met Daniel Wheeler, John Wilbur,
and George and Ann Jones.
There was a most sweet opportunity after tea,
when Ann Jones very strikingly addressed Daniel Wheeler and John Wilbur.
I shall not forget the time I think.
We parted in sweet fellowship.
Dear John Wilbur is now on the water--he is much in our minds.
I hope you have seen his letters to George Crosfield;
some of us think them very valuable, and desire they may open the eyes of many,
so as they may avoid the precipice they are drawing towards;
but others cry out against them sadly,
and say they will do mischief by laying things so open.
I must own, I am of my brother John`'s mind,
that it is not a time to shrink and to cover things all up, and daub, as it were,
with love and meekness.
It is better to search to the bottom of things, and to hold forth the good old way,
and show how good it is.

It was very sweet to spend a half-hour with Sarah Grubb before
last quarterly meeting--a treat I have not had for a year before,
though living so near.
She told me, when speaking of these times of dismay,
that she was so much struck on her return home (after
being with her children in Suffolk all the summer),
to find those opinions we deplore so spread among us.
She is not well, and no wonder;
it is enough to weigh down all our dear Friends who
see deeply and feel deeply--and how few we have!
George and Ann Jones`'s late visit was, I do believe,
very helpful at this juncture to the rousing of some,
and to the strengthening and encouraging of those whose knees are
ready to smite together for very weakness and fear.

It is very pleasant to hear of those who run to and fro down in your corner--may
their labours be blessed to the help and gathering of many!
Sarah Grubb has been holding many public meetings in and around London;
very large and striking they have been.
Alas! our poor Society--what more can be done for us that has not been done?
How sad that we should be a stumbling-block in the way of inquirers who unite with,
and receive comfort from our principles,
as described in the writings of our early Friends; but, when they look at the people now,
they go away sorrowful!
Perhaps, though, this is owing to their looking too much at the people,
instead of the principle!

L+++.+++ A. Barclay.

To Hannah Cruickshank.

Leytonstone, 3rd of 6th Month, 1833.

My Dear Friend,

It seems very long since I heard from you,
yet I know that true love does not depend on frequent communications,
but on our being united in spirit, devoted to the same good Master, who is our life,
and head, and heavenly vine,
and therefore His Spirit pervades all the living members
of His body (the Church) and branches in Him,
the true vine--which, as it unites them to Him, and gives them life, and freshness,
and fruitfulness, so, also, unites them one unto another,
and gives them to partake of the true fellowship.
And how do I long, my dear, that we may not in any way go back and lose this (if, indeed,
such a poor weak one as I may lay claim to the smallest degree of it),
but rather seek after an increase, even the heavenly increase,
a growing up more and more "`into Him in all things.`"
And I have just remembered a description (in Isaac Penington`'s works) how this
precious and desirable work is to be carried on and perfected in us;
it is very striking, and I will copy it.

As the power of the Lord began the work,
so the same power alone is able to go on with it and perfect it;
and it will go on with it and perfect it upon the same terms it began, and no other.
How were the terms at first, but on a giving up of the soul in the faith to the Lord,
in the sense of His love, and goodness, and mercy, touching, and drawing,
and making willing?
And how is the standing, but in the same giving up still; in abiding with the Lord,
in hearkening to the voice of the Lord,
in waiting for the wisdom and counsel of the Lord?

I do not regret copying this, for, in so doing, I myself have been instructed,
having been lately almost ready to flinch and look back--but how good is our heavenly
Father in bringing instruction and encouragement
to us in low times and seasons of faintheartedness!
I want to know how it has fared with my beloved friend,
of whom I have lately heard an interesting account that your bonds
have been broken through condescending goodness and Divine strength.
I may say it rejoiced my heart, and I was reminded of the time we first met, namely,
at dinner at Thomas Christy`'s, during yearly meeting, when I sat by you,
and felt knit to you under a belief that the same good Hand
was upon you that I felt to be upon me--most unworthy as
I am to partake in ever so small a degree of such a burden.
Ah! my dear friend, may He in mercy take us as by the hand, being children,
and lead us safely on in the way He is pleased to cast up for us;
and let us lean on His good hand, trusting to His love and wisdom,
that He will correct and humble us when we do wrong,
and show us the dangers we may be near falling into;
as well as that He will strengthen us to do His will faithfully and humbly.

Perhaps dear +++_______+++ will have given you an account of yearly meeting better than I can.
It was a time looked forward to with much dread by many;
yet it was found to be owned and favoured by Divine regard and goodness,
in the midst of much that was trying and almost overwhelming--to
see how we are going back (as it were) to the beggarly elements,
and throwing away the testimony delivered to our worthy predecessors,
in the morning of our day as a religious Society, to hold forth to the people.
But, as I said before, Divine goodness did qualify some of His poor, feeble,
oppressed servants to stand up for the good old way,
to contend for the faith once delivered to us;
as well as to encourage the fainthearted to wait in patience and stillness,
for the arising of Him who would scatter His enemies,
and give those who suffer with Him to reign with Him forever.
Some of us regretted that we had so little of solemn silence in our different sittings,
compared with other years,
when we had been more favoured with that stillness in which
pure worship and prostration of soul are witnessed.

I am sorry to hear of your health being so poorly;
I doubt the exercises of the mind have to do with it.
May you, dear love, be brought safely through all,
and be strengthened more and more with His might in the inner man.
The more we are purified the better;
and should these conflicts be in mercy permitted for that end--that
we may be more fitted to receive and to give from His good hand
more purely--let our very souls say amen to it;
and may we not come forth of the furnace until the
trial of our faith be found unto His "`praise,
and honour, and glory.`"

Farewell very dearly; when you are well enough and free enough, do write to me,
and believe that I am your sincerely affectionate and sympathising friend,

L+++.+++ A. Barclay.

To E. R.

Leytonstone, 21st of 6th Month, 1833.

My Dear Friend,

The sympathy, as well as the good wishes of one`'s friends is very acceptable,
particularly at a time of tossing, and fears, and dismay, as it has been with me of late,
relative to my removal to Croydon in two weeks`' time.
It is no small trial of faith to see my dear brother`'s health so indifferent,
as well as to think of leaving him a solitary bachelor;
and it seems to increase as the time draws nearer.
Sometimes it has seemed as if the floods were ready to overwhelm,
lifting up their waves on high; yet there has hitherto been a Hand underneath to support,
even in the lowest times, and He does sit as on the flood, and can stay it; yes,
He is mighty and good,
and can make a path "`in the great waters,`" and drive Jordan back!
May He still be near to sustain and to strengthen,
causing to hope continually and yet to praise Him more and more!
I was much struck the other day with the fifty-first chapter of Isaiah,
calling on Israel of old to look back at what had been graciously done for them,
thus leading still to trust and to hearken to His voice, fearing not man.
Oh! it has been a time of deep plunging since yearly meeting;
but help has been mercifully handed the last day or two.

Dear John has had many encomiums of his book.^
footnote:[Diary of Jaffray, and Memoirs of Friends in the North of Scotland]
I believe he gives all the praise to the great Giver of every talent;
I hope it has relieved his mind of much burden towards our poor Society.
His health really suffered, while writing the two last chapters, from exercise of mind.
It will be a comfort to have him watch over me at
Croydon (as well as dear John and Hannah Marsh).
I do desire that, while partaking of such congenial society there,
I may not forget the benefit of sitting alone and keeping silence.
There will be objects to interest me in the schools and the poor,
but I hope I may be preserved from activity and forwardness, which I much dread.
Crave for me, dear friend, that I may be enabled to walk circumspectly and faithfully,
and be kept in gratitude and humility, for it seems to me not a little formidable,
the step I am about to take--setting up alone as
a housekeeper--like bearing a more public testimony.
The yearly meeting was a depressing time,
very little of that solemn quiet that is so precious;
yet some were comforted in believing that the great Head of the Church was still near,
qualifying His poor oppressed servants, at some few times,
to lift up their voice for the good old way, mostly in a very few, weighty sentences.
Dear S. Grubb had an awfully striking testimony among us, saying, among other things,
that we were setting up the Saviour in name, and denying Him in power.
I doubt whether she relieved her mind sufficiently,
but I know it was to the relief and comfort of many,
although others could not receive it, I fear, as too hard!

I shall remember you with fresh love, this summer, and gratitude for all your kindness.
To think of those I love seems to draw upward to Him who is super-excellent,
unchangeably good, and whom we both desire to love and serve above all.
May I grow up more and more into Him,
and then I shall have fellowship with those whom He loves!
I feel it very kind of you to make the effort to write to me, dear friend;
I can make your writing out well, but fear whether you can mine.

With the salutation of near and dear love, I remain your affectionate friend,

L+++.+++ A. Barclay.

To +++_______+++.

Forest Place, 26th of 6th Month, 1833.

My Dear Friend,

Before leaving this neighbourhood,
I hardly feel easy without writing you a few lines
to assure you of my affectionate interest,
although I have not had an opportunity, as I have long wished, to come and see you.
I have been unfavourably situated for getting out among my friends,
which I have often regretted,
yet have often felt much affectionate interest and sympathy for them,
though it may not have appeared.

I have thought that perhaps you may have many difficulties and trials to contend with,
unknown to others, and that perhaps you may feel your distance from meeting,
and sometimes as if you were overlooked by your friends--and I have felt for you herein.
But, dear friend, there is One who sees us as we really are,
knows all our trials and hidden difficulties.
He knows what is best for us; and He leads about, and instructs, and proves,
and humbles those who are willing to be His only; and in all His dealings towards them,
He intends good to them, and He does care for them;
and if He is with them in all their trials, to strengthen them and to do them good,
surely it is enough!
Only (says my soul) may they work the good mercifully intended;
and may the trial of our faith be to His praise, and honour, and glory!

And with regard to distance from meeting,
I have often felt what a privilege it is to believe as we do,
that (after attempting to do our best to meet with our friends,
and publicly to testify our allegiance to our heavenly Father,
and our great need of His renewed strength and cleansing) being prevented,
we may still sit down in our own houses in solemn
silence and prostration of soul before Him;
and that Christ, our great and good Minister, is still near us by His Spirit,
to teach us as never man taught--to feed us with His gracious
words--to minister fresh life to our souls--yes,
to reveal His Father more and more to us, that we may know Him and have eternal life.

Well, my dear friend, I have desired your encouragement,
in trust and in faithfulness to God, that you may be as lights where you are,
and thus glorify His name who has called you.

Farewell.
With love, I remain your friend sincerely,

L+++.+++ A. Barclay.

To Hannah Cruickshank.

Croydon, 17th of 8th Month, 1833.

My Dear Friend,

Your affectionate and interesting letter of 6th month was gratefully
received by me at a time of much trial both to body and mind,
when a letter from a dear absent friend,
or ever so short an assurance that one has been in their affectionate remembrance,
is like a cordial to a weary traveller.
I believe such cups of cold water, handed in simplicity,
and prompted by love to the one good Master, will not lose their reward;
and also that they will not improperly attach to the instrument,
but rather tend to strengthen our love to the great and good Giver and Master,
animating us with fresh alacrity in our feeble service of Him,
and an earnest desire to be enabled to make straight
and diligent steps in our spiritual journey.
But on recurring again to your letter, dear Hannah, I hope you will not misunderstand me.
I cannot suppose that my poor scrawls are in the least worthy of a reward;
if there is ever anything savoury in them,
I trust the thanks and the praise all go to Him who
sometimes condescends to direct the pen.

I believe I did attempt in my last to describe a little the various
conflicts and trials I had passed through in the winter and spring,
relative to my removal to this place, and leaving my dear brother,
with whom I lived more than seven years.
After yearly meeting,
the furnace seemed to grow hotter and hotter as the time of trial approached,
and all the reasonings and fears about the step magnified themselves.

Now I feel the comfort of being here to be great.
To be situated pleasantly in a cottage with a nice garden, etc.;
a nice little society among Friends, both of the middling and poorer class;
the near neigbourhood (within a walk) of meeting, also of dear brother John and wife;
all these good things seem to weigh me down with the debt
of gratitude due to the bountiful Giver of them.
You will say my cup surely runs over; and oh,
that there may be a faithful bringing in of the tithes!
Ah! my beloved friend, I think I do desire to be enabled so to do,
as well as to be preserved from other snares;
for the enemy knows well how to set them in every place, and under varied circumstances.
You know there is danger of taking our flight as on the Sabbath-day;
and there is danger of self-complacency creeping in,
also of too great attachment to the outward good things that here surround me,
as well as of being cumbered with cares of this world--even in a little way as I am here.
How great is the need, therefore,
of continual watchfulness and seeking after a renewal
of spiritual strength and Divine counsel,
in order to be enabled to walk circumspectly as well as faithfully.

It is a great comfort to me to have my brother John`'s company so easy of access;
it reminds me of our earlier years,
when he and I were so closely linked together--his
advice and experience are very valuable to me,
and he is pleased to say that it is a comfort to him my having come here at this time.
We are a little band of united ones here (how I should like you to come
and see us)--yet I hope we are sensible of our own great weakness;
indeed,
it is sweet to believe and trust that our heavenly
Father will show it to us more and more,
and give us to feel that in Him alone are all our fresh springs.

The account, dear love, of your exercises and conflicts was very interesting to me.
It is the enemy`'s work to discourage and to dismay,
both by anticipations and reasonings,
as well as by looking back and dwelling improperly on our shortcomings and slips.
Our good Father would not have it to be so; His corrections are full of love and healing,
that we may learn to be more obedient children--not
to cast us off further and hinder our future well-doing,
unless we are given up to disobedience and revolt.
In my own short experience,
I have found the enemy has been very busy after any
time of giving up to apprehended duty,
as it were, to cast over one a flood of discouragement.
It is better not to contend with him,
but rather to endeavour to sink down into the quiet,
trusting in our heavenly Father (whom we desire to serve)
that He will in mercy show us wherein we have offended,
and how to do better; and then I have sometimes found He has, at times,
been pleased to still the accuser, and to bring into a quiet, resigned state,
in which self is willing to be brought low.
In such seasons of conflict there is rather a hidden advantage
to the soul that is properly exercised thereby.
How good He is to manage things to the good of those
who desire to love and serve Him above all!
Let us more and more trust His correcting, humbling hand,
as well as lean upon His strengthening arm!
And, dear Hannah, let us not be afraid of the face of man, nor of his thoughts,
but let us sanctify the Lord of hosts himself, and let Him be our fear and our dread;
and if He is pleased, in great condescension to poor worms,
to give us at times a little testimony to bear for Him,
let us not be ashamed if it appear very small and homely.
No matter how weak and stammering the creature appears.
If there be but life in the offering, and it minister life to the hearers,
no doubt it will tend to the praise and glory of Him who gives it.
And oh! that we may be brought low and kept low before Him forever,
and continually emptied, and washed,
and refined for every fresh service--if indeed I may dare to use such a term!

How one does feel for poor Daniel Wheeler--such a vast responsibility
and concern! and yet one`'s very heart goes with him,
and wishes success to the Gospel to the very "`ends of the earth.`"
How consoling and animating is our belief of the universal gift of grace, dispensed,
in various measures,
to mankind--though one cannot but believe that if we had been faithful,
as a people raised up to bear this testimony, many more messengers would have been,
before this, sent forth to different parts of the world,
to turn people to this grace and light which lies hid in their dark earth,
or is but partially yielded to and acknowledged.
This is indeed a fearful thought!

Farewell, my dear friend.
I must close this long letter with the assurance of my dear love,
and that I do not forget that this is the day of your general meeting.
May the great Head of the Church be with you, to your comfort, and strength,
and cleansing--giving you to acknowledge that the Lord is good,
that His mercies endure forever, and that He is worthy to be served, loved, trusted in,
and obeyed forever and ever.
I remain your sincerely affectionate friend,

L+++.+++ A. Barclay.

To Hannah Marsh

Southbridge, Croydon, 24th of 8th Month, 1833.

Poor R. H. is no more.
We visited her deathbed last third day; she was comfortable in mind,
but much pained in body; she died that evening.
I believe her loss will be felt by many of her neighbours.
It is comforting, yet awful,
to think that we are answerable according to the
measure of light and grace we are favoured with.
I have often thought that perhaps those who are less favoured with advantages,
and perhaps may appear to us less forward in the spiritual course,
may be more likely to be accepted than some of us
who have been favoured in a higher degree,
and yet are shrinking, perhaps, from the faithful occupancy of what we have received.
I feel greatly the comfort of John`'s company and advice,
also the pleasure of a little society among the Friends of our now little meeting.
In short,
the weight of the debt of gratitude due to the bountiful
Giver of all the good things around me is very great.
Yet oh! that I may be preserved in humility, and fear to step amiss;
how necessary are a constant watch and a continual cleansing!

L+++.+++ A. Barclay.

To +++_______+++.

South Bridge, 3rd of 9th Month, 1833.

My Dear Friend,

I have been for the last day or two much looking back to the time I spent with you, and,
as it were, enjoying it over again,
I trust with reference to Him who gives us to feel love and sweet unity together,
who is the band of our union (may I not venture to say?), the nourisher, and preserver,
and increaser of it.
Oh, may I more and more seek after this precious fellowship, sell all for it,
part with all that obstructs it!
Ah! it is sweet to believe that it stands not in words and outward communications,
but in the power of Him who is our holy Head, living and ruling in us,
who is the strength and life of even the least of His members,
the smallest branches in Him the true vine.
I have been looking back, as I said before,
to the instructive and refreshing sojourn that I made with
my dear Cornish friends the last three months in last year,
with a degree of gratitude, I do hope, for the many favours bestowed, both immediately,
as it were, and mediately through my dear kind friends;
but especially to the sweet times I spent with you, my dear friend,
which has done me good to remember, I think I may say,
tending to animate with fresh love and praise to Him whom
we mutually do desire to serve and love more and more,
and by whose grace our dear friends are what they are.
How do I increasingly long that whatever sweet friendships I may
be permitted to partake of in passing along through life,
they may only be the means, as no doubt they were intended,
of engaging my heart more closely to Him who ought to be the only beloved of my soul!

While on this subject of outward loans,
I think I may inform you (I long with grateful prostration of soul),
that I have felt much comfort in being settled here at present.
The change is very great from such a solitary life as I led generally at Forest Place,
to here, where I have a genial female companion in the house,
a dear brother and sister to whom I feel so nearly united, within a walk,
and a few other friends of the meeting I belong (or
may so) to--it is like a new kind of life almost!
But mind, I don`'t mean to say that my life is in visiting about.
I should not wish that; but to be within reach of a little genial society is helpful,
I cannot help believing, if it does not carry us off the watch.

I have now been two months here today.
My little cottage is very comfortable,
just the right size for me--two parlours and a tiny kitchen below,
and three bedrooms up stairs, light and airy rooms,
though very snug--a nice garden behind, a little broader than yours at Camborne,
retired to walk and work in, yet open.
My dear companion, C+++_______+++ A+++_______+++, is very valuable to me.
I feel it indeed a great favour such a one has been prepared for me.
We work together in the garden,
and have also spent some pleasant afternoons reading
and working on the top of a hill near here,
looking over a sweet view.
When I look back to the seasons of indescribable
conflict I have passed through last winter and spring,
as well as the last month before I came here, when the furnace seemed extra hot,
one cannot but be weighed down with the debt of gratitude
due to Him who has brought me through,
made a way where I could not possibly believe any could be found,
and dealt very graciously with me.
May I be made more and more deeply to feel His goodness,
as well as my great need of His continued tender care and strengthening
grace to enable me to fulfill the new duties incumbent on me,
to support me under the new trials which may be allotted to me,
and to see and avoid the new and not less dangerous
snares set around me by an unwearied enemy.

Surely it will be in great mercy to our poor backsliding Society,
if we are somehow brought back again to what we are so fallen from,
even if it be by judgment and purging.
Surely the holy and precious standard given us formerly to bear,
and to exalt before the nations,
will not be permitted wholly to fall to the ground!--let it rather be re-anointed,
and held up with fresh lustre, though suffering be the prelude.

I should like to have you here.
My dear love is to you.
Do remember me, a poor child, for good.
I have great need of your prayers to be preserved
from the many snares on one hand or another.
Oh! that I may be so instructed to know the guidings of His eye,
and the teachings of His grace, as that I might avoid them.

Farewell.
Very affectionately your friend,

L+++.+++ A. Barclay.

To +++_______+++.

+++_______+++, 1833 or 1834.

Dear +++_______+++,

Your note I duly received and should have written since but had not an opportunity;
it was your second acknowledgment of my poor scrawl,
yet I accepted it as the effusion of a grateful heart,
and one that desires to be helped on her way in the right path.
But what I long for you is, that you may not be looking outwardly at the instruments,
however they may be made helpful to you;
it is the inward work that your eye should be upon,
even to witness redemption both from the guilt of sin and from the power of it.
The apostle exhorts the Philippians to work out their
soul`'s salvation with fear and trembling,
for, says he,
"`it is God that works in you both to will and to do of His good
pleasure,`" so it is by man`'s cooperation or yielding up himself
to obey the power or the grace of God which brings salvation,^
footnote:[Titus 2]
and has appeared unto all men, even in their hearts, that this great work is wrought out,
and this must be with fear and trembling,
that is in the Divine fear and in holy watchfulness;
because we feel it is not of or by ourselves, but of God`'s free grace, who touches us,
draws us, makes us willing, if we yield unto His power, yes,
works all in us by washing us, regenerating and renewing us by the Holy Spirit.

It is by yielding up our hearts to this measure of grace,
or manifestation of the good Spirit of Christ in our hearts,
that we are gradually delivered from the power of darkness and sin,
and translated into the kingdom of the dear Son of God;
and it is thus alone that we come to partake of,
and fully to feel the preciousness of that redemption which is through His blood,
the forgiveness of sins according to the riches of His grace!
Therefore,
the great matter for us to do is to take heed to
the reproofs of the Spirit of Christ within us,
which is as a light shining in our dark hearts,
showing us the evils thereof (for whatsoever does make manifest, is light),
convincing us of sin and giving us to long after
deliverance from the enemies of our own houses;
and as we are willing to bear His coming as a convincer and reprover
of sin--a refiner with fire and a fuller with soap--we shall witness
that He will make a thorough work in our earthly hearts,
He will bring forth judgment unto victory,
and we shall be made more than conquerors through Him that loved us,
and He will become exceedingly precious to us in this His inward and spiritual appearance;
our souls will delight in Him as the blessed messenger of the covenant,^
footnote:[Mal. 3:1]
we shall love to wait upon Him in the way of His judgments that
we may learn more and more of His precious righteousness.^
footnote:[Isaiah 26:8]
Thus the kingdom of God and of His dear Son will
come to be more and more set up in our hearts,
"`which comes not with outward observation,`" "`and consists
not in meats and drinks,`" but is to be within us,
"`not in word but in power,`" and consists in righteousness, peace,
and joy in the Holy Spirit.

Now, the work of the true ministers of Christ is to point out this inward
work and how it may be witnessed--to direct to our dear Saviour,
and how His power may be felt to deliver us from our potent enemies within;
they would not have us stop short by the way in merely being pleased,
or our affections kindled by what we hear,
for it is thus that the prophet Ezekiel`'s testimony formerly was to the
Israelites like a pleasant song of one that had a pleasant voice.
But we should look beyond the gift to the Giver of all good,
and we should endeavour to centre our minds on Christ the minister of ministers,
who can work either with or without instruments,
and with the ignorant and simple as well as the wise and learned.

And now, dear R.,
I hope you will not look on your poor well-wisher as any
other than a fellow traveller in the way toward Zion,
and your very sincere friend,

L+++.+++ A. Barclay.

P+++.+++ S.--I would advise you to seek such opportunities as you can
of inward retirement and silent lifting up the heart to God,
and thus will you be helped to bear the trials,
and to fulfill the duties of your station faithfully, and in the Divine fear;
with goodwill doing service (not with eye service) as unto Christ and not unto men,
so will you be a treasure to your mistress, a good example to all around,
and a valuable member in the church.

To M. S. F.

My Dear M.,

I had no opportunity of expressing my feelings to you the other day,
otherwise than by a squeeze;
but I am now fearful of letting you go to your intended
solitary abode without disclosing them more particularly.
I was thinking of you a few days ago with much affectionate sympathy;
and considering the solitariness of your intended home,
both as it regards the distance from meetings and dear relatives,
and also the seclusion from those dear friends whose society has been felt cheering,
if not strengthening to the mind,
animating to follow after those things which are excellent and which make for peace.
And while these were my secret cogitations while at my work,
the injunction of the Psalmist struck me very impressively
and sweetly in allusion to you,
"`Seek the Lord and His strength: seek His face evermore.`"
Oh! may your eye and the cry of your soul be unto your heavenly Father,
that He would feed you daily with bread from His table, that His hand may be with you,
that He would keep you from evil, that it hurt you not.
If it be thus your earnest engagement to draw nigh to your God,
I believe He will graciously condescend, in the seasons of His good pleasure,
to draw nigh to you, and to manifest himself to be a God nigh at hand,
and a very present help in the needful time;
for "`the Lord preserves all them that love Him,`"
and His eye "`is upon them that fear Him,
upon them that hope in His mercy; to deliver their soul from death,
and to keep them alive in famine.`"

I believe I need not apologise to you for this.
It is written in dear love to you,
and under a humbling sense of my own many shortcomings,
and great need of Divine preservation, and renewal of strength every moment.

L+++.+++ A. Barclay.

To L. B.

+++_______+++, 1834.

My Dear L.,

It was pleasant to come home together last evening,
and it was in my heart to have saluted you in much affection,
believing that the good hand of my heavenly Father is laying upon you,
and that He is waiting to be very gracious to you.
You have tasted that He is so, but you will yet see more and more of His goodness,
and wisdom, and mighty power,
in proportion as you yield more and more up to the touches of His love.
Let Him work in you that which is well-pleasing in His sight,
even to make you perfect in every good work, to do His will.^
footnote:[Heb. 13:21]
And though He may lead you in a way that is crucifying to the natural inclinations,
yet shrink not back from the gentle pressure of His hand,
for He is compassionate to His little ones,
and will hold their hand with persuasive encouragement, saying from time to time,
"`Fear not, for I am with you; I will strengthen you.`"
You know our Saviour`'s parable of the grain of wheat, which, except it die,
abides alone; but if it die it brings forth much fruit;^
footnote:[John 12:24]
and again, he that hates not his own life and all that is dear to him,
cannot be His disciple.
There is, indeed, much in us to be mortified and slain.
But God is able to do exceeding abundantly above all that we can ask or think,
and His power is exceedingly great to those who believe
(who yield to it as inwardly manifested),
according to His mighty power which He wrought in
Christ when He raised Him from the dead.^
footnote:[Eph. 1:19]
And oh, how precious is the hope of His calling,
how great the riches of the glory of His inheritance in the saints!
Let us pursue nothing in comparison of it; let us fear nothing but to lose it!
And, dear L., not only tender love and encouragement are with Him,
and strength and power, but He is the God of peace too;^
footnote:[Heb. 13:20]
for verily His reward is with Him--He does "`bless His people with peace.`"

With much love, and desiring your encouragement every way, I remain, etc.,

L+++.+++ A. Barclay.

To +++_______+++.

My Dear +++_______+++,

Although it is, and has been lately with me a low season, and one of close proving,
yet I do not feel altogether excused (knowing the awful uncertainty of time,
and the responsibility that attaches to feeling any little word of advice
or caution for a dear fellow-mortal) from taking this opportunity of saluting
you and your beloved sisters with a few lines,
in what I apprehend to be Gospel love--that is, the love of Christ, whom I do desire,
above all things, to love and serve with my whole heart.
Words fail me to express the earnest and affectionate solicitude I feel, and have felt,
for your best, even your everlasting welfare; and, to that end,
have desired that you may increasingly yield yourselves
up to the government and guidance of Christ,
by His blessed Spirit, that strives and pleads with you in your hearts.
He calls for your whole heart--and oh! will you not give it, can you withhold it,
can you refuse to be filled with His goodness,
as He waits to do and to deal very graciously with you?
I beseech you, fear nothing but to grieve Him--love nothing in comparison of (that is,
more than) Him--heed not what others say or do; but do you follow closely Christ,
your good Master and blessed Saviour,
and He will give you a peace (even His peace) which the world, with all its pleasures,
can never give, neither can it, with all its discouragements, take away!

But what I have more particularly felt it right for me to touch upon now is,
to express the desire that--seeing the important station which your dear parents
are called upon to fill in our church--you may feel the necessity there is for
you to guard scrupulously against weakening their hands by a mode of dress,
or line of conduct, on your part,
inconsistent with that simplicity which our principles
(which are those of the Gospel) lead into.
Yes, my beloved although you may not think you see the necessity
for this or the other little matter in dress,
I believe, if you follow your dear Saviour`'s leadings closely,
He will make you willing to give up your own inclinations relative to it, and,
from a love to your parents as well as to Him, to take up the cross;
and I believe such little sacrifices are very graciously accepted in the Divine sight,
and will draw down a blessing upon you which you may have no idea of now.
Thus, I fully believe, will the hands of your dear parents be strengthened--and to have,
also, the blessing of our beloved parents is no light one truly.

Farewell, my beloved +++_______+++; may you be blessed and be a blessing to others around you,
even by simply attending to the leadings of the Spirit of Christ,
however small and insignificant they may appear,
and easily to be reasoned against with what you may think plausible reasonings.
Remember, that he that despises the day of "`small things,
shall fall by little and little,`" and that the beginnings of Christ`'s
heavenly kingdom are compared to the growth of a grain of mustard seed,
so small and easily crushed,
but if permitted to spread in us (by faithfulness on our part),
it leads to "`righteousness, and peace, and joy in the Holy Spirit.`"
With dear love, I remain, etc.,

L+++.+++ A. Barclay.
