== Chapter IV

To R. R.

Croydon, 5th of 3rd Month, 1835.

Your letter yesterday felt not a little cheering
and animating to my often drooping and dismayed mind.
Ah, my dear friend, I am ready to think if you heard all that we hear,
both within the limits of our own quarterly meeting as well as from other parts,
even you would be dismayed.
One is at times ready to say,
Blessed are the dead who are taken from the evil
to come! but I know this proceeds from self,
unresigned to the duties and trials to come, and shrinking from suffering; and oh,
may every thought of this kind be brought into subjection to the obedience of Christ.
I have compared one`'s feelings for four months past till lately,
to that of being trodden under foot.
I believe there are a few (and will be more by and by), valiants raised up,
who are ready accoutred, not by their power and might,
but by the Spirit of the Lord God of hosts, for the battle.
He is mustering His little ones, whom He will make as David;
and who shall be able to stand when He rises up to the battle?
and who shall hinder when He is pleased to work, though it be by the foolish and weak?
My heart salutes these dear valiants in Gospel love,
and wishes them the best speed in their work, which I apprehend to be,
through the proper exercise of our divinely appointed discipline,
to purge the camp of what has for so long been as an evil disease in it,
to the discomfiture of our Israel before the enemy,
to the hindering of the true exaltation and spreading
of our great King`'s name among the nations,
and to the great burden and pain of the faithful.
The painful things we hear of from week to week do not surprise us.
They are marks of the growth of the evil,
and we receive them as symptoms of the state of the disease.
Yet truly they must be deeply painful.
I believe the spiritually minded, honest inquirers will not be much hurt,
for they are quick-sighted enough to see through the thing;
yet there is no doubt the weak will be stumbled,
and woe unto them by whom these little ones are offended!

You kindly ask me how I fare as to the path of duty.
Alas! the fear of man seems so deeply rooted,
what struggles it requires to overcome it! and oh, what bondage it leads into,
and weakness of hands,
and dimness of sight are the consequences of allowing it
to hinder our obedience to our tender and good Master!
But how gracious and condescending is He to interpose, time after time,
for our deliverance, that we may be set free to praise Him,
and to magnify His great and ever excellent name.

I suppose you have heard of the Beacon.
I do not intend to touch it.
These unsound principles are more insidious in their poison
than the openly shocking doctrines of the Hicksites.
Ah, I often remember a manuscript, which I believe I read to you,
which says of J. Wilkinson and J. Story`'s schism,
"`They are now bringing up new things which were not in the beginning,
having the smooth words which man cannot see but as their
fruits make them manifest and an inward eye is opened.
The doctrine of this spirit is so smooth that many cannot see a hole in it,
but the nature of it is to divide Friends asunder like stray sheep.`"
Ah, is it not so now?
And the nature is, to scatter from Christ the life.
How smooth things appear now in many instances, but the Life is lacking!
Oh for the baptising ministry of good old times!

Dear Edward Smith`'s death was a rousing stimulus
to your poor friend from a lethargy of discouragement;
and I have had another in the death of dear Mary Marriage.

Farewell,
dear R. Crave that the prevailing despising of what
appears weak and foolish in man`'s eye,
and rejection of what is ancient, may not hinder your poor,
weak sister from declaring the whole counsel in mercy given her to declare.

L+++.+++ A. Barclay.

To L. S.

Wandsworth, 19th of 3rd Month, 1835.

We are here an hour before meeting time, for the select meeting to be held,
so I shall occupy the time in writing a little note to you by F. J., if here,
and which I believe will not interfere with that exercise of mind
which often seems to attend me during these important meetings,
however unworthy to be dipped into sympathy with any of the dear exercised labourers.
Your letter, dear L., was deeply interesting and instructive to me;
I might almost say I was prepared for its contents,
for I own I had felt for you about going away at this time, and especially to that part.
It was very instructive to me your yielding to what seemed best in this matter,
and a feeling of thanksgiving and praise seemed to ascend
to Him who does all things well for those who love Him,
and enables them to act for His glory; and one felt animated by your example.

On second day last, I went down to Rochester, to William Rickman`'s,
and attended the quarterly meeting next day.
I assure you it was a very exercising time to me,
and I greatly desired to be preserved from doing
anything to the reproach of the good cause;
but I had for several quarterly meetings felt a wish to be with them.
It was very crucifying to me to have to stand up the first in the meeting for worship,
and the last in that for discipline; but the Lord made hard things comparatively easy,
and what was very bitter to the natural part to be sweet, or, at least, peaceful;
blessed forever be His holy name, who is indeed worthy to be feared above all,
to be loved, trusted in, and obeyed by the whole house of Israel!
It was sweet to be with the dear Friends of that county again,
to whom I have formerly felt united.
Dear William Rickman was very lively and striking in the meeting,
but I could not hear him; also dear Mary Baker,
who took up the subject which had opened upon me.
Elizabeth Beck also was there, and I believe it was a favoured meeting;
the precious covering in silence was very sweet to me.
We afterwards went on to Maidstone,
and were at their meeting next day--also a season of favour--and
were helped to return home comfortably last night.
You will say I have cause still more to trust, to love, and obey.

May the Lord keep us poor striplings in the hollow of His holy hand,
and hold up our goings in His paths that our feet slip not!
For surely if He leave us (or, rather, if we leave Him) a moment, we shall fall.
Oh, to be preserved low in His pure fear forever!

L+++.+++ A. Barclay.

To Hannah Marsh

Croydon, 26th of 3rd Month, 1835.

This approaching committee does feel so trying and exercising,
I feel almost ill at the idea.
How very pinching it will be to express a sentiment as to any one proposed,
with that unflinching yet humble faithfulness that should be! for
perhaps there may be relatives or intimates of the individual present.
Well, dear Hannah, we must crave one another`'s help, and remember the cause is not ours,
and no might or wisdom of ours will help it forward, but rather hinder.
As for poor me, I greatly shrink from such a vast trial of faithfulness as it will be;
oh! that I may, with clearness and humble faithfulness,
be enabled to express any little feeling that may be given,
and sink into nothingness again.
Who knows, perhaps my deafness may be a help to me in such a case,
as I should not be biased by others; is it presumptuous to say so, though?
Dear E. Robson`'s testimonies felt encouraging to me, though I heard very little,
except the last.
I wish you had been appointed representative to the yearly meeting instead of me;
I am sure it would have been better.
Do not the deaf belong to the blind, the maimed, and the halt?

Oh! that the deeply exercised travailers for the welfare
of Jerusalem may not faint under their manifold afflictions,
nor cease to breathe for her; for, surely, the set time to favour her will come,
and the poor dust thereof shall be compassionated.

It was very pleasant to see +++_______+++; I told her I was glad she came to feel with us.
Why should not elders go thus to a neighbouring meeting more often than they do?

L+++.+++ A. Barclay.

To John Finch Marsh

Ventnor, 29th of 4th Month, 1835.

My mind seems much with you at this time,
when I suppose you are about to commit to the grave
the remains of our dear and valued friend,
Ann Brewster.
I have long been hoping to see her once more,
but union of spirit--which I hope it is not presumptuous
to lay claim to--is perhaps better than personal interaction.
It is indeed a blessed exchange and happy release for her,
and one seems to rejoice on her account; but we shall feel her loss,
notwithstanding she has been so long laid by from public service.
Surely the secret exercise of such is felt helpful to the body.
The places of these dear ancient worthies, of whom we have latterly lost so many,
are not easily refilled.
Their experience, and stability, and deep humility are very slowly attained,
and in the course of many a painful stepping;
but it is in the ordering of a wise and kind Providence,
and humble resignation is the disposition we should seek after.
And surely, if we feel these losses,
it is our duty more and more to yield up to His qualifying power,
whereby a capacity will be received to walk in their footsteps,
and to serve the Lord faithfully in our day and generation.

L+++.+++ A. Barclay.

To E. R.

Southampton, 8th of 5th Month, 1835.

Ah! my dear friend, it is a fearful prospect to me this yearly meeting;
but we must look to Him who can make all things work together for good
to those who sincerely desire to love and serve Him above all,
yes, to fear Him above all too; and He is abundantly sufficient for His own work.
He can choose the weak and base things, in the world`'s eye,
and things which are not (according to their idea),
to search out and bring to nothing those which are
lifted up above the pure witness for Him.
I apprehend there is, and will be more manifest at this yearly meeting,
a great desire to cover things over and mingle things together, much appearance of love,
as well as of advocating our early doctrine;
but oh! how closely have we need to feel--how closely have
we need to keep to the unerring Guide and pure Witness,
in order that we may rightly feel from where things come.
I tremble for myself, and greatly desire to be preserved in a humble, meek,
listening state, waiting for true sense and feeling--and if any service is called for,
for wisdom and strength to perform it,
fearing none but to disobey my good and gracious Master.

I hear that dear friend +++_______+++ +++_______+++,
whom I have written of to you as a remarkable instance of the sufficiency of the Divine
power to qualify the very weak and foolish ones to be ministers of the Gospel,
is coming over with certificate.
One longs there may be more such instances as there were in early days.
I would not wish to be uncharitable,
but it is hard for some to see through some things--not
that I would set up myself as discerning though,
far from it;--every degree of life or growth has a proportionate
degree of discernment mercifully given,
and, as such, it is not to be boasted of, but occupied with, in deep humility,
and close watchfulness for its preservation and increase.
But, dear friend, let us not be surprised or amazed at anything we see or hear.
We know how subtle the enemy is, and we know how weak man is,
when he departs in any way from Him who alone can preserve us.
When we ponder these sad things in secret, oh, may we not be moved thereat,
but may it tend to our instruction.
What if things do wax worse and worse,
and the spirits of some be further manifested!--there is One who is over all,
who will work as it pleases Him, to His own glory and to the purification of His Church.
Oh! then, let not the faithful few,
the little flock of Christ`'s companions in suffering, fear or be fainthearted; for,
as they keep the word of His patience, and are faithful in their day and generation,
He will give them to partake of His royal banquet at His table,
and they shall reign with Him forever.
My heart salutes them, at times, in what I believe is a measure of Gospel love,
wherever scattered, and however their dwelling may be in the dust,
and sackcloth may be the covering of their loins, and none may know how it is with them.
But God knows and sees them, and they are very dear to Him; they that touch them,
touch the apple of His eye, and none shall be able to pluck them out of His hand.

I hope I do not write too freely,
nor improperly take the great Name into my mouth and hand.
I feel you as a dear elder sister, which makes me run on so to you.
I assure you it has, by no means, been an abounding time with me lately,
but one of much exercise and discipline--I might say,
even the discipline to utter close things,
and that which I know is kicked against by some;
but things very hard to my shrinking nature have
been most graciously made comparatively easy to me,
and I would readily yield myself up to Him who has dealt so very tenderly with me,
so I may but be preserved from bringing reproach on His good cause,
or on the awful work to which I have feebly put a hand in apprehension of His requiring.

My dear brother`'s severe illness has also preyed much both upon body and mind,
although one seemed kept in quiet and resignation as to the event of it.
It was a great comfort and favour that he was raised up again,
and as soon as he could bear travelling, we came to the Isle of Wight,
about three weeks ago, which means have been wonderfully blessed to him,
so that he is very much recovered.
John`'s writing labours are at an end for the present, but he is going on with Dewsbury,
by Rawlinson`'s help.
It has been very sweet to me to be with him since being out,
though it is only a scrap now and then that I get of his quiet company.
His remarks have been very instructive,
and his mouth has been opened several times in ministry in our little private opportunities,
or with a friend, for he has been quite silent, as to public ministry,
since leaving Cornwall.
I shall feel my loss of him greatly.

I felt a sympathy that I cannot describe on hearing of dear +++_______+++`'s prospect;
my dear love to her.
I believe some will be called to singular (to man`'s eye) services,
and oh! that such may be faithful.
Are we to limit our Master, and choose our own work?

L+++.+++ A. Barclay.

+++[+++The close and lengthened trials and provings which
Lydia Barclay had to pass through were,
no doubt, heightened by her natural timidity,
which at one time well nigh amounted to that fear of man which acts as
a snare and hinderance in the path of obedience to manifested duty.
Those who knew her best in after life,
and who knew also this feature of her mental constitution,
could not but be struck with the way in which she was strengthened to faithfulness,
when she believed herself called upon to deliver close things,
"`and hard to be uttered,`" either in public or more private ministrations.
Truly the Most High gives power to the faint,
and to them that have no might He increases strength.`"
Like her brother John,
she was brought under deep exercise of spirit in
the prospect of a Gospel errand among Friends,
before her gift in the ministry had received the acknowledgment of her monthly meeting.
This will account for some of the allusions in the following letter.]

To L. S.

Croydon, 3rd of 7th Month, 1835.

I much hope that this change of air may renovate you.
Body and mind are closely connected,
and such an awful time as it must have been to you for several months,
must have pressed much upon the poor body.
I may truly say it has been an exercising time to me since yearly meeting,
in which my mind has been much turned to the same subject--not that I am aware the matter,
as it regards myself,
has been taken up by Friends--and not at all that
I have voluntarily reverted to the subject,
for I have not entertained it at all during the four years that
I have feebly put my hand (as I apprehend) to the awful work.
But circumstances have unavoidably led to it and brought it upon me; and, truly,
day and night have I felt weighed down,
and close conflict and deep searching have been my portion.
But, through favour,
one seems a little strengthened to cast all care upon Him
who has hitherto cared for me abundantly and most graciously.
He can make a way for us where we can see none, and remove mountains of difficulty.
My soul desires to lean upon Him in humble fear, and holy confidence,
and pure resignation.
And oh,
that I may be enabled to perform all my vows made in the seasons
of sore conflict and dismay--to come up in faithfulness and entire
dedication to Him who has indeed dealt very bountifully with me.
For what am I, a poor, weak handmaid,
the least in all my Father`'s house (if indeed I be one at all),
that He should condescend to look upon me, and to lay His hand upon me,
and to put His words into my heart and mouth?
May I never refuse to obey Him in whatsoever and wheresoever He calls,
is the earnest breathing of my soul.
I should not, dear L., have turned upon this subject, had I not been feeling for you,
and it seemed to lead to my own capability of sympathising by experience lately.

I greatly feel dear John`'s going.
He is now gone to Malvern,
and is only likely to return for two weeks before they leave Croydon permanently.
It is very sad to me to look at,
it has come so very strongly before me since yearly meeting--almost overwhelming;
yet I desire to feel resigned.
I shall greatly miss his help and judgment both in temporals and spirituals.
Where a friend is undaunted, speaks the truth in love and true faithfulness,
and is unbiased by the affectionate part, how may we rely on their feeling and judgment,
and what a comfort it is!
But how few there are of this description!
Yet I know there is One who is omnipotent,
who delights to show Himself strong on the behalf of those who fear Him,
and He can make the weakest to be strong in His might,
and the dry bones to stand up in living power to fight His battles!

We have had several very sweet and strengthening visits
since yearly meeting from many of our dear Friends,
namely, Edward Alexander, W. and A. T., A. C., and Solomon Chapman,
with one or two others, all whose testimonies have been in a similar strain,
tending to turn from the instruments to the great Giver,
and to the teachings of His grace in the secret of the heart.
This has been very confirming and comforting to me,
as it is what has been my exercise and labour for some time past,
and sometimes in the same words.
Ah! dear friend, this is what we greatly need--to be directed to turn inward,
instead of looking out after words and declarations concerning the thing;
and I greatly and earnestly desire that I may be preserved from,
and helped against the fear of man,
or a shrinking from delivering this very unpalatable doctrine to the carnal mind.
But oh! to be enabled in humble fear, and in the puttings forth of the Divine power,
to deliver the whole counsel, nothing doubting and no one fearing;
and do crave this for me, and let us crave it for one another, dear L.,
for indeed we seem to be standing in slippery places--a sea of glass mingled with fire!
But the Lord is able to preserve us poor striplings, if we do but look singly unto Him;
and as we are engaged to wait upon Him daily, to feel after His cleansing,
quickening power upon our souls,
I have faith to believe He will not only preserve us in public ministrations,
but so season us with His divine grace and life,
as that our whole conduct and conversation may adorn His holy doctrine, and,
being so seasoned, may minister grace to all around us.
So be it, says my soul, and let the Lord alone be exalted in us and by us,
and may all flesh be abased to the very dust before Him forever;
for He alone is worthy to be praised, magnified, and adored, to be loved, trusted in,
and obeyed by the whole house of spiritual Israel forever!

I intend leaving home on second day week, with my sister Susan,
to go to Tunbridge Wells for a week,
and from there on to Sandgate for a fortnight with Rawlinson;
I do not wish to leave home just now,
indeed it would seem desirable not to leave my own
meeting--but I feel they have a claim on me,
and I do not wish to be deficient in family duty; also my health, I hope,
may be benefited by the sea air and change.
I hope I may be preserved faithful, not forward, while out.
It is likely I may attend a few of the little meetings in Kent, but I am known there,
and it seems like going home.
I need not say to you, dear L.,
that I hope you will do what your hands find to do where you are going,
you are more faithful than poor shrinking I. May
we be preserved near to the divine Master,
that is constantly eyeing Him,
waiting upon Him to know and understand His voice and will concerning us,
and for ability to perform it,
and I believe He will show us the many and various snares we are liable to,
and will be our help and our shield!
Let us trust in His tender, correcting humbling, as well as His good, strengthening hand,
and lean upon Him evermore.
My dear love to +++_______+++, I have reason to remember her;
she was the first to whom I opened my mouth to speak (as I trust) in the Divine name;
and the peace that overflowed I shall not forget; it is now ten years ago,
when she was in Cornwall.

L+++.+++ A. Barclay.

To William Rickman.

7th Month, 1835.

Ah! my dear friend,
it must be affecting to you thus to follow to the grave your dear
friends and fellow-veterans in the good fight of faith.
I can fancy you, at times, almost longing to join them in their disembodied state,
ready to think the chariot-wheels long in coming,
yet desiring in patience to wait for Him.
Ah! the time will come, when He will not tarry, to the rejoicing of your soul;
for truly His reward is with Him, even a glorious one,
for He has prepared a crown of righteousness for all those who
have loved and yielded unto His spiritual appearance in their hearts.
And this I know to be your case, my dear and valued friend.
You have faithfully and unflinchingly laboured to bring others to this love and subjection,
for you have testified of what you have seen, heard, and handled,
and felt to be very precious.
And though, perhaps,
the humility of the disciples may not see any use they have been of in the world,
in a retrospective view; and though the future prospect, as you say,
may not appear very bright,
yet no doubt there remains a blessed reward in store for them,
and a glorious rest and joy for the faithful--even from the hands of their good Lord,
who has wrought all their works in them, by whose grace they are what they are,
and to whom alone they ascribe all the praise.
They are acceptable unto God through the beloved Son, and their song,
even in this state of trial and tribulation, is:--"`Unto him that loved us,
and washed us from our sins in His own blood,
and has made us kings and priests unto God and His Father;
to Him be glory and dominion forever and ever.
Amen!`"

I took it kind of you to write to such a stripling as I am,
and valued your letter as an encouraging testimony to His praise,
who has been with you all your life long.
Mary Marriage I felt as a dear mother.
We can but rejoice on her account it is well with her!
She rests from her labours and sufferings, and her works do follow her;
they ascend as a memorial in the Divine sight,
and they leave a precious savour behind them, tending to His praise,
as well as to the encouragement of those left.
For, although she is dead,
yet she seems to speak this language:--+++“+++'`You also be ready,`'
by a humble faithfulness to the best of masters,
for such an hour as this!`"
Ah! it is a day of trial indeed.
Some feel like being trodden under foot;
but there will be a set time to favour Zion with Him whose eye is upon her for good.
He does compassionately regard and care for the dust thereof.
In His own time He will arise and comfort her, and make her desolate places like Eden,
the garden of His own planting,
and abundant thanksgiving and praise shall be found therein.

L+++.+++ A. Barclay.

To R. R.

Croydon, 6th of 7th Month, 1835.

I felt your sympathy truly sweet.
It has been as usual, and much more than usual,
a season of exercise and conflict with me since yearly meeting,
so that I have shrunk from writing.
It always is so with me then, for the sight, and hearing,
and sense of the state of things among us are brought so close to one,
and mourning and lamentation, as well as trembling for myself, seem to cover one!

Nevertheless, in the lowest seasons,
I may thankfully acknowledge that some sweet glimpses
have been afforded of the mightiness of His power,
the excellency of His wisdom, and the tenderness of His love,
who "`sits on the circle of the earth.`"
He gives power to those who feel they have no might of their own.
He will cause all these things to work together for good to those who love Him,
who are His called, and chosen, and faithful ones,
and none shall be able to pluck them out of His preserving hand of power.

My dear brother John, you would hear, was enabled to attend a part of the yearly meeting,
and has not suffered from it.
Ah, how wily is the enemy,
how artfully he goes to work to glide us off the true Foundation,
so that we may not be aware of it.
Yet, oh! let the sincere-hearted, faithful little ones,
the little flock of Christ`'s companions in tribulation,
remember "`their Redeemer is strong, the Lord of hosts is His name.`"

L+++.+++ A. Barclay.

To Hannah Marsh

Sandgate, 25th of 7th Month, 1835.

Dear Thomas Shillitoe and Sarah Grubb may be a little
cheered in the hope of brighter days among us;
but oh! the bitter conflicts, the deep plungings, the fiery baptisms,
that must surely be passed through before those days
come--it makes one start back to think of.
The sons of Levi, the vessels of the ministry,
must indeed be purified and refined before the pure offerings, as in ancient days,
can be offered.
May it be so, says my very soul;
and let the Lord work mightily to the carrying on of His great, and good,
and gracious work.
But oh! the precious sons and daughters of Zion who have thus adulterated from Christ,
may they be saved, even as by fire, when their work is tried to the very foundations.
I hope I am not writing presumptuously.
Dear H., I desire to take my part (if indeed it belong to me),
and to be thoroughly purified.

It is trying that any men Friends (in such very small
meetings) should keep at home to tend shop.
We called after meeting at +++_______+++`'s, and, on going into the parlour behind,
I felt constrained to utter a few words, turning that way, greatly in the cross.
It is my earnest desire to be preserved from doing wrong,
or diverting from an inward attention to the great Minister,
in these days of looking after words especially,
yet I have believed it required of me to break silence in
all the meetings I have attended since leaving home;
I hope I may now be excused.
I never felt so weak, surely I shall bring reproach on the good cause,
and fall into one of the many snares around.

Dear A. Brewster!
I hope something sweet and pithy will be prepared;
I wish I might have a double portion of her meek and humble spirit.
We may covet the best gifts you know.

Farewell, dear H. Remember me when favoured,
for surely I never more needed the prayers of the faithful;
I believe they will avail for my good.
With dear love, I remain your nearly united friend,

L+++.+++ A. Barclay.

Do write to me, if inclined.
Oh! that the 6th verse of the 116th Psalm may be my experience.
It has been many a time, so I ought to trust.

To +++_______+++.

10th of 7th Month, 1835.

Your kind communication seems to awaken much tender sympathy with you,
my dear friend and sister.
I could long to have some of your company again.
I do feel very tenderly for you, dear, but do not like you to give way to gloomy,
desponding feelings.
Surely the Lord`'s mercies are very many and great,
or we should have been consumed long ago.
His compassions fail not, and great is His faithfulness indeed!
Has He not many a time extended a hand of help, even when we were ready utterly to sink,
and seemed almost beyond hope, for we seemed unable to hope even in Him?
But He has beheld us with an eye of pity, and said to the waves, the great proud waves,
"`Be still!`" and our extremity has indeed been God`'s gracious opportunity
for the display of His power and the excellency of His might.
His wisdom, too, and His tender love,
and His very faithfulness are among the wonders seen in these deeps;
and it is then that He does seal precious instruction to us.
Oh, then, lift up your trembling eye, you dear fainting sister, unto Him, your tender,
wise, compassionate heavenly Father, and stay your mind upon Him as much as you can do.
He is not far from you, even in the most desperate time.
He who is God beholds you, as He did Hagar of old,
and will succour you in the needful time, bidding you fear not!
Do not shrink from monthly meetings.
Surely it must be the enemy`'s work thus to discourage, and do not believe him,
for he was liar from the beginning; and when he comes in thus like a flood, the Lord,
your Redeemer, who is mightier than he, will lift up a standard against him,
if you drink not in the enemy`'s suggestions,
but cast your care simply upon the Mighty One,
for none ever trusted in Him and was confounded,
or whom did He ever cast off that called on Him?

Dear +++_______+++`'s printed testimony no doubt you have.
I have read it with pleasure several times.
Ah! you must miss her greatly, but the never-failing Friend, the unchangeable Minister,
remains.
If we give up ourselves too much to the feeling of our solitariness,
does it not almost show a lack of true resignation
to the wise (no doubt) and good disposal of Providence,
as well as a lack of trust in Him, the Mighty One of poor worm Jacob?
Ah! my dear friend, let the painful feeling of the loss of our dear,
valued friends excite us to a holy and humble yielding
to the Lord`'s instructing and preparing hand,
that He may give us strength to come up faithfully in their footsteps.
And surely this is fulfilling the desire of these dear worthies!--they would not keep
us always as children leaning on them!--they would want us to come up higher and higher,
in a noble faithfulness, and in a humble watchfulness,
that we may fill our ranks in righteousness,
and be valiant for the truth in our day and generation.
My very soul says amen to it!
Let the Lord do what He will with His most unworthy handmaid, fit and prepare,
lead about and instruct, and give to suffer as He will, and what He will.

It was sweet to me to have the company of +++_______+++ and +++_______+++. We enjoyed,
through Divine favour, some precious times together,
partaking of a sweet unity and of that river whose streams do refresh, and, at times,
make glad the city of the living God, and the tribulated travellers Zionward,
even in the midst of tribulations!

We have had several pleasant visits from some dear friends,
whose company and labours were strengthening and comforting to us--to me especially;
for their testimonies were much in harmony together,
and tending to direct to the inward teachings of the grace and good Spirit of Christ.
How do I desire to be enabled faithfully to bear such a
testimony (however unpalatable it is now-a-days,
as it ever was, to the wisdom and craving of man), without shrinking,
in the seasons of the puttings forth of the Divine power!
And I know, dear, you do also desire the same thing, and I would, in my small measure,
endeavour to encourage you to do with the might given what your hands find to do,
and to keep humbly and watchfully, and use faithfully,
that good thing which has been committed to you, I am persuaded,
by Him who divides to everyone severally as He will.
But I am a child, and have great need to look at home.
Exercises and conflicts have brought me very low since yearly meeting,
but I can indeed testify to the goodness and tender dealing of the Lord,
and my heart desires to trust in Him above all, and to love and serve Him above all.

L+++.+++ A. Barclay.

To +++_______+++, on her Acknowledgment as a Minister

Croydon, 8th Month, 1835.

My Beloved Friend,

I believe I can hardly do otherwise than send you a few lines,
expressive of the tender sympathy I have felt with you this last week or ten days,
since being aware of what was likely to be brought forward the other day,
as well as how rejoiced I was in the conclusion come to,
and I greatly desire it may tend to your strengthening, preservation, and growth.
Ah, my dear friend,
the Lord overrules all things for good to those who
sincerely desire above all things to love,
and fear, and faithfully to serve Him;
and you can speak well of His condescending mercy in bearing you up amidst
many deep conflicts and sore exercises during the long time of your proving,
and seasons of discouragement.
And now He has shown you this great goodness! and
I know the language of your heart is:--"`Who am I,
O Lord God, and what is my house, that you have brought me hitherto?
And yet this was a small thing in your eyes,
O God;`" for you "`have regarded me according to the state of a man of high degree.`"
And the desire of your heart, under a sense of His goodness, is,
that He would be pleased "`to establish your house,`" even your heart, in faithfulness,
and in humility before Him forever; that His powerful hand may be with you,
to prepare and to bring forth all that He calls for at your hands;
that He would so be round about you (and clothe you with watchfulness)
as that He would keep you from all the evils that are ever at hand,
that they grieve you not,
nor hinder you from fulfilling His gracious will concerning you; and truly, dear sister,
my very heart responds a feeling Amen to this language on your behalf.

May the Lord bless you, and enlarge your coast, not in words,
but in the deepening of life,
and in the further and further experience of His wonderful dealings, and mighty workings,
and precious instructions! and, if He blesses, it shall be blessed.
Ah! what a most awful and a deeply humbling exaltation it is.
What is there to puff up?
How rich is His condescending mercy in calling us,
the weaker vessels (the first in transgression)--and
often the weakest of these to publish His goodness,
and speak of the glory of His kingdom!
And truly all is of Him; the emptying, the cleansing, the filling, the qualification,
yes, the faith, the willingness, the obedience, are all of Him.
It is of His own that we give Him; and oh! may it ever be so,
and that only when He bids us!
So let flesh be forever abased and nothing before Him,
and let the weakness of the creature so appear to ourselves and to all others,
as that none of the excellency of the glory and of the power may
be detained from Him to whom it alone and everlastingly belongs.

I may truly say it has been, as you would suppose, these last ten days,
a season of deep exercise to me in the weighty consideration
of this most awful subject--a season of close proving,
and therefore, I trust, of instruction.
Conflicting feelings have been many and sore;
but there is a Power that is able to limit the mighty waves, yes,
to do us good through the varied and, to nature, painful turnings of His hand.
I desire to know a habitation in that which limits them, and to commit my way, yes,
body and spirit, into His hand who is graciously redeeming me more and more to Himself!
Farewell.

L+++.+++ A. Barclay.

+++[+++The following letter was written under feelings
of discouragement from remarks made in her presence,
but which did not relate to herself.]

To +++_______+++.

Croydon, +++_______+++, 1835.

My Dear +++_______+++,

I felt your visit yesterday very kind;
at least I have this morning been able to do so (after another plunge last night),
and I hope I take it, as I believe it was intended to be,
as an expression of your desire that I might be strengthened in what is good,
and preserved from sinking too low, or into evil.
Ah, I own I heard and felt sufficient on fifth day to prove as a cold bath,
and perhaps reasonings have but too much crowded in.
Crave for me, dear +++_______+++,
that the latter may be overcome and silenced by Him who commands the winds and the waves,
and they obey Him,
and that this season of exercise may be one of instruction and deepening in the root,
for this is what I greatly covet, and not to spread in the branches,
which I greatly fear.
Perhaps you will say, may my simile prove correct.
Though it may have a repressing effect at the time,
may it tend to brace the system and promote a healthy vigour afterwards.
So be it, says my soul.

Well, my dear friend, in saying farewell, I would add,
May the Lord of the harvest raise up more and more living ministers among us,
even from among the poor, the illiterate, and the contemptible in man`'s estimation,
that He may have all the glory.
Ah, that which is of Christ, the Life, is living and baptising;
it baptises into His nature and Spirit;
it ministers his Spirit and life to that which is born of God in the hearts of the hearers;
and truly it has a testimony from that in their hearts, from which it proceeds;--for,
as our Saviour and His beloved apostle declared, it is only those who are born of God,
and who know Him,
that can hear His words or receive the testimony of His faithful servants.
And oh, let me be one of these poor, weak, yet living, baptising ones,
if ever entrusted with so precious a gift!

L+++.+++ A. Barclay.

TO R. R.

Croydon, 17th of 9th Month, 1835.

My Dear Friend,

I feel it cause for gratitude to Him who is the primary
hander of every cup of refreshment permitted us,
that your letters have often come at such acceptable moments,
this last one peculiarly so, for I felt very fainting on First day evening,
perhaps a foretaste of the two succeeding conflicting days.
Ah, the great Master knows what He does, in leading about, and instructing,
and proving as to a hair`'s breadth; and oh, that His hand may not spare,
nor His eye pity, but that I may come forth as gold seven times purified!
Your letter felt animating and encouraging to your often fainthearted friend,
and I thought I would tell you so thus early,
as I am likely to be much occupied soon in removing
from my present cottage to John`'s house,
and also say how pleasant it would be to me to have a little of
your company at your quarterly meeting at H+++_______+++. You will say,
perhaps, what business have I to come there.
Not as a spy, I assure you; but, if it may be, to creep just inside the door,
and to sit and feel for and with you, and, if permitted,
it would be a favour to partake of a crumb of bread with you.

My dear friend queries if the fear of man has left me yet.
Ah, it is still too strong,
though I have been more stimulated latterly (both by goodness
and by judgment or affliction) to overcome it.
And oh, what great goodness and condescension it is,
that the very weak should be thus tenderly dealt with,
their weakening reasonings subdued, a willingness wrought, and obedience given!
Surely He only is to be praised and magnified, to be feared and obeyed,
to be leaned upon, and His approbation alone sought after.
May He be so by me, says my soul,
and may the creature be kept in weakness and in nothingness
before Him and before all others forever.
It is a fearful thing to open the mouth publicly in the present day; indeed,
when is it not so, if our fear is a right one?
It is my earnest desire to be preserved from yielding to improper reasonings,
and to be strengthened to be faithful to my God in my day and generation,
however close and unpalatable to the natural man, in these criticising and refusing days,
may be the testimony to be delivered.

L+++.+++ A. Barclay.

To L. S.

+++[+++After referring to her brother John`'s removal to Stoke Newington, she writes--]

Croydon, 24th of 10th Month, 1835.

Inward exercises have not decreased, too, as you would suppose,
so that there were times in last month when one seemed pressed, as the apostle said,
almost "`out of measure, above strength;`" but, through condescending goodness,
I was helped through these seasons of extremity.
Ah!
I would not have the necessary baptisms and purifications abated at all,
but that patience may have her perfect work,
lest there should be a mixture of the precious with the vile.
But oh,
to be preserved from bringing reproach on that blessed cause which
I sometimes think is more precious to me than natural life.

It was very sweet and instructive to read your kind letter,
and to mark how you were helped along.
It is marvellous to see sometimes how the very weak are helped and strengthened,
but it is the Lord`'s doing,
and how can we wonder at His might--only admire and extol
His great goodness to His often hesitating and fearful creatures.
I think I might cast in my mite of praise in testifying of His
goodness and condescension to such a very poor seasoner as I am,
when I tell you that I was favoured to return with comfort
from the quarterly meeting at Horsham (a week or two back),
where I had felt drawn for a year--or years, I might say.
I went with dear M. Pierson, who had felt similarly for the same time,
and John F. Marsh accompanied us; and we had a sweet time with dear +++_______+++ on our way.
We found W. and A. T. with L. C. there, with certificates, which was a comfort to us,
and the sweet feeling of union in love and in exercise
permitted in the meetings was very precious.
On returning from there, I went, by agreement, with dear Mary Hagger, a Kentish Friend,
to attend Epping meeting, which she had felt drawn to,
and omitted when visiting meetings in Essex in the summer.
On taking her home to her daughter`'s at Tottenham,
we planned to go also to Winchmore Hill meeting together, another First day,
which had been my desire for five or six years past, but unaccomplished till now!
In these little matters we were favoured to feel satisfaction and near unity,
and I believe we were reluctant to part from each other.
She is a dear, simple-hearted, faithful friend, and lively in old age,
and I felt instructed and helped in being with her.
I returned home last week,
and am now brought again into a low spot--if it be for purification, no matter,
let the naughtiness be thoroughly purged away--but oh!
I fear it is my own fault.
Let me bear the indignation or the purification (whichever it be) humbly and patiently,
and let Him do what He will with His most unworthy handmaid--humble, correct, empty,
or fill!
Ah! there is One (you know it, dear L.) who can in the moment of His goodness,
with a ray of His divine light and power, remove all the misty clouds of reasoning,
and cause even the mountainous height of the fear of man to flow down before Him.

I did not get away quite clear from Epping, as it respected one individual,
which I have regretted,
but we must live and learn experience and simplicity by suffering.
Since we met, we have had many warnings of the uncertainty of time,
and stimulants to diligence in doing the day`'s work,
lest the night should overtake us wherein no man can work.

L+++.+++ A. Barclay.

To William Rickman.

10th Month, 1835.

I trust you are a partaker of a degree of peaceful quiet,
in the retrospect of your northern journey,
and that the little tribulated flock of Christ`'s companions in suffering,
have been cheered and strengthened by your labours among them.
Ah, they are indeed deeply to be felt for,
but their Redeemer is strong--the Lord of hosts is His name.
May they look to Him, lean upon Him alone--not lean to their own understanding,
or trust in anything short of His arm of power; for what will the strength, or wisdom,
or activity of man do, but lead to confusion and death?
The modern fashion of lecturing is a mode in which the arts and parts
of man have a wider scope than our worthy predecessors allowed,
and which will, it is to be feared, lessen our value for true, living, Gospel ministry.

These are sad times.
Still "`the foundation of God stands sure, having this seal,
The Lord knows them that are His.`"
May He preserve us poor striplings faithful, yet humble, before Him,
when He is pleased to gather you dear veterans to your everlasting and blessed rest.
How sweet it is to feel united to such, though outwardly unknown and far separated!
Ah, this precious fellowship depends not upon words;
it depends upon and is fed by the living virtue and power of Christ,
who is the life of all His true members, and knits them together in Himself.

L+++.+++ A. Barclay.

To R. R.

Croydon, 29th of 10th Month, 1835.

It has often been remarkable to me that I generally
have such a sweet feeling of unity with you in spirit,
whenever you are engaged, as I find afterwards, in writing to me.
Oh! how precious is true fellowship.
It is not dependent on outward interaction, neither is nourished by words,
but by the living virtue and power of Christ,
who knits together in Himself all those who desire to be His living members,
and He is their life, and from Him is their "`fruit found.`"
To be brought into this, to witness an enlargement and growth in it,
to be enabled to guard against all hindrances to it, is what I earnestly long after,
more than natural life; for this is the blessing of natural life, yes,
the blessing of blessings!

My dear brother John is in a trying state of suffering with his knee;
there is also much affliction around us by illness or death.
May we be wise to consider these things,
that we may understand the lovingkindness and wisdom of the Lord in permitting them;
for surely there is a voice of love in afflictions and trials,
and they have a speech of instruction, if we will but hearken thereto

I was sorry to part so abruptly from you, dear R.;
your kind feeling expressed in your note is truly helpful.
I own I often do, from fear of uttering a single word too much,
sit down short of delivering all the counsel given;
but I do not think this was the case at H.,
praised be His name who took away the fear of man, which was very strong before,
and mercifully helped.
I desire to be kept low before Him--if it may be,
few in words and much in power--that all may be of His free goodness, love,
and mighty power, that the weakness of the vessel may so appear to myself and to others,
as that none of the excellency of the glory and of the praise
may be detained from Him to whom alone it is due.

L+++.+++ A. Barclay.

To E. R.

Croydon, 30th of 11th Month, 1835.

My mind has seemed much turned towards you (I might say, your favoured county) lately,
in sympathy with that good thing which is little, and lies very low in many;
as well as with some of you deep feelers and burden-bearers who suffer therewith,
filling up that which remains of the afflictions of Christ.
And I think I might venture to say,
the earnest breathing of my soul has been from day to day, that that may be preserved,
yes, more and more quickened, and raised up, and strengthened;
and that you may be sustained, kept from fainting, yes,
strengthened even to rejoice in the midst of suffering,
and to glorify the Lord in the fires, even the name of the Lord God of Israel,
as it were in the isles of the sea;
for I cannot but believe that the shaking and the scattering will even extend to you.
But the Lord will be a strength to the poor and the needy, a refuge from the storm,
a shadow from the heat; and He will bring down the heat as with the shadow of a cloud;
the branch of the terrible ones shall be brought low; and He shall reign in Mount Zion,
and in Jerusalem, and before His ancients gloriously!
I feel greatly for you who are watching the approach
of the enemy with all his wiles and hidden stratagems,
and are faithfully giving warning and planting the guard:
the Lord bless your honest endeavours, and give you boldness with wisdom,
and true valour with meekness.
Ah! there is a sad spirit gone forth that would cover all over with love, and meekness,
and prudence, but is it of the right sort?
I doubt it does not proceed from the pure fear of the Lord,
nor yet from the faith that He gives! but the enemy
cares not how near we approach in Saul`'s armour,
so as we do not come in the name of the Lord!
Truly it is cheering (and is it not strengthening too?) to think of you,
and of a number more, upright-hearted, clean-banded, faithful ones, up and down;
I do believe they will be preserved, whatever sifting and trial may come upon us; yes,
made to shine brighter and to wax stronger by all these things--and
how does all that is alive in me long to be made of this proved,
yet loved and preserved number!

Faith and reliance on the merits of our Saviour are so preeminently held up to us now,
that good works (or, in other words,
a faithful cooperation in fear and trembling with that grace that works in us,
and would bring salvation home to us) are quite lost sight of;
and indeed I think they lose sight of all the many and solemn declarations in holy writ,
that we shall be rewarded hereafter according to our works.
It is very painful that such Church of England doctrines
should be held and propagated among us;
and it is very painful that opposite doctrines should be preached among us,
as I think must be evident even to our dear young people.
And, also, it is very trying, my dear friend, to such poor striplings as I,
to have to utter what is contrary to what the great ones among us declare.
But what is to be done?
We cannot choose, but utter what is given--the Lord will judge,
and I do hope will set to rights whenever wrong, if there be but a keeping close to Him,
and a lying low before Him; and this is what I greatly desire,
and ever to be kept little and low.

I shall, no doubt, be with you mentally tomorrow and fourth day,
which I believe to be your quarterly meetings;
and in this mental sympathy or exercise you and I shall be sharers,
for I suppose you will not be there.
The Lord preserve His little ones, and strengthen His firmer ones;
and let all flesh be abased before Him forever,
and let His name and blessed truth be spread and exalted over all,
and the gain of all and the praise of all be ascribed unto Him alone,
to whom it is everlastingly due!

L+++.+++ A. Barclay.

+++[+++On the 24th of 12th month, 1835, she was recorded a minister by Kingston monthly meeting.
To use her own expression,
she felt this to be "`a most awful and a deeply humbling exaltation`"--one
which bound the sacrifice as with fresh cords unto the horns of the altar,
by calling for unreserved dedication, increased watchfulness,
and a yet more lowly sitting at the feet of her heavenly Master.]

To +++_______+++.

4th of 1st Month, 1836.

I fear you have thought me long in communicating with you,
but I have been so situated that I could not with comfort before now,
having had Friends with me for two days after quarterly meeting;
and since then I have felt much bowed down under
the awful and humbling sense of what has seemed,
as it were, confirmed upon me in the Divine ordering and most condescending goodness.

I now take up my pen, dear sister (for so I may and must call you,
however unworthy I feel to be united to the poor, exercised, yet living ones),
to tell you simply that your subject of consideration
has again and again been the subject of my thoughts,
both on my bed and at other times; and I believe I may say,
at no time has it been but with the feeling of unity with it, although I should be sorry,
by my thus saying, to blind your eyes concerning it;
for indeed I know too well that the opinion of others is not to be relied on,
but the Lord`'s counsel to be sought after; and as you are desirous of doing so,
in His pure, holy fear,
I believe you will be rightly directed in all your
steppings in relation to this very important matter,
as well as in your judgment as to the thing itself.^
footnote:[A marriage connection.]
It was pleasant to me to hear that +++_______+++ had made you a longer visit,
and I gathered from what you said,
that you had had some opportunity of feeling after best guidance together.
Ah! is not this most satisfactory,
if we are but brought sufficiently into quietness and inward stillness,
wherein all prejudice as well as partiality is subjected?
and I believe the feelings we are favoured with on such an occasion,
will be helpful to us in coming towards a conclusion in our more private waitings.

Well, dear +++_______+++, you have my tender sympathy and desires for you,
that a degree of peaceful quiet may attend your looking
towards whatever decision you are enabled to come to.
Ah, this is the great thing to be desired in all our steppings of whatever
sort--to feel the peace-giving smile of heavenly approbation.
This will bear up amidst many provings and clouds
that may afterwards come upon us for our trial;
this will sanctify all, and assure us that all things shall work together for our good,
as we desire above all to love, and fear, and faithfully serve Him who is over all,
mighty, and good, and blessed forever!

The first page of your letter, dear +++_______+++, as it regards your poor friend,
felt comforting and encouraging; I may say it coincided with,
and added to the feelings of awe,
and of (I trust) humble gratitude that accompanied my mind, and still does,
in reference to what has transpired in the last fortnight.
It was striking to me, the visit^
footnote:[Of the Friends appointed to inform her that she was recorded a minister.]
not being paid till second day, for, by that means, I felt emboldened, or, rather,
constrained to bear (as I thought might possibly be!) a last testimony on the
subject of worship and prayer (which had been upon me for some days past),
on yesterday week; it was very humbling to me to have to utter what was close,
as well as to utter anything on that day, but it could not be helped.

Truly they were awful and humbling meetings +++[+++on the succeeding
First-day after receiving the visit]. I had hoped and believed
that silence might be my portion for some time to come;
but, to my trial, I felt obliged to utter a few words in the afternoon meeting,
greatly in the cross.
And now, my dear friend,
I seem filled with awe at the awful consequences involved
in such a conclusion of Friends towards me!
I desire to be wholly dedicated to Him who has shown me such astonishing goodness.
It is He only who can bring into resignation, as well as give ability to obey,
and preserve in humility.
I am greatly dreading to go to +++_______+++ meeting, which I have felt for some weeks past.
I am fully sensible how desirable and proper it is in my state to keep at home in quiet,
and unless it be very clearly required and a necessity laid upon me,
I should not dare to do so; if I must,
what a great comfort would it be to have some feeling Friend with me;
but I know I must look solely to the great Minister to support, and make way,
and strengthen through all.
The monthly meeting is there this month, And now, dear +++_______+++,
I know I shall have your sympathy as you have mine; and oh,
that I may have your prayers also.
Crave for me, above all things,
that I may be brought low and kept low forever;--this
is the prevailing desire of my soul.

I feel greatly for +++_______+++ in tender sympathy; but surely, dear friend,
we must also feel for the precious cause of truth,
and let all creaturely affection and foolish pity give way to a
concern for the promotion of that in the hearts of our dear friends,
and by them.
I believe I would have the same faithful dealing
extended towards me that I would advise towards others.
I am aware there are some diffident minds whom it might be better
to leave awhile to bear the immediate corrections of Divine goodness;
but there are also others to whom it would be best, yes, necessary,
to give the tender hint outwardly, as Divine wisdom and ability are afforded.
I believe that which is tender and good will not suffer by such faithful dealing,
but be deepened and strengthened, and eventually produce more healthy,
well flavoured fruit, to the praise of the great Husbandman, and to your comfort.
I believe I write these remarks under a humbling sense of my own
great weakness and constant liability to err and slip,
if not mercifully preserved and watered every moment,
and how needful to be always kept in this sense,
that we may more earnestly seek after this help and preservation.

L+++.+++ A. Barclay.

+++[+++Of the visit spoken of in the preceding letter she subsequently
wrote--"`I had to attend their first day and monthly meetings,
to my trial and humbling,
and to bear a testimony in a close way to the inward
and spiritual appearance and work of Christ;
but, through condescending goodness, I was helped over the mountains beforehand,
and the deep plungings afterwards.
I suppose I must be content to bear such seasons of extremity,
and learn to endure hardness,
if I would be a true soldier of the unconquerable Captain.`"]

+++[+++Journal Entry]
1st Month 10th, 1836.
"`Return unto your rest, O my soul; for the Lord has dealt bountifully with you.`"
In remembering this language this evening,
I have thought that the Lord Jesus Christ is the rest of the soul;
and that to return unto her rest, is to retire back to an inward, humble abiding in Him,
in His precious power, in the pure fear; in which alone is true preservation, safety,
and peace, as well as ability to do anything that is acceptable unto God.

To +++_______+++.

Croydon, 25th of 1st Month, 1836.

My Dear Friend,

In the evening at +++_______+++, we got upon the subject of revelation, much to my dismay,
as I cannot say a word for the good way in a conversational way,
but as +++_______+++ had rather spoken against it, I felt constrained,
some little time afterwards (when they read a psalm before the young people went to bed),
to utter a few words on the subject, exceedingly in the cross, in a ministerial way.
It was altogether an exercising visit, but I felt peaceful in the retrospect.
But oh! my beloved friend,
I cannot describe to you the deep plunges and bitter anguish
that I have gone through since returning home;
I suppose the cause was from hastily letting in discouragement from something
that dear +++_______+++ said at +++_______+++ on my way home the next day.
You know a little matter is enough to one prone to take it in.
The mention even of the snares and dangers around, seems almost to plunge one into them!
So that I have almost doubted of all,
and concluded that Friends must have been wrong in their judgment of me,
and that I am wrong altogether and have believed a lie.^
footnote:[In reference to some critical remarks on her quotation of a passage of scripture,
on an occasion subsequent to the visit before alluded to.]

It appears to me that the apostles formerly, and the true ministers in the present day,
preach not themselves, but Christ, the Word;
they preach and minister his power and Spirit, otherwise the words are not living,
but dead; and they desire that He--the Word that lives and abides forever^
footnote:[1 Peter 1:23]--that is,
that His blessed power and Spirit may have free course
and be glorified in the hearts of the hearers,
may have the whole sway and rule over all in them.
I believe it was in this sense I quoted 2 Thess. 3:1,
and I have not felt any uneasiness about it since, which I hope I should,
if it were wrong; but do tell me how you feel about it.
There is One who knows my earnest desire to serve Him faithfully, and humbly,
and watchfully--to seek His favour only;
and how greatly I fear to do harm to His blessed cause,
or to bring reproach on that awful work to the which I have
apprehended myself called to put a feeble hand;
that He may humble and correct any how, graciously instruct and guide,
and powerfully strengthen and preserve!

Third Day.--I feel a little more quiet this morning
since a little strengthening retirement after breakfast,
and I have had a note from dear +++_______+++, which has allayed my reasonings.
Ah, my dear +++_______+++,
is such a proving conflict as this one of those times in which
the gift itself (if such has ever been committed) is to be purified?
If so, my very soul says Amen to it!
If the Lord`'s good hand be but underneath,
it will support under any overwhelming plunges that He sees best,
and bring forth more pure to His praise.

L+++.+++ A. Barclay.

To R. R.

Croydon, 30th of 1st Month, 1836.

My Dear Friend,

I fear you have thought me long unmindful of your kind letter of last month.
It was acceptable; but the exercised and awful state of my mind,
at that time and afterwards, seemed to preclude interaction with my dear friends,
and solemn silence towards them seemed to be most
congenial--not from a withdrawing or a lack of love,
by any means, for never more have I needed their sympathy and prayers truly.
This I know I have had from you, dear R.,
if you have heard that the awful time of recommendation
to the select meeting has come upon me--awful indeed,
and involving awful consequences!
Crave for me, that I may be preserved in the lowliness of the pure fear,
and in the simplicity of the true faithfulness.
Ah, what am I, the least in my Father`'s house, and altogether weak, foolish, despicable,
and utterly unworthy, that my Lord should thus think of me,
and show me this great goodness,
and regard me according to the state of one of high degree?

It was very pleasant to see you write as you did respecting your removal from +++_______+++;
ah, this is all we desire,
to be permitted to feel a degree of peaceful quiet
to attend our looking towards any step of the kind,
as well as in the taking of it;
and this does bear up against many reasonings and low feelings.
I sincerely hope you may continue to feel satisfaction in your re-settlement at home;
your company there may be helpful at this time of shaking,
and perhaps a visit now and then to your friends at +++_______+++
may be more beneficial now than a residence there.
I cannot describe the longing that I feel on your behalf, my beloved friend,
but I believe you know my exercise, and can feel me in that which is beyond words.

L+++.+++ A. Barclay.

To Hannah Cruickshank.

Croydon, 23rd of 2nd Month, 1836.

Many of our young people are attending other places of Worship,
and our other peculiar testimonies are being gradually laid aside.
Surely such are going back again to the beggarly elements,
to the door of the house of bondage,
from which place our forefathers were brought out
by a mighty arm and an outstretched hand of power.
And does not the world see this, and point the finger at it with satisfaction,
thinking we are coming to our right senses at last?--but alas! the little ones,
the spiritually minded and panting ones among them, are offended and stumbled,
and surely woe lies at our doors who are the means of so doing!
I heard lately that +++_______+++ had expressed a belief that,
if a revival takes place among us, it will be by the proper exercise of the discipline,
and not by preaching.
I thoroughly united with it, and shall rejoice if it be so;
for I have long thought that these modern views,
which have been for so many years gliding in among us,
have been undermining the very root and foundation of our discipline,
although the superstructure may to casual observers appear correct and fair.
Ah, we do indeed need a healthy action in this respect;
but there must be a purging in order for it; and oh,
that we may not be dismayed at the operation thereof,
nor at the falling of them of understanding, but abide in our lot,
even in the quiet habitation of stayedness upon our God,
who (as the mountains are round about Jerusalem) will be round
about His little dependent ones--His poor and afflicted remnant.
He will be their hiding-place and shield, and nothing shall harm them,
as they are followers of that which is good, even of His good Spirit;
but "`such as turn aside unto their crooked ways,
the Lord shall lead them forth with the workers of iniquity.`"
But oh! says my soul, that such may be at last gathered and brought back.
But surely, dear Hannah,
the way to this desirable end is not to salve all
over with love and harmony--this is the false love,
and the harmony and union of the wicked one; but it must be through judgment,
by setting the judgment of truth over such,
and testifying faithfully against the evil in them, in pure love to their souls,
and with tender dealing towards them.
And I do believe, if our elders and overseers had been faithful in these respects,
years and years ago,
these sad errors in doctrine and practice would not have got to the height they have now.

The fathers, the mothers, where are they?
and the ancient prophets are quickly removing from us!
Yet the Lord lives forever! and in Him is everlasting strength and wisdom.
We are, as it were,
shoving forward towards the front of the battle--the thought is fearful, and awful,
and humbling!
The Lord look upon us, poor weak striplings,
teach our hands to war and our fingers to fight, gird us with His strength,
clothe us with His heavenly wisdom,
and ever preserve us in the depths of humility in His pure fear.

Well, my dear friend, I must now bid you farewell with reluctance.
In the meantime, it is sweet to think of you and of others, though outwardly unknown.
The Lord unite us more and more together in the hidden fellowship,
by a union with Himself through His beloved Son, our Saviour.

With the salutation of love, I remain your truly affectionate friend,

L+++.+++ A. Barclay.
