== Chapter V

To E. R.

Croydon, 27th of 2nd Month, 1836.

How rejoiced I was to hear that your hands had been strengthened by your
friend`'s acknowledgment of that precious gift and qualification which
had been bestowed and wrought in you by the mighty power of God,
and the anointing of His blessed Spirit!
May the Lord be with you from day to day,
and bear up your spirit amidst the many searchings of heart, wadings of spirit,
and painful travails of soul,
that must be the portion of the living elders of the people
in these days of treading down and of backsliding.
Yes, the Lord will be near to strengthen you, to keep your bow in His strength,
ready for His use.
And though you may be ready to query your use,
and to dwell in discouragement on your being debarred from much active service,
yet I have believed that it will not be so,
as you yield to the little puttings forth of His power,
and that the place will be no sinecure to you.
My heart salutes you in dear sisterly love (though a younger and an unworthy one),
and wishes you God`'s heavenly speed in whatever your hands may
find to do for the name and blessed cause of the best of Masters;
for, truly, His is the kingdom that we do desire to promote, and His is the power,
and the strength, and the wisdom, in and by which it can be promoted, and spread,
and exalted; and to Him let the glory and the praise be forevermore ascribed.

I hope I am not going beyond the measure of a child in thus writing to you,
my dear and valued friend,
but I feel that nearness of love and union with you
that knocks down all difference of age,
and other reasonings and fear;
and perhaps I am the more prepared to sympathise with you under your promotion,
from having been permitted (most unworthily) to partake of the same exaltation,
though to a more humbling station--a place of all work!
But we must not grumble against the good Master.
How unworthy are we poor weak handmaids (the first in transgression) to be in the most
menial office of His glorious house! and the language of my heart has been,
"`Let me be a servant to wash the feet of the servants of my Lord.`"

I note your encouraging allusion to poor David--the Lord`'s hand
is not shortened--He can work by weak and despicable instruments,
and confound the wisdom of the wise,
and bring to nothing the understanding of the prudent, even by foolish things,
and things which are not, according to man`'s account.
And seeing I am so weak and ignorant, and the snares around are so many and deep,
I have said in my heart, Oh, that He would keep me very close to Him,
my eye looking wholly and steadily on Him; yes, may He lead me, a poor child,
by the hand, and cause me to lean only upon Him, for otherwise surely I shall fall; and,
if He teach my hands to war and my fingers to fight,
with His might and in His heavenly skill, oh,
may He ever preserve me in the depths of humility
and in the watchfulness of the true fear!

My brother John is confined at home, but he is not idle; he has many visits from Friends,
and I do believe he deals very faithfully and fearlessly with them.
He is also beginning a third volume of his series,
a valuable MS journal of an Irish Friend, Joseph Pike,
which treats on many subjects remarkably pat to the present times and errors.

I have often remembered a remark of an ancient worthy,
that "`the discipline is a branch from the same root from which the ministry springs.`"
This is very true, and when life goes from the one,
it goes from the other--and when this hedge is broken down, or, rather, dies down,
we are left weak as others, and a prey to all depredators.
But, my dear friend, I fear I shall make you sad, but I am often sick at heart myself,
so my communications must savour of sadness.
We have had several removals lately of dear Friends,
especially those of three dear ancient labourers in the Gospel, namely,
Joseph Binns of Southwark,
who had come forth quite late in life in the ministry with much brightness and power;
dear Sarah Lamley of Warwickshire, and Sarah Charman of Reigate.
They travelled formerly together, and were buried on the same day.
Dear William Rickman came down to my house the evening before,
and went with John F. Marsh and myself to Reigate.
It was a memorable day--a day of great favour and precious visitation to some present.
We have had several interments here also;--one of Richard Phillips.
Ah, these are truly exercising times!
I have such a jealousy of funeral sermons creeping in among us.

+++[+++And then alluding to some painful events taking place in the Society at this time,
she adds--]

Oh, the deception of the enemy, and his false appearances,
even as an advocate for the good old way of truth!
but he cares not how close the imitation is,
so as the very truth itself is kept out!
I often remember a dream of dear +++_______+++, I know not whether you have heard it.
She dreamt she was at meeting and in the gallery,
and presently she saw something come into meeting, it was so beautiful, and glorious,
and taking, that everyone made way for it and admired it;
and at last it came right up into the gallery, and was well received there,
and it crept about the legs of the Friends and gradually twined itself about their bodies,
till at length it actually squeezed the very life
out!`" "`Blessed is he that watches in deep humility,
and in faith and patience, and keeps his garments!`"
The Lord preserve his poor weak little ones low in his pure fear,
for "`in vain is salvation hoped for from the hills,`"
or help from the princes of the people;
"`truly in the Lord our God is the salvation of Israel,`" and nothing
shall harm those who are followers of that which is good,
even of his good Spirit.

L+++.+++ A. Barclay.

To L. S.

Croydon, 1st of 4th Month, 1836.

For several days after you left, it was a struggling time, but at last,
through Divine help, I was enabled to overcome,
and to cast all my care upon Him who has hitherto wonderfully cared for and helped me,
and who, I do believe,
will be the wonderful counsellor and the mighty protector of the weak and solitary ones,
if they do but lean upon Him solely,
and desire that He should be the best beloved of their soul.
Oh, then, let me seek unto and serve Him only and wholly,
and trust in His mighty power and His unchangeable and excellent goodness forever!

L+++.+++ A. Barclay.

To R. R.

27 Marine Parade, Brighton, 30th of 4th Month, 1836.

My Dear Friend,

I expect you are now suffering from exercise of mind for the body`'s sake, as well as,
perhaps, for your dear sister`'s sake,
whom I much thought of on fourth day and fifth day.
I trust it was a good day to her,
and a time owned by Him whose presence and approving favour is the crown of all blessings,
yes, in whose favour there is life, for with Him is the fountain of life!
As to the body, which is the Church,
surely every living member must at the present time be, in degree,
bowed down with exercise; and oh,
that such a child as I might be fitted and prepared to partake therein in any measure,
that I might be one of the true burden-bearers,
willing to suffer and to bear for my good Master,
as well as to cast off the burden at His bidding.

I often think that much of what the prophets Jeremiah
and Ezekiel declared is applicable to us,
and how instructive it is!
Ah, it is only such whose eyes have been divinely anointed that can see through things,
see men and their motives (as dear +++_______+++ says); these are, at times,
given to see through the hole in the wall,
the abominations that are committed as in the dark.
But I desire not to judge improperly, or to speak hastily.
It is the enemy`'s work to deceive and lead astray from the fountain of living waters,
and he well knows how to assume the appearance of an angel of light,
and thereby deceives the more easily.

L+++.+++ A. Barclay.

To William Rickman.

Croydon, 5th Month, 1836.

How very kind do I feel your affectionate remembrance of me in this way!
I trust that my eye, on receiving such tokens,
is unto Him who puts love and sympathy into the hearts of any, and gives to express it;
and in this way how often is it, that what looks very simple to ourselves,
only like a cup of cold water, is made very acceptable and helpful to a fellow-pilgrim,
leading to gratitude to the great Giver,
and to taking a little fresh courage in the fight of faith and the course of dedication.
How very kind, too, my dear and valued friend, was your warm invitation,
uniting therewith the excellent caution you afterwards
give--"`to mind the inward freedom and the stepping-stones.`"
It reminded me of what dear Mary Alexander said--"`that
it is good for spiritual children to breathe fresh air.`"
Oh, the great need, as you say, to keep close to our Divine Leader,
and to lean only on Him, not to our own understanding, nor yet be looking out at others.
Crave this for me, my dear ancient friend, when favoured with ability,
for truly I am very unworthy to be entrusted with the attractions of Gospel love.
Oh, that I may

be preserved from harming the precious cause of truth,
or bringing any reproach on that awful work to which
I have been constrained feebly to put my hand,
and then no matter how poor, and weak, and foolish I may appear.

I have been to Brighton for two weeks, recruiting by the sea-side.
The last week I was joined by Lydia Sargent, junior, and I think I may say,
through condescending goodness, it was a season of refreshing,
though mingled with plunging and conflict, which I suppose I must expect,
and is it not true,
that the cups of refreshment are thereby rendered the more precious and acceptable?
like as Elim was in the desert to the Israelites.

Our approaching annual assembly seems an awful time to look at,
yet we have great reason to trust in the Almighty Arm of power, and not to be afraid.
How greatly does it behoove those whose eyes have been divinely
anointed to see through men and their motives,
to dwell very low, to keep very inward to their Divine Leader, and Enlightener,
and Teacher--to ponder His instruction--to watch His season
for the declaring of what they have been given to see,
as on the house-top, for the arousing of His backsliding people.
Some seem enabled, amidst all the causes of trial that are around us,
with humble confidence to mark the increasing symptoms of ripeness,
to throw off that which has been as an evil disease in the camp,
and to look forward cheeringly to a season of deliverance.
But oh, the sufferings to be endured,
and the deception that must be further manifested before
such a day! "`What shall we then say to these things?
If God be for us, who can be against us?`"
"`The Lord has founded Zion, and the poor of His people shall trust in it.`"

My dear brother John is favoured to feel calm and comfortable,
resigned to leave this state of trial and probation at his Lord`'s summons.
Such a prospect is deeply affecting to me.
We are nearly united; but I believe death will not separate us,
if I am but preserved in Christ, in whom is our union.

L+++.+++ A. Barclay.

To Hannah Cruickshank.

Croydon, 29th of 5th Month, 1836.

My soul seems melted sometimes under a sense of the Lord`'s
great goodness and condescension to such a poor,
hesitating, disobedient creature for so many years,
and I do feel a desire to be helped to be diligent
in doing whatever He calls for at my hands the remaining,
though declining, few years of my life (if indeed a single year may be allowed me),
in whatever way He may be pleased to appoint, whether actively or passively.
And, dear sister, I would affectionately encourage you also, to give up,
without reasoning or fears, to so very good a Master,
for none ever shuts a door in His house for nothing,
or hands even a simple cup of cold water!
He can cleanse and qualify, strengthen and support even the weakest vessels,
and perfect His praise out of the mouths of sucklings.

Of the state of things among us M. W. would be able to inform you,
and to give you some idea of the trials and sufferings of the burden-bearers among us.
I expect we must yet look for greater sufferings and treading down,
more evil to be yet manifested and brought to light--like the prophet
being told to turn yet and behold greater abominations! and no marvel,
for the enemy is the father of lies and deception,
and can transform his deceitful workings into the appearance of an angel of light,
and it is only those whose eyes are anointed by the
finger of Christ who can see through things,
through men and their motives, who can see through the hole as it were in the wall,
what they are working in the dark out of the pure light!
But the Lord will plead the cause of His poor oppressed ones,
and arise for their help in His own time;
He will bring them forth as gold seven times purified,
so they will truly be His dear people,
made precious to Him and chosen in the furnace of affliction,
and they shall be enabled with unspeakable and most precious experience to say,
"`the Lord is our God;`" for they will have marvellously proved His power to be infinite,
and His goodness most excellent, and that His faithfulness endures forever!
And, dear love, do yield to His mighty power also,
and that is the way to have the body helped as well as the mind blessed with peace;
but oh, how unworthy are we of the least of all His precious goodness and mercies.

Farewell, very dearly,

L+++.+++ A. Barclay.

To E. R.

Croydon, 31st of 5th Month, 1836.

Ah, my dear friend,
the assurance of your love and desires for me was helpful and comforting to me,
and I do sometimes hope the prayers of some for my preservation may be heard,
and surely never did I need them more than now--having ventured to lay
before my friends a feeling of duty that I have for some years had,
to go and sit with our dear Friends of Oxfordshire
and Warwickshire in their several quarterly meetings,
the end of 6th month, and to attend some other of the little meetings thereaway,
also Birmingham monthly meeting in 7th month;
for which I am favoured with a minute instead of a certificate.
Friends kindly acceded to my wish in this respect, being such a child,
and dear Hannah Marsh is going with me.
It does indeed seem a fearful time to be going about,
and one hears things that are enough to frighten the feeble-minded.
May I be kept quiet, and leaning only on Him whom I do desire above all to fear, love,
and faithfully serve!
Truly I am without scrip or purse,
and am ready to wonder how so poor a creature can be required to go forth in this way,
as well as to fear that I shall certainly bring reproach
on the good cause or the awful work I have put my hand unto,
and fall by the hand of the enemy.
Do crave my preservation in watchfulness and deep humility,
as well as in a willingness to be anything or nothing.
I have been long disobedient and hesitating, so my time is short now,
and I feel a desire to be made diligent and faithful
the remaining years of my pilgrimage here.
It was a close exercise of faith to me last summer and autumn,
not seeing any way to move,
until it was opened by the acknowledgment of unity in the 12th month,
and now it seems very early to be so engaged, but I cannot help it.

It has been a comfort to me, amidst seasons of conflict, of deep exercise and trial,
this yearly meeting,
to be permitted to partake of sweet fellowship and
union with some dear Friends from various parts.
How sweet this is, to feel that precious love and union that extends over sea and land,
and does not depend on outward interaction!
Oh, that I may seek after preservation in it,
and to have it daily kept alive and strengthened by Him who is our life.

I know not how to give you any account of yearly meeting this year, my dear friend,
my memory is so deficient; but I may say, that although it has been a trying time,
a time of dismay and of treading down,
yet we have been favoured with some precious cups of refreshment and comfort,
which have strengthened us still to bear up and not to faint.
Dear A. Thorne is very simple and short in her conmunications, but so pithy, and full,
and sweet, they were always a few words fitly spoken.
But oh! the shrinking, the unfaithfulness, the compromising,
and the vast number of shades of declension and of going over to these new opinions,
so that the little remnant know not whom to believe, whom to trust to,
so great is the deception of the enemy to blind people`'s
eyes--but they receive renewedly the advice to sit alone,
be patient in tribulation, and to keep silence, dwelling deep,
and waiting to see the end of these things.
For surely it shall come,
I do believe the day of deliverance-although things are not yet ripe enough;
there is more evil to be manifested, and greater abominations to be seen,
that are working in the dark out of the pure light.

Oh then, that you, who have not, as yet,
been tried (though I am ready to fear your borders are not exempt entirely),
may be doubly vigilant on the watch-tower,
to watch the very beginnings of the enemy`'s approach.
And be faithful and fearless,
no matter in whomsoever you perceive a willingness
or susceptibility to receive his baits;
and it does come on so very gradually,
that those who feel a godly concern for their brethren and sisters had
need not to wait till (as they would say) things were more tangible,
but to give the warning word which may reach the witness, or, at any rate,
be the means of raising it after a while--and such faithful ones shall have their reward.

We had a sweet visit from dear W. Gundry in our women`'s
meetings--it was like marrow to one`'s bones.
He addressed the little mourning ones,
those who sigh and cry for all the abominations committed in the land,
reminding them of those formerly who, though there was not much for them to do,
had to sigh and to mourn--yet that the man clad in linen set a mark upon their foreheads,
and they were spared when the destroyer was sent over the city.
He encouraged those in small meetings,
saying that it had been his lot to be in one where there
was no minister for forty years--spoke on silent worship,
and recommended a patient, reverent exercise in meetings,
not looking for words--on the great bait of the enemy,
a desire to be something in religion--reminding us that the root
is to bear the branches and not the branches the root,
desiring we might take deep root downward, that we might bring forth, in due time,
fruit upward, and cautioned against having itching tongues as well as itching ears!

At the concluding meeting Sarah Grubb at last broke through,
on the superiority of silence above words, when the power reigns over all,
reminding us of the cloud covering the tabernacle,
so that the priests could not minister;
also how it was in old times among us--such glorious meetings--quoting a piece
out of George Fox`'s Journal showing that he had nothing to do at some place,
because the people were already under Christ`'s heavenly teaching,
and needed nothing outwardly--saying we should yet be favoured with such times,
and that then what was uttered among us would gather instead of scatter us.
Oh! it was a sweet though short time;
I should have been glad if we had sunk into this solemn silence, and concluded.

L+++.+++ A. Barclay.

To L. S.

Croydon, 6th Month, 1836.

My Dear Friend,

I am inclined to take up the pen now,
and tell you that I shall much think of and feel for you next fifth day;
I hope dear M. P. will be with you as intended, if not,
if you are but favoured with the strengthening, confirming presence of the good Master,
it will be enough!
Many, I assure you,
have been the discouraging feelings that have come over me like the waves of the sea,
and had I not had a word of encouraging stimulus from some dear Friends,
I fear I should have been quite overwhelmed.
But how tenderly are we dealt with!
He knows our great weakness and how much we can bear--He
can stay "`His rough wind in the day of the east wind.`"
I often think of what the poor Indian said--that "`the work seemed so great,
and he felt such a poor,
ignorant Indian!`"--but he was instructed that being so weak and ignorant,
there was the great need for him to say neither more
or less than the great Spirit bid him to speak,
whether two, or three, or more words.
And I can say truly, this is my desire for myself, to be so preserved,
even keeping close, and low, and watchful, and faithful to Him,
who I desire should be my Lord and Master.
As the time draws near, I seem to be filled with many fears of various sorts.
Oh that I may be kept from doing harm, and then I would not mind any proving, I think,
even though I might have to sit all the meetings in silence!

L+++.+++ A. Barclay.

To A. R.

Croydon, 18th of 6th Month, 1836.

I trust the report of your dear father`'s illness was unfounded,
it would be no small disappointment to miss of his company; however,
we must leave this and everything else that concerns us
in the hands of an all-wise and gracious Providence,
who will do all things well, and for our good and instruction.
Three of our little company here were at Tottenham yesterday,
on the sorrowful occasion of dear Thomas Shillitoe`'s interment.
Ah, it was truly affecting to me, and is so continually, to think of our loss.
The change, we cannot doubt, is a most blissful one to him,
so we may rejoice on his account--but oh, such faithful, undaunted,
uncompromising veterans are rare in these days,
and their places are not--cannot be refilled soon.
We may truly say, "`a prince has fallen this day in Israel.`"
I hope I am not insensible that the great Master and good Minister,
still remains all-sufficient for His struggling, panting, little ones;
and He can make a way of deliverance and help for them when they can see none.
So let us trust still in that Arm which is not shortened that it cannot save.
Oh, that He would cause the mantle of the Elijahs to descend upon the Elishas among us,
and make the feeble ones to become as Davids, strong in the Lord`'s might,
and wise in His wisdom, and humble and low in His pure fear!

L+++.+++ A. Barclay.

To L. C.

Croydon, 18th of 8th Month, 1836.

My Beloved Friend,

I fear you will wonder what is become of me, or at least of my feeling--nevertheless,
I would assure you, it is as strong as ever,
rather increased than diminished by the union with a Friend whom I love and value.
I have many times (as you will suppose) thought of
you with feelings of interest and strong desire that,
seeing the Lord has been pleased to bring you together (I fully believe) in His fear,
you may be daily careful to seek after preservation therein.
Thus will you be preserved from the snares, supported under the trials,
and strengthened for the duties that are attendant
on such a change of condition--and thus,
trusting only in the Lord for strength and preservation,
and doing faithfully and heartily what good your hands find to do for His name,
you shall dwell before Him in the land, even in a sense of His love and life,
and verily you shall be fed.
And as you delight yourselves thus in His ways and in His fear,
He will give you the desires of your hearts,
even to know more and more of His precious precepts, and wonderful dealings,
and mighty strengthenings, to the increase of His praise and glory.
I feel as if it were the grateful language of your heart,
"`What shall I render unto the Lord for all His benefits toward me?`"
and I know it is your desire to bring in all the
tithes of your increase into the heavenly treasury:
may you then be made fruitful in the field of offering,
even in the deep begettings of the pure life!
And may your dear partner also, by an indwelling with that which is low and pure,
witness a continual and increasing qualification to strengthen the true growth,
and to protect the good fruit.

I prosecuted my intended little trip into Essex, after we parted,
and was out till last week (third day night).
It proved very satisfactory to me, being mercifully helped to clear myself at Haverhill,
which I had had for years in my mind`'s eye.
I then went on to Halstead and Earls Colne to see my dear friends there,
and attended their meetings, also Maldon,
and took tea one evening at Sudbury with dear M. King--dear
old Friend! she seemed so cheered to see me;
I do like to visit our dear ancients who are laid by.
The visit to C. was indeed a sweet picture of a happy union.
Dear W. and H. I. are truly united in spirit;
there seemed such a peaceful sweet covering so continually over us, I said in my heart,
truly the Son of peace is here!
Dear Sarah Grubb was so overdone with public meetings I could not call on her,
to my disappointment.
This little recreative tour has done me good after my late more exercising one,
and I have been favoured to enjoy my comfortable home with a sweet relish and, I trust,
a grateful heart.
And oh,
that so many mercies and benefits may lead to proportionate returns of fearless faithfulness,
humble watchfulness, and filial confidence--for surely, surely, who is like unto Him,
and to His faithfulness round about Him!

L+++.+++ A. Barclay,

To A. and E. R.

+++_______+++, 1836.

I have long felt warmly interested in Kentish Friends; but, dear friends,
mere warmth of natural feeling or kind interest, I trust, will never move me.
No; I have said again and again in my heart,
let nothing move me but Your constraining power--let nothing hinder me when that moves!
And truly it is no light matter to move in such an awful service; but the good Master,
if He move and put forth, I trust will go before, and guide and strengthen unto all,
support under all, and preserve through all in humility;
and so I desire to live a day at a time at His good hand,
who can make the very weak to become strong.

L+++.+++ A. Barclay.

To +++_______+++.

+++_______+++, 1836.

My Dear +++_______+++,

In looking over the conversation of the day, yesterday,
I was afraid it had been too much about persons rather than things;
and I was afraid that anything like self-complacency or
looking with a judging eye should creep into myself,
in so doing, rather than to dwell under a humbling sense of His goodness and power,
by whose grace alone we are what we are (if we are in any measure what we should be!),
and by whose preserving power continually extended,
shall we be kept in that grace wherein we stand!
I thought there was at one time a precious little feeling stealing over us, as it were,
something like the strengthening and peace-giving influence of our dear Saviour^
footnote:[John 20:19]--I long at such times that we should
not shrink from opening the door to such a visitant!
Surely when He thus looks in on our social evenings we do not need words,
nor ought we to look for them, nor fear they will be looked for;
such a feeling cramps and hinders that communion which is so precious.
I was afraid also whether I had appeared to speak improperly
of my little visits at the other side the river;
I only intended to set forth His goodness who had so graciously made a way,
both outwardly and in the minds of others;
for truly I am very unworthy to lift up a finger towards the help of the least.

Farewell, desiring your remembrance of such poor striplings, when favoured.

L+++.+++ A. Barclay.

To E. D+++_______+++, Junior.

Croydon, 9th Month, 1836.

My Dear E.,

The seeing you this morning, I believe for the first time, in your Friend`'s bonnet,
seemed to awaken in my heart much affectionate interest for you,
and I thought I could salute you in Gospel love, and wish you the best speed,
even God`'s heavenly speed, on your journey through life (beginning, as you now are,
as it were, a new stage of it); and oh, that your journey may be towards Zion,
for that is the only way to blessedness--it is the city of God, the new Jerusalem,
the city of peace, and all God`'s saints and people are citizens of it;
let nothing and nobody hinder you from seeking to belong to it,
for out of it you shall be out of true peace and true blessedness!
And in order that it may be so, let your face be steadfastly set toward it;
let the desire of your heart be to seek the Lord your God,
and to know the way to his Zion.
Let it be evident to others that this is your bent,
and let the language of your example to others be, "`Come,
and let us join ourselves to the Lord in a perpetual covenant
that shall not be forgotten`"--a covenant even made by sacrifice.
And if you are thus desirous to be led aright by Him,
He will show you that to "`walk in the light of the Lord`" is the way to His holy mountain,
His city of peace and blessedness.

Therefore, oh, my dear girl,
be willing now in your youth to walk in the light of the Lord Jesus Christ,
which shines in your heart,
and will clearly show you what is pleasing and what is displeasing to God,
both in your thoughts, words, manners, dress, and conduct.
Think nothing too small it points out to you,
neither be ashamed of following it implicitly, for it is the light of your dear Saviour,
and it is His precious voice speaking in you,
and it will be your condemnation if you hate or despise it.
As you are obedient and faithful in the little,
so He will teach you more and more of His precious ways,
and strengthen you more and more to walk in His peaceful paths,
and this will be God`'s heavenly speed which I greatly long for for you;
and then you will be a great comfort and a blessing to your dear parents,
and a good example to your brothers and sisters, and all others around you.

L+++.+++ A. Barclay.

To E. R.

Croydon, 2nd of 12th Month, 1836.

My Dear Friend,

It seems very long since I took up the pen to you,
and although I have not heard from either of you since I last wrote,
yet I feel inclined to assure you that the sweet feeling
of union and love continues unabated by time or distance,
nor does it need words to fan the flame of it.
How precious is it to feel this,
extending over sea and land--even towards those unknown by outward ken!
But this may savour of boasting;
oh! how most unworthy is a poor worm to be permitted to
feel the least spark of this precious union and love.
Surely it is nothing of our own that we can fabricate
with our creaturely warmth and activity,
though there may be imitations of it, under the enemy`'s transforming influence.
Ah, it is like a tender plant that soon withers and dies when dwindling
or cut off from Him who is the life and the true vine,
from whom alone is its freshness, and its fruit is found.
Your poor correspondent longs that nothing may hinder
the preservation and growth thereof in her,
but that, nourished by the flowing of the heavenly sap,
there may be proportionate fruit produced to the praise of the great and good Husbandman.
And the testimony of this love is strengthening and animating to the poor drooping mind,
weighed down under a sense of the state of our poor church--the dimness of the gold,
and the changedness of the fine gold.
Ah, is it not a day for such burden-bearers to cling close one to another, and,
above all, to Him, the mighty strengthener!--to speak often one to another,
in the Divine fear,
and in the remembrance of His wonderful goodness and power--encouraging
to a continued confidence in His never-failing arm,
and a renewed watchfulness and faithfulness before Him.

My thoughts have been often turned towards you lately, with rejoicing,
that the feet of our dear faithful labourers, George and Ann Jones,
have been again led your way,
and I long to hear all that your kind pen can tell
me about their visit in your monthly meeting,
towards which you know I still have much of a homish feeling.
I hope nothing will scatter what they have been enabled to do among you.

It is come to pass,
as dear Sarah L. Grubb had to foretell sixteen years ago--I remember it,
and she told us we might put it down in our pocketbooks--that
we were mingling (three times repeated),
and that, if we did not retrace our steps, we should be so mingled with the people,
by degrees, that, by and by,
we should think there was no occasion for this or the other query,
and at last for any discipline at all!

L+++.+++ A. Barclay.

To E. R+++_______+++n

1st Month, 1837.

We have been solemnly warned by the sudden removal of dear Rebecca Christy.
It was a comfort that she was in the bosom of her family, and having her husband with her.
After attending Gracechurch Street meeting, held in silence,
she remarked to William Allen,
she thought she should not be much longer here--that she
hoped they might soon be singing the songs of Zion.
She was taken ill that night, and confined to her bed.
Before the close, she addressed her children separately, saying,
"`Mind not the world too much; it will eat like a canker; I have seen it,
I have seen it.`"
Her end was peaceful.^
footnote:[The following extract from the Annual Monitor for 1839,
it is thought will not be out of place here.
"`A few days before her decease,
when her mind appeared to be under concern at the state of our religious Society,
she said to her husband:--'`When I consider the manner
in which those Friends who are leaving us,
speak of the "`inward Light`" (it being the Lord`'s grace or Spirit placed in the heart),
oh! it does grieve me more than all beside.
Oh, what should I have done when I was a young woman, but for that in the heart,
when I had no one to help me or direct me.
How clearly did it show me what was right and what
was wrong!`'`" (Obituary Notice of Rebecca Christy.)]

L+++.+++ A. Barclay.

To R. R.

Croydon, 17th of 1st Month, 1837.

It was pleasant to hear of your excursion to Chichester,
and how you could speak well of His goodness who does not
fail His poor dependent ones in the needful time.
Oh! this is animating to think of,
and we may and must recount His mighty acts and speak of His great goodness.
It is the poor and the empty whom He delights to fill and to enrich,
and He makes them so, that He may do so.
Oh, what condescension!

I suppose +++_______+++ applies for membership from having been brought up among Friends,
not on the ground of convincement.
I wish she may be brought to feel really with us, and not merely a preference to us.
Why should many cover themselves with our cloak, and not faithfully wear and bear it?
as dear Sarah Tuckett says.
But I fear you will set me down as a very strait body, and a complainer in Israel.
Well, I cannot help it; I have a very high sense of what we ought to be, and oh,
that I may be made so, by any means, however battering and beating,
turning and overturning! for truly I do not wish to judge others, but rather this,
that I may not put a stumbling-block or an occasion of offence before them.
I have long been of the mind that our meetings for discipline are too open,
and that the old way of their being confined to those who are "`faithful men and women,
grown in the truth;`" and as it is seen that any young people, or others,
evince such a growing qualification, to invite them thereto,
would be preferable to our present very mixed state,
in which the discipline is handled by unclean hands.
I did not intend to write thus, dear +++_______+++, and have no particular object in view,
but as it arose while writing,
and not knowing that I had ever expressed as much to you before,
I thought I would pen it.

The rapid rolling on of weeks and months is indeed fearful and awful.
May I be enabled to watch and wait, in calm resignation and faithful confidence,
on Him who can make clear, and give strength to bring forth.
We have had an acceptable family visit from R. B., that to me was very helpful.
It is very trying to see what a desire after words,
and a leaning upon the poor instruments, there is among us.
How sad, and what a dereliction of principle it is to do so,
and thus to worship the gift instead of the giver.
Oh, that I may ever be preserved from gratifying this itching ear, whatever it cost.

We had a sweet social visit from dear W. Gundry in his way to you.
I greatly enjoyed his company, feeling him as a father (and oh,
we have few fathers!). He dined with me, so I had him alone,
which is a treat to my poor deaf powers, that I seldom have.
Before we separated, we had a precious opportunity, much in silence,
in which we were melted together and favoured with that feeling which is beyond words,
although these were not withheld for my help and comfort.
How grateful should I be for all these helps!

L+++.+++ A. Barclay.

To L. C.

2nd Month, 1837.

There is so much shrinking with some that it makes it hard work,
but it is to our own Master we stand or fall, and we must not love father or mother,
even, more than Him and His precious cause.
Let us not shrink from suffering afflictions for Christ`'s sake,
but rather rejoice that we are counted worthy, in ever so small a measure,
to fill up that which remains, for the body`'s sake, the Church.
Some, perhaps, may think me uncharitable in my remarks; but One knows my heart.
To be united to Him and to all that is of and for Him, is all that I desire.

Farewell, dear L., with dear love I remain your affectionate friend,

L+++.+++ A. Barclay.

To E. K.

Croydon, 4th Month, 1837.

My Dear E.,

I hardly feel easy to leave home without sending you a few lines,
indicative (far more than I could do personally,
no doubt,) of the affectionate interest that has always lived in my heart towards you,
and which is by no means lessened the last year or two,
although the expression thereof has but seldom been made.
I do not forget your affectionate letter in the second month of last year,
of which I have taken but little notice outwardly,
but the contents of it have often been very present
with me (especially during the autumn and winter,
when my mind seemed more at liberty),
though the yearning and affectionate solicitude that has attended me in reference
to you has hitherto been known only to the great Searcher of hearts.
Ah, He knows the travail of my soul on behalf of some in our meeting,
for surely He gives to feel it--and He knows the fears also of His poor weak creature,
lest, on the one hand,
the blood of a dear brother or sister should be required at my hand, and, on the other,
lest I should in any way step improperly,
so as either to crush that which is tender and strengthen the wrong part in any,
or be acting in the creaturely will and wisdom as if I were better than my neighbours.
Ah, it is an awful thing to have a testimony put into our hearts and
into our mouths for Him! the Lord help His poor worm to be faithful,
and preserve in the depths of humility!

In reading your letter and in the interaction we have had together since, dear E.,
I have frequently feared that there was too much of a tendency in you to lean upon others,
to live, as it were, upon their encouragement--I know it is a common weakness,
I feel it in myself,
but the Lord has graciously turned His hand upon me to lift me out of it; and will,
I do thankfully believe, still more mar this dependence, and starve this desire,
whenever it arises; and I do rejoice in His tender care of me in this respect.
For oh, I do increasingly feel, and I long for you also increasingly to feel,
that we must dwell deep, sit alone and keep silence,
bearing His yoke upon us--then we shall increasingly
feel how good He is to those that seek Him alone,
and wait upon Him in the way of His judgments, that so they may learn His righteousness,
and judgment may be brought forth unto a perfect victory!

We must dwell deep--not be looking outwardly,
for the kingdom is within that is to be overthrown,
the strongholds are within that must be razed to the very foundation,
and the strong man armed turned out thereof;
and the kingdom is within that is to be set up above every kingdom, even the heavenly,
peaceful kingdom of our Lord and Saviour Jesus Christ,
and the beginnings thereof are sown in every heart;
it is there we must watch and labour for the growth of the blessed seed of the kingdom,
for the spreading of the heavenly leaven,
even by yielding to the puttings forth of the power thereof,
allowing Christ by this measure of His blessed Spirit to
crucify the old man in us with the affections and lusts,
and to bring us into a conformity with the will of God,
and consequently into a union with Him!
And in the progress of this heavenly work, it will be good for us to sit alone,
from outward dependencies, looking and leaning upon Christ alone,
the all-sufficient teacher and support of His redeeming people!
And let us silence all fleshly desires, and resign ourselves to the Lord`'s will,
though He slay our creaturely will, and confound our creaturely wisdom,
and bring to nothing that in us which would so continually rise up and be something.
Oh! thus let us bear His heavenly yoke upon us in our youth (O what poor weak
children are we!) let us allow Him to break us to pieces by falling upon Him,
yielding to His power inwardly revealed,
and let us be willing to manifest to others (and verily it shall be so
in our whole conduct and demeanour) that we are of His broken ones,
His melted ones, and then assuredly there shall be hope for us,
a glorious hope (not the hope of the hypocrite), a hope full of immortality;
the Lord Jesus Christ shall confess us before His Father and the holy angels,
to be of the number of His dear sheep, His purified ones!
This, dear E., is the earnest desire of my heart for you, as it is for myself,
and I would be your companion in seeking, in labouring after it.

And now I would bid you affectionately farewell, remaining your poor weak sister,
but very sincere friend,

L+++.+++ A. Barclay.

To R. R.

Croydon, 17th of 1st Month, 1837.

It was pleasant to hear of your excursion to Chichester,
and how you could speak well of His goodness,
who does not fail His poor dependent ones in the needful time.
Oh, this is animating to think of, and we may and must recount His mighty acts,
and speak of His great goodness!
It is the poor and empty He delights to fill and to enrich,
and He makes them so that He may do so!
Oh, what condescension!

L+++.+++ A. Barclay,

To Mary Hagger.

Croydon, 26th of 3rd Month, 1837.

My Dear Friend,

I have often thought of you and talked of you too, with much love and unity,
and it does me good to remember such dear faithful friends as yourself;
it animates me to desire to walk in your footsteps,
in following faithfully and serving unreservedly the one good and great Master,
whom indeed you have found to be a good one, and worthy to be loved, served, trusted in,
and obeyed--and that by the whole house of the spiritual Israel.
And now you may be old and gray-headed, He does not forsake you,
even the dear faithful ancient ones, but is near you still,
to support and strengthen you, to comfort and preserve you in patience,
until He shall be pleased to take you to Himself.
Well!
Oh, that I may die the death of the righteous,
and that my latter end may be like his--peace!

You are privileged who are in a quiet, snug corner,
and neither hear or see what is going on among us much;
and yet I think the rightly exercised mind, however secluded, must feel how things are,
and the deep exercises and secret breathings and pleadings, on behalf of the body,
of these hidden ones, are helpful, though they are reluctant to believe it.
Therefore, dear friend, may you be encouraged in your deep wadings and mournful provings,
to put on strength in the name of the Lord; and when it is well with you,
breathe for the help of worm Jacob,
for the strengthening and preservation of the little ones,
even in fearless faithfulness and in humble watchfulness,
that their eye may be singly and simply unto the Lord, their mighty one,
for by Him alone shall Jacob arise, though he be but very small and despised,
and the Lord can cause the weak and foolish ones to confound the wise and the prudent;
and He can call them that are not, and them that are base in man`'s estimation,
to stand up for His great name, that no flesh should glory in His sight!
Amen, says my very soul! and may He work what He will work for the purification of His Church,
and for the glory of His great name;
for I do believe that He will have a people for His praise, whether we will be gathered,
yes or no.
I am ready to say, "`the whole head is sick, and the whole heart faint.`"
Yet we have a skillful and powerful Physician.
Oh, that He may turn His good hand upon us again and again, and not cast us off forever,
for we are called by His name.

There have been many deaths about and much sickness.
I feel it a great favour to enjoy my usual health, indeed I might say,
better than usual for the winter;
so that I feel bound in gratitude to yield up to what I
have apprehended for years to be the pointings of duty,
namely, to go and sit with our dear friends at Dublin yearly meeting,
and I look to going in about three weeks time--my friends
having liberated me for the purpose last week.
I hope you will remember me for good,
for indeed I have great need of the prayers of the faithful,
and have great faith in their success.
May the Lord help His poor weak handmaid to be faithful and deeply humble before Him.
And oh, that I may be preserved from bringing any reproach on that blessed cause,
which I do trust is more precious to me than natural life.

Farewell, my dear and valued friend.
I shall hardly look for you at our yearly meeting,
but believe you will be with us in mind.
With kind love to your daughter, I remain your truly affectionate friend,

L+++.+++ A. Barclay.

P+++.+++ S.--My pen has run on, I trust, in innocent freedom, unconsciously,
for I did not think to write more than, as I said, a few lines.

To +++_______+++.

4th Month, 1837.

My Dear Friend,

I do not feel easy to leave home at this time without taking up the pen to write you,
I trust, in Gospel love,
especially as we had not the ride together to W.
when I hoped to have the opportunity I desired.
You remember when I called to ask you to go with us,
you touched upon the subject of joining with others in the Bible district visiting,
in allusion to +++_______+++. Being in haste at the time, I could not enter upon it,
but the subject weighed upon me much,
and the desire increased to have some conversation with you on it,
as I feel it to be one of no small importance,
connected as it is with the bringing up of our dear young people.
I quite unite with the object of the Bible Society in the spreading of the holy scriptures,
and the encouraging the diligent perusal of them;
but inasmuch as we believe it to be very wrong to give them that appellation,
and that honour, which belongs only to our blessed Saviour,
I should not feel easy either to attend the committees or to hand,
in the course of the district visiting, such papers and tracts as use such terms.

With respect to our dear young people,
I would not encourage them either to attend the committees
or to join in districts with others,
for the above reason,
as well as I believe it would be injurious to them to mix with those of other denominations.
We know (and do we not feel it even in ourselves?)
how very insinuating is the spirit of the world,
how it insinuates itself into us under such very pleasing
and plausible pretences (as of our doing good to others,
and desiring that our religion should not wear a gloomy aspect,
as if we thought ourselves holier than others, etc.),
and thus are we most gradually drawn off the watch into a shaking hands, as it were,
with the worldly spirit in others, instead of, in our conversation and demeanour,
testifying against it, and being a reproof to it.
And surely, if we must feel and acknowledge our own weakness in this respect, how can we,
in conscience towards God (knowing that we shall be accountable
for the dear lambs committed to our faithful charge),
allow or encourage our beloved young people to run into
such temptation in their tender and inexperienced state.
And hereby are we also endangering their religious principles (as well as practice);
for the principles of others, who are thus united with us,
have such a plausible and taking appearance;
they are generally the most serious in the profession of them,
and with pleasing manners are very likely to mislead the young and inexperienced,
and weaken their attachment to those principles in which they have been educated.

These are my sentiments on this subject from conviction, in my own mind,
from experience of the effects in myself, and from observation of them in others;
and I think I shall hardly be acting the part of a sincere and faithful friend to you,
my dear +++_______+++,
without adding that I have for some time past felt and lamented the effects in you,
I mean of associating with those not of our Society,
and permitting the children to do so too.
I know that the education and bringing up of dear
children rests very much with the mother of a family,
and I would, in true affection, beg of you to consider impartially,
to weigh in the true balance,
whether it is not better to make any sacrifices (either of expense
or of education) rather than to subject our dear children to the
interaction with others in sending them to their schools?
for are we not thereby opening a door which we shall not be able afterwards to regulate!
Oh, that the example before our dear children,
as well as the precepts we may inculcate in our conversation,
may be such as will strengthen them in obedience to the
discoveries and reproofs of the light of Christ,
and in a faithful attachment to the testimonies of His blessed Spirit,
which ever was and ever will be contrary to the wordly spirit!
I know very well I may be thought to be narrow-minded in these remarks and sentiments,
but oh! let us sift such a thought.
Is it not that which would shake hands with the worldly spirit that says so?
Is not the way to life strait and narrow?
We must not please the worldly spirit either in ourselves or others,
if we would walk therein; we must be stripped of it, we must take up the cross to it,
that is, yield to the Spirit of Christ which will crucify it,
if we would escape the broad way that leads to destruction;
and we must be content to be thought narrow by the world,
if we would be of the number of Christ`'s little flock of redeemed ones,
redeemed from its spirit, and precious in His sight.
The blessing is to those who are despised and reproached
for obedience to Christ`'s Spirit,
and the woe is to those who are spoken well of and flattered by the world,
for the world loves his own,
and whosoever will be a friend of the world is the enemy of God.

And now, my dear friend, I must draw to a conclusion.
I know you will not take this my sisterly freedom to be
impertinently intermeddling in other men`'s matters;
you will take it in the sincere love which dictates it,
you will let it have its full weight, by retiring inward,
and waiting to feel the light of Christ`'s blessed Spirit,
to show you how things really are with you.
Oh, He is the faithful and true witness, that will not flatter us;
and may His gentle whisperings and secret discoveries be faithfully attended to,
both by example and precept, whatever may be the sacrifice,
or the mortification it may involve; for what will it profit us,
if we shall gain the whole world and lose our own soul`'s peace!
We had better cut off our right hand and pluck out our right eye than be an enemy to God,
and separated forever from Him, who loved us, and gave Himself for us.

Farewell in true and tender love,
and under a humbling sense of my own utter weakness in every respect,
and unworthiness to hand at any time even a cup of cold water,
whereby the precious tender good thing in any dear brother or sister may be strengthened.
Oh!
I feel it an awful thing to stand in the station of a minister,
or a watchman for the Lord, to give warning to others, and to testify for Him;
and I do desire, in the endeavour to be clear of the blood of all,
to be ever preserved in the depths of humility, and in the pure fear of the Lord alone!

I remain your sincerely affectionate friend,

L+++.+++ A. Barclay.

To Hannah Marsh

Reigate, 1837.

&hellip;I hope this journey will do you good.
Give my love to +++_______+++,
and say I hope nothing will hinder him from attending to the manifestations or secret
feelings of hesitation given by the Spirit of Christ in the secret of His heart,
in relation to however small a thing, and even what man`'s reason may cavil against.
There is no other way for strength of sight and of feeling being increased,
but by faithfulness to the little.
Tell him I hope he does not sell prayer books and altar companions;
we ought to have a testimony against them, and not promote them.
And, dear Hannah, do be faithful at that large meeting;
do not be afraid to please the dear Master.
I hope your visit will be blessed to many.
And now farewell, dearly loved friend,
"`let us always trust Master,`" as the dear negro said to William Williams,
and then we shall farewell.
Your affectionate friend,

L+++.+++ A. Barclay.

+++[+++In the 7th month of this year Lydia A. Barclay was liberated by her monthly meeting,
to visit the meetings composing the general meeting for Scotland,
and also those of Nottinghamshire and Derbyshire on her return home.
In this religious engagement she was accompanied by Sarah Knott of Ireland,
who had been liberated for similar service in Scotland.]

To +++_______+++.

8th Month, 1837.

I believe I must acknowledge that my mind was drawn into much sympathy with you,
ever since your kind call on us soon after our arrival in +++_______+++,
as well as while we were sitting together the other day.
This feeling was not decreased, but rather increased, by hearing, as we went to +++_______+++,
that you have sometimes a little word for our good Lord in the assemblies of His people.
Oh, my dear friend,
it is indeed (as you well know) a deeply exercising time for such in the present day,
of treading down and of despising the treasures of the inner court.
Many and deep are their sufferings, their faces often gather paleness,
and they go as with their hands on their loins in painful travail,
and they are often ready to say, "`If you deal thus with us, slay me, I pray you.`"
The enemy often pierces as with a sword in their very bones, saying,
"`Where is your God?`"
besides the daily renewed sense of their own weakness, and poverty,
and utter unworthiness, so that the language of their soul is,
"`Who is sufficient for these things?
Behold, I am a man of unclean lips, and I dwell among a people of unclean lips!`"
Yet oh, my dear friend,
the Lord is sufficient to cleanse and to qualify for His own work,
and He can work by weak and feeble instruments,
and I do believe He will more and more raise up such among us,
and give them what some would call a weak, foolish testimony, or way of preaching,
that no flesh may glory in His sight,
but that His mighty power may be the more conspicuous,
and His praise perfected as out of the mouths of the babes or simple ones!

I feel greatly for you in considering the place and the meeting where your lot is cast,
a place of great profession (as I apprehend) and of jealous looking at us as a people;
and a meeting involving much suffering and exercise of mind,
considering the lukewarmness of some,
the shaking hands with the worldly spirit in others,
as also the visitation of God`'s love still extended to the dear youth,
in many of whom the tender seed of God`'s sowing is panting after life.
Oh, that you may be enabled to cherish the one,
and faithfully to testify for your God against the other,
following your dear Master`'s leadings, nothing doubting and no man fearing;
and as you are concerned thus to honour the Lord
and seek His heavenly approbation above all,
He will honour you and make you an instrument in His holy hand,
to make war in righteousness (or uprightly) against all His enemies,
to strengthen the weak things that remain and seem ready to die,
to gather again the dispersed of Israel, and to cherish the tender thing of Him in all.
And, dear friend, in the course of this good work,
I trust you will find the discipline to go hand in hand with the ministry;
both need a faithful exercise; they are branches from the same root,
require the same life to quicken and make them fruitful.
If the discipline be not faithfully exercised (even
in the life and in the wisdom of Christ,
the ever blessed and unchangeable truth), disease creeps over the body,
and the ministry must also languish or partake of it.

Oh, dear friend, fear not,
neither let your hands be slack in whatever they
find to do for your good Lord in either way,
but be diligent and faithful in the little,
and that is the preparation to receive more from His good hand;
but every act of disobedience brings dimness of sight
and weakness of limbs against another time.
Oh, I have lamentably and often found it to be so in my very stumbling and childish experience!
And look not out at others, neither at your loneliness,
and the lack of fathers and mothers,--"`it is better to
trust in the Lord than to put confidence in princes.`"
The present is peculiarly a time when not only the earth,
but the heavens also are to be shaken in us.
We must not lean on a friend, or put confidence even in a brother,
but let our eye be single unto the Lord alone, and then we shall have plenty of light;
and our leaning be simply and wholly upon Him,
and then we shall have abundance of strength!

L+++.+++ A. Barclay.

To Hannah Marsh

York, 9th of 7th Month, 1837.

We went to Kinmuck, and sat with six families out of eight; had a meeting there next day,
which was a memorable and melting one, that I shall not easily forget.
The Lord greatly helped His poor weak handmaids, and the glory was ascribed unto Him.

Next day began the family visits at Glasgow (consisting of eleven or twelve); and found,
to our great comfort, a precious remnant.
I had to remember (and to mention too) in one of them,
how it was with one of our ancients formerly, who, when he came to a certain place,
found them gathered and settled under the inward teaching of Christ their Saviour,
and sat down among them in silence.
Nevertheless, a song or testimony to His goodness and preciousness was put into my mouth,
and we were all melted into tears.
The meeting on the fourth day (last week) was a memorable one,
so that it seemed hard to break it up, as well as to disturb it.
Several attended who were not Friends.

L+++.+++ A. Barclay.

To C. D.

Nottingham, 16th of 9th Month, 1837.

My Dear +++_______+++,

I trust I may now inform you,
under a grateful and humbling sense of the great goodness
and tender compassion shown a poor unworthy one,
that I am thus far on my journey homeward,
and I assure you that the thought is quite animating,
indeed I am ready sometimes to fear that the last
week I have been almost too longing to reach it,
counting the days, as it were,
yet am continually reminded that every day has its proper duties and trials to
be borne and done in that power which is so graciously and daily vouchsafed;
or, as a dear friend remarked to me yesterday, when I was alluding to the subject,
our home is subjection to the Divine will; I thought there was much in it.
Oh, this is indeed the quiet and peaceful habitation, the place of true prayer,
and where my soul longs to dwell forever;
and there will there be continual incense and pure offerings
ascending with acceptance before the holy One of Israel!

I suppose you would hear of me from dear Hannah Marsh, to whom I wrote from York.
I rested there all last week, but did not seem to get much on in strength,
even when I left it a week ago for Chesterfield,
so that at times I felt much disheartened about myself,
the mind often partaking of the bodily weakness.
On First day night I parted with my kind guide, Joseph Spence,
and on second day morning again launched forth,
a poor stranger alone,--but the ride through the bracing air of Derbyshire did me good;
third, fourth, fifth, and sixth days in this week I have sat in six meetings,
all appointed ones, and several have been attended by many of the neighbours;
the members are very few.
In two of them, I heard that one woman went generally and sat alone on a week day!
I reminded some of them how that Friends sprang up at first by ones and twos,
and that one faithful Friend might be the means of gathering many around him.
Fourth day was very fatiguing to the poor body,
travelling twenty-five miles in an open chaise over a rough road,
and having two exercising meetings: also yesterday,
thirty-three miles principally in an open chaise, and two meetings,
so that last night I was much exhausted on arriving here.
Yet I may acknowledge that which has felt very trying and rough to nature,
has been graciously smoothed down and sweetened to me,
so that sufficient for the day has been the strength extended!

Farewell, dear +++_______+++, I cannot add more, having to call on some elderly Friends.
So with kind love to all our Friends, I will remain your sincerely affectionate friend,

L+++.+++ A. Barclay.

To +++_______+++.

Croydon, 28th of 10th Month, 1837.

The poor servants must not expect better treatment than their Master, to be despised,
reproached, accused,
and said to be beside themselves! yet I do see that there is great danger
of such servants as have to cry woe against the evil things among us,
getting from off the watch and out of the humility and fear
in which alone is preservation in a true gift,
and so something of the creaturely activity and zeal,
creeping in and attempting to do the Lord`'s work,
which can only be done in and by His own blessed Spirit, which leads into the patient,
cool, humble state.
I feel greatly exercised on behalf of those dear Friends who, I do believe,
are on the side of the ancient and unchangeable truth,
and faithfully concerned for the proper exercise of the discipline,
that they may be preserved from the former danger, and in the latter state.
We have such daily proof how very imperceptibly (to themselves and to others)
many of those we have highly valued slip off from the true foundation.
It is very humbling and dismaying,
and should lead to a closer watchfulness and dependence on Him, who is the best Friend,
desiring to be preserved low in the pure fear.

I have great cause to acknowledge His goodness and mercy,
who so condescendingly helped me along from day to day in my late journey to Scotland,
bearing up my poor mind during the many exercises and deep conflicts permitted,
and strengthening the weak body to endure the great fatigue required.
Some of the meetings were times of great favour both in silence and otherwise,
so that it seemed hard to break them up,
and our hearts were melted under a sense of the Lord`'s goodness,
and the praise ascended unto Him, to whom does all glory belong.
I was greatly interested in going to see Ury, the seat of my worthy ancestors.
I went all over it, and to the burial place on the top of an adjacent hill,
on descending which (with a beautiful view before me),
my mind was revolving on good old times,
and led to desire that I might be enabled to follow
the faithful example of those dear worthies,
who had trod those paths,
that so I might not only bear their name but also partake of their spirit,
and be united in a precious fellowship with them and the just of all generations,
through the tender mercy of God, in and by his beloved Son,
who is the bond of all true fellowship.

27th of 11th Month,
1837.--Nor can I describe my feelings towards all
people around that part (Ury) and Aberdeen.
Oh, that they might be gathered up as from the earth, and brought down as from the air,
even from the Lo here`'s and Lo there`'s, unto Christ, the peace and rest,
the treasure and sure foundation of His people.
Do give my dear love to dear Amos and Barbara Wigham.
How sweet it was to be with them!
I would much rather be with such dear simple Friends than in the fine
drawing-rooms of those who are shaking hands with the world`'s spirit.

I must now look forward to a little time of quiet,
at my comfortable and very desirable home, but how long I may remain in it I know not,
feeling that all I have and am must be at the disposal of Him who gives it me,
or rather lends it; and oh, to spend and be spent in His service, if it might but be,
is my earnest desire.

L+++.+++ A. Barclay.
