== Chapter VI

[.letter-heading]
To J. B.

[.signed-section-context-open]
Croydon, 11th of 11th Month, 1837.

[.salutation]
My Dear Friend,

I send you herewith, according to promise, a set of my brother John`'s Tracts,
both from Penington and Penn,
and I have no doubt you will do your best toward circulating
them among any seriously inclined persons out of our Society,
as well as any of our own members.
The former class (those out of our pale) are as much an object
with my brother in his publications as our own members.

I cannot but believe there are many now (as there were in the days of our early
Friends) who are wearied with wandering from one mountain of profession to another,
and are now looking as it were towards us;
and though the present state of things among us is very shaking and stumbling
to such sincere inquirers (seeing that so many are now going back,
almost insensibly, to the very door of the house of bondage,
from which place our fathers were brought out by a mighty hand and an outstretched arm!
and woe indeed is to those who thus offend these little tender ones!) yet I do believe,
if we are favoured to know these shakings and siftings among us,
to purge our camp of that which has been as an evil disease long upon us,
to the hindering of our standing before our enemies,
and of our light shining forth as brightness before the nations,
that these sincere and tender ones will then flock to us, or to the standard of Christ,
the ever blessed and unchangeable Truth, held up by us, as doves to the windows!
And my soul longs for such a day,
and would desire that we might be melted and tried any how,
so that we might yet become what we once were, and what we were designed to be,
a people to the Lord`'s praise,
to revive and hold forth the principles of primitive Christianity,
the dispensation of the Son in Spirit, which, as Isaac Penington says,
is the last and lasting dispensation.
But the mourner over the great degeneracy among us will say,
"`Who is sufficient for these things?`"
The answer arises, "`Not by might, nor by power (that is man`'s), but by my Spirit,
says the Lord;`" and His Spirit is still with us even to
the end of the world--to strengthen the faithful,
to support the weak, to animate the fearful,
to enable unto all and to preserve amidst all.
And how encouraging is that language addressed formerly to those "`whose spirit the
Lord has stirred up,`" in an honest and faithful zeal to build His house!--"`According
to the word that I covenanted with you when you came out of Egypt,
so my Spirit remains among you; fear not but be strong and work, for I am with you.`"
And how they were despised by others as poor feeble Jews, and their work a weak work;
and let us remember that even women were engaged in building the wall,
and how they all worked in fear, with a weapon in one hand; nevertheless,
the Lord owned their work and blessed it.

Is not this encouraging, my beloved friend, to all,
however weak and feeble and solitary they may feel, to do, simply and faithfully,
what their hands may at any time find to do for their good Lord,
to promote His cause and kingdom in the hearts of any,
even in the little might and putting forth that He may be pleased to give,
though it may be in foolishness to man`'s view.
And how graciously does He condescend to accept such
little acts of love as alms-deeds done unto Himself!

I often think, in looking at our state,
that a revival will be by the faithfulness of the one`'s and two`'s, hidden ones, and,
apparently, weak and foolish ones,
who will have to come forward in innocent boldness and humble faithfulness,
and take the crowns from those who have been highly favoured,
yet have adulterated from the Life,
and so have either soared up into airy imaginations (above the meek, lowly Life),
or else have gone down, as it were,
into the earthly cloggy nature (trampling upon and crushing the Life).
And do we not read how the man, who drew a bow in his simplicity,
brought down from his seat a mighty king formerly?
So I have thought a simple act of faithfulness in our meetings for discipline
may often turn the tide of things into a proper channel,
discovering what is impure.
And faithfulness leads to fruitfulness.
Every act of faithfulness leads to greater clearness
of sight and strength of hands against the future;
and, on the contrary, every hesitation, or refusing to follow as the Lord draws,
dims the sight and weakens the hands,
and there is a mourning because of the oppression of the enemy who gains strength hereby.
Oh, then, that our eye may be single unto the Lord, to His bidding, to His favour,
to His name or kingdom, and to His glory, and then we shall be full of light.
Let our leaning be simply on His arm of power,
and then we shall have abundance of strength.

I know not how it is I have gone on thus to you, my beloved friend,
except that I feel you near and dear in that which time or distance cannot separate,
and desire affectionately your encouragement in the good way,
although I feel myself to be but a very poor weak and, as it were,
trembling companion to you.
And oh,
that you also may breathe for my preservation from the many snares spread on every hand,
and in faithfulness, watchfulness, and deep humility.
I often still visit you mentally,
and remember your great kindness to me when a poor traveller among you, and which,
I trust, the Lord, my good Master, will reward you for,
for I can`'t. I may acknowledge to you, my dear friend,
that the women`'s quarterly meeting was a season of great exercise and trial to me.
I was longing for those to come forward who are now very hidden,
yet upon them I thought I saw the Holy anointing.
You know the stripling David was little esteemed by his father`'s house,
and he was out in the solitary wilderness with the flock, but he was to be anointed,
and he was enabled to smite the great defier of the armies of Israel.

Oh, how great harm has man`'s wisdom done to us as a people, as well as his riches!
It is not man`'s arts and parts, my dear friend,
that is the qualification for offices and service in God`'s Church.
Oh, they will mar His work instead of doing it.
The excellent discipline established among us is a branch
from the same root from which springs the ministry.
The same Divine life must nourish it, and pervade it, and keep it living,
or else it will be only kept up and done in the form.
It will therefore be dead.
The Lord Jesus Christ is the Head of the Church.
He is the Minister of ministers;
and I believe our discipline was set up and kept up formerly in His Spirit, and power,
and heavenly wisdom, which alone is the authority of all our meetings.
And it is they who are bowing to His mighty power
in them (however it may be in a small measure,
yet, if it be true and going on,
it is His work of subjecting their spirits) that
are qualified to put their hands to the discipline,
not those who are whole in themselves, unbroken and unyielding to the cross,
however wise, or learned, or rich they may be.
And oh, I long for the strengthening of these little foolish ones,
and rejoice to think of them, and breathe for them,
in their hidden and solitary allotments.

Well, my dear friend, I must not enlarge further.
I hope you will not misconstrue my meaning,
nor yet think any other of me than as a poor weak sister,
very far from what I ought to be,
yet desiring to press forward towards the mark for the heavenly
prize of our _high calling_ in Christ Jesus.
In that fellowship which stands not in words, but in the power of Him,
who is the life and beloved of redeemed and redeeming souls,
subjected unto and prevailing in the heart, do I salute you and your dear husband.
In dear love, I remain your very sincere friend,

[.signed-section-signature]
L+++.+++ A. Barclay.

[.letter-heading]
To R. R.

[.signed-section-context-open]
Croydon, 27th of 2nd Month, 1838.

I believe I may in confidence tell you that I feel most easy to
strike my tent from here and to pitch within your quarterly meeting.
I hope I may not be doing wrong, but that He whom I desire faithfully to serve _anywhere,_
may abilitate me for every trial and every service,
and preserve me from the many snares on every side.

[.signed-section-signature]
L+++.+++ A. Barclay.

[.letter-heading]
To W. R.

[.signed-section-context-open]
2nd Month, 1838.

My dear brother John seems to be able to look forward to brighter days for us,
and that the right hand of the Lord will yet do valiantly, and be exalted in due season.
Ah, my dear friend, were it not for such little glimpses of hope,
what should we do in these days of treading down and sore dismay!
One is ready to say, surely never did the enemy prepare his likenesses so exact,
never did he set up his beautiful images of false religion so imposingly
as now! so that it is a trying day to the weak little ones.
But there is One above him and all his images, the Lord Jesus Christ,
the Redeemer of His people and head of His Church in all ages,
in His inward and spiritual appearance in the soul,
however lowly and mean to man`'s view.
He is the stone that is to pull down and break to pieces the enemy`'s image,
whose brightness is excellent and form imposing.
Oh!
He is a precious corner and foundation stone to those who believe in,
and yield to His lowly appearance, but to those who stumble at Him, as He is the _Word,_
quick, and powerful, and piercing, being disobedient to Him,
He ever was and ever will be a stone of stumbling and rock of offence,
be they ever so wise, and as master builders in Israel!
His kingdom shall rule over all, and stand forever.
And though I and others of middle age, may not see these brighter days,
when our poor backsliding society, refined from the dross,
and separated from those who say they are Jews and are not, but do lie,
"`shall once again hold up and hold forth the ancient standard of truth and righteousness,
even in that Spirit which alone anointed and clothed it with purity, and authority,
and strength;`" yet oh! that we may breathe and travail for that day in secret,
and die in the hope and faith hereof.
And oh! that we may never in anywise do anything
whereby such a glorious war may be hindered.
I have no doubt, my dear ancient friend, you are enjoying the lives of Pike and Oxley;
it would gladden your heart to have such dear testimony-bearers
held up to view as patterns of simplicity and faithfulness.
I know you would unite with dear John`'s remarks scattered here and there in the preface;
they are too close to please the taste of many who are pleading
for more and yet more liberty to the flesh,
and shaking hands with the wordly spirit.

[.signed-section-signature]
L+++.+++ A. Barclay.

[.letter-heading]
To E. R.

[.signed-section-context-open]
Brighton, 12th of 3rd Month, 1838.

[.salutation]
My Endeared Friend,

You are one of those I love to cling to in thought and feeling, as being,
I trust I may say,
nearly united to in the precious blood of a fellowship far
superior to that of an outward relationship or friendship,
even as much so as "`that which is not seen`" is to "`that which is seen.`"
And how greatly do I desire that I may not forfeit this precious
union and communion by letting go that subjection to,
and leaning on, and abiding in Him, who is the life and beloved of redeeming souls,
and whereby alone this union and fellowship is attained, preserved, and strengthened,
and in whom we have the true enjoyment of our dear Friends, whether present or absent,
whether in the suffering body, or whether taken out of the body,
to be ever with Him who loved them and washed them!

I may truly say, your letter was helpful and encouraging to me,
and it seems strengthening sometimes to remember
you and a few other dear faithful suffering ones;
and if it were not so, I think I, for one (being a very fainthearted one), should faint;
for one is often ready to say, "`By whom shall Jacob arise, for he is very small.`"
All seem to seek their own, and not the things that are Jesus Christ`'s,
in truth and uprightness, very many being deceived by the likenesses of things spiritual,
through the subtlety of the devil, who goes about seeking to deceive the very elect.
Even the fathers and mothers (or those who ought to be so)
are taken unwarily and unwittingly by his baits,
so like the life are his images; and we are uncertain of our dear and heretofore nearly,
united Friends even in a few months time.
So it is a time (even for the weak ones) not to look to, or lean upon, a _near_ friend,
or a dear friend; and the precious cause of Christ,
the ever blessed and unchangeable truth, must be dearer to us than father or mother,
brother or sister, wife or children, else we shall not be worthy of Him,
or of His confession of us before His Father and the holy angels.
My dear brother John and I feel very solitary often; he cheers me up sometimes,
at others, he gets low.
He has relieved his mind in putting forth the preface and
his other remarks interspersed through Joseph Pike,
in which I have no doubt you fully unite.
Some know not how to bear such close things,
but I think they are many words in season to us.
Ah, it may be truly said of us as of Israel formerly,
"`The _leaders_ of the people cause them to err.`"
Oh, what examples are they of shaking hands with the worldly spirit,
so that their hands are tied from the proper exercise of the discipline,
and their mouths are closed from the true and powerful
preaching of the cross and way of self-denial,
without which we cannot be Christ`'s true disciples!

My dear friend, your letter was very interesting and satisfactory to me.
I wanted to know how you felt as to +++_______+++, and it was just in unison with my feelings.
I was glad at your faithfulness, _dear_ friend.
I wish we had more such; but oh,
there is too much a-playing into one another`'s hands among ministers and elders now-a-days.
You understand me I dare say.
Oh, the covetousness of a profit that is filthy in God`'s sight, and is idolatry!
I fear there are many such among us now-a-days;
and many cannot see a hole in such testimonies (as John Steel says), but oh,
the life is more than food.

I had a sweet letter from dear +++_______+++ in the 1st month.
He seems to look forward to brighter days,
and that the little remnant of suffering ones will be preserved and supported
as they cleave close to the never-failing arm of Omnipotence,
faithful to the end.
I think since I wrote you last I went a long journey to Scotland, and Derby, and Notts,
which was a great stress upon my weak frame;
but through favour was helped on to pretty much satisfaction and relief,
and a degree of peaceful poverty on my return home.
Since then I have been much tossed about in mind,
in relation to a removal from Croydon to Reigate, in Surrey (ten miles off,
and belonging to this quarterly meeting).
Desiring to be rightly directed, having long felt so attracted,
and now being favoured to see my way clear enough,
I have the last week been over there and engaged a house,
looking forward to move about the 7th or 8th month.
It feels very exercising in prospect, being a small meeting, one of five little ones,
composing the monthly meeting of Dorking, and myself likely to be the only minister.
Yet I trust He who has been with me all my life, will not forsake in the needful hour,
but be near to direct, to support, to strengthen, and to preserve,
under and unto all He requires or permits.

_3rd Day._--In looking over the above,
I may add this testimony--surely we do serve a very good Master,
who orders all things well;
and though great buffetings and trying siftings (as you say) have been sorely my portion,
both after returning from Dublin and from Scotland, yet no doubt all for good,
that the vessel may be thoroughly emptied,
and again and again cleansed and plunged beneath the flood, and then set by,
with mouth downwards, to dry thoroughly,
that there be no scent left which may be offensive to the good User and Filler,
or whereby ought that He sees good to put therein, may be tinctured.
Oh, that it may ever be so, says my very soul, that He alone may be glorified!

Farewell, dear friend.
I have gone on in the freedom of a sister, and hope not too much so.
I feel as if sitting by you, and it is sweet.
The Lord help His poor worm to be faithful to Him wherever
I am--whether in open service or in deep suffering.
My dear love to all those among you who love the Lord Jesus in sincerity.
Sometimes I long to see your faces once more, but times and seasons are in best hands.
I remain your nearly united and affectionate friend,

[.signed-section-signature]
Lydia A. Barclay.

[.postscript]
====

P+++.+++ S.--I fear you will think I use strong expressions, do tell me so if you do;
but you know I cannot mince matters; all comes plump out.
I would rather be evil spoken of, than to be well spoken of and admired,
for then there would be a woe attached.

====

[.letter-heading]
To +++_______+++

[.signed-section-context-open]
4th Month, 1838.

[.salutation]
Dear Friend,

You have often come before the view of my mind during the last winter,
with much affectionate interest, and I think I may say sympathy also,
inasmuch as I know those that have families to bring up
often have many trials that the single know nothing of,
yet, dear friend, every trial, and every tear secretly shed,
is known to the great searcher of hearts, and He knows the sincerity of each one of us,
and weighs our conduct in an equal and just balance,
and will reward everyone according to their faithfulness to what light, and feeling,
and knowledge have been received of Him.
In the prospect of leaving this place in the course of the summer,
I thought it seemed with me,
and I should hardly feel clear without endeavouring to encourage you what I could,
to put on strength in the name of the Lord; to do what you can,
and what He gives and requires you to do for Him and His cause,
in the hearts of your tender charge, not fearing to restrain where you can,
remembering that you have a part to act for your good Lord towards them,
and He sanctions parental authority, and will not clear those who, from a false love,
give indulgence to wrong things.

I must in faithfulness own that I have been sorry to see your dear eldest girl,
on leaving school, so throw off her simple dress,
and feared it arose from too much of affectionate yielding on your part,
whereas I considered that until children are of age,
their parents have a Divine right (as I may say) to regulate them in all things;
and surely if we open the door but an inch for the worldly spirit to come in
and strengthen that vanity which is so soon apparent in the youthful heart,
we may strive what we will, we shall never be able to close it,
but it will be found wider and wider to our own sorrow,
and to the great injury of our beloved offspring;
and how are we thereby increasing their suffering in after life,
if ever they come then under the power of religion.
I do greatly feel for you in it, believing it is much to your trial,
and I know there are too many bad examples in this respect around us,
among all classes and stations, that are greatly stumbling to the sincere mind;
but oh! dear friend, let us not look out at others, nor listen to their reasonings;
if we do, we shall certainly only gather weakness of hands and dimness of sight;
but let us eye the good Master first of all and more than all,
and mind His secret whisperings in our hearts;--His Spirit
ever was and ever will be contrary to the worldly spirit,
and He seeks to redeem His people from it;
and His strengthening Spirit is near us and all-sufficient,
if we do not despise its small appearances, to enable us to do our duty towards Him,
and then we shall be clear, and peace will be our portion.

I hope you will not feel hurt at this very affectionate freedom,
but receive it as a mark of my true love and sympathy,
and desire for your strengthening and encouragement in the good work of the Lord,
even that you may raise up tender plants for Him and to His glory,
and receive the reward of your labour, even the joyful sentence of "`Well done,
good and faithful servant, you have been faithful over a few things,
I will make you ruler over many things; enter into the joy of your Lord!`"

[.signed-section-closing]
With kind love, I remain your very sincere friend,

[.signed-section-signature]
L+++.+++ A. Barclay.

[.postscript]
====

P+++.+++ S.--Since writing the above, I think it may be well to send my love to your daughter,
and tell her from me, please, I was sorry to see her dress so altered on leaving school;
tell her I hope she is not resisting her dear parents`' wishes in that respect,
for I would have her to remember that awful text of scripture,
"`the eye that mocks at his father, and despises to obey his mother,
the ravens of the valley shall pick it out,
and the young eagles shall eat it!`" but to honour
our parents is the first commandment with promise,
and though if we cannot as yet see the reason for anything commanded,
yet it is our duty to obey our parents,
and the sacrifice of our wills and inclinations in
this respect is very acceptable in the Divine sight,
and I fully believe will draw down a blessing from heaven!

====

[.letter-heading]
To E. R.

[.signed-section-context-open]
London, 1st of 6th Month, 1838.

[.salutation]
My Dear Friend,

I do not like to lose this opportunity of sending you a few lines.
I know you have deeply felt for and with us in our great loss.
To me you will believe it is, and will be increasingly, a heavy stroke,
seeing that we have from childhood been so very nearly united in those
sweet and precious bonds that are closer than outward relationship;
we have thought and felt like one person.
I have shared in his letters to and fro, and in his exercises, and in his labours,
inasmuch as he kindly made use of me, and thought my poor help and judgment worth having.
But now he is gone to his good heavenly home--__gathered to the heavenly garner__ (oh,
it was sealed on my mind as we solemnly sat in silence at his departure,
and I felt obliged to utter it to the rest of my dear brothers and sisters then present),
and how could I wish him back! released from "`this
shackled state`" (as he called it on his deathbed),
and is gone to join the just of all generations,
whose bright example he had been faithfully concerned to hold up to our view.
Oh, that this trial may accomplish that purification in me,
which is mercifully designed thereby,
that I also may be happily prepared to follow him
when my little day is finished for my God.

What a precious and sweet time it was to be with him as I was the last forty hours!
I shall never forget it.
He sunk so very rapidly that I was only just in time.
The day before he died he uttered many sweet sentences, some of which we put down;
but it was difficult to collect them, articulation being so thick.
Alluding to that text, "`This is the true light,`" etc., he said,
"`It does not say that we shall all at once know all things, but as they can bear.
O`'tis because they want to know all at once, not as children learn,
that the light is taken away.
Praise where it is due, and thanksgiving, and melody.
They say there is no revelation; but what is made known to us as our duty,
as the Lord`'s will, _is_ revelation.
This is my belief, I am _sure_ of it.
They slight revelation; but it shall prevail,
and the Spirit of the Lord shall reign over all.`"
He often exhorted to obedience to the smallest discoveries of the light of Christ;
also reminded us of the sure hiding-place and refuge--"`They
that trust in the Lord shall be as Mount Zion,
that cannot be removed, but abides forever, for the mouth of the Lord has spoken it.`"
Towards evening his voice was lifted up in a melodious sound,
like a constant song of praise, for hours, in which we heard--"`O Lord, dear Lord,
come,`" "`I bless the Lord,`" "`I am the Lord`'s forever,`"
"`Love Him with all your heart,`" "`Cleave to Him,
O cleave to Him,`" together with "`Hallelujah,`" often repeated.
He had no pain, he said, on being asked by Mary, only, an hour before he departed.
She asked again "`Was he happy?`"
"`Yes, _very._`"
It seemed like a translation--no pain of body, no pang of any parting,
though two of his children were often with him.
All was sweet peace;
and he seemed like one falling into a sweet sleep when he breathed his last.
We were favoured with a precious season at his interment,
especially the solemn covering in silence;
but there were several precious testimonies to that
Divine grace by which he was what he was.
Also, in the family, in the evening, the sweet feeling over us, I cannot forget,
it seemed as if his spirit was with us, and we could rejoice with him,
and praise the Lord for His goodness.

You will excuse my dwelling on this (to me interesting) subject,
but I know you will be interested also.

[.signed-section-closing]
I remain your nearly united friend,

[.signed-section-signature]
L+++.+++ A. Barclay.

[.letter-heading]
To John G. Sargent

[.signed-section-context-open]
6th Month, 1838.

In looking at your solitary situation--away from outward help in spiritual things,
and exposed to many temptations--I have felt much sympathy with you,
and the language that has saluted my inward ear in allusion to you is--"`Oh!
have you not felt at times _that_ visiting your soul which is unspeakably precious,
even tendering your heart and humbling your soul, and contriting your spirit before God,
giving you to see that nothing here below is so transcendently
excellent and worthy the pursuit of an immortal soul as the sweet
peace and life-giving favour of your heavenly Father,
and that there is something always lacking, when weighed in the true balance,
in all that men call pleasure here, because without this heavenly enjoyment!`"
Oh, if this be the case, let me entreat you not to quench these feelings, nor,
as it were, to shut your heart against them;
but may you go again and again where you have been thus preciously
favoured to feel this love and visitation of God to your soul,
it may be, perhaps, in a ten-minutes`' solemn quiet,
stolen from sleep or from the necessary avocations of the day.
Shrink not from yielding to such feelings,
but rather seek after them as for your daily bread: let your soul wait thus on the Lord,
as one, yes, more than one that watches for the morning,
and hope in the daily ministrations of His living
word that is nigh in the heart and in the mouth,
however pinching and proving the operation thereof may be,
or close the separation required--for, oh,
the Lord will make a clean separation in that heart
He in love is seeking to redeem unto himself,
even a separation between that which serves Him, and that which serves Him not,
however it may appear, but really serves and pleases the worldly spirit.
For that end, he has in mercy given us this heavenly talent, this word of grace,
this measure of Christ`'s blessed Spirit, that it may be a witness for Him in our hearts,
discerning our very thoughts and intents, and as we yield up in humble obedience thereto,
may purge out all that is evil, and leaven us into that which is good,
delivering us from the power of sin, the kingdom of darkness,
and translating us into the kingdom of the dear Son of God, the kingdom of light, life,
and peace, where the true fellowship is known,
and the true cleansing away of all sins by His precious blood.

So it seems with me to press you, not to look out at others,
or listen to their reasonings, but cleave simply, and solely, and wholly,
to this inward word that you at times hear, as it were, behind you, saying,
"`This is the way, walk in it`"--to this blessed Spirit of Christ that is pleading,
and knocking, and calling, at the door of your heart.
Oh! let none dissuade you from rising up quickly, as Mary did, when called,
and going after him; for He is waiting to be your life, your resurrection, your beloved,
and that He may make you of His dear ones, His redeemed ones, forever!
To this Divine word would I commend you, and direct you, my dear young friend,
as a never-failing teacher, wherever you are, and which will be a bridle to your tongue,
a stop to your evil thoughts, a guard over your demeanour,
a sure guide and rule of conduct on all occasions,
a stay to your mind under all afflictions and trials,
a mighty strengthener unto all duties, and a powerful preserver from all dangers,
as you are engaged to be faithful and obedient thereunto.

[.letter-heading]
To R. R.

[.signed-section-context-open]
Croydon, 15th of 6th Month, 1838.

[.salutation]
My Dear Friend,

I am anxious to avail of the first opportunity I have,
and yet I hardly know how to begin to you, dear R.;
how to describe to you the greatness of my loss, nor the keenness of my trial,
in the removal,
shall I say the _translation_ of my dearest and nearest
earthly tie--my beloved brother John;
and yet such is the union and unity I feel with his spirit,
that I seem held from weeping and dare not repine; no,
one seems many times to rejoice with him, and the wings of the soul, as it were,
to flap together with joy and with longing also to
flee away and be at rest in the Lord`'s good time,
if I might but be prepared as he was for his departure!
Oh, surely this is another tender dispensation designed for my preparation,
and sometimes the idea of not being very long after him is very sweet.
But all is in good hands--the judge of the whole earth,
who has done and who will do very well.
And oh, that His good will may be done in my preparation,
by an increased dedication and resignation to and humble
trust in Him during the rest of my day for Him here.

Oh! how sweet has been our fellowship,
how close our union of spirit from early childhood even!
What a favour it was that I have been so weaned from him by my illness this winter!

[.signed-section-signature]
L+++.+++ A. Barclay.

[.letter-heading]
To +++_______+++

[.signed-section-context-open]
7th Month, 1838.

[.salutation]
My Dear Friends,

I do not like to leave Croydon without at least sending you a few lines,
by way of saying affectionately farewell.
It has been difficult to meet you after meeting.
My dear friends, I trust that, though I am going further off,
yet my interest and affectionate solicitude for your
best welfare will not be at all lessened,
nor yet your remembrance of me for good.
We are poor frail creatures,
and should be glad of any the least hand of help held out to us;
even those who feel themselves but poor, little, and weak,
may often do some little thing to help their fellows in
the sincerity of their hearts and through best help.

I may acknowledge I was much struck with hearing how it was with +++_______+++`'s dear brother,
and that he was with you.
Surely, dear friends, this is another proof of what you have once, twice, yes,
thrice and more heard, that power does indeed belong unto God.
Oh, He has indeed again and again visited you most tenderly, both inwardly,
speaking in your souls in gentle but intelligible and persuasive whispers,
and also outwardly, in Providences that He has permitted.
He can take away the health of body or mind of ourselves or of those dear to us,
and He can take us away from them, for all power is in His hand:
He can bless and He can blast!

My solicitude on your account has been great,
sometimes day and night during the last several years,
from a belief and feeling that you have lost ground in the spiritual life or journey,
from a looking out at others and leaning to the reasonings of your own or of their minds,
instead of implicitly trusting in that little secret
revelation of the Lord`'s will and power,
with which I do believe you have been preciously favoured, and which,
if you had more simply and entirely yielded unto,
I believe would have directed your feet more out of the worldly spirit,
and more into the way of true peace, and of glorifying our heavenly Father before men.
But oh, how true it is,
it may be said of our dear Saviour`'s inward spiritual appearance in our hearts,
as it was of His outward coming, "`Who has believed our report,
and to whom is the arm of the Lord revealed;
for He shall grow up before Him as a tender plant, and as a root out of a dry ground:
He has no form or comeliness, and when we shall see Him,
there is no beauty that we should desire him: He is despised and rejected of men,
and we hid as it were our faces from Him.`"
The shinings of His light, and the whisperings and reproofs of His Spirit,
seem to us so small and despicable, that we reject them as beneath our attention;
and moreover, they discover to us and relate to such trying things to our nature,
that we are glad to hide as it were our faces from them.
And thus having despised and quenched them, they become fainter and fainter,
our sight becomes less clear to perceive His secret pointings,
our ears less quick to hear His gentle voice,
and the strength of our limbs is greatly lessened to run the way of His commandments.
And then we are apt to say--we feel easy with this or the other,
or we don`'t feel required to do this or that; whereas,
it is the false ease which the enemy gives the unfaithful,
and it is because we look out at what others say
or do that we can`'t see what _is_ required of us.

Now it seems to lie with me, in love to your immortal souls,
to entreat you not to look nor lean any more outward,
for that will not stand you in stead in the evil day; but to turn your minds inward,
to mind the shinings of the light of Christ in your hearts,
to allow Him to show you what is there, and what you should do to inherit eternal life,
and then be not faithless but believing; and let nothing hinder you (no fear, favour,
nor affection blind you) from following Him, your Divine and good Master,
wherever and however He may lead you,
for assuredly He leads in the way to true peace and life everlasting.

Farewell.
I hope you will receive this in the dear love in which it is written.
It is deeply humbling to me to write thus,
feeling so far behind what I should be and might have been, had I been more faithful;
but the Lord has indeed shown mercy, and I ought, in love to Him,
to seek to be clear of the blood of all.

[.signed-section-signature]
L+++.+++ A. Barclay.

[.letter-heading]
To R. R.

[.signed-section-context-open]
Reigate, 3rd of 8th Month, 1838.

We have had several pleasant walks and sits out in this beautiful country,
and especially in the park, which is almost like my own, being just across the road,
and so very sweet and retired, and varied by hill and dale, wood and water.

Well, dear R., I thought you would be pleased to hear that at present I feel comfortable,
and I have no cause to regret having taken this step; but, on the contrary,
have great cause to admire that goodness which has hitherto
helped and made a way where I could once see none at all,
and condescended to my great weakness.
And surely all this should lead to greater and greater love,
more and more pure subjection, resignation, entire dedication.
And oh, that it may be rendered by me, a poor weak, unworthy one,
at all times and in all places where my lot may be cast.

This little meeting is indeed a great change after Croydon.
I think we had only four men and five women on fourth day,
and the same on First day evening;
but they have been seasons of favour to your poor friend,
and I desire to receive it humbly as a token for good,
that I have not followed a vain shadow,
and so intended as a stimulus to closer attention to little pointings for the future.

[.signed-section-signature]
L+++.+++ A. Barclay.

[.letter-heading]
To +++_______+++

[.signed-section-context-open]
9th Month, 1838.

[.salutation]
My Dear Friend,

The feeling of sisterly love that I believe we have one for another,
encourages and stimulates me to take up the pen to you in the cross,
and thus to run the risk of consequences.
This is one way, I apprehend,
in which we should lay down our lives (all that our natures
have a life in) for our dear brethren and sisters,
in the faithfulness of true love; and I have a little faith that you will not,
my beloved friend, put a wrong construction on anything that follows.

I have felt a great, I trust a godly jealousy,
lest you were getting out into the spirit of the world,
whether it be in the furniture of rooms, or table equipage,
or the dress of your dear children, and it has grieved me,
feeling as I do a near love for you,
and a desire that you might be consistent upholders
of our ancient and precious testimony for Christ,
the blessed and unchangeable truth,
whose Spirit ever was and ever will be contrary to the worldly spirit,
and leads His faithful followers to deny self and all worldly desires.
I am sensible something may be said to extenuate
such feeling as to going into a larger house,
and more spacious rooms, requiring new furniture, etc.
But oh, my dear +++_______+++, things creep over us by very small degrees,
hardly perceptible perhaps at first,
and it may be under very plausible reasons which the enemy finds out to persuade us with,
as of things wearing better or being more economical in the end, or perhaps more useful,
if made a little more like the fashion, or not quite so strait and plain;
and that we must not be quite so particular,
else it will be as bad as putting on ornaments, etc.
And if we listen to any of his excuses, and smother,
and put by the least feeling of uneasiness relative to these things,
because they seem so small,
I believe we shall fall from one degree of clearness of vision,
and of strength for acting, to another, until, at last,
we shall become so weak as to get into the use of such things as, a few years ago,
we should have reprobated in others,
and shall so lose our clear-sightedness as not to see any harm in this or the other,
nor what is required of us as a testimony,
and so become gradually mingled with the world in its spirit.

Oh! my dear friend,
my mind has been much and often deeply exercised on this subject
for many months past (especially in attending our select meetings),
for it does appear to me lamentably true,
that "`the leaders of my people cause them to err`"
even in these that are considered minor matters.
Our ministers and elders who ought to be patterns to the flock in all things
are sadly examples on the contrary of shaking hands with the worldly spirit!
I cannot see how such can be rightly able to testify
_to_ the cross (which is the power of God),
nor yet _against_ the spirit of the world,
when their own conduct knocks down what they preach!
Oh, then, that we may be willing to be searched by the light of Christ in all things;
let us arise in His might, and shake ourselves from the cumbering dust of the earth,
that we may be able to shine forth to His praise, even in His heavenly radiance,
and that nothing may hinder our being faithful workmen and workwomen for Him.
Thus shall we truly contribute to the advancement
and spreading of His blessed kingdom of light,
life, and truth!

Trusting you will excuse anything that looks like improper freedom in this (for one
who does indeed feel herself to be but a poor weak child in the spiritual life),
and set it down to true sisterly love, I remain, etc.,

[.signed-section-signature]
L+++.+++ A. Barclay.

[.letter-heading]
To +++_______+++

[.signed-section-context-open]
9th Month, 1838.

[.salutation]
Dear +++_______+++,

I thought as I sat by you in preparative meeting yesterday,
I felt something of the flowings of Gospel love towards you, earnestly desiring that,
through an unreserved surrender of your heart to the melting, qualifying power of Christ,
the ever blessed Truth, you might be enabled, rightly and increasingly,
to come forward to the help of His good cause.
Oh, it is the pliableness and submission of our ways
and wills to the good will and way that He wants,
that He may mold us after His heavenly image in true righteousness and holiness,
and that He may bring us more and more into His most sweet
and happy way of the true peace and union with Himself;
and in order to this good and gracious end, He exercises us in a variety of ways,
turning His powerful and tendering hand upon us,
sometimes in a very pinching and proving way, to bring us down,
and to make us tender to the touches of His love,
and submissive to the discoveries of His Divine will--which is always
in opposition to our own inclinations (which are corrupt by nature),
as well as to the spirit of the world.

Now, my dear young friend,
I would affectionately encourage you wholly to yield
up to Him even in the smallest things;
be faithful in the little degree of light and strength that He gives you,
and this is the way to have more: an increase of light to discover,
and strength to follow, the leadings of Him your good shepherd;
and I do believe He will give you to see you must take up the cross more
fully in regard to little things in your dress than you have done.
He will give you to feel a little secret uneasiness with this and the other article,
which, though apparently small,
may proceed really from the root of pride and vanity in ourselves,
and please it or strengthen it by example in others.
Oh, my dear, listen not to the reasonings of your own mind, or of others for it,
but may you listen to the gentle word of Christ`'s Spirit,
and yield to this little secret uneasiness which He gives you to feel against the thing;
for this you will be accountable; therefore, to this be obedient,
and more shall be given--more acquaintance with His precious voice,
and with His heavenly peace, such as you have no idea of now; for oh,
_how_ great is the Lord`'s goodness to them that fear and acknowledge Him before men!
Fear not with man`'s fear, nor mind their reasonings.
Nothing is small to us that Christ`'s Spirit (however gently) draws us out of,
which always did and does testify against the worldly vain spirit.
If we really felt things small, we should not mind parting with them for His sake.
I acknowledge there is much formality among us--much lack of life,
even with a plain outside; but oh, let not us, from fear of this error,
be deterred from yielding up to our Saviour`'s crucifying power,
but shake hands with what is not of Him,
lest He should deny us as His dear disciples at the last day.

But though I write thus, dear +++_______+++,
I am not unmindful that you have been helped to make
some little stand in these things already;
but I want you to follow on to greater degrees of faithfulness and fruitfulness,
that you may be a way-mark to others of your family, and a blessing to them.
Oh, it is the willing and obedient that are blessed with
the fatness and good things of spiritual Canaan,
the land of true rest, life, and peace;
and it is they who hear Christ`'s words in their soul, and do them,
to whom He delights to manifest Himself more and more; yes, He says of such a one,
"`My Father will love him, and we will come and make our abode with him.`"
That this may be our blessed experience, my dear young friend, to the glory of God,
the peace and comfort of our souls,
and to the spreading of Christ`'s heavenly kingdom in all others around us,
is the earnest desire and breathing of your sincere and affectionate friend,
who often feels (and oh that I may still more and more) very poor, and weak,
and unworthy to hand even what may be compared to a cup of cold water,
to a dear fellow traveller, whereby the good thing in him may be strengthened or revived;
but oh, if it should ever be the case, may the Lord alone have the praise,
and let all flesh be abased before Him, in grateful love and pure service forever.

[.signed-section-signature]
L+++.+++ A. Barclay.

[.letter-heading]
To J. and S. D.

[.signed-section-context-open]
10th Month, 1838.

[.salutation]
My Dear Friends,

Though a very poor, weak, younger sister,
I thought I felt my mind brought into tender sympathy with you,
under the prospect of the service you are entering upon, and yielding to it,
I thought it seemed with me to do my little best towards
strengthening your hands by expressing as much;
for I know in my own experience that the feeling of even a little
child has sometimes been permitted to be helpful to me.
Oh, my dear friends, I do believe you are called and fitted for this good work,
and how earnestly does all that is living within me desire that
you may flinch not from _ought_ that is required at your hands,
nor shrink from that deep _inward_ exercise wherein
alone you will be given clearly to see it.
"`Sanctify the Lord of Hosts himself, and let Him be your fear,
and let Him be your dread,`" and then, indeed,
will He "`be for a sanctuary`" to you amidst all reasonings or disquieting thoughts,
either in yourselves or others!
Oh, it is His work you are going upon--what need to guard against doing it deceitfully,
on the one hand, and from _not_ coming up to His help against the mighty, on the other!
Oh, may you be like a people of old who "`jeoparded their lives unto the death,
even in the high places of the field!`"

May we, while endeavouring with warmth to cherish that which is good and tender in any,
ever guard against strengthening them in what we see and feel to be wrong,
and what the testimony of truth is against,
otherwise we shall not be faithful testimony-bearers for God,
not truly promoting the spread of His blessed kingdom in the hearts of our dear fellow-mortals!
Let us look not at what one may think, or another may say,
however highly we may esteem them, but oh,
let us mind the testimony of Christ`'s Spirit in the secret of our own hearts,
the unflattering and faithful witness, and whatever He discovers and bids us to do,
do it in the little strength which He _unfailingly_ gives us _with the discovery,_
and this is the way to have the weakness and poverty with
which our vessels seem to be filled to the very brim,
turned into overflowing comfort, strength, and support.

Farewell, my dear friends!
May the Lord ever fit us and keep us fit for His good and blessed work, by His emptying,
humbling, filling, and quickening power,
that so we may be strengthened and enabled to bear a faithful testimony for Him,
while our little day for Him is lengthened out to us, to the gathering of souls unto Him;
and may His blessed name be glorified, magnified, and adored over all,
and all flesh be laid low and abased before Him forever!

[.signed-section-signature]
L+++.+++ A. Barclay.

[.letter-heading]
To S. B.

[.signed-section-context-open]
Reigate, 30th of 10th Month, 1838.

[.salutation]
My Dear Friend,

Your sympathising allusion to my late bereavement was very grateful.
I may appear unto men not to mourn my great loss,
but I assure you there is hardly a day that I do not feel it deeply.
We thought and felt like one person.
I shared in his feelings, his letters, and his works,
from the time of our comparative childhood! but as you say,
there is One who has proved Himself to be a Friend that sticks closer than a brother.
Ah! it was in Him that we were united, and this union is not destroyed by death; and oh,
may I ever be preserved in Him,
who is the life and beloved of redeemed and redeeming souls!--even
by walking in obedience to the light of His Spirit,
and then I do trust that a place of rest will be prepared
for me (through adorable love and mercy) as was,
I believe, for my dear brother!
I am endeavouring to be diligent in copying his sweet papers,
whether I live to see it completed, or not; it may be for the help of after generations,
and to the glory of Him by whose grace (through faithfulness
thereto) my dear brother was what he was.
I feel it like holding up his righteous testimony,
and I fully believe there is much in his remarks to encourage
any poor wanderers who may have gone far astray;
for surely he was as a brand plucked from the burning,
and as one snatched from the brink of a horrible pit.

I noticed your quotation of a remark of his in the fly, relative to myself.
I am fully aware of my weakness in that respect,
that I do not sufficiently hide from outward ken the mourning within;
I believe it results from much openness of disposition
that what is felt within _will_ come out;
but I believe that my brother, as well as others,
thought I have more gloomy views than I really have,
and I know that he and I _were one_ in lamentation when together; although, before others,
he could conceal all and unbend in sweet cheerfulness.
This I apprehend was increasingly the case with him,
as he approached the confines of eternity,
that although the causes for lamentation were even increased in our poor society,
yet he was enabled at times to see beyond these trials,
being as it were lifted up above the earth,
and centered in a blessed unity with Him who sees the end from the beginning;
and who is and ever will be the all-sufficient supporter of His poor afflicted people!

Ah! dear S., I often fear and feel that I am thought a poor, gloomy, narrow-minded,
eccentric body; this I own is often the cause of discouragement to me,
yet I do increasingly desire to be content to be thought amiss of,
and ever to be despised; for all who desire to live faithfully,
must be content to suffer this kind of persecution--but
it is enough for the disciple that he be as his Master,
and woe is to those who are spoken well of.
I feel that a narrow path is that in which I must walk,
to testify against the nicety and luxury,
and superfluity that has so badly overrun our society--and is there any
other but a narrow path to the kingdom we ought _first of all_ to seek after?
for there are but two paths,
and we know where the broad one of selfish gratification certainly leads to!
But, alas, is there not a cause for lamentation and mourning,
when we see so many who make a high profession attempting
to reconcile a broader path therewith,
by shaking hands with the worldly spirit both in themselves and others,
under many and plausible pretexts?
Thus are they ceasing to be clear testimony-bearers for God,
and are weakening the hands of those who desire to be faithful;
and thus are they so imperceptibly mingling us with others,
that by and by there will be no difference.
But I do trust a living remnant will be preserved, though it be but a very few,
faithful to Him who has called them out of the worldly spirit, its fashions and customs,
maxims and manners, friendships and worships; and these,
though they be but as solitary beacons up and down the country,
will be as patterns of primitive times, waymarks to others, and as a dew from the Lord.
May their number be increased, and may they be strengthened in His name,
and preserved low in His fear to the end of their day for Him here below.

You allude to the appointment for visiting families; oh!
I have felt greatly exercised about it.
I fear that weakness and unfaithfulness will rather
be _strengthened_ than otherwise among us,
in different parts of the kingdom,
from appointing those who are not clean-handed themselves,
to go and visit and admonish Friends on these important subjects!
How is it possible such can do so rightly! and how very
few are really clean-handed among us! and those that are,
oh, that they may, without fear, favour, or affection, do their Lord`'s work,
not fearing to lose the favour of man, by speaking the truth.
Oh! we must love our Master more than father or mother even, or our own life,
and not covet man`'s favour or good esteem!
It is an evil covetousness, and will eat out the life.

[.signed-section-closing]
Farewell, with love, I remain your affectionate friend,

[.signed-section-signature]
L+++.+++ A. Barclay.

[.letter-heading]
To +++_______+++

[.signed-section-context-open]
12th Month, 1838.

Oh! my dear friend, I unite with that which is good in all, even the simplicity,
the sincerity, the uprightness, the faithfulness in all,
and I believe it is accepted of our heavenly Father, for it is His own begetting;
but what I lament over, and what I cannot unite with is the unfaithfulness in any,
and I believe it is this that dims the eyes and weakens the hands
of many who are seeking after and desiring after good,
both within and without our pale; and this is from yielding to the enemy`'s reasonings,
who thus is keeping them, as dear J. says, in the _twilight,_
or _from_ coming to the _pure_ dispensation of the _Gospel,_
which is the dispensation of the Son in Spirit, the power of God.
I believe the enemy is very cunning,
and would not draw them away from anything that appears to be very good, and taking,
and plausible, and even scriptural--this would be to defeat his own purpose;
but he seeks to draw them away from the inwardness, the inward exercise of mind,
where the attention is wholly given up to the smallest discoveries
and leadings of the light or Spirit of Christ,
which he knows very well will effectually dispel him and his darkness out of the heart;
and if he can thus succeed by his subtle reasonings to draw us
from or cause us to despise the least glimmerings of the light,
he knows we are not likely to have more light,
but rather gradually to lose the little we have,
and even to doubt about all that we have known and felt heretofore.
I believe it was, indeed, a dark suggestion of his, "`Are there _any_ that be saved?`"
and to increase and confirm it,
he gave you to suppose that all the true Friends thought the same, which is a lie.

You allude to Isaac Penington`'s sweet experience
of coming to partake of that which he had long wanted.
Do you _not_ notice _how_ it was he came to partake of it?
See page 28 of the [.book-title]#Introduction to the Selections.#
And you will find _this_ is the way to obtain the true
faith mentioned in page 13 of the [.book-title]#Selections,#
which you also allude to.
_Do_ read that piece, beginning at page 212, the whole of it,
with your eye looking up to Him who can alone give your heart to feel these things;
but especially mark the paragraph beginning thus (p. 215):
"`Therefore watch against your understanding and all the workings thereof,
as ever you desire life,`" etc.
The whole of this piece is peculiarly sweet, and appears to me applicable to your state.
So is also the piece entitled, [.book-title]#Some Directions to the Panting Soul;#
also page 395. Indeed, my mind was strikingly impressed with it on reading yours,
as an answer far better than anything I could say.
And, my dear +++_______+++,
do not suppose that because I send you these extracts from Isaac
Penington that I think I have already attained to his stature--oh,
no!
I wish it were so; yet I may not disallow that I humbly trust the Lord has,
in adorable mercy, given me a _little_ taste of it; and oh!
He has given me exceedingly to long after,
and a desire to travail for a further and further partaking of it--yes,
a full fruition of it;
because I believe Isaac Penington to have been a dear and faithful follower of Christ,
and is entered into the joy of his Lord.

Farewell, my beloved, I feel nothing more to say, except--Do not reason nor be hasty,
but keep low, keep inward, keep patient, and breathe to the Lord to help you.
In tender love and affection, I remain your sincere friend,

[.signed-section-signature]
L+++.+++ A. Barclay.

[.letter-heading]
To Hannah Marsh

[.signed-section-context-open]
Reigate, 1838.

[.salutation]
My Beloved Friend,

According to promise, I send you a few lines.
I did not at all like taking such a _scanty leave_ of your dear husband; do tell him so,
with my dear love.
I did not once think we should not probably meet again before he goes,
till I was in the coach;
but he knows full well that a true feeling of sisterly love and sympathy with him,
under the prospect before him, is not confined to words.
I trust he will be strengthened from day to day for the work and suffering of each day,
however poor and stripped he may now feel.
It is no doubt our good Master`'s way to prepare us for His service, to bring us,
as it were, to an extremity of need, that He may prove our faith and simple obedience,
and teach us pure dependence on His almighty arm alone for continual support and strength.
My heart will go with him among those little meetings and thereaway,
longing for the spreading of and the yielding to the Gospel, the power of God,
which is preached _in_ every creature, and is glad tidings, indeed,
to them that believe and obey it in its smallest manifestations or puttings forth.
I feel for him, especially in the public meetings;
I suppose it will be the first he has appointed,
and must be truly exercising in prospect.
Well, may he trust in the name of the Lord and stay himself upon his God.
The Lord is sufficient for His own work; and it matters not many words,
so they are but _His_ words, fetched up from the deep springs of life.
I often think the people of other persuasions can taste where words proceed from;
and they do want to be drawn from the many words without to the _Living_ Word _within._
I shall often think of him, and hope he will sometimes, when favoured with heavenly good,
remember me, a poor weakling of the flock (if, indeed, one of it at all),
almost at her wits end and ready to sink.

It has been a pleasure to me to have dear H. here; she has been very sweet.
We read a little of Fenelon together in French.
She has a good idea of translating, and a pretty good pronunciation.
I told her I should like, if she came to spend two or three weeks with me,
for us to regularly take up some studies together.
I talked to her a little about the employment of her time now that she has left school,
and what a great advantage she would find it (not only now but hereafter
in life) to lay out her time with some little plan or method,
so as to keep up what she has gained at school, and to go on improving too,
and yet not to encroach improperly on the time she has for domestic or needlework.
Where the whole day is before a young person without any regular employment--that is,
only doing such things as may happen to come to us, and these _chiefly_ handy,
not _mental_ occupations--the mind becomes vacant and too relaxed, which, I think,
is felt in after life when settled.
I hope you would not think me too advising; but I advised her,
if she could (after a little assistance in domestic matters perhaps),
to try and get an hour or so, between breakfast and dinner,
to read a little and exercise herself in French, also in arithmetic,
also some instructive, improving reading, such as natural history or biography,
and then she would still have the afternoon for needlework, and listening to or reading,
perhaps, a Friend`'s journal, conversation with dear father and mother, and meditation.
Perhaps you think I am expecting too much; but I remember my own feelings when her age,
and I had no one to advise me, but I have felt the advantage of learning a _good method._

It seems very pleasant to be here again.
Friends seemed very kindly to greet me; but I felt such a very poor creature.
I want to increase in an inward exercise of mind, in and out of meetings,
that I might witness the Lord`'s power rising above all, regulating all,
and persevering amidst all.

[.signed-section-signature]
L+++.+++ A. Barclay.

[.letter-heading]
To J. D.

[.signed-section-context-open]
1st Month, 1839.

I feel uneasy to omit acknowledging in this way that I have
felt much sympathy with you since the monthly meeting,
and the language that seemed much with me in reference to you was,
"`Be strong and of a good courage.`"
Let not your heart be dismayed in looking at the awful station to which you are called,
and the responsibility of it,
neither let it be afraid in feeling your weakness and incapacity
in your own self to act for your God as a father in the Church;
for the Lord your God He it is that does go before you and lead you,
while you are engaged to seek unto Him, and to lean only on Him.
"`He will not fail you nor forsake you,`" as you cleave close unto Him,
"`only be strong and _very courageous,_`" that you _may_ observe
to do according to all the law which "`you have received;
turn not from it, to the right hand or to the left,
that you _may prosper_ wherever you go--have not I commanded you?
Be strong and of good courage--be not afraid, neither be dismayed;
for the Lord your God is with you wherever you go.`"
Oh! how encouraging, my dear friend, to the drooping mind is this language,
addressed to Joshua formerly; and I think it is further said,
"`This book of the law shall not depart out of your mouth,
but you shall meditate therein day and night,
that you may observe to do according to all that is written therein;
for then you shall make your way prosperous, and _then_ you shall have good success.`"
Oh, it is so, my dear friend, is it not?
I know you feel it so,
that it is not the appointment or acknowledgment of men that is all that is necessary,
or that can qualify us for what the Lord calls us to in His Church;
but oh! it is that inward waiting and deep exercise of soul before the Lord day by day,
that meditating in His law written in the heart,
which I do believe you are no stranger to, but endeavours after.
It is this that will enable us to be strong in His might and wisdom, and not our own,
and to be _very courageous,_
and this surely is very necessary in these days of shrinking and fear,
in order that we _may_ observe to do all that He gives
us to see is according to His pure inward law.
Oh, then, let us thus seek after His strength, yes,
let us wait for His weakening us in ourselves,
and wait for His strengthening us in Himself,
and then we shall be strong indeed--our hands shall _not be weak,_
but we "`shall go from strength to strength,`" appearing continually before God,
who will strengthen us to work faithfully _for Him,_
not looking at this dear brother or the other dear sister,
but going simply forward in fearless faithfulness,
and thus our hearts will be still praising Him, ever overflowing with His love,
and praise, and honour, and our work shall be rewarded,
our "`labour shall not be in vain in the Lord.`"

Thus much I thought I would write you in tender sympathy,
though sensible of my own very childish state,
remembering my own feelings on being recommended to the select meeting,
and desiring also to be your companion in this inward exercise--for
nothing else will do for us in this day,
I do believe, wherein many must be, if they are in any way living,
the sore trials and baptisms of those who attend these meetings;
for surely is it not from _there_ that the evil spreads all over our camp,
when priests and prophets are out of the Life?--for it may be said now as formerly,
"`Like priest like people,`" and "`The leaders of my people cause them to err.`"
But the Lord is sufficient for His little ones, though they be but as ones and twos,
scattered here and there, a feeble few, but desiring to be faithful to Him alone.
He is their only hope, and help, and staff, and strength;
He will not fail nor forsake them, as they keep their integrity to Him,
and serve Him with a perfect heart, but will show Himself strong on their behalf,
and preserve them unto the end, to praise and bless His name forever and ever!
So be it, says my poor soul.

[.signed-section-signature]
L+++.+++ A. Barclay.

[.letter-heading]
To S. B.

[.signed-section-context-open]
12th of 2nd Month, 1839.

[.salutation]
My Endeared Friend,

_What_ a mercy your life was spared from that accident!
Surely what can you _not_ render to Him who has dealt so tenderly with you;
and He is able to make your way before you, to lay low mountains of difficulty,
to scatter the mists of doubt, to calm the waves of conflict, yes,
He can enable you to run through a troop of dismaying fears,
and to leap over a wall of opposition;
and as you more and more yield up yourself to be
led and guided as His devoted and blind servant,
He will make darkness light before you.
These things will He do and much more, and not forsake you in the needful time.
Oh, that we may be companions together, dear S.,
in serving Him with a perfect heart and willing mind,
yet more and more than we ever have done; for He reigns over all,
and can bless us in all and through all!
I received your acceptable letter on my return home
from attending the +++_______+++ quarterly meeting,
where I took a minute for holding a meeting at +++_______+++; and,
through adorable goodness and mercy,
I was enabled to discharge this little debt of _long standing,_ to my relief,
as well as to cast off a little burden in the Women`'s quarterly meeting,
though a great trial to nature.

I was much pleased to hear of your little turn out,
and have no doubt it was for good every way.
Your account of the little company at +++_______+++ interested me much;
but I have no prospect of going that way,
and feel much straitened _now_ from travelling for mere change.
If I am but favoured with strength of body, as well as ability of mind,
to do what little may fall to my lot in the way of testimony for my good Master,
this is all I long for, and to be enabled to lay down the body in peace at last.
I had from +++_______+++ an interesting account of +++_______+++ quarterly meeting.
What a nice conclusion they came to about the visiting families;
for surely this is what we all need more of--an individual, deep,
inward exercise of soul, that we may see our duty, and be enabled to do it;
and unless these visits are performed by those of _clean hands,_
I fear weakness will be greatly _confirmed_ upon us, instead of helped _out_ of.
And I fear this has already been the case.
For where are the clean-handed ones to be found among us?
Alas! alas! both ministers and elders are examples
of shaking hands with the worldly spirit!
Some may be plain in their own dress, but look at their children, their houses,
their tables, their equipages, and way of living;
there is more of _self-gratification_ than _self-denial_ in all these things.
Oh, it knocks down all they preach, or else hampers them and ties their hands.
Well, dear +++_______+++, we must not look out at others, let them do as they may;
let us cleave close to the dear Master,
and look at the pattern which He has shown us is consistent with His Spirit,
which ever was and ever will be _opposed_ to the worldly spirit.
Oh, we need an increased attention to little things among us;
it was in this way our dear ancients grew and throve, by minding the day of small things,
giving up to little feelings of doubt, or hesitation, or reproof, or inclination,
in regard to everything; instead of which we smother and quench all,
and then say--we don`'t see, or we feel easy with this or the other.
If we shut our eyes we can`'t see.
Oh, how do I long after more of this inward attention to little pointings,
this pliableness and subjectedness of spirit!
Let us crave it for one another, dear S., for this is the way to growth and fruitfulness.

My health, through Divine favour, has been better this winter than I at all expected,
though I do not feel very strong.
I feel this situation a comfortable home; and though sometimes rather solitary,
yet I often think it is well to sit alone and keep silence in this cloudy and dark day.
My great fear is, lest I should sit down too much at _rest_ in this corner,
and not work while it is day,
in that little humble way that I ought in this part of the heritage.
The Lord is all-sufficient for His poor tried remnant,
and no doubt will do them good in and through all, and preserve them amidst all,
as they cleave closely to Him in fear, faithfulness, and humility;
and He can make a way for their deliverance where they can see none, in His own due time,
which is the best, as patiently waited for.

[.signed-section-closing]
Farewell, very dearly,

[.signed-section-signature]
L+++.+++ A. Barclay.

[.letter-heading]
To M. A. and C. B.

[.signed-section-context-open]
Keswick, 10th of 4th Month, 1839.

[.salutation]
My Beloved Friends and Sisters,

As I lay awake one morning last week pondering your--and
your dear partner`'s--allotment in this part of the heritage,
both of suffering and of service,
my mind seemed introduced into great and precious nearness with you,
and clothed with tender sympathy for you, and I seemed to be one with you,
though in my smaller measure of service and of suffering;
and then it seemed very encouragingly brought to my remembrance,
how it was with poor Nehemiah formerly, who was solitarily situated and in captivity,
yet whose heart the Lord stirred up,
after he had mourned and wept and fasted certain days,
to seek after the restoring of the walls of Jerusalem,
and the good hand of his God was upon him and opened his way before him.
How did he yield to this good hand which was upon him! and oh,
it was both good and mighty upon him!
How did it work for him and support him above all fears and dangers!
and he went and viewed the walls which were broken down,
and the gates which were consumed with fire, even in the night season and alone,
and with great difficulty did the beast that was under him pass along,
and he had not as yet told anything either to the Jews, or to the priests,
or to the nobles--not even to the rest _that did the work._
And after that mournful view then it was laid upon him to say to them,
"`You see the distress we are in,
how Jerusalem lies waste and the gates thereof are burned with fire.
Come, and let us build up the walls of Jerusalem, that we be no more a reproach.`"
And no doubt they felt the good hand that was upon him, and they said,
"`Let us rise up and build.`"
So they strengthened their hands for this good work; and when they were laughed to scorn,
and despised, and accused of rebellion, he answered and said to them,
"`The God of Heaven _He_ will prosper us, therefore we His servants will arise and build;
but you have no portion, nor right,
nor memorial in Jerusalem,`" testifying _to whom_ was his allegiance supremely,
and that he acted from the Divine putting forth or word of command,
which word should prosper in the thing whereto it was sent;
but they were strangers to it,
and therefore could neither properly judge nor safely oppose.

How encouraging is all this to the humble waiters, the patient, mournful sufferers,
yet faithful workers in the Lord`'s power, though but a feeble few!
And it is striking to see how that the daughters also joined with their
brethren in repairing the walls--encouraging to us poor weaker vessels,
and the first in transgression!
How wonderfully were they helped to build the walls even in troublous times,
and in the midst of much indignation and mockery from their enemies,
who said that their wall might be broken down even by a fox,
and wondered how these feeble ones could think to fortify themselves,
and revive the stones out of the heaps of burnt rubbish!
And when they heard that the breaches began to be stopped they were very wroth,
and conspired to come and hinder the work; nevertheless,
the prayer of these feeble ones was unto their God,
and He enabled them to set a watch against the enemy,
and to be both valiant with their warlike weapons in the one hand,
and diligent and strong to build with the other hand, both early and late;
and the language of encouragement in and through Nehemiah to his fellows was,
"`Be not afraid of them; _remember the Lord,_ which is great and terrible.`"
And when the enemy found he could not succeed in hindering the work openly,
he tried seducing means, endeavouring to ingratiate himself with Nehemiah,
with surmising a revolt; but he refused to join hands with the enemy,
or to flee to save his life from their designs, but his answer was,
"`I am doing a great work, why should it cease while I leave it and come down to you?`"
and "`there are no such things done as you say,
but you feign them out of your own heart`"--and he was enabled
to withstand and detect the false prophecies of the prophets and
prophetesses that were hired by the enemy to make him afraid,
and thus to sin, that they might have matter for an evil report and to reproach him.

I thought there was encouragement for some of us who feel
ourselves to be few and solitary and very feeble,
in remembering this instructive portion of scripture,
that we may be animated to fearless faithfulness, endeavouring to work for our good Lord,
as He puts it into our hearts, and gives us ability;
and we know not how we may be instrumental by our example,
in stirring up others to a noble zeal for the truth--for
_one_ may in the Lord`'s might become as a thousand,
and a very feeble one as a strong nation.
He is able to sustain His poor and afflicted people
amidst all their sore exercises and deep baptisms.
He _knows how_ it is with them, beholds their secret tears, and hears their secret sighs,
yes, their groaning is not hid from him; "`He will keep them as the apple of the eye.`"

In all their afflictions he is afflicted, and the angel of His presence is with them,
does support them, and in due time will save them.
He will bring them with songs of deliverance unto Zion--yes,
"`the Lord shall reign over them in Zion,
and they shall worship Him in the holy mount in Jerusalem.`"
What shall then be answered the messengers of the nations?
That "`the Lord has founded Zion, and the poor among His people shall trust in it.`"

My heart will go with you two dear sisters where you are going;
may the Lord prosper His work in your hands, preserve you deep in spirit,
cleaving close to and leaning wholly on Him, who will be sufficient for you I know,
and give you to praise His name.
I feel it a great comfort to have been helped on thus far;
but I expect I must give up anything more at this time,
my chest being greatly affected now; my voice is quite gone,
and I think I must hasten home,
so I hope the resignation of the will is accepted
instead of any farther outward labour hereaway.

Farewell, my dear friends.
Your kindness to poor me, I trust, will be amply rewarded by a "`better hand.`"
If favoured to meet again it will be sweet; if not,
may the will of the Lord be done and permitted in us, which is our sanctification.
With dear love, I remain your nearly united and affectionate friend,

[.signed-section-signature]
L+++.+++ A. Barclay.
