== Chapter VII

To +++________+++

Norwich, 11th of 4th Month, 1839.

My Dear C.,

The letter you kindly forwarded and crossed affected me much.
It contained an account of dear E. R.`'s removal from this
state of trial and probation to a heavenly home;
but, though affecting to nature, my spirit seemed to rejoice with her`'s,
believing she is gone to her Master`'s rest and joy.
And how do I crave to be so permitted, if so be I may be prepared, when He sees fitting!
Your account of yourself and some home matters was comforting;
but somehow I do not think at all about you,
having left all and committed all with my own soul to the
care of Him whom I desire to serve with my whole soul,
and with my whole heart; and verily I can testify He is a good Master,
and a rich rewarder, even of the very poorest and meanest looking services.

I will now proceed in my narrative of my poor little travels.
I went to Yarmouth as proposed,
and attended their very small and poor meeting next morning,
to which also came A. and K. S. from P+++_______+++, who, after dinner,
and an opportunity which followed, took me back with them in a post-chaise,
which I was glad of, as it was a bitter cold east wind from the sea.
The smell of the sea was truly refreshing to me,
and I sucked it in all night long at dear old S.
B.`'s (the blind minister I have told you about),
where I lodged and felt so happy, that I did not know how to leave again.
After tea there, we went to meeting next door to her house,
and it was a sweet meeting to me in the silent part,
which was (as usual with me) very long.
There were two young women, not Friends, who, I suppose, seeing a light,
thought it was a public meeting: they behaved very lightly;
and after I had said a few words and sat down, out they went,
and then I was able to express more in a different way.
And then dear S. B. spoke at some length, and took up what I had said encouragingly;
there were several others, not members, besides the (only) five members.
S+++.+++ and M. B. and I sat up till half-past ten in interesting and instructive conversation,
and the feeling of sweet unity was very precious.
Next morning I was obliged to leave her at nine o`'clock and go back to Norwich.
When I got there, there was no room in the evening coach, so had to lodge at J. P.`'s,
and he kindly sent me next morning in his headed chaise to T. B.`'s, Wymondham.
I felt comforted to be with them; they are a sweet family, and so well brought up.
I attended W+++_______+++ meeting yesterday week,
going about four miles to it in an open gig and back;
a bitter cold wind and a little snow falling; a sweet meeting it was.
After dinner, I went in the same way about eight miles to meet the Lynn coach,
much enjoying T. B.`'s company, which was very strengthening to me.
I reached Lynn at nine o`'clock.

The monthly meeting was a time of much favour.
Dear C. B. laid before Friends the attending Dublin yearly meeting,
also joining her sister in Wales.
We had J. D., a nice elder of Tivetshall with us, who was a great help to us all.
The minute was drawn up and signed; and it was, I thought, a sweet time.
In the second meeting, I had much to do to my trial, and found it very hard work,
by reason of what was painfully uppermost there; however,
I was helped to be faithful and close; to my confirmation,
found out afterwards that things were as I felt,
and the head of the nail was knocked at through His goodness who helped me.
It was a day of much relief to me, which was cause for humble gratitude.
I had also a private time with a young man, an utter stranger, who called in after dinner.
On sixth day, I went with dear C. B. in a fly about twelve miles off,
to sit with some old Friends.
On seventh day, dined and called on the few Friends at Lynn.
On First day, was at their meetings,
in both of which there were six or eight strangers more than usual.
There are some sweet Friends there.
On second day this week, I started at seven a.m., accompanied by C. B., to Wells,
and had a most cold ride, skirting round the sea coast,
with north-east winds blowing from it.
We got a second breakfast between eleven and twelve on reaching Wells,
and then sat with the family there.
+++_______+++ was there and spoke; he seems a precious young man.
We then had a sitting with another part of the family, one of whom is confined to her bed.
I was silent therein, but dear C. ministered sweetly to them,
and I hope it was a comforting time to her.
After a hasty dinner, I was taken on in a post-chaise to Holt,
to that interesting female`'s, who has joined Friends by convincement,
her father being a clergyman.
In the evening we had our little meeting in her family,
her husband joining her (as they always do every First day);
and such a precious time it was, as I cannot describe.
I was greatly afraid of breaking the sweet silence, yet dare do no other.
Next day went to North Walsham meeting (memorable in old times to me),
had a relieving time there; also a little time with my kind host and guide, and his wife,
and then he drove me in an open chaise here to tea, to my comfort and peace.

Inflammation (from a cold caught on second day) came on
so rapidly that I had no voice whatever all yesterday,
and got very low, and thought I must give up the monthly meeting at Norwich today,
and two others on First day; but this morning I was favoured to feel less oppression,
and thought I must, at least, try and sit the meeting.
So I did,
and lo! my good and wonder-working Master was pleased
not only to put a little word into my heart to utter,
but He made me to give forth a clear sound to my humble astonishment;
and in the second meeting, also, a few words, testifying to His goodness,
for the encouragement of dear M. A. B., whose certificate was there read and signed.
I am intending, if so permitted, to be at one of the meetings on First day at Tivetshall,
and I hope my brother, Abram, will go with me in a fly; the other, at Warling,
I think I cannot accomplish in my weakly state, and feel easy about it.
I hope to get home on second day.

Farewell, very affectionately.
Remember I am in good hands, who has indeed dealt very tenderly with me.
Your affectionate friend,

L+++.+++ A. Barclay.

To J. Richards

Near Norwich, 13th of 4th Month, 1839.

My Dear Friend,

Your affecting letter was forwarded to me in this county last week,
or I should have written earlier.
It was truly a great shock to my affectionate feelings.
I had been intending from week to week to write (to your dear sister),
so that proved that I had had mental fellowship with her;
and although in the midst of company when your kind letter came to hand,
yet I seemed for a short space bowed down in inward silence--yes,
and lifted up into union with her in the Beloved, and, as it were,
into a joining with her spirit in the angelic chorus of "`Blessing and honour,
and glory and power, unto Him that sits upon the throne,
and unto the Lamb forever and ever!`"
And when thus favoured how do the wings of the soul, as it were, flap for joy,
and for longing to flee away also, to be forever at rest in Him, who is our life,
and peace, and hope of glory,
yet mingled with humble resignation to wait all the days of our appointed time
of proving and of suffering--for He is faithful who has called and promised,
who also will strengthen us and will perfect that good work He has begun,
and who is of power to establish us, "`and preserve us unto His heavenly kingdom.`"
Oh, that it may be so with us, my endeared friend, says all that is alive within me!
Oh, our dear sister is gone to join the just of all generations!
She is not far behind my dear brother John,
whose loss is revived on hearing of the removal of others,
his dear fellow-labourers and fellow-sufferers.
Surely we cannot wish their return,
but rather adore the hand that has dealt so bountifully with them,
and so tenderly with us; and as we bow under,
and yield to His good hand that seems so mightily, yes provingly laid upon us,
I do trust He will be near to support and bear up, to strengthen and to comfort us,
who are still travelling on in this vale of tears,
even as He was with them all their lives long; He will be our guide also,
even unto death, and give us to glorify His great and ever-excellent name.

It must have been very trying to you her almost sudden removal;
yet no doubt all was for the best.
You were thus both spared much feeling,
and I think you could hardly want more evidence than I know you had,
so you would rest in a blessed hope, which would be like an anchor,
when natural feelings would rise up.
And, my dear friend,
it is marvellous how you have hitherto been supported to attend to your beloved sister,
considering your own delicate health;
and how tender does that hand feel that has taken her away the first!
I have no doubt that as you have been helped so you will be still,
as your eye is kept singly looking to the source of all true counsel and direction,
and your soul wholly leaning on that arm of strength which is almighty;
so will you be enabled to fill up her place in your little circle,
according to your measure, and increasingly to follow her precious example,
as she endeavoured to follow Christ,
witnessing His light to rule and shine forth in all your
conduct and conversation to the glory of our heavenly Father.

I have been in this county nearly three weeks visiting the meetings of it, and have been,
through condescending goodness,
helped to accomplish nearly all that has come before me as a duty,
though my poor service (if it be any) is in a very little and mean
looking way in comparison of others who are very eloquent or fluent;
but if one may but bear a clear testimony in ever so humbling a way, and not stumble any,
or do harm to the precious cause, it is all I desire,
and will be a great favour if so allowed and strengthened.
I have only one meeting to go to tomorrow,
and then hope to flee away home on second day in great weakness,
having this last week an attack on the windpipe, which lowers me much,
and it has been a great exercise of faith to stand up,
not knowing that I could bring forth any sound, having lost my voice some days,
but my good Master helped me,
and I do desire to love and serve Him yet better and better,
and to praise His name forever and ever.

I think I did write once since being at Reigate.
I have continued to find it a comfortable and peaceful home and quiet retreat,
and the danger is of loving it too much.
My health has much improved, this last winter being milder, and my house very sheltered,
and the climate softer: this is truly a great favour,
and calls for grateful returns of unreserved dedication.

Farewell, my dear friend, with dear love, also, to J. B.,
who must feel the great loss deeply; a mother in Israel gone truly.
I remain your tenderly sympathising and affectionate friend,

L+++.+++ A. Barclay.

To J. B.`'s Sons and Daughters.

5th Month, 1839.

My Dear Young Friends,

My thoughts have often seemed to travel along with your dear mother,
especially in the last day or two that I have fancied her at D.,
and I think I may say as often as this has been the case,
so often have they also seemed to travel to her home,
glowing towards you with what I trust is a degree of Gospel love, desiring that you,
who I have no doubt feel it sometimes very trying to have parted with her,
yet may be daily seeking after ability to do those things that you know would please her,
daily seeking to be followers of Him as dear children,
who has thus sent her forth in His service;
this will be your way of helping forward His great and good work she is gone about,
and then,
when He brings her back again to you with the golden sheaves of His heavenly peace,
will you also be permitted to share with her in your several degrees,
and a song of praise will arise and fill the whole house, as the heart of one man,
to Him who does bless the going forth and the coming
in of His little dependent faithful ones.

And, oh! my dear young friends,
may you come and yield up your hearts to serve the same good Lord,
who is rich to all that call upon Him!
I believe you are in degree endeavouring to do so,
having felt His precious visitations to your souls; but oh,
let nothing as you grow older hinder your following on to know still more
and more of His precious ways and excellent dealings with you,
even by implicit obedience to one little glimmering of His heavenly light after another,
unfolding to you one little thing after another that is contrary to His purity,
and is of the darkness,
and showing you the clear path of self-denial in peace and safety;
and as you are thus willing as dear obedient children to follow the Lord,
sacrificing your own wills in one little thing after another,
so you will come to know more and more of His precious goodness and His mighty power.
His goings forth in your souls will be prepared as the morning,
with increasing light and strength,
and the returning incomes of His love to your souls
will be as the former and latter rain in their season,
bringing freshness and fruitfulness with them.
Oh, then, my dear young friends,
how does the language again revive towards you as when with you, "`Hearken, oh daughter,
and incline your ear; forget also your own people and your father`'s house,
so shall the king greatly desire your beauty; for He is your Lord, worship Him!`"
This may be applied to sons and daughters, for the Church is called the Lamb`'s bride.
Oh! hearken diligently to the voice of your dear Saviour speaking inwardly in your souls;
incline your ear to His sweet yet piercing words there,
forsake all that He requires you to part with--yes, even forget it,
though it be dear to you as your very home; for He should be your only Lord,
and your whole heart and worship should be given to Him.
Start not away from His holy yoke; rather draw it close about your necks.
Love His chains, the restraints of His blessed Spirit; be not ashamed of them,
let them shine conspicuously as your brightest ornaments in all that you do or say.
Let His law be your delight, His testimonies your heritage,
the judgments of His Spirit more desirable than much fine gold--yes,
sweeter than honey to your mouth.
Thus shall His wisdom and His grace be as a crown of glory,
and as an ornament of gold upon your heads;
and He will accept the beauty that He puts upon you, and the meek, quiet,
and subjected spirit that is of and from Himself, and is of great price in His sight,
and you shall be His forever and ever.
Oh! then,
hearken unto Him and incline your ear more and more--hear and your souls shall live,
and He will make an everlasting covenant with you that shall not be broken,
even the sure mercies of David, and He will betroth you unto Himself forever.

Farewell, my dear young friends, in that love which many miles of distance cannot quench.
Show this to L. B. and her brother, with my dear love,
for my affectionate solicitude extends to them as well as to you,
that nothing may nip the opening bud,
but rather desiring that it may be more and more
expanded to the genial rays of the Sun of Righteousness,
that more abundant ability may be thereby received to blossom in the beauty thereof,
and to bring forth fruit to the praise of the great and good Husbandman,
who does indeed bestow much tender labour both inwardly and outwardly.

L+++.+++ A. Barclay.

To J. R.

London, 30th of 5th Month, 1839.

My Dear Friend,

I have very often thought of you and of your great loss since I last wrote you,
as also of her who is gone home,
and it has been very sweet to remember her and the last
sweet reading we had together in her chamber at Marazion.
Oh!
I shall not forget the many sweet times we were favoured
with together there in my last visit to you,
and the near unity I enjoyed with her.
How comforting it is to reflect that this precious
unity and fellowship is not dissolved by death!
Oh, let us travel on after a growth and increase in it,
since we have been favoured to taste a little of it,
and of the exceeding graciousness of the Lord.
Oh, come, and let us more and more "`walk in the light of the Lord.`"
I am very often reminded of her (and you also), and speak of her sweet example,
as wherever I go I take with me that nice neat work-bag she made for me.

I trust, my dear friend,
that "`as your days so will be the strength`" mercifully handed you,
even at the very moment you most need it.
It will be a pleasure to try and make up her loss towards your dear nieces,
and your hand will gradually get into the good work, though now it seems formidable,
and it will divert you from dwelling unprofitably on your bereavement and solitude;
lead you to look continually upwards, and the more we do so the better,
though it be even by pinching times of trial;
for man`'s extremity is God`'s rich and blessed opportunity for
the display of His wonderful goodness and His mighty power,
and how exact and precious is His help then!
Thus we grow, and our experience is enlarged even in these troublous times--our love,
and our humble gratitude,
and our confiding trust are increased--and the continual
language of our heart and conduct will necessarily be,
"`Let the Lord be magnified.`"

Since I last wrote, I have been very ill; but, through mercy, was raised up again,
and helped along to visit the families in my own monthly meeting,
directly I got home from Norfolk, to my unspeakable relief and comfort,
having had it at heart the last nine months.
Praised be the Lord forever,
who makes a way for His poor creatures where they can see none,
and enables them to set up their Ebenezer to His praise!

This yearly meeting has been a favoured time,
though not without much trial and deep suffering.
Most insidious the enemy`'s baits are to deceive even the elect;
but there is a little Babe of immortal birth to which all is clear and open.
The select meetings were very comforting I thought.

Farewell, dear J. Let us look upward, and hope even to the end,
holding fast the beginning of our confidence,
and then surely we shall not be forsaken or forgotten of our Lord.
I remain your truly affectionate friend,

L+++.+++ A. Barclay.

To R. Barclay

My Dear Nephew,

I am rejoiced to hear that you have been strengthened more
fully to show what I believe your heart has long felt,
that your whole desire and highest aim is to be a faithful servant of the Lord,
a devoted follower of Him who was crucified for us,
and whose power will ever crucify us to the world and the things or spirit of it.
I say strengthened, for oh! how unable are we to do the least good thing of ourselves;
how does our weakness, and the reasonings which the enemy suggests,
continually rise up to oppose this good work, this tender desire to be the Lord`'s only,
the Lord`'s wholly; but gracious is He and merciful, pitying our weakness,
and holding out His hand of help at the needful moment,
assuring us that it is He that we feel touching and drawing, and making us willing;
therefore we need not be afraid, only believe in His power and He will hold us,
as by the right hand; follow Him in simplicity,
and He will give us according to the desire which
His goodness and love have raised in our heart,
enabling us to make covenant with Him, even by sacrifice;
for these are His precious ones,
whom He is redeeming more and more to Himself that He may bless them.
And I believe He has graciously accepted your burnt sacrifice,
and the peace-giving smile of His countenance (even if it be only
at moments lifted up on you) will put a most precious joy,
yes, a song of praise, into your heart, and animate you more and more to lean on Him,
and cleave to Him with full purpose of heart.
Oh, then, cleave to His power, which alone began any good work in you,
and which alone can carry it on and preserve it.
"`Wait on the Lord and keep His way,`" wait daily for His humbling, His melting,
His strengthening, and His anointing afresh;
and keep to what you know and feel to be of Him,
all His commands and restraints and tender leadings, "`so shall you dwell in the land,
and verily you shall be fed.`"
Thus keeping His way and walking in His light,
you shall be fed with food convenient from day to day,
you shall be enabled to overcome all things;
be given to partake of that blessed fellowship and union
wherein Christ is known to rule over all in our hearts,
and we to reign with Him, and to possess all things in God, of whom, and through whom,
and to whom are all things, to whom be glory forever.
"`He that overcomes shall inherit all things, and I will be his God,
and he shall be my son.`"

L+++.+++ A. Barclay.

To +++_______+++.

7th Month, 1839.

My Dear Sister,

In looking at your open kind letter again,
I would encourage you to be faithful to little pointings at all times,
even a few foolish looking words,
for this is the way to gather strength--when you feel the Lord`'s putting forth,
and the woe to attend the withholding; for the more obedient we are,
the better we shall be able to understand His tender voice,
and the more we shall hear it, whereas "`hesitation darkens inspiration.`"
I feel such a very poor weakling of the flock (if of it),
that I fear my experience will hardly be any help to you--but I may own that
so great also is my fear of uttering a word more than what is clearly given,
or of mixing up or patching to anything of my own contriving,
that I believe I have but in very few instances ever expressed
more than what seemed clearly pointed out before standing up;
but, on the contrary, I believe I have often, from fear,
and not keeping sufficiently close or inward to the gift,
failed in obtaining entire relief of that which was the burden committed for expression.
I have believed in reference to myself,
that as greater inwardness is attained and strength permitted,
greater enlargement may be witnessed,
even while speaking--but I desire to be content with the very little that is given,
and so to keep to the power (through holy help) as that I may be preserved from
both the loss (to others and to myself) of withholding more than is fitting,
as well as the snare, the great snare, of mixing in anything of the creature`'s,
or spreading out into many words; and alas! how greatly has this snare spread among us,
and the evils necessarily accompanying,
so that I am often of the belief that many now-a-days will be raised up as living,
powerful ministers, who shall be few in words, but deep in power,
and very often engaged in silent preaching!

L+++.+++ A. Barclay.

To L. C.

Reigate, 25th of 9th Month, 1839.

My Dear Friend,

I hope your dear mother has not suffered from the change of residence,
or from the longer walk to meetings, and up hill too!
I am hoping before very long (but this hope is mingled with fear and awe!) to see her,
as perhaps you have heard that I feel constrained to sit in your families,
and was a week before liberated for this awful service.
I hope to get a little crumb of bread and drop of
refreshment in being with your dear and valued mother.
I look to visit the families in Guildford and Godalming next week.
You can not think how very helpful and strengthening was
the company of W. and M. Binns at our monthly meeting.
Oh! it was an exercising day, but, through mercy, I was helped through.

My health is favoured to be middling,
as well as I can expect this very cold and wet season, and considering exercise of mind.
I shall be pleased to hear of your Western journey in your answer,
which I hope to receive very soon; and so hoping you will excuse so hasty a scrawl,
I remain, with kind love to T. and your dear mother and J.,
your sincerely affectionate friend,

L+++.+++ A. Barclay.

To +++_______+++.

Reigate, 10th Month, 1839.

My Dear Young Friend,

Since returning home,
I have felt my mind drawn to send you a few lines
in the sincerity and love of a faithful friend.
Having much love for your dear mother,
I can hardly withhold from her son what may be for his welfare.
I felt much concerned for you in considering that you would probably
be much thrown with the young man at +++_______+++`'s. I thought that,
as his parents had left Friends principles, he would be likely to be similarly inclined,
and I feared lest you should be at all warped aside from
what you have been brought up in the belief in,
and which, I believe,
you have felt for yourself in seasons of humbling and tendering favour,
even the inward revelation of the Spirit of Christ,
in and by which He is now to be heard, known, believed in, and obeyed; for the outward,
and shadowy, and preparatory dispensations of Moses, the prophets,
and John the forerunner and baptiser with water, were to pass away,
and Christ the beloved Son was to remain, with this injunction, "`Hear Him.`"

And how is He to be heard, now that He is no more personally with us,
having finished the work given Him to do,
and laid down His precious life a ransom and an acceptable sacrifice unto God for us?
by His blessed Spirit, by which He is ever with us, even to the end of the world,
as He said, "`Lo, I am with you alway,
even unto the end of the world,`" and "`He dwells with you
and shall be in you;`" "`I will not leave you comfortless:
I will come to you,`" that is, in Spirit, by which He knocks at the door of our hearts,
calling to us to open to Him that He may come in and bless us; and when He calls to us,
His voice, though gentle, pierces deep, and His word is with power to enable us to obey,
yes, even to run after Him with sweetness and ease,
parting with and leaving all behind that would draw
us away from Him or a close attention to Him,
the beloved of redeeming souls!
Oh! He is your best friend.
You can never love Him too much, or lean upon Him too much, or seek His company too much.
He will not flatter you in anything that is evil, but will speak the truth to you;
and the more you are obedient to His voice and loves His company and counsel, yes,
and reproofs too, the better you shall understand His speech,
and the more precious will He be to your soul.
Oh!
He will not disappoint your expectations of Him, but will give you wonderful counsel,
excellent lessons, strength to do all He requires,
and grace to help in every time of need.
Therefore, love, and don`'t shrink from the shinings of His light,
the reproofs of His Spirit, for, verily,
that which convinces of and reproves for the evil, if obeyed, will become our Comforter;
but, if despised and neglected, our condemnation and judge, as He declared,
"`He that rejects me, and receives not my words, has one that judges him:
the word that I have spoken, the same shall judge him in the last day.`"^
footnote:[John 12:48]

I would advise you, my dear young friend,
to avoid much association with any whose society you find to lessen your
attention and cleaving to the gentle monitions of the Spirit of Christ;
for they will not in the end prove good friends to you, however agreeable they may seem.
What will the favour and friendship of any be if you lose the peace and favour of God?
Rather may you seek for recreation in instructive reading,
or a meditative walk in the fields, where all around you, if your mind is rightly fixed,
will fill you with innocent enjoyment and sweet praise;
for there is no pleasure or cheerfulness to be compared with that
which proceeds from a peaceful sense of God`'s favour.
There is nothing gloomy in religion; it brings true sweetness and content with it,
supporting under all trials and crowning all other blessings!

L+++.+++ A. Barclay.

To +++_______+++.

10th Month, 1839.

My Dear Friend,

Ah! there is a part in us that greatly needs to be
brought down into the stillness of confiding resignation,
into the silence of patient subjection,
to that power which alone began every true work in the heart,
and which alone also can carry it on and preserve it.
Oh! how anxious is this nature in us to know what others think!
What a continual reverting to self on all occasions and in many little ways,
but with apparently very good reasons--for it is thus the enemy conceals his
snares to draw us out of the sweet and faithful simplicity of the little child,
the child that is quieted and weaned of his mother!
But the path of life and safety is for the child of God`'s begetting,
as Isaac Penington says, "`the true knowledge of the way with the walking,`" etc.^
footnote:[See Selections, page 111, down to "`the everlasting inheritance in that.`"]
If we examine ourselves by the light of Christ,
we shall find that self is at the bottom of much in us that looks plausible,
in many instances at the bottom of our discouragements, our fears, our desires,
and our actions.
A few steps fetched in the life and power of God,
in the faith and patience that is of Him,
are much safer and sweeter than a hasty progress in the anxious forward spirit.
Oh! then let us keep back to the life, keep close to the power which crucifies self,
which will bring down that which is high and exalt that which is lowly and childlike,
which will dry up that which is green and spreading,
and cause that which appears to be dry and almost dead to flourish abundantly,
giving us to rejoice in the wonderful works and the
tender dealings of the Lord to us and in us,
whose judgments are unsearchable and His ways past finding out--for of Him,
and through Him, and to Him are all things,
to whom be glory rendered forever and ever by the whole house of the spiritual Israel!

And now farewell, my dear friend.
I hope you will receive this in the dear love in which it is written, and, I may add,
in tender sympathy also, especially with that which is good and tender and living in you,
the strength and deepening and preservation whereof I greatly desire.
And oh!
I trust I do not write as one that has already attained, but as one that has,
both in myself and in others of my dear friends,
seen and felt the enemy`'s snares and attempts to crush the life,
and therefore I hope not amiss in testifying thereof,
and of that power which as laid hold of enables to overcome,
and gives to inherit all things.

L+++.+++ A. Barclay.

To Hannah Marsh

Reigate, 20th of 11th Month, 1839.

&hellip;And now, my beloved friend and sister, in looking back at our goings forth together,
my soul seems at times melted under a sense of the goodness and mercy that followed
me--mercy towards many weaknesses and goodness condescending still to favour;
it is an unspeakable relief to have been so helped through.
We have been favoured to learn some good lessons together,
which I desire ever to remember and profit by.
I have sometimes thought there is danger, after being so engaged for several weeks,
of getting too much enlarged in words, of getting, as it were,
into shallower and more spreading water; therefore,
as I endeavoured to remember M. Binns`' good advice in going along,
so I desire now to sink down again as into the deeps,
that so I may be favoured with true ability as required
to bring up from there the one stone of memorial.
And now, my dear friend, oh, that we may be preserved living and learning, yes,
learning continually lessons of life, lessons of peace,
and lessons of praise to the great and good Master.

L+++.+++ A. Barclay.

To +++_______+++.

11th Month, 1839.

My Dear Friend,

I have felt much exercised on your behalf for some time past,
and as it has revived since the monthly meeting,
I can do no less than express the earnest desire I feel that the matrimonial
step you are about to take may tend not only to your present but eternal welfare.
But, my dear friend, if you come to witness this to be the case,
it must be by its promoting the best life, a growth in the favour of God,
wherein is the life of the soul.
To this end be careful, both before and after its consummation,
to bow your soul daily before the Lord,
that you may know Him to bring all your nature into
pure subjection and humble resignation before Him;
wait upon Him and feel after His melting and quickening power,
that he may give you to desire that He would make
and mold you as He would have you to be in all things,
even His faithful servant and testimony-bearer.
Oh! watch against the selfish wisdom and will, as ever you desire life;
for it will be still deceiving and cheating you of what the Lord would have you to enjoy,
and waits to graciously bestow upon you.
And it is the Lord who alone can bring it all down to nothing,
and He "`will be inquired of to do it,`" and to fill with His heavenly goodness;
therefore, wait continually on Him,
and yield to what you feel of His good power in your heart--shrink not,
but open your heart to what He reveals in you, and when you feel and hear,
obey with your whole heart.
Thus will you witness the house of Saul to grow weaker and weaker,
and the house of David stronger and stronger--the power of an endless life to increase,
and the light thereof to shine brighter and brighter unto the perfect day,
bringing fruitfulness and glory unto God,
and peace and blessedness to yourself and all around you.
Then, indeed, will you be a true helpmeet to dear +++_______+++,
a strengthener and upholder of his hands in all things
the testimony of the Lord`'s blessed Spirit requires,
and not in any way a hindrance or weakener;
then will you be enabled faithfully and uprightly to labour with your own dear family,
as well as become "`a succourer of many`" others,
a faithful "`servant of the Church,`" with good will
doing service as "`to the Lord and not unto men.`"^
footnote:[See Col.
and Ephes.]

L+++.+++ A. Barclay.

To +++_______+++.

Reigate, 11th Month, 1839.

My Dear Friend,

In looking over those on whose behalf I have lately felt exercised, I trust,
in Gospel love, you seemed to come before me, as having felt while among you,
a desire to have some of your company separately;
but the way did not appear to open for it, so I thought I would take up my pen, and,
as matter arose, salute you in this way.

Ah! my dear M.,
I believe you have felt the Lord`'s good hand of
power to be laid tenderly upon you from time to time;
you have heard the secret, though piercing, quickening call, "`The Master is come,
and calls for you.`"
Yes, He calls for you to come up nobly in a faithful testimony-bearing for His name,
that you may gather others under His banner of love and power,
and wax more and more valiant for Him the blessed Truth.
Now, oh, what can you do less, seeing His exceeding tenderness and goodness,
than rise up quickly and go forth after Him,
away from all natural feelings that would detain or impede you, that you may be His only,
His wholly--exactly what He would have you to be--His dear faithful servant,
wholly given up to be led about, guided, and governed, and regulated by Him,
your good Lord, the best beloved of all redeemed and redeeming souls.
Oh, yes, who or what can be so dear to you as He is!
Therefore, love nothing so much as Him and His precious law revealed in your heart,
by which He will daily regulate you, and teach you wondrous things,
causing you to understand more and more of His heavenly doctrines,
as you are engaged to be found meditating therein, and walking according thereto,
in all the simplicity and humble dependence of a weaned child.
Oh, how will this precious law, or word nigh in the heart, work mightily in us,
as we shrink not, but yield up ourselves wholly to be formed and operated upon by it,
even to the breaking all the hardness of our natures,
to the bringing down all the highness of our natures,
to the melting the stubbornness thereof, straitening the crookedness,
enlightening the darkness thereof,
and to the exalting of that which is lowly and hidden under all!

Oh, then, my dear friend,
may you and I increasingly bow (even with a holy magnanimity and
resolution of heart) under the working of the Lord`'s mighty,
yet secret power; let Him humble and melt us as He will,
and make us vessels of honour in His house, of what kind soever that may be;
servants of His Church, that He may be glorified in us, by us, and through us.
Some have more to contend with in themselves than others of weakness, or fear, or doubt,
or untowardness; but the Lord`'s power is sufficient for us all,
to bring all down into the blessed and peaceful harmony of subjection to His will,
if we do but yield up unto Him.
Oh, let us love nothing that is of self or the creature (whatever we have a life in,
under whatever plausible pretext) in comparison of Him.
Let all be given up to His good power, and then He will make a way where we can see none;
make hard things easy, and things exceeding bitter to nature, to be most sweet; yes,
make all things subservient to the purpose of His grace,
and fulfill the work of faith with power, to His own praise.
Ah! let not the enemy, in any way, cast you into discouragement, or doubt, or fear;
but sink down, and lie down, as it were, under the hand of your tender God;
wait for Him again and again to touch you, draw you, quicken faith in you,
and help you with a little help from time to time; and then you shall find,
to your unspeakable comfort,
that greater is He that is in you than he that is in the world,
or that works in the selfish nature;
and a song of praise shall live in your heart to Him who is your
tender helper and your shield against all the attempts of the enemy;
your resurrection and your life; yes,
your heart shall be filled with His praise and with His honour all the day long.
So, my dear +++_______+++, may you be faithful, and then I know you will be fruitful,
to the praise of God and to the help of many others,
and you will be blessed and be a blessing.
Surely this, I trust,
temporary indisposition is designed to be a renewal of covenant as at Bethel.

L+++.+++ A. Barclay.

To +++_______+++.

12th Month, 1839.

My Dear Friend,

I have felt affectionately and earnestly solicitous on your account
since I heard of your friends acknowledging you (as a minister),
and I fear to withhold the expression of my feeling,
though it is with much fear I attempt it, yet, if we fear a snare for our brother,
and neglect to be sincere and faithful to him, his blood will be required at our hands.
Oh, my dear friend, we need a weighty, and not a light ministry; living substance,
and not mere sound; and this may be the case in few, as well as in many words; therefore,
O let us keep back to the life--keep out of willing, and running, and haste,
and wait patiently that the Spirit may arise purely and stilly in the heart,
which gives perfect evidence and full testimony of itself:
a few steps taken in the life and power of God are much safer and sweeter,
than a hasty progress, in the hasty forward spirit.
Oh, what danger is there of being settled down in a light-weighted ministry,
continually up and doing something; whereas, by abiding in the stillness and patience,
it may be often shown, that what has presented, even with brightness,
is not to be handed to others, but to be dwelt under at home!
And how may the enemy even then bring in a false uneasiness,
as if we had done wrong in withholding, that he might lead us into forwardness.
But in waiting in the patient stillness, and watching to the light of life,
all his wiles will be discovered, and the pure judgment of truth come at,
to our humbling instruction and unspeakable comfort, whatever that judgment may be.

And now, my dear friend,
I hope you will receive these few lines in the dear love in which they are penned,
and which I have ever felt flow towards you and your dear wife.
I may truly say,
I desire the wounding of none--the discouraging of nothing that is living and tender;
but rather that it may be rightly nourished and strengthened, so as to grow healthfully,
and not into a weak or diseased state.

I believe I write under a humbling sense of my own
great weakness and danger of falling every moment.
And how do I desire that I may be thus faithfully
dealt with and watched over by my dear friends;
and more than all, that the Lord, whose faithful minister I desire to be,
would be pleased yet more and more to show me my own weakness and frailty,
to humble and correct me continually as He sees best,
and keep me ever low in His pure fear, and in watchfulness and faithfulness before Him,
all my remaining little day for Him here,
that flesh may be abased and silent before Him forever,--that His blessed
testimony may be exalted and upheld in its own purity and virtue,
and His holy name may be praised, magnified, and glorified over all forever and ever!

L+++.+++ A. Barclay.

To +++_______+++.

12th Month, 1839.

My Dear Friend and Cousin,

There is an old saying "`better late then never.`"
Since being with you I have felt much on your behalf,
and though it is now some time since we parted,
yet I believe I had best be sincere in the faithfulness of true love.
I must own I felt your hospitality and great kindness
when under your roof much and gratefully;
but there was a sadness covered my mind in looking round at the house,
and the dear children also, which I did not feel able then to cast off the burden of.
There seemed to me no appearance of self-denial or the simplicity of the truth,
but rather of self-gratification and the worldly spirit.
It felt trying to me in remembrance of your dear parents and the station they occupied.
And it felt trying to me also in the full belief, my dear younger sister, that,
although we know birth-right cannot give possession of the truth,
yet that you have not been without the tender touches of the Lord`'s power,
persuading you away from such things and giving you to admire
consistency and faithfulness in any you have seen so helped;
so I felt sorry that you should in any way be yielding
to the inclinations of nature or the fears of nature,
instead of (by yielding to the drawings of grace)
coming up in the footsteps of the faithful,
answering the pure testimony of Christ`'s blessed Spirit,
both in your own heart and in all around you, and thus be gathering to Him,
and not scattering from Him!
I believe that (whatever they may say to the contrary) much lies
with the mother and mistress of the house in these respects.
It must do so.
Oh! then take care how you in any way weaken the good work, the tender work,
of the Lord in the hearts of your dear partner and eventually of your dear children,
by leading them into the worldly spirit and the gratification of the vain mind,
instead of using a gathering,
strengthening influence to draw and help them out of weakness in
best life! even that life which stands in the favour of God,
and not friendship and conformity with the world!

I know, alas! that there are but few true examples among us,
even in those who are in station, I grieve to say; but oh!
I believe we must not be looking out at others (even the princes of the people),
but must mind the dear Master`'s call,
"`You follow me;`" and I do believe some of us who have been mercifully blessed with
abundance must be willing to make sacrifices even of what we should like very much,
that we may set an example of the simplicity which the Spirit of Christ,
the ever blessed and unchangeable truth, will ever lead into--not I mean,
that we should all be exactly of the same pattern (as I heard dear S. G. once say),
but we should all be in the simplicity of truth, by subjection to the Spirit thereof.
Oh! this is the unity and the beautiful harmony that is greatly needed among us,
even in subjection to Christ`'s Spirit in all things;
for this is the great Gospel ordinance to which we must all submit,
in this Gospel-day of the breaking forth of God`'s
power in the hearts of His children and people.

Oh then, my dear sister,
to the inward law and the inward testimony of God`'s blessed Spirit,
revealed in our hearts, let you and I increasingly give heed,
which will tell us all things that ever we should do,
which will make a nice distinction between that which serves God,
and that which really serves Him not,
but gratifies the vain mind and the worldly spirit in ourselves and others,
and therefore serves the enemy of our souls instead of God.
Oh! it will show us the nice and finicking ways, and things that are crept in among us,
the superfluities and the downright ornaments and trimmings,
and it will bring the Lord`'s pure judgment (upon them all),
and it will strengthen us to cut off all these things, and to cast them away,
as not of God nor pleasing Him,
(for as W. P. says) with light and sight comes strength to follow as the light leads.
And then, I believe, as we are engaged to cut off all our superfluities and ornaments,
like the Israelites of old, through the operation of that leaven or Spirit,
that works mightily both within and without,
then the Lord would show some of us what further
He would do with us in His Church and family,
for the honour of His great name,
and for the gathering of others under His holy banner of love and power!
Oh! then, my beloved cousin,
let us look to it lest we be robbing the Church of faithful servants,
robbing God of His glory, and robbing ourselves of His blessed peace!
Farewell, from your very sincere friend and cousin,

L+++.+++ A. Barclay.

To +++_______+++.

12th Month, 1839.

My Dear Friend,

My mind seemed brought into an exercise and earnest desire yesterday,
in our little retirement after breakfast,
that I might be faithful in that little portion of service allotted me while hereaway,
whether it be to "`warn the unruly, to comfort the feeble-minded,
or to support the weak`"--and under this feeling of resignedness, you, my dear friend,
were brought before me in near love and unity,
and a desire seemed raised in me that you might be encouraged to increasing
faithfulness in doing what your hands may find to do for our good Lord,
for the advancement of His precious cause and kingdom
in your own heart and in the hearts of others.
Oh, my dear friend, it is time for you and me, and some others,
to come forward nobly and simply and show ourselves on the Lord`'s side,
that He may make us valiant for the truth,
and enable us to come up to His "`help against the mighty.`"
We can say that His goodness and mercy have followed us all our lives,
and what shall we not render unto Him of devotedness to His cause and praise to His name!
Oh, let us not in any way look outward at what others may think, say,
or do--"`be not afraid of their faces,`" and "`fear not with their
fear,`" but let us "`sanctify the Lord of hosts Himself,
and let Him be our fear and our dread,`" and then "`He will
be for a sanctuary,`" for us "`a hiding-place and a shield.`"
It is for us above all things else to mind the Master`'s
secret whisperings and smallest pointings,
and then He will undertake for us, make a way for us,
guide us aright and strengthen us to take right steps
in His fear and in obedience to Him.
And how encouraging is the declaration,
that even a mere cup of cold water handed in His name or power,
by which the little good thing in any way may be revived or strengthened,
shall not lose its reward.
And no matter our weakness and foolishness,
if we do but cleave the closer to Him in whom is everlasting strength and wisdom;
it is all the better that we have nothing of our own to lean on,
that no flesh may glory in His sight, that all may be of Him, and for Him,
and to Him forever.

I have believed that there are men and women in our monthly meeting,
who should by this time of day be strong for the Lord and valiant
for His precious cause in their different callings and degrees,
if they were more nobly and simply faithful to what they
have felt and do feel in the secret of their hearts.
And oh! what hinders it from being thus with them,
even honouring the Lord with all their substance, temporally and spiritually,
and honoured of Him, growing in His divine and life-giving favour,
and in fruitfulness and usefulness in His family.
Surely He has not been lacking on His part, time after time, to influence,
to touch and draw, and to lay His tender hand upon them in one way or another;
and oh! may such take heed of robbing Him of His glory, the Church of faithful servants,
and themselves of heavenly peace.
There is a false fear, and diffidence hinders some,
but this must be crucified in us as much as any other natural obstruction--and oh,
if we keep close to the blessed Spirit which touches and draws,
and wait in the stillness thereon, it will arise and make manifest all feelings,
the root of all, and give a perfect evidence and clear testimony of itself,
so that we need not doubt; and if we yield thereunto in the faith, willingness,
and resignation which is of its own begetting, so it will work, or strengthen to,
the obedience, and seal peace to the obedient.

Then let us, my dear friends--for I would affectionately include your dear wife too,
for you are one in my feeling--let us increasingly yield
ourselves up to the tender touches of God`'s hand of power,
which we do often feel to be good upon us, melting our hearts and contriting our spirits,
and raising the fervent desire to be His only, His wholly,
then shall we more and more know the heavenly increase of light, life, strength,
obedience, peace, and praise to Him who has indeed done great things for us.
Holy and reverend is His name!

L+++.+++ A. Barclay.

To +++_______+++.

Reigate, 21st of 1st Month, 1840.

My Dear Friend,

I have these last few days been often turning towards you and your dear husband in particular,
and long to know how you fare, and he feels.
Sometimes I have fancied him very low as the prospect of the time
of "`showing unto Israel`" what is upon him draws nigh,
yet I trust he finds, as he has often done, the good hand to be tender upon him,
reviving faith when at a low ebb,
and causing to cleave unto that which has been known and felt of the Divine power,
whereby strength will be received to bring forth
at the right time that which has been begotten,
to the praise of Him who is mighty,
and who still condescends to do great things for His poor, weak, unworthy little ones,
ordaining strength and praise even out of their mouths!
I shall be much interested in hearing of your monthly meeting on fifth day.

And, my dear sister, I have much unity with your attending on your dear +++_______+++,
and I earnestly crave, as far as enabled,
that you may be preserved in your stepping along in the simplicity, watchfulness,
and retiredness of the truth, that by a close keeping, and a simple looking and feeling,
you may be instrumental to open the door as it were--and that,
when it is closing in the Divine fear and power,
you may be assistant (by your spirit) in keeping it so,
lest anything should creep in and scatter,
or steal away that which has been in mercy left with the visited.
Thus will the Lord`'s pure fear be predominant, the Lord`'s power do all,
have dominion over all, and the praise of all.
I hope I have not done amiss in penning thus what seemed to arise,
I trust under a humble sense of my own childishness,
and in the feeling of near and dear love to all who
love and serve the precious cause as you do;
and oh, my beloved friend, let us, as put into our hearts,
breathe for one another`'s help, strength, and preservation,
for indeed we have great need of all the feeling and sympathy and
prayers one of another--but your poor friend more than all.
Perhaps I am particularly alive to this subject (the snares
and the weakness attending the honour of the cause,
and the awfulness of the vocation) just now;
and how do I desire that it may more and more continually be brought before me,
lest I should err from the right and pure way!

L+++.+++ A. Barclay.

To +++_______+++.

Reigate, 2nd Month, 1840.

Dear M.,

I thought I felt a salutation of love to you, your brothers, and H.,
and considering the uncertainty of time, it seemed safest to put pen to paper.
It felt very solemn and instructive to me last First day to sit in dear +++_______+++`'s room,
and the feeling continued for several days, and as I was meditating on the solemn sight,
and was enabled to enter into tender sympathy with you, her dear brothers and sisters,
who are more constantly witnesses of it, and more closely tried by it,
how earnestly did I desire that you also might be
seriously affected and tenderly touched by it,
as no doubt is most mercifully designed by our heavenly Father,
who never afflicts willingly, nor delights to grieve us,
but in compassionate love He touches us in a tender spot,
to arouse us to look to Him who does it, to feel after Him who thus calls to us,
that so we may seek after and find His heavenly favour and peace,
which is better than life or all things here below--yes,
which is the crowning blessing of all outward blessings,
and the life of the soul both here and hereafter!
And whenever I have thought of you and felt for you, which has been,
I would affectionately assure you, very often, how have I desired that you, each of you,
might be increasingly careful never to yield to do anything which at a future day,
when a sick bed and a rolling pillow may be your portion,
might in the least degree bring uneasiness over your mind!

I expect it has been a time of deep searching of heart with dear +++_______+++,
and a great blessing and favour it has been to have such a long time of preparation; but,
my dear friends, it will not do for us to reckon on having such a favour.
We know not how we may be situated, and I have no doubt she feels, as many have,
that the pains and weakness, and gradual wasting of the poor body,
are greatly clogging to the spirit, hindering it from soaring upward to its centre.
How important, how deeply important, then, is it that we should,
while health and vigour are permitted us,
seek earnestly and diligently to have our spirits wound up for heaven,
attuned to the unceasing anthem there of "`Your will be done!`"--for
unless we are thus prepared and clothed with heavenly dispositions,
heaven would be no happy place to us,
the harmony thereof would be discordant and disgusting to us,
neither could we join in the angelic anthem!
And oh, my beloved young friends, if you ask how may we come to this happy experience,
or who is sufficient to bring it about in us, the answer in my heart is,
"`None but Christ, none but Christ, who has all power!`"
He has the key of David,
whereby he can wind up our spirits and attune them
to the pure worship and holy praise of heaven;
and this key is His blessed Spirit,
whereby He touches our inmost soul and turns His tender hand upon us,
for the very purpose of this most glorious and blessed end.
Oh! then let us yield ourselves in submission to His Holy
Spirit--let us give ourselves to the touches of His power,
to the turnings and drawings of His good hand, at all times and in every respect,
and then He will not fail to do great and mighty things for us and in us,
to the perfecting His good and gracious work in us,
that He may present us and confess us to His Father and our Father,
as His own dear redeemed ones.
And such shall be accepted in Him the beloved, and their unceasing song shall be,
"`Worthy is the Lamb that was slain, to receive power, and riches, and wisdom,
and strength, and honour, and glory, and blessing; and blessing, and honour, and glory,
and power, be unto Him that sits upon the throne, and unto the Lamb forever and ever!`"

Earnestly desiring that we may let nothing hinder
us from pressing after this most blessed experience,
from so running as that we may be mercifully favoured to obtain this most rich prize,
I remain my dear friends, your sincere and affectionate friend,

L+++.+++ A. Barclay.

To W. E.

Reigate, 2nd Month, 1840.

My Dear Friend,

Your visit was pleasant and animating last week,
as it always is to meet with any whose eyes have been mercifully
anointed to see the beauty and blessing that there is in the truth,
even in the spiritual kingdom and government of the Lord Jesus Christ;
and who have in measure been brought and are more
and more bringing into the participation thereof,
through a willingness graciously wrought in them,
to sell all that is near and dear to them that they may purchase it,
or experience this law and power to rule in dominion over all in them,
casting down everything that is high and airy in them,
laying low the strongholds of self,
and bringing every thought into captivity to the obedience of Christ!
And these are as lively epistles written in one another`'s hearts,
tending to one another`'s comfort and strengthening,
and speaking forth the praises of Him whose grace from day to day upholds and preserves
them--though now (as formerly was the experience of the faithful) for the Lord`'s season,
if need be,
they may be in heaviness through manifold afflictions and temptations
for the trial of their faith--chiefly from the sight and sense given them
of what the Lord requires of those who profess His blessed truth.
And how far--how very far--behind the professors thereof are in coming up faithfully,
according to the pure testimony of His Spirit!
And when I have looked at some of us who thus go mourning on our way, having, as it were,
sackcloth on our loins, out of sight (except, perhaps,
disclosed to a few who understand our speech), I have felt an exercise on my mind,
and a fear, lest, in our beholding these shortcomings, we should, almost unaware,
let anything of the creature creep out, and so either judge or point the finger,
as it were, at those things out of the true humbling and fear,
or else sink into dismay and unprofitable lamentation, out of the holy faith in,
and simple yielding to, the Lord`'s never-failing arm of power.

Oh, how many ways has our subtle enemy to hinder the Lord`'s good work,
which He would bring forth in us and move us in!
And self may be stirred up in,
or may lie at the bottom of even that which looks very plausible and on the right side;
but in that which lies low in the fear, is the preservation.
Oh, then,
that we may increasingly seek to dwell in the deep
inward exercise where the true judgment is given;
where all that is of the creature is silenced,
and where that which is tender and lowly--which truly sees, and feels, and breathes to,
and leans on its Father, is nourished and gathers strength,
and is enabled to suffer patiently, to confide simply, and to act faithfully,
to the perfecting of His praise.

As I felt these words spring up in my heart (possibly
principally for my own instruction and warning),
I thought I would share them with you in the true love,
desiring your strengthening in a healthy, safe growth,
whereby much fruitfulness may redound to the praise of the great and good Husbandman,
who does indeed bestow abundance of tender labour on us,
and who is everlastingly worthy of the glory due unto His great and excellent name.

L+++.+++ A. Barclay.

To +++_______+++.

2nd Month, 1840.

My Dear Young Friend,

I believe I must acknowledge that my mind yesterday was introduced
into much exercise and affectionate solicitude on your account,
under a renewed belief which has long attended me,
that whatever you may have been learning in the way
of business since your residence in this neighbourhood,
you have been losing ground spiritually;
losing instead of gaining in that which is the very best getting of all other gettings,
the one thing supremely needful,
and which only will stand you in stead in the day of trial,
the time of affliction and sickness, and the hour of death;
even in the earnest search after that wisdom which "`is profitable to direct,`"
and after that pure fear of the Lord which is the beginning of wisdom,
and will be found to be "`a fountain of life, preserving from the snares of death.`"

Oh, my dear young friend,
do you not feel in yourself a loss towards yourself--a loss
towards God?--a little less tenderness towards Him,
a little less desire after the knowledge of His ways,
and the feeling of the tender touches of His power in your soul;
but rather an inclination to disbelieve them, and turn from them,
lest they should lead to what is mortifying and disagreeable
to nature (as it is true and likely they should)?
And this has arisen from slighting of the gentle
voice of Christ`'s Spirit in the secret of the heart,
and a turning from the shinings and instructive reproofs of His light in the conscience,
which I believe you have felt and heard even in very little matters,
for I fully know we can never go down hill, as it were, or lose ground spiritually,
without being favoured with timely warning and sufficient
strength to rally again if we will but lay hold of it.
And so having suffered a loss of strength inwardly,
through unfaithfulness to these little feelings and secret reproofs,
then it appears outwardly also;
the mind becoming more and more leavened with the worldly spirit,
and into a desire after new and fashionable cuts, and articles of dress,
and modes of dressing the hair,
and then the manners and language must be moulded accordingly also;
and so the simplicity of the truth is gradually thrown off,
and we lose our testimony-bearing,
and cannot be distinguished from others who do not profess so highly as we do.

And now, oh, my dear young friend,
how earnestly do I long that you may be aroused to consider where you are,
what you are doing,
and where the path will lead which I fear you have made some steps in!
Ponder the path of your feet in the pure fear of the Lord.
Search and try your ways by His holy light.
O beg of Him to search and try you thoroughly, and not to spare you,
but lead you in the way to everlasting life and peace.
Oh, if you do but turn unto Him with all your heart, and cry unto Him--"`My Father,
you shall be the guide of my youth,`" yielding yourself
to be guided and restrained by Him,
He will again and again visit you with His love, strengthen you by His grace,
and preserve you by His power,
even amidst all the varied temptations that assail the path of the young.
Oh, remember He has been the guide and feeder of your dear father
all his life long (as I well remember hearing him testify);
his Redeemer and help in all evil; and if you seek Him with full purpose of heart,
and serve Him uprightly with a willing mind,
I believe He will deal as tenderly and bountifully with you,
and bless you with His heavenly blessing, which makes truly rich.^
footnote:[Genesis 48:15-16]
Heed not what others may say or think, neither look at what they do.
Shun such society as draws you away in mind from your best friend--your dear Saviour,
whose voice and call is to you in secret, "`Come with me, come with me,
and I will bless you.`"
O go forth quickly after Him (as Mary did), bearing and not being ashamed of His cross,
and verily you shall have treasure in heaven.

L+++.+++ A. Barclay.
