== Chapter XIV

To R. R.

Spital, Aberdeen, 18th of 9th Month, 1847.

My Dear R.,

It is long since I took up the pen to you, and long since I heard from any of you;
but as I expect you are waiting till after quarterly meeting,
I am inclined to supersede you.
It is a time that my mind seems much with you,
as they always must be seasons of deep exercise to the faithful as well as of suffering;
but if we cannot do anything for that cause which is very precious to us,
we may be enabled to suffer much with and for it, and this is accepted,
and is a favour to us poor creatures.
I sincerely hope you will be enabled at that time to feel and act what is best
in regard to that committee which is likely to be appointed--that you may faithfully
and fearlessly oppose what is likely to be against the truth,
and honestly and simply stand up for and testify for what is likely to promote it,
that so there may be no cause for regret or sorrowful feeling afterwards.

We keep much to ourselves; indeed I am convinced it will be most for my strength,
and then if there is to be a coming out and forth it will be with most effect.
I have adored the wisdom which has shut me up,
believing it was good both for others and for myself.
Ah, the good Master knows what emptyings and humiliations are for our good,
and in His own time will bring us forth more like gold purified for His use;
and what a mercy He should deal thus excellently with us poor worms of the dust!
I desire that patience may have her perfect work in all the deep baptisms needed,
and then, when a word is given,
wisdom and power will also be given to come forth in increased purity in it,
whether it be as a new sharp threshing instrument to thresh the mountains of high profession,
or as a hammer to break down the stout opposing wall of self-conceit and pride hereaway,
or whether it be as the genial sunshine and gentle showers
from heaven to quicken and raise up and nourish the tender,
lowly seed of the kingdom.

L+++.+++ A. Barclay.

To +++_______+++

Aberdeen, 22nd of 10th Month, 1847.

My Dear Friend,

I fancied you at H. on fourth day, and can feelingly enter into sympathy with you,
dear +++_______+++, in being united in that committee.
I do hope you will let nothing hinder you from being
faithful to the sense and savour of truth,
that you may be favoured with,
in which you may be a strength to +++_______+++ and +++_______+++.
Ah! I long with you that you may be able to get down deep,
beneath all the cogitations and reasonings of man, into the nothingness, the humility,
the simplicity, and true dependence on and seeking after best wisdom and might,
direction and preservation, and thus alone may you be made helpful to the body!
Things are indeed low with you; but it is only as we are baptised in Jesus Christ,
by the one Spirit and holy fire,
that we shall be enabled to feel them so rightly--that is,
that we shall by union with Christ see and feel them as with His eye and feeling,
having His heavenly mind; and so feel them,
and consequently suffer with Him under their state,
as to be willing to put forth our hand in simplicity and faithfulness at His bidding,
and in His name, to help them up a bit into a better state!
For it is not enough to mourn over the state,
but the true mourning will seek to help the state by each one`'s
faithfully labouring as before his house for the public good.
And however poor and weak we may feel in ourselves,
let us remember the daughters of Shallum assisted their father (and he was a prince,
a ruler of the half of Jerusalem) in the good work of repairing the walls!

My dear love to +++_______+++. I have been expecting to hear from her for some time,
but expect she is in a low spot.
Remind her of the few smooth stones picked up in the valley of humility,
and slung in the Divine name,
that were effectual for what was required--and brought down the mighty Goliath!
I am pleased you think of sending some of those tracts to Australia.
I have such interesting accounts from dear +++_______+++ of a dear young man at +++_______+++,
who comes from +++_______+++,
and appears under convincement! also a similar account of +++_______+++`'s sister,
who is passing through much in coming towards Friends;
also of dear +++_______+++ who is not a member; he seems in a sweet and tender state of mind,
and thoroughly coming back;
it would glad your heart to see a letter of his that +++_______+++ has just lent me to read!
So I have my little ups as well as downs, in this remote and solitary feeling corner;
and though far off, am not debarred from the feeling of things,
the things of the dear Master,
whether they cause mourning in secret or the inward shout of praise.
Oh, to be enabled to be, and permitted graciously to be, a sufferer and testimony-bearer,
and labourer for the precious truth, is all I desire,
and far beyond all earthly gettings, and it is no matter then,
how hidden or solitary I may be, for the Lord "`knows them that trust in Him.`"

Farewell very dearly.
I fear this is hardly worth sending,
but it will assure you of my dear love and tender sympathy,
in which I rest your faithful friend,

L+++.+++ A. Barclay.

To +++_______+++

Spital, Aberdeen, 17th of 12th Month, 1847.

Dear Friend,

Having heard indirectly, through dear +++_______+++, that you are still tried in business,
I thought perhaps a mite might be acceptable, though it may not help you much.
Times have been very trying in trade, and you have my sympathy in your uphill travel,
and my affectionate desire that nothing may move you from the pure testimony
of the Spirit of truth in the faithful witness within you,
which will unfailingly guide you aright and in the peaceful way,
though for a time it may be in the way of trial and of poverty;
yet that is better than to sin against your conscience of what is right--for a little
with a peaceful heart is better than much riches with the worm that dies not.
I shall be much interested in hearing a little how you get on, or what tries you,
if you are free to tell me.
I long that you may be helped to be faithful and watchful in all your steppings,
and not fear the jeers or reproaches of man, nor yet bow to any man or his reasonings,
but let your bowing be truly to the Lord`'s power,
and let His Divine fear be ever before your eyes,
and then I cannot but believe you shall hold on your
way and be blessed by degrees in basket and store.
We poor finite creatures don`'t know what degree of trial and of proving is good for us,
and we think it is hard to be proved at all; but the Lord, our tender Father,
knows our weaknesses and what we most need to purify us,
and He will not prove us beyond what He will enable us to bear,
if we look to and lean upon Him alone; and as we yield up our all unto Him,
so He will do us good in all His dealings towards us,
and enable us to bless and praise His name for all, yes, "`most for the severe.`"

You would greatly feel the death of your dear sister W. And your poor brother-in-law,
how I do feel for him!
Has he anyone to attend to his dear children?
I long he may be more devoted to Him, who called him, I do believe,
"`out of darkness into His marvellous light,`" and that he should not
bury the talent as under the bushel of worldly gettings and cares,
but set the candle mercifully lighted as upon the candlestick.

Farewell, dear friend.
With feelings of desire for your help every way, and preservation from every snare,
I remain your sincere friend,

L+++.+++ A. Barclay.

To +++_______+++

Spital, Aberdeen, 3rd of 1st Month, 1848.

My Dear Friend,

We need more examples of consistency!
And I am much pleased to hear you feel no regret, but on the contrary peace,
in the sacrifices you have made for principle,
as well as ascribes the power and the glory to Him who is
the blessed Strengthener of His little humble ones,
to do what He requires and promises them peace in!
Truly He is good to them who seek His favour above all,
"`to them who trust in Him before the sons of men!`"

I have often felt for you in your very small meeting--but, dear friends,
the Lord`'s power gathered and strengthened us at the first
by ones and twos in solitary and trying places,
and He is as good and mighty as ever to help us all to be faithful unto Him,
and thus to be instrumental to hold up the standard
of truth and be a blessing to many others,
while receiving the blessing ourselves!

I remain your sincerely affectionate friend and well-wisher,

L+++.+++ A. Barclay.

To +++_______+++

Without date.

How wonderful is your dear sister`'s state,
that she should thus have such intermittent feelings of renovation and relapse!
Is this intended as a further purification, by proving her resignation to the Divine will?
for it must be indeed a great trial, after the mind is brought into an awful resignation,
and a humble worship in the prospect of being taken from this state of being,
to have that prospect changed by the probability of recovery!
What unwillingness must there be to return to this lower world,
and what fears of how future temptations and trials may be borne!
But how excellently does infinite wisdom and love see what we need to
perfect that which concerns us according to His astonishing goodness;
and how tenderly will He apportion all to this blessed and glorious end,
purifying and bringing all within into the pure worship and holy praise of heaven;
and when this is the case, will say, it is enough,
come up here and you shall see by closer union than you can now, the bride,
the Lamb`'s wife, and partake of her blessedness!

L+++.+++ A. Barclay.

To +++_______+++

5th of 1st Month, 1848.

Ah, "`the faithful fail from among the children of men`" may it not be said?
yet I believe there is a goodly number of the younger
and middle aged who are desiring to be so,
yet, alas! they fall short of what they should be,
and so are too much settling down as dwarfs and stumblings.
Oh, that these might be aroused to be up and doing for the Master,
and thus show their love to Him in whatever little way He
may be pleased to point out and gently press them towards.
And I am aware there is a doing or working for Him
by suffering as well as by greater activity,
yes, by seeking after that daily dying unto the old nature in us, whereby the new nature,
His own pure life, comes to be raised up and strengthened in us,
which effectually gives to feel with Him and consequently to suffer with and for Him,
as well as enables to breathe forth continually the language, "`spare your people O Lord,
and give not your heritage to reproach that the heathen should rule over them!`"

Oh, how availing is this hidden life, working example as well as precept when called for,
and this hidden prayer,
ascending even in the midst of tribulation for the precious cause sake!
The present is indeed a dismaying time, and afflictions seem increasing upon us,
the furnace waxing hotter and hotter.
Surely never was the enemy of all righteousness more specious in his devices
to lead astray and beguile from the dominion of the Saviour,
though under the appearance of all righteousness and all that is sweet and lovely!
Therefore, never was the danger greater and the trials deeper to the faithful;
and the time seems hastening on when, according to prophecy, both ancient and new,
the house of Israel shall be sifted as corn is sifted in a sieve,
and they shall be left so few in number that a child may tell them.
But there is a precious consolation in remembering that
not one grain of true weighty wheat shall be lost,
and that "`the foundation of God stands sure, having this seal,
the Lord knows them that are His.`"
And "`will not God avenge His own elect which cry day and night unto Him?
I tell you He will avenge them speedily,`" was the gracious answer.
And let it encourage us to lift up our heads in hope,
and seek for ability to possess our souls in patience;
for if we faint not in confidence towards God,
if we fail not in faithfulness and deep humility before Him,
we shall surely reap in due time, even obtain, through His mercy in Christ Jesus,
the crown of life which ever awaits such as love
and yield to His inward appearance in the soul.

Oh, then, may He keep us so to the end of our little time here,
for we cannot keep ourselves a moment,
but let us cast ourselves as it were into His tender and powerful arms,
even permit His power to rule and work in and for us, and we shall be safe!

L+++.+++ A. Barclay.

To the Same

12th of 2nd Month, 1848.

Well, my dear friend, the Lord is taking away all our creature comforts one by one;
He is handing us one bitter cup after another; but oh,
let us still kiss the hand that afflicts,
and may we increasingly learn to lean only on Him,
and to let Him only be our Rock and our Refuge, to trust in Him at all times,
and pour out our souls before Him.
May He be with us, and support us both in the breaking down of these outward tabernacles,
and in the breaking down of our friendships, or rather the outward comforts of them;
for the inward union and strength of the true friendship is not
severed or weakened by death--it is of an enduring nature,
like Him whose life is the soul of it as it were.

More is the need for us who have watched the path of the upright as the
shining light that shines more and more unto the perfect day,
to put on fresh strength in the name of the Lord,
to buckle on with fresh alacrity the whole armour of light,
that we may be enabled to withstand the wiles of the enemy,
and to live the life of the upright during the remainder of our days,
that we also may be prepared to die the death of the righteous,
praising and glorifying the name of the Lord, by whose grace they were what they were.
Surely it is because we are not yet ready that we are left a little longer,
and what a mercy that is!
Oh, how much have I yet to break down and to be purged out!
but He is of power to carry on the work of faith in us,
and perfect that which concerns us, if we do but yield up our all to Him,
and allow His Divine power to work in us His Divine will.
Ah, this is what is needed in individuals in every church almost,
and then there would be no deficiency in our borders, but a blessed revival,
indeed beauty and purity.

This is indeed a reading and writing age,
and we have need continually to recur to the Divine balance to guide in both,
as also to recur supremely to the Divine word to season our minds therefor,
to instruct us thereby, and to preserve us from harm therethrough.

L+++.+++ A. Barclay.

To +++_______+++

Spital, Aberdeen, 24th of 2nd Month, 1848.

My Dear Friend,

Your letter the other day introduced me into sympathy with you under your various trials.
I feel much for you at this trying time of trade.
It must be hard and anxious work to get along,
or rather to bear up against the overwhelming tide,
shall I say of encroaching and covetousness,
which the worldly spirit leads so many into in their trading,
to the hurt of their more moderate and honest neighbours!
But I often remember how it was with our dear early Friends,
when they first were called upon in secret to make
a stand against the world`'s ways in these things,
how they seemed at first as if they should hardly get their bread,
and especially when so seized upon for tithes and rates to their great spoliation!
But, in process of time, as they persevered in faithfulness to known duty,
their character became so established for integrity, uprightness,
and thorough good dealing, that the people would inquire where was a Quaker butcher,
baker, tailor, etc., and their trade greatly increased,
and they were blessed in all they put their hands unto!
And so I have faith to believe it will be yet witnessed by the faithful;
and even if deliverance and blessing should not come as quickly as they would desire,
that in the meantime the Divine presence and power will be their support, while proving,
as to a hair`'s breadth,
and His peace will be more worth to them "`than thousands of gold and of silver!`"

May you be enabled from day to day to seek after and obtain that fresh
"`help from the holy sanctuary and strength out of Zion,`" whereby alone
we may bear up amid the trials and temptations of our day,
and be qualified to glorify the great Name in our lives and conversations before men.
I remain, with love, your friend very sincerely,

L+++.+++ A. Barclay.

To +++_______+++

Bregsell`'s Farr, 19th of 6th Month, 1848.

My Dear Friend,

I should have liked more of your company.
I seem often, as I go along thus,
to have the query arise in my mind and sometimes to be uttered,
both for my own searching and possibly to stir up my dear
friends to the same--How far we have grown in the truth,
and made strait steps in the heavenward path since last we saw each other?
And, in looking back at my visit to you,
I have feared lest there has been a standing still and a shrinking from that going forward
in simplicity and upright-hearted faithfulness to which you have been called.
The kingdom now, as ever, comes not with observation,
is not known to increase in our hearts by looking out at others,
either at what they say or how they do or think and
feel--this is too like a seeking a sign from heaven,
as the adulterous generation or spirit does in every age;--but
it is to be known within as our eye and ear spiritually is turned
to see the pointings and hear the words of the good Shepherd,
the true Husband--and not only hear and see, but the heart given up to obey.

Oh, there is too little of a minding of inward impressions and conviction among us,
and until we know a closer watch unto all obedience to them,
we shall not progress truly in grace, in the truth,
and the heavenly kingdom not only come but set up and increasing within!
A little clear conviction in secret, in the silence and coolness of our own spirits,
in regard to men and things around us,
is worth a great deal that we can hear from this or the other dear and
valued friend--it is truly a sign from heaven sealed to each one of us,
and will not deceive us!
Yes, may I not say that the revelation of the Spirit of Christ,
in and by which God and His will,
Christ and His preciousness and blessed rule is made livingly known to each of us,
is the Rock on which the true Church is ever built?
I long you may both be building on this sure Foundation;
then it will be no matter what becomes of men and things,
for you will have the seal that the Lord knows you to be His.
Then will you be kept more loose to the worldly spirit in your business and in
all you put your hands unto--faithful testifiers by example against it,
and your hands will be kept clean and hearts upright for your dear Master`'s use,
and what you do will be seen and felt to be for His pure service and to His glory.

Farewell, in dear love to you both, from your very affectionate friend,

L+++.+++ A. Barclay.

To R. Barclay, of Ury

Stonehaven, 9th Month, 1848.

My Dear Cousin,

I have been staying here a fortnight,
having returned here after our dear friends who had the meeting left us,
and have been pleased to meet with a few serious people of various denominations,
as well as have enjoyed the scenery round this most interesting spot to me,
I might almost say classical ground among Friends! yet my
reflections have often been of a sorrowful cast,
as I have remembered the faithful worthies of old times,
our honoured ancestors who lived and walked in the Divine fear and service in this neighbourhood,
and have felt how greatly many of their descendants are departed
from that pure light and life which shined and lived in them,
and made them faithful in every good work,
and enabled them to endure hard sufferings for conscience sake!
Yet the Divine Being remains the same as ever,
mighty and willing to redeem from all the evil and weakness of our fallen nature,
and to gather out of the darkness thereof into His marvellous light, into His pure life,
into His precious love, into His enriching and enduring peace,
all those who are willing to yield to the secret touches,
reproofs and leadings of His Holy Spirit in their hearts!
Yes, He spares long and visits again and again, even as at the eleventh hour,
those who have long been rebellious,
striving to bring them away from those pursuits and pleasures, which,
in times of cool reflection,
they are convinced will not give them peace on their deathbeds!
How, then,
can they with impunity refuse so great and tender salvation!
how can they refuse to sacrifice anything that He requires,
that they may obtain that precious gift which our Saviour
came and died and ascended on high to purchase for them,
even that the Lord God might dwell among them and bless them!

I have, since being here, been once within your park,
and could I have walked so far as the house, should have called on you,
as my deafness precluded my partaking of the conversation
with you when I called with the above Friends;
but as I could not do so,
I hardly felt easy to return home to Aberdeen without writing you these few lines,
and asking your acceptance of two little tracts as a token of my
sincere love and desire for your best welfare both here and hereafter,
which I hope you will receive kindly, and believe me to remain your affectionate cousin,

L+++.+++ A. Barclay.

To +++_______+++

Aberdeen, 14th of 9th Month, 1848.

My Beloved +++_______+++,

How very sweet it was to see your own hand-writing again,
after being brought down to the very gates of death!
My dear girl,
what a great blessing you must feel it to have been thus spared and even raised up again!
Surely your heart must be often melted in looking at the
goodness and mercy which have followed you day by day,
and gratitude, I hope, is the clothing of your mind,
although your note does not convey any feeling in this way.
What can you render, indeed,
what can you not render to Him who has dealt so tenderly with you,
but renewed love and dedication and subjection of heart, yes,
praises (shown forth in conduct) out of a humbled and devoted heart?
I feel penetrated with grateful feeling whenever I look at your recovery.

We have been much taken up with company at and since our general meeting,
then we went two weeks to Stonehaven for a change,
and to spread Friends`' books and tracts, there being much openness for them,
and we met with a few sweet Methodists who sat with us on a First day evening,
also a few others, and it was a favoured time,
and it felt hard to break up;--their preacher among them, who pleased us much,
came another evening to tea with his wife.
I left two sets of books with one or another of them for lending there.
We used to take long walks, sitting down by the way,
and generally brought our little tract bag twice back empty daily.

One favourite walk of mine was up a hill south of the town, from the top of which,
looking southward,
we looked down almost perpendicularly into a pretty
little wild bay encircled with rocky cliffs,
beyond which were the ruins of Dunnottar Castle jutting out as upon a pinnacle
of basaltic rocks into another little romantic bay--in the dungeons of which
castle many "`gude souls`" were immured during the wars of the Covenanters.
Then turning our faces round (where we stood) to the north,
we looked down as steeply into another more placid little bay; at our feet lay the clean,
airy little town of Stonehaven, in a snug corner near the rocky promontory,
with its busy little pier and harbour;
beyond this were other bays and rocky capes towards Aberdeen;
westward were the lands of Ury, with its white castle embosomed in fine woods,
the park extending for miles over hill and dale.
You will judge this was a favourite spot with me, and I spent many hours there,
meditating on the faithful worthies who used to live and walk there,
as also on the degeneracy of their descendants.

Captain Barclay was very kind to us; showed us over the place and the mausoleum,
when I went with +++_______+++ and +++_______+++; took tea with us at the inn,
and sat beside us at the public meeting.
The place is going to be sold; I am hoping someone of the family will buy it,
as it is a place generally visited by Friends who come here.

My dear +++_______+++, I am much hurried to finish this;
but cannot help saying I long that proportioned fruits may be rendered
by your grateful spirit to Him who has restored you to health, etc.
Believe me to remain your truly affectionate and sincere friend,

L+++.+++ A. Barclay.

To +++_______+++ and +++_______+++

Aberdeen, 25th of 9th Month, 1848.

My Dear Friends,

Your kind letters did indeed touch my heart,
and had I had time I should have written for you to get at Dorking;
and moreover it was as a brook by the way to poor me,
or like a little oil of joy in the midst of grief--for I found your two kind epistles
on the table on returning last fourth day from our monthly meeting at Kinmuck.
Oh, the sweets of precious unity and true love! truly it is like the holy ointment poured
upon Aaron`'s head that descended to his beard and the nethermost skirt of his garments,
and as the dew on the mountains where the Lord commanded of old His heavenly blessing!
And, dear hearts,
it made me glad that you were going forth together
as fellow-helpers and workers together for the Lord,
your good Master, and the feeling and desire was and is,
"`The Lord be with you;`" and no doubt, also,
the feeling and desire that lives in your hearts,
while sensible of your own weakness and inability of yourselves to do any good thing, is,
"`The Lord prosper the work He gives us to do,
and preserve us to Himself and His glory!`"

My mind has been daily with you,
and oftener fancying to whose house you were bending your exercised course now and now;
and especially as I have been dressing in the morning,
which is often a time of sweet meditation and of
feeling with and for my dear far distant friends.
I hope you will let nothing hinder you from delivering the whole counsel Divine,
but that you may be so enabled to go down deep into
baptism with and for the dead and buried,
who are too many among us, as well as the defiled,
as that you may be qualified to minister true judgment where it is due,
and rightly divide the word wherever you come;
and though many are and will be the low and plunging seasons to pass through,
yet I trust and believe the everlasting Arm will be underneath
to support your (sometimes perhaps) fainting minds,
and to hold up your heads above the waters of conflict,
and that a little drop of heavenly peaceful comfort and calming
quiet will be permitted you in mercy from day to day.

I suppose this may reach you at +++_______+++. I hope you will have been
helped to search out the evil that lets and hurts and dims there,
and to encourage to that yielding to the mighty humbling power of truth,
whereby comes the true honour as well as the blessing to the church.

Desiring for you heavenly strength and preservation day by day,
I remain your nearly united friend,

L+++.+++ A. Barclay.

To S. B.

Aberdeen, 15th of 10th Month, 1848.

My Dear Friend,

I think I heard that latterly dear +++_______+++ had but seldom given up in meeting at R.,
which induced me to query of you how it was with her now.
I think you would do well to help her in what you can,
she may have been discouraged improperly or let in the enemy`'s reasonings,
and if that was a right calling,
perhaps this affliction is sent to call her again to faithfulness!
I do feel tenderly for such and desire their encouragement, yet above all things,
long for a pure offering, that what is offered may be of and for and to the Lord alone;
and no matter the few stammering words--for the few smooth stones
from the lowly valley slung in the pure name of the Lord,
brought down the mighty giant.
I do long for the servants and plough-boys to give up in these
days of man`'s arts and parts so universally prevailing,
that no flesh may glory in the Lord`'s sight.
Oh, how many a precious gift has been hurt by being drawn out after others,
after the opinion or example or favour of man,
instead of keeping close to the pure Divine gift, and inward in spirit,
that we may watch and wait for it, and feel its arising!
I have had great peace (now during my own long shutting up as to words) in having
printed and handed that tract of Job Scott`'s on this awful subject,
and it has been comforting the approbation of many and their comfort in it,
although I have met with the reverse.

I was pleased to hear our dear +++_______+++ gave up in
the last quarterly meeting at +++_______+++. Ah,
the dear Master knows what good He is about,
in shutting as well as opening either for our own good or the good of others,
and let us bow to Him.

Ah, my dear friend, it is a mark of our degeneracy,
the little care and feeling one for another that there is among us;
it was not so at the beginning, when if one member suffered, all suffered with it,
and if one was honoured, all rejoiced with it.
It is because we are not really baptised into Jesus Christ,
and if we know nothing of this,
our profession without the form is as bad as that of others with the form;
it avails us nothing, indeed,
the greater is our condemnation for making a more spiritual profession.
But, dear friend, let us who feel these things,
increasingly seek after the daily true baptism and true supper,
that we may be in true fellowship with our dear Lord, even in His grief and sufferings,
and then He will not fail to show us what we can individually
do to help up a bit in these days of degeneracy,
by putting our hand to what He points out in secret,
and if we are faithful (no matter whether we are or are not in
station) we shall receive an increase in heavenly good,
and be rewarded with soul-satisfying peace.
Therefore, dear friends, may you be faithful where your lot is cast,
and you know not how it may stimulate others to their duty.

With dear love to you both, remembering the pleasant times I had with you in days of old,
I remain your very sincere friend,

L+++.+++ A. Barclay.

To M. C.

Aberdeen, 24th of 10th Month, 1848.

My Dear Friend,

It seems long since I had any communication with you,
and I feel inclined to take up the pen.
And I salute you and your dear husband in renewed love,
though I have little to tell you that will interest you;
yet sometimes to know that our friends think of us is cheering by the way;
for I dare say you find with me,
that many are the low spots and the rough stony places and the clogging
swamps that we have to pass over in our journey to a better country,
and the mountains seem sometimes to rise higher and higher,
and we feel but poor weak solitary creatures to encounter difficulties
and the enemies that surround and would hinder our progress!
But oh, dear friends, help is still as ever laid upon One who is mighty, and He can,
out of much weakness, make to be strong in Him and in the power of His might, yes,
He can make a little one to chase a thousand,
and a feeble one to be valiant for the truth!
Therefore, I desire that you may not faint or improperly fear,
nor let go your hold of that which you have ever felt to
be right and required in the secret of your hearts,
remembering that it is "`he that endures to the end that shall be saved!`"

Oh, dear friends, we are poor weak creatures,
and unless we daily seek after the Lord`'s heavenly quickening power upon our spirits,
how dead shall we become to the things of His cause and heavenly kingdom,
and so there is danger of our allowing our earthly cares and enjoyments
to overcome us and prevent that aspiring of the soul heavenward,
whereby comes the true spiritual food and strengthening to fill
up those places in the Church militant to which we are called!
I have greatly longed,
that as you are favoured with an increase of family and consequently of necessary cares,
that your souls may in proportion be the more earnestly lifted up to Him,
the Lord your blesser! that He would keep you more
and more alive unto Him in a daily exercise,
for His quickening guidance, strengthening, and preserving throughout each day,
that you may be kept alive to His cause,
and enabled to put your hand to the Gospel plough for the promotion thereof,
for unto this are we every one called, more or less,
and are favoured with many precious visitations in
order to persuade and encourage us thereunto!

I long that you, dear M.,
may more honestly and nobly come forward to the help of the Lord against the mighty,
in any little way that may be pointed out in your mind, and that your dear J. may,
in the like manner, in true uprightness, stand by the good cause,
and be willing that the power of truth should humble him anyhow for the purpose,
that so he may become a firm pillar in the Lord`'s house,
for the support of the burden of the Lord`'s testimony.
Ah, if we thoroughly yield to the Lord`'s humbling power,
it will draw us out of all self-saving and self-seeking,
self will be laid as in the dust,
and the Lord`'s honour and cause will be more dear to us than anything of our
own or any saving of ourselves from exposure to what others may say or think!
Oh, this true nobility, this honest uprightness,
this going straight forward is what we so very greatly need as a people! and I believe,
if we yielded to the gentle drawings and teachings of the Spirit of truth,
it would not fail to bring us into this good state.
And then the Lord would be conspicuously with us to bless us,
and the savour of our spirits would gather others unto Him,
and not a dog could move his tongue against us;
for "`the righteous shall hold on their way,
and he that has clean hands shall wax stronger and stronger in the heavenly might!
and the Lord will show Himself strong on behalf of them who fear Him above all!`"

I hope your two dear bairns are going on nicely, growing in stature,
and I hope beginning to be well trained in giving up their little wills.
How very soon is the evil seed noticeable in dear children,
and how easy is it to be nipped in the bud!
With love, I remain your and your sincere friend,

L+++.+++ A. Barclay.

To +++_______+++

12th Month, 1848.

My Dear Friend,

Having so few opportunities alone with you I thought I would take up my pen,
and in sisterly love tell you that I was made sad a few days ago,
by hearing that there was a paper or card up in your shop or window,
saying that pale beer was sold there!
Is this really the case?
I have no doubt the present must be a trying time for trades-people.
I sympathise tenderly with such as have large families,
believing they often have many difficulties to contend with, and thus are induced,
by plausible motives,
to add one little matter or source of profit after another to their business.
But oh, my dear friend,
we who make so high a profession (and especially such as occupy
stations among us) have need to ponder well all our steppings,
to consult the pure and faithful witness within,
to weigh things in the balance of the sanctuary,
and see whether such steps are in the Divine ordering or not,
whether they have the Divine sanction,
and we can ask the Divine blessing upon them as being
such as will serve Him and His heavenly cause,
or whether they are more likely to serve the enemy,
to lead to the injury in various ways of our fellow creatures,
and thus in various degrees to mar the Lord`'s glory.

I have frequently felt pained in looking at your business,
under a fear that you have suffered loss by yielding to such motives of expediency,
and have looked at things too much in a worldly light or spirit,
instead of cleaving close to the gentle intimations and hesitations which the true light,
the pure life of Christ, would give you to feel respecting this or that, and which,
as simply obeyed, would lead to a cleanness (and consequently strength) of hands,
a clearness of sight, and an uprightness of heart for the Lord;
and if we are not clean-handed ourselves we cannot plead for our good Master with others,
no, we rather may be strengthening their hands in other inconsistencies.

I cannot help believing that if you had withheld from,
or had put away from you the selling of tobacco, snuff,
and intoxicating or fermented liquors, you would have witnessed more peace,
more strength, and would not have fared the worse for it even in a pecuniary sense,
for the earth is the Lord`'s and the fullness thereof,
and He can bless or blast all our endeavours;
and surely those who so sadly and peculiarly witness
the pernicious effects of smoking and drinking,
have peculiar need to discourage all in their power such bad habits,
and of all people should not feel easy to derive a profit by the promotion thereof.

Oh, my dear friend,
I entreat you to consider the subject even in the true light and deep exercise of mind,
and the Lord make you willing to search into all that you put your hands unto,
and enable you to wash them in innocency in these respects,
even though it be by a temporary sacrifice, not looking outward at what others may think,
say, or do, nor yet fearing the consequences, but sanctify the Lord of hosts Himself,
and let Him be your fear and dread, and follow Him and His pure testimony,
so shall the arms of your hands be made strong by and for "`the
mighty God of Jacob,`" your example will be strengthening to others,
the barrel of meal shall not waste, nor the cruse of oil fail, yes,
the Lord shall give that which is good and His soul-enriching peace shall be your crown.

Desiring you may receive these lines of sisterly faithfulness
and sincerity in that love in which they are written,
and may above all things seek after the true nobility and the true stability,
in which I desire to be your companion, I remain,
while sensible of my own great weakness and need of watchfulness,
your faithful and affectionate friend,

L+++.+++ A. Barclay

To +++_______+++

Aberdeen, 21st of 6th Month, 1849.

My Dear Friend,

My dear love attends you all.
I very often think of you and other dear distant loved ones always on a First day afternoon.
I last First day had a sweet afternoon; it was a brilliant day,
and I had been once again helped in this meeting,
and in mercy favoured with peaceful quiet after it.
And I strolled out into the garden after my siesta, and walked and sat there,
and enjoyed the scene.
The sea looked so deep a blue, the waves dashing up upon the light-house rocks;
there were lights and shades over the undulating landscape,
caused by the clouds alternating the bright beams of the sun.
There had been some nice showers after a long drought,
and all nature seemed to rejoice and look refreshed.
I felt solitary; none to whom I could say,
"`How sweet it is!`" and yet I seemed surrounded by you and other kindred spirits,
and felt that the Lord was good, and that the earth was full of His riches,
and it seemed enough and far more than such a worm is deserving of;
and if He be near to support and sustain amidst sufferings and trials,
what will it matter what we go through, so they do but work the good designed,
and all draw us upward and inward!

L+++.+++ A. Barclay.

To +++_______+++

Aberdeen, 26th of 6th Month, 1849.

Your account of the yearly meeting was very acceptable.
It`'s no matter, however, such an exercise might not please some,
or even excite ridicule or derision, +++_______+++ was Divinely led, Divinely strengthened,
and blessed with Divine peace, and this none can give or take away.
Ah, they who don`'t like going into what they call little things,
they do not remember that it is said,
"`he that despises the day of small things shall fall by little and little,`"
and thus have many among us fallen gradually and imperceptibly till we
have got into the very low spot we are now in,
of mere outward profession like other people,
with but little of the power of godliness among us
really to be felt and seen by our fruits.

I have been very poorly the last ten days, and I feel often very low,
yet it has been sweet to remember my dear friends in the south,
and to hold sweet communion as it were with them in spirit,
and whether we ever meet again,
I trust we shall be united by that precious bond which death cannot sever,
and by subjection to the Spirit of Christ we all have the same mind and are of one accord,
drawing heavenward and Christ-ward;
and so may we be kept even to the end of our little time here,
that He may take us to Himself hereafter.
And though we be reduced still more as a people, and be given to suffer more bitterly,
yet the Lord will be sufficient for His little faithful ones,
and in due time will plead their cause, and bring them forth as gold seven times tried,
and He will set His mark on the sighers and the weepers, and, when He sees fit,
will gather and save them,
and will set them on high as the precious stones of a crown to His own glory,
and no flesh shall glory in His sight.

Farewell, my beloved friends,
hoping we shall be enabled to bear one another on each of our hearts,
and to breathe for each others`' help, strength, and preservation to the end,
and thus may feel the help of each others`' spirit, and, when able and free,
write to your truly affectionate and united friend,

L+++.+++ A. Barclay.

To R. R.

Aberdeen, 8th of 7th Month, 1849.

My Beloved Friend,

Once again do I salute you from my northern home,
which continues to be dear and sweet to me,
notwithstanding the trials and privations that attend it.

Ah, my dear friend,
I have often remembered and saluted you in dear love since I have been returned home,
now three weeks last second day,
whose cravings the short opportunity of being together in London has not satisfied,
and it has been sweet to remember the solemn and precious time in silence first,
and then in expression, cementing and strengthening,
encouraging and solacing even amidst much to cast down and to try.
Such sort of opportunities or meetings together with dear ones,
may be looked back upon with peace,
and with praise to Him who gives us every little brook that we get by the way.

L+++.+++ A. Barclay.

To R. R.

Aberdeen, 30th of 11th Month, 1849.

My Dear Friend,

How pleasant, cheering, and strengthening is our fellowship together, at least to poor me!
Well, let us take comfort in the reflection that the good Lord thinks upon such.
How tender and kind to do so, and just at our moments of need!
Oh, the preciousness, because the exactness of His holy help, can our souls say!
Then may we more and more entrust Him with our all, and, as you say,
not shrink from any sort of disciplining that He may judge best.
Ah, it is, as it were, easy to desire to do so, but when it comes to the pinch,
the proving with us, then we find it hard work to be resigned, to believe,
and to suffer patiently what is permitted.

L+++.+++ A. Barclay.

To +++_______+++

Aberdeen, 1st of 12th Month, 1849.

My Dear Friend,

Since I saw you, I have visited my old friends and home in Cornwall.
Ah! what vast changes I witnessed! changes by circumstances, by growth of years,
by death, and, worst of all,
by a departure more or less from the truth and launching into the world!
It had altogether a melancholy effect upon me.
I think there were twenty removals by death in the +++_______+++ and +++_______+++ families only,
in the twenty-three years since I resided there!
But I was comforted, in the midst of tribulations and exercises for the cause sake,
in feeling that the tender good hand of Omnipotence
is laid upon several of the younger class,
and that some seem sweetly bending under it, chiefly in +++_______+++ and +++_______+++ meetings;
and to meet with these dear creatures seemed like a little brook of refreshment
and cheering by the weary way!--meeting seemed most forlorn in prospect,
and was a place of deep exercise to me.

I expect your situation in +++_______+++ gives you much quiet seclusion,
which perhaps may be congenial to your feelings as well as helpful spiritually,
for the spiritual life is hardly strengthened and nourished in bustles and excitement.
To dwell alone and keep silence, bearing the yoke of the dear Master,
and laying the mouth as in the dust of self-abasement,
seems peculiarly desirable at the present day,
there being but few whose society and example is strengthening to us, but many,
on the contrary,
who may have a tendency to draw us out of a deep dwelling and close watch,
wherein alone we may know the true seed to take deep
root downward and bring forth fruit upward.
Still, man is a social being, and should not shut himself up from his own flesh,
as it were, but seek after that watch wherein he may, in his interactions with others,
glorify his Maker and edify his brother in the true love to God and man.

I have been tried many ways with spiritual afflictions, with outward trials and straits,
as well as with various deep baptisms, buffetings, and conflicts,
for the trial of my faith and the purifying of my love,
known only to the great Searcher of hearts,
who wisely and tenderly hid these things from my prospective view,
or else I should doubtless have refused to have yielded to such humiliations.
But, blessed be His good name, He has through all hitherto sustained and helped, and,
in moments of extremity,
so lifted up the light of His glorious and soul-cheering
countenance and given a little feeling of peace thereby,
as has exceedingly comforted me in all my afflictions,
and stimulated to still trust in Him and not be afraid,
or to doubt His power and goodness.
So, dear +++_______+++, having received such large mercy,
I still am enabled to hold out and to press forward in hopes of reaping,
through adorable and unmerited grace and redeeming love,
the prize of our high and holy calling in Christ Jesus.
Yet, again and again, after such little glimpses of heavenly good,
in order to cheer up and preserve from fainting,
am I reduced and stripped naked as it were, shown my weakness and vileness in myself,
and made to abhor myself as in dust and ashes!
These are the Lord`'s tender ways with the workmanship of His hand,
and most pilgrims can testify thereunto,
and declare that He is "`very good,`" a stronghold in the day of trouble,
and He knows them that trust in Him.

And now, farewell.
I am, in much love, your affectionate friend,

L+++.+++ A. Barclay.

To +++________+++

Aberdeen, 4th of 12th Month, 1849.

My Dear Friend,

Your kind and sisterly letter deserves to be soon answered and gratefully acknowledged,
for it was truly acceptable and refreshing to my lonely and afflicted spirit.
I do believe if we attend to little pointings in epistolizing our dear friends,
we shall be instrumental to their help and strengthening when we least expect it,
and even when perhaps we are feeling ourselves as very poor weak creatures,
more in need of being ministered unto than fit to minister unto others.
And at such times, the few smooth stones fetched up as from the depths of self-abasement,
slung in the Divine power and in simple faithfulness,
will be available to the bringing down these reasonings and discouragings,
which the enemy is apt to raise up so very high as to overwhelm our dear absent friends;
and then how sweet it is for such to mingle together, and praise the Lord together,
as it were, with one heart and mouth, though widely separated.

My heart could respond to all your remarks,
especially in regard to the past experience of suffering
being only as "`the beginning of sorrows.`"
For surely things are getting worse and worse,
and the enemy`'s deceptions are so very specious,
and the appearances so plausible looking,
that even the very elect seem to our view almost ready to be deceived thereby.
Never was there more need among us for the dwelling deep, low,
and inwardly on the watch as you describe,
for it will not do to look out at the feelings or opinions of any,
nor yet even to put confidence in a brother beloved.
But there is comfort and encouragement in the reflection that the depths of Satan,
the mysteries of ungodliness, as well as of the heavenly kingdom,
will still be revealed to the simple babes,
and the meek and humble will be guided in the path of true judgment; yes,
concerning themselves, and all things without them.
The texts you quote are very animating--yes,
He can and will make the depths of the sea a way for His ransomed ones,
and He does comfort His afflicted remnant from time to time,
and He will be glorified in them and their deliverance,
which shall come in such a way as that no flesh shall be able to glory in His sight,
but all crowns be laid at the feet of Him who sits upon the throne judging righteously,
and of the Lamb forever!

As the year wears away,
I begin to look with longing eye to the pleasure of meeting many dear ones,
but we know not what a day may bring forth.
I have no doubt you are with me sensible of many infirmities creeping over you,
and the mind partakes in degree of the weakness of the body.
But what a favour to be able to say,
we feel as much alive as ever in desire for the upholding
and promotion of the blessed cause of truth! "`Oh,
to grace, how great a debtor!`"--is there not such a line somewhere?
and we do feel it so! I think I may say my soul has seemed at times, as it were,
wrapped up in sorrow.
But Divine goodness has, at some moments of extremity,
immediately and powerfully helped me when thus brought low;
and having found such grace in the needful time,
I am enabled still to hold on and to look and breathe upward unto Him,
who alone can keep us from falling,
and present us with acceptance before the throne of the Majesty on high!

I have written much more than I at all intended when I took pen,
and have run on in the freedom of old friendship,
I hope not to the multiplying words without knowledge,
being favoured through mercy to know in precious degree that whereof I affirm.
And now, dear Friend, farewell, with dear love to you both,
and your sisters whom I by no means forget--and in the feeling of much
sympathy and unity as burden-bearers and fellow-sufferers for the truth,
I remain your affectionate friend,

L+++.+++ A. Barclay.

To +++_______+++

Aberdeen, 17th of 12th Month, 1849.

&hellip;May these considerations lead us more and more
into a close searching of all our ways and our spirits,
and to cry mightily unto God for preservation,
and to cleave the more closely to the Spirit of Christ, whereby alone we can be guided,
strengthened, sustained, and preserved to the end in uprightness for His pure testimony.
Surely never did we need more of true discernment, and never had we less of it among us!
It seems as if the devil were trying all his powers against the pure truth; and oh,
to lie low and cleave close to the little seed of
life and light! here will be our preservation alone.
It requires great care how we let our feelings or fears out before our dear young people.
Ah, the pure truth will stand though all forsake it,
and though we as a people be scattered and brought to nothing, yet a remnant,
a poor and afflicted people, shall be preserved,
faithfully upholding the pure testimony thereof,
and eventually they shall be raised up with power to declare and promulgate it.

L+++.+++ A. Barclay.

To +++_______+++

Aberdeen, 27th of 12th Month, 1849.

My Dear Friend,

My feelings will hardly let me be long without writing you after your kind, long,
interesting, and affecting letter,
and I could have answered it directly had it been suitable.
My dear friend,
you were the first to give me the sorrowful tidings
of the sad disclosure at +++_______+++. This,
as well as all other evil and weakness, springs from the one evil root:
a departure from the pure and simple pointings and restraints of the Spirit of Christ,
the principle of light, life, and truth in the secret of the heart.
For I most assuredly believe that there is no evil
but has been made manifest and restrained from,
and that with the restraint and manifestation comes power all-sufficient,
if we will but allow ourselves to be led thereby in the true faith and simple obedience.
And I cannot but believe that this has been the cause not only of poor +++_______+++`'s fall,
even by little and little,
but also of the erring in vision and stumbling in judgment
of the others--they leaning to affection or esteem naturally,
or public opinion, instead of dwelling deep to feel the judgment and pointing of truth.
It is a weakness we are liable to fall into at burials,
and therefore it requires a double watch and quickening to guard against it.

But, my dear +++_______+++,
there is no need for us to be greatly moved or shaken
by these tidings of evil--the upright,
it is said, shall not be so.
I hope our hearts are fixed in a firm belief in the unchangeableness and
all-sufficiency of the Divine power of the Word that was in the beginning,
the quickening Spirit from everlasting to everlasting,
the Rock and Foundation of God that stands sure,
the blessed Truth that remains the same though all men forsake Him, the Christ of God,
our Redeemer;
and that consequently as all-sufficiency and unchangeableness is with Him the fullness,
so also there is no variableness,
no lack of sufficiency in that measure of grace and truth,
that manifestation of His Spirit, that talent of light, and life,
and pearl of great price, and leaven of the kingdom, which we have all received of Him,
and in and by which He and His Father are to be known, believed in, and obeyed;
and that as we are engaged in humble, faithful obedience thereunto,
we may truly "`trust in God`" in all these times
of shaking and sifting and treading down.

Oh, therefore, that all these things may the more drive us closely inward and deep,
to cleave to this blessed principle or power of an
endless life in all the secret revelations thereof,
and gentle restraints,
wherein alone is the way of life and peace and preservation to the end.
Oh, here, my dear friend,
we shall find all-sufficient strength to resist every temptation and snare of the enemy,
to bear us up and sustain us under every trial and proving,
and to enable us to perform all that is required of us, so that I want us,
however tempted or tried to a hair`'s breadth,
to endeavour to turn our eye away from the temptation, away from poring at the trial,
and to endeavour to gather inward and low to the tender quickening of life within us,
which will clothe us with the true childlike spirit that is willing
to be led and proved and governed as our Father wills and permits;
and as our minds are thus stayed in humble trust,
we shall be kept in perfect peace and praiseful quiet.
Ah, He knows our frame, and tendencies, and weak sides, and what proving is for our good,
and His tender mercy will not allow us to be tempted or tried above
what we shall be able to bear with His holy help;
and when we are brought into unity with His will and power in any dispensation permitted,
and thereby answer the design thereof, and receive the good mercifully intended thereby,
then will that dispensation be changed to us,
and our mouths shall be renewedly filled with His praise and with His honour.

It is very comforting to me your allusion to Shackleton`'s Letters;
and if you have not got the book in possession,
I should be pleased to make you a present of it.
It is so desirable to lend to young people.
What a good service it might be for one of your leisure to pick
out some choice scraps from Patrick Livingstone for tracts!
I had four small pieces printed as tracts for this neighbourhood,
which no doubt you have seen; but there are others that might be culled from it.
I am now copying out and preparing John Conran`'s journal, and very instructive it is.
William and Alice Ellis is very good,
and I am much pleased that J. B. could bring it forth.
Oh, there is nothing of the modern works like those of the faithful worthies of old times,
so clear and cogent, plain and practical.

Your allusion to my visit in Cornwall was truly encouraging and humbling, and I desired,
in reading it, that it might strengthen my hands in future,
for many are the plungings that we are often tried with, though unknown to others,
and such little lifts are very acceptable,
and designed to stimulate to fresh dedication as
well as humble in renewed grateful praise.
What a sweet account you gave of the poor woman near K.! Was it Clara Popplestone?
That is a sweet tract,
but needs a little more testifying for Divine grace and the work thereof.

Your affectionate friend,

L+++.+++ A. Barclay.

To Hannah Marsh

Aberdeen, 16th of 1st Month, 1850.

Your dear John F. Marsh`'s kind letter to me was quite strengthening,
and will be still as I read it again and again.
On second day I had five letters from dear friends including yours,
and was melted in gratitude to Him who thus favours me with such precious lifts;
and I craved that I might ever be kept so in unity with the blessed
principle of light and life from Christ by subjection thereto,
as that I might be preserved in that precious unity with His faithful servants everywhere,
which emanates and proceeds from the true fellowship,
with the Father and with His Son Christ Jesus,
and which blessed fellowship will only be fully consummated
and everlastingly enjoyed in an eternal state!

L+++.+++ A. Barclay.

To +++_______+++

17th of 1st Month, 1850.

I send you another copy of Job Scott`'s tract.
I sent them by post to all the select meetings in Great Britain--that is to one, two,
or three individuals in each, desiring them to spread them.
I had letters from several disapproving of them, and among others from +++_______+++,
who queried by what authority that had been published
which wise judicious Friends in America had withheld?
with much about lack of love and unity, and discord and jealousy, etc., etc.
I was helped in humility, I trust, yet firmly to testify to +++_______+++,
that these extracts were such as the wise Friends he alluded to
no doubt judged not so fit for a book for the public eye,
being more adapted for ministers and elders, and, for that reason,
I conceived there might be a service in printing them peculiarly for that class,
tending to strengthen the hands of some and to help others out of weakness and mixture;
and that I humbly trusted that the same good Spirit which had led
Job Scott to write them had laid the concern on me to reprint them,
and in which little work I had had great peace,
as well as the testimonials of many valuable and faithful Friends
as to the good service and the need for it--at the same time saying,
that, on reading his query,
I had comfortingly remembered how my dear Master had been
thus queried of by the wise Pharisees of old,
and I desired to be made like Him in suffering all things meekly.
I also desired to know what he alluded to as to lack of concord, unity, love, etc.;
for I thought that to do what little we could,
and when and how directed and impelled by the Spirit of the dear Master,
was the way to be preserved in the true unity, love, concord, etc.

There are some things in those two volumes of Job Scott`'s Works,
which I also have got and greatly value,
though edited by a Hicksite! which are too mysterious or deep for all to comprehend,
and which might be taken in an improper sense,
as if not so highly valuing the outward coming and sacrifice of our blessed Saviour,
as I fully believe dear Job Scott did.
There is quite sufficient in his works to show that he did highly
value and only look for remission of sins by that precious offering.
On this account, and because the book was edited by a Hicksite,
I never let it be about my parlour,
nor introduce it to any who are not spiritually minded.
These deep subjects are mysterious now as ever to the wise and prudent of this world,
though preciously revealed in adorable mercy to the babish spirit!
It is a book I highly value and enjoy,
and the letters are so sweet and beautifully poetic,
and how nice and lively they would have been in the journal scattered about.

I am pleased to hear you are on the committee for elders in +++_______+++ monthly meeting,
and greatly desire you may be favoured to seek after and
obtain right feeling in regard to any names proposed,
and strengthened also to speak consistently with that feeling,
nothing doubting and no man fearing--for if we have
not faith in the little touches of the Divine power,
where are we as a people?
I don`'t know who there can be there,
who are rightly anointed and baptised for the station,
and they had better have none than such as are not thus qualified.
There is no must in the case,
either for the committee to name names or for the meeting to appoint them;
and sometimes the mere consideration and exercise on the subject,
when none are felt to be suitable to name, may be beneficial,
and what if I say not impossible to go far towards a helping some
into the seeking after and yielding to the qualifying power.
How striking is Paul to Timothy on bishops, which is applicable to elders! and oh,
the need to have such as are clean-handed, as well as upright-hearted and clear-sighted,
for lamentably is it true with us as a people that the leaders cause us to err!

+++[+++Referring to the interment of one whose conduct had brought reproach upon the truth,
she writes]--Ah, if there had not been a leaning to the own understanding,
to creaturely affection and esteem, or to public opinion,
instead of to the pure light and life Divine revealed within,
there never would have been such erring in vision and stumbling in judgment,
to the hurt of many.
Those who speak at burials have need of double clearness and quickening of life Divine,
before they allude to the character, etc., of the deceased,
for nature is so easy to be warped aside as above.
Oh, how are we killed all the day long by these sad things, but may we be warned (and,
oh,
that all our elders laid hold of the subject to warn
all) to cleave closer than ever to that pure gift,
the principle or power of light and life from Christ, which like Him,
the blessed Fullness, is unchangeable, though men may, by unfaithfulness thereto,
become forsakers of the truth, which is all-sufficient also to guide us safely,
to strengthen us mightily, and preserve us faithfully to the end.

The idea of meeting again many dear ones in the summer is truly cheering,
if favoured to get so far south, but the prospect is accompanied by many awful feelings.
All things are in good hands,
and may we be given up to do and suffer all He permits and requires,
and then peace will be our portion whatever becomes of us.

Dear love from your affectionate friend,

L+++.+++ A. Barclay.

To W. H.

Aberdeen, 30th of 1st Month, 1850.

For what are we but poor worms of the dust?
and what is family name or pedigree?
How little will it avail to be descended from or related to the truly great and good,
while we are out of subjection to or despising that
power whereby they were made what they were,
faithful servants of the Lord Jesus Christ, and valiant for His precious cause on earth!
Surely the more will be our condemnation, if,
while we have their example and their writings as it were before our eyes,
and their blessed end also, we should not be walking in their footsteps,
nor manifesting forth the same life that lived and moved and acted in them,
and preserved them to the good end that crowns all.

L+++.+++ A. Barclay.
