== Chapter XVI

To +++_______+++

25th of 7th Month, 1851.

My Dear Friend,

I have been thinking of you much in Cornwall, which was once my home for several years,
believing you would feel comfort in meeting with many dear Friends there,
who would be very kind and helpful to you,
and my breathings have been many and great for your
strengthening and preservation from all snares,
for many indeed, as you well know, are the snares set in the way of poor travellers,
and there is no safety but in a close watch over our own spirits,
and a close cleaving unto His secretly revealing and strengthening power,
who stands ready to help the humble and breathing ones in every time of need,
and is almighty.
And, dear friend, bear with my faithfulness if I say that,
as I have felt that a peculiar temptation to you is to give way to the affectionate part,
so as to endanger the losing the position of the watch,
where the true feeling for the Master is obtained,
and the humble desire arises to be preserved in circumspect conduct and conversation--so
I have the more earnestly craved that the good hand may continually guide,
strengthen, humble,
and preserve you from day to day during what remains of your required service,
that so the affectionate part may be guarded against, which, if it creeps up in us,
may greatly hinder our service and right feeling for our Master,
as well as do hurt to His tender ones.

As I am not alone in my feelings,
I am the more encouraged thus in tenderness and sincerity to impart a word of caution,
and I much hope it will be taken in that true love in which it is penned.

L+++.+++ A. Barclay.

To a Young Friend.

Drumnadrochit, near Inverness, 16th of 9th Month, 1851.

My Dear +++_______+++,

Perhaps you will wonder into what outlandish place we are got, from the date of this.
I was so entirely overdone with the general meeting,
that we came to Inverness almost directly after it,
and a most fatiguing journey we had of 106 miles, in a small and greatly laden coach,
over a great part of Aberdeenshire, a very dreary and dull country,
reminding me in degree of Derbyshire,
but the latter part was through other more fertile counties,
where the difference of soil was very conspicuous, producing fine crops of wheat,
which Aberdeenshire does not; also fine trees, and hedges, and oaks too,
which are rarities in our part.
We stopped a night at an inn,
and then procured agreeable lodgings on the banks of the Ness, where we stayed two weeks.
My night`'s sleep is not fully restored yet,
which has made me feel tired and feeble by day,
and hindered my getting on as I could wish.
However, it was a pleasant sojourn, and as we were gazing-stocks to the people,
and spread also a great many tracts both in English and Gaelic,
I trust the sojourn there was not in vain.
We also found a poor solitary man who professes with Friends,
and who was delighted to see a little of kindred minds; so he met with us,
also occasionally an agreeable young woman,
whose brother is "`the high church`" preacher there,
and also came several times to see us.

We came on here last sixth day by the steamboat, along the famous Caledonian Canal,
landing by a little row-boat on the shores of Loch Ness, about one-third its length,
which is twenty-four miles long, and then we started for this place on foot;
but finding it too far for me, I mounted a little Highland cart, which took our luggage,
while C. walked with a kind fellow-passenger, dressed in the Highland costume,
who was very polite.
The above little carts are made of open work of lathes,
so that the foot or anything small might fall through
without care--they are made so for lightness,
and are drawn along these mountain roads by one small horse,
sometimes with a straw collar and a halter bridle!
This place is a straggling village,
scattered up hill and down hill for nearly two miles in a most beautiful glen,
said to be the most beautiful one in Scotland, called Glen Urquhart, pronounced Urquart.
We are at a cottage shop which is the post-office, a very simple lodging, without carpet,
and everything very rustic, but such extreme hospitality as we have never had before.
// lint-disable invalid-characters "æ"
We can hardly understand one another, as Gælic is generally spoken,
but all the people are so kind and obliging it is
quite striking to us both here and at Inverness.
I assure you we are greatly pleased with all these dear Highlanders,
// lint-disable invalid-characters "æ"
and they are so pleased with our Gælic tracts, that we sent for more from home,
and yet have not enough.

The country is far more beautiful than you can imagine
or I describe--we are out nearly all day.
Today we climbed up beside a beautiful burn, or water course,
whose banks were rocky and woody, the weeping birches so elegant,
and the woods varied by golden corn fields in every crook and corner which
the plough can reach;--we clambered across the burn at the top of it,
and then up a steep mountain,
from the top of which we had a lovely view all round the lake below surrounded by mountains,
except our valley or glen, and the glen dividing in two branches,
varied by hills in every direction like waves rising higher
to the mountains--the corn fields so richly laden,
some not cut, and others in sheaves, haycocks in others,
and green luxuriant turnips in others,
and a little river or stream running winding along.
After lying down on the soft turf for half an hour,
we were favoured to get safely down again, though so slippery and craggy,
and took our dinner at the side of the burn in the cool shade,
having the water murmuring at our side, where we filled our cup,
and afterwards washed our face and hands.
And then we passed all the afternoon a little further
eastward on the top of a craggy hill,
among fine rocks, having a sweet view of the lake, and valley,
and mountains--returning home to tea at half-past six.

Was not this making the most of a sweet day?
We longed for some of our southern friends to share such beauties with us.
I should have told you, as an instance of the genuine kindness of this people,
while we were sitting on the rocks in the afternoon,
a woman came out of a miserable looking cottage a little way off,
for they are scattered all about the glen in crooks and corners,
with a bowl of rich milk like cream to regale us, entirely spontaneously;
we were so glad of it, the sun being so hot.

And now, dear +++_______+++, it is near bed-time, so I must quiet myself for reading,
and remain, with dear love, your truly affectionate friend,

L+++.+++ A. Barclay.

To R. R.

Drumnadrochit, Inverness, 21st of 9th Month, 1851.

Recollecting it will be your quarterly meeting, I suppose this week,
and feeling you very near in spirit,
I take up my pen this evening to salute you in dear love, and to say how sweet it is,
up in this solitary yet lovely glen, as we sit on some craig,
or to use a Scotticism "`bonnie brae,`" to think of dear ones far away,
who perhaps may be remembering us at this very time,
and perhaps too may have been just now (seven in the evening), as we have been,
endeavouring to lift up the poor flagging soul heavenward,
to Him who knows the secret breathings and inmost sighs.
Well, dear R., there is consolation in Christ, there is comfort in the true love,
there is strengthening in the "`fellowship of the Spirit,`" and oh,
there is with our tender Father "`affection and mercy.`"
He pities the infirmities of His poor weak ones, whom He has given to desire to be His,
and when the poor body seems to clog the soul,
He is able to send help from His holy sanctuary.

L+++.+++ A. Barclay.

To +++_______+++

Drumnadrochit, 22nd of 9th Month, 1851.

Dear Friend,

I incline to salute you in love, by a few lines, and say you are not forgotten,
but your welfare every way sincerely desired.
And, my dear friend,
I long that earthly things and gettings may not eat out the best life,
which is far better than either clothing or food outwardly;
for what will it profit us if we gain the whole world
(or what the world calls good and desirable),
if the soul be lost, or the life of God in the soul?
I feel this little watchword, dear +++_______+++, for you both,
for now you have a dear little son to provide for.
It will be the enemy`'s snare to you both to labour for him and +++_______+++,
to care and be anxious for him,
and thus he (the enemy) will try by the lawful things to draw you away from minding
your inward condition and growth in grace by minding inward feelings.
Oh, this inwardness, this minding inward feelings, it is beyond all outward gettings;
and if our minds are rightly set heavenwards we may enjoy
it (the feeling after the Lord`'s presence and power secretly,
and the secret exclamations or aspirations that spring therefrom),
even when our hands and outward attention are engaged in measure,
we may feel that which poises and preserves us.
I am far from well, but desire to be resigned to the Lord`'s will.

Farewell.
With love truly to you both, from your friend,

L+++.+++ A. Barclay.

+++[+++The following is a postscript of the last letter addressed to Lydia A. Barclay,
by her departed friend, L. Chalk.]

Kingston, 24th of 9th Month, 1851.

I hope your late sojourn at Inverness, etc.,
will tend to recruit both body and mind after the season of trial you allude to.
When we look around, how much there seems to weigh down and cause sorrow and sadness!
Think not you are alone in this respect.
We have a large share here.
May the great Head of the Church be so near,
as to help and keep both you and us in our places,
when storms of persecution arise and threaten almost to overwhelm;
and very sweet it is to think that in His keeping we are safe, as it is written,
"`No weapon that is formed against you shall prosper;
and every tongue that shall rise against you in judgment you shall condemn.
This is the heritage of the servants of the Lord, and their righteousness is of me,
says the Lord.`"
The prospect of having my dear sister added to us here feels cheering, and very,
very comforting to me in my present feeble and uncertain health.
We hope to be so near each other as to hold daily interaction when desired.
If I have omitted to answer any part of your letter, please to excuse it.
Farewell.

L+++.+++ Chalk.

To W. H.

Aberdeen, 22nd of 10th Month, 1851.

My Dear Friend,

The true fellowship is like the healing balm and odoriferous cordial.
How excellent it is,
and strengthening and reviving and healing to the many wounds in the house of our friends,
which are now our portion!
And how precious to witness this true unity and love
extending over the mighty deep to distant lands!
Surely it is a beam from that same blessed light and life eternal
from which flows the Gospel love that ministers one unto another,
whether openly and vocally or secretly and silently, a blessing to us poor mortals.
Ah, my dear friend, I expect you, with us, will have to endure yet greater trials,
for these are but the beginning of sorrows.
I desire to be resigned to the Lord`'s will, whether life or death; and if I die,
I believe I may, in deep humility,
say it is in the faith once and still delivered to the saints.
And if yet detained here, oh, may I be preserved therein to the very end.

With dear love to you both, I am your true friend,

L+++.+++ A. Barclay

To +++_______+++

Aberdeen, 27th of 10th Month, 1851.

My Dear Friend,

I thought I would salute you in this way,
and assure you I am affectionately interested about
all your little company that meet at your house,
and desire that grace, mercy, and peace may grow and be multiplied among you;
and this I believe can only be as you individually are subjected to the grace,
accept the mercy, and allow the peace to rule in your hearts to the which you are called,
even of God and our Lord Jesus Christ.
I feel an earnest desire and concern upon me that you may not grow lax, or weary,
or lukewarm, in your sitting down together to wait for ability, heavenly ability,
to worship God in spirit and in truth,
for this is one of the enemy`'s devices to make you become so,
in order that he may rob you of spiritual good and hinder your progress heavenward.
But may you be stedfast in the Lord`'s counsel, immoveable in His fear,
and "`always abounding in the work of the Lord,`" in the waiting for His humbling power,
in the feeling after His strengthening grace,
"`forasmuch as you know that your labour is not in vain in the Lord.`"
And, dear friends,
remember it is by this individual faithful and persevering labour
that you will know a blessing to attend your little silent meetings,
and it is thus too that any one of you may,
by the further mighty working of the Divine power,
be raised up to testify of the Lord`'s goodness, and speak in His name or power;
therefore, see that you are not frustrating the Divine goodness to you,
by a lack of a deep inward exercise of mind, in your silent waiting.

L+++.+++ A. Barclay.

To +++_______+++

Aberdeen, 3rd of 11th Month, 1851.

My Dear Friend,

Your last letter of 26th of 9th month interested me greatly,
as I so well know all those parts you visited,
and the Friends who reside there--except that I suppose
+++_______+++ meeting would feel an altered one to me,
as several dear faithful Friends are departed to their heavenly rest since I was there.
How you would have prized dear +++_______+++, a true elder of the old school,
and one of the poor of the flock, though rich in faith!
How sweet and heavenly it was to sit beside her in meeting! it
seemed to help me on in my exercise (as all true elders will),
and was healing to my wounded spirit.
I did not know who she was, but felt such sweet union of spirit, that I,
on shaking hands with her, proposed to take tea with her,
and on entering her humble dwelling I felt that that was
the place where I ought to have lodged during my stay there,
and not at the rich man`'s, where my spirit was so oppressed and wounded,
that I could have said soon after I entered his house, with Peter Gardner of old,
"`My Master is not here, I`'ll not go in.`"

I had a sweet evening at +++_______+++`'s, and met there one or two seeking visited minds,
and I was reluctant to part; and when I went into the bedroom to put on my bonnet,
she said, with tears in her eyes,
that the anecdote I had been relating about J. B. (a dear
Cornish Friend) shutting up her shop to go to meetings,
had been an encouragement to her, for she felt she ought to do so, but had withheld,
fearing the loss, seeing that every shilling was needed,
but now she hoped she should be strengthened to be faithful--and she was,
till she was obliged, on account of her health, to give up shopkeeping.
She was one of my yearly meeting lodgers for four succeeding years after that,
and we loved her more every time we saw her; and she was faithful as an elder,
though a poor woman,
and I rejoiced that I had been the means of bringing
such a deeply exercised mind to the yearly meeting.
I often long to go and see how some of my dear friends get along, in a spiritual sense,
in those midland parts,
but I seem so poor and weak I fear to do hurt to the precious cause.

I find dear +++_______+++ has a few words to say in meetings now, which does not surprise me,
and I am glad of it; she has an exercised mind.
It must indeed be a comfort to dear +++_______+++ to have such a Friend
near her as +++_______+++,whom she must feel like a father.
Ah, my dear friend, there are too few now-a-days who refer to inward feeling,
as you remark of W. G.; it is these who are true fathers;
they would nourish up the younger Friends in the truth,
or the inward kingdom of the Saviour,
by encouraging them to a close attention to inward pointings and restraints.
But this way is everywhere evil spoken of, as was primitive Christianity of old.

I am your affectionate friend,

L+++.+++ A. Barclay.

To +++_______+++

Aberdeen, 4th of 11th Month, 1851.

My Dear Friend,

I was much pleased to receive your kind letter nearly two weeks ago.
I often think of you, especially on sitting down in our meeting here,
craving for the help of the ones, twos, and threes,
sincere-hearted seekers after heavenly good, wherever they may be scattered;
even that He whom they desire to love, serve, and humbly to worship,
may be pleased to overshadow them with His mighty tendering power,
bringing them down into true prostration and contrition before Him;
and that the Lord Jesus Christ, the great and unchangeable Minister, may be pleased,
after a most precious and immediate way, to minister to them and to teach them.
And, my dear friends, how often is this the case suddenly and when we least expect it,
when we feel so dry and empty and poverty-stricken, and think no good can come into us;
yet if we abide on the watch, resigned to be poor and empty,
yet waiting and wrestling in spirit for the blessing, and looking, as it were,
towards the holy temple--on a sudden, when we have toiled all night and found nothing,
the word may go forth,
"`Cast the net on the right side of the vessel,`"
and an abundant draught may be our happy portion.
So if we are brought into a low spot, let us be resigned to lie low before the Lord,
yet wrestling in faith and patience, and not casting away our confidence,
and we shall have a blessed recompense of reward.

In looking over your letter again,
I notice what you say about our "`erring in ordering our expressions.`"
I suppose you allude to expressions of sorrow or of gladness, etc., etc.
I think it very true, and I have often felt restricted from using the common expressions,
"`glad,`" or "`happy to hear,`" etc.
I think the word "`sorry`" conveys less to me than
"`sorrow,`" so I prefer using it or "`regret.`"
I am pleased you made the remark,
and I would encourage you to attend faithfully to these
little misgivings or secret intimations of duty,
even about such little things as words, for it is said,
"`that every idle word that men shall speak,
they shall give account thereof in the day of judgment.`"
"`For by your words you shall be justified,
and by your words you shall be condemned!`" that is,
if we feel that certain words are wrong and go on persisting to use them against conviction,
we shall be condemned!
I do believe that many in our poor society are not as faithful
in this respect as they ought to be to inward feelings,
and that this has brought on us the weakness and degeneracy
that so covers us--and that the way to know a revival among
us is for there to be an individual return to first principles,
to what we were at first convinced of,
and you may remember what John Crook says in that tract,
which I sent to +++_______+++ to lend you all three,
what a holy awe and dread was upon the spirits of Friends in the beginning,
lest they should be departing in their words from the pure testimony of truth,
or the Spirit of Christ, and this awe and fear kept them careful in their words,
having a bridle to their tongues! and I earnestly long to
follow the steps of those worthies and my dear ancestors,
though I am very sensible that I err sometimes through unwatchfulness.

I am pleased you see the danger of the snares I alluded to, for it is said,
"`surely in vain the net is spread in the sight of any bird;`" although
there may be circumstances which may have a controlling effect upon us,
over which we have no power,
yet if we are kept in a state of sensibility of seeing the snares that surround us,
and our own weak sides and easily besetting sins,
then we shall be stirred up to set a double watch,
and to seek the more after the Divine counteracting help that we may be preserved,
so that we shall avoid the snare, and even be favoured to gather strength in the proving!
So that I long for myself and for those I feel interested about,
that we may never grow callous or insensible and indifferent to our snares and weaknesses,
which come very imperceptibly over us, often by little and little,
but that we may ever be kept sensible and clear-sighted,
watching and craving after best help to season and preserve us!

I am glad you feel that a blessing has rested on your little meeting,
and I hope it will encourage you to persevere faithfully in the duty;
not growing weary in well-doing, and so hurrying over the time,
otherwise you may be robbed of the blessing attending the patient waiters on the Lord!
If the Divine power be with you,
you never need be ashamed of silent meetings--and
you know that it is by individual exercise of mind,
a turning in to the Divine gift of light and life, that this blessing shall be obtained.

This is all I feel at present to say.
I have no objection to your reading some of this to +++_______+++ and +++_______+++,
as it in some parts concerns you all.
With kind love to you all three, I am your sincere friend,

L+++.+++ A. Barclay.

To +++_______+++

Aberdeen, 18th of 11th Month, 1851.

My Dear +++_______+++,

I was so pleased to hear of your going to the quarterly meeting,
and hope you will be encouraged to try again, and trust all for the cause sake;
and may your hands be strengthened by the heavenly
might to work faithfully for the good Master,
in every good word and work that is secretly pointed out to you; for surely you are not,
as dear +++_______+++ said herself last third month,
to be mere idle spectators of the desolations in our poor church,
but to be up and doing your little best to repair them in the Lord`'s name or power,
remembering that the smooth stone of despised little David was
effectual thereby to the bringing down of the mighty giant,
opposer, and defier of Israel`'s God.
And, my dear ones,
do not forsake or neglect the seeking after the Lord`'s
humbling and quickening power from day to day,
that your souls may live, and living may praise the Lord.
For what, indeed, are earthly or outward things, however plausible they may appear,
and even may assume the appearance of duties almost,
compared with the increase and preservation of the Divine life in us,
whereby all we have and are are sanctified to the
Master`'s use and blessed to our truest enjoyment.

L+++.+++ A. Barclay

To +++_______+++ and +++_______+++

1st of 12th Month, 1851.

My Dear Friends,

It was in my heart yesterday to pen you a few lines to tell you how I felt,
in visiting you in your very nice new house.
I thought much of you as we rode home,
and I felt there are many snares for you in thus launching out afresh, as it were,
in a house that looks and is larger and more imposing in its aspect,
more luxurious and complete to gratify self,
and what danger of spiritual loss if those snares are fallen into;
and if we put ourselves in the way of those snares there is more fear for us,
as we cannot so trustfully hope for Divine help,
and the enemy will be tempting us to make excuses in extenuation of these things,
which the pure witness for truth in the secret of our hearts would find fault with;
and when the balance of the sanctuary, if faithfully consulted,
would pronounce us "`lacking,`" even lacking in an entire
love and serving of God in a true testimony for Him.

But, oh, my dear friends, regard not the enemy nor his persuasions, but say to him,
"`get behind me Satan, for you savour not the things that are of God,
but those that are of men.`"
And let your eye and your cry be the more mightily put up unto the Lord,
that He would both show you the snares and also help you against them,
and against the selfish nature on which the snares will work for your hurt.
"`Save me from myself,`" was my dear brother John`'s language mentioned in his memoir,
and I often think of it,
and that it is also the language of the sincere and
humble servant of the Lord of all ages,
who feels much in himself to resist and gainsay the pure testimony of Christ,
the holy truth, in the secret of his heart.
And such earnest breathings will not go unheeded,
nor will they be in vain as it regards preservation and strengthening
from the worldly spirit and the spirit of self-gratification.
And oh, how do I desire that these few lines of broken hints, in tender affection,
and I trust humble faithfulness,
may tend to stir up the pure mind in you thus to breathe and to
"`watch and be sober,`" and "`let your moderation appear unto all,
for the Lord is at hand,`" who "`will judge the secrets of all men`'s hearts,
according to what has been made known, and will reward according to our works.`"

I want you, dear friends,
to come more forward to the help of the Lord against the mighty,
and not to go more backward, or to so cripple your hands and weaken your minds,
as to hinder your help and usefulness in a right way to this little church hereaway.
For, truly,
we are in a low state and need all the help that faithful individuals can give us;
the bride, the true Church,
says "`Come,`" and the Lord`'s Spirit says "`Come,`" in the secret of every heart;
they that hear and are endeavouring to obey this call,
say "`Come,`" and help to bear the burdens and uphold the testimony; and oh,
that you may more and more be willing to come and
serve the Lord with full purpose of heart,
in true uprightness, watchfulness, and humble praise, and holy fear,
is the earnest desire of your exercised and affectionate friend,

L+++.+++ A. Barclay.

To +++_______+++

5th of 3rd Month, 1852.

I trust it will not be unacceptable again in my poor way to offer, as it were,
the sigh and tear of affectionate sympathy and heartfelt mourning; for truly,
while you lament the loss of a tender father in an outward relationship,
I do that of one whose fatherly counsel and tender encouragement
has been made very helpful to me in times of deep trial gone by,
and no doubt his loss will be greatly felt.

May we the more seek help from the Lord alone, who,
for the oppression of the poor and the sighing of the needy,
will arise in His own good time, and His words are truly pure and precious.
And though He see fitting to take from us those who have been as pillars and fellow-helpers,
yet His grace is all-sufficient for those who are left in suffering, and in weariness,
and in labour a little longer,
and He can raise up of the children to uphold the same blessed standard of truth,
so that one generation may praise His worthy name to another!

L+++.+++ A. Barclay.

To W. H., Jun.

Aberdeen, 22nd of 3rd Month, 1852.

My Dear Friend,

It appears to me that the friends of truth in one country should be open
and communicative with the friends of truth in another country,
seeing that they are deeply interested in the same blessed cause;
and what touches that seems, as it were, to touch the apple of their eye mutually.
And it is strengthening and animating to commune with one another by the way,
even though we be sad, and have to tell of mournful things,
provided always the Divine fear be before our eyes,
and our communing be in the remembrance of His good name or power;
and although it be sometimes necessary to mention
names in our description of what has occurred,
yet I believe there will be no lessening of the true love in so doing;
our love is to the person,
but our controversy is with the evil which the enemy of all righteousness raises in him.
I believe there may be a carrying of that prudence of a certain class, with you and us,
beyond the limits, or to the hurting of the true love.
But, perhaps, you feel differently; if so, do tell me, that I may be instructed.

You allude to the idolizing of our leaders.
It is too true, and among all sorts, even those who hold to the ancient way,
there is too much of a looking to and leaning on them,
instead of an individual faithfulness and deep exercise
to be guided aright in judgment for the truth,
and strengthened for the service thereof,
so that when the few who take an active part for the truth are removed,
it often makes me sad to think of the desolation.

The sense of coldness, barrenness, and almost deadness,
seems like a dispensation peculiarly permitted to some of us of late;
and my soul is ready to say, no matter how pinching the frost,
and great the darkness of the winter season,
if so be the life be but preserved in the root,
and the necessary purifications and humiliations accomplished.

Farewell.
Your sincere and affectionate friend,

L+++.+++ A. Barclay.

To +++_______+++

Aberdeen, 21st of 4th Month, 1852.

My Dear Friend,

Your kind and affecting letter surely deserved an earlier acknowledgment,
but I have been so much engaged since then with one thing or another,
and trials of various sorts have occupied my mind
that it is now five weeks since I received it,
which I am sorry for.
Your long account of your dear sister`'s end and
of her dear bereaved husband deeply interested me.
She was not one whom I had known much of in your family,
but I can feelingly sympathise with you in the vacuum that must now be left,
and in the instructive lesson that such a dispensation has administered to you all,
but especially +++_______+++,
and greatly desire that it may not soon be effaced from his memory and heart,
but that he may yield up his heart to the melting efficacy of the Divine Word,
however operating upon him,
for so will the good end be answered for which such affliction has,
in wisdom inscrutable and in tender mercy, been permitted.
I unite cordially with your remarks on purification,
and how one stroke after another is sent sometimes,
if possible to compel to a thorough yielding to the good hand of power and love, leaving,
as it were, no stone unturned,
that there may be a coming and a tasting how good
the Lord is to them that love Him above all.
What a mercy it is that He does not leave us to ourselves!

Every year strips us of some whom we have known or valued, and these strippings, I think,
come more and more home to us in instruction and warning the longer we live,
or the nearer we approach to the end of the race.
I have been and still am much tried by the illness of my eldest sister,
and I have passed three very, I might say intensely anxious days,
knowing not if all were over.
It is such a vast distance off,
I am not looking to attend the yearly meeting unless I am called up to my sister,
when I might have a slice of it, but I believe otherwise my place is at home.
With dear love to you both, I am your true friend,

L+++.+++ A. Barclay.

To Hannah Marsh

Moffat, Dumfriesshire, 15th of 5th Month, 1852.

+++[+++Describing her sister Susan`'s suffering illness, Lydia A. Barclay writes]--

However, in tender mercy, she lasted till next day,
and then both M. and E. witnessed the end, which was very peaceful and quiet.
She was remarkably sweet and patient throughout, and so very grateful to all,
quite aware of her state, and sensible to a few hours of her close,
often having the Scriptures read to her in the night, especially the thirty-fourth psalm,
her favourite one: in short, she has left a sweet savour behind her,
and her example will still, as it has often done, speak loudly to me and others.
She was buried at Leytonstone parish place,
where she had pointed out a spot likely to be her last resting-place,
next to the Buxton`'s family plot.
Most of the family attended, by which I gather that the females were allowed to go,
and +++_______+++ conducted it without formality.
I cannot describe the trial and blank it is to me, and to have been at this distance,
but mercy, tender and great, has been mingled with the bitter cup, both towards her,
her attendants, and me.
I wished to start and travel all night to get to her, at first hearing there was danger,
but my family urged me not, for indeed she was a very dear sister,
and I was greatly attached to her,
and she used to write regularly every fortnight to lessen, as she kindly said,
the vast distance between us.

How the attractions to the south are lessening! but I shall not forsake you,
my dear ancient friends.
Oh, may we seek to know a growth in the Truth and an increase in the fruitfulness thereof,
even to the end of our little time here,
that we may be guarded and preserved from every snare,
and supported under every conflict and trial yet remaining; and then surely,
while we live, we must and shall be full of praise to the Lord.
It is a favour to feel better, and I ride out each day on a pony here;
it is a beautiful country, and so retired and soothing to the mind.
Heavenly goodness is near to help and support; and oh,
that I may not cause an absence by lack of watchfulness unto prayer.

Farewell, very dearly; may the Lord preserve us purely to His praise!
My mind will be with you next week breathing for your help!

L+++.+++ A. Barclay.

To +++_______+++

Aberdeen, 27th of 5th Month, 1852.

My Beloved Friend,

We returned home on third day, and I have had your two kind sisterly epistles,
containing "`passages`" during yearly general meeting time.
How very kind it is of you thus to gratify me!
I am much obliged to you, and have never before been thus favoured by anyone.
It really seems to bring you so near to me, and though,
since I had the first account you sent,
I have been much occupied in going about and seeing many beauties,
yet there have been times when my mind has, remarkably to myself, been, as it were,
with you in a secret exercise and breathing,
more so than I have before witnessed in former deprivations from joining in the assembly.
I have indeed been imagining that you have had much to suffer and to deplore,
much to feel beneath the surface.

Things are sorrowfully ripening for a crisis; but why do I say sorrowfully?
Surely we may and must rejoice,
if way is gradually making for the furthering of the pure cause of truth,
even if it be through intense suffering to the servants thereof,
comparable to the fiery furnace heated seven times more than it is usually heated,
and even if it be preluded by such apparent desertions and strippings of outward helps,
as nature may shudder at the prospect of.
But never let us fear,
except for our own individual keeping close to the Divine gift of light and life;
let us cast the lot of faithfulness into the lap of the Divine power, and trust our all,
and all dear to us, yes, the cause most dear to us, in His hands,
whose power is infinite, and wisdom unerring, and love unfathomable,
and mercy everlasting.
I believe not a hair of the head shall be hurt of
the true and humble followers of the Lamb.

It is but very few who see through things, and they are diminishing,
either by drawing aside or by death.
Nevertheless,
"`the Lord knows them that are His;`" and He is turning His hand upon the little ones,
and raising up such whose eyes He is opening to see the deceptions of Babylon.
And oh, that they may keep close to His good hand,
to His Divine gift of light and life that never did nor will deceive.
There are some among us who are depending on instruments, leaning on man,
instead of dwelling inward and trusting in the Lord, and these are open to the deception,
if not mercifully preserved.

I was mercifully enabled in peace to leave Edinburgh the next day, and go to Moffat,
a quiet little-watering place among the mountains of the border country towards Carlisle,
where dear J. and H. H. came to us,
and we enjoyed a sort of feast of unity and sympathy and love,
which was truly strengthening, as well as cordial and reviving to us.
We took them to Glasgow to pass the First day, last week, and then, next day,
made an excursion up to the head of Loch Lomond,
and next day they went to the Falls of Clyde,
while we endeavoured to do what we had to do at Glasgow,
taking them up by an evening train at Lanark, and then went back to Moffat.
They very much enjoyed the Scottish beautiful scenery, and so did we,
and felt the better for the thorough change.

We left Moffat with much regret on seventh day last, and,
stopping a few hours at the Bridge of Allan,
that they might see the beauty of that sweet spot, we went on to Perth,
and passed First day there to satisfaction,
and I was glad of dear J. H.`'s help and exercise among the little company there,
in advising them for their good, so that it was a strength to my poor hands.
There are seven now who sit down together, and I hope, as it is more known,
that travellers will join them, provided they are of good example.
We made a pleasant excursion on second day, to see three wonderful natural objects,
called the Devil`'s Mill, the Rumbling Bridge, and the Cauldron Linn,
formed by the river Devon rushing over and into some fearful chasms and precipices,
well worth all visitors going to see,
the sides adorned with beautiful trees and verdure among the rocks.
We passed through the beautiful Glenfarg, a romantic glen of four miles;
also visited (and I sat beside) Loch Leven,
in an island on which Mary Queen of Scots was long confined.
It was forty-six miles there and back, and we were twelve hours out,
and returned to Perth much pleased, though very tired.
We parted very reluctantly with these dear friends there on third day morning,
they going to near Kendal, and we returned home,
I trust thankful for the help and refreshment we have been favoured with.

Now, I must say farewell.
From your much obliged and dearly affectionate friend,

L+++.+++ A. Barclay.

To +++_______+++

7th Month, 1852.

My Dear Friend,

I believe I cannot, in candour and faithfulness,
leave this place without just dropping you a few parting lines,
which may perhaps better relieve my mind, or convey the exercise of it on your behalf,
than a verbal communication can do; for I have often found,
since we have been acquainted, that I cannot rightly understand your way of reasoning,
neither can I express myself in a way for you to understand me in conversation.
It felt to me, last evening,
as if you shoved away what I wished to point out to your
weighty consideration in that passage from Isaac Penington,
namely, that it is not the owning of the light as it shone in the foregoing ages,
which will now commend any men to God,
but the knowing and being subject to the light of the present age.

This, I believe, applies equally to individuals as to churches, and therefore,
however a man may have been blessed with help from on high in the
use of such and such forms and ceremonies in former days,
God mercifully being, as Isaac Penington says,
"`pleased with the sincerity and simplicity of his heart,
and winking at what he erred in,`" yet if further
light goes forth from the Lord`'s Spirit to his soul,
causing him to see further into the purity and spirituality of the Gospel dispensation,
and he,
instead of following on to know more of the Lord
in the way of His further leadings and discoveries,
should shut his eyes from the light, hold back his heart from the Spirit,
and withdraw his shoulder from the yoke--the true simplicity
would wither in him and another thing begin to live in him,
and so he would settle upon the lees, and deadness would overgrow his performances,
and then he may become so darkened in vision as not
to be able to see what spirit he is of!

Now it was this great snare or danger that I wished
to point out to you for your guarding against it;
for I verily believe that the Lord calls you to come up higher,
and has made discoveries to you that you are unwilling to follow,
and are making various reasoning excuses against instead
of yielding to the gentle leadings of His holy hand,
in the simplicity and humility of a little child,
as was very manifest by the way in which you turned things off yesterday,
and which I believed would not give you true peace afterwards!
Oh, what a favour it would be if,
when the Lord`'s tender visitations in mercy should be neglected,
He would yet extend the hand of His judgments over us,
that so we may be enabled yet to sing of mercy and of judgment,
"`even to praise the Lord,
to walk in a perfect way and with a perfect heart,`" and truly
to experience Him to "`come in unto us`" with His overflowing peace!

L+++.+++ A. Barclay.

To +++_______+++

Stonehaven, 22nd of 7th Month, 1852.

My Dear Friend,

Your kind sympathy under my recent affliction was very acceptable.
Dear Susan was not a professing religious character,
but her sweet amiable conduct and Christian spirit, in many respects,
showed forth the hidden influence of the power of religion.
She was a sweet example to me of self-thoughtlessness,
and never thinking or speaking lesseningly of others
without something being held forth to their advantage.
I believe she had but little committed to her and endeavoured to act up to it,
and it is a comfort to believe we shall only be judged according to what we have had.
I seem to have a humble hope that it is well with her spirit,
through redeeming love and mercy.

And greatly shall I feel, and do I feel the prospect of going next month to London,
and not having her to go to!
My health was so affected by the anxiety about her,
that I thought it best to hasten away from home to Edinburgh,
where letters came in the morning instead of night,
and it was there I received the account of her death;
and although the general meeting came on,
I did not feel easy selfishly to give way to my sorrow,
and shut myself up from my friends, but was helped, like David, to wash and anoint,
and mingle with them, and it was a remarkable time of favour to me and to dear +++_______+++;
it seemed as if there was an unusual door of utterance
granted us little ones! praised be the great name.
Our aged friend, Anthony Wigham, was too ill to get there,
but wrote us an epistle which gave out a sweet and acceptable odour,
I thought like a box of precious ointment!

I much unite with your remarks on being disciplined, battered, and broken down.
How much of this disciplining and instructing we require, we are such poor scholars!
We are reading, with much enjoyment, Jaffray`'s diary, etc.; it is so excellent!
But the history makes us sad in beholding the difference
in this part to what it was in those bright days.
The same hardness and highness in professors at this time as then; but,
alas! among the professors of the blessed truth too much joining
and shaking hands with that spirit instead of leading out of it.
All things here are uncertain, but all is wisely ordered and tenderly permitted.

Believe me, with dear love, your affectionate and true friend,

L+++.+++ A. Barclay.

To +++_______+++

28 Victoria Street, Aberdeen, 10th of 8th Month, 1852.

My Dear Friend,

It is very long since I last heard anything of you, and I feel anxious to hear,
and I hope you will write a few lines.
+++_______+++ will doubtless give us facts when he comes
to our general meeting the end of this week,
but he will not give us feelings, which are better expressed by your kind pen,
at any little leisure you can find, and which I shall be pleased to receive.
I felt near sympathy with you under the trial of J.`'s illness,
but how great must have been your relief and comfort when she was so suddenly helped,
and I doubt not your grateful heart, as well as hers,
was lifted up in renewed praise to the Orderer of all things, and the Giver of all good,
and, I trust,
also was melted in renewed desire after love and
devotion to Him who had done for you great things,
in thus restoring your beloved partner; holy and reverend is His name,
and worthy of all our obedience, trust, worship, and thanksgiving!

I shall like to hear how your little meetings have felt of late,
and if you have had any strangers, Friends or others with you.
I hope +++_______+++ and +++_______+++ may come and see you some time in their way here or back;
but I remember the latter is likely to stay a while at Perth,
and hope it may be to your mutual comfort!
Those who love the truth--that is, the inward kingdom and power of the dear Saviour,
have always a good savour accompanying them,
which is a savour of life to those who are quickened unto life,
and a savour of death to those who are by disobedience bringing death upon themselves,
in a spiritual sense,
and what a leavening influence is felt with all with whom we associate,
therefore let us guard against a worldly leaven, and seek after a heavenly leaven; yes,
and also seek by obedience to what we know to be
so leavened into the Spirit of our dear Saviour,
whose food and drink it was to do the will of His Father,
as that we also may have a good leavening influence in all
our conduct and demeanour among those around us.

I am far from well, and life feels very uncertain, but in good hands!
I am expecting in about two or three weeks to go to the south of England,
to see my dear relatives and friends.
We shall be likely to stop a night at Perth in our way.
I do not expect that dear +++_______+++ will return back again with me from England;
I shall feel parting with her, but trust the Lord will sustain and strengthen us both,
and provide all things for us in an inward and outward sense, and oh,
that we may be preserved unto His heavenly kingdom, is the earnest desire of my soul!
And, dear friends, be sure you keep close to the pure gift and heavenly talent of light,
life, and grace in the secret of the heart, and walk in obedience thereto,
as well as be diligent in waiting thereon to be guided, taught, humbled,
and governed thereby;
and then there will be no doubt of your being true sheep
and faithful subjects of the heavenly King and blessed Shepherd,
at whose name every knee is to bow, and every tongue confess that He is Lord,
to the glory of God the Father!
With kind love to J. F., I remain your and your affectionate friend,

L+++.+++ A. Barclay.

+++[+++Journal Entry]
Aberdeen, 10th of 8th Month, 1852.--I feel free to leave it on record,
possibly for the sake of some dear relation or friend when I am gone, that,
on sitting down this evening in our little select meeting at A. W.`'s,
I felt sweetly gathered into a strengthening stillness,
in which I felt and afterwards had to express it.
How precious it is, in seasons of trial and temptation, of weakness and sorrow,
and it may be perhaps when the sense of solitude and of being as it were cast off,
pervades the mind, to know the Lord to be as a precious "`little sanctuary`" to us;^
footnote:[Ezekiel 11:16]
and not only to know it, but to be favoured to retire into His light, life, and power,
where we shall find comfort, quiet, and calm, support and succour in every time of need!
After which, the language of supplication ran through my mind in this way--O Lord,
be pleased to draw and subject me wholly to the Spirit of your dear Son,
that I may be in Him that is true; and then, oh may it please you, in your free grace,
to accept me in Him the Beloved; and then, after awhile, I was led,
in resignation to the Divine will, to look at the concern,
which I have several years felt, to have a public meeting for the factory girls here,
and if ought be required of me at the present time.
But I felt easy about it now,
and that perhaps the way may more clearly open for it in the winter,
with the caution renewed, not to be looking at this brother or the other sister,
but to look to and lean on the Lord Jesus Christ alone,
who can abundantly strengthen and qualify His poor weak handmaids
for whatever He may be pleased to require at their hands--blessed,
and praised, and confided in be His holy name forever!
Amen.

To B. B.

9th Month, 1852.

What a favour it is that we can commune together in spirit when separated in person; yes,
we can, as it were,
drink into the same blessed Holy Spirit from which comes all our springs of refreshment,
strength, and comfort!
It is a great comfort to me to visit my dear friends and take sweet counsel with them;
but I am continually reminded this is not our rest, we must look higher,
even to the Source of all good, and seek to be prepared for that happy home,
where there will be no more sorrow, weeping, or parting.
The low state of our society is deeply affecting, yet there is a remnant left,
and let us hope they may be preserved to stand in their lots to the end.
I feel as if I must commit all unto the Lord, those dear to me, and the precious cause,
for He can overrule all trials for our good.
However we as a society may be broken to pieces,
yet the precious truth shall outlive it all, and emerge out of the very ruins,
if it must come to that; for truth is stronger than all and shall prevail.
I cannot help hoping for a brighter day,
when the Lord shall have purged away the filth of the daughter of Zion,
when she may arise again and shine forth in primitive purity and brightness;
so let us wipe away our tears of sadness, and cast our burdens upon Him,
and He shall sustain and give us to praise His holy name.

L+++.+++ A. Barclay.

To +++_______+++

London, 18th of 9th Month, 1852.

My Dear Friend,

Having a little time here before the train for Dorking starts,
I thought I would pen you a few hasty lines,
to say I feel much your kind expressions towards me and wishing to see me.
I stayed a week at my sister Lucy`'s,
and then felt able to come to my two dear brothers`' houses at Leyton,
where I have passed ten days, and left this morning,
after having had an affecting interview in many respects;
and as each day seemed to bring a renewal of excitement, trials, and duties,
it seemed to bear down all I had gained by each night`'s rest.
Still I hope I am thankful to say I have been slowly gaining strength,
and have nearly lost the giddiness and swimming feeling in my head,
like being on board a ship, and which arises from great weakness.

I am on my way to spend tomorrow at Dorking,
and from there by Reigate to Wellingham for a few days,
till their quarterly meeting at Horsham, next fifth and sixth days;
and on the evening of the latter day,
I hope to go to dear John F. and Hannah Marsh`'s for a quiet rest of ten days,
so as to get fit to bear the long journey home again.
It is a very affecting journey altogether,
and seems to me like a last leave-taking to some,
and I feel especially to cling to the dear Marsh`'s, for Hannah Marsh is, I fear,
like myself, declining.
But I trust we may be helped in the quiet together--and
what is so healing and strengthening as true unity,
even to the poor body!
I don`'t know how to bear much talking, or turning rapidly from one subject to another,
and it will be a comfort to get to my snug home again, if so permitted.
I am obliged to give up some pleasant plans for stopping
and visiting several dear friends in my way home,
which is trying; but we must be willing and resigned to be turned over and over,
and even (like a poor beetle) right upon our back,
if so it seem good in the sight of Him who knows and does what is best.

If our dear John and Hannah Marsh like it,
it would be very pleasant to me if we four could dine here snugly
together on quarterly meeting day--would you like it?
It`'s a thought that just strikes me.
With dear love to you both, I remain your truly attached friend,

L+++.+++ A. Barclay.

To +++_______+++

Croydon, 7th of 10th Month, 1852.

My Dear Friend,

Dear John Harrison is no more!
A valiant soldier in the Lamb`'s army, and a faithful servant of the Church,
although in no station therein appointed.
Oh, I feel it an affliction indeed, although preparing for it ever since last 5th month,
when I urged his consulting a physician at Glasgow,
who pronounced it an incurable heart complaint.
He was a beloved brother indeed to me,
and his letters have been very animating and strengthening to me in my great solitude.
His last is a precious one, giving me an account of truth gaining the victory,
on the trying subject of grave-stones.
Oh, many of his letters have been very encouraging,
in showing how that one faithful friend, zealous for the truth,
though feeling a very little and a despised one, may be instrumental,
by a well-timed and seasoned few words,
so to help on other upright-hearted ones of lesser courage, though in station,
as that a wrong step may be frustrated through their means,
and the Lord have all the praise.
Let us go and do likewise what we can, says my soul.
I also heard yesterday of dear J. Dann of Reigate being sinking rather rapidly.

With dear love to G., I am your truly affectionate friend,

L+++.+++ A. Barclay.

To a Young Friend.

Aberdeen, 25th of 10th Month, 1852.

My Dear +++_______+++,

I have a very warm feeling towards you,
and grateful sense of your great kindness to me when with you,
and trust you will by no means lose your reward,
for it was much more than a cup of cold water.
I have very often thought and talked of you all,
and my sweet walks with your mother are very cheering and animating to look back on,
when we truly took sweet counsel together,
and endeavoured to encourage each other in faithfulness to the best of Masters.
And oh, my dear +++_______+++, that you may increasingly be devoted in heart and soul unto Him,
and you will find Him so,
and a rich Rewarder of the least little service you can do for His blessed cause,
for there is none that opens or shuts a door for nothing in His house.

I expect they are gone to join the quarterly meeting committee in visiting the meetings,
and my heart sympathises tenderly with them,
and desires their encouragement and strengthening,
for such visits must be attended with many trials and deep afflictions,
by reason of the devastations of the enemy,
who in various ways seeks to lead away from the Guide to true peace and blessedness;
and we read, because iniquity abounds, the love of many shall wax cold;
and this is painful to the true labourers,
to see a falling away from the true love to the precious cause of Christ.
But there is a precious little remnant,
and I long that our dear young people may come and join them,
who have not bowed the knee to Baal nor kissed his image; and these,
though but lightly esteemed of some, and hidden from many,
are known of and unto the Lord,
and He will confess and save them when He makes them His chosen jewels

// lint-disable invalid-characters "æ"
I have sent +++_______+++ near a pound weight of Gælic tracts,
for the emigrants from the Isle of Skye.
I am so pleased she thought of it; poor things! my heart goes with them.

Farewell, my dear; and in the flowings of tender and grateful love,
I remain your tenderly attached friend,

L+++.+++ A. Barclay.

To +++_______+++

Aberdeen, 6th of 11th Month, 1852.

My Dear +++_______+++,

Ah, how sweet is the influence that pervades the dwelling of those who are desiring,
in sincerity and uprightness of heart, to serve the Lord, the great King, yes,
the great King above all gods, or great men in other words!
Surely He only is to be supremely feared, loved, worshipped, and obeyed; to be honoured,
praised, and magnified over all;
for He gives us these inexpressible sweets of the true love and
unity which is beyond all the talk of words--a power and a life
inwardly felt that strengthens our hearts and hands,
and cheers our spirits, and confirms our faith and confidence in Him who is over all,
and therefore so preciously helps us on our often weary and tried way.
But why do I say weary and tried?
Because that the love of many for the ancient and
ever-living truth is too much waxing cold,
and the afflictions of Christ, in His mystical body the Church, do greatly abound.
Then I could and did greatly sympathise with your dear parents; but their reward is sure.
They who suffer with the dear Master shall certainly reign with Him.

Farewell, dear; and oh, that,
by believing and walking in the light of the Spirit of Christ,
you may be brought into and preserved in this blessed unity of the Spirit,
which is the bond of the King of kings and Lord of lord`'s peace,
uncomprehended of the world,
but known and preciously partaken of by the simple babes of the heavenly kingdom.
With dear love, I am your affectionate friend,

L+++.+++ A. Barclay.

To +++_______+++

Aberdeen, 16th of 11th Month, 1852.

My Dear Friend,

We are far too formal in our discipline:
what is given in the book of discipline on such outward
steps was never intended as a form always to be kept to,
but only as a specimen.
It reminds me of our Saviour`'s prayer,
which was only given as a specimen in what manner to pray,
becoming such a downright form among the generality of Christian professors,
as if because our praying is in those words it must always be right!
I have known an instance of a Friend and family,
who had been a cause of exercise and labour to the overseers,
and of exception to some of the queries being clearly answered,
having had an entirely clear certificate in the usual form, giving them on removing,
because it was thought proper to go in those words! and which I could
not help testifying against as not being in the spirit of our discipline.

I have seen many other such instances among us,
and I cannot but feel that we are fast verging on to the
fulfilment of dear Sarah Grubb`'s prophecy in 1820,
when she looked up into the upper gallery, where I sat then,
and bid the young people to note it down in their pocket-books.
She had been showing us how the enemy of all righteousness
had been laying and would lay snares for us,
in the various good looking and benevolent schemes that
were then or had lately been set afloat among us,
and that we should be so taken in them, and become so mingled with the world in them,
for lack of keeping close to the leadings and restraints
of the Spirit of Christ revealed within,
as to get mingled with the worldly spirit,
and by little and little almost imperceptibly should lose
our zeal and uprightness in the testimony of the truth,
and should begin to think there was no good in this thing or the other,
no use in this query or the other, until, by degrees,
our discipline once so excellently set up among us would utterly fall to the ground,
and we should become mingled with the spirit of,
and like the other various professors in the world!
I have been watching ever since the very gradual approach to the fulfilling of this;
and certainly,
when I see the leaders of this people joining hands with this creeping degeneracy,
some in their own conduct,
and others in letting fall such expressions before others as to
sanction a letting fall of our testimonies one by one,
it leads one to suppose that the end of these things is not very far off!

I was much struck with some remarks in a recent letter I had from a dear young man,
who is very faithful in yielding to inward feelings,
and on that account has sacrificed much in his business, in which,
after speaking of the low state of things in their meeting, goes on to say,
"`as Friends we are numerically small, and I fear we may yet become smaller,
for the younger members among us do not appear as plants growing up in their youth;
but my faith is firmer than ever,
that a blessing will descend upon the heads of those who
are jealous for the true reputation of our religious society.
One after another drops off; death and desertion thin our ranks,
and then is the time for those whose faith in the
power of truth is unshaken amidst the conflicts,
to close their ranks under the leadership of a Captain never yet foiled in battle!`"
He is quite a diffident one, and has never opened so to me before.

L+++.+++ A. Barclay.

To +++_______+++

I feel much and affectionately interested about the Friends at R. still;
my mind will be with them next First day.
Dear +++_______+++ greatly feels M. S.`'s death.
I shall be pleased to hear of any improvement in my late monthly meeting,
if your committee can report any.
I long for +++_______+++`'s help; had a nice letter from him, and have replied to it lately.
J+++.+++ H. is indeed solitary, but I am ready to think it has been blessed to him,
drawing Him closer to the alone Source of true help and comfort.
I have thought his letters have evinced this,
and also the pieces he has put into the British Friend show he is a true friend at heart;
he often sits alone at the meeting, and is truly conscientious in his business.
Ah, while I know the preciousness of that union and communion with one another,
that you allude to as so much lacking among us, I cannot but think that,
in these troublous times, it may be all for the best, and wisely so ordered,
that we are bereft of this blessing and cast solitarily in the land,
and it is consonant with "`the prudent keeping silence in that
day,`" and that it is good to sit alone and keep silence, etc.
And this reminds me, dear love,
of that sweet expression in dear John`'s letter to
+++_______+++ +++[+++after the words "`saved as by fire,`"]
there must be the overflowing scourge to pass through
"`when the refuge of lies is to be swept away,
and the sure foundation established and manifested, and when the Lord is about His work,
His strange work.

I am pleased you enjoyed dear +++_______+++`'s letter and have written to him;
I hope he will be guided in wisdom, and preserved in humility,
and strengthened in faithfulness and patience, in this engagement.
I expect he will not be received by many in +++_______+++. So they would fairly,
in their wrong estimation of the true love,
that all sorts and sects should be amalgamated together as Robert Barclay, the apologist,
so nobly deprecates.
Surely if George Fox had followed such a view,
he would never have been instrumental of gathering us as a people,
from the other professors of the Christian name,
who had so degenerated from the primitive simplicity and sincerity of the early reformers,
and sank down into lifeless formality.

Your kind expressions as to faithfulness I feel I don`'t deserve,
for I fear I am far from it.
I thought verily all ministry was taken away if ever I had any,
but today a few words sprang up which I ventured to utter;
but perhaps they were not in that line.
As to yearly meeting, I don`'t know anything about it; seem to be living a day at a time,
though it often seems like dragging on.
I desire to be found ready,
whether the heavenly summons be to yearly meeting or to the eternal world,
but how much is necessary before there be a fitness for the last!
I am feeling much about the seamen here,
wishing to get them a life-boat and apparatus for casting lines over a wreck,
with life-preserving belts complete, have had it on my mind all the winter,
and now I hope it will be accomplished in a few weeks`' time,
and I have written to my brother and S. Gurney to assist me with money.
+++_______+++ has very greatly helped me in this; she has so much boldness and self-confidence,
and unites with me in feeling for them;
she has several times been surrounded by a crowd of sailors down on the quay.
I am to visit the quay when the boat is near launching.

We are greatly enjoying George Fox;
how strikingly applicable is his remark about Scotland on his first visit here!
When will the great people come forth from this place?

My dear love to you.
Your true friend,

L+++.+++ A. Barclay.
